### ISSUE TITLE
Errors in your scoring file's init() function

### ISSUE THREAD

**Issue by diegoschapira** [Azure/MachineLearningNotebooks#100]
Hi, trying to deploy a simple text classifier model using sklearn tfidf and LinearSVC. Managed to register models, create environment file, create image but deployment fails, suggesting there might be an issue with the init() function. 

```
{'code': 'AciDeploymentFailed', 'message': 'Aci Deployment failed', 'details': [{'code': 'CrashLoopBackOff', 'message': "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance high-priority.\nYou can also try to run image highpriority7173083745.azurecr.io/high-priority:7 locally. Please refer to http://aka.ms/debugimage for more information."}]}
```
Tested score.py locally loading persisted model from local via joblib and returns predictions as expected so nothing seems wrong with the script or models. 

Any ideas?!

Here is the score.py code:

```
import pickle
import json
import numpy as np
import os
from sklearn.externals import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

from azureml.core.model import Model

def init():
    global model_1,model_2
    # get model path
    model_path1 = Model.get_model_path("tfidf_hp")
    model_path2 = Model.get_model_path("LinearSVC_hp")
    # deserialize the model file back into a sklearn model
    model_1,model_2 = joblib.load(model_path1), joblib.load(model_path2)


def run(raw_data):
    # make prediction
    data = json.loads(raw_data)['data']
    y_pred = model_2.predict(model_1.transform(data))
    return json.dumps({"prediction": y_pred.tolist()})

```

**Comment by rastala** [comment]
You can use service.get_logs() call to get more detailed log of what exactly failed.

**Comment by diegoschapira** [comment]
Thanks @rastala. Going through the logs seeing below error related to loading runs. For the time being I'm not using runs/experiments to record or log anything. Just Workspace and Model to deploy the service via ACI. 

```
azureml.core.run | DEBUG | Could not load run context Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run.,
```

Do I still need to start a run to create the service? If so, when should I start it and end it?

My script is as follows using the steps in your notebook:

Create Workspace >> Load models from local >> Register Models to ws >> Create Dependencies >> Deploy Image/Service.

Thanks for the prompt support. Working towards a tight deadline to deploy models and want to take advantage of azureml which seems straightforward but have not managed to make it work!

**Comment by rastala** [comment]
You don't need to submit a run to create web service. The "Failed to load a submitted run" is a red herring, the real error message is probably deeper down in the log. Look for errors coming from "driver_module.init()", for example:

"logger": "root", "message": "{\\"apiName\\": \\"\\", \\"message\\": \\"Encountered Exception Traceback (most recent call last):\\\\n  File \\\\\\"/var/azureml-app/aml_blueprint.py\\\\\\", line 109, in register\\\\n    main.init()\\\\n  File \\\\\\"/var/azureml-app/main.py\\\\\\", line 79, in init\\\\n    driver_module.init()\\\\n  File \\\\\\"pytorch_score.py\\\\\\", line 14, in init\\\\n    model_path = Model.get_model_path(\'pytorch-hymenoptera\')

**Comment by diegoschapira** [comment]
Here is the full log. Anything that jumps out?

2018-11-30 09:33:03,756 CRIT Supervisor running as root (no user in config file)
2018-11-30 09:33:03,759 INFO supervisord started with pid 1
2018-11-30 09:33:04,847 INFO spawned: 'rsyslog' with pid 7
2018-11-30 09:33:04,946 INFO spawned: 'program_exit' with pid 8
2018-11-30 09:33:04,948 INFO spawned: 'nginx' with pid 9
2018-11-30 09:33:04,949 INFO spawned: 'iot' with pid 10
2018-11-30 09:33:05,049 INFO spawned: 'gunicorn' with pid 11
2018-11-30 09:33:05,355 INFO success: iot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-11-30 09:33:05,852 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2018-11-30 09:33:06,401 INFO success: program_exit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-11-30 09:33:06,449 INFO exited: iot (exit status 1; expected)
2018-11-30 09:33:10,459 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "msg": "Starting gunicorn %s", "logger": "gunicorn.error", "message": "Starting gunicorn 19.6.0", "path": "/home/mmlspark/lib/conda/lib/python3.5/site-packages/gunicorn/glogging.py", "timestamp": "2018-11-30T09:33:14.552616Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "msg": "Listening at: %s (%s)", "logger": "gunicorn.error", "message": "Listening at: http://XXX.X.X.X:XXXX (11)", "path": "/home/mmlspark/lib/conda/lib/python3.5/site-packages/gunicorn/glogging.py", "timestamp": "2018-11-30T09:33:14.553914Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "msg": "Using worker: %s", "logger": "gunicorn.error", "message": "Using worker: sync", "path": "/home/mmlspark/lib/conda/lib/python3.5/site-packages/gunicorn/glogging.py", "timestamp": "2018-11-30T09:33:14.554300Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "logger": "gunicorn.error", "message": "worker timeout is set to 300", "path": "/home/mmlspark/lib/conda/lib/python3.5/site-packages/gunicorn/glogging.py", "timestamp": "2018-11-30T09:33:14.555227Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "msg": "Booting worker with pid: %s", "logger": "gunicorn.error", "message": "Booting worker with pid: 24", "path": "/home/mmlspark/lib/conda/lib/python3.5/site-packages/gunicorn/glogging.py", "timestamp": "2018-11-30T09:33:14.646916Z"}
Initializing logger
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "logger": "root", "message": "{\"message\": \"Starting up app insights client\", \"requestId\": \"00000000-0000-0000-0000-000000000000\", \"apiName\": \"\"}", "path": "/var/azureml-app/aml_logger.py", "timestamp": "2018-11-30T09:33:28.548366Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "logger": "root", "message": "{\"message\": \"Starting up request id generator\", \"requestId\": \"00000000-0000-0000-0000-000000000000\", \"apiName\": \"\"}", "path": "/var/azureml-app/aml_logger.py", "timestamp": "2018-11-30T09:33:28.548889Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "logger": "root", "message": "{\"message\": \"Starting up app insight hooks\", \"requestId\": \"00000000-0000-0000-0000-000000000000\", \"apiName\": \"\"}", "path": "/var/azureml-app/aml_logger.py", "timestamp": "2018-11-30T09:33:28.549175Z"}
{"host": "wk-caas-859542bda41b435e915a7bd32b986f32-9137f38e57d61f5e12a51e", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "stack_info": null, "level": "INFO", "logger": "root", "message": "{\"message\": \"Invoking user's init function\", \"requestId\": \"00000000-0000-0000-0000-000000000000\", \"apiName\": \"\"}", "path": "/var/azureml-app/aml_logger.py", "timestamp": "2018-11-30T09:33:28.549428Z"}
2018-11-30 09:33:28,550 | azureml.core.run | DEBUG | Could not load run context Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run., switching offline: False
2018-11-30 09:33:28,550 | azureml.core.run | DEBUG | Could not load the run context and allow_offline set to False
2018-11-30 09:33:28,551 | azureml.core.model | DEBUG | RunEnvironmentException: Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run.
2018-11-30 09:33:28,551 | azureml.core.model | DEBUG | version is None. Latest version is 1
2018-11-30 09:33:28,552 | azureml.core.model | DEBUG | Found model path at azureml-models/tfidf_hp/1/tfidf_hp_v2.joblib
2018-11-30 09:33:28,552 | azureml.core.run | DEBUG | Could not load run context Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run., switching offline: False
2018-11-30 09:33:28,553 | azureml.core.run | DEBUG | Could not load the run context and allow_offline set to False
2018-11-30 09:33:28,553 | azureml.core.model | DEBUG | RunEnvironmentException: Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run.
2018-11-30 09:33:28,553 | azureml.core.model | DEBUG | version is None. Latest version is 1
2018-11-30 09:33:28,554 | azureml.core.model | DEBUG | Found model path at azureml-models/LinearSVC_hp/1/clf_hp_v2.joblib

**Comment by diegoschapira** [comment]
Found out it was a issue with memory when creating the deployment. 4GB solved the issue.
