### ISSUE TITLE
Boolean choice breaks GridParameterSampling and BayesianParameterSampling

### ISSUE THREAD

**Issue by maxvfischer** [Azure/MachineLearningNotebooks#1000]
**SETUP**
- macOS Catalina v. 10.15.4
- Python 3.7.6
- azureml-automl-core==1.4.0
- azureml-core==1.4.0.post1
- azureml-dataprep==1.4.6
- azureml-dataprep-native==14.1.0
- azureml-mlflow==1.4.0
- azureml-pipeline==1.4.0
- azureml-pipeline-core==1.4.0
- azureml-pipeline-steps==1.4.0
- azureml-sdk==1.4.0
- azureml-telemetry==1.4.0
- azureml-train==1.4.0
- azureml-train-automl-client==1.4.0
- azureml-train-core==1.4.0
- azureml-train-restclients-hyperdrive==1.4.0

When instantiating GridParameterSampling with a parameter containing booleans, I get the following error message.

> \>\>\> params = {'test': choice(False, True)}
> \>\>\> GridParameterSampling(params)

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/max/anaconda3/envs/\<ANON ENV NAME\>/lib/python3.7/site-packages/azureml/train/hyperdrive/sampling.py", line 242, in __init__
>     distributions_validators=distributions_validators)
>   File "/Users/max/anaconda3/envs/\<ANON ENV NAME\>/lib/python3.7/site-packages/azureml/train/hyperdrive/sampling.py", line 82, in __init__
>     self._validate_supported_distributions()
>   File "/Users/max/anaconda3/envs/\<ANON ENV NAME\>/lib/python3.7/site-packages/azureml/train/hyperdrive/sampling.py", line 113, in _validate_supported_distributions
>     raise AzureMLException("Validation exception")
> azureml._common.exceptions.AzureMLException: AzureMLException:
> 	Message: Validation exception
> 	InnerException None
> 	ErrorResponse
> {
>     "error": {
>         "message": "Validation exception"
>     }
> }

A similar error message is shown when using BayesianParameterSampling:

> \>\>\> params = {'test': choice(False, True)}
> \>\>\> BayesianParameterSampling(params)

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/max/anaconda3/envs/\<ANON ENV NAME\>/lib/python3.7/site-packages/azureml/train/hyperdrive/sampling.py", line 300, in __init__
>     distributions_validators=distributions_validators)
>   File "/Users/max/anaconda3/envs/\<ANON ENV NAME\>/lib/python3.7/site-packages/azureml/train/hyperdrive/sampling.py", line 82, in __init__
>     self._validate_supported_distributions()
>   File "/Users/max/anaconda3/envs/\<ANON ENV NAME\>/lib/python3.7/site-packages/azureml/train/hyperdrive/sampling.py", line 113, in _validate_supported_distributions
>     raise AzureMLException("Validation exception")
> azureml._common.exceptions.AzureMLException: AzureMLException:
> 	Message: Validation exception
> 	InnerException None
> 	ErrorResponse
> {
>     "error": {
>         "message": "Validation exception"
>     }
> }

It seems to work fine when using RandomParameterSampling

> \>\>\> RandomParameterSampling(params)
> <azureml.train.hyperdrive.sampling.RandomParameterSampling object at 0x115e2dfd0>

**Comment by GiftA-MSFT** [comment]
@maxvfischer we will review your feedback and get back to you shrotly.

@swatig007 can you please review above feedback? Thanks.

**Comment by swatig007** [comment]
@nagau can you pls take a look?

**Comment by swatig007** [comment]
Hi @maxvfischer Choice parameter values should be 'int', 'string' or 'float'. Boolean is not supported. Can you please try resubmitting using 0/1 or string values?
