### ISSUE TITLE
AKS, can't deploy a model that reads and writes to DataStorage at scoring

### ISSUE THREAD

**Issue by Larleyt** [Azure/MachineLearningNotebooks#1001]
(First of all, sorry if this is the wrong repo for this issue. Seen something alike here.)
I have a model that detects something on an input image and outputs an image (so it is binary data and simple ModelDataCollector would not work here). I'm going to deploy it as AksWebservice. In `run()` function of `score.py` I need it to **read an image from a DataStorage** (or URL if reading from DS is not possible) and **write a new image to a DataStorage**. For now I've successfully deployed it as a LocalWebservice reading URL and writing to DataStorage. Here's the `score.py`:
```
def store_image(image_id, image_path):
    """Function for storing an image from a local filepath to a blob"""
    blob_client = blob_service_client.get_blob_client(
        container=IMAGE_STORAGE_CONTAINER_NAME, blob=image_id)
    with open(image_path, "rb") as data:
        blob_client.upload_blob(data)

def init():
    global model
    global blob_service_client
    blob_service_client = BlobServiceClient.from_connection_string(connect_str)
    try:
        container_client = blob_service_client.create_container(IMAGE_STORAGE_CONTAINER_NAME)
    except ResourceExistsError:
        print("Container already exists.")
    
    <other code related to model loading>

def run():
    <predict related code, generating output image_id>
    store_image(image_id, image_filepath)
```

As I said, it works perfectly when deployed as LocalWebservice, but not as AksWebservice – it's just deploying for 20 minutes and failing with the error:
```
ERROR - Service deployment polling reached non-successful terminal state, current service state: Transitioning
Operation ID: XXX More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "Timed out waiting for AKS deployment to complete. pollTimeout : 00:20:00 serviceName: XXX serviceId: XXX"
}
```

In `.get_logs()` all I can see is:
```
WebserviceException: WebserviceException:
	Message: Received bad response from Model Management Service:
Response Code: 400
Headers: {'Date': 'Tue, 09 Jun 2020 19:59:40 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=XXX', 'x-ms-client-request-id': XXX, 'x-ms-client-session-id': 'XXX', 'api-supported-versions': '1.0, 2018-03-01-preview, 2018-11-19', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"BadRequest","statusCode":400,"message":"The request is invalid.","details":[{"code":"KubernetesError","message":"container \\"XXX\\" in pod \\"XXX\\" is waiting to start: PodInitializing"}],"correlation":{"RequestId":"XXX"}}'
	InnerException None
	ErrorResponse 
```
And it is unclear to me if the error in `.get_logs()` is caused by timeout error or vice-versa.

In the docs I've read about Accessing Data During Scoring (https://docs.microsoft.com/en-us/azure/machine-learning/how-to-access-data#access-data-during-scoring). Does it say there's no way to use DataStorage while scoring except in Batch Prediction? If so, why? If not, why is it working as LocalWebservice and this timeout error happens on AKS? I don't need this whole Pipeline complications from Batch Prediction workflow, just to down/upload one or few binary objects while scoring. What are my options?

**Comment by ram-msft** [comment]
@Larleyt Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by Larleyt** [comment]
Is there any updates on this? @ram-msft

**Comment by Larleyt** [comment]
It turns out AKS deploy fails with the timeout if you try to create a Blob container in `score.py` (even inside `try-except` block). I've changed the code to get the existing container instead and it deployed ok. Not sure if it should fail this way on creation, though.
