### ISSUE TITLE
auto-ml-classification-bank-marketing-all-features.ipynb doesn't work

### ISSUE THREAD

**Issue by Sup90** [Azure/MachineLearningNotebooks#1002]
auto-ml-classification-bank-marketing-all-features.ipynb doesn't work at the "best_run_customized, fitted_model_customized = remote_run.get_output()" with this error.
![KakaoTalk_20200610_171212866](https://user-images.githubusercontent.com/30144765/84243744-9c307e80-ab3d-11ea-8272-94ccb3b45975.png)

i think because of xgboost version update

and same error occurred when i try to use auto ml best model as pickle.

**Comment by Sup90** [comment]
@AshokPeddakotla-MSFT  https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb

**Comment by swatig007** [comment]
@jialiu103 can you pls take a look at this notebook issue?

**Comment by arjsingh** [comment]
Hi @Sup90, I just attempted to reproduce the issue, but could not. Could you ensure that you're using the latest SDK version in the env that you may have installed before running this notebook?

Specifically, here's the correct version of xgboost: https://github.com/Azure/MachineLearningNotebooks/blob/a2a33c70a6aa428017aa723a1a9ab05e4c619826/how-to-use-azureml/automated-machine-learning/automl_env.yml#L15

Furthermore, you can leverage the documentation here for the setup:
https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning#setup-using-a-local-conda-environment

**Comment by deepakmukunthu** [comment]
@Sup90, I am closing this assume you are unblocked now. Please let us know if you have questions or need details.  thanks!

#please-close
