### ISSUE TITLE
Error when mounting FileDataset on AmlCompute: StreamAccessException was caused by ThrottlingException.

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/MachineLearningNotebooks#1007]
Hello all, 

I am submitting a training script, through a `ScriptRunConfig` and I have two FileDatasets mounted as_input.  These datasets contain around 10.000 images of an average size of 40Kb

This is the code I have:

```python
scriptargs = list()
dataset_names = ['ds-01', 'ds-02']
for ds in dataset_names:
    ds = 'my_dataset_name'
    scriptargs.append(ws.datasets[ds].as_named_input(ds).as_mount(path_on_compute = ds))

scriptargs.append('--epoch_count')
scriptargs.append(30)

scriptrunconfig = ScriptRunConfig(source_directory='./' + training_name, script="train.py", run_config=runconfig, arguments=scriptargs)
scriptrunconfig.run_config.target = compute_target
scriptrunconfig.run_config.environment = training_env

# Submit training
run = self.__experiment.submit(scriptrunconfig)
```

This is the error I get: 

> Error Code: ScriptExecution.StreamAccess.Throttling
Failed Step: 5d50e4e8-242a-4263-812a-6ccf16413b4c
Error Message: ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by ThrottlingException.
    Operation 'AzureBlob List' failed with '408: '. Cannot connect to storage service at 'Base path: https://xxx.blob.core.windows.net/, relative path: training/stages/charts/'. This could be caused by the server no longer responding due to load.
      The client could not finish the operation within specified timeout.
| session_id=065d956b-1c25-42cf-a9c1-3ae63bfca222

After retrying several time, it worked again.  So probably, it's a temporary issue, but my question is mostly if it's possible to prevent this from happening.

**Comment by kobulloc-MSFT** [comment]
@SamVanhoutte Which document does this refer to?

**Comment by SamVanhoutte** [comment]
@kobulloc-MSFT - this is not specifically related to a documentation issue or so.  but every time, I'm searching for the github project of AzureML, I end up in this project.  So maybe you could point me to the right location? 

Cheer

**Comment by kobulloc-MSFT** [comment]
@SamVanhoutte No worries!  That helps for tagging purposes.  From your error and the number of images that you are working with, I'm pretty sure what you are running into are throttling limits:

- Subscription and service limits: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits
- Throttling Requests: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling

Take a look through those as limits vary depending on your scenario.  That will allow you to set your script to work within the limits of the service that you are using.

I hope this helps!

**Comment by MayMSFT** [comment]
thanks Sam for the feedback. We will improve our documentation to list possible errors thrown by storage service and recommended actions
