### ISSUE TITLE
Typo: workflow provider

### ISSUE THREAD

**Issue by zoekdestep** [Azure/MachineLearningNotebooks#1009]
Typo: _wokflow_provider instead of _workflow_provider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda9da4c-0110-704c-5c62-72660f8ab324
* Version Independent ID: 154ae3b0-25a5-b727-358f-43586c47b2b0
* Content: [azureml.pipeline.steps.ModuleStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.modulestep?view=azure-ml-py&source=docs)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.ModuleStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.ModuleStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@zoekdestep Thanks for reporting this. We shall fix this typo in our upcoming doc update of the SDK

**Comment by vmagelo** [comment]
Addressed. Will go live with next SDK release in 1-2 weeks. Thanks.
