### ISSUE TITLE
Phishing URL

### ISSUE THREAD

**Issue by Fallenstedt** [Azure/MachineLearningNotebooks#101]
I am unsure if this is the correct repo to ask this question, however, I am new to Azure ML and was interested in downloading Azure Machine Learning Studio.

I googled Azure ML and this is one of the top url's that appear https://studio.azureml.net/

I believe this is a phishing url because of the URL does not appear to match microsoft's domain. I would expect this URL to appear instead https://azure.microsoft.com/en-us/free/services/machine-learning/?v=18.45

It's not a bug, but I believe someone is trying to obtain user credentials by posing as Azure ML.

**Comment by rastala** [comment]
https://studio.azureml.net is a legit shortcut to get to Azure ML Studio. 

For Studio questions specifically, you can use this forum: https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=MachineLearning

**Comment by j-martens** [comment]
Thanks for looking out for us @Fallenstedt 👍

**Comment by Fallenstedt** [comment]
Thank you. I just wanted to make sure. :100:
