### ISSUE TITLE
run.log* seems to have a limit of 3000b

### ISSUE THREAD

**Issue by norman-v** [Azure/MachineLearningNotebooks#1013]
EDIT: This has been edited as I have seen that the limit is on a per-call basis (on run.log_list at least) instead of a limit on the collective set of metrics in the run.

After adding a metric, I started getting the following non-terminating error when calling run.log_* commands.

azureml._restclient.exceptions.ServiceException: ServiceException:
	Code: 400
	Message: (ValidationError) Metric Document is too large, 3650b is larger than the max metric size 3000b.
	Details:
		Metric Document is too large, 3650b is larger than the max metric size 3000b.

3000b seems to be arbitrarily small especially if we are sending a larger list. Any workarounds outside of trying to break down the content of the list into multiple log* calls?

Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **jmartens**

**Comment by SnehaAgrawal-MSFT** [comment]
@norman-v Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by brunocous** [comment]
Is there any update on this or other workarounds?

**Comment by akarloff** [comment]
@brunocous The latest version of the SDK is not subject to the same 3000b limit. New limits can be found here: https://docs.microsoft.com/en-us/azure/machine-learning/resource-limits-quotas-capacity

**Comment by lostmygithubaccount** [comment]
hi @norman-v and @brunocous, please try upgrading to a newer version of the SDK which fixes this.

Closing out this issue, apologies for the slow responses. Please feel free to open a new issue if this or anything else is still blocking you.
