### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by saachigopal** [Azure/MachineLearningNotebooks#1018]
[Enter feedback here]
The 'managing environments' link under the 'from_existing_conda_environment(name, conda_environment_name)' header leads to a non-existent page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be571abf-9f4f-50f0-67df-140cadb5c916
* Version Independent ID: 4f9eb5f5-6844-b21d-6666-b5edac2f9981
* Content: [azureml.core.environment.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py#from-existing-conda-environment-name--conda-environment-name-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by SnehaAgrawal-MSFT** [comment]
@saachigopal Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YutongTie-MSFT** [comment]
@saachigopal Hi Saachi, this should work fine now. Please let us know if it's not working for you. 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
