### ISSUE TITLE
Bugs in upload_file() function

### ISSUE THREAD

**Issue by SparkSnail** [Azure/MachineLearningNotebooks#1020]
After I use run.upload_file() to upload a file to AML container from my local machine, I can check this file in AML's webportal, but I can not get the file from AML container.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run%28class%29?view=azure-ml-py#upload-file-name--path-or-stream-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by GiftA-MSFT** [comment]
@SparkSnail we will review your feedback and get back to you shortly. Thanks.

**Comment by SparkSnail** [comment]
![image](https://user-images.githubusercontent.com/22682999/85354195-9757cb80-b53c-11ea-8cc7-7ec66f5acfb8.png)
As you can see in this picture, I use a long-running process in container to monitor current folder, this process will run `pwd && ls`. Firstly I created a `file1` file in container's process, I can see this file in container output and webportal in the left side. Secondly, I call upload_file() or upload_folder() function to upload files to AML, as you can see I uploaded a `upload` folder, I can see this folder in the left side, but the container monitor process can not detect this `upload` folder. @danielsc @DebFro

**Comment by swinner95** [comment]
@SparkSnail to clarify, do you see hello.txt inside the container?

**Comment by paulshealy1** [comment]
Closing this issue with no response.
