### ISSUE TITLE
question about child run

### ISSUE THREAD

**Issue by SparkSnail** [Azure/MachineLearningNotebooks#1021]
Since one computer node in AML has many gpus, and I want to run multiple jobs in one run. If I use `submit_child()` in https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run%28class%29?view=azure-ml-py#submit-child-config--tags-none----kwargs-, I could start many child runs under a run, does these child runs share same computer node under the parent run?
If these child runs could not share same gpu, how can I run multiple jobs in one computer node?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run%28class%29?view=azure-ml-py#upload-file-name--path-or-stream-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by GiftA-MSFT** [comment]
@SparkSnail we will review your feedback and get back to you shortly. Thanks.

**Comment by lostmygithubaccount** [comment]
@GiftA-MSFT any updates?

**Comment by nishankgu** [comment]
you can either rightsize your node, to have 1 GPU per node (like using an NC6_v1 machine instead of an NC24_v1) machine. Or if you are running something like AutoML, there is a parameter in the AutoMLconfig to run multiple iterations on the same node.

**Comment by nishankgu** [comment]
https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py

AMLCompute cluster however supports running a single iteration only per node. Consider using a compute instance instead.
