### ISSUE TITLE
ScriptRunConfig() Documentation Doesn't Explicitly Call Out that the Entire Source Directory will be Uploaded

### ISSUE THREAD

**Issue by BreakingBI** [Azure/MachineLearningNotebooks#1023]
The ScriptRunConfig() function in the Python SDK (linked below), does not explicitly call out that that the entire source_directory will be uploaded as part of the Experiment Run.

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py

It's understandable why this is the case, but this could represent a serious security risk for a customer who accidentally uploads sensitive data as part of their experiment run.  This is even more serious because there doesn't appear to be a way to delete this data if this happens.

This effect is briefly hinted at in this article, but could be made much more visible and explicit.

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-save-write-experiment-files#where-to-save-input-files

The source_directory parameter also exists in a number of other functions, some of which I have linked below.

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-scikit-learn?view=azure-ml-py#create-a-scikit-learn-estimator

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-tensorflow?view=azure-ml-py#create-a-tensorflow-estimator

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-pytorch?view=azure-ml-py#create-a-pytorch-estimator
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109d9284-e234-5086-5da6-4155291361c8
* Version Independent ID: 57cc0c7a-faa7-1a86-ee14-b9cf99fb540d
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by BharathNimmala-MSFT** [comment]
@BreakingBI Thank you for your query, our team will look into it and get back to you at the earliest.

**Comment by RohitMungi-MSFT** [comment]
@danielsc Could we link this [article ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-save-write-experiment-files#storage-limits-of-experiment-snapshots) or mention to use the ignore files in the SDK documentation to avoid sensitive data being uploaded?
