### ISSUE TITLE
No dataset present for labeled-datasets.ipynb

### ISSUE THREAD

**Issue by mddiallo** [Azure/MachineLearningNotebooks#1024]
The dataset named 'crack_labels' is not present for the paragraph "Train an image classification model"

**Comment by RohitMungi-MSFT** [comment]
@mddiallo It would be great if you could let us know the documentation that you are referring to so we could check and fix the issue.

**Comment by mddiallo** [comment]
Hi,
I am refering to this notebook.
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/labeled-datasets/labeled-datasets.ipynb 
There is a reference to "cracks-labels" dataset. I don't see where it is coming from in the paragraph "Train an image classification model"
Thanks.

**Comment by RohitMungi-MSFT** [comment]
@mddiallo Thanks for the details. Yes, it looks like the reference to use crack_labels is not apparent in the notebook tutorial. @MayMSFT Could you please help how to check how we can add crack_labels dataset to the datastore?

**Comment by MayMSFT** [comment]
Hi @mddiallo  you need to create the labeled dataset from labeling service.
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-label-images
