### ISSUE TITLE
Getting Timeout error (after 30 to 45 min) during running "Test model on Azure Container Instance" steps

### ISSUE THREAD

**Issue by SUDEEPIOTTECH** [Azure/MachineLearningNotebooks#1025]
Hi Team, 

I am also getting Similar  error. Could you let me know, how I will solve the issue or whom I have to contact or any link where I will post / support link ?

from azureml.core.webservice import Webservice

aci_service_name = 'tempsensor-iotedge-ml-1'
print(aci_service_name)
aci_service = Webservice.deploy_from_image(deployment_config = aciconfig,
                                           image = image,
                                           name = aci_service_name,
                                           workspace = ws)
aci_service.wait_for_deployment(True)
print(aci_service.state)
tempsensor-iotedge-ml-2
Running...................................................................................................................................................................................................................................................................................................................................................................
TimedOut
ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
~/anaconda3_501/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    530                                           'Error:\n'
--> 531                                           '{}'.format(self.state, logs_response, error_response), logger=module_logger)
    532             print('{} service creation operation finished, operation "{}"'.format(self._webservice_type,

WebserviceException: WebserviceException:
        Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
        InnerException None
        ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}

During handling of the above exception, another exception occurred:

WebserviceException                       Traceback (most recent call last)
<ipython-input-30-48487f6bebba> in <module>
      7                                            name = aci_service_name,
      8                                            workspace = ws)
----> 9 aci_service.wait_for_deployment(True)
     10 print(aci_service.state)

~/anaconda3_501/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    538                                           'Current state is {}'.format(self.state), logger=module_logger)
    539             else:
--> 540                 raise WebserviceException(e.message, logger=module_logger)
    541 
    542     def _wait_for_operation_to_complete(self, show_output):

WebserviceException: WebserviceException:
        Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
        InnerException None
        ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}

Thanks and Regards,
Sudeep Kumar Patel

**Comment by ram-msft** [comment]
@SUDEEPIOTTECH Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by SUDEEPIOTTECH** [comment]
Hi Team,

I tired with latest GitHub code … Still same issue (timeout after 30-40 minutes  running).

+++
5: Test model on Azure Container Instance¶
You can test the performance of your model by deploying the container to ACI. Note that the service creation can take few minutes.

**from azureml.core.webservice import AciWebservice
​
aciconfig = AciWebservice.deploy_configuration(cpu_cores = 1, 
                                               memory_gb = 1, 
                                               tags = {'area': "iot", 'type': "classification"}, 
                                               description = 'IOT Edge anomaly detection demo')
from azureml.core.webservice import Webservice
​
aci_service_name = 'tempsensor-iotedge-ml-1'
print(aci_service_name)
aci_service = Webservice.deploy_from_image(deployment_config = aciconfig,
                                           image = image,
                                           name = aci_service_name,
                                           workspace = ws)
aci_service.wait_for_deployment(True)
print(aci_service.state)**
tempsensor-iotedge-ml-1
Running......................................................................................................................................................................................................................................................................................................................................................
TimedOut
ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
~/anaconda3_501/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    530                                           'Error:\n'
--> 531                                           '{}'.format(self.state, logs_response, error_response), logger=module_logger)
    532             print('{} service creation operation finished, operation "{}"'.format(self._webservice_type,

WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}

During handling of the above exception, another exception occurred:

WebserviceException                       Traceback (most recent call last)
<ipython-input-67-d238d2c10cb4> in <module>
      7                                            name = aci_service_name,
      8                                            workspace = ws)
----> 9 aci_service.wait_for_deployment(True)
     10 print(aci_service.state)

~/anaconda3_501/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    538                                           'Current state is {}'.format(self.state), logger=module_logger)
    539             else:
--> 540                 raise WebserviceException(e.message, logger=module_logger)
    541 
    542     def _wait_for_operation_to_complete(self, show_output):

WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}

**Comment by shivanissambare** [comment]
@SUDEEPIOTTECH are you still facing the issue?

if you are trying to deploy to aci, we have a great end to end example here : https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-to-cloud/model-register-and-deploy.ipynb

We have deprecated Image class and highly encourage our users to move away, start using environments and model class

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.container.containerimage?view=azure-ml-py

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.image(class)?view=azure-ml-py

**Comment by SUDEEPIOTTECH** [comment]
import pickle
import json
import pandas
import joblib                            !! Add this line
# from sklearn.externals import joblib   !! Delete this line
from sklearn.linear_model import Ridge
from azureml.core.model import Model

After comment **# from sklearn.externals import joblib** and new add **#import joblib** It's working fine.


Thanks All your support and replay inputs.

**Comment by SUDEEPIOTTECH** [comment]
After comment # from sklearn.externals import joblib and new add #import joblib It's working fine.

Thanks All your support and replay inputs.
