### ISSUE TITLE
object detection notebook not working ...

### ISSUE THREAD

**Issue by initmahesh** [Azure/MachineLearningNotebooks#1026]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/accelerated-models/accelerated-models-object-detection.ipynb

this notebook give 404 error :(

**Comment by GiftA-MSFT** [comment]
@initmahesh we will review your feedback and get back to you shortly.

@DebFro it seems this notebook has been moved. Can you please look into this issue? Thanks.

**Comment by vizhur** [comment]
Notebook has been removed, readme will be updated to resolve the broken links.
Sample is not supported at the moment, though you can access the old version that was tested with AzureML Python SDK 1.4.0 

https://github.com/Azure/MachineLearningNotebooks/tree/azureml-sdk-1.4.0/how-to-use-azureml/deployment/accelerated-models

**Comment by paledger** [comment]
The readme has been updated with the old links.
