### ISSUE TITLE
Found no resources for the input provided: 'https://pipelinedata.blob.core.chinacloudapi.cn/sampledata/batchscoring/images/'

### ISSUE THREAD

**Issue by XiaYuanxiang** [Azure/MachineLearningNotebooks#1029]
When I run machine-learning-pipelines-advanced/tutorial-pipeline-batch-scoring-classification.ipynb 

from azureml.core.dataset import Dataset
from azureml.pipeline.core import PipelineData

input_images = Dataset.File.from_files((batchscore_blob, "batchscoring/images/"))
label_ds = Dataset.File.from_files((batchscore_blob, "batchscoring/labels/"))
output_dir = PipelineData(name="scores", 
                          datastore=def_data_store, 
                          output_path_on_compute="batchscoring/results")

I got the error
ExecutionError: 
Error Code: ScriptExecution.StreamAccess.NotFound
Failed Step: f499d24c-d9b8-45d1-9cc3-e217247f11db
Error Message: ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: 'https://pipelinedata.blob.core.chinacloudapi.cn/sampledata/batchscoring/images/'
| session_id=7cd59092-00b4-43be-959a-ad94b70cb062

how should I solve this problem?

**Comment by RohitMungi-MSFT** [comment]
@XiaYuanxiang Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by shbijlan** [comment]
@XiaYuanxiang, I tried to reproduce the issue you are facing with the tutorial: machine-learning-pipelines-advanced/tutorial-pipeline-batch-scoring-classification.ipynb. I am unable to reproduce the error you see.

Can you check if you have made the input data available to your workspace correctly? I am able to run the code below without any issues.

from azureml.core.datastore import Datastore

batchscore_blob = Datastore.register_azure_blob_container(ws, 
                      datastore_name="images_datastore", 
                      container_name="sampledata", 
                      account_name="pipelinedata", 
                      overwrite=True)

def_data_store = ws.get_default_datastore()

from azureml.core.dataset import Dataset
from azureml.pipeline.core import PipelineData

input_images = Dataset.File.from_files((batchscore_blob, "batchscoring/images/"))
label_ds = Dataset.File.from_files((batchscore_blob, "batchscoring/labels/*.txt"))
output_dir = PipelineData(name="scores", 
                          datastore=def_data_store, 
                          output_path_on_compute="batchscoring/results")

**Comment by XiaYuanxiang** [comment]
Thanks for your reply, I have tried to use other dataset
