### ISSUE TITLE
Definition of "name"

### ISSUE THREAD

**Issue by ckcampbell248** [Azure/MachineLearningNotebooks#103]
Under deploy, deploy_from_model and deploy_from_image, you define "name" as "The name to give the deployed workspace". I think it should be "The name to give the deployed service."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf44bed6-8c8a-cc6b-4981-62011da8db48
* Version Independent ID: 0faf4700-36b9-a930-27c1-27d3085653af
* Content: [azureml.core.webservice.Webservice class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.webservice(class)?view=azure-ml-py#deploy-from-model-workspace--name--models--image-config--deployment-config-none--deployment-target-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.Webservice(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.Webservice(class).yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by akshaya-a** [comment]
Thanks, @ckcampbell248 we'll get that fixed in the next release!
