### ISSUE TITLE
Build_local() section typo

### ISSUE THREAD

**Issue by saachigopal** [Azure/MachineLearningNotebooks#1032]
[Enter feedback here]
The remarks under the build_local() method have a typo - they should say "To build a docker image set useDocker=True. To push a result image into AzureML workspace container registry after image build completion set pushImageToWorkspaceAcr=True"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be571abf-9f4f-50f0-67df-140cadb5c916
* Version Independent ID: 4f9eb5f5-6844-b21d-6666-b5edac2f9981
* Content: [azureml.core.environment.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by GiftA-MSFT** [comment]
@saachigopal we will review your feedback and get back to you shortly. Thanks.

**Comment by vizhur** [comment]
resolved
