### ISSUE TITLE
what datadrift baseline means？

### ISSUE THREAD

**Issue by XiaYuanxiang** [Azure/MachineLearningNotebooks#1033]
when I learn datadrift, 

I run   http://localhost:8892/notebooks/Projects/algothrim-pipeline/MachineLearningNotebooks-master/how-to-use-azureml/work-with-data/datadrift-tutorial/datadrift-tutorial.ipynb
and read doc https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-datasets

I was confused about the baseline dataset. The tutorial choose January 2019 weather data as baseline dataset,

`baseline = Dataset.Tabular.from_parquet_files(dstore.path('datadrift-data/2019/01/data.parquet'))`

but  there are many rows in the  datadrift-data/2019/01/data.parquet, which from 2019/01/01 to 2019/01/31, the question is, which row should be tread as the baseline? Or  just use the  mean value of those rows？

**Comment by SaurabhSharma-MSFT** [comment]
@XiaYuanxiang Thanks for your feedback! We will investigate and update as appropriate.

**Comment by kvijaykannan** [comment]
All the data (rows)  between these dates  2019/01/01 to 2019/01/31 will be considered as a baseline dataset.

**Comment by XiaYuanxiang** [comment]
> All the data (rows) between these dates 2019/01/01 to 2019/01/31 will be considered as a baseline dataset.

Thanks for your reply.  Then given dates 2019/02/01 to 2019/02/28 as a target dataset,  could you tell me how to calculate the datadrift？ sum( data(2019, 02,  x)  - baseline )，x vary from 01 to 28, is that right？

**Comment by kvijaykannan** [comment]
Thanks for getting back. We use a machine learning model (binary classifier) to compute the data drift. 

Sharing the below document link for more details on datadrift - 

[](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-datasets)

**Comment by XiaYuanxiang** [comment]
> Thanks for getting back. We use a machine learning model (binary classifier) to compute the data drift.
> 
> Sharing the below document link for more details on datadrift -
> https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-datasets

Thanks for your sharing. I have read the doc, but I'm still confusing about the ML model, could you explain it in more details?  you said it's a  binary classifier model, one class is baseline dataset,  then what the other class is?   I'm wondering if the model appropriate for our own datasets.
