### ISSUE TITLE
Unable to extend Parameter space from one HyperDriveRun to next

### ISSUE THREAD

**Issue by rd-bluebank** [Azure/MachineLearningNotebooks#1034]
I have a completed HyperDriveRun using BayesianParameterSampling. The optimal value for one of the parameters searched was at the upper bound of a uniform distribution. 

I would like to be able to use this run as the "resume_from" run with an extended distribution for this parameter, and the existing distribution for others. Without the ability to utilise the previous search results, the second HDR child runs are evaluating space I already know is sub-optimal, wasting compute time and energy

"HyperDriveConfigException: HyperDriveConfigException:
	Message: The parameter_space should be the same for all runs when using Bayesian sampling.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "The parameter_space should be the same for all runs when using Bayesian sampling."
    }
}
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e06f0efe-069e-b703-eb92-6e5832f0a0b2
* Version Independent ID: 58afae14-065b-f63d-c679-8def0afb54fd
* Content: [azureml.train.hyperdrive.BayesianParameterSampling class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.hyperdrive.bayesianparametersampling?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.BayesianParameterSampling.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.BayesianParameterSampling.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by swinner95** [comment]
@swatig007 can you take a look?

**Comment by swatig007** [comment]
hi @rd-bluebank, thanks for your feedback. When using the resume_from (warm start) capability, the hyperparameter space definition needs to stay the same across runs.  When warm starting a hyperparameter tuning experiment with Bayesian sampling, trials from the previous run will be used as prior knowledge to intelligently pick new samples, to improve the primary metric. However, the parameter space definition needs to stay the same.
