### ISSUE TITLE
Minor spelling: "reolace" in AutoML doc

### ISSUE THREAD

**Issue by justinormont** [Azure/MachineLearningNotebooks#1035]
Doc has "reolace" instead of "replace".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 012e5d35-c6c0-db5b-9c90-5cc9c511172a
* Version Independent ID: 19f73566-8938-edff-2ced-bffcce8bf8e6
* Content: [azureml.automl.runtime.data_transformation module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-automl-runtime/azureml.automl.runtime.data_transformation?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-automl-runtime/azureml.automl.runtime.data_transformation.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-runtime/azureml.automl.runtime.data_transformation.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by gaugup** [comment]
Thanks for reporting this issue. This is fixed now.

**Comment by justinormont** [comment]
Thanks @gaugup for the status update. Was the PR put into another repo? I don't see the change in two places yet [[1](https://docs.microsoft.com/en-us/python/api/azureml-automl-runtime/azureml.automl.runtime.data_transformation?view=azure-ml-py), [2](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-runtime/azureml.automl.runtime.data_transformation.yml)].

**Comment by gaugup** [comment]
This was fixed by an internal PR within Microsoft. There was a pypi release today and the if the docs are re-generated then this typo should be fixed. Else we would need to follow up with docs team to check why the docs aren't being updated..

**Comment by cartacioS** [comment]
Hi @justinormont seems the changes are in. Can you please confirm and close this issue if you agree? Thanks!

**Comment by justinormont** [comment]
Thanks for fixing!
