### ISSUE TITLE
Clarity around how resume_from works

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#1038]
There is no example of how to use this resume_from option of the HyperDriveConfig class, and one has to search the samples to find details of the fact there`s a new --resume_from argument that includes a path to the actual model. Can we document this to make it easier in the SDK documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7be45ce-baa1-ab0b-9c4a-8c64aab8131d
* Version Independent ID: 92eda8b3-b75c-69a3-11f0-ac1ec2fe4a87
* Content: [azureml.train.hyperdrive.HyperDriveConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.hyperdrive.hyperdriveconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.HyperDriveConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.HyperDriveConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by swatig007** [comment]
Hi omartin2010, Please refer to HyperDrive Warm Start documentation for details on how to use the resume_from parameter -
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-tune-hyperparameters#warm-start-your-hyperparameter-tuning-experiment-optional
Hope this helps.

**Comment by omartin2010** [comment]
It does help, thanks,. It would be great if we actually linked to that from the SDK docs... that's missing from this specific doc (and many others too would benefit from concrete examples - call them guides on how to use this particular class/function). Examples of what parameters mean exactly (short description + type isn't always very helpful).
