### ISSUE TITLE
Local Deployment with local conda package

### ISSUE THREAD

**Issue by thoo** [Azure/MachineLearningNotebooks#1039]
I am not sure how 'yml' file is utilized with conda environment. For local deployment , I have `environment.yml`  containing 
as 
```python
name: register-model-deploy-local
channels:
- defaults
- file:///mylocal/channel
dependencies:
- pip:
  - azureml-sdk
  - scikit-learn
```
But I got errors during the deployment saying `conda cannot access to my local channel ; 404 error` . I can search my local python package with `conda search -c file:////mylocal/channel myPackage` .  Is there anyway to get conda see a local channel? Thanks.

**Comment by swanderz** [comment]
As far as I'm aware this isn't possible, right @rastala?

Spitball ideas:
- roll package into a pip wheel and pass it directly to you environment definition
- host said package on Azure Artifacts and access via a `pip-index-url`?

**Comment by thoo** [comment]
The work around for me is just add the source directory when I add the `score.py` file.

**Comment by mjaow** [comment]
Sorry for late answer, you can't use local channels, because that's is the step we call package with all of your conda dependencies , it's finished in the server side, so it can't access the client's local file @thoo

**Comment by Bozhong68** [comment]
@mjaow for closing the loop! @thoo I will close the issue now, please feel free to re-open if you have any further questions.
