### ISSUE TITLE
Replace with "opaque box"

### ISSUE THREAD

**Issue by marktab** [Azure/MachineLearningNotebooks#1041]
Per https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/black-box

please replace with "opaque box"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32ef3eff-a772-e35a-5441-35e4901e14c2
* Version Independent ID: 3b1b8819-4aaf-ce33-5717-fea04d565813
* Content: [azureml.contrib.interpret.lime.lime_explainer module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-interpret/azureml.contrib.interpret.lime.lime_explainer?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-interpret/azureml.contrib.interpret.lime.lime_explainer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-interpret/azureml.contrib.interpret.lime.lime_explainer.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by minthigpen** [comment]
@marktab Thanks for your feedback! Microsoft is moving towards language that does not perpetuate systemic oppression. We will be following up with our team to update our documentation and terms.

**Comment by minthigpen** [comment]
Created a task to track this documentation item
#please-close
