### ISSUE TITLE
AzureMLCompute cluster gpu-cluster is in failed state and thus not ready for runs

### ISSUE THREAD

**Issue by canopusatl** [Azure/MachineLearningNotebooks#1043]
I am taking an plural sight ML course, thus I am a novice in ML, so pardon the below error if it seems so obvious. Am getting the below error when creating a pipeline - am working on the **Azure  Machine Learning Pipelines for batch prediction** inside JupyterLabs. When I click on **Run All Cells** everything passes up until the **Run the pipeline** section. I will appreciate your help on this.

 `
StepRunId: 8eea48cc-2827-4fa1-b8a1-07aff8caf305
Link to Azure Machine Learning Portal: https://ml.azure.com/experiments/batch_scoring/runs/8eea48cc-2827-4fa1-b8a1-07aff8caf305?wsid=/subscriptions/**i've_hidden_my_id_for_security_reasons**/resourcegroups/Training-For-ML/workspaces/training-ML-workspace
StepRun( batchscoring-202007091340 ) Status: NotStarted
StepRun( batchscoring-202007091340 ) Status: Running

StepRun(batchscoring-202007091340) Execution Summary
=====================================================
StepRun( batchscoring-202007091340 ) Status: Failed
---------------------------------------------------------------------------
ActivityFailedException                   Traceback (most recent call last)
<ipython-input-30-bbfe5cd3e101> in <module>
      4 pipeline = Pipeline(workspace=ws, steps=[batch_score_step])
      5 pipeline_run = Experiment(ws, "batch_scoring").submit(pipeline)
----> 6 pipeline_run.wait_for_completion(show_output=True)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in wait_for_completion(self, show_output, timeout_seconds, raise_on_error)
    293                             try:
    294                                 step_run.wait_for_completion(timeout_seconds=timeout_seconds - time_elapsed,
--> 295                                                              raise_on_error=raise_on_error)
    296                             except TypeError as e:
    297                                 # If there are package conflicts in the user's environment, the run rehydration

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in wait_for_completion(self, show_output, timeout_seconds, raise_on_error)
    735             try:
    736                 return self._stream_run_output(timeout_seconds=timeout_seconds,
--> 737                                                raise_on_error=raise_on_error)
    738             except KeyboardInterrupt:
    739                 error_message = "The output streaming for the run interrupted.\n" \

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in _stream_run_output(self, timeout_seconds, raise_on_error)
    823             print(json.dumps(error, indent=4))
    824         if error and raise_on_error:
--> 825             raise ActivityFailedException(error_details=json.dumps(error, indent=4))
    826 
    827         print(final_details)

ActivityFailedException: ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "AzureMLCompute cluster /subscriptions/**i've_hidden_my_id_for_security_reasons**/resourceGroups/Training-For-ML/providers/Microsoft.MachineLearningServices/workspaces/training-ML-workspace/computes/gpu-cluster is in failed state and thus not ready for runs.",
        "details": []
    },
    "correlation": {
        "operation": null,
        "request": "16f9db5c8bd7142d"
    },
    "environment": "eastus",
    "location": "eastus",
    "time": "2020-07-09T13:41:15.931217Z"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"AzureMLCompute cluster /subscriptions/**i've_hidden_my_id_for_security_reasons**/resourceGroups/Training-For-ML/providers/Microsoft.MachineLearningServices/workspaces/training-ML-workspace/computes/gpu-cluster is in failed state and thus not ready for runs.\",\n        \"details\": []\n    },\n    \"correlation\": {\n        \"operation\": null,\n        \"request\": \"16f9db5c8bd7142d\"\n    },\n    \"environment\": \"eastus\",\n    \"location\": \"eastus\",\n    \"time\": \"2020-07-09T13:41:15.931217Z\"\n}"
    }
}`

**Comment by canopusatl** [comment]
Good afternoon - any update or pointers on this?

**Comment by shbijlan** [comment]
@canopusatl are you still having this issue?

**Comment by lostmygithubaccount** [comment]
closing given no response for 3+ weeks

**Comment by LisiReips** [comment]
Hi, I have the same problem and I don't know how to solve it, did anyone get it?
