### ISSUE TITLE
KeyError: 'brand' when running an experiment using Azure automated machine learning SDK <1.8.0

### ISSUE THREAD

**Issue by wchill** [Azure/MachineLearningNotebooks#1044]
If a new environment was created after 10 June 2020 using SDK 1.7.0 or lower, training on local compute or an Azure Databricks customer may fail with the above error due to an update in the py-cpuinfo package. (Environments created on or before 10 June 2020 are unaffected, as well as experiments run on remote compute as cached training images are used.) To work around this issue, either of the two following steps can be taken:

1. Update the SDK version to 1.8.0 or higher (this will also downgrade py-cpuinfo to 5.0.0):
```bash
pip install --upgrade azureml-sdk[automl]
```

2. Downgrade the installed version of py-cpuinfo to 5.0.0:
```bash
pip install py-cpuinfo==5.0.0
```

**Comment by wchill** [comment]
@ram-msft can you label this issue appropriately and then close it? I've created this issue to make the fix a little more discoverable as a few users are still running into this.

**Comment by v-strudm-msft** [comment]
@wchill - Thanks for posting this info. #please-close
