### ISSUE TITLE
Please provide an example for using a private docker image

### ISSUE THREAD

**Issue by ryotatomioka** [Azure/MachineLearningNotebooks#1049]
The documentation says
> To use an image from a private docker repository, use the constructor's environment_definition parameter instead.

However I cannot find an example of environment definition using a docker image from a private repository. Could you provide such an example? For example, how can I authenticate with an Azure Container Registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db16bca-3797-0285-3ef2-99de84e4a0be
* Version Independent ID: cba716ef-395b-c8f9-2cbc-967bbc338c87
* Content: [azureml.train.estimator.Estimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.estimator?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by vizhur** [comment]
few examples here https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/using-environments/using-environments.ipynb

in [Environment ](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment%28class%29?view=azure-ml-py) object [docker ](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.dockersection?view=azure-ml-py) section specifies base image name and container registry details. If that's in your WS ACR you can just specify fully qualified name and AzureML will be able to auth you. If it's coming from other ACR, please set base_image_registry of [ContainerRegistry ](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.container_registry.containerregistry?view=azure-ml-py) type and specify the address. Username and password are required if User Identity is not set

**Comment by ryotatomioka** [comment]
Thanks @vizhur 

1. So from your message it sounds like there is an ACR for each Workspace? How can I access it? For example, how can I push an image to the registry?
2. Regarding your last comment about authenticating with other ACRs, I understand that username and password is an option but I think it is less ideal because we don't want to have a password in the code. Another option seems to be to set an "User Identity". How can I set an User Identity?

**Comment by vizhur** [comment]
from you workspace overview page you can navigate to registry
![image](https://user-images.githubusercontent.com/21002116/87308243-ef08a780-c4e8-11ea-8dfb-51c82cbae632.png)

if the base image in the same workspace, you do not need to provide username/password it will be resolved service side

**Comment by vizhur** [comment]
closing the issue
