### ISSUE TITLE
Cannot use sample to submit training script to local machine python environment

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/MachineLearningNotebooks#1053]
I used sample source in this docs page to submit training job to local machine. I am using current python environment (version 3.8.2 using `userManagedDependencies=True`) and not using conda environment. The experiment (named MyExperiment) is correctly created in my Azure ML workspace, run is also submitted, but `wait_for_completion` blocks for ever. Kindly see source and run output.

My training script contains only 1 line which is: `print ('hello world')`. _Also, even if I introduce a syntax error in training script (train.py), there is no impact to the below run_ 

**Source Code**
```python
import azureml.core
from azureml.core import Experiment, Environment, Workspace, ScriptRunConfig, RunConfiguration

workspace = Workspace.from_config()
print("SDK version:", azureml.core.VERSION)
print(workspace.name, workspace.resource_group, workspace.location, workspace.subscription_id)

# create or load an experiment
experiment = Experiment(workspace, "MyExperiment")

# By setting the user_managed_dependencies = True, the run uses the current python environment in your local machine
run_config = RunConfiguration()
run_config.environment.python.user_managed_dependencies = True

# run a trial from the train.py code in your current directory
config = ScriptRunConfig(source_directory='.', script='train.py', run_config=run_config)

print ("Experiment  Submit")
script_run = experiment.submit(config)

print ("Experiment  Wait for completion")
script_run.wait_for_completion(show_output=True) #this blocks for ever

print ("Experiment Complete")
```

**Output**
![run-output](https://user-images.githubusercontent.com/1491933/87320213-47bb5d00-c548-11ea-8204-1dfda3670c11.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109d9284-e234-5086-5da6-4155291361c8
* Version Independent ID: 57cc0c7a-faa7-1a86-ee14-b9cf99fb540d
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by tlby** [comment]
Hello future bug hunters!  This seems to happen when bootstapping the local job fails.  If you are reading this scratching your head, look in `/tmp/azureml_runs` for any breadcrumbs.  In my case a control_log.txt file showed that a python 2 interpreter was being given python 3 code and was fixed by making sure `python` on my path was a python 3 interpreter.
