### ISSUE TITLE
how-to-use-azureml/deployment/deploy-to-cloud/model-register-and-deploy.ipynb notebook does not deploy

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/MachineLearningNotebooks#1054]
I was trying to run model-register-and-deploy.ipynb ([link](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-to-cloud/model-register-and-deploy.ipynb)) inside a local jupyter notebook (azure ml sdk version 1.9.0). The model was created and sucessfully registered. But failed when I tried to deploy the model. Error screenshots attached. Requesting help.

1. Does the ACI computer cluster (in the Deploy model section) have to be created manually before deployment? If yes, that is not mentioned in notebook. Anyway, I also tried manually created ACI cluster. That also did not help.
2. It appeared the ACI `service_name` variable cannot be more than 16 characters. But even after I reduce it to below 16 chars, the error persists.
3. The `Model.deploy` does not have deployment_config pointed at ACI. Is that intentional?

Screenshot [1](https://user-images.githubusercontent.com/1491933/87416794-da153c80-c5ec-11ea-9457-5f0df5ec2d02.png)

Screenshot [2](https://user-images.githubusercontent.com/1491933/87416815-e0a3b400-c5ec-11ea-8d83-cd07e8375e4b.png)

**Comment by kartiez** [comment]
Please use

` ws.webservices['service-name'].get_logs()`

 to get the error details.

**Comment by thoo** [comment]
It looks like your path doesn't exist. Make sure you type your model path including `pkl` like 
` model_path = os.path.join(os.getenv('AZUREML_MODEL_DIR'), 'iris_model.pkl')` not just the name in `score.py`.

**Comment by kiranpradeep** [comment]
@jpe316 Why is this closed? It still does not deploy. Also I had raised 3 points which causes error. None of them are addressed.
