### ISSUE TITLE
LocalWebservice/Model.deploy() is pushing large docker images to cloud (also pulling same image again)

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/MachineLearningNotebooks#1055]
I was trying deploying on local web service using [register-model-deploy-local.ipynb](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-to-local/register-model-deploy-local.ipynb) notebook provided in this repository. The program works correctly. But from logs, it is noticed that, there are 5 steps

1. Pull mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20200423.v1 and follows a 15 steps docker build.
2. Push newly built image (from step 1) to ACR on cloud !
3. Again pull the newly pushed image (from step 2) from cloud to local machine !
4. Follows with 5 step docker build again based on the newly pulled image (which was same as output of step 1).
5. Start the final image as a docker service.

Question: Is there any option (e.g. a parameter to `LocalWebservice.deploy_configuration()/Model.deploy()` methods) with which I can skip step (2) and (3)? Why should local deployment needs to push image to cloud and then pull the same thing again. Both the push and pull consumes bandwidth and time.

**Comment by Bozhong68** [comment]
@kiranpradeep thanks for feedback. We have opened a work item to track this feedback for improvement.
