### ISSUE TITLE
Please define feature importances

### ISSUE THREAD

**Issue by vla6** [Azure/MachineLearningNotebooks#1060]
The documentation says the explain method returns "feature importances" but I would like more information about what these mean.   Are these SHAP values?  For a classification problem do these relate to the log odds or probability?  Are they relative to the mean training data values passed to the original explainer, which I guess is usually a tabular explainer?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f574001b-5906-caab-a273-1d16c6fabb32
* Version Independent ID: f187ccd2-5e48-5084-ade0-22532f8c17e8
* Content: [azureml.interpret.scoring.scoring_explainer.TreeScoringExplainer class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-interpret/azureml.interpret.scoring.scoring_explainer.treescoringexplainer?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-interpret/azureml.interpret.scoring.scoring_explainer.TreeScoringExplainer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-interpret/azureml.interpret.scoring.scoring_explainer.TreeScoringExplainer.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by minthigpen** [comment]
Thank you for your question! Yes, they are SHAPley values. Looping in @imatiach-msft who will be able to provide additional clarity on your other questions.

**Comment by imatiach-msft** [comment]
@vla6 thanks for the great question.  The feature importances are SHAP values of the TreeScoringExplainer.  These will be log-odds unless in the original explainer the user specified shap_values_output to be probabilities.
Hope this resolves the question, please feel free to reopen if you need more information.
