### ISSUE TITLE
How to obtain 'Pipeline' information using python sdk from an AutoML run

### ISSUE THREAD

**Issue by fwaris** [Azure/MachineLearningNotebooks#1062]
When I run an AutoML job, the widget shows the model algorithms used under the 'Pipeline' column as shown below:

![pipeline](https://user-images.githubusercontent.com/289968/87949523-1ffe5480-ca74-11ea-89df-0b416585d3e0.PNG)

However I am unable to find a why to retrieve the algorithm information from the AuoML run output.

I have explored the data returned by Model.list, run.get_metrics and run.get_details API calls and I can't seem to find the model algorithm information anywhere.

I would appreciate if you could show me how to retrieve the model algorithm information from the AutoML runs.

Thanks

Faisal

[Edit] I can obtain the above information for the "best run" model but I am also looking for similar information for the other models that were evaluated as part of the run

**Comment by ahyerman** [comment]
Hi Faisal,

`get_output()` is able to select a parameter `iteration` which will help you here. You can use the following code snippet to view every model:
```python
# retrieve all AutoML children
n_iters = len(automl_run.get_children())
# iterate through the AutoML children and get their models
for i in range(0, n_iters):
    child, model = automl_run.get_output(iteration=i)
    print('{}: {}'.format(child.id, model)
```

**Comment by temiwale88** [comment]
Hello, in line with getting outputs from a pipeline. I'm having issues following the pattern in this [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb):
```
best_run, fitted_model = remote_run.get_output()
```

This notebook uses AutoML without a pipeline strategy.
How do I retrieve the best_run from a pipeline run?

Thanks,
Elijah

**Comment by temiwale88** [comment]
Thank you God! Got it so nevermind. 
For those who might want to use AutoML in an AutoMLStep of your experiment pipleine - to retrieve the AutoML details e.g.  your "best_run" and "fitted_model" - try the following: 

- Find your AutoMLStep by its name e.g.
```
step_run = pipeline_run.find_step_run("AutoML_Step")[0] #whatever you called your Pipeline Run e.g. "pipeline_run"
```
- Then declare a variable that inherits the AutoMLRun class and its associated properties e.g. ".get_output()":
```
from azureml.train.automl.run import AutoMLRun

autoMlStepRunId = step_run.id

experiment_run = ws.experiments[<'your experiment name'>] #requires your workspace details passed to 'ws' variable.
automl_step_run = AutoMLRun(experiment_run, run_id = autoMlStepRunId)
automl_step_run
```

And you should be able to proceed from there.
All the best!
