### ISSUE TITLE
max_request_wait_time parameter

### ISSUE THREAD

**Issue by robert4os** [Azure/MachineLearningNotebooks#1065]
When enabling queuing by using replica_max_concurrent_requests > 1 ...the related parameter max_request_wait_time seems to have no effect.

What is the status of queuing in AKS in general, is this officially supported?

Thank you and best regards, Robert

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c5068c-bf75-51ea-a8b3-a3356ba81b5c
* Version Independent ID: 9036f1f0-f669-bb28-74e7-3ea8dae6d7e9
* Content: [azureml.core.webservice.AksWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.akswebservice?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AksWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AksWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by DmitryKakurin** [comment]
`replica_max_concurrent_requests` allows informing AML request router (only for AKS) that the deployed model can process multiple requests in parallel without loss of performance. It’s **not** for queuing of requests on the replica, which we work hard to avoid for perf reasons (to reduce latency).

If queueing of requests is desired, a much more efficient request queueing is implemented on the AML request router itself. Max queue wait time can be controlled either by specifying `max_queue_wait_ms` setting during service deployment (default is `500ms`), or even individually per-request by specifying `x-max-queue-wait-ms` HTTP header.

**Comment by Bozhong68** [comment]
Hey @robert4os, thanks for the question. I will close the issue now, please feel free to re-open if necessary.
