### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.ensemble._forest. Worker exiting

### ISSUE THREAD

**Issue by kartiez** [Azure/MachineLearningNotebooks#1066]
I'm getting this error while deploying a Random Forest model. 

I have deployed other random forest models in Azure AKS & ACI, But this one is not getting deployed. After my hours of troubleshooting, I found the issue is with the model, because changing just the model name to a previously trained model works.

It's trained using the same method, just the data that changed!

Any guesses?

Please help!

**Comment by kartiez** [comment]
I fixed it, 
It was due to sklearn verison mismatch. 

Also, it's same as #https://github.com/Azure/MachineLearningNotebooks/issues/1066

**Comment by Saaraavaanaa** [comment]
can you say how to check version of sklearn
