### ISSUE TITLE
Missing documentation to deprecated forecasting parameters

### ISSUE THREAD

**Issue by robert4os** [Azure/MachineLearningNotebooks#1067]
Hi,

I am receiving the deprecate warnings, but the documentation is not reflecting these changes.

e.g.
WARNING - Forecasting parameter country_or_region will be deprecated in the future, please use holiday_country instead.
WARNING - Forecasting parameter max_horizon will be deprecated in the future, please use forecast_horizon instead.
WARNING - Forecasting parameter grain_column_names will be deprecated in the future, please use time_series_id_column_names

Thank you and best regards,
Robert

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by cartacioS** [comment]
Hello,

Thanks for your comment! I have updated all the AutoML documentation to refer to the new forecasting parameter names. The updates should be live within 1 or 2 days at most. Please feel free to close now, or when you see the changes reflected.

Thanks,
Sabina

**Comment by cartacioS** [comment]
Hey @robert4os  just a ping that the documentation is live now: 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast

**Comment by CESARDELATORRE** [comment]
#please-close this issue since the doc is already available.
