### ISSUE TITLE
We should add some hint for Dataset class document.

### ISSUE THREAD

**Issue by UncooleBen** [Azure/MachineLearningNotebooks#1068]
I noticed that creating a `Dataset` with `Dataset.Tabular.from_delimited_files` method (possibly many other factory shortcuts)  only exposes new APIs, i.e. `AbstractDataset`'s methods, to the user. Calling these methods can be confusing. Users might believe that they're calling the deprecated ones since they are using methods directly reachable from the `Dataset` class to construct the objects. Especially when there are multiple methods with the same names but different parameters in both versions. In my case this was `Dataset.register`. It took me hours and dozens of argument combinations only to find out that I was calling a new API with the seemingly old object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b905f15-6470-b8cf-0963-efb5c16a848d
* Version Independent ID: 02bcf9a3-057d-b4e4-3f6d-acbe8a689ba8
* Content: [azureml.core.dataset.Dataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by MayMSFT** [comment]
Thanks for your feedback. We added notes and redirection page to get users on the right page here: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py

For register method, we also have redirection link on the notes. 
![image](https://user-images.githubusercontent.com/47834041/88696403-14381100-d0b8-11ea-8e1f-9e4a40b30c3e.png)

Do you have other suggestion to make the page clearer?
