### ISSUE TITLE
Unclear documentation on AzureCliAuthentication

### ISSUE THREAD

**Issue by prapanw** [Azure/MachineLearningNotebooks#1069]
It is absolutely unclear where you want the user to run 'az login' and how it is associated with AzureCliAuthentication object. I have been trying to simply run a published pipeline. I already have an endpoint and it has now taken more than 4 hours to investigate this even though we have article/documentation around this: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-your-first-pipeline#run-a-published-pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e1418f-261c-0e99-a980-45dd4a3e8af7
* Version Independent ID: 4c830a5d-9e6a-9d37-1592-b580fc976bd6
* Content: [azureml.core.authentication.AzureCliAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.azurecliauthentication?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.AzureCliAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.AzureCliAuthentication.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by mx-iao** [comment]
@johnwu0604 @jpe316 please take a look

**Comment by shbijlan** [comment]
@prapanw Thank you for your feedback. We are investigating how to improve documentation for this. 

Does the documentation on Azure CLI address your task?
https://docs.microsoft.com/en-us/azure/machine-learning/reference-azure-machine-learning-cli#ml-pipeline-management
