### ISSUE TITLE
Submit child run with HyperDriveConfig failed

### ISSUE THREAD

**Issue by stevenluda** [Azure/MachineLearningNotebooks#1071]
Is submit_child method able to accept HyperDriveConfig?

I got the following error when submitting a HyperDriveConfig:
Traceback (most recent call last):
  File "hyper_tuning.py", line 145, in <module>
    run.submit_child(hyperdrive_run_config)
  File "/azureml-envs/azureml_1fa689a622c520f6bf39101e973af28a/lib/python3.6/site-packages/azureml/core/run.py", line 586, in submit_child
    return self.experiment.submit(config, tags=tags, _parent_run_id=self.id, **kwargs)
  File "/azureml-envs/azureml_1fa689a622c520f6bf39101e973af28a/lib/python3.6/site-packages/azureml/core/experiment.py", line 211, in submit
    run = submit_func(config, self.workspace, self.name, **kwargs)
  File "/azureml-envs/azureml_1fa689a622c520f6bf39101e973af28a/lib/python3.6/site-packages/azureml/train/hyperdrive/_search.py", line 151, in search
    "HyperDrive run {}".format(str(e)), inner_exception=e) from None
UserScriptException: UserScriptException:
	Message: Exception occurred while creating the HyperDrive run User token validation failed: The specified alg value is not allowed
	InnerException TrainingException:
	Message: Exception occurred while creating the HyperDrive run User token validation failed: The specified alg value is not allowed
	InnerException User token validation failed: The specified alg value is not allowed
	ErrorResponse 
{
    "error": {
        "message": "Exception occurred while creating the HyperDrive run User token validation failed: The specified alg value is not allowed"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Exception occurred while creating the HyperDrive run User token validation failed: The specified alg value is not allowed"
    }
}

Any workaround to submit a HyperDriveConfig as child run?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by swatig007** [comment]
Hi @stevenluda,
In order to submit a HyperDrive run, you would need to submit a run (not a child run) using the config.
e.g. hyperdrive_run = experiment.submit(hyperdrive_run_config)

More details on how to submit a run with a HyperDrive config at https://docs.microsoft.com/en-us/azure/machine-learning/how-to-tune-hyperparameters#submit-experiment

hope this helps
