### ISSUE TITLE
Ways to parameterize hyperparameter sampling space as PipelineParameter

### ISSUE THREAD

**Issue by stevenluda** [Azure/MachineLearningNotebooks#1072]
Currently, the HyperDriveStep receives a HyperDriveConfig, but we can't find a way to make the hyperparameter_sampling in HyperDriveConfig accepting PipelineParameter. Is there any solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c38a69-084f-2185-60b2-b5bdedd45c65
* Version Independent ID: d9d1234e-c713-ba08-fb19-b9874a356a5a
* Content: [azureml.pipeline.steps.HyperDriveStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.hyperdrivestep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.HyperDriveStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.HyperDriveStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by swatig007** [comment]
HI @stevenluda , are you looking for a way to pass a Pipeline run to the HyperDriveConfig (so that each hyperparmeter configuration explored a different Pipeline)? if so, you could pass the Pipeline parameter to the HyperDriveConfig as callled out in -
https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.hyperdrive.hyperdriverunconfig?view=azure-ml-py

**Comment by stevenluda** [comment]
No, I have a HyperDriveStep in pipeline, and I want to the sampling space
to be dynamically defined by PipelineParameter.

**Comment by swatig007** [comment]
@stevenluda can you please share an example of a pipeline parameter you are trying to use? and how the parameter space would dynamically be defined?

**Comment by swatig007** [comment]
closing this issue since there's no response for 2 weeks. Please reopen if needed.
