### ISSUE TITLE
Code snippets in Remarks section not formatted correctly

### ISSUE THREAD

**Issue by yangsiyu007** [Azure/MachineLearningNotebooks#1073]
In the Remarks section of `as_named_input()` (https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py#as-named-input-name-), the two code snippets are not formatted correctly. There's a sentence that should not be a part of the code snippet in the first one, and extra ``` in the second one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06be0567-a5f7-21d0-6dac-8edeefe68980
* Version Independent ID: 4c06aaf8-fce2-6df2-0386-51a7472957fb
* Content: [azureml.data.abstract_dataset.AbstractDataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py#as-named-input-name-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.abstract_dataset.AbstractDataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.abstract_dataset.AbstractDataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by MayMSFT** [comment]
Thank you for the feedback. We will track it as bug in our documentation and fix in the next few SDK release

**Comment by lostmygithubaccount** [comment]
@MayMSFT has this been fixed?

**Comment by MayMSFT** [comment]
we did the investigation but it's a bug in documentation generation instead of our source code.

**Comment by meyetman** [comment]
This has been fixed! Thanks! #please-close
