### ISSUE TITLE
monitor schedule failed

### ISSUE THREAD

**Issue by XiaYuanxiang** [Azure/MachineLearningNotebooks#1075]
I am trying datadrift example on MachineLearningNotebooks-master/how-to-use-azureml/work-with-data/datadrift-tutorial/datadrift-tutorial.ipynb
when I run monitor.enable_schedule()  I got the error
"
Current state: Enabling
...State transitioning failed, please try again. status: EnableFailed
"
I have tried many times, but still got this problem, how should I sovle this?

**Comment by MayMSFT** [comment]
sorry for the late reply.
Which region is your machine learning workspace in? and which SDK version are you using? can you also share the drift id for us to investigate? You can find drift id from the monitor object. Thanks!

![image](https://user-images.githubusercontent.com/47834041/91219125-02558800-e6cf-11ea-8f37-808aa4db189e.png)

**Comment by lostmygithubaccount** [comment]
closing pending response - feel free to reopen
