### ISSUE TITLE
Cant install azureml-sdk with automl

### ISSUE THREAD

**Issue by sebastianfastert** [Azure/MachineLearningNotebooks#1076]
I'm trying to setup a docker image for development.
This Dockerfile is a minimal example for my problem
```
FROM python:3.8

WORKDIR /jup

RUN pip install --upgrade setuptools
RUN pip install jupyterlab
RUN pip install azureml-sdk[automl]

EXPOSE 8888

ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]
```

But when running `docker build . -t jupyter`.
I get the error:
```
ERROR: Could not find a version that satisfies the requirement nimbusml==1.7.1 (from azureml-automl-runtime~=1.10.0->azureml-train-automl~=1.10.0; extra == "automl"->azureml-sdk[automl]) (from versions: 1.8.0)
ERROR: No matching distribution found for nimbusml==1.7.1 (from azureml-automl-runtime~=1.10.0->azureml-train-automl~=1.10.0; extra == "automl"->azureml-sdk[automl])
```

Thanks a lot for your help!

**Comment by vizhur** [comment]
@sebastianfastert 

AzureML AutoML does not support python 3.8 at the moment. The reason for that is missing py38 dependencies like nimbus from your error https://pypi.org/project/nimbusml/1.7.1/#files. 
We are working on python 3.8 support and will ship it soon.

Please consider to use python 3.7 for now.
