### ISSUE TITLE
Classes and methods are confused

### ISSUE THREAD

**Issue by robert4os** [Azure/MachineLearningNotebooks#1080]
Classes and methods are confused in this article.

E.g. in "working directly with their corresponding factory methods TabularDatasetFactory and FileDatasetFactory"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed683fb5-825c-23fa-ad73-02432e9ba89e
* Version Independent ID: a45ba4d2-5789-5b99-3780-85c320baf1ab
* Content: [azureml.core.Dataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset%28class%29?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Dataset(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Dataset(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by SturgeonMi** [comment]
Thanks for the feedback! We are looking into this.

**Comment by MayMSFT** [comment]
Thanks for your feedback. What are you trying to do here? Have you checked out the article that introduce dataset and how to create them? 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets

**Comment by robert4os** [comment]
Hi,

I am just pointing out that the documentation uses the terms 'methods' and
'classes' in an imprecise way. Like in the text quote in my initial post it
should say 'factory classes' or 'factory methods of Tabular...'.

Best regards, Robert

**Comment by MayMSFT** [comment]
thanks for the feedback. we will follow up with doc update

**Comment by meyetman** [comment]
This has been updated. #please-close
