### ISSUE TITLE
Indicate that there is a GA version for this class 

### ISSUE THREAD

**Issue by robert4os** [Azure/MachineLearningNotebooks#1082]
Please indicate in the documentation when there is a GA version corresponding to a class from the 'contrib' package.
i.e. in this case azureml.pipeline.steps.ParallelRunStep   

This is also true for ParallelRunConfig and likely for other classes in the contrib package.

This is especially important, because the search function does not rank GA classes higher and so GA classes do not even show up in the top results. e.g.:

![prs](https://user-images.githubusercontent.com/1668298/89273479-e1ee5c80-d63f-11ea-9d80-5f8dfe20c5c3.jpg)

(The search result does not make the user aware that there might be a GA version of these classes.)

Thank you and best regards, Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 661da595-2113-82e0-6834-ac3366ec06e1
* Version Independent ID: dca619fe-b8b7-6c13-1dec-6a312bbc8f7a
* Content: [azureml.contrib.pipeline.steps.ParallelRunStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.parallelrunstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.ParallelRunStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.ParallelRunStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by junshi356** [comment]
Hi! I am the engineer of Docs.ApiBrowser service. Just want to remind that if you want to update ApiBrowser index of **Python/Javascript/Java/Powershell**, please kindly send us (Me juns@microsoft.com or Osmond) emails to contact us. Otherwise the index will stay still since they are not already supported by automated re-index feature in ApiBrowser yet. :)

**Comment by harneetvirk** [comment]
After re-indexing, the issue seems to be mitigated. Now, we can see GA classes first and then contrib classes.
![image](https://user-images.githubusercontent.com/20194110/91514418-97a57780-e89b-11ea-9d63-8ec4338022f9.png)

**Comment by shivanissambare** [comment]
@tracychms tracy can we please close the issue, since the reference doc bug is resolved.
thanks!
