### ISSUE TITLE
Feature Request : Better integration with Prometheus

### ISSUE THREAD

**Issue by thoo** [Azure/MachineLearningNotebooks#1083]
I saw the docker image has installed prometheus client for python. It would be really helpful to have a better integration like the endpoint from the web service tied to Prometheus.

**Comment by jpe316** [comment]
Hey @thoo - we'd love to hear more about your scenario.
Are you wanting to expose metrics from a deployed model?

**Comment by thoo** [comment]
@jpe316 Thanks. I would like to see there is an endpoint like `localhost/metrics` for Prometheus and anyone can write any metrics on `score.py` with prometheus python client. Currently in [bentoml](https://github.com/bentoml/BentoML), I can just write the following code and the metric will be there at `localhost/metrics` .  I would also like to have response time, response total and other usual metrics for API call. 
```python
from prometheus_client import Counter
c = Counter('myValue', 'Description of counter')
c.inc()     # Increment by 1
c.inc(1.6)  # Increment by given value
```

**Comment by Bozhong68** [comment]
Hey @thoo - thanks for suggestion. We have opened a new work item to track this request, and will include it in our next planning and release process.

**Comment by Bozhong68** [comment]
#please-close
