### ISSUE TITLE
SSLCertVerificationError during Model Register Operation

### ISSUE THREAD

**Issue by aliasneo1** [Azure/MachineLearningNotebooks#1084]
I'm getting SSLCertVerificationError while registering pretrained  model in local.

from azureml.core.model import Model
model = Model.register(model_path = "./models",
                       model_name = "BART-MNLI",
                       description = "BART Zero shot classifier",
                       workspace = ws)

Error trace:
ClientRequestError                        Traceback (most recent call last)
<ipython-input-34-20d397ce0af2> in <module>
      2 # Tip: When model_path is set to a directory, you can use the child_paths parameter to include
      3 #      only some of the files from the directory
----> 4 model = Model.register(model_path = "./models",
      5                        model_name = "BART-MNLI",
      6                        description = "BART Zero shot classifier",

~\Anaconda3\lib\site-packages\azureml\core\model.py in register(workspace, model_path, model_name, tags, properties, description, datasets, model_framework, model_framework_version, child_paths, sample_input_dataset, sample_output_dataset, resource_configuration)
    570         Model._validate_model_path(model_path, child_paths)
    571 
--> 572         asset = Model._create_asset(workspace.service_context, model_path, model_name, child_paths)
    573         asset_id = asset.id
    574 

~\Anaconda3\lib\site-packages\azureml\core\model.py in _create_asset(workspace_service_context, model_path, model_name, child_paths)
    615         # Register the artifact prefix as the model asset.
    616         prefix_values = [{'prefix': artifacts_path}]
--> 617         asset = asset_client.create_asset(model_name, prefix_values, None)
    618 
    619         return asset

~\Anaconda3\lib\site-packages\azureml\_restclient\assets_client.py in create_asset(self, model_name, artifact_values, metadata_dict, project_id, run_id, tags, properties, asset_type)
     53                       type=asset_type)
     54 
---> 55         return self._execute_with_workspace_arguments(self._client.assets.create, asset)
     56 
     57     def get_asset_by_id(self, asset_id):

~\Anaconda3\lib\site-packages\azureml\_restclient\workspace_client.py in _execute_with_workspace_arguments(self, func, *args, **kwargs)
     68 
     69     def _execute_with_workspace_arguments(self, func, *args, **kwargs):
---> 70         return self._execute_with_arguments(func, copy.deepcopy(self._workspace_arguments), *args, **kwargs)
     71 
     72     def _execute_with_arguments(self, func, args_list, *args, **kwargs):

~\Anaconda3\lib\site-packages\azureml\_restclient\workspace_client.py in _execute_with_arguments(self, func, args_list, *args, **kwargs)
     84                 return self._call_paginated_api(func, *args_list, **kwargs)
     85             else:
---> 86                 return self._call_api(func, *args_list, **kwargs)
     87         except ErrorResponseException as e:
     88             raise ServiceException(e)

~\Anaconda3\lib\site-packages\azureml\_restclient\clientbase.py in _call_api(self, func, *args, **kwargs)
    230                 return AsyncTask(future, _ident=ident, _parent_logger=self._logger)
    231             else:
--> 232                 return self._execute_with_base_arguments(func, *args, **kwargs)
    233 
    234     def _call_paginated_api(self, func, *args, **kwargs):

~\Anaconda3\lib\site-packages\azureml\_restclient\clientbase.py in _execute_with_base_arguments(self, func, *args, **kwargs)
    318         back_off = self.backoff_factor
    319         total_retry = 0 if self.retries < 0 else self.retries
--> 320         return ClientBase._execute_func_internal(
    321             back_off, total_retry, self._logger, func, _noop_reset, *args, **kwargs)
    322 

~\Anaconda3\lib\site-packages\azureml\_restclient\clientbase.py in _execute_func_internal(cls, back_off, total_retry, logger, func, reset_func, *args, **kwargs)
    334                 return func(*args, **kwargs)
    335             except Exception as error:
--> 336                 left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
    337 
    338             reset_func(*args, **kwargs)  # reset_func is expected to undo any side effects from a failed func call.

~\Anaconda3\lib\site-packages\azureml\_restclient\clientbase.py in _handle_retry(cls, back_off, left_retry, total_retry, error, logger, func)
    385                 raise error
    386         elif not isinstance(error, RETRY_EXCEPTIONS):
--> 387             raise error
    388 
    389         delay = back_off * 2 ** (total_retry - left_retry)

~\Anaconda3\lib\site-packages\azureml\_restclient\clientbase.py in _execute_func_internal(cls, back_off, total_retry, logger, func, reset_func, *args, **kwargs)
    332         while left_retry >= 0:
    333             try:
--> 334                 return func(*args, **kwargs)
    335             except Exception as error:
    336                 left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)

~\Anaconda3\lib\site-packages\azureml\_restclient\operations\assets_operations.py in create(self, subscription_id, resource_group, workspace, body, custom_headers, raw, **operation_config)
     83         # Construct and send request
     84         request = self._client.post(url, query_parameters)
---> 85         response = self._client.send(
     86             request, header_parameters, body_content, stream=False, **operation_config)
     87 

~\Anaconda3\lib\site-packages\msrest\service_client.py in send(self, request, headers, content, **kwargs)
    334         kwargs.setdefault('stream', True)
    335         try:
--> 336             pipeline_response = self.config.pipeline.run(request, **kwargs)
    337             # There is too much thing that expects this method to return a "requests.Response"
    338             # to break it in a compatible release.

~\Anaconda3\lib\site-packages\msrest\pipeline\__init__.py in run(self, request, **kwargs)
    195         pipeline_request = Request(request, context)  # type: Request[HTTPRequestType]
    196         first_node = self._impl_policies[0] if self._impl_policies else self._sender
--> 197         return first_node.send(pipeline_request, **kwargs)  # type: ignore
    198 
    199 class HTTPSender(AbstractContextManager, ABC, Generic[HTTPRequestType, HTTPResponseType]):

~\Anaconda3\lib\site-packages\msrest\pipeline\__init__.py in send(self, request, **kwargs)
    148         self._policy.on_request(request, **kwargs)
    149         try:
--> 150             response = self.next.send(request, **kwargs)
    151         except Exception:
    152             if not self._policy.on_exception(request, **kwargs):

~\Anaconda3\lib\site-packages\msrest\pipeline\requests.py in send(self, request, **kwargs)
     70         try:
     71             try:
---> 72                 return self.next.send(request, **kwargs)
     73             except (oauth2.rfc6749.errors.InvalidGrantError,
     74                     oauth2.rfc6749.errors.TokenExpiredError) as err:

~\Anaconda3\lib\site-packages\msrest\pipeline\requests.py in send(self, request, **kwargs)
    135 
    136         try:
--> 137             return self.next.send(request, **kwargs)
    138         finally:
    139             if old_max_redirects:

~\Anaconda3\lib\site-packages\msrest\pipeline\__init__.py in send(self, request, **kwargs)
    148         self._policy.on_request(request, **kwargs)
    149         try:
--> 150             response = self.next.send(request, **kwargs)
    151         except Exception:
    152             if not self._policy.on_exception(request, **kwargs):

~\Anaconda3\lib\site-packages\msrest\pipeline\requests.py in send(self, request, **kwargs)
    191         return Response(
    192             request,
--> 193             self.driver.send(request.http_request, **kwargs)
    194         )

~\Anaconda3\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    331         """
    332         requests_kwargs = self._configure_send(request, **kwargs)
--> 333         return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
    334 
    335 

~\Anaconda3\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    143         except requests.RequestException as err:
    144             msg = "Error occurred in request."
--> 145             raise_with_traceback(ClientRequestError, msg, err)
    146 
    147         return RequestsClientResponse(request, response)

~\Anaconda3\lib\site-packages\msrest\exceptions.py in raise_with_traceback(exception, message, *args, **kwargs)
     49     error = exception(exc_msg, *args, **kwargs)
     50     try:
---> 51         raise error.with_traceback(exc_traceback)
     52     except AttributeError:
     53         error.__traceback__ = exc_traceback

~\Anaconda3\lib\site-packages\msrest\universal_http\requests.py in send(self, request, **kwargs)
    137         session = kwargs.pop('session', self.session)
    138         try:
--> 139             response = session.request(
    140                 request.method,
    141                 request.url,

~\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         }
    529         send_kwargs.update(settings)
--> 530         resp = self.send(prep, **send_kwargs)
    531 
    532         return resp

~\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    641 
    642         # Send the request
--> 643         r = adapter.send(request, **kwargs)
    644 
    645         # Total elapsed time of the request (approximately)

~\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    512             if isinstance(e.reason, _SSLError):
    513                 # This branch is for urllib3 v1.22 and later.
--> 514                 raise SSLError(e, request=request)
    515 
    516             raise ConnectionError(e, request=request)

ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='eastus2.modelmanagement.azureml.net', port=443): Max retries exceeded with url: /modelmanagement/v1.0/subscriptions/02f98505-8150-48e9-8b0b-b2963db5ffd1/resourceGroups/sit-aip-ml-reg1-01/providers/Microsoft.MachineLearningServices/workspaces/sit-na-aip-aml-auw_wkspace/assets (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))

**Comment by jpe316** [comment]
Closing this as it appears to be transient, please let us know if it happens again!
