### ISSUE TITLE
auto-ml-classification-bank-marketing-all-features.ipynb does not return ONNX model if AutoML is used as AutoMLStep

### ISSUE THREAD

**Issue by justas-exadel** [Azure/MachineLearningNotebooks#1085]
I want to create a pipeline that has an AutoMLStep and returns ONNX model. 
I started with auto-ml-classification-bank-marketing-all-features.ipynb by changing it into a pipeline with AutoMLStep. 
My expectations were that AutoMLStep output will contain ONNX file. 
It did not happen, the output did not contain ONNX file
![image](https://user-images.githubusercontent.com/69246763/89411863-cdd55880-d72e-11ea-8d18-79ee27806b06.png)

Next I tried to convert model.pkl file into ONNX format using OnnxConverter class. It returned

**(None, None, None, 
{'Info': 'Failed to convert Model.', 'Class': 'AttributeError', 'ErrorMsg': "'NoneType' object has no attribute 'built_default'", 'RawModelString': '[Scrubbed]', 'IsOnnxCompatibleMode': False, 'StackTrace': '  
File "onnx_converter.py", line 508, in convert\n    raise inner_e\n  File "onnx_converter.py", line 489, in convert\n    pipe, model_name, model_desc)\n  File "onnx_converter.py", line 763, in _convert\n    target_opset=target_opset)\n  File "onnx_converter.py", line 781, in _convert_whole_model\n    topology = self._parse_model(model, target_opset)\n  File "onnx_converter.py", line 979, in _parse_model\n    self._setup_initial_types_based_on_model(model)\n  File "onnx_converter.py", line 942, in _setup_initial_types_based_on_model\n    if trans.mapper.built_default is None or trans.mapper.built_default is False:\n'})**

After endless experimentation I came up with the conclusion that something is wrong on AutoMLStep.

**Comment by swatig007** [comment]
@CESARDELATORRE can you pls take a look at this issue?

**Comment by CESARDELATORRE** [comment]
@justas-exadel Can you provide the notebook/code for repro?
Also the Run ID and log files from the AutoMLStep run.

Adding some folks from the team to help and diagnose the issue.
Please, @anupsms @pieths can you advise here?

**Comment by CESARDELATORRE** [comment]
I got this confirmation from the team.
If you are using SDK<1.12.0 you need to set passthru=True then it'll enable_onnx_compatible_models. 
 
If using SDK>=1.12.0 you don't need to do anything special and you should get the ONNX models depending on the supported AutoML algorithms for ONNX.

We recommend to update and use the latest SDK version.

Please, confirm your status after trying these recommendations, ok?

**Comment by CESARDELATORRE** [comment]
#please-close Closing this issue since it was answered and no further question was posted.
Please, re-open if issue persists.
