### ISSUE TITLE
Azureml-train-automl-runtime is not installed. Submitting run to a new conda environment.

### ISSUE THREAD

**Issue by luistelmocosta** [Azure/MachineLearningNotebooks#1086]
Hello, I installed azure ML through pip, using: `azureml-sdk[automl_databricks]` so I could use AutoML with Databricks.
My dataset is a pandas dataframe with a couple millions of lines

I am using the following config:

```
time_series_settings = {
    "time_column_name": "ds",
    #"time_series_id_column_names": ["store"],
    "forecast_horizon": "auto",
    "target_lags": "auto",
    "target_rolling_window_size": "auto",
    "featurization": "auto",
}

automl_config = AutoMLConfig(task='forecasting',
                             primary_metric='normalized_root_mean_squared_error',
                             experiment_timeout_minutes=15,
                             enable_early_stopping=True,
                             training_data=train_data,
                             label_column_name=label,
                             #spark_context=sc,
                             n_cross_validations=5,
                             enable_ensembling=False,
                             verbosity=logging.INFO,
                             **time_series_settings)
```

However, when I try to run, I get the following warning: `Azureml-train-automl-runtime is not installed. Submitting run to a new conda environment.` and it hangs forever.

Do I need to convert my dataset to an azure friendly format? What may be causing this issue? 

```
experiment = Experiment(ws, "forecasting_example")
local_run = experiment.submit(automl_config, show_output=True)
```

**Comment by cartacioS** [comment]
azureml-sdk[automl-databricks] has been deprecated, please try again with azureml-sdk[automl]. Documentation is here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-environment#install-the-correct-sdk-into-a-databricks-library

**Comment by cartacioS** [comment]
Hi @luistelmocosta, I have provided a solution above. I will go ahead and close this issue, feel free to reach out if the issue persists. Thanks! #please-close
