### ISSUE TITLE
TypeError: register() got an unexpected keyword argument 'create_new_version'

### ISSUE THREAD

**Issue by jiajinghu19** [Azure/MachineLearningNotebooks#1087]
I have updated azureml sdk, but still got the error saying unexpected key word 'create_new_version' :

```
ds.register(workspace=ws,
                name='newdata',
                description='some description',
                create_new_version = True)
```

error message:

```
TypeError: register() got an unexpected keyword argument 'create_new_version'
```

**Comment by lostmygithubaccount** [comment]
@jiajinghu19 is `ds` a Dataset?

**Comment by MayMSFT** [comment]
how did you create the ds? and which sdk version are you using. we'd recommend to upgrade to the latest azureml-sdk version and follow this doc to create & register dataset.
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets

**Comment by jiajinghu19** [comment]
Hey thanks, I was able to get it work now
