### ISSUE TITLE
How to write batch scoring results to data lake?

### ISSUE THREAD

**Issue by lingfeidiewu** [Azure/MachineLearningNotebooks#1089]
I'm trying to write the output of batch scoring into datalake:
```
parallel_step_name = "batchscoring-" + datetime.now().strftime("%Y%m%d%H%M")

output_dir = PipelineData(name="scores", 
                          datastore=def_ADL_store,
                          output_mode="upload",
                          output_path_on_compute="path in data lake")

batch_score_step = ParallelRunStep(
    name=parallel_step_name,
    inputs=[test_data.as_named_input("test_data")],
    output=output_dir,
    parallel_run_config=parallel_run_config,
    allow_reuse=False
)

```
However I meet the error: "code": "UserError",
        "message": "User program failed with Exception: Missing argument --output or its value is empty.",
How to resolve the problem?

**Comment by MayMSFT** [comment]
PipelineData does not support datalake. We just released the surport of data lake via dataset API. documentation will be published next week. stay tuned!

**Comment by meyetman** [comment]
Here is the example that @MayMSFT referred to https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb 

#please-close
