### ISSUE TITLE
The link to the GitHub site is broken

### ISSUE THREAD

**Issue by ryanwadebg** [Azure/MachineLearningNotebooks#1090]
[Enter feedback here]

The link to the GitHub site is broken. I tried to find similar documentation in the repo but could not find any. Please advise where I should go.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3321a1-39ab-8e41-f678-68ddbb939a17
* Version Independent ID: b49c840c-1dca-7113-4160-bc767cc4f31e
* Content: [azureml-dataprep package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-dataprep/?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-dataprep/index.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-dataprep/index.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by SturgeonMi** [comment]
Hi, what is the issue you encountered when you open https://github.com/microsoft/AMLDataPrepDocs?
I can open the link and view the files.

**Comment by ryanwadebg** [comment]
Hello. That is interesting because I get a 404 error.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ryanwadebg** [comment]
This is what I see when I click on the link:

![image](https://user-images.githubusercontent.com/56444898/89648550-5f5adc80-d88d-11ea-92c2-5f137500c539.png)

**Comment by SturgeonMi** [comment]
It seems the link is set as "internal".  Let me confirm with the team and get back to you.

**Comment by ryanwadebg** [comment]
Thanks SturgeonMi,

I look forward to what you find.

Ryan

**Comment by SturgeonMi** [comment]
@MayMSFT As we synced offline, you indicated the Dataprep SDK is deprecated, we are having new SDK experience.

@ryanwadebg Do you have specific questions towards some specific tasks? Or you want to check what's the current Github folder for instructions towards tasks/contents contained in https://github.com/microsoft/AMLDataPrepDocs? 
(Tasks e.g. 
	How to load data is an overview guide on how to load data using the Data Prep SDK.
	How to transform data is an overview guide on how to transform data.
	How to write data is an overview guide on how to write data to different storage locations. )

**Comment by MayMSFT** [comment]
The dataprep package is deprecated for internal use only. Customers are encouraged to use [auzreml dataset](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets) to access and load data from cloud.

We are working on removing the API reference for dataprep to avoid user confusion in the future. sorry for this.

**Comment by DieselAnalytics** [comment]
Thanks for the update @MayMSFT. Trying to keep up with these changes and the direction you all are going is quite confusing.

**Comment by ryanwadebg** [comment]
Is there a road map for AML? I know there is one for Power BI. Is there is something similar for AML that you can share with the public?
