### ISSUE TITLE
Creating pipelines in code with modules from the designer

### ISSUE THREAD

**Issue by ashic** [Azure/MachineLearningNotebooks#1093]
Is it possible to use the python sdk to define a machine learning pipeline using some of the modules available in the designer? For example, Clean Missing Data, Train, LinearRegression, etc? Or are these modules only available in the designer? 

Also, is it possible to export the definition of a pipeline built in the designer to some xml / yaml / json format that can then be taken to a different azure account to set up the pipeline there?

**Comment by luzhang06** [comment]
We have a feature in private preview which can help you leverage the modules in Designer in SDK. Please reach out to me: luzhan@microsoft.com if you have interest.

Regarding pipeline yaml format, it's in our road map to support it.
