### ISSUE TITLE
Time rolling window forecast

### ISSUE THREAD

**Issue by luistelmocosta** [Azure/MachineLearningNotebooks#1094]
Hello, I would like to know if there is any out of the box function for a time rolling window forecast.

The idea is the following:
- Train until a certain date, e.g, 31-12-2020
- Increase one window, train again and make predictions
- Repeat the process until the window is over

Is there any quick way of doing this or we need to train for every window?

Regards,
Luís

**Comment by kelmahrsi** [comment]
There is one for AutoML forecasting tasks (cf. https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast). I hope it does what you're looking for.

**Comment by luistelmocosta** [comment]
> There is one for AutoML forecasting tasks (cf. https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast). I hope it does what you're looking for.

Thank you for your reply. I already checked that link, it is about the general parameters of auto ml forecast. What I am talking about is completely different. 
Time rolling window is widely used for forecast problems, the idea is to increase the time window iteratively so you can have a smaller lag. I would like to know if this problem has already been tackled or not.

**Comment by pbartos** [comment]
AutoML forecast supports rolling forecast when you try to predict the horizon longer than the window size. It predicts one window and use these predicted values to predict the next one.
There is no good reason to train on predicted values.

**Comment by swatig007** [comment]
@cartacioS can you pls take a look at this issue?

**Comment by cartacioS** [comment]
Hi @luistelmocosta, to confirm your question AutoML forecasting does not re-train models during the recursive forecast. This would be quite a tricky implementation in AutoML since it leads to the question: Do you want to have full model selection on each window, or just re-train the model originally selected? AutoML does not support the second option.

However, I suspect that what you actually need is the recursive forecasting. We are currently working on a sample notebook and documentation to show users how to leverage this functionality.

**Comment by deepakmukunthu** [comment]
@luistelmocosta, I am closing this assuming your question is answered. Please let us know if you have more questions or need more details.

#please-close

**Comment by ayushgupt** [comment]
> Hi @luistelmocosta, to confirm your question AutoML forecasting does not re-train models during the recursive forecast. This would be quite a tricky implementation in AutoML since it leads to the question: Do you want to have full model selection on each window, or just re-train the model originally selected? AutoML does not support the second option.
> 
> However, I suspect that what you actually need is the recursive forecasting. We are currently working on a sample notebook and documentation to show users how to leverage this functionality.

Hi @cartacioS , can you please share this sample notebook you mentioned if available?
