### ISSUE TITLE
Model Name too short for MLFlow

### ISSUE THREAD

**Issue by AndrewLouw** [Azure/MachineLearningNotebooks#1099]
The requirements for the model name, when registering a model are:
"It must only consist of letters, numbers, dashes, periods, or underscores, start with a letter or number, and be between 1 and 32 characters long."

This doesn't allow a name of exactly 32 characters (must actually be less than 32)

MLFlow experiment id's are exactly 32 characters long. This makes it impossible to use mlflow experiment id's as model names which is very frustrating. Please increase. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by shivp950** [comment]
can you share what version of the SDK you're using? We have increased the character limit, I'll follow up on my end as well

**Comment by AndrewLouw** [comment]
Using:
import azureml
azureml.core.__version__
'1.0.85'

I've checked again and the problem looks like it's gone - thanks. I think I was debugging while you guys were updating everything last weekend. I'll update to the latest version and start using the URI properly. Is this preview now live? https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-mlflow

Thanks

**Comment by shivp950** [comment]
That's great to hear! Yup MLflow is public preview,you can use it today. We are actively working on improving the integration.
