### ISSUE TITLE
"No usable environment found" error when deploying AutoML model

### ISSUE THREAD

**Issue by jwood803** [Azure/MachineLearningNotebooks#1103]
I was following the steps in [this section](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb) of an AutoML sample with a different data set. 

When running the `aci_service.wait_for_deployment(True)` command, I get the below error:
```
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "No usable environment found that's linked to your model with RunId : AutoML_9088241f-575c-4226-b6a6-2d656a89c076_14 and ExperimentName : housing_experiment",
  "details": []
}
```

Here's the code I used for deploying a model:

```python
best_run.download_file('outputs/scoring_file_v_1_0_0.py', 'inference/score.py')

inference_config = InferenceConfig(entry_script="inference/score.py")

aciconfig = AciWebservice.deploy_configuration(cpu_cores = 1, 
                                               memory_gb = 1, 
                                               tags = {'area': "housing", 'type': "automl_regression"}, 
                                               description = 'Housing Automl Regression')

aci_service = Model.deploy(ws, "automl-housing-price-regression", [model], inference_config, aciconfig)
aci_service.wait_for_deployment(True)
```

Am I missing something here or something I need to do in the Azure ML Service portal?

**Comment by swatig007** [comment]
@rtanase can you pls take a look at this issue?

**Comment by rtanase** [comment]
@jwood803, it looks like the model was trained on a local environment, for which we don't currently capture automatically the environment in the Run object (like it happens for models trained remotely). As a workaround, can you please try to explicitly set the environment for the InferenceConfig object?

`from azureml.core.environment import Environment`
`from azureml.automl.core.shared import constants`
`best_run.download_file(constants.CONDA_ENV_FILE_PATH, 'myenv.yml')`
`myenv = Environment.from_conda_specification(name="myenv", file_path="myenv.yml")`
`inference_config = InferenceConfig(entry_script="inference/score.py", environment=myenv)`

**Comment by jwood803** [comment]
Thanks for looking into this @rtanase! That works for me! 😄 

I'm running this in a compute instance inside of the Azure ML service. Would that capture the environment automatically? Or is it some other scenario that captures the environment?

**Comment by rtanase** [comment]
Awesome, thanks for confirming @jwood803!

The environment is only being automatically captured when the experiment is running on a remote compute target (when AutoML is creating the environment from scratch).
