### ISSUE TITLE
SSL error on ws.compute_targets

### ISSUE THREAD

**Issue by AndrewLouw** [Azure/MachineLearningNotebooks#1107]
Trying to get ws.compute_targets hangs for a long time (max retries) then eventually produces an error. The actual error is:
Max retries exceeded
but this is due to an underlying bad handshake
 
This does not happen on 1.0.85

To replicate:
1. create a new azureml workspace resource
2. pip install --upgrade azure-sdk
3. download config file
4 run below:

import azureml
from azureml.core import Workspace
print(f"version: {azureml.core.__version__}")
ws = Workspace.from_config(config)
ws.compute_targets

Out:
version: 1.12.0

...Traceback...

SSLError: HTTPSConnectionPool( REDACTED_PII ) Max retries exceeded with url: REDACTED_PII api-version=2020-02-02 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90efe042-27ac-6e77-9292-10df77bb1c36
* Version Independent ID: 3b9f2576-7d3f-00f8-0afe-549960520f08
* Content: [azureml.core.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace%28class%29?view=azure-ml-py#compute-targets)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by nishankgu** [comment]
#assign @sauryadas

**Comment by AndrewLouw** [comment]
I got this issue on release day for version: 1.12.0 (and I suspect new infrastructure on cloud service).

**Comment by sauryadas** [comment]
Can you please provide information on which region you deployed? is this AKS ? Did you create or attach the cluster? are you able to access the cluster with the kube config?

**Comment by AndrewLouw** [comment]
I was using an Azure ML workspace in the UK South region. 
Here is a corrected and improved set of reproduction steps - I tested today and still got the error:

1. create a new azureml workspace resource: https://portal.azure.com/#create/Microsoft.MachineLearningServices
2. pip install --upgrade azureml-mlflow
3. pip install --upgrade azureml-sdk
4. download config file
5. run below:

import azureml
from azureml.core import Workspace
print(f"version: {azureml.core.\_\_version\_\_}")
ws = Workspace.from_config()
ws.compute_targets

**Comment by sauryadas** [comment]
Do you have a correlation id?

**Comment by lostmygithubaccount** [comment]
no

**Comment by shayeny** [comment]
Was this solved? I am facing the same issue trying to pip install from behind a VNET.

**Comment by sauryadas** [comment]
I notice that this is issue was in v 1.12.0

Can you try the latest SDK version ? v1.22.0

https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes?view=azure-ml-py&toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpython%2Fapi%2Foverview%2Fazure%2Fml%2Ftoc.json%3Fview%3Dazure-ml-py&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpython%2Fazureml_stable_breadcrumb%2Ftoc.json%3Fview%3Dazure-ml-py

**Comment by v-strudm-msft** [comment]
We haven't received a response to our last comment so assume it's resolved and are closing it. Should there still be a question, please reopen this issue. Thank you.
