### ISSUE TITLE
Location of AutoMLStep please.

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#1112]
Azure ML SDK Version:  1.12.0

```from azureml.pipeline.steps import AutoMLStep```

Per this doc:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-automated-machine-learning-step.ipynb

It looks like you can import the AutoMLStep, however I can't find it. 

```
azureml-automl-core==1.12.0
azureml-automl-runtime==1.12.0
azureml-contrib-notebook==1.10.0
azureml-core==1.12.0.post1
azureml-dataprep==2.0.7
azureml-dataprep-native==20.0.2
azureml-dataset-runtime==1.12.0
azureml-defaults==1.12.0
azureml-explain-model==1.12.0
azureml-interpret==1.12.0
azureml-model-management-sdk==1.0.1b6.post1
azureml-pipeline==1.12.0
azureml-pipeline-core==1.12.0
azureml-pipeline-steps==1.12.0
azureml-sdk==1.12.0
azureml-telemetry==1.12.0
azureml-train==1.12.0
azureml-train-automl==1.12.0
azureml-train-automl-client==1.12.0
azureml-train-automl-runtime==1.12.0
azureml-train-core==1.12.0
```

**Comment by luzhang06** [comment]
Hi BillmanH, can you please share more details about what you mean by "you cannot find the AutoMLStep"? Any error you get when importing AutoMLStep?

**Comment by BillmanH** [comment]
Actually it looks like an older version of the SDK. 

The solution was that if you use `pip install --upgrade azureml-sdk` it will upgrade the VERSION to 1.12.0, however it won't upgrade all of the dependent packages. This gives the user the false impression that they are current, when they aren't. 

In order to ensure that you have upgraded correctly you need to use `pip install --upgrade azureml-sdk[explain,automl]`. Updating in this way solved the issue.
