### ISSUE TITLE
Error when running ML Pipeline (Failed to upload outputs and mark job as failed)

### ISSUE THREAD

**Issue by NathanNZ** [Azure/MachineLearningNotebooks#1113]
Our ML pipeline in Azure ML Learning (using 1.12.0 libraries) finishes successfully however the overall experiment is marked as failed. This is complicated further as each of the Steps within the experiment are marked as successful.

Digging more into the last step that registers the model the following error (below) can be found in the executionlogs.txt output. This does not seem to effect the registration of the model however it would be nice to figure out what is causing this error & fix the bug that makes it harder to figure out what step in the pipeline caused the overall experiment to fail.

```
[2020-08-21 04:07:30Z] Job finished, job RunId is 02658432-b54b-4654-935c-20e2679ebf54
[2020-08-21 04:07:30Z] Failed to upload outputs and mark job as failed. Error: Object reference not set to an instance of an object., stack trace:    at Microsoft.Aether.BlueBox.Clouds.Common.OutputDataLocationUtils.<>c__DisplayClass8_0.<<UpdateOutputDataLocationWithDatasetIdAsync>b__1>d.MoveNext() in d:\dbs\sh\Ae\0810_152138\cmd\0\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\OutputDataLocationUtils.cs:line 202
   at Microsoft.Aether.BlueBox.Clouds.Common.OutputDataLocationUtils.UpdateOutputDataLocationWithDatasetIdAsync(AMLJobMetadata job, RunDto runDto, IAzureMachineLearningDatasetManagementClient datasetClient, IDataStoreClient datastoreClient) in d:\dbs\sh\Ae\0810_152138\cmd\0\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\OutputDataLocationUtils.cs:line 199
   at Microsoft.Aether.EsCloud.Common.JobProcessor.CheckRunStatusAsync(EsCloudJobMetadata job, RunDto runDto) in d:\dbs\sh\Ae\0810_152138\cmd\2\src\aether\platform\backendV2\Clouds\ESCloud\ESCloudCommon\JobProcessor.cs:line 380

```

**Comment by luzhang06** [comment]
Hi NathanNZ,

Thanks for reporting this issue. Can you please share with us the notebook you used so that we can repro the issue?

Thanks,
Lu

**Comment by NathanNZ** [comment]
Currently working on acquiring a notebook that I can share. As it's not a blocking error at this stage this may not be possible, but i'll see what I can do!

**Comment by abij** [comment]
I'm running into the same issue with AuzreML sdk 1.12.0. I'll try to give some more context:

First step is running in Databricks, creating a parquet file on the blob. This blob is also mounted in AzureML as a datastore.
Second step running on ComputeCluster registers the dataset in Python, pointing at the parquet files on the blob.

The second step does not 'have' or produces any data for the 'outputs'-folder. It just registers a path on the blob.
Looks like AzureML is trying to upload some output, which not there.

```
# AzureML Pipeline using Python:

step1a_select = DatabricksStep(
        name="refresh-data",
        source_directory=STEPS_DIRECTORY,
        python_script_name="dataloader.py",
        python_script_params=[
            "--dbfs_mount_path", '/mnt/storageaccount/container/',
            "--output_path", 'mydatafolder'
        ],
        pypi_libraries=[
            PyPiLibrary("azureml-core"), 
            PyPiLibrary("azureml-dataprep") 
        ],
        compute_target=databricks,
        existing_cluster_id='some-cluster-id',
        run_name="Refreshing the data",
    )

step1b_register = PythonScriptStep(
        name="register-dataset",
        source_directory=STEPS_DIRECTORY,
        script_name="register_dataset.py",
        arguments=[
            "--datastore_name", "container_on_storageaccount",
            "--dataset_name", "dummy",
            "--file_path", "mydatafolder",
        ],
        compute_target=aml_compute,
        runconfig=run_config,
    )

# step2 is some data-pre-processing using the updated dataset, fetched by name 'dummy'
```

Where the `register_dataset.py` does:

```
# ... truncated for a shorter example
parquet_path = os.path.join(args.file_path, "*.parquet")
data_store = Datastore.get(ws, args.datastore_name)
data_path = DataPath(data_store, parquet_path)

tabular_ds: TabularDataset = (
        Dataset.Tabular
            .from_parquet_files(data_path)
            .with_timestamp_columns("date"))

tabular_ds = tabular_ds.register(
        ws, args.dataset_name,
        description="Some example dataset",
        create_new_version=True,
        tags={"sometag": "this works..."})

# No 'outputs' folder is created, no data is written.
```

**Comment by abij** [comment]
I took the effort to make a failing pipeline with a single step, please have a look!

[azureml_pipeline_sdk_1.12_issue.ipynb.zip](https://github.com/Azure/MachineLearningNotebooks/files/5142313/azureml_pipeline_sdk_1.12_issue.ipynb.zip)

**Comment by NathanNZ** [comment]
I've gotten confirmation through support that this is a known issue with a hotfix pending. I believe the fix should have rolled out to EastUS however for other regions they are still pending a release, this can also be worked around by rolling back to 1.11.
