### ISSUE TITLE
azureml-sdk and azure-identity==1.4.0

### ISSUE THREAD

**Issue by marcin-vt** [Azure/MachineLearningNotebooks#1117]
In our project we already use azure-identity==1.4.0 (to use az cli authentication in development - DefaultAzureCredential). Now we would like to use azureml-sdk however it seems that it only works with azure-identity<1.3.0. 
Is there any workaround to make it work? Any idea when azureml-sdk will catch up and how to make a pressure on them?

**Comment by vizhur** [comment]
pressure was put on azureml python sdk and the latest versions of azureml-dataprep updated the dependency range.
