### ISSUE TITLE
Recommendation: change execution_type from str to Enum

### ISSUE THREAD

**Issue by tarockey** [Azure/MachineLearningNotebooks#1118]
In the Module "publish" method, it requires an `exectution_type` parameter of type string, but it is not documented anywhere what the possible execution types are. It wasn't until I dug through the source code after downloading the SDK that it was clear that choices include: "escloud", "AzureBatchCloud", "adlcloud", and presumably others which are not defined. This makes using Modules in any way other than those explicitly included in demo code very difficult.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5786e5-32df-303d-5795-a0b48af5c5b8
* Version Independent ID: 62de5e2e-691b-8b79-d91a-949aa0b5acf3
* Content: [azureml.pipeline.core.module.Module class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.module.module?view=azure-ml-py#create-workspace--name--description---workflow-provider-none-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.module.Module.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.module.Module.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
@tarockey Thank you for the feedback. I have opened a work item to address this recommendation in the next planning and release cycle.
