### ISSUE TITLE
@CESARDELATORRE

### ISSUE THREAD

**Issue by Meenakshi-subramanian** [Azure/MachineLearningNotebooks#1119]
@CESARDELATORRE 
Hi ,
I have registered my dataset using a python script step and I have given the dataset (Tabular Dataset) as input to AutoMLConfig. When I submit the AutoMLConfig as an experiment, The run is successful. 

**Problem with AutoMLstep:**
However when I include the AutoMLConfig in the AutoML step and try to submit the pipeline. I face the followig error.

![image](https://user-images.githubusercontent.com/17467126/91314507-43839000-e7d4-11ea-8502-57c17cad76f1.png)

I used the following for AutoML step
![image](https://user-images.githubusercontent.com/17467126/91314612-601fc800-e7d4-11ea-9722-3fe7145b6fd3.png)
The automl_config above is working fine when it is submitted separately. 

The AutoML step is imported as follows
`from azureml.pipeline.steps import AutoMLStep`

Could not debug this  as there is no clear indication of
What is {dataName} and what is not found. And also Automl config works fine but the same doesnt work with AutoML step.
Kindly help ASAP.

_Originally posted by @Meenakshi-subramanian in https://github.com/Azure/MachineLearningNotebooks/issues/844#issuecomment-680911280_

**Comment by CESARDELATORRE** [comment]
Closing this issue since it's duplicated in favor of the original #844 where we're answering.
