### ISSUE TITLE
BaseExplanation is mentioned, but not documented

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#1125]
BaseExplanation has it's own plethora of functions and metrics. It's also got a lot of unclear outputs. Someone should document what it's methods and parameters mean and how to interpret them. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba5415b-89a4-5f52-eb68-f864ca76a409
* Version Independent ID: ebbe9f91-ecde-900c-b3c4-64fd20f76fc3
* Content: [azureml.contrib.interpret.explanation.explanation_client.ExplanationClient class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-interpret/azureml.contrib.interpret.explanation.explanation_client.explanationclient?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-interpret/azureml.contrib.interpret.explanation.explanation_client.ExplanationClient.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-interpret/azureml.contrib.interpret.explanation.explanation_client.ExplanationClient.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by minthigpen** [comment]
Thanks for the feedback! Could you please clarify which outputs were unclear to you that we should improve our documentation with? Currently we outline the methods and parameters and link to other resources on python docs. It would be great to understand what we're missing.

**Comment by BillmanH** [comment]
See how the document says:
```
Return type
BaseExplanation
```

Well many users may not know what a BaseExplanation object is as it isn't a standard python object.  In similar documentation the BaseExplanation would contain a link, to another place where BaseExplanation is explained.  Upload model requires a BaseExplanation, download model returns a BaseExplanation. But the BaseExplanation object itself is undocumented.  

When you look into the BaseExplanation object itself, it has a lot of properties and methods. I would recommend creating a separate doc page about that object so that a user could use the methods of that object. This would make it easier to be certain that a user's application accomplishes what they assume it will do.

**Comment by minthigpen** [comment]
Thanks for opening the issue @swanderz - closing this issue here since we've opened an issue in the open source repo. #please-close

**Comment by swanderz** [comment]
@minthigpen are you referring to this issue that I opened?
> https://github.com/interpretml/interpret-community/issues/317

**Comment by minthigpen** [comment]
@swanderz  yes that one!

**Comment by swanderz** [comment]
@imatiach-msft says the main sdk docs have nothing to do with the `interpret-community` package and I agree. this isn't a matter of needed documentation created. The issue is that said documentation isn't available on the main sdk doc page.

@minthigpen, can re-open this issue and close the other one?

**Comment by swanderz** [comment]
#please-reopen per discussion in https://github.com/interpretml/interpret-community/issues/317
sphinx is not correctly importing the documentation from the `interpret-community` package into MSFT docs.
cc: @minthigpen @j-martens @imatiach-msft

**Comment by BillmanH** [comment]
Closing old tickets. The SDK has come a long way and this is no longer relevant. Also, IMO the best practice is to lean on the AML SDK for the execution of pipelines and containers, but to rely on your own code and packages for your data science. The AML tools that do data science are just wrappers around the open-source packages.
