### ISSUE TITLE
Environment attributes not in Docs

### ISSUE THREAD

**Issue by luisquintanilla** [Azure/MachineLearningNotebooks#1130]
The environment class has a series of attributes that are not in the API docs like:

- `name`
- `python`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf83484-8d65-c598-3a97-2e1f8a1cf917
* Version Independent ID: aeed389d-4eec-013f-7b91-642f2de3f676
* Content: [azureml.core.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by saachigopal** [comment]
name is listed as a parameter and python is listed as a variable

**Comment by luisquintanilla** [comment]
Perfect. Thanks @saachigopal
