### ISSUE TITLE
questions about how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building

### ISSUE THREAD

**Issue by likebupt** [Azure/MachineLearningNotebooks#1135]
in this notebook, the [normalize.py](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/scripts/prepdata/normalize.py) split the pickup_datetime to pickup_date and pickup_time like following
![image](https://user-images.githubusercontent.com/39058063/92359386-bf0f0680-f11d-11ea-9ccd-dbcda4cee933.png)

but in [transform.py](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/scripts/prepdata/transform.py), it set the pickup_date and pickup_time to datetime, which cannot be executed successfully, since these are not complete format of datetime, datetime must contain date and time.
![image](https://user-images.githubusercontent.com/39058063/92359756-5aa07700-f11e-11ea-8e53-39272d664d41.png)

Could you please help with this issue?

**Comment by shbijlan** [comment]
@likebupt I am able to reproduce this issue and have opened a work item to get it fixed. Will update you once resolved.

**Comment by shbijlan** [comment]
@likebupt Please try to run this notebook on the latest azureml-sdk version 1.13.0. The notebooks and packages used have been updated to comply with azureml-sdk 1.13.0. This should solve the issue you are facing. I have validated and can confirm the notebook runs successfully after updating SDK version. 

If you still experience issues with this after updating, please re-open this issue.
