### ISSUE TITLE
Incorrect example code

### ISSUE THREAD

**Issue by akosb** [Azure/MachineLearningNotebooks#1136]
Hi,

 please fix the sample code for how to log an Image

```Example: run.log_image("ROC", plt)```

won't work, as second param is 'path' and not 'plot', the sample correctly:

```Example: run.log_image("ROC", plot=plt)```

Just for the record, using the example as it is today would result:
```
AttributeError: module 'matplotlib.pyplot' has no attribute 'tell'
```

Thanks and regards, Akos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by shivp950** [comment]
fix addressed, should be visible soon.

**Comment by akosb** [comment]
This issues should not be closed yet, the [documentation](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py) is still not updated.

**Comment by paulshealy1** [comment]
Documentation is updated.
