### ISSUE TITLE
SSLError: HTTPSConnectionPool when registering ML model on Azure

### ISSUE THREAD

**Issue by jay2017-git** [Azure/MachineLearningNotebooks#1140]
Hi Everyone,

Please I have my Databricks instance in a VNET. I’m trying to deploy my Machine learning model using the Azure ML workspace on Azure Container Instance (ACI).

I’m able to create an ML workspace. I get an SSLERROR when I try to register the Model using Model.register().

Using this code -

`from azureml.core import Workspace
from azureml.core.model import Model
import azureml.core
from azureml.core.workspace import Workspace
from azureml.core.model import Model

from azureml.core import Workspace
ws = Workspace.create(name='myworkspace',
subscription_id='mysub_id',
resource_group='myresourcegroup',
location='eastus'
)

model_reg = Model.register(model_path = “./model_dir”,
model_name = "ModelX",
workspace = ws)
`

Find below the error when I try to deploy my model.

SSL Error:
`
SSLError: HTTPSConnectionPool(host='eastus.experiments.azureml.net', port=443): Max retries exceeded with url: /discovery (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))`
Please note only the Azure Databricks is in a VNET on Azure. How do I resolve it and deploy my model as a webservice on ACI.

Thank you.

**Comment by lostmygithubaccount** [comment]
closing in favor of https://github.com/Azure/MachineLearningNotebooks/issues/1138 

this is currently the best GitHub repo to post issues with the Azure ML service, azureml-examples is relatively new
