### ISSUE TITLE
compute_target arguemnt doesn't exist?

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#1141]
Seems like the compute_target argument doesn't exist?
![image](https://user-images.githubusercontent.com/11371870/92752953-65921c00-f357-11ea-8699-3263836bbf35.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109d9284-e234-5086-5da6-4155291361c8
* Version Independent ID: 57cc0c7a-faa7-1a86-ee14-b9cf99fb540d
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
it does not (but coincidentally is being added to the constructor along with environment and other useful stuff).

like the environment, today you need to set the target on the run_config object which is commented out in the code above:
```
src.run_config.target = cpu_cluster.name
```

**Comment by omartin2010** [comment]
Makes sense... but why do we document this : 
![image](https://user-images.githubusercontent.com/11371870/92754254-a9395580-f358-11ea-9283-0fd03a44139f.png)

**Comment by lostmygithubaccount** [comment]
not sure...looking at the example lower in the same page:

```python
from azureml.core import ScriptRunConfig, RunConfiguration, Experiment

   # create or load an experiment
   experiment = Experiment(workspace, 'MyExperiment')
   # create or retrieve a compute target
   cluster = workspace.compute_targets['MyCluster']
   # create or retrieve an environment
   env = Environment.get(ws, name='MyEnvironment')
   # configure and submit your training run
   config = ScriptRunConfig(source_directory='.',
                            script='train.py',
                            arguments=['--arg1', arg1_val, '--arg2', arg2_val],
                            compute_target=cluster,
                            environment=env)
   script_run = experiment.submit(config)
```

I suspect the SDK docs went out before the changes have actually been made? @mx-iao to confirm

**Comment by mx-iao** [comment]
What version of the SDK are you using? The reference docs are up-to-date for the latest release of azureml-sdk (1.13.0)

**Comment by omartin2010** [comment]
I think 1.12... the docs should have a version thing... it otherwise gets confusing...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mx-iao** [comment]
We will look into versioning for the reference docs.
