### ISSUE TITLE
Pipelines get triggered as many times, as blobs changed in the datastore

### ISSUE THREAD

**Issue by sfilipi** [Azure/MachineLearningNotebooks#1142]
In the Remarks section of the Schedule class, there is this statement about triggering Pipeline runs:

```
Two types of schedules are supported. The first uses time recurrence to submit a Pipeline on a given schedule. The second monitors an AzureBlobDatastore for added or modified blobs and submits a Pipeline when changes are detected.
```

This lead me to believe that if there are multiple changes in the interval between checks, **one** Pipeline run would be triggered. In reality there are as many pipelines triggered, as blobs are changed. 

IMO, the most common scenario would be to have data for the experiment in one container, and if all of those input files are updated within the poll interval time, trigger a **single** run. 

Otherwise make the documentation explicitly state that the pipeline gets triggered as many times as blobs changed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca505228-7b1f-12aa-da29-0cb343c74030
* Version Independent ID: ecb04c61-fc02-9a03-eede-88fca8bee6a8
* Content: [azureml.pipeline.core.Schedule class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.schedule(class)?view=azure-ml-py&source=docs)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.Schedule(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.Schedule(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
@sfilipi Thank you for the feedback! I have opened a work item to address this. The team will review the feedback and accommodate it in the planning and release process.
