### ISSUE TITLE
Bike share example has a config issue in the automl_config

### ISSUE THREAD

**Issue by kristianjaeger** [Azure/MachineLearningNotebooks#1144]
Please see the time_series_settings parameter below compared with what is in github. Thanks.  This is in https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-bike-share/auto-ml-forecasting-bike-share.ipynb

automl_config = AutoMLConfig(task='forecasting',                             
                             primary_metric='normalized_root_mean_squared_error',
                             blocked_models = ['ExtremeRandomTrees'],                         
                             experiment_timeout_hours=0.3,
                             training_data=train,
                             label_column_name=target_column_name,
                             compute_target=compute_target,
                             enable_early_stopping=True,
                             n_cross_validations=3, 
                             max_concurrent_iterations=4,
                             max_cores_per_iteration=-1,
                             verbosity=logging.INFO,
                             ****time_series_settings**)

**Comment by cartacioS** [comment]
Hi @kristianjaeger - we have updated the experience so that forecasting settings are set using the new parameters class you noted in the notebook. Our forecasting documentation is also currently being updated. Was there a question or further clarification I can provide?

**Comment by kristianjaeger** [comment]
Thanks, @cartacioS ! I think that is all for now. I would still like to finish the related video series when I have time. Cheers.

**Comment by deepakmukunthu** [comment]
#please-close
