### ISSUE TITLE
Moving Data in and out of pipelines documentation has incorrect API

### ISSUE THREAD

**Issue by ahyerman** [Azure/MachineLearningNotebooks#1145]
The [following document](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-move-data-in-out-of-pipelines) reads:
>To pass a dataset to your pipeline step:
>1. Use TabularDataset.as_named_inputs() or FileDataset.as_named_input() (no 's' at end) to create a DatasetConsumptionConfig object

However `as_named_inputs()` results in `AttributeError`
```
train_dataset.as_named_inputs('foo')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-ab05b3fe51a0> in <module>
----> 1 train_dataset.as_named_inputs('foo')

AttributeError: 'TabularDataset' object has no attribute 'as_named_inputs'
```

The correct statement should probably be:
>To pass a dataset to your pipeline step:
>1. Use TabularDataset.as_named_input() or FileDataset.as_named_input() to create a DatasetConsumptionConfig object

**Comment by lostmygithubaccount** [comment]
made a PR to fix - @MayMSFT please confirm this is correct, there were a few instances of `as_named_inputs` in this article. https://github.com/MicrosoftDocs/azure-docs-pr/pull/129711

**Comment by lostmygithubaccount** [comment]
PR has been merged - will close this once updated on public docs - thanks @ahyerman for reporting

**Comment by ahyerman** [comment]
Thanks @lostmygithubaccount for the quick turnaround!
