### ISSUE TITLE
Access to AKS web service endpoint in vnet allowed from Postman without inbound security rule enabled 

### ISSUE THREAD

**Issue by brberton-msft** [Azure/MachineLearningNotebooks#1150]
I created an AKS cluster in a vnet and used it to host my model as a web service following the documentation.

I skipped the step to enable an inbound security rule for the scoring endpoint in the NSG group that controls the virtual network. I was unable to access the web service endpoint using either the python Request module or aks_service.run() (running on compute not in the vnet) and I received a timeout error. However, I was able to access the web service endpoint using Postman. What's happening here?

After enabling the inbound security rule, I was able to access the web service using all three methods.

See the stackoverflow discussion for additional details.

**Comment by Bozhong68** [comment]
@brberton-msft The behavior is by design. We think that Postman might be running through the system proxy that has access through NSG, where Python request and AML SDK won't use system proxy by default. Closing the issue now but feel free to reopen if you have additional question.
