### ISSUE TITLE
need more document for data_types parameter in InputPortDef

### ISSUE THREAD

**Issue by ling0322** [Azure/MachineLearningNotebooks#1155]
[Enter feedback here]

we need more document for data_types parameter in InputPortDef. Only from the source code could I know the default value was ["AnyFile", "AnyDirectory"].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b4cd6a2-5ba5-5691-d4fc-abc6800f5718
* Version Independent ID: 4151db15-3faf-f16c-70e8-fe114e61a85c
* Content: [azureml.pipeline.core.graph.InputPortDef class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.inputportdef?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.graph.InputPortDef.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.graph.InputPortDef.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
@ling0322 Thank you for your feedback. I have opened a work item to address this gap in documentation. It will be reviewed in the planning and release process.

**Comment by shbijlan** [comment]
This is being updated in reference documentation.
