### ISSUE TITLE
Tag definition in PipelineData objects

### ISSUE THREAD

**Issue by jarandaf** [Azure/MachineLearningNotebooks#1161]
Is it possible to define tags when registering datasets from `PipelineData` objects? I create some datasets as follows during a multiple-step pipeline execution:

```python
PipelineData('some_output', datastore=blob_datastore).as_dataset().register(some_name)
```

The only way I have found to set some tags to these datasets is to retrieve them by name after the pipeline execution and set their tags property explicitly. This is not very convenient since I want to be able to retrieve these datasets by tag (and not their names). Actually, querying datasets by tag does not seem supported. What is the use case for using datasets tag, then?

**Comment by MayMSFT** [comment]
Thanks for the feedback. We are working on enabling search dataset by tags at the moment.

**Comment by jarandaf** [comment]
Is there any feature release estimate? Thank you.

**Comment by MayMSFT** [comment]
Hi @jarandaf 
we dont have a concrete estimate at the moment. Most likely early next year

**Comment by MayMSFT** [comment]
#please-close
