### ISSUE TITLE
Named package extras do not exist

### ISSUE THREAD

**Issue by timoklimmer** [Azure/MachineLearningNotebooks#1163]
The package extras named in the article do not exist. Please provide the correct extra names and ideally give us more insights about the packages on https://pypi.org/user/amlpypi. When should we install which package? I am really confused from this package zoo...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by vizhur** [comment]
@timoklimmer if you look on the left pane of the install page on the help you can find description for the most of the zoo inhabitants. 
From the page you can get information or links for particular scenarios, samples and use case guidance
 
![image](https://user-images.githubusercontent.com/21002116/94695542-05fab100-0304-11eb-93fc-513dc723b833.png)
