### ISSUE TITLE
Monitoring Models in AKS (notebook enable-app-insights-in-production-service)

### ISSUE THREAD

**Issue by frvigano** [Azure/MachineLearningNotebooks#1164]
Notebook enable-app-insights-in-production-service fails when it tries do deploy the endpoint into AKS. 

I was able to have it working by modyfing the dependencies as follows:

it is :

conda_deps = CondaDependencies.create(conda_packages=['numpy','scikit-learn==0.19.1','scipy'], pip_packages=['azureml-defaults', 'inference-schema'])

instead it should be

conda_deps = CondaDependencies.create(conda_packages=['numpy','scikit-learn==0.19.1','scipy'], pip_packages=['azureml-defaults', 'inference-schema','azureml-monitoring'])

Apparently, we created a new library (azureml-monitoring) to store class 

from azureml.monitoring import ModelDataCollector

**Comment by tmccrmck** [comment]
I ran with azureml.core version 1.16.0 and everything worked. What version are you using?

I believe `azureml-monitoring` should only be needed if you are doing `config = AksWebservice.deploy_configuration(collect_model_data=True, enable_app_insights=True)`

**Comment by Bozhong68** [comment]
@frvigano azureml-monitoring library has been there since we have ModelDataCollector a while ago, if you enable collect_model_data then the library will been needed. I will close the issue now, please let us know if you still have issues.
