### ISSUE TITLE
Only single character is supported for argument: separator

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#1173]
[Enter feedback here]
Unable to read a tab-delimited file into AML.  Tab delimitation is a very common framework and should be supported. Also, it's technically just one character, it's just represented by the `separator` parameter as `/t`

```
training_data=output.read_delimited_files(
                                 filename, separator='/t')
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6558448-0f7f-b25a-eb36-e931b3f9220c
* Version Independent ID: 89ce38ad-a133-054e-dd1b-7900ca2ecb52
* Content: [azureml.data.output_dataset_config.OutputFileDatasetConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.output_dataset_config.outputfiledatasetconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.output_dataset_config.OutputFileDatasetConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.output_dataset_config.OutputFileDatasetConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by SturgeonMi** [comment]
Hi William, Tab separated files should be supported already.
Could you help to provide related error message?
Thanks!

Please find instructions about read_delimited_files() here:
[https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_factory.tabulardatasetfactory?view=azure-ml-py#from-delimited-files-path--validate-true--include-path-false--infer-column-types-true--set-column-types-none--separator------header-true--partition-format-none--support-multi-line-false--empty-as-string-false--encoding--utf8--](url)

**Comment by BillmanH** [comment]
FYI that link doesn't go anywhere. 

I had to pivot my inputs for commas so I don't have the error message any more, however the title of this issue was a copy/paste of that error.  So the error was something like: 

```
Error: Only single character is supported for argument
```

**Comment by SturgeonMi** [comment]
Got it. Thanks! The error message is helpful.
Added an internal tracking item for investigation.

I have updated the link above. (The new link is to the parent page, you can search for from_delimited_files)
And it seems it won't jump from Github directly. you need to copy to the Browser and then it can land on the page.

**Comment by SturgeonMi** [comment]
@BillmanH  It seems it should be "separator='\t'", rather than '/t'.
\t is the escaped tab character.

**Comment by BillmanH** [comment]
? 

Wow. Ok. Can't believe I never saw that before.
