### ISSUE TITLE
Mount point / path_on_compute missing in as_mount() method for PipelineData object

### ISSUE THREAD

**Issue by Jhidzzo** [Azure/MachineLearningNotebooks#1177]
Hi,
I was working with azure ml and was moving data around using the PipelineData object. In my files in the PipelineData I need to set absolute paths. When working with a small amount of data there should be no problem with using the as_download() method. However if that is not the case I would like to switch to the as_mount() method. But when working with it following question came up:
Why does the PipelineData object not give the option to set the mount point (path_on_compute) in the as_mount() method?

Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76780996-4443-4aff-18c0-65195afcab00
* Version Independent ID: 6032c190-bb76-7050-89fa-30476b36b43f
* Content: [azureml.pipeline.core.PipelineData class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinedata?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineData.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineData.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by SturgeonMi** [comment]
Hi Jhidzzo,

AzureML dataset has the ability to set mount path, and you can use dataset for moving data around via pipelines.
Please find related doc here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets
And (1) output filedataset: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.output_dataset_config.outputfiledatasetconfig?view=azure-ml-py
(2) output tabulardataset: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.output_dataset_config.outputtabulardatasetconfig?view=azure-ml-py

Hope the dataset abilities can help here.

**Comment by Jhidzzo** [comment]
Hi @SturgeonMi,
thanks for your comment. I figured that out myself. And I got it working now. However I still ask myself why the PipelineData object does not give the option to set the mount path...

**Comment by SturgeonMi** [comment]
We are thinking about recommending to use Dataset in pipelines.
If there is no other questions, will close it here.
Thanks!

**Comment by meyetman** [comment]
#please-close
