### ISSUE TITLE
DataTransferStep starts doing the tranfer then fails

### ISSUE THREAD

**Issue by LaurieCantaloube** [Azure/MachineLearningNotebooks#1179]
Hi!
I'm trying to use a DataTransferStep to move a directory from a location to another in the same Azure Storage. 
I use a PipelineData to specify the source location, a DataReference for the destination location and 'Directory' as parameter for source_reference_type and destination_reference_type.
I've this kind of structure for the source: 
/azureml/4dc04302-670b-4961-8354-f5577b9a30b5/predictions(path from the PipelineData)/DATE=x/xxx.parquet
and this one for the destination: 
/Directory1/Directory2/predictions/
and finally what I want is:
/Directory1/Directory2/predictions/DATE=x/xxx.parquet
At the beginning, the step runs perfectly and starts copying DATE=x directories (with the parquet file) in /usage/affluence/predictions/ but before the end, after the copy of 2-3 directories, I've this error (stderrlogs.txt): 

`[2020-10-06 08:51:07Z] Data transfer failed: {
  "errorCode": "2200",
  "message": "Failure happened on 'Sink' side. ErrorCode=UserErrorFailedFileOperation,
'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,
Message=Upload file failed at path Directory1/Directory2/predictions/\\DATE_PREDICTION=2020-09-21/a88d23f1d88c437fb124db602e5384ce.parquet.,
Source=Microsoft.DataTransfer.ClientLibrary,
''Type=Microsoft.WindowsAzure.Storage.StorageException,
Message=The remote server returned an error: (404) Not Found.,
Source=Microsoft.WindowsAzure.Storage,
StorageExtendedMessage=The specified blob does not exist.
RequestId:eea25116-d01e-0006-6abd-9b3844000000
Time:2020-10-06T08:50:54.6832234Z,,
''Type=System.Net.WebException,
Message=The remote server returned an error: (404) Not Found.,
Source=Microsoft.WindowsAzure.Storage,'",
  "failureType": "UserError",
  "target": "CopyActivity",
  "details": []
}`

I don't understand why the step can copy the first elements but not all...Any idea?

**Comment by swanderz** [comment]
`Directory1/Directory2/predictions/\\DATE_PREDICTION=2020-09-21/a88d23f1d88c437fb124db602e5384ce.parquet.`
The path you included has an escaped forward slash, `\\`, is that intentional? it _might_ be related to #1088

**Comment by swanderz** [comment]
This also might be a great scenario to skip the complexity of `DataTransferStep` invoking Azure Data Factory, and in stead just you `OutputFileDatasetConfig` which is now in public preview. Check out this [Pipelines with Datasets notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb), which now makes use of this new feature. cc: @MayMSFT

**Comment by LaurieCantaloube** [comment]
@swanderz `\\` is an error I think, it wasn't my will to have it in my path... 
I finally used `OutputFileDatasetConfig` instead of `DataTransferStep`and it works perfectly! Thanks a lot for your advice!
I close this issue

**Comment by swanderz** [comment]
@LaurieCantaloube great to hear! Can you share more about your experience using `OutputFileDatasetConfig` using [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR56WvHlfSMBOmRUduEaJtFFUQVFTUTVCNU5LVzBNSEFIRE5YUzBVTlhPMi4u)? Thanks!
