### ISSUE TITLE
Workspace connection Issue

### ISSUE THREAD

**Issue by nikhil8786** [Azure/MachineLearningNotebooks#118]
Hi,
I am able to connect to the workspace first time when I log in but when I am trying to connect to the workspace after 2-3 hours, I am getting this issue :

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

May be it is because of any token expire issue.
Please reply if any other person has resolved this issue.

Regards,
Nikhil

**Comment by artsheiko** [comment]
I think the smae issue is here : https://github.com/Azure/MachineLearningNotebooks/issues/215
