### ISSUE TITLE
About 50% of links on the homepage of this repo are broken

### ISSUE THREAD

**Issue by levalencia** [Azure/MachineLearningNotebooks#1182]
AMLSamples  link on homepage of this repo is broken

**Comment by harneetvirk** [comment]
@j-martens

**Comment by j-martens** [comment]
@lostmygithubaccount owns this page. thank you. Cody?

**Comment by lostmygithubaccount** [comment]
@harneetvirk this is on us (not docs team) to fix

**Comment by harneetvirk** [comment]
The broken links are removed/fixed: https://github.com/Azure/MachineLearningNotebooks/pull/1198
