### ISSUE TITLE
Environment.load_from_directory(path)

### ISSUE THREAD

**Issue by chengyu-liu-cs** [Azure/MachineLearningNotebooks#1183]
[Enter feedback here]
The documentation is not clear what kind of format is required for this function and what file it looks for. I have to run blindly to find out from error message. It seems it searches for `azureml_environment.json`. But isn't it much easier to provide path to file instead of directory ? And it is better to support yaml file instead of json file as `RunConfiguration.save`  stores environment as yaml file.

It is not clear what should be inclueded in the json file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf83484-8d65-c598-3a97-2e1f8a1cf917
* Version Independent ID: aeed389d-4eec-013f-7b91-642f2de3f676
* Content: [azureml.core.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment(class)?view=azure-ml-py#load-from-directory-path-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by vizhur** [comment]
that's a poor documented not intended to be public method that stays there for backward compat. the method instantiates an env object from a special folder structure with dockerfile and python dependencies. 
to instantiate an object from a yml or pip requirements there are factories on the Environment class

**Comment by chengyu-liu-cs** [comment]
@vizhur  So basically what I need to do is to create an Environment object from yaml files (including conda yaml file) that were generated from `RunConfiguration.save`.  I can create a `RunConfiguration` object first and then only take environment variable. But I feel there should be more divided functions or better way to do this?

**Comment by vizhur** [comment]
That's a RunConfiguration contract that has nothing to do with the Environments. You can instantiate RunConfiguration and get Environment object from there. Sorry, for the confusion.

**Comment by chengyu-liu-cs** [comment]
So then there is no other way to create Environment object from yaml files that are generated from `RunConfiguration.save` ? Are there similar functions in the roadmap ?

**Comment by vizhur** [comment]
not with 1.x. 2.x will standardize contracts between AzureML components, the work is in progress but no ETA. @chengyu-liu-cs  Closing the ticket, please feel free to open if you have any questions
