### ISSUE TITLE
how to load an experiment?

### ISSUE THREAD

**Issue by marciomocellin** [Azure/MachineLearningNotebooks#1185]
I have many experiment, like:

![image](https://user-images.githubusercontent.com/40580910/95883598-82a07d00-0d51-11eb-847d-872452f6caa4.png)

and now, i want load an experiment
```python
#%% sumonando os pacotes e verificando azureml.core
import azureml.core
import pandas as pd
import numpy as np
import logging

print("AzureML SDK Version: ", azureml.core.VERSION)

#%% Conectando ao azure e crinado o exparimento

from azureml.core import Workspace, Experiment

ws = Workspace.from_config() 
print(Experiment.list(ws))
#%%
Experiment = Experiment.from_directory('teste2-Monitor-Runs')
 ```

but

`"error": {
        "message": "No cache found for current project, try providing resource group and workspace arguments"
    }`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
* Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
* Content: [azureml.core.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by marciomocellin** [comment]
> `Experiment.from_directory` is deprecated per https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment.experiment?view=azure-ml-py#from-directory-path--auth-none-
> 
> Could you instead try retrieving the experiment like this?
> 
> ```python
> from azureml.core import Workspace, Experiment 
> ws = Workspace.from_config()
> 
> exp = Experiment(ws, "teste2-Monitor-Runs")
> ```


No, this creates a new experiment with the same name.

**Comment by lostmygithubaccount** [comment]
right sorry - you can do:

```python
exp = ws.experiments["teste2-Monitor-Runs"]
```
