### ISSUE TITLE
wait_for_deployment(show_output=False, timeout_sec=None)

### ISSUE THREAD

**Issue by chengyu-liu-cs** [Azure/MachineLearningNotebooks#1190]
[Enter feedback here]
What is timeout_sec default value ? It seems when it is None, it does not raise error but when certain secs passes, it raises errors.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 504498ae-210a-59a9-b329-5bde1f900b6b
* Version Independent ID: 18a2860b-9b4c-89e5-beaa-ef44d2c24352
* Content: [azureml.core.Webservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-core/azureml.core.webservice(class)?view=azure-ml-py#wait-for-deployment-show-output-false-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Webservice(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Webservice(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by vaidya-s** [comment]
The default timeout is 20 mins. @Bozhong68 to update the documentation.

**Comment by Bozhong68** [comment]
The default timeout is 20 mins for AKS deployment, and 30 mins for ACI deployment.
