### ISSUE TITLE
Are variables defined in Environment.environment_variables available from built docker images ?

### ISSUE THREAD

**Issue by chengyu-liu-cs** [Azure/MachineLearningNotebooks#1196]
[Enter feedback here]
Hi

The documentation for `Environment.environment_variables available` is not clear. What does it mean by "These environment variables are set on the process where the user script is executed." what is "user script" ? 

I have been using this feature to store some environment variables which can be loaded by running `os.getenv`, for example in score.py file. It works well when I use score.py in webservice deployment (`Model.deploy()`). But I could not find variables defined from built images (`Model.package`).  I created a detailed issue [here](https://github.com/Azure/MachineLearningNotebooks/issues/1195).

Can you specify in which cases those variables can be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf83484-8d65-c598-3a97-2e1f8a1cf917
* Version Independent ID: aeed389d-4eec-013f-7b91-642f2de3f676
* Content: [azureml.core.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by vizhur** [comment]
closing as a dup of https://github.com/Azure/MachineLearningNotebooks/issues/1195
