### ISSUE TITLE
power consumption calculation

### ISSUE THREAD

**Issue by NSVR57** [Azure/MachineLearningNotebooks#1199]
I am inferencing certain AI models on PB6s family by deploying webservice. is there any workaround or any API to do the same.

**Comment by lostmygithubaccount** [comment]
hi @NSVR57, I don't understand what you're asking for - can you elaborate?

**Comment by NSVR57** [comment]
Hi @lostmygithubaccount 

I am trying to inference certain models in different cards(Specifically on intel Arria). after i inference one  model on this card. i just want to calculate total power consumption by this card. i have azure paid subscription and i am inferencing on Pb6s family. is there any way around for this?

**Comment by lostmygithubaccount** [comment]
@Bozhong68 can you help with this?

**Comment by Bozhong68** [comment]
@NSVR57 hi there, we don't expose any API for FPGA power consumption directly. If you have any questions about FPGA card power consumption, we are happy to chat with you offline, my email bozhlin@microsoft.com. Closing the issue for now.
