### ISSUE TITLE
Is there a way to un-register a custom environment in Azure ML studio?

### ISSUE THREAD

**Issue by mavsun** [Azure/MachineLearningNotebooks#1201]
Hi, 

I was trying to deploy a xgboost classifier model and encountered some issues. 
It says that it could not locate the model despite the fact that I registered it and put in the same directory as the score.py file. I reckon there may be something wrong with my environment variable, so I wanted to start from scratch, then I realized that there is no 'unregister' in the environment class. Is there any way I can remove my custom environment from the list of environment in my workspace?

I tested my model path using os.getenv('AZURE_MODEL_DIR'), but returned none.
I am currently testing a new environment name (with the same conda and pip packages)

Many thanks.

**Comment by saachigopal** [comment]
Currently, un-registering/removing environments is not supported.

**Comment by majidaldo** [comment]
FAIL

**Comment by RinatVeliakhmedov-TomTom** [comment]
Then are we supposed to just leave it there for now?

**Comment by alesalloum** [comment]
Any progress on unregistering the unnecessary environments?

**Comment by saachigopal** [comment]
Through the CLI v2 (public preview), you can now delete environments

**Comment by AnijaJacob** [comment]
az ml environment delete --name --resource-group  --version --workspace-name
                         
 https://docs.microsoft.com/en-us/cli/azure/ml/environment?view=azure-cli-latest#az-ml-environment-delete                        
                         

> @saachigopal Hey there, I have looked a lot but couldn't find a way to delete. can you please share any leads on how to delete? thanks

**Comment by caitriggs** [comment]
When running the CLI command:
`az ml environment delete --name test-env  --resource-group [redacted rg name] --version 1 --workspace-name [redacted workspace name]`
I'm getting a permissions error when trying to delete the registered custom environment I created. **I have Owner level permissions to our AML workspace**

` does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/environments/versions/delete' `

is there a specific role I should add myself with to IAM for the AML workspace?
