### ISSUE TITLE
Inconsistency in recommended dependency management tool

### ISSUE THREAD

**Issue by carloshvp** [Azure/MachineLearningNotebooks#1204]
Hello,
[this Tutorial](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py&preserve-view=true) to get started with the AzureML SDK shows the pip commands to manage the azureml-sdk dependency, although the how to guide to [Set up dev environments](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-environment) recommends conda. This would not be an issue when the default channels for conda would include azureml-sdk, but that is not the case, so "conda install azureml-sdk" cannot replace "pip install azureml-sdk" making it difficult for a newcomer to follow the recommendation to use conda for dependency management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py&preserve-view=true)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by vizhur** [comment]
@carloshvp can't see any inconsistency here. AzureML recommends to use conda for environment isolation. From any python environment the only way to get AzureML python SDK is pypi, ie. `pip install`. AzureML Python SDK is not published on any conda channel.

**Comment by carloshvp** [comment]
Thank you @vizhur , I see your point.

Wouldn't it be reasonable to publish the AzureML python SDK in Conda if this is the recommended dependency management tool?

**Comment by vizhur** [comment]
Conda as a dependencies management tool perfectly manages conda and pip dependencies. Our documentation pages recommend to use it for isolated environment creation, we would never limit users on their preferred way to install or manage environment or dependencies.
