### ISSUE TITLE
Azure Managed SQL Instance As a DataStore

### ISSUE THREAD

**Issue by ekapti** [Azure/MachineLearningNotebooks#1208]
I am trying to connect a database within the Managed SQL Instance as a datastore. Managed Instance is not among the datastore type options so I tried to select the Azure SQL database and "enter manually" option for account selection. When I enter the full hostname of the managed instance which is something like "xxx-xxxx-xxx-xxxx-sql.45bsa4569.database.windows.net" it complaints due to dot "." that comes after 'sql'. Since I do not have control over that part of the hostname (Azure adds something like '.45bsa4569' on the managed instance name itself) I do not know how to fix it. Does anyone have any experience in connecting a managed instance az a datastore? 

FYI: The managed instance is behind a vnet so I am using service principal to authenticate.

**Comment by SturgeonMi** [comment]
Hi Engin, 
Azure SQL MI is not officially supported per [doc ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-access-data#supported-data-storage-service-types).
          It's possible to create a datastore on Azure SQL MI, by providing connection string to API [register_azure_sql_database,](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#register-azure-sql-database-workspace--datastore-name--server-name--database-name--tenant-id-none--client-id-none--client-secret-none--resource-url-none--authority-url-none--endpoint-none--overwrite-false--username-none--password-none----kwargs-) but unexpected behavior may occur.

AzureML data team is looking into this issue, and will update if we find any work around.

**Comment by MayMSFT** [comment]
Thanks for reaching out. Azure SQL MI is not supported at the moment. We added this request to our product backlog and will prioritize accordingly in future release.

**Comment by MayMSFT** [comment]
#please-close
