### ISSUE TITLE
03.Build_model_runHistory.ipynb auth variable not working

### ISSUE THREAD

**Issue by mhelb** [Azure/MachineLearningNotebooks#121]
CMD 6 has a ##TESTONLY comment, but that code block isn't working causing subsequent code referencing that arg to fail.  This should be cleaned up, either with more descriptive comment or so, ideally, it works straight away.

**Comment by rastala** [comment]
This is an issue with our notebook publishing, please ignore cells with ##TESTONLY comment.

**Comment by Exlsunshine** [comment]
We cannot just skip ## TESTONLY cells, because some normal cells use variables from those ## TESTONLY cells.

Could you please provide us more details about how to obtain these id and password?
@rastala 
```
tenant = dbutils.widgets.get('tenant_id')
username = dbutils.widgets.get('service_principal_id')
password = dbutils.widgets.get('service_principal_password')

auth = azureml.core.authentication.ServicePrincipalAuthentication(tenant, username, password)```
