### ISSUE TITLE
[Urgent Help Needed] How to schedule Batch Scoring pipelines with varying input data folders using DatasetConsumptionConfig?

### ISSUE THREAD

**Issue by kchaitanyabandi** [Azure/MachineLearningNotebooks#1213]
Hi,

I successfully built, ran and published a Batch Scoring pipeline that takes in dynamic input datasets at the time of submission. The datastore I used was obtained from an Azure File Share.

I wish to schedule this pipeline based on changes made to the Datastore. I know that the change based schedule only supports the blob containers and not file shares, also the `ParallelRunStep` for Batch Scoring accepts only `list[DatasetConsumptionConfig]` as inputs. 

I'm confused on how to schedule (based on datastore change) a Batch Scoring pipeline with dynamic varying input datasets.

Please let me know if you need additional information.
Thanks for the help.

**Comment by shbijlan** [comment]
@kchaitanyabandi please refer to the documentation for using Pipelines schedules https://docs.microsoft.com/en-us/azure/machine-learning/how-to-schedule-pipelines

You can also schedule AML pipelines with Azure Data Factory:  https://docs.microsoft.com/en-us/azure/data-factory/transform-data-machine-learning-service

**Comment by meyetman** [comment]
Should you still have questions regarding this issue, please comment here and reopen it. We're closing it for now. #please-close
