### ISSUE TITLE
Scheduled Pipeline - run build sometimes failing - automatic resubmit

### ISSUE THREAD

**Issue by gilahenry** [Azure/MachineLearningNotebooks#1223]
Hi,
We have some Scheduled Pipelines runs that sometimes (not often) fail because of a reason that's independent from our code (e.g., a docker pull failure, or a conda dependency that can't get installed because of a server error).
We can use the GUI to resubmit these runs and they succeed.

I was wondering if we could programmatically let Azure ML know that if a run fails, it needs to automatically resubmit it N times.

Is this feature available? Is it on your roadmap?

Kind regards,
Gil

**Comment by lostmygithubaccount** [comment]
I don't think there's anything built into the product and I wouldn't expect it anytime soon, however I'll let the Pipelines confirm/deny.

In the short term, I'd recommend working around this by setting up a similarly scheduled ML Pipeline, Azure Function, GitHub Action, etc. which runs a Python script checking if the run failed, possibly determining why, and submitting a rerun.

**Comment by shbijlan** [comment]
@gilahenry Thank you for the feedback. We have this feedback in our backlog, however, it is not planned for the near future.
