### ISSUE TITLE
Azureml pipeline graph connection between steps using run_after() really ugly

### ISSUE THREAD

**Issue by corticalstack** [Azure/MachineLearningNotebooks#1234]
When building an Azureml pipeline, the graph for the pipeline shows a line connecting steps that share a common output>input.

If additionally the <step1>.run_after(<step2>) command is specified, you get a second additional connecting line with output named _run_after_output and an input named _run_after_input. I believe these are generated by the site package azureml/pipeline/core/graph.py

`fake_output_name = "_run_after_output"
    fake_input_prefix = "_run_after_input_"

    def _init_fake_sequencing_ports(self):
        """Create fake input and output for sequencing."""
        if self._input_port_defs is None:
            self._input_port_defs = []

        if self._output_port_defs is None:
            self._output_port_defs = []

        if self._create_sequencing_ports:
            if not ModuleDef._contains(self._output_port_defs, lambda x: x.name == ModuleDef.fake_output_name):
                self._output_port_defs.append(OutputPortDef(ModuleDef.fake_output_name, data_type="AnyFile"))` 

This looks really ugly from a graph vizualisation perspective. Is there any way to hide these connectors, or at least be able to rename them if its the case that step B follows step A without sharing an output/intput dataflow?  Is it typical that it would be either a dataflow OR a run_after() that is defined to connect 2 steps? I suppose the workaround would be to create an own fake dataflow,  but that's an extra step.

On the image below, I have removed any "run_after()" referring to step Data Cleansing. However, step Study Methods is configured to run.after(Language Detection), hence you can see two connectors - 1 for the flow of output/input data, and the ugly run_after set due to use of the run.after() syntax.

![image](https://user-images.githubusercontent.com/3995321/98594004-51758700-22d4-11eb-817c-393cafaeed9b.png)

Many thanks

**Comment by shbijlan** [comment]
@corticalstack Thank you for bringing this to our attention. I have opened a work item to investigate this design change. If approved, we will incorporate it into our planning and release cycle.
