### ISSUE TITLE
check if blob already exist before uploading?

### ISSUE THREAD

**Issue by meeldurb** [Azure/MachineLearningNotebooks#1239]
When making a new dataset, i would like to know whether the file already exist on a blob.
Scenario:
I wrote the data "diabetes.csv" to my local workspace, then uploaded in to the blob as "diabetes.csv", and registered the dataset as "Diabetes". I created Version1

Now I unregister the dataset, and delete the local file. In the blob i delete nothing.
Now i create new data, and write it to local workspace, then upload in to the blob as "diabetes.csv", and register the dataset as "Diabetes". I created Version1 again, but the file in the blob was not overwritten, so the wrong file of diabetes.csv is registered as a dataset.

I know that in the upload class, i can choose to overwrite it. However, for documentation reasons I would never want to delete things from the blob storage. I would just like to get a notification that the file already exists in the blob and that I have to choose a different name for my dataset and file in the blob because it already exists. 

How could i check that?
Is there any other class or command that checks whether the file exists in the blob storage?
You have it in the .upload() class, because i can "show_progress = True", and it sees the file exists. 
How could i get that message, if i want to trhow an error for example?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9851745d-46c4-436b-3e6c-4ae1ef577bf4
* Version Independent ID: 9b2286d5-23ed-e3a4-2b84-bb45a700adda
* Content: [azureml.data.azure_storage_datastore.AzureFileDatastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.azure_storage_datastore.azurefiledatastore?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.azure_storage_datastore.AzureFileDatastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.azure_storage_datastore.AzureFileDatastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
@SturgeonMi

**Comment by MayMSFT** [comment]
hi @meeldurb 

You can get the console output in the following way. then write logic to parse the information about whether target already exists.
![image](https://user-images.githubusercontent.com/47834041/99009235-8401c880-24fc-11eb-981d-e7e969035824.png)

**Comment by lostmygithubaccount** [comment]
is there a way to do that without reading `stdout` like that?

**Comment by MayMSFT** [comment]
not through datastore API. But users can use blob API to list the container content. 
https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#list-blobs-name-starts-with-none--include-none----kwargs-

**Comment by meeldurb** [comment]
@MayMSFT 

> hi @meeldurb
> 
> You can get the console output in the following way. then write logic to parse the information about whether target already exists.
> ![image](https://user-images.githubusercontent.com/47834041/99009235-8401c880-24fc-11eb-981d-e7e969035824.png)

**Comment by meeldurb** [comment]
> not through datastore API. But users can use blob API to list the container content.
> https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#list-blobs-name-starts-with-none--include-none----kwargs-

How do instantiate the class? I have no experience with .self things.

**Comment by ynpandey** [comment]
The behavior defined here is expected behavior. Setting show_progress = True should show the message when file upload is skipped. If it is desired to overwrite the file overwrite flag should be set to true.
