### ISSUE TITLE
inputs as parameter

### ISSUE THREAD

**Issue by jsburckhardt** [Azure/MachineLearningNotebooks#1240]
Hi guys, I'm going nuts, can you confirm if inputs is a parameter?
![image](https://user-images.githubusercontent.com/18494471/99011385-15764680-25a0-11eb-89e3-af2526870b70.png)
also, is the estimator_config a RunConfiguration or a MMLBaseEstimatorRunConfig?
and the MMLBaseEstimatorRunConfig keeps failing with this exception:
![image](https://user-images.githubusercontent.com/18494471/99012023-908c2c80-25a1-11eb-92ec-fa56c16314dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4cfc529-11a8-d5f1-08d2-87c24de49c8b
* Version Independent ID: 34970955-8470-7e18-27e0-e9f785b6a9e8
* Content: [azureml.train.estimator.MMLBaseEstimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.mmlbaseestimator?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.estimator.MMLBaseEstimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.estimator.MMLBaseEstimator.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
would it be possible to use a `azureml.core.ScriptRunConfig` and an `azureml.core.Environment` for this? Using estimators is discouraged and on path to deprecation.

there is a curated environment you could potentially build off of named `"AzureML-PySpark-MmlSpark-0.15"`

**Comment by jsburckhardt** [comment]
hi mate, I did try using the ScriptRunConfig but it was complaining about `data_references`. Is there an example for Tune hyperparameters using `run_config`? all the examples I can find are using `estimator`.

**Comment by lostmygithubaccount** [comment]
all the examples should be updated to use `ScriptRunConfig`, with the recommendation being to use File Datasets instead of data references for download/mounting

one example is here: https://github.com/Azure/MachineLearningNotebooks/blob/91d43bade6a86c6d40cf9f6d78a84f4aa8aae801/how-to-use-azureml/ml-frameworks/tensorflow/hyperparameter-tune-and-warm-start-with-tensorflow/hyperparameter-tune-and-warm-start-with-tensorflow.ipynb

**Comment by jsburckhardt** [comment]
Hi guys, the example is perfect. I could run the experiment. I'll try now with the AML pipeline. Thanks

**Comment by jsburckhardt** [comment]
Bad news, I'm back to the issue regarding the ```data _reference``` in an AML pipeline when creating the ```HyperDriveStep```. 
1. without script parameters
![image](https://user-images.githubusercontent.com/18494471/99755919-0e22e000-2b40-11eb-8571-cc5220bd7256.png)
2. With script parameters as part of the ```ScriptRunConfig``` (similar to the successful experiment run ```exp.submit(HyperDriveConfig)```)
![image](https://user-images.githubusercontent.com/18494471/99755981-301c6280-2b40-11eb-8f59-56a086ffdd38.png)
3. With the script parameters passed into the ```estimator_entry_script_arguments``` (we aren't using an estimator - we are using **ScriptRunConfig** .
![image](https://user-images.githubusercontent.com/18494471/99757028-9e622480-2b42-11eb-94e6-0be515151013.png)


I checked the repo you sent and I couldn't find an AML pipeline that is tunning hyperparameters using a ```ScriptRunConfig```

**Comment by shbijlan** [comment]
@jsburckhardt here is an example of an AML pipeline using HyperDriveStep https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb
