### ISSUE TITLE
@MayMSFT

### ISSUE THREAD

**Issue by meeldurb** [Azure/MachineLearningNotebooks#1241]
@MayMSFT 

When I run this my console stops printing things. 
cannot even print("hello world")

> hi @meeldurb
> 
> You can get the console output in the following way. then write logic to parse the information about whether target already exists.
> ![image](https://user-images.githubusercontent.com/47834041/99009235-8401c880-24fc-11eb-981d-e7e969035824.png)

_Originally posted by @meeldurb in https://github.com/Azure/MachineLearningNotebooks/issues/1239#issuecomment-726811162_

**Comment by v-strudm-msft** [comment]
Related to #1239

**Comment by MayMSFT** [comment]
Hi,

Did you run the last command in the sample to reset  & print normally again?
Here is the tutorial that explained this: https://www.kite.com/python/answers/how-to-redirect-print-output-to-a-variable-in-python

**Comment by meyetman** [comment]
Should you still have questions regarding this issue, please comment here and reopen it. We're closing it for now. #please-close
