### ISSUE TITLE
AML Job Fails due to Pre-Empted Node

### ISSUE THREAD

**Issue by seanytak** [Azure/MachineLearningNotebooks#1242]
Hello, I am currently working with an AML Pipeline that uses a Low-Priority VM Compute Cluster.

The error I am receiving is
`AzureMLCompute job failed. PreemptionError: Nodes of this job got pre-empted. Check if the run has failed or restarted. Reason: Received pre-emption warning signal`

On the [following docs it says that a "A preempted job is restarted, not resumed."](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-cluster?tabs=python#low-pri-vm) but in my experience thus far, a preempted job is not restarted at all, it will just fail the pipeline. There doesn't seem to be a configuration setting that controls this on the `AmlCompute` class or the `provisioning_configuration` function.

Versions
`python==3.8.5`
`azureml-core==1.16.0`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2602bce8-83ed-cb02-ad23-943e3a955a43
* Version Independent ID: f117372d-7e39-b79b-282f-aded9be4003c
* Content: [Create compute clusters - Azure Machine Learning](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-cluster?tabs=python#low-pri-vm)
* Content Source: [articles/machine-learning/how-to-create-attach-compute-cluster.md](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/machine-learning/how-to-create-attach-compute-cluster.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @sdgilley
* Microsoft Alias: **sgilley**

**Comment by lostmygithubaccount** [comment]
I think that documentation is incorrect, I am not aware of any automatic restarting of preempted jobs

**Comment by seanytak** [comment]
I see, so is there any mechanism to have the job restarted or at least re-queue it until the nodes are available again?

**Comment by seanytak** [comment]
As a note, [I've opened an issue on the Azure Docs page responsible for the one I linked](https://github.com/MicrosoftDocs/azure-docs/issues/66288)

**Comment by lostmygithubaccount** [comment]
I don't believe there is an automated mechanism. You would probably want to run a parallel pipeline that checks occasionally for runs which failed due to preempted nodes and resubmit the job. 

We could probably do this simply with GitHub actions and provide a template

**Comment by nishankgu** [comment]
We ahve a feature to automatically restart/requeue pre-empted jobs. If you had like to get allow listed let me know and we can enable your sub.

**Comment by MathieuBeaudoin** [comment]
Hi, has this been fixed? I seem to have run into the same issue myself, while running a Pipeline on a Low-Priority Compute Cluster:
![image](https://user-images.githubusercontent.com/59290188/175045910-d813e058-2317-40d9-95a7-e466717401c0.png)
