### ISSUE TITLE
AutoML crashes with ValidationException on non-trimmed input data for regression task

### ISSUE THREAD

**Issue by faxg** [Azure/MachineLearningNotebooks#1246]
I get an error similar to #1174 when running AutoML using a .csv file as datasource.

The datasource was loaded (and profiled) in the Web UI without problem. All columns seemed to be detected as numerical on import, there's no missing values or invalid characters.
So everything looks great up to this point.

But when I try to "automl" the data, I get the following exception:

`2020-11-20 23:53:09.404 - CRITICAL - 101 - azureml.train.automl.run.log_traceback:224 - Type: InvalidInputDatatype
Class: ValidationException
Message: ValidationException:
	Message: Input of type 'empty' is not supported. Supported types: [decimal, integer, floating, mixed-integer-float]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Input of type 'empty' is not supported. Supported types: [decimal, integer, floating, mixed-integer-float]",
        "details_uri": "https://aka.ms/AutoMLConfig",
        "target": "y",
        "inner_error": {
            "code": "BadArgument",
            "inner_error": {
                "code": "ArgumentInvalid",
                "inner_error": {
                    "code": "InvalidInputDatatype"
                }
            }
        },
        "reference_code": "08629a21-bbcb-4088-959b-2d35c00cae32"
    }
}
Traceback:
  File "_remote_script.py", line 639, in setup_wrapper
    script_directory, dataprep_json, entry_point, parent_run, verifier)
  File "_remote_script.py", line 825, in _prep_input_data
    verifier=verifier
  File "_remote_script.py", line 109, in _prepare_data
    automl_settings=automl_settings_obj)
  File "training_utilities.py", line 145, in set_task_parameters
    target='y'

ExceptionTarget: y
2020-11-20 23:53:09.491 - WARNING - 101 - azureml.train.automl.run._is_local:173 - Failed to retrieve AutoMLSettings for run: AutoML_5ebdcdc3-f016-4d2e-854a-29742262c4f2_setup
2020-11-20 23:53:09.494 - ERROR - 101 - azureml.train.automl.run.log_traceback:226 - Type: Unclassified
Class: TypeError
Message: the JSON object must be str, bytes or bytearray, not 'NoneType'
Traceback:
  File "run.py", line 167, in _is_local
    settings = self._get_automl_settings()
  File "run.py", line 719, in _get_automl_settings
    **json.loads(self._get_property('AMLSettingsJsonString')))
  File "__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))

ExceptionTarget: Unspecified`

Going back to my source file, I noticed that there are whitespace characters in every cell (and right before end of line).
I removed the spaces and now it works. 

crashes: https://pastebin.com/DAbKr3j0
works ok: https://pastebin.com/pTpNRTUq

I think the loader should be either more robust, give better error messages or at least it should be consistently be flagged by the validation on import / upload of the file.

**Comment by kvijaykannan** [comment]
Thanks for taking time in providing the feedback. We will evaluate and have these changes incorporated.

**Comment by rtanase** [comment]
Thank you @faxg for providing the datasets! @vijethav91 can you please check where is this parsing issue raised?

**Comment by vijethav91** [comment]
@faxg did you use UI to run AutoML? If not, which version of AutoML were you using?

**Comment by vijethav91** [comment]
@faxg thank you for the feedback and providing the datasets! We have identified the issue and created a bug to track the repair item.

**Comment by vijethav91** [comment]
This is fixed.

#please-close
