### ISSUE TITLE
Unable to pull custom docker image from Azure private registry

### ISSUE THREAD

**Issue by corticalstack** [Azure/MachineLearningNotebooks#1247]
Hi,

I created a new Azure machine learning service. During the creation wizard I specified names for the workspace, storage, key vault and importantly, the container registry (i.e. NOT None).

Checking the registry I can see that the wizard has added a service principal entry to the identity management for the container registry, giving the machine learning workspace SP the role of contributor.

I have pushed a custom python environment to the azure registry.

On running the AzureML pipeline, it fails when trying to pull the docker image:

`
AzureMLCompute job failed.
FailedPullingImage: unable to pull docker image
	imageName: acreurfrcaass.azurecr.io/azureml-env-base-research-platform:latest
	err: Run docker command to pull public image failed with error: error response from daemon: get https://acreurfrcaass.azurecr.io/v2/azureml-env-base-research-platform/manifests/latest: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.`

So next I created a new test user in Azure AD, updated the password, and assigned the user the contributor role in the container registry IM.  Also specified the name/password in my pipeline code when setting up the environment as below:

```
myenv.docker.base_image_registry.address = "xyz.azurecr.io"
myenv.docker.base_image_registry.username = "test@xyz.onmicrosoft.com"
myenv.docker.base_image_registry.password = "xyz"

myenv.docker.base_image = "xyz.azurecr.io/xyz:latest"
```

The pipeline fails with the same authorisation issue.

Not if I login to Azure registry with cli using the same user specified in pipeline code with:

`az acr login --name <nameofregistry>`

and then 

`docker pull <acrregistry>/<image>`

the pull is successful

I also created a new service principal with the following script and used the SP id and password in my pipeline - still get the same "unauthorised" issue:
[Create container registry SP](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal)
Note - The above linked script does not make it clear if you should use the SP name or application ID as username - I tried both without success.

```
#!/bin/bash

# Modify for your environment.
# ACR_NAME: The name of your Azure Container Registry
# SERVICE_PRINCIPAL_NAME: Must be unique within your AD tenant
ACR_NAME=<container-registry-name>
SERVICE_PRINCIPAL_NAME=acr-service-principal

# Obtain the full registry ID for subsequent command args
ACR_REGISTRY_ID=$(az acr show --name $ACR_NAME --query id --output tsv)

# Create the service principal with rights scoped to the registry.
# Default permissions are for docker pull access. Modify the '--role'
# argument value as desired:
# acrpull:     pull only
# acrpush:     push and pull
# owner:       push, pull, and assign roles
SP_PASSWD=$(az ad sp create-for-rbac --name http://$SERVICE_PRINCIPAL_NAME --scopes $ACR_REGISTRY_ID --role acrpull --query password --output tsv)
SP_APP_ID=$(az ad sp show --id http://$SERVICE_PRINCIPAL_NAME --query appId --output tsv)

# Output the service principal's credentials; use these in your services and
# applications to authenticate to the container registry.
echo "Service principal ID: $SP_APP_ID"
echo "Service principal password: $SP_PASSWD"
```

Please advise as my pipeline is broken until this is resolved, many thanks.

**Comment by corticalstack** [comment]
Just to add - If you DO NOT create a container registry when setting up the machine learning workspace, the documentation notes that Azure will automatically create a container registry the first time a model is trained/deployed.

I assume that pulling a container image works here as azure has persisted the **ADMIN** credentials for the registry in it's associated key vault. This is depise azure also creating a service principal in the registry IM - I suspect when the pull is happening azure is using the admin credentials, not the SP credentials?

**Comment by lostmygithubaccount** [comment]
@corticalstack do you think this is a ML pipelines issue specifically?

**Comment by corticalstack** [comment]
@lostmygithubaccount I can log in and pull from the Azure container registry using the same credentials as I supply in the pipeline code that fails. I can see that the registry is registered in the workspace with the below:

`az ml workspace show -w <machine learning workspace> -g <resource group> --query containerRegistry`

I think behind the scenes, when the registry is left to the azureml pipeline to create the registry, it is using the admin credentials (which is not at all indicated in the documentation).  So yes, I think it is a pipleline issue given I can authenticate the same registry with same credentials from the CLI, and poor documentation does not help.

**Comment by corticalstack** [comment]
@lostmygithubaccount I try to summarize what works and doesnt for you:

1. Container registry created by Azure ML on first model train - image pull OK
2. Container registry created in advance, specified when creating Azure ML service, no registry uname/pwd specified in pipeline code - image pull NOT OK
3. Container registry created in advance, specified when creating Azure ML service, service principal specified specified in pipeline code - image pull NOT OK
4. Container registry created in advance, specified when creating Azure ML service, user/pwd of user assigned to registry Identity Management M specified in pipeline code - image pull NOT OK
5. Container registry created in advance, specified when creating Azure ML service, registry updated to enable admin user, admin user credentials specified in pipeline code - image pull OK

Note in scenarios 2-5, doing the below shows registry is linked with ML workspace, so according to the linked documentation, credentials should not even need to be specified?

`az ml workspace show -w <machine learning workspace> -g <resource group> --query containerRegistry`

Thanks

**Comment by vizhur** [comment]
myenv.docker.base_image_registry.address = "xyz.azurecr.io"
myenv.docker.base_image_registry.username = "test@xyz.onmicrosoft.com"
myenv.docker.base_image_registry.password = "xyz"

myenv.docker.base_image = "xyz:latest"

should work

**Comment by corticalstack** [comment]
@vizhur I had already tried that suggestion without success, but thanks. I assume the user your refer to is "standard" user set up in AAD and assigned a role in the registry IM (and not for example the registry user or the app service principal)?

**Comment by vizhur** [comment]
@corticalstack sorry, I should've read it through. From what I understand, service side auth was successful because it exchanges the creds with ACR for access token, so execution proceeds to compute but it trying to pull the image using the credentials and it does not work when admin is not enabled or credentials have a scoped access to the registry.

**Comment by corticalstack** [comment]
@vizhur User managed dependencies =True, using image to set env. Servcie side auth is only successful when specifying credentials of the admin user for the ACR (when this is enabled, as disabled by default).  Only in this case does the pipleline proceed to compute custom Python pipleline step.

In all other cases Ive tried (a new user set up in AAD scoped to ACR, or use of service principal scoped to ACR) I get an authorisation issue on pull of ACR.  Does this clarify for you?

**Comment by vizhur** [comment]
@corticalstack yes it does

**Comment by corticalstack** [comment]
Any progress? Thanks

**Comment by vizhur** [comment]
ah.. looks like no one got back to you, sorry about that. You would need to assign an identity to your compute and then give it acr pull access to ACR

**Comment by corticalstack** [comment]
> ah.. looks like no one got back to you, sorry about that. You would need to assign an identity to your compute and then give it acr pull access to ACR

No problem. Can you provide example of assigning identity to compute? Currently creating it programmatically as per below:

```
compute_config = AmlCompute.provisioning_configuration(vm_size=vm_size,
                                                           max_nodes=4)
    aml_cpu_compute = ComputeTarget.create(ws, aml_cpu_compute_cluster_name, compute_config)
```

**Comment by sweana** [comment]
Hi @corticalstack 
you would need to set the identity_type field to assign an identity to the compute.
Reference documentation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-cluster?tabs=python#managed-identity

Also, here is documentation of how to use Compute Identity for accessing ACR.
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-managed-identities?tabs=python#create-compute-with-managed-identity-to-access-docker-images-for-training

Hope this help... please let us know if you have more questions.

**Comment by damin604** [comment]
Hi,

I'm having the same issue of authorization required while pulling the docker container from ACR.
But in my case, I'm using a `Compute Instance (Standard_NC6)` and I tried to look for identity_type parameter in the ComputeInstance.provisioning_configuration documentation and this parameter doesn't exist.

![image](https://user-images.githubusercontent.com/80477823/140166369-6ae31175-213e-46f4-90f5-8e2549e151cc.png)

How would I be able to run an experiment using Compute Instance?. Thanks.
