### ISSUE TITLE
Timeseries frequency documentation unclear

### ISSUE THREAD

**Issue by gregorybchris** [Azure/MachineLearningNotebooks#1248]
- The `freq` parameter isn't included in this page under parameters to the ForecastingParameters configuration. In the short series section the `freq` parameter is described but without any units. It's unclear exactly how to use this parameter. A link to a notebook that uses `freq` would also be helpful.
- It's a bit confusing to link the energy demand notebook under the `time_series_id_column_names` parameter since that notebook doesn't use the parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e318b56f-a45e-9a74-93ae-a5d8aaaf6639
* Version Independent ID: b0a56b5a-0179-a8f4-b84f-17759cbbf6b9
* Content: [azureml.automl.core.forecasting_parameters.ForecastingParameters class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.forecasting_parameters.forecastingparameters?preserve-view=true&view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.forecasting_parameters.ForecastingParameters.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.forecasting_parameters.ForecastingParameters.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by gregorybchris** [comment]
Note: these comments refer to this documentation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast

**Comment by ahyerman** [comment]
Documentation here can also be improved: https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.forecasting_parameters.forecastingparameters?preserve-view=true&view=azure-ml-py

**Comment by jialiu103** [comment]
@ahyerman the improvement of python documentation below is going to release in 2 weeks.
 https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.forecasting_parameters.forecastingparameters?preserve-view=true&view=azure-ml-py

**Comment by jialiu103** [comment]
+@cartacioS to address @gregorybchris 's freedback on tutorial below
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast

**Comment by cartacioS** [comment]
Docs and notebooks have been updated based on feedback. Closing, thanks!

**Comment by sanjaydatasciencedojo** [comment]
The op is referring to this one for time_series_id_column_names.
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast#configure-experiment
![image](https://user-images.githubusercontent.com/30843127/101965613-2f6c6e80-3bca-11eb-8c84-55a728628bb9.png)

**Comment by sanjaydatasciencedojo** [comment]
@cartacioS  think the second concern is still not addressed.
