### ISSUE TITLE
Error: TypeError: 'NoneType' object is not subscriptable while running local web service notebook

### ISSUE THREAD

**Issue by RohitMungi-MSFT** [Azure/MachineLearningNotebooks#1251]
While running the following notebook ~how-to-use-azureml/deployment/deploy-to-local/register-model-deploy-local.ipynb the local service uri is not getting set during deployment of the service which causes an error while running the following command:

`local_service.run(sample_input)`

![image](https://user-images.githubusercontent.com/46958063/100578123-a0c53b00-3307-11eb-9eae-3fe9c908a08f.png)

**Comment by konstantinmiller** [comment]
I've also run into the issue while deploying my model locally. The issue didn't happen before.

**Comment by konstantinmiller** [comment]
The following workaround seems to work:
`del service._container_override_config`
prior to calling the `local_service.run()` method.

Alternatively, you can call your service via its URI: `http://localhost:<port>/score`

**Comment by frcai** [comment]
This issue should be fixed in last Nov. @anirbansaha96 - please try latest python SDK. https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py

**Comment by shivanissambare** [comment]
please feel free to reopen this issue, if it is not fixed :)
