### ISSUE TITLE
Unable to install azureml-sdk with pip (Python 3.9 support)

### ISSUE THREAD

**Issue by akashpandey111** [Azure/MachineLearningNotebooks#1256]
**OS: Mac OS Big Sur
Python version: 3.9**

**Command used: venv/bin/python -m pip install -U --no-cache-dir azureml-sdk**

I've been trying to install azureml-sdk since the last couple of days on my machine inside a python virtual environment to train models as experiments on Azure.

However, it's as if pip is unable to determine which version of each dependency is the right one for all the components of the SDK (please refer to the log.txt file linked at the bottom for better insight). 

Please note that _the log file is incomplete_ since it's a time consuming loop wherein pip downloads an older version for a component and checks whether the versions of all the dependencies for that component are compatible with it.

So far I've tried installing each component individually. azureml-core and azureml-dataprep installed smoothly whereas I faced the same problem of pip trying to figure out the right version of dependencies with azureml-train.

I have tried installing a specific version of azureml-sdk (1.18.0), however that fails too with the following error.

 _Collecting azureml-sdk==1.18.0
  Downloading azureml_sdk-1.18.0-py3-none-any.whl (4.4 kB)
ERROR: Could not find a version that satisfies the requirement azureml-core~=1.18.0 (from azureml-sdk)
ERROR: No matching distribution found for azureml-core~=1.18.0_

Link for the log file: [log.txt](https://github.com/Azure/MachineLearningNotebooks/files/5658546/log.txt)

**Comment by vizhur** [comment]
@akashpandey111 thank you for reporting the issue. New pip dependency resolver has some breaking changes. You should be able to mitigate the issue downgrading pip on your side

`python -m pip install -U pip==20.2.4`

**Comment by bandsina** [comment]
Hi @akashpandey111 , what is your scenario? Do you need any other package than azureml-core and azureml-dataprep? You shouldnt need azureml-train.

**Comment by akashpandey111** [comment]
@bandsina indeed, I do not need azureml-train as of now. I was following the documentation and going over each component in azureml-sdk and thought of installing them individually. Thanks for letting me know that it's deprecated!

@vizhur Thanks for your suggestion! I have downgraded Python to use Python 3.8.6 with Pip version as 20.2.1. However, there is an exception while installing build dependencies (log file linked at bottom).

[log.txt](https://github.com/Azure/MachineLearningNotebooks/files/5664021/log.txt)

**Comment by vizhur** [comment]
I'd think that's a system issue. Like xcode update or check with https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target

**Comment by akashpandey111** [comment]
@vizhur  I've updated the command line tools as mentioned in the link. Thank you so much for that!

Here's the most recent log:

[log.txt](https://github.com/Azure/MachineLearningNotebooks/files/5677507/log.txt)

**Comment by vizhur** [comment]
I'd think you need x64 python

**Comment by paulshealy1** [comment]
Python 3.9 is now supported.

**Comment by BenAji** [comment]
Please I have been having this issue but with python 3.10.4
Id like to know if it is supported
Thanks
