### ISSUE TITLE
How to specify location for an amlcompute provisioning.

### ISSUE THREAD

**Issue by dem108** [Azure/MachineLearningNotebooks#126]
Method `provision_configuration` does not have location variable. Is it possible to specify a location to provision this compute? We have a scenario for this, as not all VMs can be create everywhere. For example, GPU VMs.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 668817de-7350-c4fb-5652-70fa00aaf3cc
* Version Independent ID: ca7ff1c2-9009-d1ea-9471-7629642e1520
* Content: [azureml.core.compute.amlcompute.AmlCompute class - azureml - Azure Machine Learning SDK for Python](https://docs.microsoft.com/ko-kr/python/api/azureml-core/azureml.core.compute.amlcompute.amlcompute?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.compute.amlcompute.AmlCompute.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.compute.amlcompute.AmlCompute.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by nishankgu** [comment]
@dem108 - We restrict creating AmlCompute in the region of the workspace so the users dont pay data movement costs, and also ensure that user data is bounded to a region as much as possible. Which region are you working in, and what SKU are you interested in using?
Also, is it not possible to create the workspace in this other region?

Let us know - we are interested in hearing feedback.

**Comment by nishankgu** [comment]
Thanks for your feedback. We will continue to monitor this request and follow up.
