### ISSUE TITLE
AutoMLRun register_model fails with exception

### ISSUE THREAD

**Issue by amitca71** [Azure/MachineLearningNotebooks#1264]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-7c83818a7f6f> in <module>
      2 
      3 description = 'My AutoML Model'
----> 4 model = automl_run.register_model()
      5 
      6 print(run.model_id)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/train/automl/run.py in register_model(self, model_name, description, tags, iteration, metric)
    972         :rtype: Model
    973         """
--> 974         automl_settings = self._get_automl_settings()
    975         self._set_custom_dimensions(automl_settings)
    976         with logging_utilities.log_activity(

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/train/automl/run.py in _get_automl_settings(self)
    573         return AzureAutoMLSettings(
    574             experiment=self.experiment,
--> 575             **json.loads(self._get_property('AMLSettingsJsonString')))
    576 
    577     def get_children(

/anaconda/envs/azureml_py36/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346         if not isinstance(s, (bytes, bytearray)):
    347             raise TypeError('the JSON object must be str, bytes or bytearray, '
--> 348                             'not {!r}'.format(s.__class__.__name__))
    349         s = s.decode(detect_encoding(s), 'surrogatepass')
    350 

TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

the AutoMLRun itself looks fine, and completed status 
Experiment	Id	Type	Status	Details Page	Docs Page
readinessforecast	9441f57c-de08-4f47-b4b4-16850d1e87e9	azureml.PipelineRun	Completed	Link to Azure Machine Learning studio	Link to Documentation
(calling automl_run._get_automl_settings() yield same exception on 575             **json.loads(self._get_property('AMLSettingsJsonString'))) )

**Comment by arjsingh** [comment]
Hello, thanks for reaching out.

1. Could you please share the steps/code you used to get the automl_run, which is what you're using to register the model?
2. Assuming that automl_run is a pipeline run, you can use the below code snippet to register your model. Please replace automl_module" with the name you've chosen for your automl step.

```
automl_run_step = automl_run.find_step_run("automl_module")[0]
automl_step_run = AutoMLStepRun(automl_run_step)
automl_step_run.register_model()
	
```

3. There are other ways to register the model. Sharing the following notebook as an example:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/continuous-retraining/auto-ml-continuous-retraining.ipynb

**Comment by amitca71** [comment]
i did register the model as described in https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/continuous-retraining/auto-ml-continuous-retraining.ipynb. but then for the deployment i need to create init and so on... i thought to get it automatically by automl... 
anyway, is there away to get these deployment script for automl (i know to write it for other type of modles, but not sure how to do it for AutoML model. in addition, how do i make sure my FQDN is not changing, every time i deploy new model?

**Comment by arjsingh** [comment]
In order to both register and deploy the model you need both the parent and child runs. AutoML will automatically generate a scoring file per model and here's an example code snippet to both register and deploy. The file named _scoring_file_v_1_0_0.py_ is generated for every child run.

```
n = None  # set n to desired iteration or None for best model
registered_model = automl_run.register_model(iteration=n)
run, in_memory_model = automl_run.get_output(iteration=n)
run.download_file("outputs/scoring_file_v_1_0_0.py")
```

In order to keep the same FQDN, you'd need to call **update** on an existing webservice with a new model.
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aci.aciwebservice?preserve-view=true&view=azure-ml-py#update-image-none--tags-none--properties-none--description-none--auth-enabled-none--ssl-enabled-none--ssl-cert-pem-file-none--ssl-key-pem-file-none--ssl-cname-none--enable-app-insights-none--models-none--inference-config-none-

**Comment by amitca71** [comment]
thanks for the asnweres :-)
as you suggested, i use the alternative and not automl_run (as its failing...).
I found the generated script, but its failing during  deploy, with exception, during health check:
ModuleNotFoundError: No module named 'azureml.automl'

the code looks like:
from azureml.core.environment import Environment
from azureml.core.model import InferenceConfig
from azureml.core.conda_dependencies import CondaDependencies
conda_dep = CondaDependencies()
# Installs numpy version 1.17.0 conda package
conda_dep.add_conda_package("numpy==1.16.2")
conda_dep.add_conda_package("scikit-learn")
env = Environment.get(workspace=ws, name="AzureML-Minimal")
env.python.conda_dependencies=conda_dep

for pip_package in ['azureml','azureml-sdk[automl]', 'azureml-defaults']:
    env.python.conda_dependencies.add_pip_package(pip_package)
inference_config = InferenceConfig(entry_script='score.py',
                                    environment=env)
from azureml.core.webservice import LocalWebservice, Webservice
deployment_config = LocalWebservice.deploy_configuration(port=8890)
service = Model.deploy(ws, "myservice", [model], inference_config, deployment_config)
service.wait_for_deployment(show_output = True)


full log:
Downloading model delivery_prep_dur_eval:6 to /tmp/azureml_99t263cz/delivery_prep_dur_eval/6
Generating Docker build context.
Package creation Succeeded
Logging into Docker registry viennaglobal.azurecr.io
Logging into Docker registry viennaglobal.azurecr.io
Building Docker image from Dockerfile...
Step 1/5 : FROM viennaglobal.azurecr.io/azureml/azureml_19952de5360d0452e053615b352b988e
 ---> 6ab1f8f5d322
Step 2/5 : COPY azureml-app /var/azureml-app
 ---> 2efa06734084
Step 3/5 : RUN mkdir -p '/var/azureml-app' && echo eyJhY2NvdW50Q29udGV4dCI6eyJzdWJzY3JpcHRpb25JZCI6IjYwNzdmYzQ0LWQyMzgtNDIzMS04Y2ViLTBjNTZmOTg0Y2JmNCIsInJlc291cmNlR3JvdXBOYW1lIjoiYWktZGYiLCJhY2NvdW50TmFtZSI6ImFuaXQtYWkiLCJ3b3Jrc3BhY2VJZCI6ImI2MjRjNWIwLTU2ZjQtNDhkMS1iMThiLThhODgxZDg5NDZlZCJ9LCJtb2RlbHMiOnt9LCJtb2RlbHNJbmZvIjp7fX0= | base64 --decode > /var/azureml-app/model_config_map.json
 ---> Running in f7afc6f79477
 ---> cde2024e9e60
Step 4/5 : RUN mv '/var/azureml-app/tmp8x9c0wr0.py' /var/azureml-app/main.py
 ---> Running in 58e170059335
 ---> cba9f2db3297
Step 5/5 : CMD ["runsvdir","/var/runit"]
 ---> Running in 26f1f4c2d1cc
 ---> 8600130231ee
Successfully built 8600130231ee
Successfully tagged myservice:latest
Container (name:serene_babbage, id:97e6ea79c73f4bcacd17be3b034d8bf25a4ae6ff77b95c965cfd3c8584e1aa65) cannot be killed.
Container has been successfully cleaned up.
Image sha256:ca92a804b72d71f4520bad1e39e5e447c7fc786b162438f0255c2e0392d35e7c successfully removed.
Starting Docker container...
Docker container running.
Checking container health...
ERROR - Error: Container has crashed. Did your init method fail?


Container Logs:
/bin/bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by /bin/bash)
2020-12-23T14:39:41,626794569+00:00 - iot-server/run 
2020-12-23T14:39:41,628201578+00:00 - rsyslog/run 
2020-12-23T14:39:41,628644881+00:00 - gunicorn/run 
bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by bash)
2020-12-23T14:39:41,640286758+00:00 - nginx/run 
/usr/sbin/nginx: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libcrypto.so.1.0.0: no version information available (required by /usr/sbin/nginx)
/usr/sbin/nginx: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libcrypto.so.1.0.0: no version information available (required by /usr/sbin/nginx)
/usr/sbin/nginx: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libssl.so.1.0.0: no version information available (required by /usr/sbin/nginx)
/usr/sbin/nginx: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libssl.so.1.0.0: no version information available (required by /usr/sbin/nginx)
/usr/sbin/nginx: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libssl.so.1.0.0: no version information available (required by /usr/sbin/nginx)
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
/bin/bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by /bin/bash)
2020-12-23T14:39:41,718143876+00:00 - iot-server/finish 1 0
2020-12-23T14:39:41,719417385+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.9.0
Listening at: http://127.0.0.1:31311 (11)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 41
SPARK_HOME not set. Skipping PySpark Initialization.
Exception in worker process
Traceback (most recent call last):
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/var/azureml-server/wsgi.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 3, in <module>
    from app import main
  File "/var/azureml-server/app.py", line 32, in <module>
    from aml_blueprint import AMLBlueprint
  File "/var/azureml-server/aml_blueprint.py", line 33, in <module>
    main_module_spec.loader.exec_module(main)
  File "/var/azureml-app/score.py", line 12, in <module>
    import azureml.automl.core
ModuleNotFoundError: No module named 'azureml.automl'
Worker exiting (pid: 41)
Shutting down: Master
Reason: Worker failed to boot.
/bin/bash: /azureml-envs/azureml_f7834da2edca74e44d923018c85f9f6f/lib/libtinfo.so.5: no version information available (required by /bin/bash)
2020-12-23T14:39:42,620062877+00:00 - gunicorn/finish 3 0
2020-12-23T14:39:42,621353685+00:00 - Exit code 3 is not normal. Killing image.

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
<ipython-input-51-1fa1c3684350> in <module>
      3 deployment_config = LocalWebservice.deploy_configuration(port=8890)
      4 service = Model.deploy(ws, "myservice", [model], inference_config, deployment_config)
----> 5 service.wait_for_deployment(show_output = True)
      6 print(service.state)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/webservice/local.py in decorated(self, *args, **kwargs)
     70                 raise WebserviceException('Cannot call {}() when service is {}.'.format(func.__name__, self.state),
     71                                           logger=module_logger)
---> 72             return func(self, *args, **kwargs)
     73         return decorated
     74     return decorator

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/webservice/local.py in wait_for_deployment(self, show_output)
    609                                    self._container,
    610                                    health_url=self._get_health_url(),
--> 611                                    cleanup_if_failed=False)
    612 
    613             self.state = LocalWebservice.STATE_RUNNING

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_model_management/_util.py in container_health_check(docker_port, container, health_url, cleanup_if_failed)
    741             # The container has started and crashed.
    742             _raise_for_container_failure(container, cleanup_if_failed,
--> 743                                          'Error: Container has crashed. Did your init method fail?')
    744 
    745         # The container hasn't crashed, so try to ping the health endpoint.

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_model_management/_util.py in _raise_for_container_failure(container, cleanup, message)
   1259         cleanup_container(container)
   1260 
-> 1261     raise WebserviceException(message, logger=module_logger)
   1262 
   1263 

WebserviceException: WebserviceException:
	Message: Error: Container has crashed. Did your init method fail?
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Error: Container has crashed. Did your init method fail?"
    }
}

**Comment by amitca71** [comment]
Thanks for your assistance :-)

i took your advise and  used the generated scoring script, with the manual deployment ( i cant use auto_ml, as its failing with th einitial issue), but the model is not found by the path.
FileNotFoundError: [Errno 2] No such file or directory: 'azureml-models/delivery_prep_dur_eval/7/model.pkl'
and the model looks like:
Model(workspace=Workspace.create(name='XXX', subscription_id='XXXXXX', resource_group='XXX'), name=delivery_prep_dur_eval, id=delivery_prep_dur_eval:7, version=7, tags={}, properties={})
the init from score.py looks like:
def init():
    global model
    # This name is model.id of model that we want to deploy deserialize the model file back
    # into a sklearn model
    model_path = os.path.join(os.getenv('AZUREML_MODEL_DIR'), 'model.pkl')
    try:
        model = joblib.load(model_path)

AZUREML_MODEL_DIR- does not reflect the path....

the full code is:
from azureml.core.model import Model
model = Model(ws, 'delivery_prep_dur_eval')
from azureml.core.environment import Environment
from azureml.core.model import InferenceConfig
from azureml.core.conda_dependencies import CondaDependencies
conda_dep = CondaDependencies()
# Installs numpy version 1.17.0 conda package
conda_dep.add_conda_package("numpy==1.16.2")
conda_dep.add_conda_package("scikit-learn[alldeps]")
env = Environment('my-test-environment')
env.python.conda_dependencies=conda_dep

for pip_package in ['azureml','azureml-sdk[automl]', 'azureml-defaults','joblib', 'inference_schema']:
    env.python.conda_dependencies.add_pip_package(pip_package)
inference_config = InferenceConfig(entry_script='score.py',
                                    environment=env)

from azureml.core.webservice import LocalWebservice, Webservice
deployment_config = LocalWebservice.deploy_configuration(port=8890)
service = Model.deploy(ws, "myservice", [model], inference_config, deployment_config)
service.wait_for_deployment(show_output = True)
print(service.state)







2020-12-23 16:42:51,235 | root | ERROR | Encountered Exception Traceback (most recent call last):
  File "/var/azureml-server/aml_blueprint.py", line 177, in register
    main.init()
  File "/var/azureml-app/score.py", line 37, in init
    model = joblib.load(model_path)
  File "/azureml-envs/azureml_3f1ffc7e7d20cd4c3d307a3605357254/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'azureml-models/delivery_prep_dur_eval/7/model.pkl'

Encountered Exception Traceback (most recent call last):
  File "/var/azureml-server/aml_blueprint.py", line 177, in register
    main.init()
  File "/var/azureml-app/score.py", line 37, in init
    model = joblib.load(model_path)
  File "/azureml-envs/azureml_3f1ffc7e7d20cd4c3d307a3605357254/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'azureml-models/delivery_prep_dur_eval/7/model.pkl'

/azureml-envs/azureml_3f1ffc7e7d20cd4c3d307a3605357254/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)

**Comment by arjsingh** [comment]
Could you please share all the steps you performed from the beginning, including what notebook/code-snippet you've executed to get to this point?

Also, could you share how you're deploying the model? Are you creating your own environment, using our conda_env file from the run, or reusing the training environment?

**Comment by amitca71** [comment]
i create new environment.

code below:
#notebook.ipynb:
from azureml.train.automl import AutoMLConfig
from azureml.pipeline.steps import AutoMLStep
train_ds =train_dataset.parse_parquet_files()
automl_settings = {
    "iteration_timeout_minutes": 3,
    "experiment_timeout_hours": 0.25,
    "n_cross_validations": 3,
    "primary_metric": 'normalized_mean_absolute_error',
    "max_concurrent_iterations": 3,
    "max_cores_per_iteration": -1,
    "verbosity": logging.INFO,
    "enable_early_stopping": True
}

automl_config = AutoMLConfig(task = 'regression',
                             debug_log = 'automl_errors.log',
                             path = ".",
                             compute_target=compute_target,
                             training_data = train_ds,
                             label_column_name = target_column_name,
                             **automl_settings
                            )


from azureml.pipeline.core import PipelineData, TrainingOutput

metrics_output_name = 'metrics_output'
best_model_output_name = 'best_model_output'

metrics_data = PipelineData(name='metrics_data',
                           datastore=datastore,
                           pipeline_output_name=metrics_output_name,
                           training_output=TrainingOutput(type='Metrics'))
model_data = PipelineData(name='model_data',
                           datastore=datastore,
                           pipeline_output_name=best_model_output_name,
                           training_output=TrainingOutput(type='Model'))
						   
automl_step = AutoMLStep(
    name='automl_module',
    automl_config=automl_config,
    outputs=[metrics_data, model_data],
    allow_reuse=False)

ds_name = PipelineParameter(name="ds_name", default_value=dataset)
model_name = PipelineParameter("model_name", default_value="delivery_prep_dur_eval")
register_model_step = PythonScriptStep(script_name="register_model.py",
                                       name="register_model",
                                       allow_reuse=False,
                                       arguments=["--model_name", model_name, "--model_path", model_data, "--ds_name", ds_name],
                                       inputs=[model_data],
                                       compute_target=compute_target,
                                       runconfig=conda_run_config)
training_pipeline = Pipeline(
    description="training_pipeline",
    workspace=ws,    
    steps=[dbricks_create_data_step,data_prep_step, automl_step, register_model_step])
training_pipeline_run = experiment.submit(training_pipeline)


from azureml.core.model import Model
model = Model(ws, 'delivery_prep_dur_eval')

from azureml.core.environment import Environment
from azureml.core.model import InferenceConfig
from azureml.core.conda_dependencies import CondaDependencies
conda_dep = CondaDependencies()
# Installs numpy version 1.17.0 conda package
conda_dep.add_conda_package("numpy==1.16.2")
conda_dep.add_conda_package("scikit-learn[alldeps]")
env = Environment('my-test-environment')
env.python.conda_dependencies=conda_dep

for pip_package in ['azureml','azureml-sdk[automl]', 'azureml-defaults','joblib', 'inference_schema']:
    env.python.conda_dependencies.add_pip_package(pip_package)
inference_config = InferenceConfig(entry_script='score.py',
                                    environment=env)
									
from azureml.core.webservice import LocalWebservice, Webservice
deployment_config = LocalWebservice.deploy_configuration(port=8890)
service = Model.deploy(ws, "myservice", [model], inference_config, deployment_config)
service.wait_for_deployment(show_output = True)
print(service.state)									


#register_model.py:
from azureml.core.model import Model, Dataset
from azureml.core.run import Run, _OfflineRun
from azureml.core import Workspace
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--model_name")
parser.add_argument("--model_path")
parser.add_argument("--ds_name")
args = parser.parse_args()

print("Argument 1(model_name): %s" % args.model_name)
print("Argument 2(model_path): %s" % args.model_path)
print("Argument 3(ds_name): %s" % args.ds_name)

run = Run.get_context()
ws = None
if type(run) == _OfflineRun:
    ws = Workspace.from_config()
else:
    ws = run.experiment.workspace

train_ds = Dataset.get_by_name(ws, args.ds_name)
datasets = [(Dataset.Scenario.TRAINING, train_ds)]

# Register model with training dataset

model = Model.register(workspace=ws,
                       model_path=args.model_path,
                       model_name=args.model_name,
                       datasets=datasets)
print ("AMIT    model_path:")
print(args.model_path,args.model_name, datasets )

**Comment by arjsingh** [comment]
The following code in the notebook is already registering the model for you and you can see the model in your workspace with the name "noaaweatherds".

```
register_model_step = PythonScriptStep(script_name="register_model.py",
                                       name="register_model",
                                       allow_reuse=False,
                                       arguments=["--model_name", model_name, "--model_path", model_data, "--ds_name", ds_name],
                                       inputs=[model_data],
                                       compute_target=compute_target,
                                       runconfig=conda_run_config)
```

Additionally, if you do want to download the pkl file and then register the model yourself, you could follow the next two steps:

```
import pickle
model_output = training_pipeline_run.get_pipeline_output(best_model_output_name)
model_output.download("model_pkl_dir")
with open("model_pkl_dir\\azureml\\<some_coded_path>\\model_data", "rb") as f:
    m = pickle.load(f)

```
```
from azureml.core.model import Model
model_reg = Model.register(workspace=ws,
                       model_path="model_pk_dirl\\azureml\\<some_coded_path>\\model_data",
                       model_name="some_model_name")
```

**Comment by temiwale88** [comment]
Hello Arjun, in line with getting outputs from a pipeline. I'm having issues following the pattern in this [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb):
```
best_run, fitted_model = remote_run.get_output()
```

This notebook uses AutoML without a pipeline strategy.
How do I retrieve the best_run from a pipeline run?

Thanks,
Elijah

**Comment by temiwale88** [comment]
Thank you God! Got it so nevermind. 
For those who might want to use AutoML in an AutoMLStep of your experiment pipleine - to retrieve the AutoML details e.g.  your "best_run" and "fitted_model" - try the following: 

- Find your AutoMLStep by its name e.g.
```
step_run = pipeline_run.find_step_run("AutoML_Step")[0] #whatever you called your Pipeline Run e.g. "pipeline_run"
```
- Then declare a variable that inherits the AutoMLRun class and its associated properties e.g. ".get_output()":
```
from azureml.train.automl.run import AutoMLRun

autoMlStepRunId = step_run.id

experiment_run = ws.experiments[<'your experiment name'>] #requires your workspace details passed to 'ws' variable.
automl_step_run = AutoMLRun(experiment_run, run_id = autoMlStepRunId)
automl_step_run
```

And you should be able to proceed from there.
All the best!

**Comment by ahyerman** [comment]
#please-close
