### ISSUE TITLE
Speed issues with LightGBM as part of Sklearn pipelines

### ISSUE THREAD

**Issue by waiyujack** [Azure/MachineLearningNotebooks#1268]
Hi all

I have done some speed tests on getting the prediction out using the following two sklearn pipelines

pipeline 1: simple imputation + sklearn gbm
pipeline 2: simple imputation + lightgbm

So the only difference is swapping the gbm function with the Scikit-learn API lightgbm function and they are both embedded in a sklearn pipeline and then deploy to a aks service cluster ( with same specification).

Even though I have set some similar parameters (say number of trees/ iterations), the prediction time for lightgbm pipeline seems to be much slower than the first piepline. (400 ms as compared to 50ms for one row/ record).

Does anyone have any ideas? Please let me know if this is not the suitable place for the question.

**Comment by shbijlan** [comment]
Hi @waiyujack our team tracks issues with AML pipelines in this repo, not sklearn pipelines.
