### ISSUE TITLE
Missing details on including the 'Azure-Monitoring' package in the conda-dependency for the web service

### ISSUE THREAD

**Issue by MustAl-Du** [Azure/MachineLearningNotebooks#1269]
There is a missing section in the page. The 'ModelDataCollector' will not work in the AKS web service unless the 'Azure-Monitoring' pip package is included in the conda dependency of the web service.

**Please, revise the current python snippet:**
"
webservice_config = AksWebservice.deploy_configuration(collect_model_data=True)
Model.deploy(ws, "myservice", [model], inference_config, webservice_config, aks_cluster)
"

**to this corrected version:**

"
env = Environment('deploytwebserviceenv')
env.python.conda_dependencies = CondaDependencies.create(conda_packages=['numpy'],pip_packages=['azureml-defaults','azureml-monitoring','inference-schema[numpy-support]'])
inference_config = InferenceConfig(entry_script="score.py", environment=env)

webservice_config = AksWebservice.deploy_configuration(collect_model_data=True)
Model.deploy(ws, "myservice", [model], inference_config, webservice_config, aks_cluster)
"

This issue was previously raised in (https://github.com/Azure/MachineLearningNotebooks/issues/1037) and not correctly resolved (Jadhosne who created the issue never confirmed the fix).

I have created a complete notebook with the correct configuration here: https://github.com/MustAl-Du/AzureMachineLearning/blob/main/diabetescsv-regression-aks-drift/diabetescsv-regression-aks-drift.ipynb

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63501a75-ac56-360f-fd2f-9b47980943dd
* Version Independent ID: 922345ef-a929-7202-b76a-668f95695f35
* Content: [azureml.monitoring.modeldatacollector.ModelDataCollector class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-monitoring/azureml.monitoring.modeldatacollector.modeldatacollector?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-monitoring/azureml.monitoring.modeldatacollector.ModelDataCollector.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-monitoring/azureml.monitoring.modeldatacollector.ModelDataCollector.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by shivanissambare** [comment]
Hi,
Thank you for the feedback!

In our documentation: 

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-enable-data-collection#enable-data-collection

Our documentation includes:
7. Add the 'Azure-Monitoring' pip package to the conda-dependencies of the web service environment:

````python
env = Environment('webserviceenv')
  env.python.conda_dependencies = CondaDependencies.create(conda_packages=['numpy'],pip_packages=['azureml-defaults','azureml-monitoring','inference-schema[numpy-support]'])

**Comment by shivanissambare** [comment]
Please re-open if you have any other feedback or issue following our docs :)

Thanks,
Shivani S.S.
