### ISSUE TITLE
train-hyperparameter-tune-deploy-with-tensorflow 

### ISSUE THREAD

**Issue by JonnyThePython** [Azure/MachineLearningNotebooks#127]
Hi, when I try to save the model using this code: 

model = best_run.register_model(model_name='tf-dnn-mnist', model_path='outputs/model')

It gives me this: 

Deprecated, use RunHistoryFacade.assets instead. 

Any help would be appreciated.

**Comment by mx-iao** [comment]
@JonnyThePython The `register_model` function works; in the next release we will be fixing the deprecation warning
