### ISSUE TITLE
 There should be an option to specify the namespace

### ISSUE THREAD

**Issue by andremarques023** [Azure/MachineLearningNotebooks#1270]
AksAttachConfiguration and AksProvisioningConfiguration classes should include namespace configuration parameters for attaching and provisioning AksCompute targets. Currently, kubernetes objects are created in the default namespace.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 24563085-8fca-ffc2-6f61-de4020b95ee3
* Version Independent ID: 8cd65fcd-30ad-a79c-9dd7-26a8f322adff
* Content: [azureml.core.compute.aks.AksAttachConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/pt-br/python/api/azureml-core/azureml.core.compute.aks.aksattachconfiguration?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.compute.aks.AksAttachConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.compute.aks.AksAttachConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by shivanissambare** [comment]
@brendalee can you help with this?

**Comment by sauryadas** [comment]
This is a known issue but we do not have a plan in the next quarter to fix this. 

@andremarques023 Do you want to be able to specify where the scoring fe, etc pods/services go into or would it be fine if we placed in a pre created NS like 'azureml' .. this would be similar to placing system pods in 'kube-system'

**Comment by andremarques023** [comment]
I'd like to be able to specify that but having the resources deployed into a predefined namespace like you suggested would be great for now.

Thanks!

**Comment by sauryadas** [comment]
@brendalee @shivanissambare Can one of you tag this as a feature ask ? and its probably best for @Bozhong68 to own this

**Comment by Bozhong68** [comment]
This will be supported in AmlArc inference private preview: https://github.com/Azure/amlarc-preview
