### ISSUE TITLE
AutoMLStep name parameter can not contain whitespaces

### ISSUE THREAD

**Issue by justas-exadel** [Azure/MachineLearningNotebooks#1273]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3522144-f5a3-ebcd-051d-08719a2d867c
* Version Independent ID: e6b3374d-8b16-e798-2085-cb6dab7ffb0c
* Content: [azureml.pipeline.steps.AutoMLStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.automlstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.AutoMLStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.AutoMLStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by justas-exadel** [comment]
I created a pipeline of different steps. PythonScriptStep name has no restrictions while AutoMLStep can not contain whitespaces or dashes.

**Comment by CESARDELATORRE** [comment]
@justas-exadel Just to make sure, do you mean that "AutoMLStep can not contain whitespaces" in the AutoMLStep's **name** parameter? 

Please, confirm. 

In any case, I'll create an internal issue in order to investigate it. I agree that AutoMLStep and PythonScriptStep should be consistent in parameters and behavior.

**Comment by justas-exadel** [comment]
> @justas-exadel Just to make sure, do you mean that "AutoMLStep can not contain whitespaces" in the AutoMLStep's "**name**" parameter? or any other parameter?
> 
> Please, confirm.
> 
> In any case, I'll create an internal issue in order to investigate it. I agree that AutoMLStep and PythonScriptStep should be consistent in parameters and behavior.

Correct, AutoMLStep "**name**" parameter can not contain whitespaces.

**Comment by CESARDELATORRE** [comment]
Fyi @anupsms 
I created an internal VSO issue to tack down this issue:
https://msdata.visualstudio.com/Vienna/_workitems/edit/995841

**Comment by CESARDELATORRE** [comment]
Closing this issue as the bug was fixed in a PR within the product.
Thanks for raising the issue.

This fix will be released on Feb. 8th 2021 as part of a release.
