### ISSUE TITLE
Broken link in deploy-multi-model

### ISSUE THREAD

**Issue by sharatsc** [Azure/MachineLearningNotebooks#1274]
Notebook example link in 

Source page:  https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/deployment/deploy-multi-model 
Broken link: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-multi-model/model-register-and-deploy.ipynb

**Comment by shivanissambare** [comment]
can you please try again, the link is fixed:

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-multi-model/multi-model-register-and-deploy.ipynb

**Comment by shivanissambare** [comment]
please re-open the issue if the link is still is not working for you :)
