### ISSUE TITLE
Issue while redeploying the Ml model into AKS Instance

### ISSUE THREAD

**Issue by devendraks** [Azure/MachineLearningNotebooks#1275]
Hi,

I am have deployed ML model in Azure AKS compute instance. I have an issue while redeploying the model with the same endpoint name as it throws the following error. "WebserviceException: WebserviceException:
	Message: Deployment request failed due to insufficient compute resource. For the specified compute target, 1 replica cannot be created per specified CPU/Memory configuration(1 CPU Cores, 2GB Memory). You can address this problem by adjusting number of replicas, using a different CPU/memory configuration, or using a different compute target."

However, if delete the endpoint manually and re-run this works fine but the issue issue is, it creates a new key everytime and hence I wont be able to use it in production. May I please get immediate help to address the two problems I mentioned above 1) How re-deploy in AKS
2) How can I get the same auth key even when I redeploy

Any immediate help here is highly appreciated.

Thank you,
Devendra
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1a7ca9-d49f-d32c-8b43-3e8fc9576815
* Version Independent ID: bc09c6bb-e989-14e6-5ab4-06a1fcd2f3a1
* Content: [azureml.core.webservice.aks.AksWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aks.akswebservice?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.aks.AksWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.aks.AksWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by SAIVENKATARAJU** [comment]
Hi 
Did you find the solution, I am also getting the same error. I have also tried deleting end points but issue is still there.

**Comment by devendraks** [comment]
Hi,

Yes, I was able to get through the issue. It is basically due to the system
configuration you use for deployment. I tried with default configuration
which is 0.1 CPU and 0.5 RAM and tried redeploying and it worked. Please
let me know if you have any questions.

Regards,
Devendra

**Comment by SAIVENKATARAJU** [comment]
Hi @devendraks ,

Thanks for your comment. issues did not get resolved even I tried with default configuration. Here is the error. Also is this related our quota and usage. Currently, I have quota 10 cores and i have used 6 cores for GPU(Standard NC Family vCPUs).
`
` "message": "Deployment request failed due to insufficient compute resource. For the specified compute target, 1 replica cannot be created per specified CPU/Memory configuration(0.1 CPU Cores, 0.5GB Memory). You can address this problem by adjusting number of replicas, using a different CPU/memory configuration, or using a different compute target."

`
`

**Comment by devendraks** [comment]
Hi Sai,

Sorry for being very late to reply. I am able to relate to the issue that I
have faced in this regard and there are solutions in combination that
worked for me. First, keeping the default core size and memory. Second,
upgrading the AKS cluster to a higher configuration. If first one doesn't
work, second one would work for sure because, I have tried it multiple
times and it has worked for me.

I hope this answer would be of help.

Regards,
Devendra

**Comment by shivanissambare** [comment]
Hi, are you still facing this issue?
Please take a look at our updating web service documentation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-update-web-service

To update a web service, use the `update` method. You can update the web service to use a new model, a new entry script, or new dependencies that can be specified in an inference configuration.

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.akswebservice?view=azure-ml-py#methods

Use `get_access_token` method to retrieve auth token.

**Comment by shivanissambare** [comment]
Closing this issue, please feel free to reopen if you have any more questions/concerns/issues.

Thank you!

**Comment by v-ravikumar** [comment]
I also faced same problem 2 days back. 
I found a workaround:
**Go to the AKS Kubernetes service on azure portal then go to node pools, you will find an option of scale node pool , now increase or decrease the number of nodes and apply. You will see that now the aks model redeployment will happen successfully.**
