### ISSUE TITLE
How do call Localwebservice with python requests.

### ISSUE THREAD

**Issue by NSVR57** [Azure/MachineLearningNotebooks#1276]
Hi,

I Have deployed a sample Local webservice and trying to consume with requests package. but ending up with this error.

```
import requests
import json
import numpy as np
from PIL import Image
from azureml.core.authentication import InteractiveLoginAuthentication
import pandas as pd

uri="https://test-sss-32773.westus2.instances.azureml.net/score"
interactive_auth = InteractiveLoginAuthentication()
auth_header = interactive_auth.get_authentication_header()

# Create and submit a request using the auth header
headers = auth_header
# Add content type header
headers.update({'Content-Type':'application/json'})


res=requests.get(uri,headers)
print(res.text)
```
ERROR:

> 
> 
> <!DOCTYPE html>
> <html dir="ltr" class="" lang="en">
> <head>
>     <title>Sign in to your account</title>
>     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
>     <meta http-equiv="Pragma" content="no-cache">
>     <meta http-equiv="Expires" content="-1">
>     
>     <meta name="PageID" content="ConvergedError" />
>     <meta name="SiteID" content="" />
>     <meta name="ReqLC" content="1033" />
>     <meta name="LocLC" content="en-US" />
> 
>         <meta name="referrer" content="origin" />
> 
>     <noscript>
>         <meta http-equiv="Refresh" content="0; URL=" />
>     </noscript>

**Comment by shivanissambare** [comment]
Please take a look at this documentation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-local-container-notebook-vm#test-the-service

Or this notebook : https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-to-local/register-model-deploy-local.ipynb

Our Python SDK reference: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.local.localwebservice?view=azure-ml-py#methods

`local_service.run(sample_input)`

**Comment by shivanissambare** [comment]
please, feel free to re-open the issue if you have more questions
