### ISSUE TITLE
Cannot submit job into AML in ubuntu 

### ISSUE THREAD

**Issue by cddlyf** [Azure/MachineLearningNotebooks#1278]
Today, when our team (microsoft internal team) members try to submit job onto azure ml by using the ubuntu machine, it will always encounter the authentication error. Please help solve this problem ASAP, tks!

![Capture](https://user-images.githubusercontent.com/7030833/103332402-a2754200-4a1e-11eb-9a39-ae1317a16e40.PNG)

**Comment by paulshealy1** [comment]
Resolved per an offline discussion with @cddlyf.
