### ISSUE TITLE
DataTransformer cannot be used in sklearn ColumnTransformer

### ISSUE THREAD

**Issue by alanflanders-teck** [Azure/MachineLearningNotebooks#1279]
I'm trying to use the DataTransformer in my pipeline but get an error when trying to use it with a ColumnTransformer

Code:
`from azureml.automl.runtime.featurization.data_transformer import DataTransformer

combined_features = ColumnTransformer(
    transformers=[
     ('data_transformer', DataTransformer(), [1, 2, 3])
     ],
     remainder='drop')

combined_features.fit(partial_data)
`

Error:
`/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/automl/runtime/featurization/data_transformer.py in __init__(self, task, is_onnx_compatible, logger, observer, enable_feature_sweeping, enable_dnn, force_text_dnn, feature_sweeping_timeout, featurization_config, is_cross_validation, feature_sweeping_config, working_dir)
    125         if task not in constants.Tasks.ALL:
    126             raise DataTransformerUnknownTaskException(
--> 127                 "Unknown task", has_pii=False, reference_code=ReferenceCodes._DATA_TRANSFORMER_UNKNOWN_TASK)
    128 
    129         # TODO: Remove this

DataTransformerUnknownTaskException: DataTransformerUnknownTaskException:
	Message: Unknown task
	InnerException: None
	ErrorResponse 
{ ...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2208e7f-6a56-b6fc-a655-d8e53f7a4424
* Version Independent ID: ca52ef9e-e699-504d-c99b-3a82d7ef0c5a
* Content: [azureml.automl.runtime.featurization.data_transformer.DataTransformer class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-automl-runtime/azureml.automl.runtime.featurization.data_transformer.datatransformer?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-automl-runtime/azureml.automl.runtime.featurization.data_transformer.DataTransformer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-runtime/azureml.automl.runtime.featurization.data_transformer.DataTransformer.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by kvijaykannan** [comment]
Thanks for sharing these details. Could you please share more details around what you are trying to do - which will help us to understand the scenario and provide recommendations.

**Comment by rtanase** [comment]
@alanflanders-teck, it looks like you're not passing in any arguments to the constructor / __init__ method of the DataTransformer class.

**Comment by alanflanders-teck** [comment]
Thanks for the replies.
I'm trying to apply the DataTransformer transformer to one set of columns and a different transformer to other columns and combine them using the ColumnTransformer. Regardless, is there a way to use DataTransformer with the ColumnTransformer class?
According to the docs the constructor does not have any required parameters:
https://github.com/Azure/MachineLearningNotebooks/issues/1279#issuecomment-757042581

**Comment by svaruag** [comment]
@alanflanders-teck Thanks for your responses, and bringing this to our attention. Unfortunately, we haven't intended for 'DataTransformer' to be used in sklearn's ColumnTransformers, or even to be called outside of AutoML context yet. There's some internal state for that class, which is extremely tied to the auto featurization of data that we currently do in AutoML.

Apologize for the confusion, just looking by the namespace, class name (given that it's a public class), the fact that it follows sklearn's fit / transform contracts., it's completely normal to think that it can be substituted for a sklearn transformer and be used in a pipeline as is.

May I ask what is your intended use case? We do have plans to expose the complete auto-featurization logic to the public, with well defined contracts, but it's not there yet. Until then, you may consider submitting a regular AutoML experiment, with custom featurization for the columns that you don't want to featurize (e.g., you maybe transforming it outside of an AutoML context). Please refer to the custom featurization documentation [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-features#customize-featurization).

Happy to answer any questions that may come out of this. Cheers!

**Comment by svaruag** [comment]
Please feel free to re-open this in case there are any follow ups that you need from us.
