### ISSUE TITLE
cannot import 'AutoMLConfig from azureml.train.automl

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#128]
I tried to create a fresh environment using the three methods below. No matter what I can't import from azureml.train.automl. Help!

1. using `automl/automl_env.yml` from this repo: `conda create env -n AML_BTB -f automl_env.yml` 
2. The instructions given [here](https://docs.microsoft.com/en-us/azure/machine-learning/service/quickstart-create-workspace-with-python#install-the-sdk-1).
3. The instructions listed [here](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/intro?view=azure-ml-py): `pip install --upgrade azureml-sdk[notebooks,automl]`
4. The instructions listed [here](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment)
```
>>> from azureml.train.automl import AutoMLConfig
3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)]
C:\Users\swanderz\Documents\attrition\aml_config\config.json
Found the config file in: C:\Users\swanderz\Documents\attrition\aml_config\config.json
avadevitsmlsvc  westus2 RG-ITSMLTeam-Dev        westus2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\swanderz\AppData\Local\Continuum\anaconda3\envs\AML_BTB\lib\site-packages\azureml\train\automl\__init__.py", line 12, in <module>
    from automl.client.core.common.utilities import extract_user_data, get_sdk_dependencies
  File "C:\Users\swanderz\Documents\attrition\automl.py", line 40, in <module>
    from azureml.train.automl import AutoMLConfig
ImportError: cannot import name 'AutoMLConfig'
```

**Comment by swanderz** [comment]
sometimes i get this error.
should i be installing `matplotlib` before azureml-sdk? How about `cython` or `numpy`?
```
>>> import azureml.train.automl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\swanderz\AppData\Local\Continuum\anaconda3\envs\AML1707\lib\site-packages\azureml\train\automl\__init__.py", line 12, in <module>
    from automl.client.core.common.utilities import extract_user_data, get_sdk_dependencies
  File "C:\Users\swanderz\Documents\attrition\automl.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by jeff-shepherd** [comment]
matplotlib is included in the automl_env.yml.  So, you may be missing this if you just did "pip install --upgrade azureml-sdk[notebooks,automl]" rather than "conda create env -n AML_BTB -f automl_env.yml.".   matplotlib is not part of the core automl but is used in some of the sample notebooks.

In general I would recommend "conda create env -n AML_BTB -f automl_env.yml", which we also have wrapped by automl_setup.cmd.  There is a README.md under https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning, which has more details.

Can you sent the output of "pip list" from the environment that you created (AML_BTB) ?

**Comment by swanderz** [comment]
Hi jeff. Just tried again creating the environment from the automl_env.yml ( which i renamed to AMLjeff :) ),
Unfortunately, I still get an error from `azureml.train.automl` I've had this issue for the past 3 days and my coworker hasn't been able to help me. I have however, learned a great deal about Conda.

More info:After a lot of the messages like the following:
```
Requirement already satisfied: webencodings in c:\users\anders.swanson\appdata\local\continuum\anaconda3\envs\amljeff\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets>=7.0.0->azureml-widgets==1.0.2.*; extra == "notebooks"->azureml-sdk[automl,explain,notebooks]->-r C:\Users\anders.swanson\Documents\attrition\condaenv.xq0t5l_w.requirements.txt (line 2)) (0.5.1)
```
I get this
```
azure-cli-core 2.0.52 has requirement wheel==0.30.0, but you'll have wheel 0.32.3 which is incompatible.
azureml-train-automl 1.0.2 has requirement wheel==0.30.0, but you'll have wheel 0.32.3 which is incompatible.
```

Then a bunch of these
```
The script chardetect.exe is installed in 'C:\Users\anders.swanson\AppData\Local\Continuum\anaconda3\envs\AMLjeff\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this
warning, use --no-warn-script-location.
```

**Comment by jeff-shepherd** [comment]
The wheel messages are normal and don't cause an error when running AutoML. 
Also, the script not in the path warnings are normal.  automl_setup.cmd suppresses them.
I don't see any issue with your pip list.  The necessary libraries are present.

Can you make sure that this environment is active when you start jupyter notebook?  
       conda activate AMLjeff 

Make sure that the correct kernel is active.  This is selected with the Kernel | Change Kernel menu option.

If you still see the problem.  Download the latest automl_env.yml and automl_setup.cmd for GitHub https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning and try updating conda with the command "conda update conda".  Then try running the script automl_setup and pass a new environment name.

**Comment by swanderz** [comment]
hey jeff. really appreciate your help here. 

My troubleshooting instinct is to remove complexity so I've been troubleshooting with python 3 in the command line.

here's the steps i just took:
1. downloaded the `automl_env.yml` (i renamed it because you can't pass a name parameter to 'conda create env' when you're building from a yml file
2. ran `conda create env  -f AMLjeff.yml`
3. after install, `activate AMLjeff
4. launch `python`
5. `import azureml.train.automl` -> ERROR

My theory is that maybe my conda installation is corrupted and I should start from scratch with that...

**Comment by jeff-shepherd** [comment]
Thanks for the details.
I tried the sequence that you listed and it worked for me with a minor modification.
"conda create env" doesn't work on my system.  I used "conda env create" instead (like in the automl_setup.cmd).

When I run python, it shows:
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)] on win32

What do you see?

On your comment "(i renamed it because you can't pass a name parameter to 'conda create env' when you're building from a yml file", I can specify both -f and -n when using "conda env create".  The -n overrides the "name:" value in the yml file.
If I don't specify -n, it uses the "name:" value in the yml file as the environment name.  The name of the file doesn't matter.
Did you change the "name:" value inside AMLjeff.yml?
If you didn't, the environment name would be azure_automl rather than AMLjeff.

If you did, I agree that it looks like an issue with your conda installation.  You could try upgrading with "conda update conda" or just installing again.

**Comment by swanderz** [comment]
just now I've:
1. completely uninstalled conda and reinstalled
2. built the azure_automl env using `azure_automl.cmd`
3. Got `from azureml.train.automl import AutoMLConfig` to work.

I think I've isolated the issue to the VSCode Jupyter Extension. When the AML extension rebranded, I thought to try the Jupyter extension instead of AI tool's "open in jupyter server". The past two days has taught me otherwise!

I'm abandoning the idea of a REPL inside of VSCode and going back to jupyter as my IDE from here on out.

Thanks for all the support.

**Comment by DieselAnalytics** [comment]
Thanks @swanderz! Your days of frustration that led you to your solution enabled me to solve the same problem in minutes.

**Comment by swanderz** [comment]
@DieselAnalytics made my day thanks

**Comment by smfahad** [comment]
@swanderz could you please point me to where i will find azure_automl.cmd file to setup the environment in conda

**Comment by swanderz** [comment]
@smfahad setting up an azureml conda env can be tricky especially when automl is involved. Do you want to run the automl on your local machine or on an Azure ML compute target?

Check out [this folder](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning), and read the README. The `.cmd` file is there.

**Comment by smfahad** [comment]
@swanderz I want to setup in my local machine. I trained a model using AzureML studio, now i want to run the model in my local machine. I completely uninstall and reinstall conda. Then i use automl_setup.cmd to setup a new environment as mentioned in README file but when i execute my code, i am still getting error.

ModuleNotFoundError: No module named 'azureml.train.automl.automlconfig'

I am wondering you mentioned azure_automl.cmd to setup new env whereas the available file is automl_setup.cmd as mentioned in README file. What am i missing?

**Comment by swanderz** [comment]
@smfahad sorry that's a really crappy experience. everyone on my team has issues using the azureml-sdk with conda. i'd say once per month things break to the extent that I have to make a new local conda environement. and once a quarter, I have to uninstall and reinstall conda.

Unless @CESARDELATORRE says otherwise, I recommend you make a new environment and run
`pip install azureml-sdk[automl,interpret]`. This will install all the packages required for you to run automl runs (and hopefully use a pickled automl model) both on your local machine as well as submit runs remotely.

**Comment by smfahad** [comment]
@swanderz I tried your suggestion even i completely remove anaconda and reinstall it from scratch. I then created a new environment and run pip install azureml-sdk[automl,interpret], but still I am getting the same error message "ModuleNotFoundError: No module named 'azureml.train.automl.automlconfig'" when running the model .

Any other advise or suggestion do you have?

**Comment by swanderz** [comment]
Are other azureml modules importing correctly? Does the following work for you? You might not have your conda env properly registered as a Jupyter kernel.
```python
from azureml.core import VERSION
print("Azure ML SDK Version: ", VERSION)
```

**Comment by CESARDELATORRE** [comment]
Yes, I recommend you make a new CONDA environment and run the pip installs stated here:
https://github.com/Azure/MachineLearningNotebooks/blob/master/NBSETUP.md

I've been doing that in several custom environments with no issues.

**Comment by smfahad** [comment]
@swanderz yes, it is working for me, i am getting the output "Azure ML SDK Version:  1.2.0"

@CESARDELATORRE I have setup a new environment as you suggested and tried again with the automl best deploy model downloaded from AzureML studio but still i am getting the same error.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c7d25df3a7f4> in <module>
      3 import numpy as np
      4 import pandas as pd
----> 5 import azureml.train.automl
      6 from sklearn.externals import joblib
      7 from azureml.core.model import Model

~\AppData\Roaming\Python\Python36\site-packages\azureml\train\automl\__init__.py in <module>
     26     # Suppress the warnings at the import phase.
     27     warnings.simplefilter("ignore")
---> 28     from azureml.train.automl.automlconfig import AutoMLConfig
     29 
     30 try:

ModuleNotFoundError: No module named 'azureml.train.automl.automlconfig'

**Comment by swanderz** [comment]
can you run `pip list | grep “azureml”` in this environment and share the results?

**Comment by smfahad** [comment]
@swanderz here is the output

azureml-automl-core                  1.2.0
azureml-automl-runtime               1.2.0
azureml-contrib-notebook             1.2.0
azureml-contrib-pipeline-steps       1.2.0
azureml-contrib-server               1.2.0
azureml-contrib-services             1.2.0
azureml-core                         1.2.0.post2
azureml-dataprep                     1.3.6
azureml-dataprep-native              14.1.0
azureml-defaults                     1.2.0
azureml-explain-model                1.2.0
azureml-interpret                    1.2.0
azureml-model-management-sdk         1.0.1b6.post1
azureml-pipeline                     1.2.0
azureml-pipeline-core                1.2.0
azureml-pipeline-steps               1.2.0
azureml-sdk                          1.2.0
azureml-telemetry                    1.2.0
azureml-tensorboard                  1.2.0
azureml-train                        1.2.0
azureml-train-automl                 1.2.0
azureml-train-automl-client          1.2.0
azureml-train-automl-runtime         1.2.0
azureml-train-core                   1.2.0
azureml-train-restclients-hyperdrive 1.2.0
azureml-widgets                      1.2.0

**Comment by swanderz** [comment]
Also to be clear, what’s your import statement? Below is what the [reference tutorial](https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-auto-train-models) suggests. I recommend using that as it is more likely to stay Up to date compared to the notebooks in this repo.

`from azureml.train.automl import AutoMLConfig`

**Comment by smfahad** [comment]
@swanderz  Even when i am just running the mention statement without any other statement in my notebook, i am getting the error.

from azureml.train.automl import AutoMLConfig
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9b5a7ce91deb> in <module>
----> 1 from azureml.train.automl import AutoMLConfig

~\AppData\Roaming\Python\Python36\site-packages\azureml\train\automl\__init__.py in <module>
     26     # Suppress the warnings at the import phase.
     27     warnings.simplefilter("ignore")
---> 28     from azureml.train.automl.automlconfig import AutoMLConfig
     29 
     30 try:

ModuleNotFoundError: No module named 'azureml.train.automl.automlconfig'

**Comment by swanderz** [comment]
I'm sorry this is so difficult, I can definitely empathize. I'm 85% sure that the issue has to do with your jupyter notebook is not using your conda environment.

## Fix
Open the anaconda prompt and try this sequence of commands.
```
(base) C:\Users\anders.swanson>conda activate ret
(ret) C:\Users\anders.swanson>python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 30 2017, 11:52:29) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from azureml.core import VERSION
>>> print("Azure ML SDK Version: ", VERSION)
Azure ML SDK Version:  1.3.0
>>> from azureml.train.automl import AutoMLConfig
>>>
```

If the above works, I recommend that you read this article about [setting up an env on you local computer](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-environment#local). Specifically the part about registering a new kernel w/ the ipykernel package.

## Root Cause
Look at the path of your stacktrace. 
`~\AppData\Roaming\Python\Python36\site-packages\azureml\train\automl_init_.py`
The stacktrace should say something like 
```
~\AppData\Local\Continuum\anaconda3\envs\{YOUR_ENV_NAME}\lib\site-packages\azureml\train\automl\__init__.py"
```

My guess is that you installed the Azure ML SDK into your system (i.e. non-anaconda) Python a long time ago. So all your conda work is valid, but jupyter is using a kernel pointing to the wrong place.

**Comment by jadhosn** [comment]
>My guess is that you installed the Azure ML SDK into your system (i.e. non-anaconda) Python a long time ago. So all your conda work is valid, but jupyter is using a kernel pointing to the wrong place.

@smfahad I usually face something similar with some packages, whenever in doubt, I check where these packages are being summoned from using `.__file__` (if they have that implemented). 

For azureml's case, you would try:
```
import azureml.core as az
az.__file__ #check from where it's being loaded
import azureml.train as azt
azt.__file__ # check from where it's being loaded
```

**Comment by smfahad** [comment]
@swanderz Thanks for your help. Very much appreciated to identify the problem and taking it to the right direction.

When i run your mentioned commands within conda activated environment, the azureml.core package imported correctly and  pointing to the package with in my environment as @jadhosn mentioned, which seems fine.

But when i imported azureml.train.automl, it through an exception pointing the package to the global package directory (~\AppData\Roaming\Python\Python36\site-packages\azureml\train\automl_init_.py). I am not sure why this happens as one package is being imported from my environment package directory and the other is from the global package directory.

So I did the following:

1- Uninstall both anaconda and python completely. 
2- Deleted all the folders related to anaconda from C:\Users\{username} (like .anaconda, .conda)
3- Deleted the complete folder c:\users\{username}\appdata\roaming\python\

Then reinstalled Anaconda, created a new environment and install all the pip packages as mentioned by @CESARDELATORRE

and there you go, it is now working fine.

Thanks again for your kind support. @swanderz @CESARDELATORRE @jadhosn

**Comment by CESARDELATORRE** [comment]
Cool! I'm glad it worked for you! 👍
