### ISSUE TITLE
score.py script missing in tutorials/quickstart

### ISSUE THREAD

**Issue by sebastianbirk** [Azure/MachineLearningNotebooks#1282]
The score.py script is missing in the tutorials/quickstart folder leading to the model deployment to fail.
The file was there in the initial commit f1126e07f918c46a4a65eda27d8d5c3507f3f543 by samuel100 but seemed to have gotten lost in subsequent commits.

**Comment by shivanissambare** [comment]
We added it back

https://github.com/Azure/MachineLearningNotebooks/tree/master/tutorials/quickstart
