### ISSUE TITLE
from_docker_image parameters not correct : docker_file instead of image

### ISSUE THREAD

**Issue by alanflanders-teck** [Azure/MachineLearningNotebooks#1283]
The documentation does not indicate what data type the "image" parameter is supposed to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf83484-8d65-c598-3a97-2e1f8a1cf917
* Version Independent ID: aeed389d-4eec-013f-7b91-642f2de3f676
* Content: [azureml.core.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment(class)?view=azure-ml-py#from-docker-image-name--image--container-registry-none--conda-specification-none--pip-requirements-none-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by saachigopal** [comment]
A PR is out to fix the issue
