### ISSUE TITLE
Error Installing Azureml. (Python 3.9 support)

### ISSUE THREAD

**Issue by klawrawkz** [Azure/MachineLearningNotebooks#1285]
This guidance results in an error:

"To install the default packages in an environment without a previous version of the package installed, run the following command." 

PS C:\> pip install azureml-sdk

`ERROR: Could not find a version that satisfies the requirement azureml-sdk (from versions: none)
ERROR: No matching distribution found for azureml-sdk`

What am I missing?

Thanks,
claw
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by harneetvirk** [comment]
@klawrawkz :  What is your OS? What is the python and pip version? 

azureml-sdk only supports Python 3.5 to 3.8. So, if you're using an out-of-range version of Python (older or newer), then you'll need to use a different version.

**Comment by klawrawkz** [comment]
Thanks for the reply @harneetvirk. I'm pretty sure it's not a python version issue.

py --version
Python 3.9.1

Could be a Win 10 version issue?
![image](https://user-images.githubusercontent.com/48074223/103943498-2f478c00-5100-11eb-9bfd-43443a4cb582.png)

I ran this command and got farther. 
`pip install --upgrade --upgrade-strategy eager azureml-sdk`

I am stuck at this point now.
```
...
INFO: pip is looking at multiple versions of azure-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of azure-mgmt-containerregistry to determine which version is compatible with other requirements. This could take a while.
Collecting azure-mgmt-containerregistry>=2.0.0
  Downloading azure_mgmt_containerregistry-2.7.0-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB ...
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading azure_mgmt_containerregistry-2.6.0-py2.py3-none-any.whl (501 kB)
     |████████████████████████████████| 501 kB 1.6 MB/s
INFO: pip is looking at multiple versions of azure-mgmt-core to determine which version is compatible with other requirements. This could take a while.
  Downloading azure_mgmt_containerregistry-2.5.0-py2.py3-none-any.whl (494 kB)
     |████████████████████████████████| 494 kB 6.4 MB/s
  Downloading azure_mgmt_containerregistry-2.4.0-py2.py3-none-any.whl (482 kB)
     |████████████████████████████████| 482 kB 6.4 MB/s
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading azure_mgmt_containerregistry-2.3.0-py2.py3-none-any.whl (481 kB)
     |████████████████████████████████| 481 kB 6.8 MB/s
```

What's your advice on commands to provide "stricter constraints to reduce runtime?" The command (above) has been "running" for ~24 hours, so I'm guessing that it's dead in the H20.

Klaw

**Comment by harneetvirk** [comment]
azureml-sdk only supports Python 3.5 to 3.8, but you are having python 3.9.1 installed in the environment.  Please change the python version between 3.5 to 3.8.

Also, the latest pip 20.3 has a new dependency resolver which is resulting in this long running dependency resolutions. If you switch to older version of pip (<20.3), you will notice the difference in the performance.

**Comment by klawrawkz** [comment]
Gotcha, thanks for the info. I'll make the change.

Klaw

**Comment by adamjstewart** [comment]
If azureml-sdk does not support Python 3.9, then the metadata should be updated from:
```
Requires-Python: >=3.5,<4
```
to:
```
Requires-Python: >=3.5,<3.9
```
Is this also true for the hundreds of subpackages that azureml-sdk depends on? When is Python 3.9 support coming?

**Comment by absognety** [comment]
when will azureml-core be compatible with python 3.9?

**Comment by johan12345** [comment]
I am currently using azureml-sdk under Python 3.9 by installing with pip's `--ignore-requires-python` option, and everything I am using seems to work fine. But there are probably some other parts that don't work...

**Comment by absognety** [comment]
@johan12345 is this in production environment? you are using it like this? or in your local env?

**Comment by johan12345** [comment]
In my local development environment.

**Comment by paulshealy1** [comment]
`azureml-core` now supports Python 3.9.

**Comment by VedAustin** [comment]
unfortunately although `azureml-core` might install w/o errors in 3.9, `azureml-sdk` still creates errors. Installed w/o errors in 3.8.12

**Comment by harneetvirk** [comment]
azureml-sdk is a meta package.  azureml-core is one of the upstream that supports python 3.9 but there are some other AutoML dependencies in azureml-sdk  which do not support python 3.9.

**Comment by jeff-shepherd** [comment]
I have just updated azureml-sdk to allow Python 3.9.
This should be included in the next Azure ML SDK release, 1.45.0.

**Comment by adamjstewart** [comment]
What about 3.10? 3.11 is coming out soon too.

**Comment by jeff-shepherd** [comment]
@adamjstewart Python 3.10 is already supported in the new SDK V2 preview: https://docs.microsoft.com/en-us/azure/machine-learning/concept-v2
I expect that we will support 3.10 in SDK V1 as well but I don't have a date for that.
