### ISSUE TITLE
Typo "DataBricks notebook"→"Databricks Notebook"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/MachineLearningNotebooks#1287]
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.databricksstep?view=azure-ml-py

![azureml_pipeline_steps_databricks_step_databricksstep](https://user-images.githubusercontent.com/40815708/103846473-868a3400-50e1-11eb-85c5-f746e203109e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4d04b0-78b3-db32-a338-65f0ffc9167e
* Version Independent ID: 06721cca-fc1c-771c-c036-109712a1f7be
* Content: [azureml.pipeline.steps.databricks_step.DatabricksStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.databricksstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.DatabricksStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.DatabricksStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
Hi @hyoshioka0128, thanks for pointing this out. I have opened a bug to fix the typo. I will update here once done.

**Comment by shbijlan** [comment]
@hyoshioka0128 the typo has been fixed.
