### ISSUE TITLE
LocalWebService.run(input_data) does not work

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/MachineLearningNotebooks#1290]
I am following the [sample notebook](https://render.githubusercontent.com/view/ipynb?color_mode=light&commit=cda1f3e4cf8c8d9ed14b1bc0912277d562d673f0&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f417a7572652f4d616368696e654c6561726e696e674e6f7465626f6f6b732f636461316633653463663863386439656431346231626330393132323737643536326436373366302f686f772d746f2d7573652d617a7572656d6c2f6465706c6f796d656e742f6465706c6f792d746f2d6c6f63616c2f72656769737465722d6d6f64656c2d6465706c6f792d6c6f63616c2e6970796e62&nwo=Azure%2FMachineLearningNotebooks&path=how-to-use-azureml%2Fdeployment%2Fdeploy-to-local%2Fregister-model-deploy-local.ipynb&repository_id=145148726&repository_type=Repository#Test-Web-Service).

While calling the 

```
import json

sample_input = json.dumps({
    'data': dataset_x[0:2].tolist()
})

local_service.run(sample_input)
```
The error message is:
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-6feb00074e5a> in <module>
      5 })
      6 
----> 7 local_service.run(sample_input)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/webservice/local.py in decorated(self, *args, **kwargs)
     70                 raise WebserviceException('Cannot call {}() when service is {}.'.format(func.__name__, self.state),
     71                                           logger=module_logger)
---> 72             return func(self, *args, **kwargs)
     73         return decorated
     74     return decorator

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/webservice/local.py in run(self, input_data)
    427 
    428         return container_scoring_call(self._port, input_data, self._container, self._internal_base_url,
--> 429                                       cleanup_on_failure=False, score_url=self.scoring_uri)
    430 
    431     @property

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/webservice/local.py in scoring_uri(self)
    440             scorePath = WEBSERVICE_SCORE_PATH
    441             if hasattr(self, '_container_override_config'):
--> 442                 overrideScorePath = self._container_override_config["scorePath"]
    443                 if overrideScorePath is not None:
    444                     scorePath = overrideScorePath

TypeError: 'NoneType' object is not subscriptable
```

What exactly seems to be the issue?

**Comment by shivanissambare** [comment]
@frcai / @Bozhong68   Chifeng/Bo can you please help with this issue?

**Comment by frcai** [comment]
This issue should be fixed in last Nov.  @anirbansaha96 - please try latest python SDK. https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py
