### ISSUE TITLE
Problem install azureml-sdk on windows OS

### ISSUE THREAD

**Issue by dataovoxo** [Azure/MachineLearningNotebooks#1291]
I am trying to set up my local environment to use azureml-sdk. I create a new environment, activate it and run

`pip intsall azureml-sdk`

There seems to be a versioning problem within the installation. It eventually freezes for hours while trying to install azure-core<2.0.0,>=1.8.2a and I terminate it the process

please find my system config:

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	Dell Inc.
System Model	Latitude 5500
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.7.4, 2020/05/12
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Version	A01
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States

This is the error I get multiple times:

(azure_env) C:\Users\XXXXX>pip install azureml-sdk
Collecting azureml-sdk
  Using cached azureml_sdk-1.20.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.19.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.18.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.17.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.16.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.15.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.14.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.13.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.12.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.11.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.10.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.9.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.8.0-py3-none-any.whl (4.4 kB)
  Using cached azureml_sdk-1.7.0.post1-py3-none-any.whl (4.5 kB)
  Using cached azureml_sdk-1.7.0-py3-none-any.whl (4.6 kB)
  Using cached azureml_sdk-1.6.0-py3-none-any.whl (4.6 kB)
  Using cached azureml_sdk-1.5.0-py3-none-any.whl (4.6 kB)
  Using cached azureml_sdk-1.4.0-py3-none-any.whl (4.6 kB)
  Using cached azureml_sdk-1.3.0-py3-none-any.whl (4.6 kB)
  Using cached azureml_sdk-1.2.0-py3-none-any.whl (4.6 kB)
  Using cached azureml_sdk-1.1.5.1-py3-none-any.whl (4.6 kB)
Collecting azureml-core==1.1.5.*
  Using cached azureml_core-1.1.5.7-py2.py3-none-any.whl (1.2 MB)
Requirement already satisfied: azure-mgmt-keyvault>=0.40.0 in c:\users\XXXXX\miniconda3\envs\azure_env\lib\site-packages (from azureml-core==1.1.5.*->azureml-sdk) (8.0.0)
Requirement already satisfied: six>=1.11.0 in c:\users\\miniconda3\envs\azure_env\lib\site-packages (from azureml-core==1.1.5.*->azureml-sdk) (1.15.0)
Requirement already satisfied: azure-common>=1.1.12 in c:\users\oo19584\miniconda3\envs\azure_env\lib\site-packages (from azureml-core==1.1.5.*->azureml-sdk) (1.1.26)
Requirement already satisfied: msrest>=0.5.1 in c:\users\\miniconda3\envs\azure_env\lib\site-packages (from azureml-core==1.1.5.*->azureml-sdk) (0.6.19)
Requirement already satisfied: urllib3>=1.23 in c:\users\\miniconda3\envs\azure_env\lib\site-packages (from azureml-core==1.1.5.*->azureml-sdk) (1.26.2)
Requirement already satisfied: requests>=2.19.1 in c:\users\\miniconda3\envs\azure_env\lib\site-packages (from azureml-core==1.1.5.*->azureml-sdk) (2.25.1)
Collecting azureml-pipeline==1.1.5.*
  Using cached azureml_pipeline-1.1.5-py3-none-any.whl (3.7 kB)
Collecting azureml-pipeline-core==1.1.5.*
  Using cached azureml_pipeline_core-1.1.5-py2.py3-none-any.whl (271 kB)
Collecting azureml-pipeline-steps==1.1.5.*
  Using cached azureml_pipeline_steps-1.1.5-py3-none-any.whl (48 kB)
Collecting azureml-train==1.1.5.*
  Using cached azureml_train-1.1.5-py3-none-any.whl (3.2 kB)
Collecting azureml-train-automl-client==1.1.5.*
  Using cached azureml_train_automl_client-1.1.5.2-py3-none-any.whl (78 kB)
Collecting azureml-automl-core==1.1.5.*
  Using cached azureml_automl_core-1.1.5.1-py3-none-any.whl (108 kB)
Collecting azureml-telemetry==1.1.5.*
  Using cached azureml_telemetry-1.1.5.3-py3-none-any.whl (29 kB)
Collecting azureml-train-core==1.1.5.*
  Using cached azureml_train_core-1.1.5-py3-none-any.whl (8.6 MB)
Collecting azureml-train-restclients-hyperdrive==1.1.5.*
  Using cached azureml_train_restclients_hyperdrive-1.1.5-py3-none-any.whl (18 kB)
Collecting adal>=1.2.0
  Using cached adal-1.2.5-py2.py3-none-any.whl (55 kB)
Collecting azure-graphrbac>=0.40.0
  Using cached azure_graphrbac-0.61.1-py2.py3-none-any.whl (141 kB)
Collecting azure-mgmt-authorization>=0.40.0
  Using cached azure_mgmt_authorization-1.0.0-py2.py3-none-any.whl (141 kB)
Requirement already satisfied: azure-mgmt-core<2.0.0,>=1.2.0 in c:\users\\miniconda3\envs\azure_env\lib\site-packages (from azure-mgmt-authorization>=0.40.0->azureml-core==1.1.5.*->azureml-sdk) (1.2.2)
Collecting azure-mgmt-containerregistry>=2.0.0
  Using cached azure_mgmt_containerregistry-2.8.0-py2.py3-none-any.whl (718 kB)
Requirement already satisfied: azure-core<2.0.0,>=1.9.0 in c:\users\\miniconda3\envs\azure_env\lib\site-packages (from azure-mgmt-core<2.0.0,>=1.2.0->azure-mgmt-authorization>=0.40.0->azureml-core==1.1.5.*->azureml-sdk) (1.10.0)
Collecting azure-mgmt-resource<9.0.0,>=1.2.1
  Using cached azure_mgmt_resource-8.0.1-py2.py3-none-any.whl (758 kB)
Collecting azure-mgmt-storage>=1.5.0
  Using cached azure_mgmt_storage-16.0.0-py2.py3-none-any.whl (811 kB)
Collecting azureml-dataprep[fuse]<1.4.0a,>=1.3.5
  Using cached azureml_dataprep-1.3.6-py3-none-any.whl (26.6 MB)
Collecting azureml-dataprep<1.4.0a,>=1.3.5
  Using cached azureml_dataprep-1.3.5-py3-none-any.whl (26.6 MB)
INFO: pip is looking at multiple versions of azure-mgmt-storage to determine which version is compatible with other requirements. This could take a while.
Collecting azure-mgmt-storage>=1.5.0
  Using cached azure_mgmt_storage-11.2.0-py2.py3-none-any.whl (547 kB)
  Using cached azure_mgmt_storage-11.1.0-py2.py3-none-any.whl (547 kB)
  Using cached azure_mgmt_storage-11.0.0-py2.py3-none-any.whl (546 kB)
  Using cached azure_mgmt_storage-10.0.0-py2.py3-none-any.whl (532 kB)
  Using cached azure_mgmt_storage-9.0.0-py2.py3-none-any.whl (525 kB)
  Using cached azure_mgmt_storage-8.0.0-py2.py3-none-any.whl (524 kB)
  Using cached azure_mgmt_storage-7.2.0-py2.py3-none-any.whl (519 kB)
INFO: pip is looking at multiple versions of azure-mgmt-storage to determine which version is compatible with other requirements. This could take a while.
  Using cached azure_mgmt_storage-7.1.0-py2.py3-none-any.whl (517 kB)
  Using cached azure_mgmt_storage-7.0.0-py2.py3-none-any.whl (516 kB)
  Using cached azure_mgmt_storage-6.0.0-py2.py3-none-any.whl (514 kB)
  Using cached azure_mgmt_storage-5.0.0-py2.py3-none-any.whl (436 kB)
  Using cached azure_mgmt_storage-4.2.0-py2.py3-none-any.whl (435 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached azure_mgmt_storage-4.1.0-py2.py3-none-any.whl (435 kB)
  Using cached azure_mgmt_storage-4.0.0-py2.py3-none-any.whl (426 kB)
  Using cached azure_mgmt_storage-3.3.0-py2.py3-none-any.whl (1.0 MB)
  Using cached azure_mgmt_storage-3.1.1-py2.py3-none-any.whl (696 kB)
  Using cached azure_mgmt_storage-3.1.0-py2.py3-none-any.whl (696 kB)
  Using cached azure_mgmt_storage-3.0.0-py2.py3-none-any.whl (682 kB)
  Using cached azure_mgmt_storage-2.0.0-py2.py3-none-any.whl (558 kB)
Collecting azure-mgmt-nspkg>=2.0.0
  Using cached azure_mgmt_nspkg-3.0.2-py3-none-any.whl (1.6 kB)
Collecting azure-nspkg>=3.0.0
  Using cached azure_nspkg-3.0.2-py3-none-any.whl (1.5 kB)
INFO: pip is looking at multiple versions of azure-nspkg to determine which version is compatible with other requirements. This could take a while.
  Using cached azure_nspkg-3.0.1-py3-none-any.whl (1.5 kB)
INFO: pip is looking at multiple versions of azure-mgmt-nspkg to determine which version is compatible with other requirements. This could take a while.
Collecting azure-mgmt-nspkg>=2.0.0
  Using cached azure_mgmt_nspkg-3.0.1-py3-none-any.whl (1.6 kB)
  Using cached azure_mgmt_nspkg-2.0.0-py2.py3-none-any.whl (2.8 kB)
Collecting azure-nspkg>=2.0.0
  Using cached azure_nspkg-2.0.0-py2.py3-none-any.whl (2.6 kB)
Collecting azure-mgmt-storage>=1.5.0
  Using cached azure_mgmt_storage-1.5.0-py2.py3-none-any.whl (189 kB)
INFO: pip is looking at multiple versions of azure-nspkg to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of azure-mgmt-resource to determine which version is compatible with other requirements. This could take a while.
Collecting azure-mgmt-resource<9.0.0,>=1.2.1
  Using cached azure_mgmt_resource-8.0.0-py2.py3-none-any.whl (758 kB)
INFO: pip is looking at multiple versions of azure-mgmt-nspkg to determine which version is compatible with other requirements. This could take a while.
  Using cached azure_mgmt_resource-7.0.0-py2.py3-none-any.whl (757 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached azure_mgmt_resource-6.0.0-py2.py3-none-any.whl (705 kB)
  Using cached azure_mgmt_resource-5.1.0-py2.py3-none-any.whl (681 kB)
  Using cached azure_mgmt_resource-5.0.0-py2.py3-none-any.whl (672 kB)
  Using cached azure_mgmt_resource-4.0.0-py2.py3-none-any.whl (657 kB)
  Using cached azure_mgmt_resource-3.1.0-py2.py3-none-any.whl (534 kB)
INFO: pip is looking at multiple versions of azure-mgmt-resource to determine which version is compatible with other requirements. This could take a while.
  Using cached azure_mgmt_resource-3.0.0-py2.py3-none-any.whl (468 kB)
  Using cached azure_mgmt_resource-2.2.0-py2.py3-none-any.whl (780 kB)
  Using cached azure_mgmt_resource-2.1.0-py2.py3-none-any.whl (757 kB)
  Using cached azure_mgmt_resource-2.0.0-py2.py3-none-any.whl (698 kB)
  Using cached azure_mgmt_resource-1.2.2-py2.py3-none-any.whl (323 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached azure_mgmt_resource-1.2.1-py2.py3-none-any.whl (323 kB)
INFO: pip is looking at multiple versions of azure-mgmt-keyvault to determine which version is compatible with other requirements. This could take a while.
Collecting azure-mgmt-keyvault>=0.40.0
  Using cached azure_mgmt_keyvault-7.0.0-py2.py3-none-any.whl (197 kB)
  Using cached azure_mgmt_keyvault-2.2.0-py2.py3-none-any.whl (89 kB)
  Using cached azure_mgmt_keyvault-2.1.1-py2.py3-none-any.whl (117 kB)
  Using cached azure_mgmt_keyvault-2.1.0-py2.py3-none-any.whl (117 kB)
  Using cached azure_mgmt_keyvault-2.0.0-py2.py3-none-any.whl (80 kB)
  Using cached azure_mgmt_keyvault-1.1.0-py2.py3-none-any.whl (111 kB)
  Using cached azure_mgmt_keyvault-1.0.0-py2.py3-none-any.whl (57 kB)
INFO: pip is looking at multiple versions of azure-mgmt-keyvault to determine which version is compatible with other requirements. This could take a while.
  Using cached azure_mgmt_keyvault-0.40.0-py2.py3-none-any.whl (21 kB)
INFO: pip is looking at multiple versions of azure-core to determine which version is compatible with other requirements. This could take a while.
Collecting azure-core<2.0.0,>=1.9.0
  Using cached azure_core-1.9.0-py2.py3-none-any.whl (124 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of azure-mgmt-core to determine which version is compatible with other requirements. This could take a while.
Collecting azure-mgmt-core<2.0.0,>=1.2.0
  Using cached azure_mgmt_core-1.2.1-py2.py3-none-any.whl (21 kB)
Collecting azure-core<2.0.0,>=1.8.2a
  Using cached azure_core-1.8.2-py2.py3-none-any.whl (122 kB)
ERROR: Operation cancelled by user

**Comment by lostmygithubaccount** [comment]
please see https://stackoverflow.com/questions/65112585/pip-installation-stuck-in-infinite-loop-if-unresolvable-conflicts-in-dependencie

in short, this is a pip issue. from there answer:

```
Workarounds:

Local environment: Downgrade pip to < 20.3

Conda environment created from yaml: This will be seen only if conda-forge is highest priority channel, anaconda channel doesn't have pip 20.3 (as of now). To mitigate the issue please explicitly specify pip<20.3 (!=20.3 or =20.2.4 pin to other version) as a conda dependency in the conda specification file

AzureML experimentation: Follow the case above to make sure pinned pip resulted as a conda dependency in the environment object, either from yml file or programmatically
```

**Comment by dataovoxo** [comment]
@lostmygithubaccount Thank you. I was on pip 20.2 but I downgraded to 20.1 and it worked fine. My other laptop uses pip 20.3.3 and the installation ran fine. This behavior is quite inconsistent.
