### ISSUE TITLE
Deploying Pipeline with input as a Service 

### ISSUE THREAD

**Issue by mavsun** [Azure/MachineLearningNotebooks#1292]
Hello all,

I've been working on a project involving a pipeline with a number input parameters.
The pipeline has already been published and, due to the project needs, I wonder if we can submit input and run request externally? In another word, can we send input to the pipeline through Postman using the pipeline's rest API.
(I attempted to use the pipeline API on postman but is missing a Bearer Token, where can I find the bearer token?)

OR, is it possible to deploy the pipeline as service (with the scoring files and such)? 
Like the way we deploy models.

Thank you very much for your help!

**Comment by mavsun** [comment]
Please Respond

**Comment by shbijlan** [comment]
Hi @mavsun, the articles below share pointers on how to deploy a pipeline endpoint with the required authentication. Let us know if this helps or if there is any specific error you are facing. 

https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-pipeline-batch-scoring-classification#publish-and-run-from-a-rest-endpoint 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-pipelines

**Comment by mavsun** [comment]
Thanks for the articles, I guess I was not careful the first time I read them. I was able to initiate a pipeline run with Postman, but when I moved on to javascript, it begun to give me CORS issue. I've dug a bit on the internet and it seems like I have to use a API management service to bypass the CORS. I've set up the API management service on Azure, tested my POST query and got a response, but I'm still not getting pass the CORS thing on Javascript. Please assist, thanks.
