### ISSUE TITLE
Deploying  ResNet50 Image Classification using ONNX and AzureML

### ISSUE THREAD

**Issue by Xuan-1998** [Azure/MachineLearningNotebooks#1293]
http://5e850c38-f6d3-4c85-a3cb-4f4d52e3072f.eastus2.azurecontainer.io/score
The above is the url I got but it shows that {"error": "'data'"}.
How to solve it?

**Comment by lostmygithubaccount** [comment]
I suspect the team will need more information, can you explain what you are trying to do and what you are getting stuck on?

**Comment by v-strudm-msft** [comment]
Since we haven't received a reply to our request for more information for a few months we assume the issue was resolve. Should there still be a question, please reopen this issue.   Thank you.
--

**Comment by v-strudm-msft** [comment]
Since we haven't received a reply to our request for more information for a few months we assume the issue was resolved and closed it. Should there still be a question, please reopen this issue. Thank you.
