### ISSUE TITLE
ACIWebService with VNET and Subnet

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/MachineLearningNotebooks#1294]
The tutorial to deploy an ACIWebService inside a VNET mentions providing Subnet Delegation to the Microsoft.ContainerInstance/containerGroups. However, in our structure, we are not being allowed to do that. While we try to do this we get the following error:

```
Failed to save subnet <REDACTED-MANUALLY>.
Error: 'Delegations of subnet <REDACTED-MANUALLY>/providers/Microsoft.Network/virtualNetworks/<REDACTED-MANUALLY>/subnets/<REDACTED-MANUALLY> cannot be changed from [] to [Microsoft.ContainerInstance/containerGroups] because it is being used by the resource /subscriptions/<REDACTED-MANUALLY>/resourceGroups/<REDACTED-MANUALLY>/providers/Microsoft.Network/networkInterfaces/<REDACTED-MANUALLY>/ipConfigurations/amlworkspace-default.privateEnpoint
```

What is the other way to solve this issue, our AML Workspace resides in the Subnet of a VNET and we wish to deploy our model with a private end point?

**Comment by shivanissambare** [comment]
Hi,
can you please confirm if the prerequisites:

When using Azure Container Instances in a virtual network, the virtual network must be:
1. In the same resource group as your Azure Machine Learning workspace.

2. If your workspace has a private endpoint, the virtual network used for Azure Container Instances must be the same as the one used by the workspace private endpoint.

3. When using Azure Container Instances inside the virtual network, the Azure Container Registry (ACR) for your workspace cannot be in the virtual network.

if above three conditions are met, you can this documentation to add/remove subnet- https://docs.microsoft.com/en-us/azure/virtual-network/manage-subnet-delegation

**Comment by v-strudm-msft** [comment]
Since there wasn't a post after our last comment we assume the above advice resolved it. Should there still be a question, please reopen this issue. Thank you.
