### ISSUE TITLE
Definition of "original explainer" in ScoringExplainer documentation 

### ISSUE THREAD

**Issue by vla6** [Azure/MachineLearningNotebooks#1301]
I am looking for clarification on documentation for various ScoringExplainer classes, for example:

- https://docs.microsoft.com/en-us/python/api/azureml-interpret/azureml.interpret.scoring.scoring_explainer.treescoringexplainer?view=azure-ml-py
- https://docs.microsoft.com/en-us/python/api/azureml-	interpret/azureml.interpret.scoring.scoring_explainer.treescoringexplainer?view=azure-ml-py

These have a parameter in the constructor called "original_explainer", and contain this text:

> Parameters:
> original_explainer
> <xref:BaseExplainer>
> The training time explainer originally used to explain the model.

I haven't been able to find out what "originally" means, or find a definition of the BaseExplainer class.  I was attempting to wrap a SHAP tree explainer in the TreeScoringExplainer class but that doesn't seem to work.  What is an original explainer?  Why does it need to be created at training time?  

It is desirable to have some flexibility with explainers.  For example you might change the background or foil dataset in Shapley to answer different questions.  So I may want more than 1 explainer per model.

**Comment by minthigpen** [comment]
@imatiach-msft Could you take a look at this question? Thank you!

**Comment by imatiach-msft** [comment]
@vla6 the "original_explainer" is from interpret-community repository (https://github.com/interpretml/interpret-community) and can be any of the wrappers around SHAP TreeExplainer/KernelExplainer/DeepExplainer or the auto TabularExplainer which finds the best one or the MimicExplainer.  I think it's a great idea to allow ScoringExplainer classes to take SHAP explainers as well instead of the wrappers in interpret-community on top of the SHAP explainers.

**Comment by CESARDELATORRE** [comment]
Removing AutoML tag since this is not related to AutoML, afaik, but about azureml.interpret.

**Comment by vla6** [comment]
Hi @imatiach-msft .  Thank you for the reply.  How do you set up an "original explainer" with the TreeScoringExplainer?  Is there any documentation?  Can you just pass the interpret community explainer to the TreeScoringExplainer constructor, and use that?   

Thanks a lot!

**Comment by imatiach-msft** [comment]
@vla6 sorry for the late reply.  Indeed, you can pass any of the interpret-community explainers that use the TreeExplainer to the TreeScoringExplainer constructor, specifically MimicExplainer with a tree-based surrogate model (for example LightGBM classifier or regressor surrogate model) or the TreeExplainer.

**Comment by imatiach-msft** [comment]
maybe these notebooks might help:

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/explain-model/azure-integration/scoring-time/train-explain-model-locally-and-deploy.ipynb

```
from azureml.interpret.scoring.scoring_explainer import TreeScoringExplainer, save
# ScoringExplainer
scoring_explainer = TreeScoringExplainer(tabular_explainer)
# Pickle scoring explainer locally
save(scoring_explainer, exist_ok=True)

# Register original model
run.upload_file('original_model.pkl', os.path.join('./outputs/', model_file_name))
original_model = run.register_model(model_name='local_deploy_model', 
                                    model_path='original_model.pkl')

# Register scoring explainer
run.upload_file('IBM_attrition_explainer.pkl', 'scoring_explainer.pkl')
scoring_explainer_model = run.register_model(model_name='IBM_attrition_explainer', model_path='IBM_attrition_explainer.pkl')
```

Then in the web service:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/explain-model/azure-integration/scoring-time/score_local_explain.py

```

def init():

    global original_model
    global scoring_explainer

    # Retrieve the path to the model file using the model name
    # Assume original model is named original_prediction_model
    original_model_path = Model.get_model_path('local_deploy_model')
    scoring_explainer_path = Model.get_model_path('IBM_attrition_explainer')

    original_model = joblib.load(original_model_path)
    scoring_explainer = joblib.load(scoring_explainer_path)


def run(raw_data):
    # Get predictions and explanations for each data point
    data = pd.read_json(raw_data)
    # Make prediction
    predictions = original_model.predict(data)
    # Retrieve model explanations
    local_importance_values = scoring_explainer.explain(data)
    # You can return any data type as long as it is JSON-serializable
    return {'predictions': predictions.tolist(), 'local_importance_values': local_importance_values}
```

**Comment by imatiach-msft** [comment]
Another notebook example using the scoring explainers:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/explain-model/azure-integration/scoring-time/train-explain-model-on-amlcompute-and-deploy.ipynb
This actually submits this script to run on AMLCompute:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/explain-model/azure-integration/scoring-time/train_explain.py

But in this case it uses the LinearScoringExplainer, since the TabularExplainer chose the LinearExplainer:
```
# also create a lightweight explainer for scoring time
scoring_explainer = LinearScoringExplainer(tabular_explainer)
# pickle scoring explainer locally
save(scoring_explainer, directory=OUTPUT_DIR, exist_ok=True)

# register scoring explainer
run.upload_file('IBM_attrition_explainer.pkl', os.path.join(OUTPUT_DIR, 'scoring_explainer.pkl'))
scoring_explainer_model = run.register_model(model_name='IBM_attrition_explainer',
                                             model_path='IBM_attrition_explainer.pkl')
```


And then runs this web service remotely:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/explain-model/azure-integration/scoring-time/score_remote_explain.py

**Comment by imatiach-msft** [comment]
@vla6 you can also find API docs on the scoring explainers here:
https://docs.microsoft.com/en-us/python/api/azureml-interpret/azureml.interpret.scoring.scoring_explainer.treescoringexplainer?view=azure-ml-py

And some walkthroughs here:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-interpretability-automl#register-the-model-and-the-scoring-explainer

**Comment by vla6** [comment]
Thanks a lot for your help, especially the examples!  I will try some
