### ISSUE TITLE
Can no longer retrieve data with OutputFileDatasetConfig

### ISSUE THREAD

**Issue by kelsey-emnett** [Azure/MachineLearningNotebooks#1305]
I am creating a HyperDrive pipeline on remote Azure ML compute cluster. Since the new release yesterday, I am no longer able to retrieve data outputted from one pipeline step with PipelineData and OutputFileDatasetConfig within the next step. In first step, the files drop into Azure BLOB storage correctly. However when I try to retrieve those files in the following step I am now getting this error:
 ```
	Message: Cannot mount Dataset(id='702f8452-a26b-4d9c-b9c9-75484c4be49c', name='None', version=None). Source of the dataset is either not accessible or does not contain any data. Error Message: ScriptExecutionException was caused by StreamAccessException. 
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: 'https://orximagingstorage.blob.core.windows.net/pipeline-data/azureml/5b1586b6-2133-48ad-adb8-5e036c34af7f/output_56bbf1b6'
```

The code I am using worked before the release 2 days ago. The code in the driver script creating the PipelineData and OutputFileDatasetConfig is as follows:
```
image_data = PipelineData('image_files', datastore=pipelinedata, output_name='image_files')
image_files= OutputFileDatasetConfig(destination=(pipelinedata, 'image_data'))
```
The pipeline step where I am encountering this error are:
```
est_step1 = Estimator(source_directory=os.path.join(os.getcwd(),'class_step'),
                        compute_target=compute_target,
                        entry_script='script1.py',
                        conda_packages=conda_packages,
                        pip_packages=pip_packages
)

hd_config_step1 = HyperDriveConfig(estimator=est_step1,
                            hyperparameter_sampling=ps_step,
                            primary_metric_name="Average_Accuracy",
                            primary_metric_goal=PrimaryMetricGoal.MAXIMIZE,
                            max_total_runs=20,
                            max_concurrent_runs=20
)

step1 = HyperDriveStep(
    name='data_cleaning',
    hyperdrive_config=hd_config_step1,
    estimator_entry_script_arguments=['--image_outputs', image_files],
    outputs=[image_files],
    allow_reuse=False
)

est_step2 = Estimator(source_directory=os.path.join(os.getcwd(),'text_step'),
                        compute_target=compute_target,
                        entry_script='script2.py',
                        conda_packages=conda_packages,
                        pip_packages=pip_packages
)

hd_config_step2 = HyperDriveConfig(estimator=est_step2,
                            hyperparameter_sampling=ps_step,
                            primary_metric_name="Average_Accuracy",
                            primary_metric_goal=PrimaryMetricGoal.MAXIMIZE,
                            max_total_runs=20,
                            max_concurrent_runs=20
)

step2 = HyperDriveStep(
    name='text_step',
    hyperdrive_config=hd_config_step2,
    estimator_entry_script_arguments=['--image_inputs', image_files],
    inputs=[image_files],
    allow_reuse=False
)
```

I am dumping it in storage with this code in step 1 (this happens successfully):
```
run = Run.get_context()

parser = argparse.ArgumentParser()
parser.add_argument('--image_outputs', type=str)
args = parser.parse_args()

os.makedirs(args.image_outputs, exist_ok=True)
file_name = "data.json"
inputpath = os.path.join(args.image_outputs, file_name)
with open(inputpath, "w") as write_file:
    json.dump(json_object, write_file)
```

I am retrieving the data inside the pipeline step as follows:
```
run = Run.get_context()

parser = argparse.ArgumentParser()
parser.add_argument('--image_inputs', type=str)
args = parser.parse_args()

file_name = 'data.json'
inputpath = os.path.join(args.image_inputs, file_name)

with open(inputpath) as f:
    json_data = json.load(f)
```

The script fails when it tries to mount the dataset after performing the first step and has moved onto the step shown above.

**Comment by MayMSFT** [comment]
Hi @kelsey-emnett 

Can you help confirm that there is data in the following path in your storage account?
https://orximagingstorage.blob.core.windows.net/pipeline-data/azureml/5b1586b6-2133-48ad-adb8-5e036c34af7f/output_56bbf1b6

will be great if you can share the script for your step1 as well. Not sure how pipelinedata is used in your scenario.

Thanks

**Comment by kelsey-emnett** [comment]
Hello @MayMSFT 

Yes, there is definitely data in storage in that location. It succesfully dumps from step 1 according to time stamps on storage. I will provide a sanitized version of the code above. I cannot provide the real code publicly due to client privacy restrictions so the actual code looks very different.

**Comment by kelsey-emnett** [comment]
I ended up using Azure blob storage functions from the package azure.storage.blob instead of the Azure ML-specific packages. This is not ideal because we lose a lot of the data traceability features from within Azure ML this way but it should mean that future updates to storage functions no longer will break our code.

**Comment by v-strudm-msft** [comment]
Since there hasn't been a response to our last comment, we assume this was resolved and are closing this issue. Should there still be a question, please re-open this issue. Thank you.
