### ISSUE TITLE
Link is wrong

### ISSUE THREAD

**Issue by levalencia** [Azure/MachineLearningNotebooks#1306]
This link is wrong (404)

A full sample is available at https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning /regression/auto-ml-regression.ipynb

Remove the space after machine learning

**Comment by skasturi** [comment]
@Aniththa @jeff-shepherd

**Comment by jeff-shepherd** [comment]
I think this about the link on [https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
I can fix that.

**Comment by CESARDELATORRE** [comment]
Closing this issue. As per @jeff-shepherd:

"I have fixed the link in the source file.  It is in automatically generated documentation from the Python source code.  I did create a bug for this: Bug 1027976.

It will be published with the next SDK version."
