### ISSUE TITLE
ParallelRunConfig class documentation does not include append_row_file_name parameter

### ISSUE THREAD

**Issue by vla6** [Azure/MachineLearningNotebooks#1307]
I am looking at this documentation for the ParallelRunConfig  class:

https://docs.microsoft.com/en-us/python/api/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.parallel_run_config.parallelrunconfig?view=azure-ml-py

In the constructor, it shows a parameter append_row_file_name as follows:

ParallelRunConfig(environment, entry_script, error_threshold, output_action, compute_target, node_count, process_count_per_node=None, mini_batch_size=None, source_directory=None, description=None, logging_level=None, run_invocation_timeout=None, input_format=None, **append_row_file_name=None**)

However, this parameter is not defined or explained in the "Parameters" section.   What does this name mean and how is it used?

**Comment by shbijlan** [comment]
Hi @vla6 The document link above refers to a deprecated package. Please refer to https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.parallelrunconfig?view=azure-ml-py. You can find details on append_row_file parameter there.
