### ISSUE TITLE
AutoML doesnt work on remote cluster

### ISSUE THREAD

**Issue by levalencia** [Azure/MachineLearningNotebooks#1308]
The following code works if I comment the compute cluster parameter.

from azureml.train.automl import AutoMLConfig
from azureml.core.compute import ComputeTarget, AmlCompute
from azureml.core.compute_target import ComputeTargetException

```
cpu_cluster_name = "computecluster"
compute_target = ComputeTarget(workspace=ws, name=cpu_cluster_name)
print(compute_target)
automl_config = AutoMLConfig(task='regression',
                             #compute_target = compute_target,
                             debug_log='automated_ml_errors.log',
                             training_data = df,
                             label_column_name="paidInDays",
                             **automl_settings)
```

However if I uncomment it, I get this error:

```

ConfigException: ConfigException:
	Message: Input of type 'Unknown' is not supported. Supported types: [azureml.data.tabular_dataset.TabularDataset, azureml.pipeline.core.pipeline_output_dataset.PipelineOutputTabularDataset]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Input of type 'Unknown' is not supported. Supported types: [azureml.data.tabular_dataset.TabularDataset, azureml.pipeline.core.pipeline_output_dataset.PipelineOutputTabularDataset]",
        "details_uri": "https://aka.ms/AutoMLConfig",
        "target": "training_data",
        "inner_error": {
            "code": "BadArgument",
            "inner_error": {
                "code": "ArgumentInvalid",
                "inner_error": {
                    "code": "InvalidInputDatatype"
                }
            }
        }
    }
}
```

**Comment by rtanase** [comment]
@levalencia , what is the type of df? Is it a pandas dataframe?
If you uncomment compute_target, training is supposed to happen remotely, in which case we are not accepting Pandas Dataframe as training data, but the types mentioned in the exception details.

**Comment by levalencia** [comment]
understood, let me try.
it was a pandas dataframe

**Comment by levalencia** [comment]
OKI changed this to an azure dataset.
Its been like 10 minutes and I still see 0 provisioned nodes, is it normal?

**Comment by levalencia** [comment]
its been there like 2 hours with no output, and no nodes provisioned


Running on remote.
No run_configuration provided, running on computecluster with default configuration

**Comment by rtanase** [comment]
Was there a run ID created (like AutoML_GUID)? Could you share that? Just to clear this out, do you have quota for the cluster to spin up new nodes?

**Comment by levalencia** [comment]
strange this, last week it didnt work, but today it did, and the nodes were provisioned and the entire experiment worked fine.
