### ISSUE TITLE
ParallelRunConfig - Document meaning of "error"; perhaps allow flexibility 

### ISSUE THREAD

**Issue by vla6** [Azure/MachineLearningNotebooks#1309]
In the [documentation for the ParallelRunConfig class](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinedata?view=azure-ml-py), the parameter error_threshold is defined as:

> error_threshold int
> The number of record failures for TabularDataset and file failures for FileDataset that should be ignored during processing. If the error count goes above this value, then the job will be aborted. Error threshold is for the entire input and not for individual mini-batches sent to run() method. The range is [-1, int.max]. -1 indicates ignore all failures during processing.

I didn't realize at first that, for a TabularDataset input and output_action='append_row', an "error" is defined as fewer rows out than you put in.  If you get out fewer rows, you have an error, the same number or more is no error.    I am not sure if there is any other way to trigger an error?   I am not sure if it would be good to clarify the documentation?

Also, it might be nice to have some flexibility with this.   It makes sense if you are generating predictions from a model, maybe you would always have 1 row output for 1 row input.  But, I was using ParallelRunConfig  to generate explanations, and sometimes explanations (LIME or Shapley etc) could be in "long" format with 1 row per input observation/feature.  I actually was testing with a subset of rows when I saw the error.  However, if you output *more* rows than the input, you are always fine, no matter how many more, while any fewer is an error. 

For explanations, it might be good to tell the step you expect something like (for example) 5 outputs per input.  Or maybe even a range.   Or just allow the user to query rows in vs. rows out?

**Comment by shivanissambare** [comment]
@tracychms  can you take a look, thank you :)

**Comment by tracychms** [comment]
doc is updated clarifying for TabularDataset input, error_threshold is: The number of record failures for TabularDataset
