### ISSUE TITLE
[ResourceNotFound] The Resource 'Microsoft.ContainerInstance/containerGroups/aci-birds-' under resource group was not found.

### ISSUE THREAD

**Issue by praveentn** [Azure/MachineLearningNotebooks#1311]
While running this [notebook ](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb), there's an exception encountered on deploying the service.

```
service = Model.deploy(workspace=ws, 
                           name='aci-birds', 
                           models=[model], 
                           inference_config=inference_config, 
                           deployment_config=aciconfig)
```
Stack trace:

```
WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Transitioning
Operation ID: 912ba59b-fbbd-4f8e-9239-000
More information can be found using '.get_logs()'
Error:
{
  "code": "ResourceNotFound",
  "statusCode": 404,
  "message": "The Resource 'Microsoft.ContainerInstance/containerGroups/aci-birds-hash' under resource group 'res_grp_name' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Transitioning\nOperation ID: 912ba59b-fbbd-4f8e-9239-000\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"ResourceNotFound\",\n  \"statusCode\": 404,\n  \"message\": \"The Resource 'Microsoft.ContainerInstance/containerGroups/aci-birds-hash' under resource group 'res_grp_name' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"\n}"
    }
}

```

**Comment by shivanissambare** [comment]
What did the deployment logs show?

Can you add this line: `inference_config.source_directory = "./"`

after:
`inference_config = InferenceConfig(entry_script="pytorch_score.py", environment=pytorch_env)`

and let us know if it helps with your issue?

**Comment by shivanissambare** [comment]
please, feel free to re-open the issue, if you have more questions.

**Comment by lohitdoradla** [comment]
Hello, even I have the same issue. Tried many things but was not successful.

service_name = 'modelwine'
service =Webservice.deploy_from_model(workspace= ws,
                                     name= service_name,
                                     deployment_config=aciconfig,
                                     models=[model],
                                     image_config=image_config)
service.wait_for_deployment(show_output=True)
print(service.state)






Error



![image](https://user-images.githubusercontent.com/33143564/146329751-4e4f84a1-5f41-4c34-af18-b2ad3f99bb95.png)
