### ISSUE TITLE
Local execution is not supported for Azure ML pipelines. ValueError: Please specify a remote compute_target. 

### ISSUE THREAD

**Issue by meghalv** [Azure/MachineLearningNotebooks#1316]
When I try to run a pipeline with target as "local" it gives me an error. 
ValueError: Please specify a remote compute_target. 
This should be mentioned somewhere in the end of the page under target section. 
Also please specify why pipelines cannot be run on local target? People like me waste a lot of time trying this & then realize its a shortcoming in the Azure ML Python SDK. 
Please update this documentation page as soon as possible.
![image](https://user-images.githubusercontent.com/17008122/106663751-73fe0000-65a4-11eb-87f7-fcc7613dd42f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c8e18c-8443-67fe-b1f9-531de3599c8f
* Version Independent ID: a8c897b7-c44b-1a72-52f2-f81bbdbce753
* Content: [azureml.core.runconfig.RunConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfig.runconfiguration?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.runconfig.RunConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.runconfig.RunConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
apologies, we understand the frustration and are working to fully support local execution through Azure Machine Learning with our v2 developer experience, which is approaching public preview

**Comment by meghalv** [comment]
While it is allowed to Run AzureML experiments in Local Target using the Python SDK, I am expecting the pipelines as well to be allowed to run on local target. If this is an exception then it should be clearly flagged bot & documented by Microsoft at all relevant places. Below 2 pages should definitely contain this note
1) 
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace(class)?view=azure-ml-py#azureml_core_Workspace_compute_targets
<under compute_targets section>

2)
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfig.runconfiguration?view=azure-ml-py
<under target section>

**Comment by lostmygithubaccount** [comment]
unfortunately the initial preview of v2 will not address this issue, I will allow the Pipelines team to give a more clear ETA for that. but initial preview is tentatively March 2021

**Comment by meghalv** [comment]
Thank you for quick reply. I would be happy if this feature is included in the 2.0 release. Let me know if there is any way to rate this feature on higher priority.

PS: Please change your screen name,  "lostmygithubaccount" is very confusion & unprofessional.

**Comment by andrescodas** [comment]
Hi @lostmygithubaccount and @meghalv .  I'm currently blocked by this issue.  I'm unable to allocate a remote Compute Target and I don't find an example on how to use my local computer.

Is this feature already delivered?.  Do you have an example?

**Comment by robert4os** [comment]
Hi @lostmygithubaccount, 

what is the status of local execution of Pipelines in Azure Machine Learning? Why was this issue closed without any conclusive information or workaround? 

This missing feature is blocking customers that want to use local IDE and debugging.

**Comment by metang** [comment]
The local pipeline is still in development. We don't have an ETA for the release date.

**Comment by hinriksnaer** [comment]
Hi, I just wanted to contribute to the conversation and say that this feature would be much appreciated. Currently, it is difficult to bounce between local debugging and cloud deployment. This is because the lack of local pipeline support requires change in data-flow as well as various azureml-core variables that are accessible during pipeline runs.
