### ISSUE TITLE
minecraft example gives me this error

### ISSUE THREAD

**Issue by mrmarten** [Azure/MachineLearningNotebooks#1318]
The minecraft example gives me the error when using the Jupyter notebook and using Compute clusters.

`{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "User program failed with CalledProcessError: Command 'python minecraft_train.py ' returned non-zero exit status 1.",
    "messageFormat": null,
    "messageParameters": {},
    "referenceCode": null,
    "detailsUri": "https://aka.ms/azureml-known-errors",
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": {
      "type": "CalledProcessError",
      "message": "Command 'python minecraft_train.py ' returned non-zero exit status 1.",
      "stackTrace": "  File \"/mnt/batch/tasks/shared/LS_root/jobs/ai-ml-workbench/azureml/minecraft-maze_1612379610_38278b5f_head/mounts/workspaceblobstore/azureml/minecraft-maze_1612379610_38278b5f_head/azureml-setup/context_manager_injector.py\", line 210, in execute_with_context\n    runpy.run_path(sys.argv[0], globals(), run_name=\"__main__\")\n  File \"/opt/miniconda/lib/python3.7/runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n  File \"/opt/miniconda/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/opt/miniconda/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"azureml-setup-rl/ray_head_launcher.py\", line 112, in <module>\n    subprocess.run(command, check=True, shell=True)\n  File \"/opt/miniconda/lib/python3.7/subprocess.py\", line 512, in run\n    output=stdout, stderr=stderr)\n",
      "innerException": null,
      "data": null,
      "errorResponse": null
    }
  },
  "correlation": null,
  "environment": null,
  "location": null,
  "time": "0001-01-01T00:00:00+00:00",
  "componentName": null
}`

Regards
Marten

**Comment by keijik** [comment]
Hi @mrmarten, thanks for trying out RL on Azure Machine Learning and reaching out.  

I am sorry to hear about the error.  Are you able to see any more details in the file called 70_driver_log.txt?  

![image](https://user-images.githubusercontent.com/33700985/106960272-ad438680-66f0-11eb-8c20-2f6236f3fff8.png)

**Comment by v-strudm-msft** [comment]
Since there wasn't a post after our last comment we assume the above advice resolved it. Should there still be a question, please reopen this issue. Thank you.
--

**Comment by v-strudm-msft** [comment]
Since there wasn't a post after our last comment we assume the above advice resolved it. Should there still be a question, please reopen this issue. Thank you.
