### ISSUE TITLE
Missing description for parameters: enable_cache, enable_subsampling, subsample_seed, and whitelist_models

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#132]
see title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d73eed-d8eb-b7a6-ec5b-98d391cf8a16
* Version Independent ID: 242cf736-4dea-6309-6410-e027e01e5e84
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ggupta2005** [comment]
Thanks for pointing this out. We have fixed the documentation and this should be reflected in the next release.

**Comment by swanderz** [comment]
Thanks, @ggupta2005. shameless plug for another documentation issue #133 with the same AutoMLConfig function
