### ISSUE TITLE
[meta issue] support all current Python versions

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/MachineLearningNotebooks#1326]
- https://github.com/Azure/MachineLearningNotebooks/issues/1285
- https://github.com/Azure/MachineLearningNotebooks/issues/1256
- https://github.com/Azure/MachineLearningNotebooks/issues/959 (3.8 support? or ubuntu?)

**Comment by lostmygithubaccount** [comment]
3.10 set for May 2021 https://www.python.org/dev/peps/pep-0619/

**Comment by jeff-shepherd** [comment]
@lostmygithubaccount which specific versions do you need support for?
Azure Machine Learning does not supported Python version older than 3.5.2.
Support for newer versions is sometimes limited by support from dependent packages.

**Comment by lostmygithubaccount** [comment]
"all current Python versions" - currently, 3.6 through 3.9, and 3.10 as soon as we can once it releases.

I assume by dependencies, you're talking about AutoML, which takes a dependency on many open source ML frameworks? Can we not work with those communities to update their Python support if that's what we need to do? 3.9 has been out for a while now. 

According to pypi, there are quite a few "azureml-automl" packages (see #1325) 

https://pypi.org/project/azureml-train-automl-runtime/

- <3.8

https://pypi.org/project/azureml-train-automl-client/

- <3.9

https://pypi.org/project/azureml-train-automl/

- <4 

https://pypi.org/project/azureml-contrib-automl-pipeline-steps/

- <3.8

https://pypi.org/project/azureml-contrib-automl-dnn-vision/

- <3.8

https://pypi.org/project/azureml-contrib-automl-dnn-forecasting/

- <4

https://pypi.org/project/azureml-automl-runtime/

- <3.8

https://pypi.org/project/azureml-automl-core/

- <3.9

**Comment by CESARDELATORRE** [comment]
Adding @savitamittal1 to comment on Python packages versions supported by AutoML and roadmap upgrading.

**Comment by savitamittal1** [comment]
Currently AutoML support python 3.6 and 3.7 version of python. 
Version 3.8 is in roadmap and is planned to be added in the second semester of the year.

**Comment by lostmygithubaccount** [comment]
and 3.9? 3.10 is releasing second semester of the year

​- Cody
________________________________

**Comment by kvijaykannan** [comment]
This will get planned for next year.

**Comment by marcindulak** [comment]
If possible, please don't close the issue, but instead wait until it is resolved.

**Comment by lostmygithubaccount** [comment]
reopening until resolved

**Comment by lostmygithubaccount** [comment]
@kvijaykannan note this issue is for all of Azure ML, not specifically AutoML

**Comment by kvijaykannan** [comment]
Thanks Cody. I have removed AutoML tag, so it doesn't show up in our AutoML tracking.

**Comment by lostmygithubaccount** [comment]
@vijaykannan it is an AutoML issue as well, adding back the label - please discuss this internally.

**Comment by jmwoloso** [comment]
do you have anymore insight into support for python 3.9 from the entirety of the azureml-sdk ecosystem? this is the only thing holding us up from switching to python 3.9.
