### ISSUE TITLE
[meta issue] release process is confusing to external and internal users

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/MachineLearningNotebooks#1329]
not going to list the various PRs/issues, but here's an example: https://github.com/Azure/MachineLearningNotebooks/pull/1313 

this is a longstanding issue

**Comment by lostmygithubaccount** [comment]
@azureml-github testing

**Comment by lostmygithubaccount** [comment]
https://github.com/Azure/MachineLearningNotebooks/pull/1335

**Comment by lostmygithubaccount** [comment]
https://github.com/Azure/MachineLearningNotebooks/pull/1373

**Comment by paulshealy1** [comment]
@lostmygithubaccount we will address this with the new samples and v2 work.
