### ISSUE TITLE
Deploy model - Azure Container Instance deploy_configuration missing gpu_cores

### ISSUE THREAD

**Issue by corticalstack** [Azure/MachineLearningNotebooks#1330]
Hi,

As per following Azure container instance sizing, should be possible to spec container instance with GPU resource (GPU is available in my region - France Central):

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-region-availability

However, see the following code below, to deploy a model as a webservice endpoint running within a container instance - I don't believe the option for gpu_cores is available?

`from azureml.core.webservice import AciWebservice`
`aci_config = AciWebservice.deploy_configuration(cpu_cores=2, memory_gb=8)`

**Comment by shivanissambare** [comment]
Hi,
Yes we do not have gpu support for ACI.

We have documentation for GPU Inference on AKS : https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-inferencing-gpus#create-a-kubernetes-cluster-with-gpus

Sample notebook: https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/deployment/production-deploy-to-aks-gpu

**Comment by shivanissambare** [comment]
closing this issue, please feel free to re-open if you have any more questions.
