### ISSUE TITLE
show how to get lication of input dataset without being in the experiment run context.

### ISSUE THREAD

**Issue by rbavery** [Azure/MachineLearningNotebooks#1331]
Ideally there'd be an easy, documented way to get this on my local machine context where I'm running the code to launch the experiment. I'd like to know where my data are going to be downloaded without needing to go into the experiment run context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f376be7e-6049-d0db-93a9-2a778dc41fcd
* Version Independent ID: bdc4020e-aad7-056d-16d5-004d27fd5238
* Content: [azureml.data.dataset_consumption_config.DatasetConsumptionConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_consumption_config.datasetconsumptionconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.dataset_consumption_config.DatasetConsumptionConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.dataset_consumption_config.DatasetConsumptionConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
in general you can pass something like `my_dataset.as_mount()` in your `ScriptRunConfig` arguments, then retrieve the argument name in your script - this will be the mount (or download) location
