### ISSUE TITLE
Youo don't have access to XXXX subscription.

### ISSUE THREAD

**Issue by chengyu-liu-cs** [Azure/MachineLearningNotebooks#1332]
Hi

We have been constantly encountering this error `"You are currently logged-in to XXXX tenant. You don't have access to 4ddf2bc2-XXXXX subscription, please check if it is in this tenant. All the subscriptions that you have access to in this tenant are"`.

Previous my colleague had this issue in his laptop and he called MS support to resolve this issue by running `InteractiveLoginAuthentication(tenant_id="my-tenant-id", force=True)` from his laptop [ref codes](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb ). But this time the same solution did not work for my case.

It seems this is a common [issue](https://docs.microsoft.com/en-us/answers/questions/171465/problems-connecting-to-workspace-using-azure-machi.html?childToView=267256#answer-267256 )

Now we are having it in production environment where CICD pipelines are running in a hosted agent (as AML workspace is accessible only via private link in a vnet). It is really inconvenient to run `InteractiveLoginAuthentication(tenant_id="my-tenant-id", force=True)` when subscription id changes. I feel this is a bug and could you help investigate and provide a permanent solution ?

**Comment by rastala** [comment]
@chengyu-liu-cs In a CI/CD production environment it makes sense to use ServicePrincipalAuthentication. The InteractiveAuthentication is meant for situations where user can interactively log in to Azure. 

See "Service Principal Authentication" section in this notebook:

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb

**Comment by v-strudm-msft** [comment]
We haven't received a response to our last comment so assume the above advice resolved it. Should there still be a question, please reopen this issue. Thank you.
--

**Comment by v-strudm-msft** [comment]
We haven't received a response to our last comment so assume the above advice resolved it. Should there still be a question, please reopen this issue. Thank you.
