### ISSUE TITLE
Get the id of the default container registry of an azure ML workspace

### ISSUE THREAD

**Issue by irishun** [Azure/MachineLearningNotebooks#1340]
Hi, I cannot find how to get the id of the default container registry of an azure ML workspace.
Is there a SDK function or CLI command to do so?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3600f5-8708-f211-014a-f2b620b2bf51
* Version Independent ID: 59af6b62-f2cf-089c-7ea2-63c5d786e980
* Content: [azureml.core.container_registry.ContainerRegistry class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.container_registry.containerregistry?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.container_registry.ContainerRegistry.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.container_registry.ContainerRegistry.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by vizhur** [comment]
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace.workspace?view=azure-ml-py#get-details--

you can also find it through the Azure Portal

**Comment by irishun** [comment]
Thank you vizhur! 
I was looking for a programming way. Thanks to the link you provided I can now parse the containerRegistry returned by get_details() and get the id.
