### ISSUE TITLE
Question about license 

### ISSUE THREAD

**Issue by sandguardian** [Azure/MachineLearningNotebooks#1345]
I trained model on Azure AutoML and downloaded it from web console.
When I try to load model and predict data, it requires azure ml python packages.

Is there any license issue to use related azure python packages and model trained on Azure?
Or can I use it freely?

**Comment by lostmygithubaccount** [comment]
excellent question...from a practical perspective and from the engineering team, you can definitely use the model freely.

as far as the actual License, it seems this is the SDK license: https://github.com/Azure/MachineLearningNotebooks/blob/master/Licenses/sdk-license/LICENSE 

you can also find licenses listed on the pypi pages, but they aren't particularly helpful: https://pypi.org/project/azureml-sdk/

I will bring this up with the team internally.

**Comment by lostmygithubaccount** [comment]
you can find a given license for a Python package in the "dist-info" folder if you download the package/navigate to where it is downloaded

**Comment by sandguardian** [comment]
Thanks for your confirmation @lostmygithubaccount.

**Comment by CESARDELATORRE** [comment]
#pleaseclose since the question was already answered.
