### ISSUE TITLE
PythonScriptStep never reuses previous output when inside Azure Pipelines CI/CD

### ISSUE THREAD

**Issue by kelmahrsi** [Azure/MachineLearningNotebooks#1346]
Hello,

I am having this weird issue with a PythonScriptStep that always runs no matter what when an Azure ML pipeline is submitted from a Azure Pipelines CI/CD YAML pipeline.

I have an AML pipeline which is composed of both PythonScriptStep and DatabricksStep steps.

When I submit the pipeline from my local machine, all steps are detected as eligible to reuse and will not run (which is the expected behavior).

However, when the exact same pipeline, generated and submitted with the exact same code is executed as part of my CI/CD pipeline (using Azure Pipelines), then all DatabricksStep steps are still eligible for reuse (again, as intended) but for some weird reason, the PythonScriptStep will run again and generate new outputs.

Does anyone have the slightest idea on how to fix this?

Thank you in advance!

**Comment by shbijlan** [comment]
@kelmahrsi could you confirm that you only upload files relevant to the job at hand? Any change in files within the data directory will be seen as reason to rerun the step the next time the pipeline is run even if reuse is specified.

**Comment by kelmahrsi** [comment]
@shbijlan Yes! I confirm that's the case. Each step's script is in a separate directory. The data used by the steps are stored on an Azure storage and don't budge. Like I said in the issue: the step is reused correctly if the code that creates the pipeline and submits it is executed from my local machine. The problem only happens with CI/CD in Azure Pipelines.

**Comment by wayliums** [comment]
@kelmahrsi are you still facing the problem? can you share a sample yaml?

**Comment by wayliums** [comment]
closing the item since no response. Sometimes there are backend changes that invalidated the cache.
