### ISSUE TITLE
Metric dropdown is missing metrics in Run Details on AzureML studio

### ISSUE THREAD

**Issue by jeydn** [Azure/MachineLearningNotebooks#1347]
Hi, 
maybe I am missing something but in the metrics dropdown it seems like some of the metrics I am logging are missing. I am running a hyperdrive experiment and  would like to compare how the different hyperparameters affect all my metrics, not just randomly selected 4 of them. 
Here is the example: 
![image](https://user-images.githubusercontent.com/32169999/108386243-5ff10a00-7204-11eb-921e-826b97508c59.png)

It only shows AUC, F1, Recall and Precision in the dropdown even though I am also logging Accuracy and some other metrics. However, these do appear in the Run Details of the child runs, e.g.:
![image](https://user-images.githubusercontent.com/32169999/108386497-9cbd0100-7204-11eb-8d84-20d0495aead7.png)

Is this a bug or am I missing a configuration? 

Thanks in advance.

**Comment by lostmygithubaccount** [comment]
this seems to be a bug and has been routed internally to the right team who should be able to give a more meaningful update soon

**Comment by JennaEllis** [comment]
Hello!

This is a bug on our end unfortunately. We are working on a fix from our end, and will update you once it is available to you. Thanks so much for reporting this!

**Comment by JennaEllis** [comment]
The patch for this issue has been released to all regions @jeydn! Please let us know if this has improved your use case, and we can close this issue.

**Comment by jeydn** [comment]
Hi, it works for a new pipeline (different Experiment) that I created and has similar metrics. On the old one I still can't select 'Accuracy'. However, this is sufficient for me now. 
Thanks a lot.

**Comment by v-strudm-msft** [comment]
Since this issue was resolved, we're now closing it.
