### ISSUE TITLE
allow_reuse not working with DatabricksStep

### ISSUE THREAD

**Issue by GeethanadhP** [Azure/MachineLearningNotebooks#1352]
I have a databricks notebook, which generates 5 DatabricksStep's and then submits them to AML

```
DatabricksStep(
            name=self.step_name,
            notebook_path=self.notebook_path,
            notebook_params=self.notebook_parameters,
            run_name=f"{self.step_name}-{self.build_number}",
            compute_target=self.databricks_compute,
            allow_reuse=True,
            existing_cluster_id=self.databricks_cluster_id
        )

pipeline = Pipeline(workspace, steps)
run = pipeline.submit(experiment_name) # regenerate_outputs=False as its the default value
```

But when a step 4 fails and i rerun my original notebook, it create a new run on AML, but aml is still re-running the first 3 steps instead of re-using previous runs

Also i noticed that in the AML UI, under the experiment, steps tab my steps were having "NO" as value for "Reuse" eventhough i am passing True from the step while creating it (as above code)

Am i doing something wrong or is it a bug with DatabrickStep?

**Comment by shbijlan** [comment]
@GeethanadhP could you confirm that you only upload files relevant to the job at hand? Any change in files within the data directory will be seen as reason to rerun the step the next time the pipeline is run even if reuse is specified.

**Comment by GeethanadhP** [comment]
Hi, i have raised an azure support ticket and have it resolved, apparently the re-use step won't work even if the databricks-cluster-id is changed, which is the case for me
