### ISSUE TITLE
08 - Create a Pipeline.ipynb notebook fails

### ISSUE THREAD

**Issue by slsu0424** [Azure/MachineLearningNotebooks#1354]
Hello - I am running through the attached notebook, and running into the following error with the following code:

```
from azureml.core import Experiment
from azureml.pipeline.core import Pipeline
from azureml.widgets import RunDetails

# Construct the pipeline
pipeline_steps = [prep_step, train_step]
pipeline = Pipeline(workspace=ws, steps=pipeline_steps)
print("Pipeline is built.")

# Create an experiment and run the pipeline
experiment = Experiment(workspace=ws, name = 'mslearn-diabetes-pipeline')
pipeline_run = experiment.submit(pipeline, regenerate_outputs=True)
print("Pipeline submitted for execution.")
RunDetails(pipeline_run).show()
pipeline_run.wait_for_completion(show_output=True)
```

The error I receive is the following:

Expected a StepRun object but received <class 'azureml.core.run.Run'> instead.
This usually indicates a package conflict with one of the dependencies of azureml-core or azureml-pipeline-core.
Please check for package conflicts in your python environment
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in wait_for_completion(self, show_output, timeout_seconds, raise_on_error)
    294                                 step_run.wait_for_completion(timeout_seconds=timeout_seconds - time_elapsed,
--> 295                                                              raise_on_error=raise_on_error)
    296                             except TypeError as e:

TypeError: wait_for_completion() got an unexpected keyword argument 'timeout_seconds'

During handling of the above exception, another exception occurred:

ActivityFailedException                   Traceback (most recent call last)
<ipython-input-28-e1c5033d6731> in <module>
     13 print("Pipeline submitted for execution.")
     14 RunDetails(pipeline_run).show()
---> 15 pipeline_run.wait_for_completion(show_output=True)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in wait_for_completion(self, show_output, timeout_seconds, raise_on_error)
    307                                         'azureml-core or azureml-pipeline-core.\n' +
    308                                         'Please check for package conflicts in your python environment')
--> 309                                     step_run.wait_for_completion(raise_on_error=raise_on_error)
    310                                 else:
    311                                     # Different error than the run rehydration issue

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/run.py in wait_for_completion(self, show_output, wait_post_processing, raise_on_error)
    748 
    749                 if raise_on_error:
--> 750                     raise ActivityFailedException(error_details=json.dumps(error, indent=4))
    751 
    752             return final_details

ActivityFailedException: ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "Image build failed. For more details, check log file azureml-logs/20_image_build_log.txt.",
        "messageFormat": "Image build failed. For more details, check log file {ArtifactPath}.",
        "messageParameters": {
            "ArtifactPath": "azureml-logs/20_image_build_log.txt"
        },
        "details": [],
        "innerError": {
            "code": "BadArgument",
            "innerError": {
                "code": "ImageBuildFailure"
            }
        }
    },
    "correlation": {
        "operation": null,
        "request": "18ed176a3705ee81"
    },
    "environment": "eastus2",
    "location": "eastus2",
    "time": "2021-02-22T19:20:22.384652Z",
    "componentName": "execution-worker"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Image build failed. For more details, check log file azureml-logs/20_image_build_log.txt.\",\n        \"messageFormat\": \"Image build failed. For more details, check log file {ArtifactPath}.\",\n        \"messageParameters\": {\n            \"ArtifactPath\": \"azureml-logs/20_image_build_log.txt\"\n        },\n        \"details\": [],\n        \"innerError\": {\n            \"code\": \"BadArgument\",\n            \"innerError\": {\n                \"code\": \"ImageBuildFailure\"\n            }\n        }\n    },\n    \"correlation\": {\n        \"operation\": null,\n        \"request\": \"18ed176a3705ee81\"\n    },\n    \"environment\": \"eastus2\",\n    \"location\": \"eastus2\",\n    \"time\": \"2021-02-22T19:20:22.384652Z\",\n    \"componentName\": \"execution-worker\"\n}"
    }
}

Can someone advise as to the error and how to resolve?

[08 - Create a Pipeline.ipynb.zip](https://github.com/Azure/MachineLearningNotebooks/files/6024656/08.-.Create.a.Pipeline.ipynb.zip)

**Comment by vla6** [comment]
I think I had this issue and it had to do with version mismatches between various versions of azureml-core and azureml-pipeline-core, as well as other libraries.  **The fix was to use a new VM.**   

Once I started up a new VM things worked great.  I was told Microsoft doesn't do any updates or ensure consistency with other parts of Azure after the VM is spun up.  I believe things got out of sync as changes were made to the greater Azure ecosystem.

**Comment by emepetres** [comment]
Hi, I'm having the same message trying to run it locally, any ideas?

```
diabetes_env = Environment("local_conda_env")
diabetes_env.python.user_managed_dependencies = True
pipeline_cluster = "local"
```

**Comment by MrCordeiro** [comment]
I have the same problem as @emepetres. The pipeline may or may not run - for the same VM and environment, depending on when I run it.
