### ISSUE TITLE
Unable to import azureml.contrib.

### ISSUE THREAD

**Issue by Raman1121** [Azure/MachineLearningNotebooks#1355]
[Enter feedback here]
I have installed the azureml-SDK and azureml-contrib-notebook but am getting the following error "ModuleNotFoundError: No module named 'azureml.contrib'" while executing the code 
`
from azureml.core import Workspace, Experiment, RunConfiguration
from azureml.contrib.notebook import NotebookRunConfig, AzureMLNotebookHandler

workspace = Workspace.from_config()
exp = Experiment(workspace, "azureml_notebook_experiment")

run_config_user_managed = RunConfiguration()
run_config_user_managed.environment.python.user_managed_dependencies = True

handler = AzureMLNotebookHandler(timeout=600, progress_bar=True)

cfg = NotebookRunConfig(source_directory="Users/harman/",
                        notebook="create_template_s3.ipynb",
                        handler=handler,
                        run_config=run_config_user_managed)

run = exp.submit(cfg)
run.wait_for_completion(show_output=True)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfbc3d8c-fd22-fdfa-1f4f-e0549b58d6d6
* Version Independent ID: cc9a7f93-97ce-879b-07f5-758dd506ec6d
* Content: [azureml.contrib.notebook.AzureMLNotebookHandler class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-notebook/azureml.contrib.notebook.azuremlnotebookhandler?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-notebook/azureml.contrib.notebook.AzureMLNotebookHandler.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-notebook/azureml.contrib.notebook.AzureMLNotebookHandler.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by vizhur** [comment]
should be False: run_config_user_managed.environment.python.user_managed_dependencies = **True**. True means you have an image specified that has all the dependencies. From the code snippet above the default environments is used. The base image for the default environment doesn't have a python layer and setting user_managed_dependencies to True prevents AzureML to materialize conda environment with needed dependencies.

Unless I'm missing smth..
