### ISSUE TITLE
Open source azureml on github

### ISSUE THREAD

**Issue by epa095** [Azure/MachineLearningNotebooks#1356]
Azureml should be open source and have its sourcecode in a repository on github. It would provide a natural place to discuss the code, arcitecture and report issues. And who knows, you might even get a PR or two ;-) 
At the moment the lack of transparancy is a strong argument for us against going all-in in Azure ML, and it would make our decision a lot easier if the development process was more transparent and the code open.

**Comment by lostmygithubaccount** [comment]
v2 will be open source and hosted on GitHub

**Comment by epa095** [comment]
Awesome! Is there a timeline?

**Comment by epa095** [comment]
While I still would prefer to have v1 open source, including a timeline for v2, I feel satisfied enough with this :-) Looking forward to V2!

**Comment by lostmygithubaccount** [comment]
v2 is https://github.com/Azure/azureml-v2-preview 

We're in what we consider a "private preview" but, as you can see, the code/docs are actually public (but not referenced anywhere officially - "private" through obscurity). We're targeting what we'd consider "public preview", where we'll actually promote it on official documentation etc., in the next few months - I'm hesitant to give an exact timeline at this point, but you are free to try out the CLI as it is now and give feedback on the preview repository

**Comment by lostmygithubaccount** [comment]
I'll bring up open sourcing v1 with the engineering team, but I do not expect it to happen
