### ISSUE TITLE
Config.json error in img-classification-part2-deploy.ipynb

### ISSUE THREAD

**Issue by RabbitJackTrade** [Azure/MachineLearningNotebooks#136]
When running  **img-classification-part2-deploy.ipynb**, cell 2:

        from azureml.core import Workspace
        from azureml.core.model import Model
        ws = Workspace.from_config()

results in:
`UserErrorException: We could not find config.json in: /home/nbuser/library/tutorials or in its parent directories. Please provide the full path to the config file or ensure that config.json exists in the parent directories.
`

**Comment by rastala** [comment]
Try running the [configuration notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/configuration.ipynb) first. It should save the config.json in the root folder of your notebook session.

**Comment by RabbitJackTrade** [comment]
I did; but I received a different error; see issue #131 : https://github.com/Azure/MachineLearningNotebooks/issues/131
