### ISSUE TITLE
Link to MPIStep example is broken

### ISSUE THREAD

**Issue by tarockey** [Azure/MachineLearningNotebooks#1362]
At the top of the MpiStep doc, it links to an example notebook, but the link is broken. The closest I can find to the "correct" link is https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/pipeline-style-transfer/pipeline-style-transfer-parallel-run.ipynb, which does not mention MpiStep anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00db76ef-5f7c-4685-b4ee-535fa9f9016a
* Version Independent ID: 30d18264-1388-61d7-085e-ae49c0db7805
* Content: [azureml.pipeline.steps.mpi_step.MpiStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.mpi_step.mpistep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.mpi_step.MpiStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.mpi_step.MpiStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
@tarockey Thank you for the feedback. I have opened a work item to address this. Will share updates here.
