### ISSUE TITLE
Why must we register the env before using build_local ?

### ISSUE THREAD

**Issue by epa095** [Azure/MachineLearningNotebooks#1367]
This seems quite counter-intuitive to me, after all I have the environment locally and I want to build it locally. What does the cloud have to do with it? I want to build it locally to weed out any embarrising problems before I register it ;-)

**Comment by vizhur** [comment]
@epa095 I understand your frustration. Any environment used in the system should be registered with the service. This way you can reference to in from the UI, associated with your experiment run, etc. 

We are planning to remove explicit registration requirement on v1 SDK side, but there is no priority or ETA.
I believe you found out the workaround and can use env.register(ws).build(ws)  

Sorry for the bad experience
