### ISSUE TITLE
Use a TabularDataset as a side_inputs

### ISSUE THREAD

**Issue by epa095** [Azure/MachineLearningNotebooks#1368]
I am trying to use a TabularDataset  as a elementin `side_inputs` in a (scoring)-pipeline, but I am not able to make it work. Is this supposed to work?
If it is *not* supposed to work, it would be natural to document this (e.g. in docstrings and other places).
If it *is* supposed to work, can I get some pointers to how to work with the data in my python script? If I take in the `ds.as_named_input(..)` should I get a path to some serialized version of it? Or can I get it directly as a panda dataframe somehow?

Or should I rather read the dataset "manually" in my script using `Dataset.get_by_name(...)`?

**Comment by shivanissambare** [comment]
@tracychms  can you help with this issue?
thank you!

**Comment by epa095** [comment]
@tracychms is `label_ds` a **Tabular**Dataset in this example? And what resides then in `labels_path`? If label_ds is backed by e.g. a SQL, how is it exposed as files in labels_path?

**Comment by psavdekar** [comment]
@epa095 , side input is used to mount the data user want to refer in scoring script. Since tabular dataset is not something which gets mounted it'll not work. I'll track our document updates, thanks for pointing it out.
As you mentioned above, using Dataset.get_by_name should work for your case. Sorry for the inconvenience.

**Comment by shivanissambare** [comment]
since tsg has been updated, closing this issue, feel free to re-open if you have more questions.
thanks!

**Comment by JoeYi-PG** [comment]
@epa095  You can get it by: Run.get_context().input_datasets["input_name"].to_pandas_dataframe()
