### ISSUE TITLE
Azureml-core dependencies incompatible in latest release 1.23.0

### ISSUE THREAD

**Issue by jzazo** [Azure/MachineLearningNotebooks#1370]
Hi. I tried to update an installation environment that depended on `azureml-core`, and when trying to install it using `pipenv update`, the tool could not find a stable set of packages to install. I had to constrain the library to `azureml-core==1.22.0` for this update to pass. It seems an incompatibility regression of packages has been introduced in version 1.23.0. From the error message I received from pipenv, it was caused by cryptography package.

EDIT: This is the pipenv message with incompatible packages: `cryptography!=1.9,!=2.0.*,!=2.1.*,!=2.2.*,<4,<4.0.0,<=3.2,>=0.6,>=1.1.0,>=2.0,>=2.1.4,>=3.2,>=3.3.1`. The requirement `<=3.2` is new from version 1.23.0, apparently.

I report this encountered issue here since I could not find a better location. Let me know if I should redirect this issue somewhere else.

**Comment by elonp** [comment]
Repro steps:
```
cd tmp
pipenv install
pipenv install "azureml-sdk==1.23.0"
```

**Comment by bandsina** [comment]
Thank you, @jzazo for the report! We added the upper bound because of a breaking change in the cryptography package on certain platforms. We are working on this.

**Comment by needuv** [comment]
Hi @jzazo, thanks for letting us know. A couple of questions for you:

1. Could you please share your Pipfile for your pipenv?
2. How did you initially install azureml-core in your environment? Did you use the azureml-sdk install? Or, did you install azureml-core as its own package? 

It seems that pipenv has some issue installing azureml-sdk==1.23.0, but it can install azureml-core==1.23.0 fine. I'm looking into why that's the case.

**Comment by jzazo** [comment]
Yes, I started installing with `azureml-sdk` and then switched to `azureml-core`, and I was still getting errors afterwards.

My local Pipfile is not shareable, because I have lots of local project dependencies and it is big. `azure-core` is a dependency we have, in case there are colliding requirements with `azureml-core`.

It is likely one of my dependencies requires a minimum version of cryptography >3.2, and this is incompatible with latest requirement introduced in 1.23.0. Have you been able to find what added <=3.2 requirement?

**Comment by needuv** [comment]
The `cryptography<=3.2` requirement was added to `azureml-core` in 1.23.0. It indeed might be the case that one of your dependencies requires `cryptography>3.2` as `azureml-core==1.23.0` appears to install successfully by itself in a pipenv-- would you be able to check on that? Thanks for raising the issue on `azureml-sdk` as well.

**Comment by jzazo** [comment]
I tried to look on the dependencies graph. I found `pyopenssl`, version `20.0.1` requires `cryptography>=3.2`. `pyopenssl` is a direct dependence of `azureml-core`.

**Comment by elonp** [comment]
The following steps reproduce the problem on a new environment with nothing installed:
```
mkdir tmp
cd tmp
pipenv install
pipenv install "azureml-sdk==1.23.0"
```
The first `pipenv install` creates the environment.
So the conflict is within the requirements of `azureml-sdk==1.23.0`.

**Comment by needuv** [comment]
Hi @jzazo and @elonp, I found two mitigations that may work for you:

1. Could you try installing `pyjwt< 2.0.0` in your environment and then trying installing `azureml-sdk==1.23.0` again? It appears that azureml-sdk==1.23.0 tries to install `pyjwt[crypto]==2.0.1`, which has a requirement of `cryptography<4>=3.3.1`, and the pipenv resolver is unable to resolve the dependencies.
2. If possible, can you try using `conda` instead? We did not observe this problem when trying to install `azureml-sdk==1.23.0` in a conda environment. I understand if you cannot move to `conda` easily, but if you can, this may also resolve the issue for you.

**Comment by jzazo** [comment]
Thank you needuv for the suggestions. We will stay in version 1.22.0 for the time being as this is sufficient atm. In future azureml versions we will check if cryptography <=3.2 is still required (before the update we had version 3.4.6), and we will update when the issue is resolved.

We cannot switch to conda. Adding an extra dependency mitigates the issue, and we would consider adding it if the upper bound requirement remains in future azureml versions.

May I inquire if `cryptography<=3.2` is going persist in future versions?

**Comment by needuv** [comment]
We had to pin `cryptography<=3.2` since the newer versions did not work with certain platforms. We will remove the pinning once it is compatible with all platforms.

**Comment by bandsina** [comment]
@jzazo , @elonp , quick question - do you need to use azureml-sdk? We updated our guidance to customers to install required packages separately, aka azureml-core, and not install the meta-package azureml-sdk. Curious, if that will work for your scenario? https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py#default-install

**Comment by jzazo** [comment]
We are using `azureml-core` and `azureml.train.estimator.Estimator` (which I think has been deprecated and we should change). If cryptography is not pinned in `azureml-core`, we will switch to it and this will solve our issues. Thanks for pointing this out.

**Comment by vizhur** [comment]
Very good point to switch from referencing metapackage, though it won't solve the issue. azureml-core is the one that brings cryptography dependency. Upper bounding that dependency going forward is very unlikely as many versions of cryptography have vulnerabilities and AzureML will be forced eventually to update the range. Pinning shouldn't even happen with this release as AzureML SDK not directly depend on it, I believe that was temporarily done to mitigate on going issue

**Comment by benbogart** [comment]
Adding to this, even within the azure packages there this version upper bound causes problems.
azureml.core 1.22.0 requires cryptography <= 3.2
azureml.datasets 1.24.0 requires cryptography >=3.3.1

This is even the case in the prebuilt azure compute instances and makes running the tutorials impossible.

@needuv
> 2. If possible, can you try using `conda` instead? We did not observe this problem when trying to install `azureml-sdk==1.23.0` in a conda environment. I understand if you cannot move to `conda` easily, but if you can, this may also resolve the issue for you.

I can't find azureml-sdk (or any azureml packages) in any of the conda channels.  Do you know which channel can the azureml packages can be found in?  I can try out the conda approach and report back.

**Comment by benbogart** [comment]
@vizhur you are correct.  I meant azureml.opendatasets which is used with azureml.core in [this tutorial ](https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/create-first-ml-experiment/tutorial-1st-experiment-sdk-train.ipynb) for example.  I loaded the dataset from sklearn and was able to complete the tutorial, but right now the packages in that tutorial are incompatible because of this issue.

**Comment by vizhur** [comment]
@benbogart azureml-opendatasets does not depend directly on cryptography. As I can see, the only dependency that might bring the >=3 is an extra 'crypto' on the latest PyJWT that might be referenced in the nested dependencies. conda/pip should resolve the dependencies for the new environments. For partial environment update there is a high chance to hit such issues.

**Comment by benbogart** [comment]
@vizhur I can't reproduce this error now.  I'm sorry to say I don't know what changed but its no longer an issue.  Thank you for your help.

**Comment by singankit** [comment]
@jzazo cryptography package has been unpinned in azureml-core package [version](https://pypi.org/project/azureml-core/1.24.0.post2/).

**Comment by jzazo** [comment]
Thank you! I have unpinned the package and everything updated correctly. Cryptography updated to latest version. Will now close.

**Comment by harvinder-singh44** [comment]
This issue has cropped up again after latest release of PyopenSSL 22.1.0, Sept 25th. PyopenSSL is pulling cryptography 38.0.x whereas azureml-core is expecting it to be v37.0.x.

**Comment by chrisk314** [comment]
Also hitting this again as mentioned by @harvinder-singh44. Please resolve the pinning.

**Comment by vizhur** [comment]
Please open a new issue. Original issue was resolved.
