### ISSUE TITLE
Azure ML Run docker command to pull public image failed 

### ISSUE THREAD

**Issue by scofield1991** [Azure/MachineLearningNotebooks#1371]
'm going through this notebook: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/train-on-remote-vm/train-on-remote-vm.ipynb

I need to start the training using the docker image from my local registry. I provided all required data in the environment I created:

conda_env.docker.enabled = True
conda_env.docker.base_image = "tf_od_api:latest"
conda_env.docker.base_image_registry.address = "mylocalacr.azurecr.io"
conda_env.docker.base_image_registry.username = "MyToken"
conda_env.docker.base_image_registry.password = "MyPassword"

conda_env.python.user_managed_dependencies = True

src = ScriptRunConfig(source_directory='azureml-examples/workflows/train/fastai/pets/src',
                      script='aml_wrapper.py',
                      compute_target=attached_dsvm_compute,
                      environment=conda_env)
run = exp.submit(config=src)
run.wait_for_completion(show_output=True)

And when I start the pipeline I got: "FailedPullingImage: Unable to pull docker image\n\timageName: Run docker command to pull public image failed with error: error response from daemon: unauthorized: authentication required"

If I set conda_env.python.user_managed_dependencies = False

then the pipeline can pull my image from my local registry, build a new image with all required python dependencies on top of my base image and push the new image to my local registry. But on the second step of the pipeline, when it tries to pull the image for running it, that was just created and pushed, it again crashes with the same error: "Run docker command to pull public image failed with error: error response from daemon: unauthorized: authentication required"

**Comment by vizhur** [comment]
please try this 
https://github.com/Azure/MachineLearningNotebooks/issues/1247#issuecomment-738887772

**Comment by scofield1991** [comment]
Seems like it solved the issue. Thanks!
