### ISSUE TITLE
Running automl_setup.cmd fails running with Python 3.7.

### ISSUE THREAD

**Issue by tchmiel** [Azure/MachineLearningNotebooks#138]
Running the `automl_setup.cmd` with Anaconda or Miniconda (Python 3.7) crashes the Anaconda prompt on activation of the env.  It appears to be a keras mismatch within Anaconda itself and not directly related to the actual setup.   However, if one runs `automl_setup.cmd`, it can hose one's other conda envs.   

Anaconda prompt starts, try to activate an env,  and then immediately closes(crashes).   Very similar behavior found [here](https://stackoverflow.com/questions/53271865/anaconda-prompt-crashes-as-soon-as-i-activate-tensorflow-env):  Ferari's [image](https://i.stack.imgur.com/NMhLD.png,), shows the contents of the window before it crashes.

To workaround this issue, I created a generic python environment  within Anaconda

- `conda  create -n py36_automl  python=3.6`
- `activate py36_automl `
- `conda install`ed [each dependency separately ]in automl_env.yml (with exception of tensorflow and keras)
- `conda install keras`

**Comment by rastala** [comment]
The setup depends on Tensorflow which doesn't support Python 3.7 currently see: https://github.com/tensorflow/tensorflow/issues/20517

**Comment by tchmiel** [comment]
Thanks for finding the root case.

On [automated_machine_learning readme](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning) page, it states to install mini-conda and choose Python 3.7 or higher.  IMO, this page should state this compatibility issue, and recommend an earlier version of MiniConda that allows the `automl_setup.cmd` to run successfully and avoid this rabbit hole.

**Comment by jeff-shepherd** [comment]
The note about Python 3.7 or higher relates to the Miniconda installation page, which has the choice of 3.7 or 2.7.  automl_setup.cmd, does specify python 3.6 when it creates the new environment.   Most people install Miniconda, choose Python 3.7 and don't see this problem.  So, I think that something else is happening here.  Was this a new conda installation?  Was it conda or miniconda?  Were other packages installed before AutoML?

**Comment by tchmiel** [comment]
Due to a corrupted environment in Anaconda, (see my [other thread here](https://github.com/MicrosoftDocs/azure-docs/issues/20750#issuecomment-447498391),  I tried to run the `automl_setup.cmd` to create a new env but it failed (I forget the specific error).  I tried to update the conda env first, but still failed, - (then after numerous of other fails),  At some point,  other envs would crash the Anaconda prompt on activate as described above.

I completely uninstalled VS2017, VSCode, and Anaconda, and at this point, I now had no python environments installed on my box. Full Reboot.  Installed Anaconda using python3.7 version (5.3.1), then ran autocmd_setup next (no other envs), and got the above behavior.  Uninstalled Anaconda, installed Miniconda, (thinking this might make a difference) then ran autocmd_setup again  (again no other envs), and still got the above behavior. Uninstalled Miniconda, and finally reinstalled an older version of Anaconda (5.2.0), and then performed the workaround as described above. No mods to `automl_setup.cmd` or.`automl_env.yml` files.

If you can't repro, you can close the issue.  Just hoping that someone else didn't have to suffer thru the same learning curve I had to.

**Comment by jeff-shepherd** [comment]
Thanks for the details.  I haven't been able to reproduce the problem so far with either Conda 64-bit or Miniconda 64-bit.

There is an issue with 32-bit, which causes automl_setup to fail with:

   ResolvePackageNotFound:
     - tensorflow[version='>=1.12.0']
     - keras

I have updated the README.md to recommend Miniconda 64-bit. 
Were any of your conda/miniconda installs 32-bit ?

**Comment by tchmiel** [comment]
Only installed64bit only - `Anaconda3-5.3.1-Windows-x86_64.exe`  and `Miniconda3-latest-Windows-x86_64.exe` - I just double checked the installs in my downloads folder to be sure.
