### ISSUE TITLE
How to mount a dataset using docker?

### ISSUE THREAD

**Issue by crisansou** [Azure/MachineLearningNotebooks#1381]
Hello,

I'm using the docker image **python:3.6.9** and when I execute the command `dataset.mount(mounted_path)` the following message is displayed:

![image](https://user-images.githubusercontent.com/29444086/110381865-d8dfc680-8038-11eb-9c84-77e228fcd70c.png)

I've set the --privileged flag and --cap-add SYS_ADMIN --device /dev/fuse, as suggested by the documentation, but it didn't work. For example: 

`docker run --privileged --cap-add SYS_ADMIN --device /dev/fuse -d -i --name pythonaml -v "D:\aml:/usr/src" python:3.6.9`

Do you know guys what's missing?

Reference: 

- Mount: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.filedataset?view=azure-ml-py#mount-mount-point-none----kwargs-

Best regards,
Cristina

**Comment by YuandaXu** [comment]
Hi, Crisansou,

This looks like libfuse was not installed, would you double check and try to install it if it's not installed yet?

Thanks,
Yuanda

**Comment by crisansou** [comment]
Hello @YuandaXu ,

It was not installed. I installed it and the dataset.mount(mounted_path) command worked correctly, thanks!

apt-get install -y libfuse-dev

Best regards,
Cristina

> libfuse

**Comment by YuandaXu** [comment]
Hi, Cristina,

Thanks for updates. Great to hear this~!

Best,
Yuanda
