### ISSUE TITLE
azureml.core.webservice.local.LocalWebservice.deploy_configuration fails in Python SDK 1.24.0

### ISSUE THREAD

**Issue by olbermann** [Azure/MachineLearningNotebooks#1383]
SDK version: 1.24.0

azureml.core.webservice.local.LocalWebservice.deploy_configuration fails because
azureml.core.webservice.local.LocalWebserviceDeploymentConfiguration is missing a
print_deploy_configuration method.

**Comment by lostmygithubaccount** [comment]
hi @olbermann can you provide more information on this issue? is this an example that isn't working for you? can you provide a minimal code snippet?

**Comment by olbermann** [comment]
Deploying a model to a local webservice as in 
https://docs.microsoft.com/azure/machine-learning/how-to-deploy-existing-model


Minimal snippet is just the 2 lines:
```
from azureml.core.webservice import LocalWebservice
deployment_config = LocalWebservice.deploy_configuration()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-afaab4f4ff42> in <module>
      2                                    environment=myenv)
      3 
----> 4 deployment_config = LocalWebservice.deploy_configuration()

c:\users\olbermann\appdata\local\continuum\anaconda3\envs\xxxxxxxx\lib\site-packages\azureml\core\webservice\local.py in deploy_configuration(port)
    236         :raises: :class:`azureml.exceptions.WebserviceException`
    237         """
--> 238         return LocalWebserviceDeploymentConfiguration(port)
    239 
    240     def deploy_to_cloud(self, name=None, deployment_config=None, deployment_target=None):

TypeError: Can't instantiate abstract class LocalWebserviceDeploymentConfiguration with abstract methods print_deploy_configuration
```

Parent class has abstract method which is not implemented.

**Comment by v-strudm-msft** [comment]
Since there wasn't a post after our last comment we assume the above advice resolved it. Should there still be a question, please reopen this issue. Thank you.
