### ISSUE TITLE
azure ml Python SDK 1.24.0 image build fails with the error failed to get layer was working fine before

### ISSUE THREAD

**Issue by MAQ-Ravijit-Ramana** [Azure/MachineLearningNotebooks#1387]
![image](https://user-images.githubusercontent.com/74793968/110592377-36daee00-81a0-11eb-8fb0-de7e2ba93af1.png)

This issue wasn't present until a few days ago. Issue shows up when we submit an experiment to azure ml workspace in the image build logs. We are using mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04 base image

**Comment by vizhur** [comment]
I would think that is some transient issue. 
Side note, mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04 was deprecated in 2019, please use 
mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04 or better default cpu image from your client version that is pinned to a versioned tag

**Comment by MAQ-Ravijit-Ramana** [comment]
Still facing the same issue. Kind of blocked is their some way i could fix this. Updated the image thanks for that

**Comment by vizhur** [comment]
is it local build? if yes, try to remove the image. Have you switched to azureml/intelmpi2018.3-ubuntu16.04?

**Comment by MAQ-Ravijit-Ramana** [comment]
Nope it is remote compute build.

**Comment by MAQ-Ravijit-Ramana** [comment]
Any updates ?

**Comment by MAQ-Ravijit-Ramana** [comment]
The issue got resolved we were earlier creating an image and storing it in Azure Container Registry. Now we don't pass it to RunConfiguration() object. We create it directly in the AML Build process and that has fixed the issue though now the image is not cached anymore so that is problematic.

**Comment by vizhur** [comment]
@MAQ-Ravijit-Ramana it would be great to get some details of your scenario, like the script you running
