### ISSUE TITLE
Authentication Error iOS 14.4.1

### ISSUE THREAD

**Issue by adityaSomak** [Azure/MachineLearningNotebooks#1388]
Hi, I received an email from Core services Engineering to upgrade my iOS to 14.4.1. I have upgraded. However, while trying to use `phillytools`, it still shows an error:
```
Authentication Error: "['access_denied']". Description: "["AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.\r\nTrace ID: f0c4b1f6-852d-43e5-ba34-b7c8ac040500\r\nCorrelation ID: d7e978c9-d0f0-498a-bf40-772ceb475a78\r\nTimestamp: 2021-03-10 07:51:48Z"]" 
CC AuthenticationException:
    Message: Login failed
    InnerException None
    ErrorResponse
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "Authentication"
        },
        "message": "Login failed"
    }
}
```
I can safely authenticate and login for other services.  But for philly/azure-ml I am not able to. This error shows up when I am trying to use `pt target list amlk8s`.

**Comment by lostmygithubaccount** [comment]
hello @adityaSomak, `phillytools` is an internal Microsoft tool - you will probably receive better support on this issue in internal teams or email threads with the team

**Comment by lostmygithubaccount** [comment]
closing given no response - feel free to reach out to the Azure ML team internally or reopen as needed
