### ISSUE TITLE
dotnet-runtime-2.1 installed on Arch (GNU/Linux), but no support?

### ISSUE THREAD

**Issue by oliverw1** [Azure/MachineLearningNotebooks#1391]
I'm attempting to trigger an AzureML pipeline (`azureml.pipeline.core.pipeline.Pipeline`) from my local machine, which runs Arch Linux. It has the dotnet-runtime-2.1 installed. However, it seems that one of the steps taken is to attempt to download a tarball, which is not provided.

The error can be reproduced easily:
```
(.venv) [oliver@armstrong project]$ dotnet --list-runtimes
Microsoft.NETCore.App 2.1.26 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
(.venv) [oliver@armstrong project]$ cat debug.py 
from dotnetcore2 import runtime
runtime._enable_debug_logging()
runtime.ensure_dependencies()
(.venv) [oliver@armstrong project]$ python debug.py 
Traceback (most recent call last):
  File "/home/oliver/work/clients/A/code/project/.venv/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 272, in attempt_get_deps
    blob_deps_to_file()
  File "/home/oliver/work/clients/A/code/project/.venv/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 264, in blob_deps_to_file
    blob = request.urlopen(deps_url, context=ssl_context)
  File "/home/oliver/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/oliver/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/oliver/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/oliver/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/oliver/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/oliver/.pyenv/versions/3.7.9/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "debug.py", line 3, in <module>
    runtime.ensure_dependencies()
  File "/home/oliver/work/clients/A/code/project/.venv/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 286, in ensure_dependencies
    if not attempt_get_deps():
  File "/home/oliver/work/clients/A/code/project/.venv/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 280, in attempt_get_deps
    raise NotImplementedError(err_msg + '\n' + _unsupported_help_msg)
NotImplementedError: Linux distribution arch . does not have automatic support.
.NET Core 2.1 can still be used via dotnetcore2 if the required dependencies are installed.
Visit https://aka.ms/dotnet-install-linux for Linux distro specific .NET Core install instructions.
Follow your distro specific instructions to install `dotnet-runtime-*` and replace `*` with `2.1`.
```

It would seem that Arch is simply unsupported (no tarball provided). If that
is the case, I propose to make the error message clearer, adding that "some distributions are unsupported" to `_unsupported_help_msg`, as right now that message made it look like there was still an option using e.g. Snap (Arch has dotnet-runtime-2.1 in AUR, and a newer one in the official repo, so it's not a matter of not being able to install the dotnet-runtime).

Inspiration for the simple debug script came from #1003 , which is about similar problems but on Ubuntu 20.04, back when it was not yet supported. In #1003 it was predicted that a list of allowed distros would indeed stop certain distributions.

**Comment by YuandaXu** [comment]
Hi, @oliverw1 ,

Would like suggest you try below steps to solve it:

1. Type "python" in terminal, under python prompt try below codes:
    ```
    from dotnetcore2 import runtime
    bin_folder  = runtime._get_bin_folder()
    missing_packages = runtime._gather_dependencies(bin_folder)
    print(missing_packages)
    ```
    Then you can see what package is missing.
    (Doing this is because the indication of missing package could not be printed on Arch Linux due to a logging level problem.)

2. Try to install corresponding packages.
    For latest Arch Linux image (2021.03.01-x86_64), my test shows the missing package is "liblttng-ust.so.0" which can be installed by:
    ```
    pacman -Sy lttng-ust
    yay -Sy lttng-tools
    yay -Sy lttng-modules
    
    ```	
    On my local test, after installation of this missing package, the ensure_dependencies() was executed without problem. If you get notice of missing other packages, you may also want to install them before try ensure_dependencies() again.

**Comment by oliverw1** [comment]
@YuandaXu super, that worked. Had the same missing library. The packages from the Arch User Repository are optional, the first command installed the shared object. Thanks a lot for your advice!

**Comment by gegnew** [comment]
Hello all, sorry to necropost, but I have the same problem, but installing `liblttng` _doesn't_ solve the problem. I'm a bit at a loss, since this seems to have worked for everyone else with this issue

**Comment by behrica** [comment]
> Hello all, sorry to necropost, but I have the same problem, but installing `liblttng` _doesn't_ solve the problem. I'm a bit at a loss, since this seems to have worked for everyone else with this issue

I needed to do this in /usr/lib

```
ln -s liblttng-ust.so liblttng-ust.so.0
```
