### ISSUE TITLE
How do use ParallelRunStep with a Parameterized Dataset/DataPath Input

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/MachineLearningNotebooks#1393]
The ParallelRunStep Documentation suggests the following:

A named input Dataset (`DatasetConsumptionConfig` class)

    path_on_datastore = iris_data.path('iris/')
    input_iris_ds = Dataset.Tabular.from_delimited_files(path=path_on_datastore, validate=False)
    named_iris_ds = input_iris_ds.as_named_input(iris_ds_name)

Which is just passed as an Input:

    distributed_csv_iris_step = ParallelRunStep(
        name='example-iris',
        inputs=[named_iris_ds],
        output=output_folder,
        parallel_run_config=parallel_run_config,
        arguments=['--model_name', 'iris-prs'],
        allow_reuse=False
    )

The Documentation to submit Dataset Inputs as Parameters suggests the following:
The Input is a `DatasetConsumptionConfig` class element

    tabular_dataset = Dataset.Tabular.from_delimited_files('https://dprepdata.blob.core.windows.net/demo/Titanic.csv')
    tabular_pipeline_param = PipelineParameter(name="tabular_ds_param", default_value=tabular_dataset)
    tabular_ds_consumption = DatasetConsumptionConfig("tabular_dataset", tabular_pipeline_param)

Which is passed in `arguments` as well in `inputs`

    train_step = PythonScriptStep(
        name="train_step",
        script_name="train_with_dataset.py",
        arguments=["--param2", tabular_ds_consumption],
        inputs=[tabular_ds_consumption],
        compute_target=compute_target,
        source_directory=source_directory)

While submitting with new parameter we create a new `Dataset` class:

    iris_tabular_ds = Dataset.Tabular.from_delimited_files('some_link')

And submit it like this:

    pipeline_run_with_params = experiment.submit(pipeline, pipeline_parameters={'tabular_ds_param': iris_tabular_ds})

However, how do we combine this: How do we pass a Dataset Input as a Parameter to the ParallelRunStep?

If we create a `DatasetConsumptionConfig` class element like so:

    tabular_dataset = Dataset.Tabular.from_delimited_files('https://dprepdata.blob.core.windows.net/demo/Titanic.csv')
    tabular_pipeline_param = PipelineParameter(name="tabular_ds_param", default_value=tabular_dataset)
    tabular_ds_consumption = DatasetConsumptionConfig("tabular_dataset", tabular_pipeline_param)

And pass it as an argument in the ParallelRunStep, it will throw an error.

References:

 1. [Notebook with Dataset Input Parameter][1]
 2. [ParallelRunStep Notebook][2]

  [1]: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-showcasing-dataset-and-pipelineparameter.ipynb
  [2]: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/parallel-run/tabular-dataset-inference-iris.ipynb

**Comment by tracychms** [comment]
Please follow this [notebook ](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/parallel-run/file-dataset-image-inference-mnist.ipynb) with a full example of how to parameterize input dataset for ParallelRunStep.
