### ISSUE TITLE
ParallelRunStep hangs forever when passed a model_name referring to a model containing a dataset

### ISSUE THREAD

**Issue by vla6** [Azure/MachineLearningNotebooks#1394]
Notebook to reproduce this issue: https://github.com/vla6/Azure_notes/blob/main/parallelrunstep_hang_model_name_MOD.ipynb

I am finding that a ParallelRunStep hangs forever when you pass the name of a registered model that contains any dataset(s) in an argument called "--model_name". The parallel run appears to fail to schedule any mini batches and hangs without scheduling. The error occurs whether or not you ever use the model in the script.  The same model with no dataset is fine.

In addition, the argument "--model_name" seems to be reserved even though that is not documented anywhere as far as I can tell. If you pass some dummy string to the argument called "--model_name", the script will create an error. This is true even if that argument isn't actually used anywhere in the script, or if you didn't intend it to refer to a registered model

**Comment by vla6** [comment]
I should add that I discovered this when code that had worked fine a few weeks ago suddenly started not working.  The scripts were fine around March 9, started failing March 18.  So this is a new issue of some sort.

**Comment by tracychms** [comment]
We recently reserved the "--model_name" argument for an upcoming feature, will update the doc and sample notebook. We are looking into the model with dataset issue, will get back with the finding.

**Comment by dwt0317** [comment]
@vla6 Thanks for providing detailed reproducing steps. But I can only reproduce this issue once in my workspace. 
Could you provide more information about:
1. Does this issue always happen when you use model with datasets? 
2. Which region is your workspace in?
3. Could you share the log in logs/sys/node/(ip)/_main.txt?

For "--model_name", currently we will try downloading the model before calling user's script if "--model_name" is specified. That's why it will throw error if you pass a nonexistent model name.

**Comment by vla6** [comment]
Here is the info:

1. Does this issue always happen when you use model with datasets? **Yes, it has always happened for me.  I had the issue with my own code (which is much different) and could reproduce with the simple "iris" example.**
2. Which region is your workspace in? **East US**
3. Could you share the log in logs/sys/node/(ip)/_main.txt?  **These are attached, for the 2 nodes used**


[_main.txt](https://github.com/Azure/MachineLearningNotebooks/files/6206993/_main.txt)
[_main (1).txt](https://github.com/Azure/MachineLearningNotebooks/files/6206994/_main.1.txt)

**Comment by dwt0317** [comment]
This issue may be related to dataset. We are cooperating with dataset team to narrow down the root cause. Will update here once we come into a conclusion.

**Comment by dwt0317** [comment]
@vla6 We released a fix yesterday. Please help check if this issue is still ongoing.

**Comment by vla6** [comment]
I assume that I should spin up a new cluster or VM to test this issue, to get the updates?  Or was the fix entirely outside the packages/environment?  Thanks!

**Comment by dwt0317** [comment]
> I assume that I should spin up a new cluster or VM to test this issue, to get the updates? Or was the fix entirely outside the packages/environment? Thanks!

Sorry for the late response. You don't need to do anything. This fix happened in our backend.
