### ISSUE TITLE
How to check if MSI auth will work so we can fallback to Interactive?

### ISSUE THREAD

**Issue by norman-v** [Azure/MachineLearningNotebooks#1395]
Is there a clean way to check from the instance of this MsiAuthentication if it is configured or not (or if it is running in a VM with managed identity vs running locally)? We like code that work seamlessly in the Azure environment as well as when we are running it locally. The Azure SDK does this serial checking of available authentication mechanisms with DefaultAzureCredential. I wonder if there is a way we can do the same in Azure ML.

We can attempt to authenticate and then fail, but it is not very clean (we don't need to see auth failure errors in environments where we know MSI is not setup and wouldn't even work)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeee5fbb-56db-817e-f095-928ea13e478e
* Version Independent ID: 10f2c77a-1dd7-29bb-7e04-c57885c39813
* Content: [azureml.core.authentication.MsiAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.msiauthentication?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.MsiAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.MsiAuthentication.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
have you seen this notebook? https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb

**Comment by paulshealy1** [comment]
try/catch is your best option to support this scenario.
