### ISSUE TITLE
AutoML: See hyperparameters

### ISSUE THREAD

**Issue by swaticolab** [Azure/MachineLearningNotebooks#1399]
I have created a classification model using Azure AutoML in GUI. I have got the best model. 
I can see the scoring metrices. Is there any way to also get the hyperparameters of the best model?

**Comment by CESARDELATORRE** [comment]
@swaticolab In the UI, the visibility of hyperparameters used by the algo (or several algos if using ensembling) is going to be provided soon.

In the meantime, you can use SDK code to query/print those hyperparameters like in the following code:

(Full sample notebook here)
https://github.com/CESARDELATORRE/Easy-AutoML-MLOps/blob/master/notebooks/other-scenarios/show-automl-model-algos-hyperparams/show-automl-model-algos-hyperparams.ipynb

```
from azureml.train.automl.run import AutoMLRun

ws = Workspace.from_config()
experiment = ws.experiments['automl-classification']
automl_run = AutoMLRun(experiment, run_id = 'AutoML_YOUR-AUTOML-RUN-ID--89fd-41cc-905f-2f41a5a98883')

best_run, model_from_aml = automl_run.get_output()

print_model(model_from_aml) 

```

And the function to "print" the model is this:

```
from pprint import pprint

def print_model(model, prefix=""):
    for step in model.steps:
        print(prefix + step[0])
        if hasattr(step[1], 'estimators') and hasattr(step[1], 'weights'):
            pprint({'estimators': list(e[0] for e in step[1].estimators), 'weights': step[1].weights})
            print()
            for estimator in step[1].estimators:
                print_model(estimator[1], estimator[0]+ ' - ')
        elif hasattr(step[1], '_base_learners') and hasattr(step[1], '_meta_learner'):
            print("\nMeta Learner")
            pprint(step[1]._meta_learner)
            print()
            for estimator in step[1]._base_learners:
                print_model(estimator[1], estimator[0]+ ' - ')
        else:
            pprint(step[1].get_params())
            print()
            
```

You can print any model coming from AutoML, like from child runs, too. Not just the "best model".

Hope it helps,

**Comment by CESARDELATORRE** [comment]
Closing this issue sine a solution was already provided days ago.
