### ISSUE TITLE
Feature request: Allow a (small) dataframe as sample_input_dataset for models

### ISSUE THREAD

**Issue by epa095** [Azure/MachineLearningNotebooks#1400]
If `X,y` are pandas dataframes I would like to be able to do:
```python
            Model.register(
                workspace=ws,
                model_path=model_path,
                model_name=model_name,
                sample_input_dataset=X.head(),
                sample_output_dataset=y.head(),
            )
```
Today I need to register them as datasets and give an explicit datastore. I understand the desire to track datasets explicitly, but I think it would be quite usefull to be able to upload a small dataset which is stored together with the model with as little mocking around as possible, just in the same way as we can log images and metrics. So a kind of "log_input_datset" maybe;-)

**Comment by jpe316** [comment]
We'll be addressing this in our 2.0 release - we are overhauling our data management experience there. Thanks for the feedback!
