### ISSUE TITLE
Dataset.Tabular.register_pandas_dataframe - Error saving date column

### ISSUE THREAD

**Issue by crisansou** [Azure/MachineLearningNotebooks#1401]
Hello,

I used the **Dataset.Tabular.register_pandas_dataframe** function to save the dataset and it appeared in the log that the data was saved successfully.

![image](https://user-images.githubusercontent.com/29444086/112160732-38a5a800-8bc9-11eb-9411-e7a042411a29.png)

However, when returning the data from the dataset, the string ERROR appeared in all rows of the date column.

![image](https://user-images.githubusercontent.com/29444086/112160767-41967980-8bc9-11eb-8900-f58da98ce1ac.png)

Do you know how to solve the problem, please?

Best regards,
Cristina

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9b1aee32-5a1f-2ef1-ee76-30b17999db87
* Version Independent ID: f4785272-a81d-e9cc-c6a5-9d41c8dcd90b
* Content: [azureml.data.dataset_factory.TabularDatasetFactory class - Azure Machine Learning Python](https://docs.microsoft.com/pt-br/python/api/azureml-core/azureml.data.dataset_factory.tabulardatasetfactory?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.dataset_factory.TabularDatasetFactory.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr.pt-BR/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.dataset_factory.TabularDatasetFactory.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by YuandaXu** [comment]
Hi, crisansou,

I tried to reproduce your problem but didn't see the failure. Do you mind sharing some information for investigation? Below information will be very helpful: 
- Your subscription Id
- Your workspace name
- Your region

Thank you!

**Comment by crisansou** [comment]
Hi @YuandaXu ,

Please try this code, if you are unable to reproduce I pass you the requested data. The workspace is in West Europe region:

import pandas as pd
import datetime as dt
import azureml.core
from azureml.core import Workspace, Datastore, Dataset

print("Azure ML Version", azureml.core.VERSION)

#### Get Workspace
ws = Workspace.from_config()

####  Get Datastore
datastore = Datastore.get_default(ws)

####  Generating a dummy dataset
df = pd.util.testing.makeDataFrame()
df['data_exec'] = dt.date.today()
df.head()

![image](https://user-images.githubusercontent.com/29444086/114031142-78b78c80-9851-11eb-8b51-c0c44929ee3a.png)

try:
    Dataset.Tabular.register_pandas_dataframe(dataframe  = df, 
                                              target = datastore,
                                              name = 'dummy_dataset',
                                              description='Dummy Dataset')
except Exception as ex:
    print('Error register_pandas_dataframe: ', ex)

![image](https://user-images.githubusercontent.com/29444086/114031242-8ec54d00-9851-11eb-9d96-098d1e39ec12.png)

![image](https://user-images.githubusercontent.com/29444086/114031824-1f039200-9852-11eb-9f64-21b4b4f7d7f9.png)


Best regards,
Cristina




> Hi, crisansou,
> 
> I tried to reproduce your problem but didn't see the failure. Do you mind sharing some information for investigation? Below information will be very helpful:
> 
> * Your subscription Id
> * Your workspace name
> * Your region
> 
> Thank you!

**Comment by YuandaXu** [comment]
Thanks, Cristina!

I tried your steps and did see the error. Let me confirm with our experts for more details, will back to you soon.

**Comment by YuandaXu** [comment]
Hi, Cristina,

Some updates:
1. I checked dtypes of dataframe, it turned out the 'data_exec' is datetime.date instead of datetime64, which currently is not supported in data process engine therefore the unsupported values was replaced by string "ERROR" in default.

2. As a workaround, either a datetime.datetime object or a string would work here, so you can try replace it with either a datetime.datetime or convert it to a string. I validated both, they do work.

3. I also double confirmed supported objects, basically in current stage, we support numpy arrays with datetime64 type, other objects supported would be strings, every other primitive type (numbers, bools) should be stored in numpy arrays specific to that type.

Hopefully above information is helpful.

Thanks!

**Comment by crisansou** [comment]
Hi @YuandaXu,

Thanks for the updates! I used datetime64 and string types and it worked in both cases.

![image](https://user-images.githubusercontent.com/29444086/114939654-252bdc80-9e17-11eb-8186-ddf152eb7e72.png)
 
![image](https://user-images.githubusercontent.com/29444086/114939770-4c82a980-9e17-11eb-8c8b-a7e8ec91af34.png)


Best regards,
Cristina




> Hi, Cristina,
> 
> Some updates:
> 
> 1. I checked dtypes of dataframe, it turned out the 'data_exec' is datetime.date instead of datetime64, which currently is not supported in data process engine therefore the unsupported values was replaced by string "ERROR" in default.
> 2. As a workaround, either a datetime.datetime object or a string would work here, so you can try replace it with either a datetime.datetime or convert it to string. I validated both, they do work.
> 3. I also double confirmed supported objects, basically in current stage, we support numpy arrays with datetime64 type, other objects supported would be strings, every other primitive type (numbers, bools) should be stored in numpy arrays specific to that type.
> 
> Hopefully above information is helpful.
> 
> Thanks!
