### ISSUE TITLE
experiment.submit - The experiment does not generate a sequence number for the run

### ISSUE THREAD

**Issue by crisansou** [Azure/MachineLearningNotebooks#1403]
Hi,

I'm training the model using the code below:

![image](https://user-images.githubusercontent.com/29444086/112179572-90e4a600-8bd9-11eb-88d7-2ed54083c940.png)

In the first run, the id was set to 1, but in the second the id was set to 16. The correct thing would be to show id 2.

![image](https://user-images.githubusercontent.com/29444086/112179653-a35edf80-8bd9-11eb-8831-ea2c84fc7c5d.png)

Does anyone know why this happens and how do I fix it?

Best regards,
Cristina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
* Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
* Content: [azureml.core.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
Run 1 is a parent run - if you click into it then the child runs, you should see 2-15. So the next run is 16

​- Cody
________________________________
From: crisansou ***@***.***>
Sent: Tuesday, March 23, 2021 9:20 AM
To: Azure/MachineLearningNotebooks ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/MachineLearningNotebooks] experiment.submit - The experiment does not generate a sequence number for the run (#1403)


Hi,

I'm training the model using the code below:

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29444086%2F112179572-90e4a600-8bd9-11eb-88d7-2ed54083c940.png&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497051172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MGWvV9gp2YytlmkjDmJBPwaSYlJ40v3Tp2d293JKXSY%3D&reserved=0>

In the first run, the id was set to 1, but in the second the id was set to 16. The correct thing would be to show id 2.

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29444086%2F112179653-a35edf80-8bd9-11eb-8831-ea2c84fc7c5d.png&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497061169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=scD2nBacRy%2FrV8NWmZZXnnvugmCbbi4m7OEt1bE%2FyzM%3D&reserved=0>

Does anyone know why this happens and how do I fix it?

Best regards,
Cristina

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
  *   Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
  *   Content: azureml.core.Experiment class - Azure Machine Learning Python<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpython%2Fapi%2Fazureml-core%2Fazureml.core.experiment(class)%3Fview%3Dazure-ml-py&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497061169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GJWWJo58zf1NxJ4spkH5YdlL0oJHd%2FMR25v7A6a4dTU%3D&reserved=0>
  *   Content Source: AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FMachineLearning-Python-pr%2Fblob%2Flive%2FAzureML-Docset%2Fstable%2Fdocs-ref-autogen%2Fazureml-core%2Fazureml.core.Experiment(class).yml&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497071166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fhjiufmQFDN927GeeDIPSY4Pgi8cOTKeyGJ9R222VTk%3D&reserved=0>
  *   Service: machine-learning
  *   Sub-service: core
  *   GitHub Login: @DebFro<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDebFro&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497081158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UvW0vWzaLwItE8bjYIJxnnRQkXcAxksq72Ei1KbTyTg%3D&reserved=0>
  *   Microsoft Alias: debfro

**Comment by crisansou** [comment]
> Run 1 is a parent run - if you click into it then the child runs, you should see 2-15. So the next run is 16​- Cody
> […](#)
> ________________________________ From: crisansou ***@***.***> Sent: Tuesday, March 23, 2021 9:20 AM To: Azure/MachineLearningNotebooks ***@***.***> Cc: Subscribed ***@***.***> Subject: [Azure/MachineLearningNotebooks] experiment.submit - The experiment does not generate a sequence number for the run (#1403) Hi, I'm training the model using the code below: [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29444086%2F112179572-90e4a600-8bd9-11eb-88d7-2ed54083c940.png&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497051172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MGWvV9gp2YytlmkjDmJBPwaSYlJ40v3Tp2d293JKXSY%3D&reserved=0> In the first run, the id was set to 1, but in the second the id was set to 16. The correct thing would be to show id 2. [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29444086%2F112179653-a35edf80-8bd9-11eb-8831-ea2c84fc7c5d.png&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497061169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=scD2nBacRy%2FrV8NWmZZXnnvugmCbbi4m7OEt1bE%2FyzM%3D&reserved=0> Does anyone know why this happens and how do I fix it? Best regards, Cristina
> ________________________________ Document Details ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking. * ID: a49038bc-1bad-a7ca-b107-760f156f4ee9 * Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd * Content: azureml.core.Experiment class - Azure Machine Learning Python<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpython%2Fapi%2Fazureml-core%2Fazureml.core.experiment(class)%3Fview%3Dazure-ml-py&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497061169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GJWWJo58zf1NxJ4spkH5YdlL0oJHd%2FMR25v7A6a4dTU%3D&reserved=0> * Content Source: AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FMachineLearning-Python-pr%2Fblob%2Flive%2FAzureML-Docset%2Fstable%2Fdocs-ref-autogen%2Fazureml-core%2Fazureml.core.Experiment(class).yml&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497071166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fhjiufmQFDN927GeeDIPSY4Pgi8cOTKeyGJ9R222VTk%3D&reserved=0> * Service: machine-learning * Sub-service: core * GitHub Login: @DebFro<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDebFro&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497081158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UvW0vWzaLwItE8bjYIJxnnRQkXcAxksq72Ei1KbTyTg%3D&reserved=0> * Microsoft Alias: debfro — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FMachineLearningNotebooks%2Fissues%2F1403&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497081158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NMRGo11U9%2FChVDI3nnBdBwr4PDa91Mdxv74SS8F4GZI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANCGO2MNYORXM2UJDNHCTP3TFC5V7ANCNFSM4ZVQITIA&data=04%7C01%7Ccody.peterson%40microsoft.com%7C5355330695a44f86d00208d8ee179e30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521132497091155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UoWTpIzgVgm8X4VZaO2QLO%2BtysWLvr9Q7Uy%2BBqJ9cSc%3D&reserved=0>.

Hi,

I get it, I thought the parent id was independent of the child. But if it's just one, ok, thank you!
