### ISSUE TITLE
ParallelRunStep Error: invalid mount config for type "volume": field BindOptions must not be specified

### ISSUE THREAD

**Issue by MelissaKR** [Azure/MachineLearningNotebooks#1405]
Hi,

I'm trying to run a batch scoring job on Azure ML, and I run into this error in the 55_azureml-execution log:

**"Running Docker Command attempt 1 failed with err: exit status 125,docker: Error response from daemon: invalid volume specification: '$AZ_BATCHAI_JOB_MOUNT_ROOT/..../: invalid mount config for type "volume": field BindOptions must not be specified."**

I've tried multiple variations of how I pass my registered File dataset to ParallelRunStep, with as_mount(), as_download(), wrapping it in DatasetConsumptionConfig, but nothing works. I've done parallel batch inferencing before on a similar dataset (images) with the very same settings, so I'm confused why the docker is throwing this error.

I'm using the Default CPU image as the base docker image, and 2 nodes of STANDARD_D2_V2 as compute target. Here is the code snippet:

    parallel_run_config = ParallelRunConfig(
        source_directory=str(src_directory),
        entry_script=entry_script_name,
        mini_batch_size=PipelineParameter(
            name="batch_size_param",
            default_value=4
        ),
        error_threshold=5,
        output_action="append_row",
        append_row_file_name="batch_masks_putput.txt",
        environment=batch_run_env,
        compute_target=compute_target,
        process_count_per_node=PipelineParameter(
            name="process_count_param",
            default_value=2
        ),
        node_count=2
    )

    frames_ds = Dataset.get_by_name(
            workspace=workspace_name, name=frames_name, version='latest'
        )
    frames_ds_consumption = DatasetConsumptionConfig(
        "frames_ds_config", frames_ds
    ).as_mount()
    output_data = PipelineData(name="batch_scoring", datastore=ds).as_dataset()

    parallelrun_step = ParallelRunStep(
        name="batch-score",
        parallel_run_config=parallel_run_config,
        inputs=[frames_ds_consumption],
        output=output_data,
        allow_reuse=False
    )

I'd really appreciate some help with this issue.

**Comment by MelissaKR** [comment]
Hi @tracychms , thank you for your response. Under Outputs+logs/logs/azureml/stderrlogs.txt I get:

job RunId is 4c1e33e1-a762-47ff-9e3f-9ba1805be1e7. Error: {"Error":{"Code":"UserError","Severity":null,"Message":"AzureMLCompute job failed.\nFailedStartingContainerUserError: Incorrect arguments or poorly formatted environment variables set. Please check 55_azureml-execution for error details\n\tFailedStartingContainerUserError: Unable to start docker container\n\timageName: #####.azurecr.io/azureml/azureml_######\n\terr: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/#####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\n\tReason: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\nFailedStartingContainerUserError: Incorrect arguments or poorly formatted environment variables set. Please check 55_azureml-execution for error details\n\tFailedStartingContainerUserError: Unable to start docker container\n\timageName: ####.azurecr.io/azureml/azureml_#####\n\terr: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/#####/azureml/#####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\n\tReason: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\n\tInfo: Failed to prepare an environment","MessageFormat":"{Message}","MessageParameters":{"Message":"AzureMLCompute job failed.\nFailedStartingContainerUserError: Incorrect arguments or poorly formatted environment variables set. Please check 55_azureml-execution for error details\n\tFailedStartingContainerUserError: Unable to start docker container\n\timageName: ####azurecr.io/azureml/azureml_####\n\terr: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\n\tReason: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\nFailedStartingContainerUserError: Incorrect arguments or poorly formatted environment variables set. Please check 55_azureml-execution for error details\n\tFailedStartingContainerUserError: Unable to start docker container\n\timageName: ####.azurecr.io/azureml/azureml_####\n\terr: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\n\tReason: docker: error response from daemon: invalid volume specification: '$az_batchai_job_mount_root/####:/mnt/batch/tasks/shared/ls_root/jobs/####/azureml/####/mounts/workspaceblobstore/azureml/####/####/../../mounts/workspaceblobstore/azureml/####/$az_batchai_job_mount_root/####:rslave': invalid mount config for type \"volume\": field bindoptions must not be specified.\nsee 'docker run --help'.\n\n\tInfo: Failed to prepare an environment for the job execution: Failed to prepare an environment for the job execution: Job environment preparation failed on 10.0.0.7 with err exit status 1.\n\tInfo2: Failed to prepare an environment for the job execution: Job environment preparation failed on 10.0.0.6 with err exit status 1."},"ReferenceCode":null,"DetailsUri":null,"Target":null,"Details":[],"InnerError":{"Code":"BadArgument","InnerError":{"Code":"AmlComputeBadRequest","InnerError":null}},"DebugInfo":null},"Correlation":{"operation":null,"request":"36959001db9458ad"},"Environment":"eastus2","Location":"eastus2","Time":"2021-03-24T15:00:02.5152724+00:00","ComponentName":"execution-worker"}

where #### are the parts I redacted.

I use the default CPU docker image (mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu18.04) and add pip packages from conda_dependencies.yml file. Here's how it looks like:

channels:
- conda-forge

dependencies:

- pip:
  - pandas==1.1.3
  - numpy==1.19.2
  - torch==1.7.1
  - scikit-learn
  - Pillow==6.2.1
  - opencv-contrib-python==4.1.0.25
  - Shapely==1.7.1
  - python-decouple>=3.3
  - future==0.18.2
  - matplotlib==3.3.2
  - torchvision==0.8.2
  - azureml-sdk
  - azureml-core
  - azureml-dataset-runtime[pandas, fuse]
  - azureml-defaults
  - azureml-telemetry

It basically looks like this:

aml_env = Environment(name=aml_env_name)
conda_dep = CondaDependencies(conda_dependencies_file_path=requirements_path)

aml_env.python.conda_dependencies.set_python_version("3.7")
aml_env.docker.enabled = True
 aml_env.python.user_managed_dependencies = False

 aml_env.docker.base_image = ("mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu18.04")

aml_env.register(workspace=workspace_name)

**Comment by MelissaKR** [comment]
I'd appreciate any insights into this problem. It seems that I am doing everything right, both based on my previous working codes and all the batch inferencing tutorials. Perhaps something internal to the API's has changed, in which case users should be notified.

**Comment by tot0** [comment]
@MelissaKR Hi Melissa, what version of azureml-sdk are you using to submit your Runs? Upgrading to recent version `>=1.20` should fix the problem you're hitting.

**Comment by MelissaKR** [comment]
@tot0 Hey, so I'm using version 1.14.0, but I'm afraid specifying the latest version would create version incompatibilities with the other packages because, during run preparation, the container collects all azureml-sdk's and picks this one. I'm however willing to give it a try if the core cause of this problem is really with azureml-sdk.

**Comment by tot0** [comment]
What is 'the container' in this context. There are two different places azureml-sdk will be installed. In the Control Plane, where you configure your Run and code and submit for training, and the Data Plane, where your training code runs in a Container on the Compute traget you submitted to.
To fix this issue a newer Control Plane SDK needs to be used.

**Comment by MelissaKR** [comment]
@tot0 Thank you for the notes. I upgraded the azureml-sdk package, but I get incompatibility errors between azureml-cli and azureml-core.:

The conflict is caused by:
    azure-cli 2.18.0 depends on azure-mgmt-keyvault==8.0.0
    azureml-core 1.20.0.post1 depends on azure-mgmt-keyvault<7.0.0 and >=0.40.0
    azure-cli 2.18.0 depends on azure-mgmt-keyvault==8.0.0
    azureml-core 1.20.0 depends on azure-mgmt-keyvault<7.0.0 and >=0.40.0

So, which of the packages in my dependencies file is installing azure-cli? What packages do you think I should specify for each of these?   
  - azureml-core
  - azureml-dataset-runtime[pandas, fuse]
  - azureml-defaults
  - azureml-telemetry
  
Thanks a lot for your help!

**Comment by tot0** [comment]
`azureml-core` is brining in the azure-cli dependency.
The package that specifically need to be updated is `azureml-pipeline-core`. I can not guarantee that some stuff won't break but if you have a hard requirment on a particular version of `azure-cli` you can install the latest `azureml-*` packages and then reinstall the specific version of azure-cli you want.

**Comment by MelissaKR** [comment]
Thanks a ton @tot0! I managed to make it work with azureml-sdk upgrade! :)

**Comment by lostmygithubaccount** [comment]
closing this issue out - please feel free to reopen or create a new issue as needed

**Comment by MelissaKR** [comment]
I've tried to run the same code with the same dependencies and environment with a smaller similar dataset after two weeks, and now I'm getting the following error in sys > error > _main:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/*****/azureml/*****/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 237, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/*****/azureml/******/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 135, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/****/azureml/******/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (187, 1)
2021-04-13 03:25:50,285|ERROR|254|140325028292352|Failed to set task visible because of (195, 1).

I get a bunch of these for each node with different KeyError values. The error for each process look like this:

2021-04-13 03:23:05,649|ERROR|334|Stop for run() unable to finish within 90 seconds for {"agent": "process000", "task_id": 16, "dequeue_count": 1, "total": 2, "succeeded": 0, "method": "run", "exc_type": "", "message": "", "detail": "", "start_time": "2021-04-13T03:21:35.275058", "duration": 90.31819200515747, "process_time": 117.17833209800001, "run_method_time": 90.31819200515747, "status": "RUN_TIMEOUT"}.

I'm wondering if something with azure ml packages has changed. I was using version 1.20 before, but trying with 1.26 for   - azureml-sdk, azureml-core, azureml-dataset-runtime[pandas, fuse], and azureml-defaults didn't help. The other thing that is interesting is I'm using Python3.7 in my environment but the error messages are for python3.8.
