### ISSUE TITLE
Missing file in quickstart

### ISSUE THREAD

**Issue by numericx** [Azure/MachineLearningNotebooks#1407]
Hi!

In the tutorials/quickstart/ section, the score.py file isn't provided for the model deployment.

**Comment by lostmygithubaccount** [comment]
this is a known issue - @AbeOmor ETA for fixing?

**Comment by lostmygithubaccount** [comment]
ETA for fix is April 5th

**Comment by stawo** [comment]
Hi @lostmygithubaccount, any update on this?

**Comment by lostmygithubaccount** [comment]
Hi @stawo it looks like the release did not go out yesterday - I would expect it to go out today, I'll follow up and update here

**Comment by lostmygithubaccount** [comment]
The file has been added: https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/quickstart/score.py 

closing this issue, apologies for the slow fix here
