### ISSUE TITLE
Container build fails when using conda_dependencies.yml on GPU instance with "prepare_image" issue

### ISSUE THREAD

**Issue by blueskypac** [Azure/MachineLearningNotebooks#1409]
**Issue:**

When using the code provided in this tutorial here: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb
The "prepare_image" pipeline fails when trying to create the docker image used for training the pytorch model. It appears from the logs that the image is build and then tried to be run but the mounting of the GPU interfaces does not work. 

Output from the script: 
`docker: error response from daemon: oci runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /mnt/docker/overlay2/46d893265be0168001238a5d158b57ef002bdb18c3259cbb0281d3c5ea300eb4/merged/run/nvidia-persistenced/socket: no such device or address: unknown.
`

I also attached the `image_build_aggregate_log.txt` logfile with more details about the execption. I did not modify the code in the sample jupyter notebook except for updating the workspace configuration. 

**Environment**
I am running this in an Azure VM Instance from a Jupyter Notebook. I am not running this inside a VPN.

[image_build_aggregate_log.txt](https://github.com/Azure/MachineLearningNotebooks/files/6224311/image_build_aggregate_log.txt)

**Comment by vizhur** [comment]
Can you please specify CPU SKU as image build compute? For training you can use any SKU

**Comment by vizhur** [comment]
@blueskypac any update? did CPU SKU resolve your issue?

**Comment by blueskypac** [comment]
@vizhur Yes, the issue was solved using a CPU SKU for the image build in the workspace config, thank you so much for your quick help.
