### ISSUE TITLE
PipelineParameter with no default value?

### ISSUE THREAD

**Issue by stanton119** [Azure/MachineLearningNotebooks#1412]
The default parameter for a PipelineParameter cannot be ignored which forces python scripts to include extra logic for working with AzureML Pipelines.

I have a python script that accepts optional arguments, I would like to be able to control them via PipelineParameters. For example in my python script I have an `optional_arg`:
```
parser = argparse.ArgumentParser("input_args")
parser.add_argument("--training_data")
parser.add_argument("--optional_arg", type=str, default=None)
args = parser.parse_args()
```
When creating a pipeline I would like to be able to setup a parameter as follows:
```
param_optional_arg = PipelineParameter(
    "optional_arg", default_value=None
)
```
This fails as `default_value` must be set.

The way I'm dealing with this at the moment is to change the logic of the receiving python script to accept a placeholder value and change it after loading:
```
parser = argparse.ArgumentParser("input_args")
parser.add_argument("--training_data")
parser.add_argument("--optional_arg", type=str, default=None)
args = parser.parse_args()
if args.optional_arg == "None":
    args.optional_arg = None
```

and the PipelineParameter setup as:
```
param_optional_arg = PipelineParameter(
    "optional_arg", default_value="None"
)
```

This feels quite clunky as any exposure optional arguments require extra logic to work with Pipelines, is there a better way or is this a possible new feature?

I couldn't find anything on this is existing issues - the most related discussion was here about #668.

Thanks

**Comment by shbijlan** [comment]
Hi @stanton119 thank you for your feedback. This is by design, however, we will take this into consideration for future changes.
