### ISSUE TITLE
How to effectively use azureml.exceptions.WebserviceException for efficient REST API Error Management?

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/MachineLearningNotebooks#1413]
In Azure Machine Learning Service, when we deploy a Model as an AKS Webservice Endpoint, how can we raise exceptions to let the end-user get proper feedback if their API call is unsuccessful? Azure mentions using `azureml.exceptions.WebserviceException` in their documentation. However, how do we use this class to raise exceptions in case the API call cannot be processed properly and the end-user is responsible for it?

**Comment by Chris113113** [comment]
@anirbansaha96 can you link to the doc you mention? The only doc I'm aware of about authoring errors is here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-advanced-entry-script#binary-data
 
Which mentions using AMLResponse in the scoring file.

AMLResponse will allow the writer of the scoring file to set a custom error message and api response code.

**Comment by anirbansaha96** [comment]
Yes `return AMLResponse("Message", status-code)` is what I was looking for. The documentation I was referring to: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.exceptions.webserviceexception?view=azure-ml-py
