### ISSUE TITLE
Tutorial - AutoML: classification-bank-marketing-all-features

### ISSUE THREAD

**Issue by numericx** [Azure/MachineLearningNotebooks#1422]
Hi AzureML team,

I'm trying to run the classification-bank-marketing-all-features notebook and I obtain an joblib module not found error.

The score.py script is given by the AutoML experiment.

Do I need to specify an environment to deploy this? It's not done in the notebook...

See the attached screenshot.
![AutoML-BankMarketing](https://user-images.githubusercontent.com/75331669/113896655-25353800-9798-11eb-92c2-bbad0545986b.png)

**Comment by pieths-ms** [comment]
Hi @numericx.

Are you still seeing this issue?
What version of the SDK were you using when you executed the notebook?
Was this notebook run locally or in an AzureML compute instance?

Could you try re-running the notebook and see if you still encounter the same issue? Thanks.

**Comment by swatig007** [comment]
closing due to no response for a couple of months
