### ISSUE TITLE
Give us the steps of the migration to use DockerConfiguration

### ISSUE THREAD

**Issue by urasandesu** [Azure/MachineLearningNotebooks#1426]
When we updated `azureml-core` to 1.26.0 and ran some notebooks, the following warning has begun to indicate: 
```
'enabled' is deprecated. Please use the azureml.core.runconfig.DockerConfiguration object with the 'use_docker' param instead.
```

So we searched in this repository, but there were no steps to resolve this warning.
(However, we found the example notebooks that will get the same warning ... : [NVIDIA RAPIDS in Azure Machine Learning](https://github.com/Azure/MachineLearningNotebooks/blob/2e404cfc3a4ebccda9e743edd39bd03732671b9e/contrib/RAPIDS/azure-ml-with-nvidia-rapids.ipynb), [Automated Machine Learning - Continuous retraining using Pipelines and Time-Series TabularDataset](https://github.com/Azure/MachineLearningNotebooks/blob/6f893ff0b40d3d6af94ac43867676a3d9df1fcbd/how-to-use-azureml/automated-machine-learning/continuous-retraining/auto-ml-continuous-retraining.ipynb), [Automated Machine Learning - Regression with Aml Compute](https://github.com/Azure/MachineLearningNotebooks/blob/6f893ff0b40d3d6af94ac43867676a3d9df1fcbd/how-to-use-azureml/automated-machine-learning/regression-explanation-featurization/auto-ml-regression-explanation-featurization.ipynb) and stuff like that)

Please give us the steps of the migration to use DockerConfiguration.

**Comment by vizhur** [comment]
just drop it from your code. that will be true for the remote execution and does not require any special handling

**Comment by urasandesu** [comment]
The warning has gone away and our notebooks run successfully as before! Thank you!!
