### ISSUE TITLE
Update code samples to match the latest version of the SDK (target becomes compute_target)

### ISSUE THREAD

**Issue by vladiliescu** [Azure/MachineLearningNotebooks#1427]
In the code samples, instead of `target=compute_target` it should say `compute_target=compute_target`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f44644d4-e8d2-1a82-1858-95abb5e4294c
* Version Independent ID: 2b538246-2460-1536-4e6c-ac77a25c67d6
* Content: [azureml.pipeline.core.PipelineParameter class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelineparameter?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineParameter.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineParameter.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by Di-Tez** [comment]
MSFT internal use: https://msdata.visualstudio.com/Vienna/_queries/edit/1135277/?triage=true

**Comment by shbijlan** [comment]
@vladiliescu Thank you for pointing out this issue. I will update here once the documentation is corrected.

**Comment by shbijlan** [comment]
The documentation bug has been resolved.
