### ISSUE TITLE
Error "AciDeploymentFailed" when trying to deploy a model

### ISSUE THREAD

**Issue by feliciasegui** [Azure/MachineLearningNotebooks#1432]
Hi! 
I am trying to deploy a image classification model using the model-register-and-deploy notebook in the MachineLearningNotebooks/how-to-use-azureml/deployment-folder but the deployment fails with the error code "AciDeploymentFailed" and it seems to stem from importing the open_image-function from fastai.vision, in the entry script, since the deployment succeeds when I erase that import line. I am having troubles getting around the problem as the open_image-function is needed to run the predict function. Here you see my entry script:

![image](https://user-images.githubusercontent.com/62569865/114678460-8797b680-9d0b-11eb-803b-a36440649bbe.png)

And this is how my environment parameter looks like before running Model.deploy()
![image](https://user-images.githubusercontent.com/62569865/114678679-c7f73480-9d0b-11eb-83e0-71bdb879046b.png)

I am quite new to these tools so just let me know if you have any tips or possible ways for me to proceed. 

Thanks in advance! 

Best regards Felicia

**Comment by shivanissambare** [comment]
Hi @feliciasegui  can you please add link to the notebook you are using, unfortunately I am not able to find it

If you are just getting started on Inference/Model Deployment on Azure Machine Learning, I highly recommend this notebook: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-to-cloud/model-register-and-deploy.ipynb

This documentation gives a pretty good overview : https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where?tabs=azcli

If you want a image classification example notebook: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/onnx/onnx-inference-mnist-deploy.ipynb

**Comment by shivanissambare** [comment]
closing this issue, feel free to re-open if you have more questions.
thank you!
