### ISSUE TITLE
Request to add example for instantiating Graph Class

### ISSUE THREAD

**Issue by jonchang03** [Azure/MachineLearningNotebooks#1435]
It's not immediately clear from the [docs](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.graph?view=azure-ml-py) how to instantiate the Graph Constructor. Namely, a GraphContext needs to be provided but it is not immediately clear how to create `azureml.pipeline.core._GraphContext` which seems to reference `_aeva_provider.py` which I am assuming is internal to Microsoft. It would be extremely helpful to add an example of how to properly create a pipeline run graph. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16543d05-1994-553f-c3af-ecfa90943fcc
* Version Independent ID: b34e60c8-36e6-7e06-cdf4-995cf85b3ec4
* Content: [azureml.pipeline.core.graph.Graph class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.graph?view=azure-ml-py&source=docs)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.graph.Graph.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.graph.Graph.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by Di-Tez** [comment]
MSFT internal use: https://msdata.visualstudio.com/Vienna/_queries/edit/1135213/?triage=true

**Comment by shbijlan** [comment]
@jonchang03 You should not need to instantiate a graph constructor. Could you please share your use case where you need to do this?
