### ISSUE TITLE
Automl classification-text-dnn example is failing with error "features have inconsistent row count."

### ISSUE THREAD

**Issue by dhangerkapil** [Azure/MachineLearningNotebooks#1441]
Hi,

Automl classification-text-dnn example (https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning/classification-text-dnn)  is failing with below error 

Encountered an internal AutoML error. Error Message/Code: features have inconsistent row count. Additional Info: DataTransformerInconsistentRowCountException:
	Message: features have inconsistent row count
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "TransformRuntime",
        "inner_error": {
            "code": "InvalidTransformData",
            "inner_error": {
                "code": "TransformDataShapeError",
                "inner_error": {
                    "code": "DataTransformerInconsistentRowCount"
                }
            }
        },
        "message": "features have inconsistent row count",
        "reference_code": "data_transformer.DataTransformer.transform"
    }
}

**Comment by kvijaykannan** [comment]
Thanks for raising this. Our engineering team is looking into this issue.

**Comment by rtanase** [comment]
issue has been fixed. closing.

**Comment by CESARDELATORRE** [comment]
Closing issue since it's been fixed.
