### ISSUE TITLE
AutoMLPipelineBuilder.get_many_models_train_steps - Is there a way to set the model name?

### ISSUE THREAD

**Issue by crisansou** [Azure/MachineLearningNotebooks#1442]
Hi,

I'm following the tutorial below and I managed to train many models at the same time. However the generated names are random and to know which is the related dataset I have to look at the tags. Is there a way to set a pattern for the model name based on the dataset?

For example:

![image](https://user-images.githubusercontent.com/29444086/115456739-e4a6d700-a1f9-11eb-81e7-6b2fed08a203.png)

Reference: 
- https://github.com/microsoft/solution-accelerator-many-models

Best regards,
Cristina

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 49399a7d-d4e8-370e-ce62-d60a6b64e412
* Version Independent ID: 782d8ba4-75dd-27c3-5a46-a921c3ead4bf
* Content: [azureml.contrib.automl.pipeline.steps.AutoMLPipelineBuilder class - Azure Machine Learning Python](https://docs.microsoft.com/pt-br/python/api/azureml-contrib-automl-pipeline-steps/azureml.contrib.automl.pipeline.steps.automlpipelinebuilder?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-automl-pipeline-steps/azureml.contrib.automl.pipeline.steps.AutoMLPipelineBuilder.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr.pt-BR/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-automl-pipeline-steps/azureml.contrib.automl.pipeline.steps.AutoMLPipelineBuilder.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by cartacioS** [comment]
Hi @crisansou - it is currently not possible to name these models, the main reason being certain restrictions around the length of name (capped at 255 characters) and hence would fail if the group pattern had multiple categories causing the name to exceed the character limitation. I will however, log your feedback to see if we can better surface the helpful grouping tags to make it easier to identify which models map to what data partition. 

Currently what you can identify s the key:value where key is the group column name, in your image this maps to 'brand:minute.maid'. You can use the filter on the registered models page to search for your desired models.
![image](https://user-images.githubusercontent.com/9436875/116282914-541c4980-a759-11eb-8278-bfea5089a64c.png)

**Comment by crisansou** [comment]
Hi @cartacioS,

Ok, thanks for the info!

Best regards,
Cristina

> Hi @crisansou - it is currently not possible to name these models, the main reason being certain restrictions around the length of name (capped at 255 characters) and hence would fail if the group pattern had multiple categories causing the name to exceed the character limitation. I will however, log your feedback to see if we can better surface the helpful grouping tags to make it easier to identify which models map to what data partition.
> 
> Currently what you can identify s the key:value where key is the group column name, in your image this maps to 'brand:minute.maid'. You can use the filter on the registered models page to search for your desired models.
> ![image](https://user-images.githubusercontent.com/9436875/116282914-541c4980-a759-11eb-8278-bfea5089a64c.png)
