### ISSUE TITLE
Document that ParallelRunConfig output_action needs 1 row per input

### ISSUE THREAD

**Issue by epa095** [Azure/MachineLearningNotebooks#1448]
Turns out that when you use a `ParallelRunConfig`  with `output_action="append_row",` then the output must be equal *or* greater length than the input. 
1: This should be documented in the [docstring](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.parallel_run_config.parallelrunconfig?view=azure-ml-py) for the "append_row" option. I only understood this when I read the documentation for the "summary_only" option, and there it reads like this is obvious for the "append_row" option. 
2: For the longest time I returned 2 rows per input-row, and there is no complaints about this. If you want to use the nr of rows returned as an indicator of succsess, then maybe you should (by default) complain if the nr of rows returned is larger than the nr of rows passed in?

**Comment by shivanissambare** [comment]
closing this issue, since document has been updated.
thanks!
