### ISSUE TITLE
azureml.core.scriptrunconfig should have a way to filter what gets uploaded

### ISSUE THREAD

**Issue by sausag3** [Azure/MachineLearningNotebooks#1450]
Locally I work on scripts inside a git repository. When I use "azureml.core.scriptrunconfig" it uploads not only my python files, but everything it finds, .git folders, any random files I just happen to have, etc, it would be great if at the very least it ignored the .git folders, but ideally have an inclusion and maybe an exclusion file filter so I don't need to waste time uploading files that aren't important.

**Comment by paulshealy1** [comment]
You can include either a .gitignore or .amlignore file in your directory to exclude files and directories. More information is [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-save-write-experiment-files#storage-limits-of-experiment-snapshots).
