### ISSUE TITLE
Private package add to environment issues

### ISSUE THREAD

**Issue by vla6** [Azure/MachineLearningNotebooks#1453]
This issue relates to this document: [(https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-private-python-packages](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-private-python-packages)

I have some private packages I'd like to add to an environment for experiment runs, PLUS be able to use on a VM.  I am using the "wheel file attach to workspace" option described in the document above.  It contains this code snippet:

```
whl_url = Environment.add_private_pip_wheel(workspace=ws,file_path = "my-custom.whl")
myenv = Environment(name="myenv")
conda_dep = CondaDependencies()
conda_dep.add_pip_package(whl_url)
myenv.python.conda_dependencies=conda_dep
```
I am having a lot of issues with the above.  I have an existing environment with a lot of other dependencies and I just want to update it.    

The first issue is the first line of code (Environment.add_private_pip_wheel...).  If you run this line of code more than  once, it fails (or becomes a noop it you set exist_ok=True).  At this point the only option seems to be making another .whl file, with a new name (in practice updating the version in a setup.py file or some such) and redoing the whole thing.    **Is there any way to check if that private pip wheel already exists in the workspace?  Or get the URL if it was already added?**  Having the above issue makes it very difficult to update other aspects of the environment then also update the private package.

FYI, because I am updating an existing environment, I replace the other lines of code with:
```
conda_dep = myeng.python.conda_dependencies
conda_dep.add_pip_package(whl_url)
```
The above seems OK, as long as I don't change anything or run the add_private_pip_wheel() more than once.

The second issue is related - how can I get that workspace URL so I can install the .whl file on a VM?  If I just create a VM within the workspace, shouldn't I be able to find and use that .whl file?  There seems to be no way to retrieve the URL to install it again.  The document for [add_private_pip_wheel](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py#add-private-pip-wheel-workspace--file-path--exist-ok-false-) doesn't say anything about retrieving the whl or getting the URL.  It also seems there's no way to delete this file if I messed up somehow.

**Comment by vla6** [comment]
If I want to use that same .whl file with more than one environment, and I don't have access to the original .whl file, and I do:

`
Environment.add_private_pip_wheel(workspace=ws, file_path = 'name_of_the_file.whl', exist_ok=True)
`

This fails (because the file doesn't exist).  But I am just looking to get the URL so I can assign it as a dependency to the environment.  

How can I use the same .whl file as a dependency in multiple environments?   I guess if I know the name of the .whl file maybe I can assume the base URL is the same and assume the URL looks like:

> https://DEFAULT_FILESTORE_NAME.blob.core.windows.net/azureml/Environment/azureml-private-packages/WHEEL_FILE_NAME.whl

However, if this pattern ever changed I'd be in trouble, and I have to query the default datastore.  I guess I could also create an empty or dummy .whl file (if I am 100% sure it exists) and use that Environment.add_private_pip_wheel(...) command

**Comment by vla6** [comment]
The other thing is on a compute instance (VM) which isn't using a registered environment, how do I install from the whl file?  Even if I know the URL, this doesn't work:

`%pip install https://DEFAULT_FILESTORE_NAME.blob.core.windows.net/azureml/Environment/azureml-private-packages/WHEEL_FILE_NAME.whl`

**Comment by vizhur** [comment]
AzureML materializes conda environment you specified in the docker container where your experimentation will happen. You can specify wheel from any public location. So if blob has public access there won't be any issues for pip to pull from there. 
If wheel is from the storage associated with your AzureML workspace we are be able to authorize pip to pull the dependency.
Any updates to the wheel should result in a version bump for reproducibility reason, as usually customers don't want previous experiments start to fail or image rebuild.

**Comment by vla6** [comment]
> AzureML materializes conda environment you specified in the docker container where your experimentation will happen. You can specify wheel from any public location. So if blob has public access there won't be any issues for pip to pull from there.
> If wheel is from the storage associated with your AzureML workspace we are be able to authorize pip to pull the dependency.
> Any updates to the wheel should result in a version bump for reproducibility reason, as usually customers don't want previous experiments start to fail or image rebuild.

I can understand not allowing updates to the wheel, but how can I obtain a reference to a wheel that's already there for a new environment?  I need the URL that was originally used when writing the wheel - I have to document this somewhere?   Also, how can I download this from blob storage to a compute instance?  I assume that having the .whl saved in the workspace means it should be available to environments/resources across the workspace?

**Comment by vizhur** [comment]
whl_url = Environment.add_private_pip_wheel(workspace=ws,file_path = "my-custom.whl") returns blob url where it is published. 

Register environment and use it for your experimentation, so you can reference it by name or retrieve an instance.

registered_env = myenv.register(ws)

URL where the wheel is stored and internal mechanics are not documented and not intended to be used other than documented API or samples.

Private wheel is not a generic way for custom wheels but rather a quick turn around for a user to add something from local to remote environment. For more generic solution please consider to use find links or private index or any other supported by pip python feeds

**Comment by vla6** [comment]
If I want to re-create an environment, or update it, I **must** have access to the original .whl file, but then this file isn’t used.  You can call Environment.add_private_pip_wheel(workspace=ws,file_path = "my-custom.whl", exist_ok = True), and then this is a noop and fine.  But noop or no, if file_path doesn’t point to a file the command will fail. Why should you have to have access to that .whl file on a local compute instance, when it’s already stored on the default blob storage?  Why couldn’t I use this command for any environment without the file?  You can’t tell whether the file exists before you call the function, so using a dummy or empty file is risky.

**Comment by vizhur** [comment]
for the private packages the workflow is the following:
whl_url = Environment.add_private_pip_wheel(workspace=ws, file_path = 'name_of_the_file.whl', exist_ok=True) - puts .whl file into a bloc storage associated with user's workspace
conda_dep.add_pip_package(whl_url) adds blob URI to the pip section of the environment

Storage is usually secure and requires auth. AzureML services can authorize by generating SAS URI service side so you can proceed with the cloud build.

You cannot use that URI for other environments, neither locally or on a compute instance. It is possible to make it public by a user if there are no security concerns. Alternatively generate SAS URI to the wheel in the storage and use it instead. That also could be done programmatically between two calls above.

If the solution is not scalable please consider to use own private feeds or Azure DevOps feeds that are supported by AzureML services.
