### ISSUE TITLE
Why are names of algorithm duplicated in autoML RunDetails? Is there any place to set a seed or random_state?

### ISSUE THREAD

**Issue by tsuting** [Azure/MachineLearningNotebooks#1455]
Hello,

My goal to run forecasting by autoML. I have two questions.
- Why did I find the same combination of scaler and algorithm but with different results? 
![image](https://user-images.githubusercontent.com/67579322/116037026-7c953c80-a6a2-11eb-9efa-4b75a659bd18.png)
(Updated) Answer: I know they are with different hyperparameters. I guess this is the reason. But where can I find hyperparameter approaches which made hyperparameters different?

- Is there any place that I could set a seed or `random_state` to get the same result of an experiment every time?

**Comment by cartacioS** [comment]
Hi @tsuting - Your updated answer is correct. You're seeing the same model name, but behind the scenes they have different hyperparameters. You have two options, the first is to follow the code steps mentioned
[here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-features#scaling-and-normalization). You can also view the models in the UI and on the model details page the tags should show model weights of interest. There is a better UI experience for viewing these details under development. However the documentation code I shared should meet your requirements. 

Unfortunately, there is not a way to ensure you get the same result of an experiment every time.

**Comment by tsuting** [comment]
@cartacioS  Thanks for the reply. 
For my first question, I was wondering how I could get the approaches' names of hyperparameter tuning instead of results from either UI or python? Could you please elaborate more on the approaches of hyperparameters tuning on autoML?

**Comment by cartacioS** [comment]
@tsuting Sorry, to clarify the documentation I shared above, sharing again below, has a code snippet prefaced by 'To get more details, use this helper function' and that will give you the hyperparameter names _and_ values. 

 https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-features#scaling-and-normalization
 
 We also have a published Microsoft research paper here: https://www.microsoft.com/en-us/research/uploads/prod/2018/09/Probabilistic-Matrix-FactorAML.pdf
 
 Should you be looking for something different, please let me know.
