### ISSUE TITLE
AutoML Forecasting: Classical Time Series Models and Prophet Always Blocked Despite AutoMLConfig Setting

### ISSUE THREAD

**Issue by petrenkw** [Azure/MachineLearningNotebooks#1456]
Hi,

I'm passing in the [classical time series models](https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.shared.constants.modelcategories?view=azure-ml-py#classical-timeseries-models-----naive----autoarima----seasonalaverage----seasonalnaive----exponentialsmoothing----arimax----average--) and prophet into the allowed_models parameter in AutoMLConfig using an AmlCompute cluster as my compute target. 

My understanding, per [documentation on remote compute](https://docs.microsoft.com/en-us/azure/machine-learning/concept-automated-ml#feature-availability) , is that the above referenced models should be available when using a remote compute resource such as AmlCompute. However, once I run the experiment and check its configuration settings in my workspace I see that all of those models are listed as blocked algorithms.

Below is the code I'm using to create the remote cluster and configuration settings:

```python

amlcompute_cluster_name = "ci{}".format(ws._workspace_id)[:10]

try:
    compute_target = ComputeTarget(workspace=ws, name=amlcompute_cluster_name)
    print('Found existing cluster, use it.')
except ComputeTargetException:
    compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_DS12_V2',max_nodes=6)
    compute_target = ComputeTarget.create(ws, amlcompute_cluster_name, compute_config)

compute_target.wait_for_completion(show_output=True)


target_column_name = 'revenue'
time_column_name = 'month_date'
time_series_id_column_names = 'partner'
forecast_horizon = 3

ts_models = ['Naive', 'AutoArima', 'SeasonalAverage', 'SeasonalNaive', 'ExponentialSmoothing', 'Arimax', 'Average','Prophet','RandomForest']

forecasting_parameters = ForecastingParameters(
    time_column_name=time_column_name,
    time_series_id_column_names = time_series_id_column_names,
    forecast_horizon=forecast_horizon,
    target_lags='auto', # use heuristic based lag setting
    freq='MS' # Set the forecast frequency to be MonthBegin per pandas offset documentation
)

automl_config = AutoMLConfig(task='forecasting',
                             featurization='off',
                             primary_metric='normalized_root_mean_squared_error',
                             allowed_models = ts_models,                             
                             experiment_timeout_hours=0.3,
                             training_data=train,
                             label_column_name=target_column_name,
                             enable_early_stopping=True,
                             n_cross_validations=3,
                             compute_target=compute_target,
                             max_concurrent_iterations=4,
                             max_cores_per_iteration=-1,
                             verbosity=logging.INFO,
                             forecasting_parameters=forecasting_parameters)

```

After submitting a run with this configuration, I see that all of the models in my allowed_models list are blocked except for RandomForest as shown in the attachment
![AutoML Configuration Settings](https://user-images.githubusercontent.com/40646692/116158875-1f9a8600-a6a4-11eb-8850-c347da6d6d41.png)

Is this a bug or am I missing something? 

As a secondary question, will Databricks soon be supported outside of local mode only so that we can leverage databricks compute with these forecasting models? Per [compute target documentation](https://docs.microsoft.com/en-us/azure/machine-learning/concept-compute-target#train), Databricks appears compatibile with AutoML through "local" mode only which seems to imply that it will not be able to support most time series models.

Thanks!

**Comment by cartacioS** [comment]
Hi @petrenkw - some forecasting models are automatically blocked when lags and/or rolling windows are enabled. If you remove this line from your settings 'target_lags='auto', # use heuristic based lag setting' you should see ARIMA and Prophet show up in your runs.

This restriction is something we are working on and will deliver on soon. Hope that helped!

**Comment by petrenkw** [comment]
Thanks @cartacioS, that worked. For clarification, does the target_lag parameter in the ForecastingParameters class default to 1 or None? The [documentation](https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.forecasting_parameters.forecastingparameters?view=azure-ml-py) seems a bit conflicting.

The constructor shows the following in the documentation which seems to imply no target lags:
```python
ForecastingParameters(time_column_name: typing.Union[str, NoneType] = None, forecast_horizon: typing.Union[str, int] = 1, time_series_id_column_names: typing.Union[str, typing.List[str], NoneType] = None, group_column_names: typing.Union[str, typing.List[str], NoneType] = None, target_lags: typing.Union[typing.List[int], int, str, NoneType] = None, feature_lags: typing.Union[str, NoneType] = None, target_rolling_window_size: typing.Union[str, int, NoneType] = None, holiday_country: typing.Union[str, NoneType] = None, seasonality: typing.Union[str, int, NoneType] = 'auto', country_or_region_for_holidays: typing.Union[str, NoneType] = None, use_stl: typing.Union[str, NoneType] = None, short_series_handling: bool = True, short_series_handling_configuration: typing.Union[str, NoneType] = 'auto', freq: typing.Union[str, NoneType] = None, target_aggregation_function: typing.Union[str, NoneType] = None, validate_parameters: typing.Union[bool, NoneType] = True, **kwargs: typing.Any)
```

but the parameters details mention a target_lag default of 1:
![fp_img](https://user-images.githubusercontent.com/40646692/116324269-b20a5a80-a774-11eb-8e83-457c5209e21d.PNG)

**Comment by cartacioS** [comment]
Hi @petrenkw - great observation. The SDK doc details are outdated and I've created a task to go ahead an update that.

By default, target_lags are off. There are a few steps we take when you set target_lags to 'auto' :
1) Estimate the period, on which we consider lags, in our case it is the next date frequency granularity i. e. if frequency is daily, it will be a week (7), if it is a week, it will be month (4). That values multiplied by two is the largest possible values of lags/rolling windows (14 and 8 respectively for these examples).

2) Decompose the series to seasonal, trend and residual components and remove seasonal part. 

3) Estimate the PACF - Partial Auto Correlation Function on the on the data from (2) and search for points, where the auto correlation is significant i. e. its absolute value is more then 1.96/square_root(maximal lag value), which correspond to significance of 95%.

4) If all points are significant, we consider it being strong seasonality and do not create look back features.

5) We scan the PACF values from the beginning and the last value where the auto correlation is significant will become a lag. If it is only the 0-th element (value correlate with itself, which is merely always true), the lag will be 0 and we will not use lagging features.

6) For rolling window size will be the last value where the PACF is more then the significance threshold.

We refer to lags and rolling windows as look back features.

**Comment by petrenkw** [comment]
Thanks for the explanation! great to know the methodology. i'll close this one out. appreciate the help @cartacioS
