### ISSUE TITLE
Datastore get_default method requests non-existing attribute

### ISSUE THREAD

**Issue by Uasmi** [Azure/MachineLearningNotebooks#146]
AttributeError: 'GenericResource' object has no attribute 'workspaceid'
We had to create a hack to make datastore work: ws._workspace_autorest_object.workspaceid = ws._workspace_autorest_object.id

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: abb6da6e-eb0a-616d-5c2f-3dd3bb659460
* Version Independent ID: 3196a898-00f8-bf48-e804-6249c2f3748d
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/ru-ru/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#register-azure-blob-container-workspace--datastore-name--container-name--account-name--sas-token-none--account-key-none--protocol-none--endpoint-none--overwrite-false--create-if-not-exists-false-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by filipkrzeminski** [comment]
Also ran into this issue when getting a workspace using ServicePrincipalAuthentication.

import azureml.core
print(azureml.core.VERSION) #1.0.21

from azureml.core.authentication import ServicePrincipalAuthentication
auth = ServicePrincipalAuthentication('****', '****', '****')
from azureml.core.workspace import Workspace
ws = Workspace.get('****', subscription_id='****', auth=auth)

# the following code works
print('Workspace name: ' + ws.name, 
      'Azure region: ' + ws.location, 
      'Subscription id: ' + ws.subscription_id, 
      'Resource group: ' + ws.resource_group, sep='\n')

# but this code throws (note that it does work if I get workspace from config 'Workspace.from_config()' in my azure notebooks)
from azureml.core import Datastore
datastores = ws.datastores

  File "...\lib\site-packages\azureml\core\workspace.py", line 567, in datastores
    return {datastore.name: datastore for datastore in _DatastoreClient.list(self)}
  File "...\lib\site-packages\azureml\data\datastore_client.py", line 246, in list
    dss, ct = _DatastoreClient._list(workspace, ct, 100)
  File "...\lib\site-packages\azureml\data\datastore_client.py", line 388, in _list
    client = _DatastoreClient._get_client(ws, auth, host)
  File "...\lib\site-packages\azureml\data\datastore_client.py", line 419, in _get_client
    ws._subscription_id, ws._resource_group, ws._workspace_name), ws._workspace_id)
  File "...\lib\site-packages\azureml\core\workspace.py", line 668, in _workspace_id
    return self._workspace_autorest_object.workspaceid
AttributeError: 'GenericResource' object has no attribute 'workspaceid'

**Comment by rongduan-zhu** [comment]
When getting the workspace, `Workspace.get('', subscription_id='****', resource_group='***', auth=auth)` please make sure you specify the __`resource_group`__ argument.
