### ISSUE TITLE
OutputFileDatasetConfig or PipelineData?

### ISSUE THREAD

**Issue by JackCaster** [Azure/MachineLearningNotebooks#1460]
What is the recommended way of passing data across pipeline's steps?

In the [official doc](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-machine-learning-pipelines#configure-data-with-dataset-and-outputfiledatasetconfig-objects) `OutputFileDatasetConfig` seems the way to go. Same for the official `how-to-use-azureml` example notebook [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb). On the other hand, the tutorial uses `PipelineData` only ([here](https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/machine-learning-pipelines-advanced/tutorial-pipeline-batch-scoring-classification.ipynb) and [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb)). 

Would you be able to point me into the right direction?

**Comment by ynpandey** [comment]
The recommended way is to use `OutputFileDatasetConfig` as shown in `how-to-use-azureml` Datasets tutorial notebook [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb).

**Comment by JackCaster** [comment]
Thanks. Could the tutorial be updated to use `OutputFileDatasetConfig`?

**Comment by ynpandey** [comment]
Yes, the tutorial is being updated to use `OutputFileDatasetConfig`.

**Comment by anderl80** [comment]
Will `PipelineData` be deprecated in favor of `OutputFileDatasetConfig`? Could you provide more background why `OutputFileDatasetConfig` is preferred?
