### ISSUE TITLE
Missing package in documentation

### ISSUE THREAD

**Issue by asears** [Azure/MachineLearningNotebooks#1461]
https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes shows a library azureml-contrib-mir however no documentation appears to exist for this library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by shivanissambare** [comment]
`azureml-contrib-mir` is our internal package, which ideally should not have been documented in the release notes.

we will work with our documentation team to remove it's reference

please take a look at managed inference offering here : https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-managed-online-endpoints

**Comment by shivanissambare** [comment]
we have a PR out to remove `azureml-contrib-mir` references
if you have anymore question, please feel free to reopen the issue.

thank you!
