### ISSUE TITLE
AutoMLPipelineBuilder.get_many_models_train_steps - Method shows the message: "'enabled' is deprecated. Please use the azureml.core.runconfig.DockerConfiguration object with the 'use_docker' param instead."

### ISSUE THREAD

**Issue by crisansou** [Azure/MachineLearningNotebooks#1462]
Hi,

When executing the method, the warning below was displayed. Can you guys explain how to use the 'use_docker' parameter, please?

![image](https://user-images.githubusercontent.com/29444086/117366629-70c22b00-ae97-11eb-83fc-900e0adcdcfe.png)

Warning: 'enabled' is deprecated. Please use the azureml.core.runconfig.DockerConfiguration object with the 'use_docker' param instead.

Reference:

https://github.com/microsoft/solution-accelerator-many-models

Best regards,
Cristina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49399a7d-d4e8-370e-ce62-d60a6b64e412
* Version Independent ID: 782d8ba4-75dd-27c3-5a46-a921c3ead4bf
* Content: [azureml.contrib.automl.pipeline.steps.AutoMLPipelineBuilder class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-automl-pipeline-steps/azureml.contrib.automl.pipeline.steps.automlpipelinebuilder?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-automl-pipeline-steps/azureml.contrib.automl.pipeline.steps.AutoMLPipelineBuilder.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-automl-pipeline-steps/azureml.contrib.automl.pipeline.steps.AutoMLPipelineBuilder.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by crisansou** [comment]
Hi,

Setting the environment as shown in the example below, the message was no longer displayed. However, I don't know if it's the best practice.

from azureml.core.environment import Environment

env = Environment.get(workspace=ws, name="AzureML-Tutorial")
myenv = env.clone("automl_env")

train_steps = AutoMLPipelineBuilder.get_many_models_train_steps(experiment=experiment,
automl_settings=automl_settings,
train_data=dataset_input,
compute_target=compute_target,
partition_column_names=partition_column_names,
node_count=1,
process_count_per_node=2,
run_invocation_timeout=3700,
train_env=myenv)

Best regards,
Cristina

**Comment by cartacioS** [comment]
Hi @crisansou - you can safely ignore this warning, everything works correctly even if it gets thrown. This parameter is being set internally by our code so they can't really do anything about it. However it was our understanding that this issue was fixed sometime back. Can you let me know what SDK version you're using?

**Comment by crisansou** [comment]
Hi @cartacioS ,

Got it, thank you for the info! I'm using **1.27.0** version and the environment at compute instance is **Python 3.6 - AzureML**.

Best regards,
Cristina

> Hi @crisansou - you can safely ignore this warning, everything works correctly even if it gets thrown. This parameter is being set internally by our code so there's not really anything to do about it. However it was our understanding that this issue was fixed sometime back. Can you let me know what SDK version you're using?
