### ISSUE TITLE
Parent run id for pipelines 

### ISSUE THREAD

**Issue by JackCaster** [Azure/MachineLearningNotebooks#1465]
[Here](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline.pipeline?view=azure-ml-py#remarks) it says that we can supply a run id to the pipeline but this example is not clear:
```
from azureml.pipeline.core import Pipeline

pipeline = Pipeline(workspace=ws, steps=steps)
pipeline_run = experiment.submit(pipeline,
                                    continue_on_step_failure=True,
                                    regenerate_outputs=True,
                                    pipeline_parameters={"param1": "value1"},
                                    parent_run_id="<run_id>")
```
What is `"<run_id>"`? Is this a placeholder that is automatically filled in? I did notice that a pipeline with 1 step results in a run number that is not continuous (i.e., 1, 3, 5...) and I cannot understand why. Perhaps, `parent_run_id="<run_id>"` would solve this issue but I do not know how to use it. Would you be able to help?

![image](https://user-images.githubusercontent.com/18400141/117672645-54313600-b1aa-11eb-806c-f411262243fe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e29a33-0622-294e-4558-ca898e9ea5a3
* Version Independent ID: e3e3dfc0-3f51-a15e-309e-81113ef49bdb
* Content: [azureml.pipeline.core.pipeline.Pipeline class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline.pipeline?view=azure-ml-py#remarks)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
@JackCaster the run ID is not continuous due to step runs also having a run ID. You can provide a run ID in place of <runID>, which would refer to the pipeline and not step runs.
