### ISSUE TITLE
00.configuration.ipynb

### ISSUE THREAD

**Issue by mddiallo** [Azure/MachineLearningNotebooks#147]
Hello,

the following link is dead.
https://github.com/Azure/MachineLearningNotebooks/blob/master/00.configuration.ipynb

**Comment by yodobrin** [comment]
This is the right path:
https://github.com/Azure/MachineLearningNotebooks/blob/master/configuration.ipynb

**Comment by rastala** [comment]
Thank you! 

@mddiallo Where did you see the broken link?

**Comment by Smarker** [comment]
@rastala The broken link is where you reference `train in notebook` at the bottom in the **Next Steps** section.
