### ISSUE TITLE
TypeError in DatabricksStep Class - permit_cluster_restart

### ISSUE THREAD

**Issue by Mystorius** [Azure/MachineLearningNotebooks#1476]
I am using SKD Version 1.28.0

I want to use Databricks as attached compute resource in my pipeline. I am using your DatabricksStep Class. I am using your [example](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-use-databricks-as-compute-target.ipynb) N0. 6 (at the bottom of the notebook)

Your current documentation states that permit_cluster_restart=True should be used. This is also indicated by the error stack_trace` Failed to submit job because of error: the job needs access blob storage account, while it does not allowed to restart the cluster after editing cluster spark config,you may need open the switch of parameter permit_cluster_restart`

However I cant add the argument as I receive the following error:
TypeError: __init__() got an unexpected keyword argument 'permit_cluster_restart'

How can I used No. 6 - Running a Python script in Databricks that currently is in local computer with existing cluster - with attached Blob Storage if permit_cluster_restart is required but not implemented in the the DatabricksStep class?

Thank you in advance.

**Comment by irwang** [comment]
Hi Mystorius, can you try to upgrade pipeline version again by
_pip install azureml-pipeline-steps==1.28.0_

btw, are you using an old compute instance or a new provisioned one?

**Comment by irwang** [comment]
@Mystorius please let me know whether the problem is get resolved?

**Comment by HakzA** [comment]
Anybody have more information on this issue?

I'm getting the error:

`TypeError: __init__() got an unexpected keyword argument 'permit_cluster_restart'`

When running the code:

`step_1 = DatabricksStep(
                                    name="calculate_turnover",
                                    inputs=[input_data],
                                    num_workers=1,
                                    python_script_name=python_script_name,
                                    source_directory=source_directory,
                                    run_name='DB_Python_Local_demo',
                                    compute_target=databricks_compute,
                                    allow_reuse=True
                                )`

I'm not even adding the `permit_cluster_restart  `as a parameter.

**Comment by irwang** [comment]
Can you show me the azureml sdk versions you installed?

**Comment by HakzA** [comment]
I'm running a docker container with the following versions in my environment file:

`- azureml-sdk==1.31.0
- azureml-datadrift==1.21.0
- azureml-telemetry==1.23.0
- azure-keyvault-secrets==4.2.0
- azureml-pipeline-steps==1.28.0`

However I'm still getting the typeerror after changing the versions to:
`- azureml-sdk==1.34.0
- azureml-datadrift==1.21.0
- azureml-telemetry==1.23.0
- azure-keyvault-secrets==4.2.0
- azureml-pipeline-steps==1.34.0`
