### ISSUE TITLE
Run number high in newly created experiment

### ISSUE THREAD

**Issue by JackCaster** [Azure/MachineLearningNotebooks#1492]
I have created a pipeline and executed it in a new experiment (no runs were executed in here). I noticed that the run number starts at 1 billion and something, while it should starts at 1. Is this a bug? Can this be controlled by the pipeline script? I am wondering if I unintentionally made an error somewhere. Would you be able to help?

![Untitled](https://user-images.githubusercontent.com/18400141/119799079-091e5f00-bedc-11eb-869b-e61d5dead9dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
* Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
* Content: [azureml.core.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py#azureml_core_Experiment_submit)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by swinner95** [comment]
Hello @JackCaster, we are currently working on a fix to show the old run number experience.

**Comment by JackCaster** [comment]
Thanks, I see now the run ID is displayed correctly.
