### ISSUE TITLE
01.auto-ml-classification using deprecated hyperparameters 

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#150]
Running the example code and got this error:

`WARNING:root:Parameter 'max_time_sec' will be deprecated. Use 'iteration_timeout_minutes'`

Where is the documentation on `iteration_timeout_minutes`?

**Comment by chaoqian** [comment]
Hi, sorry for any inconvenience.

The latest document is here: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-auto-train?branch=pr-en-us-58158 

Please feel free to let us know if anything more confusing.

**Comment by ktebbe** [comment]
Thank you for sending the link - however, those examples still have `max_time_sec`. The documentation is there for the newer parameter, I just brought it up so it can be corrected.

**Comment by chaoqian** [comment]
Good catch, we will follow up with document team for correction.
