### ISSUE TITLE
Error in azureml.train.widgets (in 01.auto-ml-classification)

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#151]
In the Explore the Results section of the example notebook, running the cell with `from azureml.train.widgets import RunDetails` gives the following error:

`ImportError: cannot import name 'batchai_payload_template'`

Any idea why this is the case? All other libraries called earlier in the notebook imported successfully.

**Comment by yuanzhuangyuanzhuang** [comment]
This one has already been changed to azureml.widgets a while ago. Could you install the latest SDK and try the notebook [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification/auto-ml-classification.ipynb) to see whether it works?
