### ISSUE TITLE
please add current python version constraints

### ISSUE THREAD

**Issue by evansimmons** [Azure/MachineLearningNotebooks#1511]
this page should reflect the current version of python the SDK works with. been fighting python 3.9 for a couple hours only to realize my version is not supported.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by harneetvirk** [comment]
The supported versions of python for SDK is listed on pypi index page as follow: Requires: Python >=3.6, <3.9. 

Link to the pypi index:  https://pypi.org/project/azureml-core/
