### ISSUE TITLE
Cannot add pipeline to endpoint

### ISSUE THREAD

**Issue by JackCaster** [Azure/MachineLearningNotebooks#1513]
I have already a pipeline endpoint to which I want to add a new version of a pipeline.
I used:
```python
pipeline_endpoint = PipelineEndpoint.get(ws, name=endpoint_name)
pipeline_endpoint.add_default(new_pipeline)
```
but got
```python
Exception has occurred: AttributeError
'Pipeline' object has no attribute 'id'
```
What does it mean? The new pipeline does not, in fact, have an `id` attribute, but I am not sure what to do about it. In the doc there is no mention to this requirement.

The only way I can get an `id` is if I publish the pipeline and then add it.
```python
published_pipeline = pipeline.publish(
        name=...,
        description=...,
    )
```
but [here](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.pipelineendpoint?view=azure-ml-py#publish-workspace--name--description--pipeline---workflow-provider-none---service-endpoint-none-) it says that the endpoint can contain either published or unpublished pipelines. This is true, because I can add an unpublished pipeline to the endpoint, but then I cannot add a new version if that new pipeline is not published. I am a bit confused.

Would you be able to help?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f506755-3573-985e-46e4-0554b8652214
* Version Independent ID: 340f468f-ae38-70f8-267f-abbc7294ccdd
* Content: [azureml.pipeline.core.pipeline_endpoint.PipelineEndpoint class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.pipelineendpoint?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.PipelineEndpoint.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.PipelineEndpoint.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by JackCaster** [comment]
I was made aware that `add` and `add_default` can only accept pipelines of type `PublishedPipeline`. Perhaps we could make the doc more clear?

**Comment by shbijlan** [comment]
This is correct. Please refer to reference documentation for add and add_default methods for PipelineEndpoint. https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_endpoint.pipelineendpoint?view=azure-ml-py#add-pipeline-
