### ISSUE TITLE
AzureML Pipelines: Expected a StepRun object but received <class 'azureml.core.run.Run'> instead.

### ISSUE THREAD

**Issue by afogarty85** [Azure/MachineLearningNotebooks#1517]
I am running a lightly edited version of this pipeline example: https://github.com/Azure/MachineLearningNotebooks/blob/8f7717014b7e9b431c11857956982f0f718eb362/how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/nyc-taxi-data-regression-model-building.ipynb

and it is yielding me this error (or warning): `Expected a StepRun object but received <class 'azureml.core.run.Run'> instead.`

I am also getting this same warning in other pipelines I make and I cannot figure out what is causing it.

Here is a slightly reduced MWE for (hopefully) clarity:

```
from azureml.core import Workspace, Datastore, Dataset, Experiment
from azureml.core.authentication import ServicePrincipalAuthentication
from azureml.core.runconfig import RunConfiguration, DEFAULT_CPU_IMAGE
from azureml.core.conda_dependencies import CondaDependencies
from azureml.core.compute import ComputeTarget, AmlCompute
from azureml.core.compute_target import ComputeTargetException
from azureml.data import OutputFileDatasetConfig
from azureml.pipeline.steps import PythonScriptStep
from azureml.pipeline.core import Pipeline

import os

# environment data
from dotenv import load_dotenv  # pip install python-dotenv
load_dotenv('.env') # load .env file with sp info
```

```
# instantiate the service principal
sp = ServicePrincipalAuthentication(tenant_id=os.environ['AML_TENANT_ID'],
                                    service_principal_id=os.environ['AML_PRINCIPAL_ID'],
                                    service_principal_password=os.environ['AML_PRINCIPAL_PASS'])
```

```
# instantiate a workspace
ws = Workspace(subscription_id = "redacted",
               resource_group = "redacted",
               auth=sp,  # use service principal auth
               workspace_name = "redacted")

print("Found workspace {} at location {}".format(ws.name, ws.location))
```

```
# pipeline step 1
step1 = PythonScriptStep(
    name="generate_data",
    script_name="scripts/mwe.py",
    arguments=["--save", 'hello world'],
    runconfig=RunConfiguration(),
    compute_target='retry2',
    allow_reuse=True
)
```

```
%%writefile scripts/mwe.py

# load packages
import os
from azureml.core import Run
import argparse
import pandas as pd

print('hello world')
```

```
# build the pipeline
pipeline1 = Pipeline(workspace=ws, steps=[step1])
# validate the pipeline
pipeline1.validate()
# submit a pipeline run
pipeline_run1 = Experiment(ws, 'mwe').submit(pipeline1)
# run and wait for completion to check its results
pipeline_run1.wait_for_completion(show_output=True)

```

```
Expected a StepRun object but received <class 'azureml.core.run.Run'> instead.
This usually indicates a package conflict with one of the dependencies of azureml-core or azureml-pipeline-core.
Please check for package conflicts in your python environment
```

**Comment by shbijlan** [comment]
@afogarty85 can you share the version of SDK you are using?

**Comment by afogarty85** [comment]
```
import azureml
print(azureml.core.__version__)
1.31.0
```

**Comment by shbijlan** [comment]
@afogarty85, I'm unable to reproduce the error you are seeing. Is the pipeline running despite the error/warning?

**Comment by afogarty85** [comment]
It is running/working anyways and indeed -- on a different workspace, I too cannot reproduce it. I am not sure why it is a symptom of the one I am on.

**Comment by shbijlan** [comment]
I am opening a bug for investigation and will update you when I have a response.

**Comment by rudizhou428** [comment]
I am also running into this issue with code that was working previously. Had a weekly pipeline scheduled to run at the start of every Monday. It usually took around a couple of minutes  to finish but looking back at some logs it seems like after June 13  runs were taking 100+ hours and most timed out. I tried to manually run the pipeline and hit the exact same issue with Expecting StepRun object, not sure if there was some sort of update around the middle of June to the SDK?

**Comment by shbijlan** [comment]
I'm sharing the investigation from engineering below. Since this is expected behavior, we will not be fixing it. Hope this helps. 

This bug is activated if the user has a package version conflict in their local python environment, the PipelineRun.wait_for_completion() method may fail with an error 'Unexpected keyword argument timeout_seconds'. This is because the run rehydration fails and we receive a run object with the wrong type, which doesn't have this argument.
