### ISSUE TITLE
Move (delete) data in the storage

### ISSUE THREAD

**Issue by JackCaster** [Azure/MachineLearningNotebooks#1519]
I have a ML script that performs a prediction on the data that have been uploaded to the storage. The ML script uses `Datastore` to read the data from the storage account. After the prediction is done, I would like to move the already processed data to another location or delete the data altogether.  How can I do that programmatically (e.g., using the azureml Python SDK)? I can do it via the Microsoft Azure Storage Explorer, but I would like to have an automatic process in place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72d4eb-b5c9-c98d-3305-be3c00e937a2
* Version Independent ID: 5576d10f-9dad-b5cd-7032-07ce54f17b68
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by ynpandey** [comment]
The recommended way to delete intermediate pipeline data is to use a dedicated storage account for storing transient data. Set up a datastore to point to that storage account for intermediate data and directly delete that data. To automate this, you can set up Azure lifecycle management policy to delete the data 2-6 months after the data was created. Long term data can be stored in a different storage account.

**Comment by SturgeonMi** [comment]
Hi, ADF pipeline can be set up to move data to another storage automatically, please find more details here: https://docs.microsoft.com/en-us/azure/data-factory/solution-template-move-files
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-data-ingest-adf
