### ISSUE TITLE
ModuleNotFoundError in energy-demand and orange-juice forecasting examples

### ISSUE THREAD

**Issue by andreaskopp** [Azure/MachineLearningNotebooks#152]
Hi all,
I am using Azure Notebooks (AML SDK 1.0.2) to test above AML workbooks.
In both cases, the AML cells (local_run = experiment.submit(automl_config, show_output=True)) return:
ModuleNotFoundError: No module named 'ftk'

Thanks for any hints!
[amlerror.txt](https://github.com/Azure/MachineLearningNotebooks/files/2712367/amlerror.txt)

**Comment by yuanzhuangyuanzhuang** [comment]
You can try to install ftk by in your notebook by following either of the advice describing [here](https://social.technet.microsoft.com/Forums/en-US/ba58c690-3571-42e9-9030-4056d8735006/azure-auto-ml-forecast-no-module-named-ftk?forum=AzureMachineLearningService). If you are using the second advice, you need to install the dependencies for ftk [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/automl_env.yml) as well.

**Comment by andreaskopp** [comment]
Thanks a lot for your kind reply! 
Since I am not an expert, could you explain the necessary steps a bit more in detail for the Azure Notebook environment?

**Comment by yuanzhuangyuanzhuang** [comment]
1. Create a new cell in your Azure notebook.
2. Running the followings command in your Azure notebook cells.

> !pip install dill pyodbc statsmodels numexpr keras "distributed>=1.21.5,<1.24"
> !pip install https://azuremlpackages.blob.core.windows.net/forecasting/azuremlftk-0.1.18323.5a1-py3-none-any.whl

After these two steps, you should be good to go now.

**Comment by andreaskopp** [comment]
Thank you so much!

**Comment by skasturi** [comment]
@andreaskopp , Thank you. We also removed the dependency on azuremlftk in the recent releases. You wouldn't need to install this anymore. Please contact us in case you face any more issues.

@rastala  Please close this.
