### ISSUE TITLE
Add data updated parameter to PublishedPipeline and Schedule

### ISSUE THREAD

**Issue by JCZuurmond** [Azure/MachineLearningNotebooks#1528]
Hi all,

I would like to filter PublishedPipelines and Schedules based on the date updated  as present in the ML workspace online. Similar to `created_at` in for [Model](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py#variables)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51bf1534-0004-72a7-6e9e-cbb855c748e0
* Version Independent ID: b9d3cc69-fd39-d477-d8b3-4372e500ffa6
* Content: [azureml.pipeline.core.PublishedPipeline class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.publishedpipeline?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PublishedPipeline.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PublishedPipeline.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by shbijlan** [comment]
@JCZuurmond thank you for the feedback. I have opened a product improvement item for this. The feature request will be incorporated in the planning and rollout process if approved.
