### ISSUE TITLE
Dataset for inference data is registered with wrong path when deployed on Kubernetes

### ISSUE THREAD

**Issue by waqassiddiqi** [Azure/MachineLearningNotebooks#1529]
When model is deployed on Kubernetes with model data collection set to true, the dataset which gets registered in workspace has a wrong path. 
The blob storage path where this data being collected has `default` in it but the path registered doesn't have `default`.
For example:
Actual path on storage:
```
azuremlwsdev/modeldata/GUID/ad/ad-workspace-dev/dev-ad-model-v1-2-jen/model/default/inputs
```
Path dataset is registered with:
```
GUID/ad/ad-workspace-dev/dev-ad-model-v1-2-jen/model/inputs/**/inputs*.csv
``` 
Code inside our scoring service to init collector and use them:
```
def init():    
    global inputs_dc, prediction_dc
    ...
    inputs_dc = ModelDataCollector('model', designation="inputs", feature_names=feature_set.columns.values.tolist())
    prediction_dc = ModelDataCollector('model', designation="predictions", feature_names=["score"])

def run(raw_data):
    inputs_dc.collect(X)
    prediction_dc.collect(y_pred)
```

Below are the library versions being used:
```
azureml-defaults==1.1.5
azureml-monitoring==0.1.0a21
```

**Comment by shivanissambare** [comment]
hi,
The path to the output data in the blob follows this syntax:

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-enable-data-collection

https://docs.microsoft.com/en-us/python/api/azureml-monitoring/azureml.monitoring.modeldatacollector?view=azure-ml-py

````
/modeldata/<subscriptionid>/<resourcegroup>/<workspace>/<webservice>/<model>/<version>/<designation>/<year>/<month>/<day>/data.csv

# example:

 /modeldata/1a2b3c4d-5e6f-7g8h-9i10-j11k12l13m14/myresourcegrp/myWorkspace/aks-w-collv9/best_model/10/inputs/2018/12/31/data.csv
````

can you use the latest version of azureml-defaults : https://pypi.org/project/azureml-defaults/#history

**Comment by shivanissambare** [comment]
please re-open this issue if you have more questions 
thanks!
