### ISSUE TITLE
Azure ML SDK on Azure Notebooks is out of date

### ISSUE THREAD

**Issue by edrickwong** [Azure/MachineLearningNotebooks#153]
When I run the configuration file, I get: 
```
This notebook was created using version 1.0.6 of the Azure ML SDK
You are currently using version 1.0.2 of the Azure ML SDK
```

**Comment by sungyonhong** [comment]
could you please let us know which configuration file and/or what steps you were doing to see this error?

**Comment by rastala** [comment]
The SDK gets first released to PyPi, then Azure Notebooks picks it up when deploying new base image. So Azure Notebooks may be on previous version, if the new base image hasn't been deployed yet.

If you need to update to latest, you can run !pip install --upgrade azureml-sdk[notebooks] within the notebook cell, or in an environment setup script.
