### ISSUE TITLE
Broken link in AML doc to azureml.core.runconfig.MpiConfiguration

### ISSUE THREAD

**Issue by xkszltl** [Azure/MachineLearningNotebooks#1534]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/5203025/123860354-63399680-d958-11eb-9dc8-dc0a52d67cc2.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109d9284-e234-5086-5da6-4155291361c8
* Version Independent ID: 57cc0c7a-faa7-1a86-ee14-b9cf99fb540d
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by Mossaka** [comment]
Thanks for submitting the issue. I am fixing this broken link now.

**Comment by Mossaka** [comment]
The links should be fixed on next SDK release on Aug 3rd
