### ISSUE TITLE
attach remote compute vm

### ISSUE THREAD

**Issue by yodobrin** [Azure/MachineLearningNotebooks#154]
RemoteCompute.attach is deprecated. 
using the command does not work. instead the code needs to be:
-----------------------
from azureml.core.compute import RemoteCompute
**from azureml.core.compute import ComputeTarget**
from azureml.core.compute_target import ComputeTargetException
import os

username = os.getenv('AZUREML_DSVM_USERNAME', default='XXXXX')
address = os.getenv('AZUREML_DSVM_ADDRESS', default='XXXXXXXXXXXXXXXX')

passw = "XXXXXXXX"

compute_target_name = "ds-ub"

try:
attached_dsvm_compute = RemoteCompute(workspace=ws, name=compute_target_name)
print('found existing:', attached_dsvm_compute.name)
except ComputeTargetException:
attach_config = RemoteCompute.attach_configuration(address=address, ssh_port=22, username=username, password=passw)
attached_dsvm_compute = **ComputeTarget**.attach(ws, compute_target_name, attach_config)

**Comment by rastala** [comment]
Thanks @yodobrin , good catch!
