### ISSUE TITLE
automl tcnforecaster sample in  forecasting-bee-remote with tcnforecaster fails

### ISSUE THREAD

**Issue by azeltov** [Azure/MachineLearningNotebooks#1542]
I am working on a automl tcnforecaster model , and using forecasting-bee-remote as demo. Running into an issue wiht the scoring of the  tcnforecaster.pt file. Getting this pickle error: 

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb
    
Traceback (most recent call last):
  File "/azureml-envs/azureml_4ff0644bb14496c2c4206407b99387dc/lib/python3.7/pickle.py", line 1120, in load_persid
    pid = self.readline()[:-1].decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 63: ordinal not in range(128)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "infer.py", line 277, in <module>
    fitted_model = joblib.load(model_path)
  File "/azureml-envs/azureml_4ff0644bb14496c2c4206407b99387dc/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/azureml-envs/azureml_4ff0644bb14496c2c4206407b99387dc/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/azureml-envs/azureml_4ff0644bb14496c2c4206407b99387dc/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/azureml-envs/azureml_4ff0644bb14496c2c4206407b99387dc/lib/python3.7/pickle.py", line 1123, in load_persid
    "persistent IDs in protocol 0 must be ASCII strings")
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

The other models are working fine only getting this error for TCNForecaster. The customer has build an automl forecaster and best performer is the dnn TCNForecaster and trying to deploy as batch scoring service now and running into the same issue.

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb

**Comment by azeltov** [comment]
# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.7

- pip:
  - azureml-train-automl-runtime==1.31.0
  - inference-schema
  - azureml-interpret==1.31.0
  - azureml-defaults==1.31.0
  - azureml-contrib-automl-dnn-forecasting==1.31.0
- numpy>=1.16.0,<1.19.0
- pandas==0.25.1
- scikit-learn==0.22.1
- py-xgboost<=0.90
- fbprophet==0.5
- holidays==0.9.11
- psutil>=5.2.2,<6.0.0
- pytorch>=1.2
channels:
- anaconda
- conda-forge
- pytorch

**Comment by swatig007** [comment]
based on offline conversation, this issue was due to using an older version of notebook / scripts. using am updated version resolved the issue. hence closing
