### ISSUE TITLE
Error while creating and updating Schedule

### ISSUE THREAD

**Issue by RamyaM12** [Azure/MachineLearningNotebooks#1544]
I've scheduled time based recurrence for pipeline_endpoint_id few days back using Schedule.create_for_pipeline_endpoint. I'm getting error now when trying to update the schedule using update(). 

schedule = Schedule.get(ws, 'id')
schedule.update(recurrence=new_freq_obj)

Error : azureml.pipeline.core._restclients.aeva.models.error_response.ErrorResponseException: (BadRequest) Value cannot be null. (Parameter 'source')

Additionally I'm also not able to create Schedule pipeline now using Schedule.create_for_pipeline_endpoint(..). I'm getting the same error as above.

**Comment by RamyaM12** [comment]
This issue came up from VS Code and is working from notebooks. Closing this issue. Thanks

**Comment by RamyaM12** [comment]
This issue came up from VS Code and is working from notebooks. Closing this issue. Thanks

**Comment by jarandaf** [comment]
@RamyaM12 were you able to solve this? I am getting the same error when trying to create a new pipeline schedule.
