### ISSUE TITLE
How to deploy MobileNetSSD object detection using Azure

### ISSUE THREAD

**Issue by vmdhhh** [Azure/MachineLearningNotebooks#1548]
Does anybody know or can help in this matter -  how to deploy the MobileNetSSD object detection model as a web service on Azure?

**Comment by shivanissambare** [comment]
Hi, you would need to follow steps mentioned here : https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where?tabs=azcli

to deploy a model in azure machine learning

**Comment by shivanissambare** [comment]
Hi, I am closing this issue if you have any more questions, please feel free to re-open 

We do not have specific example for MobileNetSSD, but you can follow the link above to understand deployment process in Azure Machine Learning.

There are several examples for deployments: 
- https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/ml-frameworks
- https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/deployment

Once you have your scoring script you can AzureML inference http server to make sure it works as expected: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-inference-server-http
