### ISSUE TITLE
Search bar on the left is not working

### ISSUE THREAD

**Issue by yangsiyu007** [Azure/MachineLearningNotebooks#155]
Searching for "PythonScriptStep" or "azureml-core" returned "No results" but these are sections of this set of documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c318f67-9169-e151-fc8c-7ff06108db6a
* Version Independent ID: 9dbeb2f3-1382-e246-8eb4-c6fb797f537b
* Content: [API Reference container - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-joined/index.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-joined/index.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by yangsiyu007** [comment]
I find that the search bar works fine on page https://docs.microsoft.com/en-us/python/api/overview/azure/ml/intro?view=azure-ml-py, but not this page...

**Comment by j-martens** [comment]
Thanks for your report. We are aware and have logged a bug to get this fixed. Thank you!
