### ISSUE TITLE
Mount is unix only

### ISSUE THREAD

**Issue by AlexWareUltromics** [Azure/MachineLearningNotebooks#1550]
Why does this page not mention that Mount is only supported on unix-like operating systems? I have to be told in an error message:

"Mount is only supported on Unix or Unix-like operating systems and the FUSE library must be present. For more information, please refer to the remarks section of FileDataset.mount's documentation. Execution failedunexpectedly due to OSError"

Also, why is it unix only? Is there any workaround for other OS's like Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9eddd8e-9908-93f4-1e14-cd8bf1c3ada9
* Version Independent ID: ecba1c21-8faf-2094-36d6-65b0c3ec9018
* Content: [azureml.data.file_dataset.FileDataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.file_dataset.filedataset?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.file_dataset.FileDataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.file_dataset.FileDataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment]
Linux is "Unix-like" and supported. Are you seeing this error message in Linux? It would be expected from Windows, where the recommendation would be to use the Windows Subsystem for Linux (WSL) if needed

**Comment by AlexWareUltromics** [comment]
> Linux is "Unix-like" and supported. Are you seeing this error message in Linux? It would be expected from Windows, where the recommendation would be to use the Windows Subsystem for Linux (WSL) if needed

I got this error on a flask portal - azure app service with a linux plan.

OS.name: posix
Platform.system: Linux
Platform.release: 5.4.0-1031-azure

**Comment by lostmygithubaccount** [comment]
Seems like the data team will need to investigate why you're seeing this error. Additional info needed will likely by the versions of packages, if you could provide that with something like `pip list | grep azureml`

**Comment by AlexWareUltromics** [comment]
Yeah here we go, let's get the data team involved so they can ask the same questions over and over and fail sideways for months. It's ok mate I'll figure it out myself eventually.

**Comment by lostmygithubaccount** [comment]
Sounds good, closing this issue out. Feel free to re-open this issue or open a new issue referencing this one with additional details if additional investigation is needed.
