### ISSUE TITLE
"User program failed with OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by harshalwavre7** [Azure/MachineLearningNotebooks#1562]
Running the following script how-to-use-scriptrun.ipynb from how-to-use-azureml

gettting the below Error 

ActivityFailedException                   Traceback (most recent call last)
<ipython-input-19-c525ff7b8c5b> in <module>
----> 1 run.wait_for_completion(show_output=True)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/run.py in wait_for_completion(self, show_output, wait_post_processing, raise_on_error)
    792                     file_handle=sys.stdout,
    793                     wait_post_processing=wait_post_processing,
--> 794                     raise_on_error=raise_on_error)
    795                 return self.get_details()
    796             except KeyboardInterrupt:

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/run.py in _stream_run_output(self, file_handle, wait_post_processing, raise_on_error)
   1034                 file_handle.write("\n")
   1035             else:
-> 1036                 raise ActivityFailedException(error_details=json.dumps(error, indent=4))
   1037 
   1038         file_handle.write("\n")

ActivityFailedException: ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "User program failed with OSError: [Errno 30] Read-only file system: '/mnt/batch/tasks/shared/LS_root/jobs/hwavremlopssbwksp/azureml/scriptrun_sample_1627583009_958966af/wd/input_bf987af4-3713-4298-949b-4819fc229a80/iris.csv'",
        "messageParameters": {},
        "detailsUri": "https://aka.ms/azureml-run-troubleshooting",
        "details": []
    },
    "time": "0001-01-01T00:00:00.000Z"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with OSError: [Errno 30] Read-only file system: '/mnt/batch/tasks/shared/LS_root/jobs/hwavremlopssbwksp/azureml/scriptrun_sample_1627583009_958966af/wd/input_bf987af4-3713-4298-949b-4819fc229a80/iris.csv'\",\n        \"messageParameters\": {},\n        \"detailsUri\": \"https://aka.ms/azureml-run-troubleshooting\",\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
    }
}

Searched Around but didn't find any solution

**Comment by paulshealy1** [comment]
Thank you for the feedback. Are you running this notebook on an AmlCompute cluster or a Compute Instance?

**Comment by harshalwavre7** [comment]
Compute Instance I resolved the issue by creating a new dataset which i was trying to access in my above code

**Comment by paulshealy1** [comment]
Thank you!
