### ISSUE TITLE
azureml-core compatibility with python3.9

### ISSUE THREAD

**Issue by GautamKumarSkyPointCloud** [Azure/MachineLearningNotebooks#1563]
Hi,

When can we expect the new release of the python sdk which is compatible with python3.9

Thanks

**Comment by absognety** [comment]
@GautamKumarSkyPointCloud commenting relevant issue here Azure/MachineLearningNotebooks#1285

**Comment by paulshealy1** [comment]
@GautamKumarSkyPointCloud thank you for the feedback. Are you only asking about azureml-core, or do you need other packages as well?

**Comment by friggog** [comment]
Also would like to know about py3.9 compatibility for `azureml-core` and `azureml-train-core`

**Comment by paulshealy1** [comment]
For `azureml-core` we are just starting the work. We will get back to you when we have more information to share, and when we know more on `azureml-train-core`.

**Comment by asears** [comment]
Are there typings for AzureML SDK available or will be available as part of this release?

**Comment by paulshealy1** [comment]
`azureml-core` and `azureml-train-core` now support 3.9.
