### ISSUE TITLE
pip install `azureml-core` fails on `ruamel.yaml`

### ISSUE THREAD

**Issue by areed1192** [Azure/MachineLearningNotebooks#1564]
### System Specs
**Operating System:** Windows 10
**Python Version:** 3.9.5 64-bit

When I run the command:

```terminal
pip install azureml-core
```

I get an error during the installation, specifically on the `ruamel.yaml` package. I guess the first question I have is there any reason we are restricted to that specific version of `ruamel.yaml`? I was able to install the latest version **(0.17.10)** no problem, so if we could use a later version that would be the easiest fix.

### Partial Log
```terminal
Attempting uninstall: ruamel.yaml
Found existing installation: ruamel.yaml 0.17.10
Uninstalling ruamel.yaml-0.17.10:
Successfully uninstalled ruamel.yaml-0.17.10
Running setup.py install for ruamel.yaml ... error
ERROR: Command errored out with exit status 1:
```

### Full Log
[Error Log From Installation Run](https://github.com/Azure/MachineLearningNotebooks/files/6913613/error.log)

**Comment by vizhur** [comment]
0.17.5 introduced a breaking change hence there is an upperbound

**Comment by paulshealy1** [comment]
Thank you @vizhur! @areed1192, I'm closing this issue. Please reopen if you still have questions.
