### ISSUE TITLE
AutoMLPipelineBuilder.get_many_models_train_steps - Method shows the message:Parameter automl_settings will be deprecated in the future. Please use ManyModelsParameters instead.Showing this error and 'AttributeError'

### ISSUE THREAD

**Issue by ullas261** [Azure/MachineLearningNotebooks#1567]
![2](https://user-images.githubusercontent.com/75771891/128354472-7e20416a-44ec-49f6-8061-10df3b743043.png)

**Comment by ullas261** [comment]
automl_settings in giving attribute error,

**Comment by cartacioS** [comment]
Hello- could you please try upgrading to SDK version 1.34? We believe this was an issue that was fixed in a newer SDK and upgrading should help unblock you. Keep us updated if you continue to face this issue after upgrading.
