### ISSUE TITLE
Cannot get configuration notebook to work

### ISSUE THREAD

**Issue by sennendoko** [Azure/MachineLearningNotebooks#157]
I'm trying to create a workspace following the instructions in MachineLearningNotebooks/configuration.ipynb. I've set my_sid to an existing subscription ID to which I'm a contributor, my_rg to a resource group in southcentralus which I've created, and my_ws_name to an existing workspace name. I then run this:
```
from azureml.core import Workspace
ws = Workspace.create(name=my_ws_name,
                      subscription_id=my_sid, 
                      resource_group=my_rg,
                      location='southcentralus',
                      create_resource_group=True,
                      exist_ok=True)
```
After half a minute or so, I get a long traceback of which the most informative part seems to be this:
```
CloudError: Azure Error: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
Exception Details:
	Error Code: NotFound
	Message: {'error': {'code': 'InvalidResourceType', 'message': "The resource type could not be found in the namespace 'Microsoft.BatchAI' for api version '2018-05-01'."}}
```
I looked at the failed deployment operations in the activity log under the resource group. The first one to fail has this summary:
```
Error code
PrincipalNotFound
Message
Principal 72407f26c32a43f085d5dce6d550aa5b does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.
```
Can you explain what is going on here? What is a principal, what is the resource type that could not be found, and more generally, what knowledge of Azure is being presupposed here that I apparently don't have? Thanks.

**Comment by nishankgu** [comment]
Hi - Could you please share the SDK version you are using, and roughly when you had created the workspace (was it in December, or somtime in the summer before our Public Preview) - this information will help us diagnose the issue better.

**Comment by sennendoko** [comment]
Hi,

It was created in December. How do I find the SDK version? Thanks.

David

**Comment by nishankgu** [comment]
Thanks. Try running this piece of code if you are using our Python SDK:

import azureml.core
print("You are currently using version", azureml.core.VERSION, "of the Azure ML SDK")
print("")

**Comment by sennendoko** [comment]
That gives 0.1.59. (Sorry for the silly question, I got your mail on my
phone and couldn't check the document).

I'm running  the "Python 3.6 AzureML" interpreter inside Jupyter notebook
on a data science VM provisioned on December 15th.

Thanks!

**Comment by rastala** [comment]
Version 0.1.59 is an old preview one, latest version shouldn't have this issue. Try running ```pip install --upgrade azureml-sdk[notebooks,automl]``` to get the latest version.

**Comment by sennendoko** [comment]
That doesn't help I'm afraid - I still get 0.1.59. Let's close this ticket
- I'm going to take it up with the people who provisioned the VM, as I
don't think they should be using previews and I don't want to get involved
with version issues, that is what data science VMs are meant to avoid.
Thanks!

**Comment by nishankgu** [comment]
We refresh our DSVM image roughly once a month so it is likely that the VM was provisioned a little time back (for example we were still on 0.1.59 in mid december on the DSVM). The upgrade command that Roope shared should work though. You might have to restart the kernel - please let us know if you continue to face an issue.

Apologies for the inconvenience.
