### ISSUE TITLE
Issue loading dataset

### ISSUE THREAD

**Issue by WPB92** [Azure/MachineLearningNotebooks#1574]
I am having issues whilst using Azure Machine Learning Studio.

When attempting to load a dataset it is taking an inordinate amount of time, as you can see from the screenshot below:

![image](https://user-images.githubusercontent.com/85882007/129408500-788f2f11-d624-4134-aea6-dc2b4834bd23.png)

The dataset itself is a .csv file of size 21mb.

Please could someone provide some guidance or suggestions on how I could go about rectifying this problem.  If you require any more details, then please do let me know.

**Comment by ynpandey** [comment]
Can you share the code snippet you used for creating this this dataset?

**Comment by WPB92** [comment]
The dataset itself was uploaded directly to Azure Machine Learning Studio. I have however provided all of the code for full visibility.

```
import azureml
from azureml.core import Experiment
from azureml.core import Environment
from azureml.core import Dataset
from azureml.core import Workspace, Run
from azureml.core.compute import ComputeTarget, AmlCompute
from azureml.core.compute_target import ComputeTargetException

ws = Workspace.from_config()
print('Workspace name: ' + ws.name, 
      'Azure region: ' + ws.location, 
      'Subscription id: ' + ws.subscription_id, 
      'Resource group: ' + ws.resource_group, sep='\n')

script_folder = './TestingModel1'
os.makedirs(script_folder, exist_ok=True)

exp = Experiment(ws, name='TestingModel1')


cluster_name = "cpu-cluster"

try:
    compute_target = ComputeTarget(workspace=ws, name=cluster_name)
    print('Found existing compute target')
except ComputeTargetException:
    print('Creating a new compute target...')
    compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_NC6',
                                                           max_nodes=4)

    compute_target = ComputeTarget.create(ws, cluster_name, compute_config)

    compute_target.wait_for_completion(show_output=True, min_node_count=None, timeout_in_minutes=20)

compute_targets = ws.compute_targets
for name, ct in compute_targets.items():
    print(name, ct.type, ct.provisioning_state)

keras_env = Environment.from_conda_specification(name = 'keras-2.3.1', file_path = './conda_dependencies.yml')

# Specify a GPU base image
#keras_env.docker.enabled = True
keras_env.docker.base_image = 'mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.0-cudnn7-ubuntu18.04'

test_data_ds = Dataset.get_by_name(ws, name='test_data')

```
I have tried changing the final line of the above to the below (thinking that the issue could be with the Dataset.get_by_name function). The same issue still exists however.

```
ds = ws.datasets['test_data']
df = ds.to_pandas_dataframe()
```

Please note that the conda_dependencies.yml file contains the following, although I don't think this will be the route of the problem.

```
channels:
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - azureml-defaults
  - tensorflow-gpu==2.0.0
  - keras<=2.3.1
  - matplotlib
  - pandas
  - scikit-learn

```

**Comment by WPB92** [comment]
I have attempted to load the dataset again this morning. The code to load the dataset executed within 6 seconds. 

Does anyone know what the cause could be as to why it was taking so long previously? How could I go about trying to troubleshoot this?

**Comment by ynpandey** [comment]
From the description that you have provided, it may be a problem with network/connectivity. In case you encounter this problem again, it will be helpful if you can share the logs.

**Comment by WPB92** [comment]
Noted Yogi. Thank you for your assistance - should it re-occur I will make sure to share the logs.
