### ISSUE TITLE
Identity Based Access No longer works (with Azure SQL DB datastore) in V1.33 of Azure ML SDK

### ISSUE THREAD

**Issue by rudizhou428** [Azure/MachineLearningNotebooks#1584]
Seems like recent upgrade to V1.33 for Azure ML SDK has changed how identity based access worked? Previously if you had a datastore (ex. SQL) with no credentials and then tried to register a dataset, it would prompt you to login to get your AAD auth token to see if you had permission to get access to the underlying data source. Seems like recent update the same code now seems to prompt this message instead of asking for user to login to and grab AD auth token:
**_Getting data access token with Assigned Identity (client_id=clientid)._**

I have verified the underlying datastore does not have Managed Identity on and V1.32 SDK Prompts me to log in at microsoft.com/devicelogin and gives a code to enter and identity based access works normally after. Has any changes been made to the identity based access feature from on V1.33 SDK? According to the SDK docs, running the TabularDataset.to_pandas_dataframe() command should prompt an AD login if using no credentialed datastore into dataset creation. FYI currently using Azure SQL DB as datastore, any clarifications would be appreciated!
azureml.core.Datastore class - Azure Machine Learning Python | Microsoft Docs

**Comment by rudizhou428** [comment]
Any updates to this?

**Comment by rastala** [comment]
The driver log had error message "Compute has no identity provisioned." Try updating the compute to enable managed identity, and grant managed identity access to the data storage.

**Comment by rudizhou428** [comment]
Ah ok I was under the impression only the compute clusters had MI and not the compute instance. I'll take a look at the docs and will also re-configure the datastore which might be issue.

**Comment by rudizhou428** [comment]
@chunyli0328 Ah ok cool, I ended up creating a new Azure ML Workspace and moved all my files over and since you need to recreate the CI and clusters, I'm guessing thats why it started to work again. Closing this issue, thanks for the help everyone!
