### ISSUE TITLE
Azureml-sdk seems to have some dependencies on Azure package

### ISSUE THREAD

**Issue by santiagxf** [Azure/MachineLearningNotebooks#161]
Some commands would fail if Azure python package is not present in the env. I would suggest updating the documentation to reflect that. In my case, I had to use pip install azure in order to completely be able to work with Azure Machine Learning Services using azure-sdk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0be5f00-b267-a544-5e1c-36fa254f7801
* Version Independent ID: b8b3eec3-8cf4-dc39-a4e3-f2ed5fa3590d
* Content: [Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/intro?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-conceptual/intro.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-conceptual/intro.md)
* Service: **machine-learning**
* GitHub Login: @rastala
* Microsoft Alias: **roastala**

**Comment by swatig007** [comment]
Hi,
  Can you please provide more info on which specific commands failed?
Thanks.

**Comment by santiagxf** [comment]
Sure, the problem seem to be related when you already have some parts of the SDK in your Python environment. After installing, when importing

python` -c "import azureml.core"
ImportError: No module named 'azure.mgmt.storage' from azure.mgmt.storage import StorageManagementClient

"pip install azure" fixes the issue and then the SDK works correctly.

**Comment by rastala** [comment]
How did you install the SDK? If you pip install it should pull in the necessary azure.mgmt dependencies automatically.
