### ISSUE TITLE
task parameter 

### ISSUE THREAD

**Issue by rbobadilla** [Azure/MachineLearningNotebooks#162]
Hi all

Allowed values on task parameters are: "regression" or "classification". What if i have a clustering problem, or a neural network?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d73eed-d8eb-b7a6-ec5b-98d391cf8a16
* Version Independent ID: 242cf736-4dea-6309-6410-e027e01e5e84
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swatig007** [comment]
Hi,
  Automated ML supports only tasks of type classification, regression or forecasting. More info can be found at -
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-auto-train
