### ISSUE TITLE
Bug Reports for AzureML SDK?

### ISSUE THREAD

**Issue by deeceefar2** [Azure/MachineLearningNotebooks#1626]
Where do you file bug reports for the AzureML SDK?  I don't see it listed on the documentation web pages: https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py

It's also not obvious how to file it where opening Azure Support Request only allowing for "Problems with Installation" and the "Get Support: link in the links at the Top Left of the documentation page takes you to MSDN forum for asking a "Question".

It seems there should be a link in the documentation and Azure Support Requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb938463-51c2-43f3-d528-76a07a28bec8
* Version Independent ID: e15753c0-6fe1-100a-0efc-08c1f845dc83
* Content: [Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/index.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/index.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by Sysa** [comment]
You can for sure use common python azure SDK issue log for filling in any AML SDK related questions: https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aissue+is%3Aopen+AML+
