### ISSUE TITLE
ContainerImage configuration Python version always 3.6.7

### ISSUE THREAD

**Issue by thijsgelton** [Azure/MachineLearningNotebooks#163]
Hi,

Asked on stackoverflow as well: https://stackoverflow.com/questions/54072811/how-to-change-the-python-version-in-azure-machine-learning-sdk-containerimage-wi

I am trying to get my Faster R-CNN model into an Container Instance on ACI. For that I need my docker image to posses python version 3.5.*. I specify that in my conda yaml file, but everytime I spin an instance up and 'docker run -it *** /bin/bash' into it I see that it only has python 3.6.7. 
![image](https://user-images.githubusercontent.com/21140767/50680590-82b20b80-1008-11e9-9bfe-4a0e71084ce0.png)

How can I get my docker image to have python version 3.5.*? I already tried conda installing python version 3.5.2, but that didnt work as eventually it didnt posses 3.5.2, but only 3.6.7. (dfimage lets you see the dockerfile from which the image was created, https://hub.docker.com/r/chenzj/dfimage/).
![image](https://user-images.githubusercontent.com/21140767/50680673-d6245980-1008-11e9-9d48-71a7c150d925.png)

My yaml:
```yaml
name: project_environment
dependencies:
- python=3.5.2

- pip:
  - matplotlib
  - opencv-python==3.4.3.18
  - azureml-core==1.0.6
  - numpy
  - cntk
  - cython
channels:
- anaconda
```

Notebook cell:
```python
from azureml.core.conda_dependencies import CondaDependencies 

svmandss = CondaDependencies.create(python_version="3.5.2", pip_packages=[
    "matplotlib",
    "opencv-python==3.4.3.18",
    "azureml-core",
    "numpy",
    "cntk",
    "cython"], )
svmandss.add_channel('anaconda')

with open("fasterrcnn.yml","w") as f:
    f.write(svmandss.serialize_to_string())
```

Another notebook cell with ContainerImage specifications.
```python
%%time

# configure the image
image_config = ContainerImage.image_configuration(execution_script="score_fasterrcnn.py", 
                                                  runtime="python", 
                                                  conda_file="./fasterrcnn.yml",
                                                  dependencies=listdir("utils"),
                                                  docker_file="./Dockerfile")

service = Webservice.deploy_from_model(workspace=ws,
                                       name='faster-rcnn',
                                       deployment_config=aciconfig,
                                       models=[Model(workspace=ws, name='Faster-RCNN')],
                                       image_config=image_config)

service.wait_for_deployment(show_output=True)
```

Thanks for your help.

**Comment by thijsgelton** [comment]
Edit: this is no longer a problem for me as I found another way to make my project work with python version 3.6.7

**Comment by rastala** [comment]
Currently, the version of Python is fixed to what's in Azure ML's base image, when deploying the web service. We're investigating removing this limitation in future.
