### ISSUE TITLE
Loosen azureml-dataprep requirements to cloudpickle<=2.0.0

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [Azure/MachineLearningNotebooks#1637]
`azureml-dataprep` (which is a depedency for `azureml-dataset-runtime`) has requirement `cloudpickle<2.0.0 and >=1.1.0`. However there is to my knowledage no breaking features going from `cloudpickle==1.6.0` to `cloudpickle==2.0.0`. `cloudpickle==2.0.0` introduces some very effective tools for serializing helper scripts which is very helful when working with azureml. So `azureml-dataprep` should allow `cloudpickle==2.0.0 `

Intro to new cloudpickle:
https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs

PR: 

https://github.com/cloudpipe/cloudpickle/pull/417

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by YutongTie-MSFT** [comment]
@harneetvirk Hello Harneet, could you please review the PR and see if we can merge it? Thanks.

**Comment by yikei** [comment]
@thomasfrederikhoeck - Thank you for your feedback here and also sending us an email! I am part of the team maintaining azureml-dataprep.

We included version upper bounds to the packages we depend on to avoid automatically taking in new major versions that might have breaking changes. We will look into loosening the upper bound of cloudpickle and get back to you about this.

**Comment by thomasfrederikhoeck** [comment]
That makes a lot of sense and is probably a good default behavior @yikei . I will be looking forward to it :-)

**Comment by YutongTie-MSFT** [comment]
@thomasfrederikhoeck Hello Thomas, is that possible for you to accept the answer in Q&A forum since this issue has been good handle here by yikei?
https://docs.microsoft.com/en-us/answers/questions/632441/index.html

Thanks a lot!

**Comment by thomasfrederikhoeck** [comment]
@YutongTie-MSFT done :-)

**Comment by yikei** [comment]
@thomasfrederikhoeck Quick update - we are targeting to loosen the upper bound of cloudpickle and have the change shipped by mid January. It should be released as azureml-dataprep 2.26, which will be used by AzureML SDK 1.38. Thanks!

**Comment by thomasfrederikhoeck** [comment]
@yikei wonderful! Many thanks.

**Comment by yikei** [comment]
To give an update, we released azureml-dataprep 2.26 already. Once azureml sdk 1.38 releases (scheduled for 1/24/2022), it will start picking up azureml-dataprep 2.26. (If you use compute instances, it may take a few extra days for the image to get updated to use the newest versions.)
Or, you may try upgrading dataprep manually if you need it urgently. Thanks!

**Comment by thomasfrederikhoeck** [comment]
@yikei sounds good! I will close the ticket as it relates to azureml-dataprep. Thank you for fixing. As site-note: when I went to https://pypi.org/project/azureml-dataprep/2.26.0/ to see the new package it appears that the Homepage url (under Project Links) is broken - just to let you know.

**Comment by yikei** [comment]
@thomasfrederikhoeck Appreciate the heads up! We used to have extensive public facing documentation for azureml-dataprep but that has been removed (as we no longer recommend directly using dataprep). We will get that old link removed. Thanks!
