### ISSUE TITLE
AutoML pipeline for object detection training: subprocess failed to get dependencies list from conda

### ISSUE THREAD

**Issue by ameicler** [Azure/MachineLearningNotebooks#1671]
Trying to run a basic AutoML training pipeline for object detection following the documentation (yolov5 or fasterrcnn_resnet50_fpn models produce the same error) such as:

``` python
ENV_NAME = "AzureML-pytorch-1.10-ubuntu18.04-py38-cuda11-gpu"

ws = Workspace.from_config()
compute_target = ComputeTarget(workspace=ws, name=CLUSTER_NAME)

aml_run_config = RunConfiguration()
aml_run_config.target = compute_target
curated_environment = Environment.get(workspace=ws, name=ENV_NAME)
aml_run_config.environment = curated_environment
aml_run_config.environment.name = 'env-antoine-ml'
aml_run_config.environment.version = '1.0'

experiment = Experiment(ws, name=EXPERIMENT_NAME)

ds = Datastore(ws, DATASTORE_NAME)
ds_input = Dataset.get_by_name(ws, name=DATASET_NAME)

metrics_output_name = 'metrics_output'
best_model_output_name = 'best_model_output'

metrics_data = PipelineData(name='metrics_data',
                           datastore=ds,
                           pipeline_output_name=metrics_output_name,
                           training_output=TrainingOutput(type='Metrics'))
model_data = PipelineData(name='model_data',
                           datastore=ds,
                           pipeline_output_name=best_model_output_name,
                           training_output=TrainingOutput(type='Model'))

image_config_yolov5 = AutoMLImageConfig(
    task=ImageTask.IMAGE_OBJECT_DETECTION,
    compute_target=compute_target,
    run_configuration=aml_run_config,
    training_data=ds_input,
    hyperparameter_sampling=GridParameterSampling({"model_name": choice(MODEL_NAME)}),
    iterations=1,
)

automl_step = AutoMLStep(
    name='automl_module',
    automl_config=image_config_yolov5,
    outputs=[metrics_data, model_data],
    allow_reuse=True
)

pipeline = Pipeline(ws, steps=[automl_step])
automl_image_run = experiment.submit(pipeline)
automl_image_run.wait_for_completion()
```

As you can see from the driver log enclosed, training seems to run OK but after last epoch, child run fails on this obscure message. Any idead how to solve it or what's going on?

> subprocess failed to get dependencies list from conda
Type: Unclassified
Class: FileNotFoundError
Message: [Hidden as it may contain PII]
Traceback:   File "package_utilities.py", line 338, in _all_dependencies_conda_list
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
ExceptionTarget: Unspecified

[70_driver_log.txt](https://github.com/Azure/MachineLearningNotebooks/files/7900468/70_driver_log.txt)

**Comment by vizhur** [comment]
Is that just a warning? from the log it looks like run completed successfully

**Comment by ameicler** [comment]
The job never stops running actually (it never completes). So if I add an additional step afterwards, this step never starts

**Comment by mobaniha** [comment]
use this instead 

```
automl_step=AutoMLStep(
    name='automl_module',
    automl_config=image_config_yolov5,
    # outputs=[metrics_data, model_data], # skip this step as it causes the step to copy the artifact to pipeline output
    enable_default_model_output=True, # set this
    enable_default_metrics_output=True, #set this
    allow_reuse=True
)
```

**Comment by raduk** [comment]
@ameicler this has been resolved and deployed
