### ISSUE TITLE
Unable to import azureml.contrib

### ISSUE THREAD

**Issue by tomjamesis** [Azure/MachineLearningNotebooks#1682]
The title is identical to ['Unable to import azureml.contrib'](https://github.com/Azure/MachineLearningNotebooks/issues/1355), which appears to be sub-set issue of the [confusing Python package strategy](https://github.com/Azure/MachineLearningNotebooks/issues/1325) and not resolved by another associated issue [azureml-defaults not described](https://github.com/Azure/MachineLearningNotebooks/issues/1341). This problem does **_not_** have a solution that I can find via Google.

The attached image demonstrates the error and attempts to resolve it (cell [14]). Yes, the 'Trainig' typo is noted!!!

![azureml-contrib package issue](https://user-images.githubusercontent.com/93130742/153775895-c2cc9695-a0b9-471c-93b4-381de51cb01e.png)

**Comment by tomjamesis** [comment]
Unfortunately, I tried this, which is visible in the second line within 'cell[14]' and is commented out, in the previously attached image. Running `!pip list` indicates that `azureml-contrib-dataset 1.38.0` is installed (see below).

![image](https://user-images.githubusercontent.com/93130742/154475241-7aa36a82-05ca-4cd1-8f7d-6c4a177258e4.png)


I have also performed a full `!pip audit` to eliminate missing package issues but this did not solve the issue either.

**Comment by vizhur** [comment]
>> pip install azureml-contrib-dataset
>> python
>>> import azureml.contrib.dataset

unable to repro. Possibly something was installed that overwrote the namespace and you still see the package but it can't be resolved by python. Full pip list might help, or try to force package install
