### ISSUE TITLE
Python Version Required?

### ISSUE THREAD

**Issue by jeffsdata** [Azure/MachineLearningNotebooks#1689]
What version of Python is suggested for installing azureml-sdk? I tried installing the following packages, and it seems like the pip dependency resolver isn't working on Python 3.9.6.

azureml-sdk
azureml-pipeline-steps
azureml-pipeline-core
azureml-explain-model

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by harneetvirk** [comment]
The latest pip is significantly stricter and more consistent when it receives incompatible instructions, and the dependency resolver sometimes takes way too long to resolve the conflicts. 
One of the workarounds is to pin pip (pip==21.1.1) back to the older release with the old resolver. 
azureml-sdk (1.38.0) requires Python >=3.6, <3.9

**Comment by jeffsdata** [comment]
Awesome! That works. Thanks for the response!
