### ISSUE TITLE
azure machine learning - environment - SDK- conda dependancies seems not to be taken into account

### ISSUE THREAD

**Issue by bilnab** [Azure/MachineLearningNotebooks#1696]
i need joblib but same thing with pillow
i start by cloning a tensorflow environment so as to add some dependancies as mentionned on the documentation on my jupyterlab notebook
if i modify directly the dockerfile on studio for example, the experiment is ok
but if i try to add some dependancies , the environment seem not to take into account the request.
what i m doing wrong? or what the sdk is doing wrong?

```
     import os, shutil
     import pandas as pd
     from joblib import dump, load
#training folder
     training_folder = 'test-dir'
     os.makedirs(training_folder, exist_ok=True)
#data for experiment
     data = {'product_name': ['laptop', 'printer', 'tablet', 'desk', 'chair'],
             'price': [1200, 150, 300, 450, 200]
             }
     df = pd.DataFrame(data)
     dump(df,os.path.join(training_folder, 'test.joblib'))
```
write python script:
```
     %%writefile $training_folder/test.py
        
     import os
     from azureml.core import Run
     # Get the experiment run context
     run = Run.get_context()
        
     #load data
     from joblib import dump, load
        
     data = load('test.joblib', mmap_mode='r')
     run.complete()
```
submit the experiment:
```
     from azureml.core import Experiment, ScriptRunConfig, Environment, Workspace
     from azureml.core.compute import ComputeTarget
     from azureml.core.environment import Environment
     from azureml.core.conda_dependencies import CondaDependencies
     ws = Workspace.from_config()
     compute_name = 'P7-cpu' #'Standard_DS3_v2'
        
     env = Environment.get(workspace=ws, name="AzureML-tensorflow-2.7-ubuntu20.04-py38-cuda11-gpu")
     env_clone = env.clone("custom_env")
     # Adds dependencies
     conda_dep = CondaDependencies()
     conda_dep.add_pip_package("joblib==1.0.1")
     env_clone.python.conda_dependencies=conda_dep
     script_config = ScriptRunConfig(source_directory=training_folder,
                           script='test.py',
                           compute_target=ComputeTarget(workspace=ws, name=compute_name),
                           environment=env_clone)
     experiment_name = 'test-train'
     experiment = Experiment(workspace=ws, name=experiment_name)
     run = experiment.submit(config=script_config)
        
     run.wait_for_completion()
```

error after running:
[2022-02-24T08:53:35.895570] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
2 items cleaning up...
Cleanup took 0.10983729362487793 seconds
Traceback (most recent call last):
File "[test.py](http://test.py/)", line 8, in <module>
from joblib import dump, load
ModuleNotFoundError: No module named 'joblib'

**Comment by vizhur** [comment]
Curated environment is a user managed curated environment, that means python dependencies are defined in the dockerfile or base image. Python dependencies defined in the python section will be ignored (SDK is luck of proper warning unfortunately). 

Curated environments are not intended to be extended and there is no way but just take a dockerfile and add another conda/pip install to build your environment.
