### ISSUE TITLE
Please document this class.

### ISSUE THREAD

**Issue by admcleod** [Azure/MachineLearningNotebooks#170]
To run MPI-based training scripts, this seems pretty essential.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cc2832-6f5f-946e-5882-8bcc8d284544
* Version Independent ID: 90b524ab-0aca-7347-391f-38368977b045
* Content: [azureml.core.runconfig.MpiConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfig.mpiconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.runconfig.MpiConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.runconfig.MpiConfiguration.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by grgarcia-ms** [comment]
404 when trying to access content source.

**Comment by j-martens** [comment]
@grgarcia-ms - https://docs.microsoft.com/python/api/azureml-core/azureml.core.runconfig.mpiconfiguration?view=azure-ml-py

**Comment by grgarcia-ms** [comment]
Params were already updated and should be in by Monday, what exactly are we asking for here? It seems its more than params what you want, an example?
