### ISSUE TITLE
Script error with Databricks

### ISSUE THREAD

**Issue by gbrueckl** [Azure/MachineLearningNotebooks#171]
I am running the samples from https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/machine-learning-pipelines in my Databricks environment and when I run the following code
´´´
RunDetails(pipeline_run2).show(render_lib = displayHTML)
´´´
I end up with a "script error"

also tried this code with the same error:
```
RunDetails(pipeline_run2).show(render_lib = displayHTML, widget_settings = {"debug": True, "display": "popup"})
```

any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9ee5b5-b8b7-0e7e-a665-a9c602b835c0
* Version Independent ID: 6b238373-7218-71fc-a3aa-89a7687086d4
* Content: [azureml.widgets.RunDetails class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-widgets/azureml.widgets.rundetails?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-widgets/azureml.widgets.RunDetails.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-widgets/azureml.widgets.RunDetails.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by parasharshah** [comment]
Adding @sanpil as fyi pls

**Comment by hning86** [comment]
Jupyter widgets does NOT work in Databricks Notebook. Please skip that line.

**Comment by j-martens** [comment]
We will now proceed to close the issue. Thank you.
