### ISSUE TITLE
Environment creation from existing conda env on managed compute instance fails

### ISSUE THREAD

**Issue by sbp-dev** [Azure/MachineLearningNotebooks#1719]
Hi, I was trying to understand environment reproduction from this example notebook
https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/training/using-environments

I wanted to see if I can clone an environment using AzureML SDK from an already existing conda environment in the same machine, so tried the following:

- Opened a notebook in ml.azure.com
- Connected to a managed Compute Instance (STANDARD_DS3_V2)
- The instance already has a few conda environments pre-installed, chose to create an Environment object from existing conda env named "azureml_py38_PT_TF"
- Submitted a dummy script to run using this Environment in the same machine (hoping it would automatically create a new environment with different name)
- Fails with "Creating conda environment failed with exit code: 1"

Upon inspecting the logs, this seems to be the first error:
`ERROR: Cannot uninstall 'ptyprocess'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

This seems very surprising since its a working environment and everything is in the same machine! Attaching notebook code with logs 
[create_env_code.pdf](https://github.com/Azure/MachineLearningNotebooks/files/8315457/create_env_code.pdf)
[60_control_log.txt](https://github.com/Azure/MachineLearningNotebooks/files/8315458/60_control_log.txt)

**Comment by vizhur** [comment]
There is a little chance to repro existing environment from conda export esp on a complex env like CI due to many some custom steps for the env set up. I would suggest to specify the dependencies actually needed for the run

**Comment by sbp-dev** [comment]
Of course, I can use `from_conda_specification` , `from_pip_requirements` etc. to build my environment if I really wanted to. But if the `from_existing_conda_environment` method works as promised, it'd really be great since then I don't have to hand-pick every dependency.
