### ISSUE TITLE
ModuleNotFoundError: No module named 'azureml.explain'

### ISSUE THREAD

**Issue by zszzsz111** [Azure/MachineLearningNotebooks#172]
code：
from azureml.train.automl.automlexplainer import explain_model
shap_values,expected_values,overall_summary,overall_imp,per_class_summary,per_class_imp=explain_model(fitted_model, x_train, x_test)
#Overall feature importance
print(overall_imp)
print(overall_summary) 
#Class-level feature importance
print(per_class_imp)
print(per_class_summary) 

result：
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
&lt;ipython-input-41-fc557da69821&gt; in &lt;module&gt;
      2 from azureml.train.automl.automlexplainer import explain_model
      3 
----&gt; 4 shap_values,expected_values,overall_summary,overall_imp,per_class_summary,per_class_imp=explain_model(fitted_model, x_train, x_test)
      5 #Overall feature importance
      6 print(overall_imp)

~/anaconda3_501/lib/python3.6/site-packages/azureml/train/automl/automlexplainer.py in explain_model(fitted_model, X_train, X_test, best_run, features, **kwargs)
     73         return _convert_explanation(explanation)
     74     except ImportError as import_error:
---&gt; 75         raise import_error
     76 
     77 

~/anaconda3_501/lib/python3.6/site-packages/azureml/train/automl/automlexplainer.py in explain_model(fitted_model, X_train, X_test, best_run, features, **kwargs)
     41 
     42     try:
---&gt; 43         from azureml.explain.model._internal import TabularExplainer
     44 
     45         # Transform the dataset for datatransformer and laggingtransformer only

ModuleNotFoundError: No module named 'azureml.explain'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c9ed64-01c3-d7d5-bbdb-8ede3f69d02e
* Version Independent ID: 01df3a5d-c87d-b629-4cfe-2ddee7f2eb06
* Content: [azureml.train.automl.automlexplainer module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlexplainer?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlexplainer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlexplainer.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by rastala** [comment]
Try installing the explainability extra using ```pip install azureml-sdk[explain]```
