### ISSUE TITLE
reference to constants.Metric.CLASSIFICATION_PRIMARY_SET doesn't exist

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#173]
azureml.train.automl.constants.Metric.CLASSIFICATION_PRIMARY_SET
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d73eed-d8eb-b7a6-ec5b-98d391cf8a16
* Version Independent ID: 242cf736-4dea-6309-6410-e027e01e5e84
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
in the docs for the `AutoMLConfig class` the description for the parameter `primary_metric` references `azureml.train.automl.constants.Metric.CLASSIFICATION_PRIMARY_SET` and 
`azureml.train.automl.constants.Metric.REGRESSION_PRIMARY_SET` that I can't find anywhere in the docs

> `primary_metric`
> str or azureml.train.automl.constants.Metric
> The metric that Automated Machine Learning will optimize for model selection. Automated Machine Learning collects more metrics than it can optimize. Please consult azureml.train.automl.constants.Metric.CLASSIFICATION_PRIMARY_SET for valid metrics for a classification task and azureml.train.automl.constants.Metric.REGRESSION_PRIMARY_SET for valid metrics for a regression task.

https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py

**Comment by wchill** [comment]
@SKrupa

**Comment by swanderz** [comment]
@pathancuet @j-martens -- thanks for getting back to me. I appreciate the help.

my ask is to have a page added to the docs that details what all the metrics are, not just their names. This does not exist currently.

I have two reason for why this is important:
1. My fallback so far has been to use the [sklearn docs](https://scikit-learn.org/stable/modules/classes.html), however there are metrics in AutoML which are not present there, such as  `average_precision_score_weighted`.
2. It concerns the metrics that you mentioned above for classification is a different set from what this AutoMLConfig error provides to me: 
    ```
    ValueError: Invalid primary metric specified for classification. Please use on of:
    ['norm_macro_recall', 'average_precision_score_weighted', 'precision_score_weighted', 'accuracy', 'AUC_weighted']
    ```

**Comment by SKrupa** [comment]
@swanderz We have a fix to this documentation shipping shortly. The new reference for these metrics will be 
    `azureml.train.automl.utilities.get_primary_metrics(<task>)`
instead of 
    `azureml.train.automl.constants.Metric.<task>_PRIMARY_SET`
If you are using an older SDK, this method might still be private, so you can try and use 
    `azureml.train.automl.utilities._get_primary_metrics(<task>)`
This new reference should match the ValueError output, which is what our system supports "under the hood". The automated ML experiment will fail at start up time if the primary metric is set incorrectly, so there should be no concern of running a faulty experiment in the scenario a non-primary metric is selected.

You can find the calculations here: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-auto-train#explore-model-metrics
I will follow up to make sure our documents align with each other and making this information easier to discover.

**Comment by swanderz** [comment]
@SKrupa ok great. that metrics reference page is what I wanted. I'll experiment with upgrading the SDK this weekend
