### ISSUE TITLE
mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20220418.v1

### ISSUE THREAD

**Issue by migsguray** [Azure/MachineLearningNotebooks#1745]
What's the best tag for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04? mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20220418.v1 image is having xz utilz vulnerability.

**Comment by vizhur** [comment]
The best tag to use is the latest versioned tag. The one you listed is the latest as of today. Vulnerabilities addressed within 30 days, so the next release will have a fix for known vulnerabilities
