### ISSUE TITLE
Misleading Error Statement

### ISSUE THREAD

**Issue by agarwal22meghaMS** [Azure/MachineLearningNotebooks#178]
My client was trying to register a data store and had permission issues but got a 400 Azure data lake error asking to ensure the store name is correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb6da6e-eb0a-616d-5c2f-3dd3bb659460
* Version Independent ID: 3196a898-00f8-bf48-e804-6249c2f3748d
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#register-azure-data-lake-workspace--datastore-name--store-name--tenant-id--client-id--client-secret--resource-url-none--authority-url-none--subscription-id-none--resource-group-none--overwrite-false-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by agarwal22meghaMS** [comment]
![image](https://user-images.githubusercontent.com/44770681/51632556-84a42600-1f47-11e9-9853-01a3a73db186.png)

**Comment by rastala** [comment]
Thank you for reporting this issue!

**Comment by j-martens** [comment]
@rastala is this still open? If not, #please-close

**Comment by jamescheng01** [comment]
@agarwal22meghaMS Does your client use Azure Data Lake Gen2 or Gen1? I am trying to register Azure Data Lake Gen2 unsuccessfully. Could you share some insight how to do it?

**Comment by mssshankar** [comment]
See the earlier comment. ADLS gen2 support is being worked on, and only ADLS gen1 is supported currently.
