### ISSUE TITLE
Submit job from function in notebook

### ISSUE THREAD

**Issue by damienpontifex** [Azure/MachineLearningNotebooks#180]
In examples such as [TensorFlow Distributed Training](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-train-tensorflow#distributed-training) the estimator takes an entry script.

If I'm working in a jupyter notebook, is it possible to take a function from the notebook and submit? If I'm experimenting in the notebook and want to convert that to a training job in Batch AI say. Maybe something like

```python
def train(steps, learning_rate):
    # Have training code here

from azureml.train.dnn import TensorFlow

tf_est = TensorFlowJob(entry_point=train,
                    params={
                        'steps'=1000,
                        'learning_rate'=1e-3
                    },
                    compute_target=compute_target,
                    node_count=2,
                    process_count_per_node=1,
                    distributed_backend='mpi',
                    use_gpu=True)
```

Maybe this would dump the jupyter session with something like dill and then create a script file that loads the session and executes it. The code from the `tf_est` constructor might be:
```python
def TensorFlowJob(entry_point, params):
    import dill
    diill.dump_session('tf-est.pkl')
    est_func_name = entry_point.__name__

    script = """import dill

    dill.load_session('dill-session.pkl')

    eval('{entry_point}')(**{entry_args})
    """.format(entry_point=entry_point.__name__, entry_args=params)

    with open('script.py', 'w') as f:
        f.write(script)

    from azureml.train.dnn import TensorFlow

    tf_est = TensorFlow(source_directory='.',
                        script_params={},
                        compute_target=compute_target,
                        entry_script='script.py',
                        node_count=2,
                        process_count_per_node=1,
                        distributed_backend='mpi',
                        use_gpu=True)
    
    return tf_est
```

This then could pass onto the script constructor as per the docs.

n.b. This is in no way a spec or tested, but I'm trying to see how I can take a jupyter notebook and then run in a scaled out fashion with the lowest friction. Happy for any feedback, suggestions or other notes

**Comment by rastala** [comment]
Thanks for feedback @damienpontifex ! We have functions-as-runs in our feature backlog. 

There's some subtleties involved, such as how to pass in input arguments and handle return values; it'd be great to hear your thoughts.

**Comment by damienpontifex** [comment]
Thanks @rastala I'd love to be involved making it happen. Please let me know if there's a branch or trial approaches that may be of interest? Or if I can provide feedback in another way.

I'm very early into investigating how I could make this happen so don't have anything more to add than what is already above. If I do find out more or investigate further I'll be sure to add to this.

**Comment by damienpontifex** [comment]
I came across [kubeflow/fairing](https://github.com/kubeflow/fairing) today and wondered whether it provides any insights into how this could be achieved?
