### ISSUE TITLE
Private wheel addition to Environments from JFROG or Storage Account

### ISSUE THREAD

**Issue by pankajkumar002** [Azure/MachineLearningNotebooks#1803]
Hi, 
I am trying to add a private python wheel file to my AzureML Environment from JFROG or AMLs default storage account. I cannot figure out how to add a private_pip_wheel from the AMLs default storage account instead of a local disk. 
Below is the workflow - 
1. ML Engineers create a private wheel file in their local box
2. This package is availed to the Data Scientists and is pip installed by them in their conda environment
3. The Data Scientists are using these private libraries to create their training pipelines
4. Now the wheel file shall also is added to the conda.yml by Data Scientist
5. This conda environment is registered on Azure ML using Environment. register() package

Now instead of sharing the wheel file with Data Scientists through a direct channel, ML Engineers wants to rather ship it to a storage location and broadcast it to all available Data Scientists. 
Also, instead of uploading these private wheel files to AMLs environments from local disks, they want to upload them from a Storage Location or JFROG artifactory.

Could you please help in understand the right workflow for doing this? Thanks

**Comment by gravesee** [comment]
@vizhur this ONLY works with Azure Devops, correct? I have not had any success configuring this to work with JFrog or other private repositories
