### ISSUE TITLE
Adding / Reading description and tags for Environment using Python SDK

### ISSUE THREAD

**Issue by sbp-dev** [Azure/MachineLearningNotebooks#1805]
Hi, I'm able to create environments and register them using Python SDK. However, I can't find a way to add "Description" and "Tags". 

I can add them from the web portal after registering though (refer image). I then tried to read it back using:
`env = Environment.get(ws, "my_env")`
However, I can't seem to find the description / tag information anywhere within the `env` object

![image](https://user-images.githubusercontent.com/54526452/186431138-a84ee506-b03f-472b-baad-e8ef5cef1d95.png)

Any leads please? Thanks.

**Comment by vizhur** [comment]
metadata is not exposed in v1 python sdk

**Comment by sbp-dev** [comment]
Thanks @vizhur 
Any plans for adding this feature? It'll be very helpful to track differences between environment versions, e.g. which modules were added / removed.

**Comment by vizhur** [comment]
There are no current plans to backport the feature to v1 AzureML Python SDK, feature is available for v2 https://docs.microsoft.com/en-us/azure/machine-learning/concept-v2
