### ISSUE TITLE
RunDetails Widget Freezes With Large Number of Runs

### ISSUE THREAD

**Issue by marabout2015** [Azure/MachineLearningNotebooks#181]
Description: When using RunDetails to track a HyperDrive experiment that has a large number of runs but still less than the maximum, the widget can stop updating for more than 30-40 minutes even though looking at the run in Portal shows changes every few minutes.
Environment:  Linux DSVM (Ubuntu)
Repro steps:
- Follow the set up instructions in https://github.com/Microsoft/MLBatchAIHyperparameterTuning/tree/mabou/hyperdrive
- Then run notebooks 00 through 02.
- Step through notebook 03 up to the cell that creates the "RunDetails" widget.
- Finally, uncomment the lines that create the widget, and run them.
Observed output: The widget updates until the processes start running, and then freezes for 30 or more minutes, or well after the entire HyperDrive run is done. That the run continues can be observed in Azure Portal.
Expected output: The widget updates regularly showing the same progress that can be observed in Azure Portal.
Customer impact:  The customer cannot use this very informative widget to track the progress of jobs with a large number of runs.

**Comment by archanpi** [comment]
Hi, 
The link you have pasted is broken. Can you fix the link? What's the number of runs you ran that caused this issue?

**Comment by archanpi** [comment]
I'm actively investigating this issue.

**Comment by marabout2015** [comment]
This issue appears to have been addressed in 1.0.17.
