### ISSUE TITLE
Error installing azureml-sdk in Docker

### ISSUE THREAD

**Issue by shaleenb** [Azure/MachineLearningNotebooks#1820]
I have azureml-sdk installed in my local environment with python 3.9. However, when I try to install it inside a Docker image, the installation fails.

Here is a minimal reproducible Dockerfile.

```
FROM python:3.9

RUN pip install azureml-sdk
```

I have tried downgrading to python 3.8 as well as using older versions of pip.

**Comment by jeff-shepherd** [comment]
@shaleenb I was able to successfully build the Dockerfile that you listed on a Compute Instance.
What error message did you get?

**Comment by shaleenb** [comment]
It ended up being an issue with Docker on Apple SIlicon. Adding the target platform for the base image (`FROM --platform=linux/x86_64 python:3.9`) fixed the issue for me.
