### ISSUE TITLE
regression-part2-automated-ml - OSError: dlopen(/anaconda3/envs/azenv/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6)

### ISSUE THREAD

**Issue by snowch** [Azure/MachineLearningNotebooks#187]
On OSX High Sierra, running the cell:

```
from azureml.train.automl import AutoMLConfig

# local compute 
automated_ml_config = AutoMLConfig(task = 'regression',
                             debug_log = 'automated_ml_errors.log',
                             path = project_folder,
                             X = x_train.values,
                             y = y_train.values.flatten(),
                             **automl_settings)
````

I hit this error:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-51733759cee1> in <module>
----> 1 from azureml.train.automl import AutoMLConfig
      2 
      3 # local compute
      4 automated_ml_config = AutoMLConfig(task = 'regression',
      5                              debug_log = 'automated_ml_errors.log',

/anaconda3/envs/azenv/lib/python3.6/site-packages/azureml/train/automl/__init__.py in <module>
     15 sys.path.append(vendor_folder)
     16 
---> 17 from automl.client.core.common.utilities import extract_user_data, get_sdk_dependencies
     18 
     19 from .automl import fit_pipeline

/anaconda3/envs/azenv/lib/python3.6/site-packages/azureml/train/automl/_vendor/automl/client/core/common/__init__.py in <module>
      3 """Init for standard AutoML modules."""
      4 
----> 5 from automl.client.core.common.datasets import ClientDatasets
      6 __all__ = []
      7 

/anaconda3/envs/azenv/lib/python3.6/site-packages/azureml/train/automl/_vendor/automl/client/core/common/datasets.py in <module>
     15 from sklearn import model_selection
     16 
---> 17 from automl.client.core.common import constants, problem_info, utilities
     18 from automl.client.core.common.utilities import sparse_std
     19 from automl.client.core.common._cv_splits import _CVSplits, _CVType

/anaconda3/envs/azenv/lib/python3.6/site-packages/azureml/train/automl/_vendor/automl/client/core/common/utilities.py in <module>
     18 from sklearn import model_selection
     19 
---> 20 from automl.client.core.common import constants, datasets, pipeline_spec
     21 from automl.client.core.common.constants import Metric, NumericalDtype
     22 from automl.client.core.common.exceptions import (DataException,

/anaconda3/envs/azenv/lib/python3.6/site-packages/azureml/train/automl/_vendor/automl/client/core/common/pipeline_spec.py in <module>
     13 from sklearn import linear_model, pipeline
     14 
---> 15 from automl.client.core.common import constants, model_wrappers, tf_wrappers
     16 
     17 PREPROC_NAME = 'preproc'

/anaconda3/envs/azenv/lib/python3.6/site-packages/azureml/train/automl/_vendor/automl/client/core/common/model_wrappers.py in <module>
      7 from abc import ABC, abstractmethod
      8 
----> 9 import lightgbm as lgb
     10 import numpy as np
     11 import scipy

/anaconda3/envs/azenv/lib/python3.6/site-packages/lightgbm/__init__.py in <module>
      6 from __future__ import absolute_import
      7 
----> 8 from .basic import Booster, Dataset
      9 from .callback import (early_stopping, print_evaluation, record_evaluation,
     10                        reset_parameter)

/anaconda3/envs/azenv/lib/python3.6/site-packages/lightgbm/basic.py in <module>
     32 
     33 
---> 34 _LIB = _load_lib()
     35 
     36 

/anaconda3/envs/azenv/lib/python3.6/site-packages/lightgbm/basic.py in _load_lib()
     27     if len(lib_path) == 0:
     28         return None
---> 29     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     30     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     31     return lib

/anaconda3/envs/azenv/lib/python3.6/ctypes/__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

/anaconda3/envs/azenv/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: dlopen(/anaconda3/envs/azenv/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /anaconda3/envs/azenv/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
```

**Comment by jeff-shepherd** [comment]
Did you get any errors or warnings when installing the automated machine learning libraries?
If you did, please sent the error message.

Did you use the automl_setup_mac.sh script or just pip install the libraries?
automl_setup_mac.sh includes a separate command for lightgbm:
 conda install lightgbm -c conda-forge

Do you have "Command line developer tools" installed?   If not, please try installing it.  You can use the command: xcode-select --install
and then install the automated machine learning libraries again.

**Comment by snowch** [comment]
I didn't use the automl_setup_mac.sh.  I can't recall seeing instructions to do that in the path I followed through the documentation.  IIRC the path I followed was to walk through the notebooks in this order:

- configuration.ipynb 
- tutorials/img-classification-part1-training.ipynb
- tutorials/img-classification-part2-training.ipynb
- tutorials/regression-part1-data-prep.ipynb
- tutorials/regression-part2-automated-ml.ipynb

In the pre-reqs for the last notebook, the Setup link takes you to a page that has the setup ./automl_setup_mac.sh instruction, but I think I only followed the section "Use your own Jupyter notebook server" and not "Automated ML setup".  

I don't know why I didn't follow the latter section.  Maybe this section needs to be explicitly linked to in the pre-reqs for tutorials/regression-part2-automated-ml.ipynb?  Even if I did notice that section, the note at the top may have put me off running it my notebook wasn't in that folder:

> These steps apply only to the notebooks in the automated-machine-learning folder.

**Comment by kaleko** [comment]
I have a similar issue. I am running on a local jupyter notebook server. I installed all packages via the directions:
    `pip install azureml-sdk[automl]`

Importing:
`from azureml.train.automl import AutoMLConfig`
results in

> OSError: dlopen(/anaconda3/envs/amlservices/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
>   Referenced from: /anaconda3/envs/amlservices/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
>   Reason: image not found

Please update the instructions in the [automl tutorial](https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-auto-train-models), or provide a method to remove broken models (lightgbm) from the automl routine.

**Comment by mcmchammer** [comment]
Hi, installing lightgbm from conda-forge solved the issue for me (see [here](https://github.com/Microsoft/LightGBM/issues/1369#issuecomment-465576304)).
here's my conda setup:
`conda create -n myenvir -y -q Python=3.6`
`conda activate myenvir`
`pip install "azureml-sdk[automl, notebooks]"==1.0.39`
`conda install -c conda-forge lightgbm`
