### ISSUE TITLE
source_directory_data_store description isn't helpful

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#188]
The functionality of this parameter would be to back up the content of the source_directory directory that the source_directory parameter points to. But I'm not sure in all instances if that is the case or not, so a doc update would be helpful to reflect this. Also on PyTorch and on MMLBaseEstimator.

Also, the text at the beginning of the article has :

"specified, it will be defaulted to 'dedicated'. Supported values: 'dedicated' and 'lowpriority'. This takes effect only when the vm_size param is specified in the input."
which should be the description of vm_priority and be below the definition of the class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 467fb465-3db5-bdec-c15a-4b42ba598324
* Version Independent ID: 08f6b327-dc9e-911d-adc8-535499c58ba3
* Content: [azureml.train.dnn.TensorFlow class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.tensorflow?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.TensorFlow.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.TensorFlow.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by renerocksai** [comment]
I second that. The description of `source_directory_data_store` is not very helpful at all. What does it do? How can it be used? Please clarify. Thanks!
