### ISSUE TITLE
release tag format

### ISSUE THREAD

**Issue by adrosa** [Azure/MachineLearningNotebooks#1916]
typically release tags have 3 parts eg [azureml-sdk-1.50.0](https://github.com/Azure/MachineLearningNotebooks/tree/azureml-sdk-1.50.0) but for most recent release only two parts [azureml-sdk-1.51](https://github.com/Azure/MachineLearningNotebooks/tree/azureml-sdk-1.51)

is this a new format or a typo?

**Comment by adrosa** [comment]
we are fine either way, just need to know because we have script that cares. @paulshealy1

**Comment by diondrapeck** [comment]
@adrosa Sorry about the confusion. This was a mistake that has been corrected. The x.xx.x format persists.
