### ISSUE TITLE
azureml-dataset-runtime is not available on pypi as source distribution and is missing conda packaging 

### ISSUE THREAD

**Issue by rxm7706** [Azure/MachineLearningNotebooks#1925]
[Enter feedback here]

PyPi Distribution is not Uploading Source Distribution and is also not packaged as conda. 

https://pypi.org/project/azureml-dataset-runtime/#files

See example of azure-ai-ml  That has both Conda & source distribution 
https://anaconda.org/microsoft/azure-ai-ml/
https://pypi.org/project/azure-ai-ml/#files

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0e41adb-e207-3c99-7c3c-afee3cb4fed5
* Version Independent ID: 9be835d1-df2c-a865-08ee-b29cb6849240
* Content: [azureml.core.dataset module - Azure Machine Learning Python](https://learn.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.dataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.dataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @DebFro
* Microsoft Alias: **debfro**

**Comment by rxm7706** [comment]
Hi - this is closed with a comment or resolution ?

**Comment by vizhur** [comment]
AzureML Python SDK is available only from PyPI as whl.
