### ISSUE TITLE
azureml-pipeline-steps issue

### ISSUE THREAD

**Issue by WenjuanOlympus** [Azure/MachineLearningNotebooks#1931]
Hello,

I installed azureml-pipeline-steps==1.52.0 to deploy my pipeline from github actions to azure ml studio pipeline. This package has dependency on dotnetcore2<4.0.0,>=3.0.0, then dotnetcore2==3.1.23 was installed.  

ubuntu==22.04

python==3.8

I installed different version combination of dotnet-sdk, dotnet-runtime, still can't solve the error below:

Missing packages: {'liblttng-ust.so.0'}

NET Core 3.1 can still be used via `dotnetcore2` if the required dependencies are installed.

Visit https://aka.ms/dotnet-install-linux for Linux distro specific .NET Core install instructions.

Follow your distro specific instructions to install `dotnet-runtime-*` and replace `*` with `3.1.23`.

Any help will be appreciated.

**Comment by lumamachiron** [comment]
same here

**Comment by WenjuanOlympus** [comment]
Solved ubuntu==20.04
sudo apt -y install libssl-dev zlib1g-dev build-essential libffi-dev libsqlite3-dev
pip3 install pip-tools==7.0.0
without the need to install dotnet-runtime
