### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by jakedubb** [Azure/MachineLearningNotebooks#194]
Getting the following error when trying to start ACI service.  When running notebook "train-within-notebook"

Container definition:
```
from azureml.core.conda_dependencies import CondaDependencies 
from azureml.core.image import ContainerImage

# Create an empty conda environment and add the scikit-learn package
env = CondaDependencies()
env.add_conda_package("scikit-learn")
env.add_conda_package("numpy")

# Display the environment
print(env.serialize_to_string())

# Write the environment to disk
with open("myenv.yml","w") as f:
    f.write(env.serialize_to_string())

# Create a configuration object indicating how our deployment container needs to be created
image_config = ContainerImage.image_configuration(execution_script="score.py", 
                                    runtime="python", 
                                    conda_file="myenv.yml")

```

```
> > # Conda environment specification. The dependencies defined in this file will
> > # be automatically provisioned for runs with userManagedDependencies=False.
> > 
> > # Details about the Conda environment file format:
> > # https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually
> > 
> > name: project_environment
> > dependencies:
> >   # The python interpreter version.
> >   # Currently Azure ML only supports 3.5.2 and later.
> > - python=3.6.2
> > 
> > - pip:
> >     # Required packages for AzureML execution, history, and data preparation.
> >   - azureml-defaults
> > - scikit-learn
> > - numpy
> > 
> 
```

Deploy Code:
```
%%time
from azureml.core.webservice import Webservice

# Create the webservice using all of the precreated configurations and our best model
service = Webservice.deploy_from_model(name='my-aci-svc',
                                       deployment_config=aciconfig,
                                       models=[model],
                                       image_config=image_config,
                                       workspace=ws)

# Wait for the service deployment to complete while displaying log output
service.wait_for_deployment(show_output=True)
```

```
> Creating image
> Image creation operation finished for image my-aci-svc:4, operation "Succeeded"
> Creating service
> Running.........................
> FailedACI service creation operation finished, operation "Failed"
> Service creation polling reached terminal state, current service state: Unhealthy
> {
>   "code": "AciDeploymentFailed",
>   "message": "Aci Deployment failed",
>   "details": [
>     {
>       "code": "CrashLoopBackOff",
>       "message": "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance my-aci-svc.\nYou can also try to run image wu2modtimesmls5288786732.azurecr.io/my-aci-svc:4 locally. Please refer to http://aka.ms/debugimage for more information."
>     }
>   ]
> }
> Wall time: 6min 46s
```

Service log:
`print(service.get_logs())`

```
> 2019-02-01T07:06:49,496028169+00:00 - nginx/run 
> 2019-02-01T07:06:49,496746186+00:00 - rsyslog/run 
> 2019-02-01T07:06:49,500812486+00:00 - gunicorn/run 
> ok: run: rsyslog: (pid 14) 0s
> 2019-02-01T07:06:49,497672009+00:00 - iot-server/run 
> ok: run: rsyslog: (pid 14) 0s
> ok: run: gunicorn: (pid 16) 0s
> ok: run: nginx: (pid 13) 0s
> ok: run: rsyslog: (pid 14) 0s
> EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
> 2019-02-01T07:06:49,632180319+00:00 - iot-server/finish 1 0
> 2019-02-01T07:06:49,633751558+00:00 - Exit code 1 is normal. Not restarting iot-server.
> {"timestamp": "2019-02-01T07:06:49.913589Z", "message": "Starting gunicorn 19.6.0", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Starting gunicorn %s", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:49.914430Z", "message": "Listening at: http://127.0.0.1:9090 (16)", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Listening at: %s (%s)", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:49.914538Z", "message": "Using worker: sync", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Using worker: %s", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:49.915289Z", "message": "worker timeout is set to 300", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:49.916372Z", "message": "Booting worker with pid: 40", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Booting worker with pid: %s", "stack_info": null}
> Initializing logger
> {"timestamp": "2019-02-01T07:06:53.374061Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Starting up app insights client\", \"apiName\": \"\"}", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.374292Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Starting up request id generator\", \"apiName\": \"\"}", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.374397Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Starting up app insight hooks\", \"apiName\": \"\"}", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.374497Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Invoking user's init function\", \"apiName\": \"\"}", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
> 2019-02-01 07:06:53,375 | azureml.core.run | DEBUG | Could not load run context Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run., switching offline: False
> 2019-02-01 07:06:53,375 | azureml.core.run | DEBUG | Could not load the run context and allow_offline set to False
> 2019-02-01 07:06:53,375 | azureml.core.model | DEBUG | RunEnvironmentException: Failed to load a submitted run, if outside of an execution context, use project.start_run to initialize an azureml.core.Run.
> 2019-02-01 07:06:53,375 | azureml.core.model | DEBUG | version is None. Latest version is 1
> 2019-02-01 07:06:53,375 | azureml.core.model | DEBUG | Found model path at azureml-models/best_model/1/model.pkl
> {"timestamp": "2019-02-01T07:06:53.376512Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"User's init function failed\", \"apiName\": \"\"}", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "ERROR", "logger": "root", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.377417Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Encountered Exception Traceback (most recent call last):\\n  File \\\"/var/azureml-app/aml_blueprint.py\\\", line 109, in register\\n    main.init()\\n  File \\\"/var/azureml-app/main.py\\\", line 87, in init\\n    driver_module.init()\\n  File \\\"score.py\\\", line 15, in init\\n    model = joblib.load(model_path)\\n  File \\\"/opt/miniconda/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py\\\", line 598, in load\\n    obj = _unpickle(fobj, filename, mmap_mode)\\n  File \\\"/opt/miniconda/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py\\\", line 526, in _unpickle\\n    obj = unpickler.load()\\n  File \\\"/opt/miniconda/lib/python3.6/pickle.py\\\", line 1050, in load\\n    dispatch[key[0]](self)\\n  File \\\"/opt/miniconda/lib/python3.6/pickle.py\\\", line 1338, in load_global\\n    klass = self.find_class(module, name)\\n  File \\\"/opt/miniconda/lib/python3.6/pickle.py\\\", line 1388, in find_class\\n    __import__(module, level=0)\\nModuleNotFoundError: No module named 'numpy.core._multiarray_umath'\\n\", \"apiName\": \"\"}", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "ERROR", "logger": "root", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.377589Z", "message": "Worker exiting (pid: 40)", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Worker exiting (pid: %s)", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.518551Z", "message": "Shutting down: Master", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Shutting down: %s", "stack_info": null}
> {"timestamp": "2019-02-01T07:06:53.518879Z", "message": "Reason: Worker failed to boot.", "host": "wk-caas-24cb4b95da73495e891fe3cb7f5f0c60-ff51522df14e7fbf80152d", "path": "/opt/miniconda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Reason: %s", "stack_info": null}
> 2019-02-01T07:06:53,544267082+00:00 - gunicorn/finish 3 0
> 2019-02-01T07:06:53,545528713+00:00 - Exit code 3 is not normal. Killing image.
> 
```

**Comment by jakedubb** [comment]
>pip show numpy
Name: numpy
Version: 1.16.0
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\jacwang\envs\venv\lib\site-packages
Requires:
Required-by: tensorflow, tensorboard, sklearn-pandas, scipy, pandas, matplotlib, lightgbm, Keras-Preprocessing, Keras-Applications, h5py, azureml-train-automl, azureml-dataprep

>pip show scikit-learn
Name: scikit-learn
Version: 0.19.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: Andreas Mueller
Author-email: amueller@ais.uni-bonn.de
License: new BSD
Location: c:\users\jacwang\envs\venv\lib\site-packages
Requires:
Required-by: sklearn-pandas, lightgbm, azureml-train-automl

**Comment by rastala** [comment]
Looks like they're behind the latest versions which get installed when the web service is deployed. Maybe this causes incompatibility. You could try specifing exact versions in your conda dependencies file:

- pip:
    # Required packages for AzureML execution, history, and data preparation.
    - azureml-defaults
- scikit-learn=0.19.1
- numpy=1.16.0

**Comment by jakedubb** [comment]
I've updated my conda dependencies to include the version numbers:

```
Name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
- scikit-learn=0.19.1
- numpy=1.16.0
```

Now it's failing on the build of the image:

Runtime is python-slim
Creating resource directory
Downloading main file
Dependency is an artifact: https://westus2.experiments.azureml.net/artifact/v1.0/subscriptions/7fd76d0f-84f2-498b-a997-e0d059af5ce1/resourceGroups/wu2modtimerg/providers/Microsoft.MachineLearningServices/workspaces/wu2modtimesmlsw/artifacts/contentinfo/LocalUpload/321a1e72/tmp692ujkrw.py
Getting artifact SAS URL(s)
Getting artifact SAS URL(s) took 0.049996137619018555 seconds.
Artifact resolved to 1 URLs
Trying to download https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/LocalUpload/321a1e72/tmp692ujkrw.py?sv=2018-03-28&sr=b&sig=3nZ%2BoKaVsHGUx%2FOJs2zhI2K8ZO0u7hzIz%2Bav82fRCeM%3D&st=2019-02-01T18%3A24%3A01Z&se=2019-02-02T02%3A34%3A01Z&sp=r as main.py
downloading using http get
HTTP GET took 0.1173698902130127 seconds.
Saving config file
parsing the dependency list
validate and download dependencies
Dependency is an artifact: https://westus2.experiments.azureml.net/artifact/v1.0/subscriptions/7fd76d0f-84f2-498b-a997-e0d059af5ce1/resourceGroups/wu2modtimerg/providers/Microsoft.MachineLearningServices/workspaces/wu2modtimesmlsw/artifacts/contentinfo/LocalUpload/d432df82/f9ab6809.tar.gz
Getting artifact SAS URL(s)
Getting artifact SAS URL(s) took 0.04328799247741699 seconds.
Artifact resolved to 1 URLs
Dependency is to be unpacked
Trying to download https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/LocalUpload/d432df82/f9ab6809.tar.gz?sv=2018-03-28&sr=b&sig=Qs25H%2FxdqjhfEcxXOo5W8OvSUQZ1b4BRByzvg%2BXtcps%3D&st=2019-02-01T18%3A24%3A01Z&se=2019-02-02T02%3A34%3A01Z&sp=r as f9ab6809.tar.gz
downloading using http get
HTTP GET took 0.018114805221557617 seconds.
Compressed dependency downloaded to /mnt/batch/tasks/workitems/wu2modtimesmls5288786732_0f3d15174fb54977a9dd433ac77dab51/job-1/ice_task/wd/resources/f9ab6809.tar.gz
Dependency is a .tar so it will be extracted in place before copying to the Docker image
Dependency is an artifact: https://westus2.experiments.azureml.net/artifact/v1.0/subscriptions/7fd76d0f-84f2-498b-a997-e0d059af5ce1/resourceGroups/wu2modtimerg/providers/Microsoft.MachineLearningServices/workspaces/wu2modtimesmlsw/artifacts/contentinfo/LocalUpload/dda091c3/d741bc63.tar.gz
Getting artifact SAS URL(s)
Getting artifact SAS URL(s) took 0.04628920555114746 seconds.
Artifact resolved to 1 URLs
Dependency is to be unpacked
Trying to download https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/LocalUpload/dda091c3/d741bc63.tar.gz?sv=2018-03-28&sr=b&sig=134pHRTAcrjP5YfRxVsSTCqZp56kc8XRnAU4r5mVTAc%3D&st=2019-02-01T18%3A24%3A01Z&se=2019-02-02T02%3A34%3A01Z&sp=r as d741bc63.tar.gz
downloading using http get
HTTP GET took 0.0431673526763916 seconds.
Compressed dependency downloaded to /mnt/batch/tasks/workitems/wu2modtimesmls5288786732_0f3d15174fb54977a9dd433ac77dab51/job-1/ice_task/wd/resources/d741bc63.tar.gz
Dependency is a .tar so it will be extracted in place before copying to the Docker image
Dependency is an artifact: https://westus2.experiments.azureml.net/artifact/v1.0/subscriptions/7fd76d0f-84f2-498b-a997-e0d059af5ce1/resourceGroups/wu2modtimerg/providers/Microsoft.MachineLearningServices/workspaces/wu2modtimesmlsw/artifacts/prefix/contentinfo/ExperimentRun/dcid.8e0239f8-d640-47fc-9300-edc528ed277e/outputs/model.pkl
Getting artifact SAS URL(s)
Getting artifact SAS URL(s) took 0.05047965049743652 seconds.
Artifact resolved to 1 URLs
Trying to download https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.8e0239f8-d640-47fc-9300-edc528ed277e/outputs/model.pkl?sv=2018-03-28&sr=b&sig=5f8Z6E8EJEzJaUw2vozYia61Qa9FxZxibJYAACvCq%2Bw%3D&st=2019-02-01T18%3A24%3A01Z&se=2019-02-02T02%3A34%3A01Z&sp=r as model.pkl
downloading using http get
HTTP GET took 0.0410003662109375 seconds.
Processing dependency: https://modelmgmtwestus2.blob.core.windows.net/c670c054-b8d7-49d7-904e-74be5072fd6d/model_config_map.json
Trying to download https://modelmgmtwestus2.blob.core.windows.net/c670c054-b8d7-49d7-904e-74be5072fd6d/model_config_map.json?sv=2017-04-17&sr=b&sig=b1u%2FOPWBKT3n5fdOThxczKYCqtg4uBbdPF1suGuM%2F70%3D&st=2019-02-01T18%3A28%3A48Z&se=2020-02-01T18%3A33%3A48Z&sp=r as model_config_map.json
downloading using http get
HTTP GET took 0.11247849464416504 seconds.
Dependency download took: 0.5501835346221924 s
Checking to see if CUDA is requested and modifying Dockerfile accordingly
Checking to see if requirements.txt exists and modifying Dockerfile accordingly
pip requirements file found
Dependency is an artifact: https://westus2.experiments.azureml.net/artifact/v1.0/subscriptions/7fd76d0f-84f2-498b-a997-e0d059af5ce1/resourceGroups/wu2modtimerg/providers/Microsoft.MachineLearningServices/workspaces/wu2modtimesmlsw/artifacts/contentinfo/LocalUpload/b674395d/requirementsn2tz8dgb.txt
Getting artifact SAS URL(s)
Getting artifact SAS URL(s) took 0.04359698295593262 seconds.
Artifact resolved to 1 URLs
Trying to download https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/LocalUpload/b674395d/requirementsn2tz8dgb.txt?sv=2018-03-28&sr=b&sig=9d%2F7dnCs2HiughUG2AU42ozeuEa8lLJO4BVj7A3e6SU%3D&st=2019-02-01T18%3A24%3A01Z&se=2019-02-02T02%3A34%3A01Z&sp=r as requirements.txt
downloading using http get
HTTP GET took 0.03061699867248535 seconds.
editing dockerfile to put in pip requirements
Checking to see if conda env file exists and modifying Dockerfile accordingly
Conda env file found
Dependency is an artifact: https://westus2.experiments.azureml.net/artifact/v1.0/subscriptions/7fd76d0f-84f2-498b-a997-e0d059af5ce1/resourceGroups/wu2modtimerg/providers/Microsoft.MachineLearningServices/workspaces/wu2modtimesmlsw/artifacts/contentinfo/LocalUpload/8d4db045/myenv.yml
Getting artifact SAS URL(s)
Getting artifact SAS URL(s) took 0.03841376304626465 seconds.
Artifact resolved to 1 URLs
Trying to download https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/LocalUpload/8d4db045/myenv.yml?sv=2018-03-28&sr=b&sig=hU6HXZQSmSgV%2BEexAD%2Ff0tVHmIuIuCbsRpnfXn8bg1s%3D&st=2019-02-01T18%3A24%3A01Z&se=2019-02-02T02%3A34%3A01Z&sp=r as env.yml
downloading using http get
HTTP GET took 0.09092521667480469 seconds.
sanitizing conda env file
dependencies:
- pip:
  - azureml-defaults
- scikit-learn=0.19.1
- numpy=1.16.0
- pip=9

editing dockerfile to put in conda env file
Checking to see if docker steps file exists and modifying Dockerfile accordingly
Building image with name wu2modtimesmls5288786732.azurecr.io/my-aci-svc:6
Sending build context to Docker daemon  219.6kB

Step 1/5 : FROM iceacrwestus2.azurecr.io/python-slim-base-image:20190108210051
 ---> c8f028605e33
Step 2/5 : COPY resources /var/azureml-app
 ---> 0e406e6acb60
Step 3/5 : RUN conda env update --name=base -f /var/azureml-app/env.yml && conda clean -aqy && rm -rf /root/.cache/pip && rm -rf /opt/miniconda/pkgs && find /opt/miniconda -type d -name __pycache__ -exec rm -rf {} +
 ---> Running in 9e78f1533460
Solving environment: ...working... failed
[91m
ResolvePackageNotFound: 
  - numpy=1.16.0

[0mDocker image build failed
Removing any dangling images
The command '/bin/sh -c conda env update --name=base -f /var/azureml-app/env.yml && conda clean -aqy && rm -rf /root/.cache/pip && rm -rf /opt/miniconda/pkgs && find /opt/miniconda -type d -name __pycache__ -exec rm -rf {} +' returned a non-zero code: 1
Deleted: sha256:0e406e6acb60a77963a5034ad4b2437bd2a2803d5de3e0144ec68801590383c4
Docker image build took: 12.971733093261719
Pruning docker cache
Deleted Containers:
9e78f153346067947cd0ee7910477f1111b41b94e5681f25c0cda1c74b116752

Total reclaimed space: 36.92MB
Docker pruning took: 1.0942134857177734 s
Removing dependencies
script done and exiting
Total Time: 14.61681580543518 s

**Comment by jakedubb** [comment]
Fixed!!

Had to add the following to the conda dependencies in the tutorial:
```
from azureml.core.conda_dependencies import CondaDependencies 
from azureml.core.image import ContainerImage

# Create an empty conda environment and add the scikit-learn package
env = CondaDependencies()
env.add_pip_package("scikit-learn==0.19.1")
env.add_pip_package("numpy==1.16.0")
env.add_pip_package("scipy")
env.add_pip_package("matplotlib")

# Display the environment
print(env.serialize_to_string())

# Write the environment to disk
with open("myenv.yml","w") as f:
    f.write(env.serialize_to_string())

# Create a configuration object indicating how our deployment container needs to be created
image_config = ContainerImage.image_configuration(execution_script="score.py", 
                                    runtime="python", 
                                    conda_file="myenv.yml")
```

```
# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - scikit-learn==0.19.1
  - numpy==1.16.0
  - scipy
  - matplotlib
```
