### ISSUE TITLE
HttpOperationError Received 500 from a service request when logging images

### ISSUE THREAD

**Issue by lmccoy1** [Azure/MachineLearningNotebooks#200]
I have tried to log matplotlib.pyplot objects to the run record following [this example](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/logging-api/logging-api.ipynb).

When I run the following line of code:
`run.log_image(name='Hyperbolic Tangent', plot = plt)`

I get this error:
HttpOperationError: Operation returned an invalid status code 'Received 500 from a service request'

**Comment by hning86** [comment]
Can you try a different name? This is probably a bug where we don't throw proper error message when you log a image with an existing name under the same run.

**Comment by lmccoy1** [comment]
The problem was related to an old workspace I created a few months ago. I have created a new machine learning workspace and logged the image to the new workspace successfully. Thank you for your response.
