### ISSUE TITLE
Conda dependency yml

### ISSUE THREAD

**Issue by zackdrescher** [Azure/MachineLearningNotebooks#201]
what is the best way to configure an estimator environment from a conda dependency yml? Looks like you need to parse the file yourself and feed it to `conda_packages` and `pip_packages`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c6df68-5739-e8db-1acb-38f5a504ce7c
* Version Independent ID: b9664417-0785-378c-c082-5e63bd1b3f6a
* Content: [azureml.train.estimator.Estimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.estimator?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by aashishb** [comment]
Tagging @hning86 to help

**Comment by swanderz** [comment]
See my comment on #202

**Comment by hning86** [comment]
you can load an existing conda.yml file and rehydrate it into a conda dependency object:

cd = CondaDependencies(conda_dependencies_file_path='env.yml')

you can create a run configuration object with this cd object.
you can then pass the environment property of the run config object to the estimator constructor's environment definition parameter.
