### ISSUE TITLE
conda_packages argument failing 

### ISSUE THREAD

**Issue by zackdrescher** [Azure/MachineLearningNotebooks#202]
Leverage a conda environment yml I parsed into a list of dependencies, the Esitmator arguement is failing on 'python=3.6.8=h9f7ef89_0'. it doesnt appear to be able to properly parse the version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c6df68-5739-e8db-1acb-38f5a504ce7c
* Version Independent ID: b9664417-0785-378c-c082-5e63bd1b3f6a
* Content: [azureml.train.estimator.Estimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.estimator?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by aashishb** [comment]
Tagging @hning86

**Comment by swanderz** [comment]
@hning86, I have similar issues to @zackdrescher in that I can't build specify an environment as part of a run config file. I only get it to work when explicitly passing packages to `conda_packages` or `pip_packages` argument. Here is a link to both of those scenarios along with the `.runconfig` and `conda_dependencies.yml`

https://gist.github.com/swanderz/2551e8fcf36dcd3426b15915e4652757

**Comment by hning86** [comment]
you can load an existing conda.yml file and rehydrate it into a conda dependency object:

cd = CondaDependencies(conda_dependencies_file_path='env.yml')

**Comment by hning86** [comment]
also, @zackdrescher, it should probably be "python=3.6.8**-**h9f7ef89_0"

**Comment by zackdrescher** [comment]
Thanks for the help. I talked with some others at microsoft and i think we had been a little to litteral with our dependency management. We have since started useing the CondaDependencies object and it seems to be working.
