### ISSUE TITLE
AutoML: Pre-processing steps of LightGBM-related pipelines are unnecessary

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#204]
@chaoqian correct me if I am wrong, but I believe that the existing AutoML pipelines are doing uneccessary pre-processing steps when it comes to tree-based models

I'm requesting that the LightGBM (and other tree-based-model pipelines) be modified to not use any scaling pre-processing (provided there are no categorical features)
My rationale: [Tree-based models are not affected by scaling of quantitative features](https://datascience.stackexchange.com/questions/6721/how-to-preprocess-different-kinds-of-data-continuous-discrete-categorical-be)
Also, it might be worth allowing categorical features sent AutoML to be processed without a one-hot encoding first in the case of LightGBM. [LightGBM treats categorical features differently](https://lightgbm.readthedocs.io/en/latest/Features.html#optimal-split-for-categorical-features)

Some context on this issue:
@ggupta2005 informed me in #135 that there is pre-processing happening that is out of my control. in #133 I was trying to work around this issue.

**Comment by nagau** [comment]
@swanderz  Thanks for your comments. Some of the preprocessors can be beneficial for tree based learners as well. We have plans to optimize the preprocessors needed within a pipeline, as well as handle categorical data in optimal manner for tree based learners in future releases.

**Comment by swanderz** [comment]
Great to hear. Thanks @nagau
