### ISSUE TITLE
multi-step or multi-target regression or forecasting in automl

### ISSUE THREAD

**Issue by GlennCeusters** [Azure/MachineLearningNotebooks#211]
Does multi-step or multi-target regression or forecasting supported in this automl package?
Or should we, as of now, run an experiment for every target individually (e.g. t+1, t+2, t+3, ...) and then wrap them together?

Cheers,
/Glenn

**Comment by GlennCeusters** [comment]
I've done some experimentation myself and found out that this is indeed not supported (only for classification? as this is mentioned in the documentation). 

One way forward could be the white-list only MIMO algo's (like random forests, neural nets, ...) - and then not only allow for [n x 1] inputs of course.

Another (more resource intensive) way could be the different wrapper strategies like also available in sklearn (MultiOutputRegressor, RegressionChain).

**Comment by singliar** [comment]
Hi Glenn,

we currently don't have plans for multi-output regression. Wrapper strategies are a good way to go for now.

For forecasting, the natural multi-output arrangement is to make predictions of the same variable (e.g. "quantity sold") for every forecast horizon out to the maximum for which the model was trained. You can do this by constructing the corresponding grain and time index in the X_test input data frame, and you will get back all the values you so requested. 

We do not currently support making jointly multivariate predictions (e.g. "predict price AND quantity sold"). More thought needs to go to the questions of causality, and consequently how to arrange the regressor chain.

Tomas
