### ISSUE TITLE
References to Azure Batch AI

### ISSUE THREAD

**Issue by vapaunic** [Azure/MachineLearningNotebooks#213]
This document makes multiple references to Azure Batch AI. Should this be changed to AML Compute?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728ca4df-c476-164d-dc8b-48c52d4c916f
* Version Independent ID: 09d15b88-5b3e-a7e0-7a15-001c1e8b667d
* Content: [azureml.core.runconfig.RunConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-core/azureml.core.runconfig.runconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.runconfig.RunConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.runconfig.RunConfiguration.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by hning86** [comment]
Yes good point. We will fix this.
