### ISSUE TITLE
access to Azure ML workspace

### ISSUE THREAD

**Issue by mohaissa** [Azure/MachineLearningNotebooks#215]
Since 28/01/2019 I am not able to  access my Azureml ws as befor and i get the error:
from azureml.core import Workspace

ws = Workspace.create(name = workspace_name,
                      subscription_id = subscription_id,
                      resource_group = resource_group, 
                      location = workspace_region,
                      auth = auth,
                      exist_ok=True)

output:
Falling back to use azure cli credentials. This fall back to use azure cli credentials will be removed in the next release. 
Make sure your code doesn't require 'az login' to have happened before using azureml-sdk, except the case when you are specifying AzureCliAuthentication in azureml-sdk.
Performing interactive authentication. Please follow the instructions on the terminal.
From cffi callback <function _verify_callback at 0x7ff8d016ae18>:
Traceback (most recent call last):
  File "/databricks/python/lib/python3.5/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'

**Comment by mohaissa** [comment]
[Doc1.pdf](https://github.com/Azure/MachineLearningNotebooks/files/2865631/Doc1.pdf)

**Comment by hning86** [comment]
how did you construct your "auth" object? 

also, what happens if you remove the "auth" parameter from the constructor? (you should be able to do device-login following on-screen instruction).

**Comment by mohaissa** [comment]
subscription_id = "exxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx31"
resource_group = "Analytics"
workspace_name = "ml-service" 
workspace_region = "Est des États-Unis"

**Comment by mohaissa** [comment]
Sorry on my code I did not use the ''auth'',
![image](https://user-images.githubusercontent.com/29986627/52816330-041ca500-306f-11e9-8935-ef45789d580d.png)

**Comment by mohaissa** [comment]
Hi Hai,
As you know, there are two ways to access  WS from Databricks:
•	The first is with credentials as you mentioned in your tutorial, and this is the way I've been using  since the beginning.
•	The second way by using config.json file as  on in your tutorial for using  Jyputer Notebook and I tried this method for Databricks when the first did not work  And I failed to connect.

As you could see on the screenprint, I am not able to acess anymore, could you help with that please
Thanks

![image](https://user-images.githubusercontent.com/29986627/52861796-966d8900-3101-11e9-8a20-480685cd4e81.png)

**Comment by hning86** [comment]
pls make sure you follow the instruction here.
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment#azure-databricks

**Comment by mohaissa** [comment]
Hi Hai,
First thanks for you answer, I am relying on you to resoulve this issus. I check evru credentile  evry thing look  correct.
This is not the first time I access to the WS from DB, I have no problem since September 2018 and I have advance in my project until the part of deployment. 
but since January 28, 2019 I can not connect,
 I'm really stuck
![image](https://user-images.githubusercontent.com/29986627/52878907-d184b200-312b-11e9-83bf-df36bd037b26.png)

**Comment by hning86** [comment]
did you set the ADB cluster exactly following the instruction? can you try create a new cluster and install azureml-sdk[databricks] and see if that works?

**Comment by mohaissa** [comment]
Hi Hai,
Yes sir I set the ADB cluster exactly following the instruction.
FYI, the access work fine before, just ask me to sign in, at https://microsoft.com/devicelogin and enter the code EXXXXX for authenticate. But since two weeks I am unable to access ,so I tryed a lot of thing like:
- Change the cluster several times
- Change the DB version (lower then 5.2)
- Create a new  DB instance  
- Create a new Azure WS
- Put DB and Azur WS on the same work space region
All that doesn't work, I  have a ticket with Microsoft support  (119021324001427)but look like no body knows how to resolve this issue.
Thanks

**Comment by hning86** [comment]
try forcing an interactive log in:
```python
from azureml.core.authentication import InteractiveLoginAuthentication
interactive_auth = InteractiveLoginAuthentication()
ws = Workspace.get(subscription_id="my-subscription-id",
               resource_group="my-ml-rg",
               workspace_name="my-ml-workspace",
               auth=interactive_auth)
```

**Comment by mohaissa** [comment]
Hi Hai,
![image](https://user-images.githubusercontent.com/29986627/53022797-edd56700-3429-11e9-9d5e-a09832a1e872.png)

**Comment by vizhur** [comment]
Hello @mohaissa ,

Please 
1. recreate a cluster
2. install azureml-sdk[databricks]

**Comment by adyada** [comment]
Hello @mohaissa ,
Either you can do what the above comment says that is to delete and recreate the adb cluster or if you want to use the same cluster then the following might help in resolving the issue.

1) Remove all the libraries that you have attached to the adb cluster including azureml-sdk or any other libraries.
2) Restart the cluster.
3) On restarting perform a "pip freeze" and if possible post that result here. 
4) Attach azureml-sdk[databricks] library.

My guess is that you might have attached some other library apart from azureml-sdk[databricks] that broke the databricks python environment. 

Please let us know if this works or not.

**Comment by mohaissa** [comment]
Thank you for your help Guys
 I created a new databricks instance, a new cluster and  azureml-sdk library, I still have the same isue,see the images below:
![image](https://user-images.githubusercontent.com/29986627/53268994-ad8a1900-36b5-11e9-9c39-704f36840e57.png)
![image](https://user-images.githubusercontent.com/29986627/53269043-d01c3200-36b5-11e9-8a11-8b0169c22244.png)
![image](https://user-images.githubusercontent.com/29986627/53269097-fd68e000-36b5-11e9-88d1-95fbb3fad73b.png)
![image](https://user-images.githubusercontent.com/29986627/53269345-9dbf0480-36b6-11e9-8e61-ea9b148f9c43.png)
![image](https://user-images.githubusercontent.com/29986627/53269388-bd562d00-36b6-11e9-9399-1df0d43f5595.png)

**Comment by adyada** [comment]
Did you add azureml-sdk or azureml-sdk[databricks] as the library?  You will need to add azureml-sdk[databricks] as the library, this has some version pinnings that are needed for databricks.  In your pip freeze I don't see azureml-sdk. Can you please try "!pip freeze"

**Comment by mohaissa** [comment]
But there is no azureml-sdk[databricks] on PyPi
pip install azureml-sdk[databricks]
Collecting azureml-sdk[databricks]
  Could not find a version that satisfies the requirement azureml-sdk[databricks] (from versions: )
No matching distribution found for azureml-sdk[databricks]

**Comment by vizhur** [comment]
@mohaissa 

There is definitely azureml-sdk on PyPI. 
https://pypi.org/project/azureml-sdk/

databricks just an extra on the package that would bring some packages that databricks environment require. Please try again to install azureml-sdk[databricks]

you can check that extra == 'databricks' is here: https://pypi.org/pypi/azureml-sdk/json

**Comment by artsheiko** [comment]
Same issue, even for Workspace.create(). Neither version azureml-core 1.0.10 nor 1.0.15 doesn't work

![image](https://user-images.githubusercontent.com/16267961/53299107-a0486800-3836-11e9-8c11-15dc9efcb731.png)

**Comment by artsheiko** [comment]
I hit the same issue on my local computer. After numerous permutations of trying to accomplish the auth to AzureML Service I found a solution. You need to open your cmd, execute "az login", login to your account using a provided link, execute "az logout" and than use Workspace.create() or Workspace.get()

**Comment by artsheiko** [comment]
But on Azure Databricks we need another solution. After I installed azure-cli :
%sh
pip install azure-cli
And I performed az login, az logout, az login I obtain the next exception : 
![image](https://user-images.githubusercontent.com/16267961/53304623-af033f00-3877-11e9-840a-29021e861cdb.png)

**Comment by artsheiko** [comment]
> @mohaissa
> 
> **Could not find a version that satisfies the requirement azureml-sdk[databricks] (from versions: )** is actually strange as it should look for azureml-sdk, so there might be smth's wrong with the databricks. You can earlier databricks runtime versions
> 
> There is definitely azureml-sdk on PyPI.
> https://pypi.org/project/azureml-sdk/
> 
> databricks just an extra on the package that would bring some packages that databricks environment require.
> 
> you can check that extra == 'databricks' is here: https://pypi.org/pypi/azureml-sdk/json

As @mohaissa sad, pip install azureml-sdk gets "Could not find a version that satisfies the requirement azureml-sdk" cuz pip here is pip for python 2. So, we need to install pip3. Ok, no problem : 
%sh
apt-get install -y python3-pip

After that, we install azureml-sdk : pip3 install azureml-sdk
So, here pip3 freeze command : 
adal==1.2.1
applicationinsights==0.11.7
asn1crypto==0.24.0
azure-common==1.1.18
azure-graphrbac==0.53.0
azure-mgmt-authorization==0.51.1
azure-mgmt-containerregistry==2.7.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==2.1.0
azure-mgmt-storage==3.1.1
azure-nspkg==3.0.2
azure-storage-blob==1.5.0
azure-storage-common==1.4.0
azure-storage-nspkg==3.1.0
azureml-core==1.0.15
azureml-pipeline==1.0.15
azureml-pipeline-core==1.0.15
azureml-pipeline-steps==1.0.15
azureml-sdk==1.0.15.1
azureml-telemetry==1.0.15
azureml-train==1.0.15
azureml-train-core==1.0.15
azureml-train-restclients-hyperdrive==1.0.15
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.6
certifi==2018.11.29
cffi==1.12.1
chardet==3.0.4
colorama==0.4.1
contextlib2==0.5.5
cryptography==2.5
docker==3.7.0
docker-pycreds==0.4.0
idna==2.8
isodate==0.6.0
jmespath==0.9.3
jsonpickle==1.1
msrest==0.6.4
msrestazure==0.6.0
ndg-httpsclient==0.5.1
oauthlib==3.0.1
paramiko==2.4.2
pathspec==0.5.9
pyasn1==0.4.5
pycparser==2.19
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.7.1
PyNaCl==1.3.0
pyOpenSSL==19.0.0
python-apt==1.1.0b1+ubuntu0.16.4.1
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
ruamel.yaml==0.15.51
SecretStorage==2.3.1
six==1.12.0
ssh-import-id==5.5
unattended-upgrades==0.1
urllib3==1.23
virtualenv==15.0.1
websocket-client==0.55.0

The issue "Falling back to use azure cli credentials. This fall back to use azure cli credentials will be removed in the next release." is still present

**Comment by artsheiko** [comment]
Same issue on StackOverflow : https://stackoverflow.com/questions/54640854/login-to-azure-ml-workspace-from-azure-databricks-notebook

**Comment by artsheiko** [comment]
You need to install azureml-sdk[databricks] library on your cluster. Not azureml-sdk, but azureml-sdk[databricks] : http://prntscr.com/mpk05g

**Comment by mohaissa** [comment]
Not able to install it,
![image](https://user-images.githubusercontent.com/29986627/53345145-3be2e280-38e2-11e9-9da7-7b3c967625f9.png)

**Comment by mohaissa** [comment]
Hi @hning86 
On your example (how-to-use-azureml/) Databricks, you just  call azureml.core,
What is the difference btw azureml.core and azureml-sdk.
thanks

**Comment by vizhur** [comment]
@mohaissa 

please install **azureml-sdk[datatabricks]**, not azureml-sdk or azureml-sdk=='databricks'. 

AzureML SDK is a set of 20+ packages that provide different features. In order to make it clear and simple for a user there is a metapackage called azureml-sdk. By default it will bring you core functionality and some of the features. You can customize your install by installing separate packages or providing extras on the azureml-sdk, like databricks, automl, notebooks, etc. 
here you can find more information
https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py

**Comment by artsheiko** [comment]
On my opinion, there is some issue with a library : why azureml-sdk cannot to connect, but azureml-sdk[databricks] can ? SSO is not a core functionality ? 
And a key question : why azure-core 1.0.10 worked well and 1.0.15 is not ? Even if there were some breaking changes in code, why we have nothing in release history about this ?

**Comment by adyada** [comment]
Hi @mohaissa,

There is an issue with databricks that if you ever set a library to auto install on all clusters in a databrcicks workspace then it will be auto installed on all clusters in that databricks workspace without telling users. So, I guess you might be hitting this.

https://forums.databricks.com/questions/16400/remove-auto-install-library-thats-already-been-del.html


In this case, only solution I have found is to delete the cluster and databricks workspace both. And then recreate the databricks workspace and cluster, and then never set a library to autoinstall on all clusters as one can't remove them later on.  You can backup notebooks etc somewhere before deleting databricks workspace. 

@artsheiko 

 azureml-sdk[databricks] is specifically designed to be installed in databricks python environment, so it has some pinned versions of packages then azureml-sdk doesn't have. azureml-sdk[databricks]==1.0.15 should still work. Is it not working for you?

**Comment by vizhur** [comment]
azureml-sdk[databricks] and azureml-sdk[automl_databricks] are the **only** scenarios supported on ADB.

**Comment by mohaissa** [comment]
@adyada  
 agree with you, and this happened with me, but as you can see  from the image, I created a new  databricks instannce (22 Feb) and I created a new cluster but I still have the issue, note able de install azureml-sdk[databricks], please see the images.

@vizhur 
Not able to install it
![image](https://user-images.githubusercontent.com/29986627/53350831-f0363600-38ed-11e9-8156-6490ca120dca.png)

**Comment by mohaissa** [comment]
@vizhur 
![image](https://user-images.githubusercontent.com/29986627/53350888-1e1b7a80-38ee-11e9-9848-729681a4b337.png)

**Comment by mohaissa** [comment]
Hi Guys
it,s work now
thansk for your help
![image](https://user-images.githubusercontent.com/29986627/53351043-7bafc700-38ee-11e9-8e4c-655de3969e94.png)

**Comment by mohaissa** [comment]
Thanks for your help
Interactive authentication successfully completed.

**Comment by Nealit25** [comment]
> [Doc1.pdf](https://github.com/Azure/MachineLearningNotebooks/files/2865631/Doc1.pdf)
