### ISSUE TITLE
How to query existing Run from Azure ML?

### ISSUE THREAD

**Issue by peteratwork** [Azure/MachineLearningNotebooks#216]
If an experiment was created in the past and we have a runId then how do we query the model and results in the python notebook. Experiment.get_runs where property runId set to the known Id return a generator object. There isn't any documentation on the generator object on how to use it for querying the run results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d2314c0-1812-e30f-17b6-aa60238c00c9
* Version Independent ID: 63186725-185b-876a-5ea6-5fec581d4af5
* Content: [azureml.core.experiment.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment.experiment?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.experiment.Experiment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.experiment.Experiment.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by hning86** [comment]
https://aka.ms/aml-docs-cancel-run

**Comment by vincentAGNES** [comment]
Do smth like: 
     `L=exp_name.list(workspace_name)`
Then  select your experiment among the list like L[0] or L[1]...
And do smth like:
     `[i for i in Experiment.get_runs()]`
