### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by macwanj** [Azure/MachineLearningNotebooks#219]
This should be a very easy fix. The link in the main README is broken in the 'how to navigate' section:

...deploy models as batch scoring service, first train a model within Notebook, learn how to register and manage models, then create Machine Learning Compute for scoring compute, and use Machine Learning Pipelines (BROKEN LINK) to deploy your model.

**Comment by swinner95** [comment]
@sanpil does this notebook still exist?

**Comment by sanpil** [comment]
The correct link is: https://aka.ms/pl-batch-scoring. I will send a PR to fix.
