### ISSUE TITLE
Problem in docker image built process

### ISSUE THREAD

**Issue by gitathrun** [Azure/MachineLearningNotebooks#220]
Hello, I am currently try to create a docker image according to the tutorial. I initialised all the previous process smothly in my notebook (model registration, image config, etc), but in image creation step, I encountered problem.
In the notebook, I run the following statement:

image = ContainerImage.create(name = "xxxx", 
                              models = [model], #this is the model object
                              image_config = image_config,
                              workspace = ws
                              )

In the Notebook, it only output "Creating image" then no response.

Then in my Azure portal, the "images" page, the "status" shows "running" then few mins later, it shows "failed", and there is not any links to logs or notification what the problem is, can you help me at this point?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf6fb77-160e-92d8-987c-92f544f4fb31
* Version Independent ID: 3d19e0ce-c3c1-870e-1978-8bf0e12e9082
* Content: [azureml.core.image.ContainerImage class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-core/azureml.core.image.containerimage?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.image.ContainerImage.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.image.ContainerImage.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by hning86** [comment]
please see help here: https://aka.ms/debugimage

**Comment by gitathrun** [comment]
That is exactly what I need for the debug, thanks.
