### ISSUE TITLE
Search bar should be improved

### ISSUE THREAD

**Issue by vapaunic** [Azure/MachineLearningNotebooks#222]
The search bar for the AML SDK for Python performs really poorly, pretty much returns 'No result' for any search. It makes it difficult to use the API and find the references without the Search improved.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c318f67-9169-e151-fc8c-7ff06108db6a
* Version Independent ID: 9dbeb2f3-1382-e246-8eb4-c6fb797f537b
* Content: [API Reference  - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/overview/azure/ml/?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-joined/index.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-joined/index.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@vapaunic You are right. This is not working well and it can make it hard. We are aware and there is a bug open to fix it. 

Workaround: click the overview article in the table of contents and then try the search. It seems to work if you try searching from these articles:

![image](https://user-images.githubusercontent.com/8481597/53101288-0f4c5680-34ef-11e9-9a5c-4df26b5f3a98.png)

**Comment by vapaunic** [comment]
Thank you, Josee. This helps. I also noticed that the search filter was recently fixed, so feel free to close this issue.

Many thanks,
Vanja
