### ISSUE TITLE
Fetch authentication credentials from file, not in plain text

### ISSUE THREAD

**Issue by ArvidBaa** [Azure/MachineLearningNotebooks#223]
When working in notebooks, I don't feel like writing credentials and/or secrets in plain text. I know I could use environment variables in this case, but that is not always convenient.

My suggestion is to set up a similar method as when initializing a Workspace from a config file. The authentication credentials could be saved in an auth file in the same way. Like this:

```
svc_pr = ServicePrincipalAuthentication.from_auth_file(path=auth_path)
ws = Workspace.from_config(path=config_path, auth=svc_pr)
```

If possible, I could even suggest extending the config file to hold the authentication information, but an auth file should be the easier way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31731eb3-e539-a563-6557-bb5c4d1e5fc8
* Version Independent ID: e773574b-f028-5293-0f12-84a6a0258b13
* Content: [azureml.core.authentication.ServicePrincipalAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.serviceprincipalauthentication?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.authentication.ServicePrincipalAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.authentication.ServicePrincipalAuthentication.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Perhaps you can set up similar method as when initializing a Workspace from a config file. The authentication credentials could be saved in an auth file in the same way. Like this:
svc_pr = ServicePrincipalAuthentication.from_auth_file(path=auth_path)
ws = Workspace.from_config(path=config_path, auth=svc_pr)
Or, extend the config file to hold the authentication information, but an auth file should be the easier way.
