### ISSUE TITLE
FQDN for ACI webservices?

### ISSUE THREAD

**Issue by gitathrun** [Azure/MachineLearningNotebooks#225]
Hi, I used the code in the tutorial and created an ACI webservice, but it only offers IP address for access, is it possible to add a FQDN for the new ACI, so developers no need to fetch the new IP address everytime this ACI restarted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135107d5-83c1-5358-ac71-12456ff76a15
* Version Independent ID: 11398512-1226-8fa9-4be2-5c379d8aca62
* Content: [azureml.core.webservice.AciWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aciwebservice?view=azure-ml-py#deploy-configuration-cpu-cores-none--memory-gb-none--tags-none--properties-none--description-none--location-none--auth-enabled-none--ssl-enabled-none--enable-app-insights-none--ssl-cert-pem-file-none--ssl-key-pem-file-none--ssl-cname-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.AciWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.AciWebservice.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by gitathrun** [comment]
or an option for DNS name label setting ?

**Comment by aashishb** [comment]
Thanks for your feedback! We do plan to support dnsnamelabel for ACI but I do not have a firm timeline yet on when it will be available.

**Comment by gitathrun** [comment]
Great news, thanks for the reply.
