### ISSUE TITLE
while training model in automl, getting error for type casting 

### ISSUE THREAD

**Issue by arpitvw** [Azure/MachineLearningNotebooks#227]
data profile
![image](https://user-images.githubusercontent.com/35973377/53232710-b5e05500-36b1-11e9-91e6-393e596c3629.png)

when i am giving this data for training , i am getting below error 
![image](https://user-images.githubusercontent.com/35973377/53232751-d27c8d00-36b1-11e9-88dd-ecf0f177a01d.png)
there are no data of float type in my data. 
can you please let me know from where i need to check for the same 

commands that i have used : 
from sklearn.model_selection import train_test_split

x_df = dflow_X.to_pandas_dataframe()
y_df = dflow_y.to_pandas_dataframe().astype(int)

x_train, x_test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.2, random_state=223)
# flatten y_train to 1d array
y_train.values.flatten()

settings:
automl_settings = {
    "iteration_timeout_minutes" : 10,
    "iterations" : 20,
    "primary_metric" : 'spearman_correlation',
    "preprocess" : True,
    "verbosity" : logging.INFO,
    "n_cross_validations": 5
}

from azureml.train.automl import AutoMLConfig

# local compute
automated_ml_config = AutoMLConfig(task = 'regression',
                             debug_log = 'automated_ml_errors_gui.log',
                             path = project_folder,
                             X = x_train,
                             y = y_train.values.flatten(),
                             **automl_settings)

-----model run ------
# load workspace configuration from the config.json file in the current folder.
ws = workspace.Workspace.from_config()
from azureml.core.experiment import Experiment
experiment_name='ToG_Local_gui_test'
experiment=Experiment(ws, experiment_name)
local_run = experiment.submit(automated_ml_config, show_output=True)

error : 
![image](https://user-images.githubusercontent.com/35973377/53232903-21c2bd80-36b2-11e9-91d5-662991a5206b.png)

**Comment by arpitvw** [comment]
@aakanchjoshi@gmail.com @aakanch.j@somaiya.edu @milind.vengurlekar@mastek.com

**Comment by gaugup** [comment]
You could pass the dflow objects (i.e. dflow_x, dflow_y) directly to AutoML. AutoML does the conversion from dataflow object to pandas data frame internally. Could you give this a try to see if the training works for you.

However, this should have worked irrespective. Let me check further and get back.

**Comment by gaugup** [comment]
Also, another suggestion is to try with recent AutoML version 1.0.15.

**Comment by arpitvw** [comment]
I tried with both the ways , upgrading the version and used directly dflow_x,dflow_y , but getting same error

**Comment by arpitvw** [comment]
i prepared data using "pendleton" UI for dataprep library

**Comment by gaugup** [comment]
Thanks for giving this a try. Could you share the run-id from your recent experiment (looks like AutoML_***)? I can do some investigation as to why the experiment still fails.

**Comment by arpitvw** [comment]
i am using automl-sdk , 
my run id is AutoMLe1f5385d0best

**Comment by arpitvw** [comment]
closing the ticket , as there was issue with some auotml setting from my side
NOTE: if we give task as "regression" in automl config for "classification" problem then we will get above error

**Comment by gaugup** [comment]
Thanks for letting us know. Glad it worked for you.
