### ISSUE TITLE
Dependencies for ContainerImage ignored

### ISSUE THREAD

**Issue by HansG89** [Azure/MachineLearningNotebooks#228]
Hello,

How does the dependencies parameter work?
When I try to add local files to my image they’re simply ignored. There is no error but the files are not part of the created image.

**Comment by hning86** [comment]
they should be included. are you using relative path? please share the detail of your code adding local files.

**Comment by HansG89** [comment]
I have a python script which configures and builds my container image.

`image_config = ContainerImage.image_configuration(execution_script='score.py',
                                                  runtime='python',
                                                  conda_file='myenv.yml',
                                                  dependencies=[os.path.join(os.getcwd(), 'model_training', 'Model.py')])`

In the same folder there is another directory called "model_tranig" which contains a class in "Model.py".
When I add this file to the dependencies list with the code above, it doesn't get copied into /var/azureml-app inside the container.

**Comment by HansG89** [comment]
I debugged further. The file gets compressed and uploaded to azure blob storage. At this point, the internal magic of azure happens. I don’t know, how the actual docker build process is done. But so far I’m unable to find the file inside my image

**Comment by HansG89** [comment]
Got it!
the tar command which is invoked by `upload_dependency` function in `_utils.py ` includes the complete absolute path of the compressed file inside the archive. As a result, the original folder structure of the host machine is reproduced in`/var/azureml-app ` inside the container.

**Solution:**
replace
`dependencies=[os.path.join(os.getcwd(), 'model_training', 'Model.py')]`
with
`dependencies=[os.path.join('.', 'model_training', 'Model.py')]`
