### ISSUE TITLE
how to get cmake in azure ml experiment docker

### ISSUE THREAD

**Issue by DHOFM** [Azure/MachineLearningNotebooks#236]
Ho can I get an experiment run that needs dlib?
I submit the experiment from visual studio code with AML:Run as experiment in azure
my conda_depencies.yml look like this:

```
name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2
- cmake

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - dlib
  - imutils
  - opencv-python
  - scikit-image
  - tqdm

```  

The docker installation than fails:

>  RuntimeError:
>     *******************************************************************
>      CMake must be installed to build the following extensions: dlib
>     *******************************************************************

**Comment by ninghu** [comment]
Hi @DHOFM , try to install cmake through pip and it should work. See below yml file:

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - cmake
  - dlib
  - imutils
  - opencv-python
  - scikit-image
  - tqdm

**Comment by j-martens** [comment]
Hope this answers your question. Thanks for your report. We shall proceed to close this issue, #please-close. If you feel that your issue has not been resolved please reopen the issue and provide additional context.
