### ISSUE TITLE
web service issue:"Model not found in cache or in root at 

### ISSUE THREAD

**Issue by mohaissa** [Azure/MachineLearningNotebooks#237]
Hi Guys
I am trying to deploy my model as web service, but I am not able to debug this issue, when I open the url score I got this issue:
"{\"trainedModel\": \"Model not found in cache or in root at ./{naivebayes.pickle}. For more info,set logging level to DEBUG.\"}"

![image](https://user-images.githubusercontent.com/29986627/53746987-4ff18b80-3e70-11e9-8423-6e18e84ef0b5.png)

the log are there 
019-03-04 16:04:26,655 CRIT Supervisor running as root (no user in config file)
2019-03-04 16:04:26,657 INFO supervisord started with pid 1
2019-03-04 16:04:27,660 INFO spawned: 'rsyslog' with pid 9
2019-03-04 16:04:27,661 INFO spawned: 'program_exit' with pid 10
2019-03-04 16:04:27,663 INFO spawned: 'nginx' with pid 11
2019-03-04 16:04:27,665 INFO spawned: 'iot' with pid 12
2019-03-04 16:04:27,666 INFO spawned: 'gunicorn' with pid 14
2019-03-04 16:04:27,676 INFO success: iot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-03-04 16:04:27,830 INFO exited: iot (exit status 1; expected)
{"timestamp": "2019-03-04T16:04:28.217808Z", "message": "Starting gunicorn 19.6.0", "host": "wk-caas-4b08a687a67448398a3f66caca6679cdafd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Starting gunicorn %s", "stack_info": null}
{"timestamp": "2019-03-04T16:04:28.218506Z", "message": "Listening at: http://127.0.0.1:9090 (14)", "host": "wk-caas-4b08a687a67448398a3f66caca6679cdafd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Listening at: %s (%s)", "stack_info": null}
{"timestamp": "2019-03-04T16:04:28.218609Z", "message": "Using worker: sync", "host": "wk-caas-4b08a687a67448398a3f66caca6679cdbafd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Using worker: %s", "stack_info": null}
{"timestamp": "2019-03-04T16:04:28.219179Z", "message": "worker timeout is set to 300", "host": "wk-caas-4b08a687a67448398a3f66caca6679cdfd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "stack_info": null}
{"timestamp": "2019-03-04T16:04:28.220102Z", "message": "Booting worker with pid: 35", "host": "wk-caas-4b08a687a67448398a3f66caca6679fd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.error", "msg": "Booting worker with pid: %s", "stack_info": null}
2019-03-04 16:04:29,223 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-04 16:04:29,223 INFO success: program_exit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/home/mmlspark/lib/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.microsoft.ml.spark#mmlspark_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-69d5068b-9524-4008-bc0c-53aa8b642baa;1.0
	confs: [default]
	found com.microsoft.ml.spark#mmlspark_2.11;0.15 in spark-list
	found io.spray#spray-json_2.11;1.3.2 in central
	found com.microsoft.cntk#cntk;2.4 in central
	found org.openpnp#opencv;3.2.0-1 in central
	found com.jcraft#jsch;0.1.54 in central
	found org.apache.httpcomponents#httpclient;4.5.6 in central
	found org.apache.httpcomponents#httpcore;4.4.10 in central
	found commons-logging#commons-logging;1.2 in central
	found commons-codec#commons-codec;1.10 in central
	found com.microsoft.ml.lightgbm#lightgbmlib;2.1.250 in central
:: resolution report :: resolve 583ms :: artifacts dl 11ms
	:: modules in use:
	com.jcraft#jsch;0.1.54 from central in [default]
	com.microsoft.cntk#cntk;2.4 from central in [default]
	com.microsoft.ml.lightgbm#lightgbmlib;2.1.250 from central in [default]
	com.microsoft.ml.spark#mmlspark_2.11;0.15 from spark-list in [default]
	commons-codec#commons-codec;1.10 from central in [default]
	commons-logging#commons-logging;1.2 from central in [default]
	io.spray#spray-json_2.11;1.3.2 from central in [default]
	org.apache.httpcomponents#httpclient;4.5.6 from central in [default]
	org.apache.httpcomponents#httpcore;4.4.10 from central in [default]
	org.openpnp#opencv;3.2.0-1 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   10  |   0   |   0   |   0   ||   10  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: ERRORS
	unknown resolver repo-1

	unknown resolver repo-1

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
:: retrieving :: org.apache.spark#spark-submit-parent-69d5068b-9524-4008-bc0c-53aa8b642baa
	confs: [default]
	0 artifacts copied, 10 already retrieved (0kB/9ms)
2019-03-04 16:04:31 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2019-03-04 16:04:32,891 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Initializing logger
{"timestamp": "2019-03-04T16:04:37.403155Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Starting up app insights client\", \"apiName\": \"\"}", "host": "wk-caas-4b08a687a67448398a3f66caca6679cdbafd4011dc690c303", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
{"timestamp": "2019-03-04T16:04:37.403377Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Starting up request id generator\", \"apiName\": \"\"}", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-bafd4011dc690c303", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
{"timestamp": "2019-03-04T16:04:37.403478Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Starting up app insight hooks\", \"apiName\": \"\"}", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-bfd4011dc690c303", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
{"timestamp": "2019-03-04T16:04:37.403570Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Invoking user's init function\", \"apiName\": \"\"}", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-afd4011dc690c303", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
2019-03-04 16:04:38,616 | azureml.core.run | DEBUG | Adding new factory <function ScriptRun._from_run_dto at 0x7fb2852cc598> for run source azureml.scriptrun
2019-03-04 16:04:38,622 | azureml.core.run | DEBUG | Could not load run context Failed to load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run., switching offline: False
2019-03-04 16:04:38,622 | azureml.core.run | DEBUG | Could not load the run context and allow_offline set to False
2019-03-04 16:04:38,623 | azureml.core.model | DEBUG | RunEnvironmentException: Failed to load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
2019-03-04 16:04:38,623 | azureml.core.model | DEBUG | Checking root for {my_best_model} because candidate dir azureml-models had 1 nodes: azureml-models/naivebayes.pickle/1/naivebayes.pickle
{"timestamp": "2019-03-04T16:04:38.623417Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Users's init has completed successfully\", \"apiName\": \"\"}", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-afd4011dc690c303", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/mmlspark/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /home/mmlspark/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /home/mmlspark/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
{"timestamp": "2019-03-04T16:04:38.623826Z", "message": "{\"requestId\": \"00000000-0000-0000-0000-000000000000\", \"message\": \"Scoring timeout setting is not found. Use default timeout: 3600000 ms\", \"apiName\": \"\"}", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-bafd4011dc690c303", "path": "/var/azureml-app/aml_logger.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "root", "stack_info": null}
{"timestamp": "2019-03-04T16:04:38.626883Z", "message": "127.0.0.1 - - [04/Mar/2019:16:04:38 +0000] \"GET / HTTP/1.0\" 200 7 \"-\" \"Go-http-client/1.1\"", "host": "wk-caas-4b08a687a67448398a3f66caca6679cafd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.access", "stack_info": null}
2019-03-04 16:04:48,639 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 20 seconds (startsecs)
{"timestamp": "2019-03-04T16:04:48.692400Z", "message": "127.0.0.1 - - [04/Mar/2019:16:04:48 +0000] \"GET / HTTP/1.0\" 200 7 \"-\" \"Go-http-client/1.1\"", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-bafd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.access", "stack_info": null}
{"timestamp": "2019-03-04T16:04:52.599423Z", "message": "127.0.0.1 - - [04/Mar/2019:16:04:52 +0000] \"GET / HTTP/1.0\" 200 7 \"-\" \"Go-http-client/1.1\"", "host": "wk-caas-4b08a687a67448398a3f66caca6679cd-afd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.access", "stack_info": null}
{"timestamp": "2019-03-04T16:05:55.117148Z", "message": "127.0.0.1 - - [04/Mar/2019:16:05:55 +0000] \"GET / HTTP/1.0\" 200 7 \"-\" \"Go-http-client/1.1\"", "host": "wk-caas-4b08a687a67448398a3f66caca6679cdafd4011dc690c303", "path": "/home/mmlspark/lib/conda/lib/python3.6/site-packages/gunicorn/glogging.py", "tags": "%(module)s, %(asctime)s, %(levelname)s, %(message)s", "level": "INFO", "logger": "gunicorn.access", "stack_info": null}

**Comment by khordoo-sensorup** [comment]
Adding the version number solved the issue for me.
`model = Model(ws, name='my-best-model',version=3)`

**Comment by khordoo** [comment]
Adding the version number solved the issue for me.
`model = Model(ws, name='my-best-model',version=3)`
