### ISSUE TITLE
Permission issue while running the python scripts on adb cluster

### ISSUE THREAD

**Issue by apraovjr** [Azure/MachineLearningNotebooks#239]
Hi

I am using databrickstep to run the step in the ADB cluster. The step is simple as just getting workspace info. The workspace script looks like this 

ws = Workspace(subscription_id=subscription, resource_group=group, workspace_name=workspace, auth=svcpr)

where svcpr is the service principal created and required role assignment is done.

While running it on cluster in ADB , it still shows this error 

UserErrorException: You are currently logged-in to 72f988bf-86f1-41af-91ab-2d7cd011db47 tenant. You don't have access to "676a39db-05e1-4d98-bac5-25a85d1e5d35" subscription, please check if it is in this tenant. All the subscriptions that you have access to in this tenant are = 
 [SubscriptionInfo(subscription_name='TE Account - Aprao', subscription_id='676a39db-05e1-4d98-bac5-25a85d1e5d35')]. 

Also all my resources tied to AML pipelines are in same resource.
Any help would be appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f93a584-8199-d04b-788e-53ce99ef483a
* Version Independent ID: c1ee7a99-6d4b-3763-446a-912077183ccb
* Content: [azureml.core.workspace.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace.workspace?view=azure-ml-py#get-name--auth-none--subscription-id-none--resource-group-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

@sanpil @nacharya1

**Comment by fahdkmsft** [comment]
@apraovjr is this error coming from your AML script that you use to run the Pipeline or the Databricks script? Can you paste which line in the script causes this error?

Also, please make sure that your Azur Databricks workspace and AML workspace belong to the same subscription.
