### ISSUE TITLE
can you please share sample train.py file (with training code)

### ISSUE THREAD

**Issue by arpitvw** [Azure/MachineLearningNotebooks#241]
Hello Team , 
while creating pipeline , i am getting http error for GET method 
can you please share one sample "Train.py" file which include training code as well.

**Comment by arpitvw** [comment]
and also can you please mention where to keep which script file , 
like where to keep train.py file and where to keep pipeline code (whether at adla storage or workspace storage or somewhere else)

**Comment by sanpil** [comment]
The issue is resolved. The file, train.py is now available under the train sub-folder.
