### ISSUE TITLE
AutomatedML multi-label classification

### ISSUE THREAD

**Issue by adKatta** [Azure/MachineLearningNotebooks#242]
hi,
Many of the automatedML notebooks mention that "An indicator matrix turns on multilabel classification. This should be an array of integers.".

However I am unable to get the multi-label classification to work. 
I have tried sendiing in a indicator matrix in amongst other things. Each time I get an error saying either
1) y should be a vector Nx1
2) unhashable type: 'list', 'array' etc.
Can you please share an example of how to supply the target "y".

**Comment by eclausenbrown** [comment]
Thank you for bringing this to our attention.  This is an error in the automl notebooks that we'll correct shortly.  Currently Azure AutoML does not support multi-label classification, we only support binary and multi-class classification.

**Comment by adKatta** [comment]
Thanks for the information.

**Comment by skasturi** [comment]
@rastala , can you please close this issue?
