### ISSUE TITLE
Unable to register the model using Jupyter Notebook with error message: "HttpOperationError: Operation returned an invalid status code 'Service invocation failed!Request: GET https://cert-westeurope.experiments.azureml.net/rp/workspaces'"

### ISSUE THREAD

**Issue by mahdouch550** [Azure/MachineLearningNotebooks#243]
> from azureml.core.model import Model
model = Model.register(model_path = MODEL_FILENAME,
                       model_name = "MyONNXmodel",
                       tags = {"onnx":"V0"},
                       description = "test",
                       workspace = ws)
this is the python code I am using to register the model.

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see our answer this issue was delayed. Our apologies. We did not receive a response to our response, so will close this issue for now. Should you need further assistance, please submit a post on this forum. We are happy to help.
