### ISSUE TITLE
Is there a way to enable Flask debug in the deployment?

### ISSUE THREAD

**Issue by KevinXTian** [Azure/MachineLearningNotebooks#244]
Can we have a parameters debug=False that we could turn it on when needed?

That is extremely important when importing some previous trained model. When there is a run-time error in that model, Flask may hide that with 5xx errors, preventing developers to get the stack trackback. Thus the developer has to guess what really happened. If we could enable Flask debug, things will be much easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eb312fb-5317-8d04-0a2b-806d5bb34b42
* Version Independent ID: b5d87b71-994b-6d88-c161-f4852a3ce05a
* Content: [azureml.core.webservice.aci.AciServiceDeploymentConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aci.aciservicedeploymentconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciServiceDeploymentConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciServiceDeploymentConfiguration.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue?

**Comment by KevinXTian** [comment]
Yes.

**Comment by jpe316** [comment]
@vaidya-s

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us. We see our answer was delayed. Our apologies. We   did not receive a response to our response, so will close this issue for now.   Should you need further assistance, please submit a post on this forum. We   are happy to help.
--

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see your latest post was not addressed and was posted some time ago. Our apologies. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
