### ISSUE TITLE
Experiment failed in portal but it's OK in log files

### ISSUE THREAD

**Issue by rbobadilla** [Azure/MachineLearningNotebooks#245]
I'm training a sample experiment in AMLS. My goal is to run it in a remote hdi cluster with python3.

I manually installed all the libraries that i need on the cluster (both in head nodes and worker nodes), such as numpy, azureml, sklearn, and then i made a jupyter notebook to submit a .py script with all the functions needed to be run in the spark environment inside the hdi cluster. 

Checking the logs files created for a particular run i can see that my script completed succesfully, but for some reason, the run took a failed status.

I attach the log files and the script.py in spark
[60_control_log.txt](https://github.com/Azure/MachineLearningNotebooks/files/2947073/60_control_log.txt)
[80_driver_log.txt](https://github.com/Azure/MachineLearningNotebooks/files/2947074/80_driver_log.txt)
[azureml.log](https://github.com/Azure/MachineLearningNotebooks/files/2947075/azureml.log)

I thought the problem was caused in the complete() method of run object, but i put a print() function after this sentence and i can see its output, so i can guess run.complete() works properly.
Then, i though that maybe the clean up process could origin the problem, but by checking all the log files, everything seems to be fine.
What can cause this issue?

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us. We see our answer was delayed. Our apologies. We   did not receive a response to our response, so will close this issue for now.   Should you need further assistance, please submit a post on this forum. We are happy to help.
