### ISSUE TITLE
[Issue] remote dsvm attachment failed.

### ISSUE THREAD

**Issue by yexing99** [Azure/MachineLearningNotebooks#251]
The sample notebook of 'train on vm' on AML github does not work. The error is the following:

Creating......

FailedProvisioning operation finished, operation "Failed"

Async operation failed with

StatusCode: 500

Message: An internal server error occurred. Please try again. If the problem persists, contact support

Compute object has provisioning state "Failed"

and provisioning errors: [{'code': 'InternalServerError', 'message': 'An internal server error occurred. Please try again. If the problem persists, contact support', 'error': {'code': 'InternalServerError', 'statusCode': 500, 'message': 'An internal server error occurred. Please try again. If the problem persists, contact support', 'details': [{'code': 'An internal server error occurred. Please try again. If the problem persists, contact support', 'message': 'Connection failed to establish within 30000 milliseconds.'}]}}]

 

 

My script is the following:

from azureml.core.compute import ComputeTarget, RemoteCompute

from azureml.core.compute_target import ComputeTargetException

 

username = os.getenv('AZUREML_DSVM_USERNAME', default='adminye')

address = os.getenv('AZUREML_DSVM_ADDRESS', default='70.37.49.45')

 

compute_target_name = 'vmtestye2'

# if you want to connect using SSH key instead of username/password you can provide parameters private_key_file and private_key_passphrase

try:

    attached_dsvm_compute = RemoteCompute(workspace=ws, name=compute_target_name)

    print('found existing:', attached_dsvm_compute.name)

except ComputeTargetException:

    attach_config = RemoteCompute.attach_configuration(address=address,

                                                        ssh_port=22,

                                                        username=username,

                                                        password = "****")

                                                        #private_key_file='./.ssh/id_rsa')

    attached_dsvm_compute = ComputeTarget.attach(workspace=ws,

                                                 name=compute_target_name,

                                                 attach_configuration=attach_config)

    attached_dsvm_compute.wait_for_completion(show_output=True)

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

**Comment by ra312** [comment]
I believe I am experiencing the same issue at the moment? Are there any updates on the above behaviour?

**Comment by v-strudm-msft** [comment]
#please-close

**Comment by lostmygithubaccount** [comment]
we are removing the notebook and no longer supporting it
