### ISSUE TITLE
Issues installing Opencv

### ISSUE THREAD

**Issue by nkma1989** [Azure/MachineLearningNotebooks#252]
Hello.
I'm trying to install opencv on my compute target. The will run if i'm not installing opencv, but when i add it I get the following error:
  File "train.py", line 7, in &lt;module&gt;
    from cv2 import add
  File "/azureml-envs/azureml_2b8741335a5c3198578051301af43a5b/lib/python3.6/site-packages/cv2/__init__.py", line 3, in &lt;module&gt;
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

I use the following estimator:

estimator= TensorFlow(source_directory=project_folder,
                      compute_target=compute_target,
                      script_params=script_params,
                      entry_script='train.py',
                      pip_packages=['keras==2.1.2','h5py','scipy','opencv-python'],
                      node_count=2,
                      process_count_per_node=1,
                      distributed_backend='mpi',
                      use_gpu=True)

Any ideas to what I should do?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 467fb465-3db5-bdec-c15a-4b42ba598324
* Version Independent ID: 08f6b327-dc9e-911d-adc8-535499c58ba3
* Content: [azureml.train.dnn.TensorFlow class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-train-core/azureml.train.dnn.tensorflow?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.TensorFlow.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.TensorFlow.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ninghu** [comment]
Opencv requires mesa's GL library. Use conda_packages=['mesa-libgl-cos6-x86_64']

**Comment by amardeepjaiman** [comment]
i think this is not solving the issue. I am using below estimator but i m getting same error.

est = TensorFlow(source_directory='maskrcnn-train',
                 script_params=script_params,
                 compute_target=compute_target, 
                 pip_packages=['Cython','keras', 'opencv-python','matplotlib','scikit-image','scipy','h5py','imgaug','IPython[all]','numpy','Pillow'],
                 entry_script='training.py', 
                 conda_packages=['mesa-libgl-cos6-x86_64'],
                 use_gpu=True,
                 use_docker=True,
                 inputs=[ds.as_mount()])

**File "/azureml-envs/azureml_0fbacf49bc84b9af7157d336ed1fc6bb/lib/python3.6/site-packages/imgaug/__init__.py", line 2, in <module>
    from imgaug.imgaug import *
  File "/azureml-envs/azureml_0fbacf49bc84b9af7157d336ed1fc6bb/lib/python3.6/site-packages/imgaug/imgaug.py", line 13, in <module>
    import cv2
  File "/azureml-envs/azureml_0fbacf49bc84b9af7157d336ed1fc6bb/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory**

**Comment by ninghu** [comment]
Can you please try with installing opencv through conda_packages?

est = TensorFlow(source_directory='maskrcnn-train',
script_params=script_params,
compute_target=compute_target,
pip_packages=['Cython','keras', 'matplotlib','scikit-image','scipy','h5py','imgaug','IPython[all]','numpy','Pillow'],
entry_script='training.py',
conda_packages=['mesa-libgl-cos6-x86_64', ‘opencv=3.4.2'],
use_gpu=True,
use_docker=True,
inputs=[ds.as_mount()])

**Comment by amardeepjaiman** [comment]
Thanks, I tried to install opencv using conda package. but this time it does not find another shared library. please find the error below :

 File "/azureml-envs/azureml_3ec0ba3f30b4357edd78d07bd8af8197/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_3ec0ba3f30b4357edd78d07bd8af8197/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "training.py", line 151, in <module>
    train(args.dataset)
  File "training.py", line 50, in train
    import imgaug
  File "/azureml-envs/azureml_3ec0ba3f30b4357edd78d07bd8af8197/lib/python3.6/site-packages/imgaug/__init__.py", line 2, in <module>
    from imgaug.imgaug import *
  File "/azureml-envs/azureml_3ec0ba3f30b4357edd78d07bd8af8197/lib/python3.6/site-packages/imgaug/imgaug.py", line 13, in <module>
    import cv2
  File "/azureml-envs/azureml_3ec0ba3f30b4357edd78d07bd8af8197/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

I have used following estimator :
est = TensorFlow(source_directory='maskrcnn-train',
                 script_params=script_params,
                 compute_target=compute_target, 
                 pip_packages=['Cython','keras','matplotlib','scikit-image','scipy','h5py','imgaug','IPython[all]','numpy','Pillow'],
                 entry_script='training.py', 
                 conda_packages=['mesa-libgl-cos6-x86_64','opencv=3.4.2'],
                 use_gpu=True,
                 use_docker=True,
                 inputs=[ds.as_mount()])

any other conda package also need to be installed for this ?

**Comment by ninghu** [comment]
It seems to be related to the issue discussed here:
https://stackoverflow.com/questions/47113029/importerror-libsm-so-6-cannot-open-shared-object-file-no-such-file-or-directo


  1.  Try to include “opencv-python-headless” in the pip_packages and see it works.
  2.  If not, you can build a custom docker image on top of AML base images(i.e. mcr.microsoft.com/azureml/base-gpu:0.2.4) and include the libsm and other libraries mentioned in the thread.  And use that image in estimator to submit your training job.

**Comment by kenkadota** [comment]
Closing issue per Ninghu

**Comment by Darek-S** [comment]
I had the same issue and got it to work with these exact packages (newer versions caused problems):
est = TensorFlow(source_directory=script_folder,
                 compute_target=compute_target, 
                 pip_packages=['keras'],
                 conda_packages=['mesa-libgl-cos6-x86_64','opencv=3.4.2','numpy=1.14.5'],
                 entry_script='resnet50.py', 
                 use_gpu=True)

**Comment by kenkadota** [comment]
Thank you Derek this is very helpful
