### ISSUE TITLE
Problem of installing azureml-sdk[databricks] together with Tensorflow

### ISSUE THREAD

**Issue by james-tn** [Azure/MachineLearningNotebooks#254]
Having them two seems to create a conflict and as the result, databricks cannot execute anything in the notebook. My workaround is to uninstall azureml-sdk[databricks], restart cluster then install azureml-sdk[databricks] after Tensorflow is already in place. But I had to do this everytime my cluster restarts and it's annoying. 
I use Databricks runtime 5.2

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close the issue. Should you need   assistance with another issue, please let us know and we will respond to your   post promptly.
