### ISSUE TITLE
How to add custom script to DSVM?

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/MachineLearningNotebooks#257]
I need to install pynvrtc with pip install because pytorch requires NVIDIA runtime.

I probably need to do this with a custom script that executes on DSVM that I am attaching to.
Is this possible to run such a  script?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed. Our apologies. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
