### ISSUE TITLE
how to set local python file as dependency in myenv.yml file

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#260]
Hi ,

I need to set a local python file as dependency for scoring script while deploying my model as webservice on azure ML. I can set pip and conda package as dependency but not able to set local python abc.py as dependency.

Please guide me how to do it.

Thanks,
Amardeep

**Comment by krabhishek8260** [comment]
You can specify it as dependencies when creating image_configuration. 
Refer here: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.container.containerimage?view=azure-ml-py#image-configuration-execution-script--runtime--conda-file-none--docker-file-none--schema-file-none--dependencies-none--enable-gpu-none--tags-none--properties-none--description-none--base-image-none--base-image-registry-none-
