### ISSUE TITLE
CORS support when running from REST endpoint

### ISSUE THREAD

**Issue by piizei** [Azure/MachineLearningNotebooks#261]
Currently it looks like CORS is not supported for executing a pipeline from REST endpoint?
If this is true, can this be added as a feature?

**Comment by syedsadiqalinaqvi** [comment]
Was curious to know if there's any way to call a published pipeline from its REST endpoint without an authentication token? Like the way deployments are called?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed. Our apologies. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
