### ISSUE TITLE
Broken link in training/train-within-notebook/train-within-notebook.ipynb

### ISSUE THREAD

**Issue by chagen24** [Azure/MachineLearningNotebooks#262]
The "Configuration" link in the "Setup" section of MachineLearningNotebooks/how-to-use-azureml/training/train-within-notebook/train-within-notebook.ipynb is broken. It leads to a "Not Found" page.

**Comment by j-martens** [comment]
This has been fixed. Thanks for your report.
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/train-within-notebook/train-within-notebook.ipynb
