### ISSUE TITLE
Using ACI service to make predictions is not working properly 

### ISSUE THREAD

**Issue by a-motouz** [Azure/MachineLearningNotebooks#268]

**Comment by a-motouz** [comment]
When testing the ACI service (deploy-to-aci-04), I get the following output:

 "'str' object has no attribute 'tolist'"

Thanks,
MT

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us. We see our answer was delayed. Our apologies. We did not receive a response to our post, so will close this issue for now. Should you need further assistance, please submit a post on this forum and we will respond promptly.
