### ISSUE TITLE
Fail to run automl_setup.sh on mac

### ISSUE THREAD

**Issue by qq609299174** [Azure/MachineLearningNotebooks#272]
When I run the file automl_setup_mac.sh it shows me an error:
: command not found: line 2: 
: command not found: line 7: 
automl_setup_mac.sh: line 56: syntax error: unexpected end of file

I checked these lines that these are all blanks. I don't know how to edit on .sh file. Can someone tell me what is wrong here?

I have installed Conda 4.6.8

**Comment by skasturi** [comment]
@jeff-shepherd

**Comment by jeff-shepherd** [comment]
There was a problem with line termination in the automl_setup_mac.sh script when it was uploaded to GitHub.  The file has been fixed now in GitHub.  You can download the latest from GitHub or fix the file that you already have with the following commands:

cp automl_setup_mac.sh automl_setup_mac_old.sh
tr -d '\15\32' < automl_setup_mac_old.sh > automl_setup_mac.sh
