### ISSUE TITLE
azureml.widget not running

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/MachineLearningNotebooks#273]
Could you help to resolve this issue?

>est = Estimator(source_directory=source_folder,
                script_params=script_params,
                compute_target=compute_target,  
                entry_script='dummy-tracker.py',
                pip_packages=['pynvrtc'],
                conda_packages=['pytorch','scipy','numpy','scikit-learn','tqdm','cython','torchvision','cudatoolkit=9.0','matplotlib'])
experiment = Experiment(workspace = ws, name = "KDTree-GPU")
run = experiment.submit(est, show_output=True)

Error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-42102463560b> in <module>
----> 1 RunDetails(run).show()

~/.conda/envs/tracking/lib/python3.7/site-packages/azureml/widgets/_widget_run_details_base.py in show(self, render_lib, widget_settings)
     44             widget_settings = {}
     45 
---> 46         widget_settings = {**self._get_default_setting(), **widget_settings}
     47 
     48         self.settings = widget_settings

~/.conda/envs/tracking/lib/python3.7/site-packages/azureml/widgets/_widget_run_details_base.py in _get_default_setting(self)
    155                 "send_telemetry": send_telemetry,
    156                 "log_level": level,
--> 157                 "sdk_version": azureml.core.VERSION}
    158 
    159     def _get_telemetry_values(self, func):

AttributeError: module 'azureml' has no attribute 'core'
`

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Thank you!

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us. We see our answer was delayed. Our apologies. We did not receive a response to our post, so will close this issue for now. Should you need further assistance, please submit a post on this forum and we will respond promptly.
