### ISSUE TITLE
internal server error on creating aks compute target on Azure ML

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#274]
Hi ,

I am getting internal server error on create AKS compute target using following code :
prov_config = AksCompute.provisioning_configuration(vm_size='Standard_NC6')

# Create the cluster
aks_target = ComputeTarget.create(workspace = ws, 
                                  name = "aks-deploy", 
                                  provisioning_configuration = prov_config)

%%time
aks_target.wait_for_completion(show_output = True)
print(aks_target.provisioning_state)
print(aks_target.provisioning_errors)

Error stacktrace:

Creating...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
FailedProvisioning operation finished, operation "Failed"
Async operation failed with
StatusCode: 500
Message: An internal server error occurred. Please try again. If the problem persists, contact support
Compute object has provisioning state "Failed"
and provisioning errors: [{'code': 'InternalServerError', 'message': 'An internal server error occurred. Please try again. If the problem persists, contact support', 'error': {'code': 'InternalServerError', 'statusCode': 500, 'message': 'An internal server error occurred. Please try again. If the problem persists, contact support'}}]

Failed
[{'code': 'InternalServerError', 'message': 'An internal server error occurred. Please try again. If the problem persists, contact support', 'error': {'code': 'InternalServerError', 'statusCode': 500, 'message': 'An internal server error occurred. Please try again. If the problem persists, contact support'}}]
CPU times: user 13.5 s, sys: 592 ms, total: 14.1 s
Wall time: 55min 41s

Please let me know whats the issue with the code.or anyway to fix it.

**Comment by amardeepjaiman** [comment]
Anyone facing this issue ? or any response from Azure team ?

**Comment by amardeepjaiman** [comment]
Dont MIcrosoft people provide support on Azure ML services related issues here ?

**Comment by krabhishek8260** [comment]
@amardeepjaiman Can you please share your workspace details.

**Comment by amardeepjaiman** [comment]
What details you need, please specify?

Name: Amjn_workspace
Location: EastUS

**Comment by hongjj2013** [comment]
Standard_NC6 contains GPUs, and it was failed due to fail to setup nvidia-device-plugin. This is a bug which is fixed recently in AML code. If try again, it should succeed.

**Comment by mustafakasap** [comment]
as of today, having the same problem. below code was working weeks ago. Now I tried multiple times. Re-created the workspace from scratch, migrated to Enterprise tier but again getting the same error (details below)

from azureml.core.compute import AksCompute, ComputeTarget
from azureml.exceptions import ComputeTargetException

# Check to see if the cluster already exists
try:
    aks_target = ComputeTarget( workspace = aml_workspace,
                                    name = aks_name)
    print('Found existing compute target')
except ComputeTargetException:
    print('Creating a new compute target...')
    
        prov_config = AksCompute.provisioning_configuration(    vm_size = "Standard_NC6",
                                                            agent_count = 3,
                                                            location = res_grp_location)

    # Create the cluster
    aks_target = ComputeTarget.create(  workspace = aml_workspace,
                                        name = aks_name,
                                        provisioning_configuration = prov_config)

    aks_target.wait_for_completion(show_output=True)

print('- Created compute target handle')

############################################
Receiving the following error message after several minutes:


Creating a new compute target...
Creating............................................................................................................................................................................
FailedProvisioning operation finished, operation "Failed"
---------------------------------------------------------------------------
ComputeTargetException                    Traceback (most recent call last)
~/Documents/projects/amls_test_k8s/aml_deploy.py in 
     10     aks_target = ComputeTarget( workspace = aml_workspace,
---> 11                                     name = aks_name)
     12     print('Found existing compute target')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azureml/core/compute/compute.py in __new__(cls, workspace, name)
     78                 raise ComputeTargetException('ComputeTargetNotFound: Compute Target with name {} not found in '
---> 79                                              'provided workspace'.format(name))
     80         else:

ComputeTargetException: ComputeTargetException:
	Message: ComputeTargetNotFound: Compute Target with name AKS-NC6-v1 not found in provided workspace
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "ComputeTargetNotFound: Compute Target with name AKS-NC6-v1 not found in provided workspace"
    }
}

During handling of the above exception, another exception occurred:

ComputeTargetException                    Traceback (most recent call last)
~/Documents/projects/amls_test_k8s/aml_deploy.py in 
     33                                         provisioning_configuration = prov_config)
     34 
---> 35     aks_target.wait_for_completion(show_output=True)
     36 
     37 print('- Created compute target handle')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azureml/core/compute/compute.py in wait_for_completion(self, show_output)
    426                                              'Current state is {}'.format(self.provisioning_state))
    427             else:
--> 428                 raise e
    429 
    430     def _wait_for_completion(self, show_output):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azureml/core/compute/compute.py in wait_for_completion(self, show_output)
    419                                              'state, current provisioning state: {}\n'
    420                                              'Provisioning operation error:\n'
--> 421                                              '{}'.format(self.provisioning_state, error_response))
    422         except ComputeTargetException as e:
    423             if e.message == 'No operation endpoint':

ComputeTargetException: ComputeTargetException:
	Message: Compute object provisioning polling reached non-successful terminal state, current provisioning state: Failed
Provisioning operation error:
{'code': 'InternalServerError', 'message': 'An internal server error occurred. If the problem persists, contact support.'}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Compute object provisioning polling reached non-successful terminal state, current provisioning state: Failed\nProvisioning operation error:\n{'code': 'InternalServerError', 'message': 'An internal server error occurred. If the problem persists, contact support.'}"
    }
}

**Comment by iarovyi** [comment]
Still problem.
Tried to do a hello world with ML editor

![image](https://user-images.githubusercontent.com/2605923/81547430-1ffb1d80-937c-11ea-8ecc-e85e95f159f0.png)
