### ISSUE TITLE
Not able to create GPU enabled ACI instance for deploying model as webservice

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#275]
Not able to find anyway to deploy model as webservice on ACI instances. Only arguments available to provide CPU cores and memory. Please provide the resolution.

**Comment by amardeepjaiman** [comment]
any comments on this ?

**Comment by rsethur** [comment]
Hello,
I learnt recently that ACI support for GPU is not available. GPU in AKS seems to work for me.

**Comment by krabhishek8260** [comment]
ACI support for GPU is in preview and hence AML currently does not support GPU on ACI.
