### ISSUE TITLE
Log Image Display on in portal

### ISSUE THREAD

**Issue by zackdrescher** [Azure/MachineLearningNotebooks#276]
When logging multiple images using the log_image() function, they are displayed in the portal all over lapped and difficult to read, you can still veiw them seperately in another tab but this performance is less than desirable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2464cc9-aef4-8929-142f-a1ce7ae69d78
* Version Independent ID: 7b46b2e5-965f-1a0e-7c35-686900196f6e
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by zackdrescher** [comment]
![image](https://user-images.githubusercontent.com/14876895/55080183-10cfe800-5074-11e9-8c13-00b947844009.png)

Example of 3 images.

**Comment by v-strudm-msft** [comment]
Thank you for your post. We’re glad to see this issue was resolved and will now close this thread. Should you have additional questions, please continue to post here.
