### ISSUE TITLE
autoML - iteration_timeout_minutes not working

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#277]
I've set the iteration_timeout_minutes parameter to be a certain time, but many of the iterations are running over it. Is this parameter broken?

EDIT: It seems like setting model_explainability=True is part of the problem. If that's off, it runs normally. If it's on, a single iteration seems to run forever (I recently interrupted the kernel and the runtime for a single experiment was 90 minutes), disregarding the iteration_timeout_minutes parameter.

**Comment by swanderz** [comment]
how large are the train and test data? how many features? setting `model_explainability=True` invokes SHAP which can be quite resource intensive as it models with all possible permutations of features.

**Comment by wchill** [comment]
Hi, I believe currently the iteration_timeout_minutes parameter only works for the time it takes to train a model - if model explanation is enabled, the time it takes to run model explanation (which is done for each iteration) is not counted towards the timeout.

This is somewhat confusing behavior, so I'll start a discussion internally on how to best address this.

**Comment by ktebbe** [comment]
@swanderz I did an 80/20 split of 65,000 observations, 60 features.
@wchill I see; that is a bit confusing. I'd love to know if changes are made.

**Comment by swanderz** [comment]
@ktebbe I've used AutoML with model explain-ability and a very similarly sized dataset and I haven't seen a runtime of 90 minutes.
I'm not sure if by  90+ min runtime you mean
- for a cell in jupyter to be execute have the kernel say its free, or 
- for the run execution for the Run in Experiment?

Can you try setting running again with only 1000 rows or something and monitoring it in the portal to see how long it takes to run?

**Comment by ktebbe** [comment]
@swanderz it was the first experiment's runtime. I tried your suggestion and ran it with a subset of 1000 rows, but again, the first experiment took over an hour before I interrupted it.

**Comment by ktebbe** [comment]
Hi there - wondering if there are any updates on if this is being addressed.

**Comment by j-martens** [comment]
@nacharya1 @deepak-muniappan

**Comment by nacharya1** [comment]
@ktebbe - what is iteration time out set too? And how much over are the iterations going?

**Comment by jialiu103** [comment]
@ktebbe which SDK version are you using? We shipped an improvement using mimic explainer for model explanation which targets to improve the explanation time. Can you upgrade to latest version and give it a try?

Another related question, is it helpful to have feature importance for every pipeline, or do you need only for the best one?

**Comment by kenkadota** [comment]
Closed per Ani

**Comment by ktebbe** [comment]
Hi there - I'm still having issues with this. I re-installed Jupyter (my SDK), set the timeout to 5 minutes, but it's going at least twice that over (a recent experiment took 14). Should I just allot more time? Does the iteration timeout only apply to fitting the model, not detailing the explanability?

**Comment by rahulnosedat** [comment]
I am also having the same problem. It's running when the dataset is small but when it's a large dataset, it's a timeout and doesn't run at all. I am facing this for the last few weeks and it's still the same.

**Comment by lostmygithubaccount** [comment]
@rahulnosedat could you please open a new issue with repro steps?
