### ISSUE TITLE
dependencies parameter: location of files and folders in image

### ISSUE THREAD

**Issue by timoklimmer** [Azure/MachineLearningNotebooks#278]
The additional files and folders specified by the dependencies parameter will be put into /var/azureml-app in the image and are available when the additional Docker commands are run (see parameter docker_file). You can use this eg. to install private packages in your container. However note that the conda_file is run AFTER the docker_file. Hence you might need to install some conda packages in the docker_file commands on your own if those are needed to install your private packages (using RUN conda install ...).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf6fb77-160e-92d8-987c-92f544f4fb31
* Version Independent ID: 3d19e0ce-c3c1-870e-1978-8bf0e12e9082
* Content: [azureml.core.image.ContainerImage class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.containerimage?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.image.ContainerImage.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.image.ContainerImage.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thank you.
