### ISSUE TITLE
Problem with conde related to Docker in train-on-local.ipynb

### ISSUE THREAD

**Issue by GeisaFaustino** [Azure/MachineLearningNotebooks#279]
The notebook train-on-local.ipynb located at how-to-use-azureml/trainingtrain-on-local/ has a problem with the code on below:
![image](https://user-images.githubusercontent.com/32823639/55252866-9a2d1900-5232-11e9-952d-01c3d886d85b.png)
Although docker is installed and running, it returns the message "Docker engine not installed.".
To fix the code I did:
![image](https://user-images.githubusercontent.com/32823639/55253045-0a3b9f00-5233-11e9-9e7d-1e6f6f831d18.png)
I am using Python 3.6.6 and Docker 18.09.2.

**Comment by kenkadota** [comment]
Thanks for your report. Since we haven’t heard back from you, we shall proceed to close this issue, #please-close. If you feel that your issue has not been resolved please reopen the issue and provide additional context.
