### ISSUE TITLE
AutoML - export pre-processed data?

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#283]
Hi there,

I love the pre-process feature of autoML and am wondering if it's possible to export my pre-processed data to use elsewhere. Is that possible?

**Comment by swanderz** [comment]
@ktebbe, I also love AutoML, but, like you, I'd like to take the results of AutoML and use them for further experimentation, but that's not currently possible.  @krishnaanumalasetty says features like this are on the roadmap.

In the meantime, here's some info that might be helpful to you:

The `fitted_model` object returned by `run.get_output()`  is actually a `sklearn` `Pipeline` object, which has an attribute called `.named_steps` for unpacking exactly what the preprocessing steps are. Then you could just explicitly call those transformations on your dataset.
```
best_run, fitted_model = run.get_output()
fitted_model.named_steps
fitted_model.named_steps.(insertnamedstephere)
```
The returned tuples and dicts are somewhat helpful, I'm most interested in getting the actual estimator which is the last step of the "`Pipeline`"

**Comment by ktebbe** [comment]
Thanks @swanderz for the information. I did as you suggested, but it's hard to interpret. I'll close this and just hope that the exporting feature is added soon.

**Comment by deepamu** [comment]
Hello Kira, would love to get your inputs as we are currently designing this feature.  What would you be an ideal experience for you?  And, what do you plan to do using the pre-processed data?

**Comment by ktebbe** [comment]
Hi @deepamu - I'd love to be able to use data that has been intelligently imputed to take outside of autoML and use in R, for example. I have no specific use case in mind right now, but can definitely foresee the benefit of having access to the preprocessed data.

**Comment by deepamu** [comment]
Thanks Kira. https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-auto-train#data-pre-processing-and-featurization list some of our preprocessing steps. Based on what you mentioned, is it fair to say that imputations is the key preprocessing you care about? Are other pre-processing steps (and hence pre-processed data) interesting to you? Would love to understand how you plan to use it.

**Comment by swanderz** [comment]
@deepamu what if you could get a python snippet to reconstruct the `sklearn` Pipeline object and apply it yourself to the input dataset? I feel as if this would meet both @ktebbe and my needs.

Alternatively it'd be great to be able to provide a DataReference to AutoMLConfig that will dump the cleaned dataset in there.

**Comment by ayuwhu** [comment]
@swanderz We have a new python SDK for feature engineering that supports that reconstruction of sklearn pipeline object and apply it to the input dataset. It is in private preview now. If you are interested in trying it out, please email yuwhu@microsoft.com and I will share more instructions with you. Thank you.

**Comment by sakshamjain1998** [comment]
@ayuwhu , are there any updates related to the feature that allows us to export the data that has been preprocessed by the Azure  AtuoML framework? Or any other way of doing it.
