### ISSUE TITLE
Error when reading from conda environment.yml file

### ISSUE THREAD

**Issue by shaunirwin** [Azure/MachineLearningNotebooks#286]
Hi,

If I run the following:

```
from azureml.core import Workspace
ws = Workspace.from_config()
from azureml.core.conda_dependencies import CondaDependencies
conda_deps = CondaDependencies('./environment.yml')
print('test', list(conda_deps.conda_packages), list(conda_deps.pip_packages))
```

With the following environment.yml file, as a fairly minimal example:
```
name: azure_env
dependencies:
- python=3.6
- numpy
- pip
- pip:
  - dvc[ssh]
```

I get the following error:

```
Found the config file in: /home/deepblue/s3repos/azure_testing/config.json
Traceback (most recent call last):
  File "/home/deepblue/s3repos/azure_testing/azure_test.py", line 5, in <module>
    print('test', list(conda_deps.conda_packages), list(conda_deps.pip_packages))
  File "/home/deepblue/miniconda3/envs/azure_env/lib/python3.6/site-packages/azureml/core/conda_dependencies.py", line 262, in pip_packages
    pip_dependencies = self._filter_options(ditem[PIP], keep=False)
TypeError: string indices must be integers

Process finished with exit code 1
```

I see that I can fix this problem by omitting "- pip" from environment.yml.

Would it please be possible to allow for pip to be included in the conda environment file, as it is quite common for conda environment files to include it when using both conda and pip? In my case it would be preferable to not have to make adjustments between conda files that we use on azure and on our local machines.

My azureml library is version 1.0.21.

Thanks,
Shaun

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb6e18dd-c5d9-02dd-41ee-f12dc8152a24
* Version Independent ID: 8db0f517-4578-e32c-3162-cd95635a0dc3
* Content: [azureml.core.conda_dependencies.CondaDependencies class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by gro1m** [comment]
Hi I have the same issue. I think it would be as simple as adjusting the line `if PIP in ditem` (commented below) in the following code block, by checking that the expression found is indeed a dictionary.
```python
    @property
    def pip_packages(self):
        """Return pip dependencies.

        :return: Returns the pip dependencies. Returns a copy of pip packages, and any edits to
            the returned list won't be reflected in the pip packages of this object.
        :rtype: iter
        """
        pip_dependencies = []
        if PACKAGES in self._conda_dependencies:
            for ditem in self._conda_dependencies[PACKAGES]:
                if PIP in ditem and isinstance(ditem, dict): #if PIP in ditem:
                    pip_dependencies = self._filter_options(ditem[PIP], keep=False)

        return iter(pip_dependencies)
```
Could somebody update this, I do not seem to be able to make a PR for this.
Cheers, Michael

**Comment by pavan-kalyan** [comment]
I seem to be having the same problem, Is there a workaround for this ?
using ScriptRunConfig with a RunConfiguration which has the conda_dependecies obj seems to work, but it's not ideal.

**Comment by j-martens** [comment]
@Blackmist who is a good contact that can help with this? Can you point me in the right direction?

**Comment by Blackmist** [comment]
@j-martens Unsure. Maybe Roope. FYI, I can't reproduce the error using SDK 1.0.48 and the code/yaml from earlier in this issue. So the problem may have been resolved. It successfully loads the config and prints the following:

`test ['python=3.6', 'numpy', 'pip'] ['dvc[ssh]']`

**Comment by j-martens** [comment]
@shaunirwin . @pavan-kalyan - with the most recent SDK, are you still experiencing this issue?

**Comment by pavan-kalyan** [comment]
I was on SDK 1.0.43, when I first faced the issue.
After updating to 1.0.48, It seems to be working fine now.

**Comment by pavan-kalyan** [comment]
Since no one else seems to be having this issue anymore, I think this can be closed
