### ISSUE TITLE
AML large file support doc link

### ISSUE THREAD

**Issue by pospanet** [Azure/MachineLearningNotebooks#288]
Your total project size exceeds the limit of 300.0 MB.
Please see http://aka.ms/aml-largefiles on how to work with large files.

link above pointing to this page, but nothing related to large file is mentioned here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2464cc9-aef4-8929-142f-a1ce7ae69d78
* Version Independent ID: 7b46b2e5-965f-1a0e-7c35-686900196f6e
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py#take-snapshot-file-or-folder-path-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by chengyin38** [comment]
Having the same problem as well. Came across this: https://github.com/MicrosoftDocs/azure-docs/issues/26076. But not sure where to add `snapshot_directory=None`.

**Comment by Jess0-0** [comment]
Having the same problem as well and also not sure where to add  ```snapshot_directory=None```. @j-martens wondering if you can expand on that a little bit. My code that triggers this issue looks like this 
```
pipeline = Pipeline(workspace=ws, steps=[batch_score_step])
pipeline_run = Experiment(ws, experiment_name).submit(pipeline, pipeline_params={"param_batch_size": 8}) 
```
Thanks!

**Comment by j-martens** [comment]
Thanks for your posts. Adding others to help get answers. 

@rastala   @sanpil

**Comment by nibaccam** [comment]
@nibaccam

**Comment by sanpil** [comment]
Adding @heatherbshapiro for the AKA link and the message.
Please make sure you use a sub directory for all the associated files for a given step so we are under 300 MB. If there are bigger data files, then should be in the data store.

**Comment by Jess0-0** [comment]
After removing all the files in the subdirectory, the code is able to run further. Thank you very much for your help!

**Comment by bootsinthecity** [comment]
Hi there - I'm experiencing the same issue. I can create the workspace and the experiment just fine. I also followed the guidance here: 
https://github.com/MicrosoftDocs/azure-docs/issues/26076

To no avail. I thought perhaps my environment was causing issues because I used conda to create most of it but then needed to use pip to install azureml-sdk. The new environment did not fix it. 

I could see the kernels "running" but they were empty. I created new workspaces and experiments several times. 

![image](https://user-images.githubusercontent.com/20246821/58117266-2a9d2f80-7bcc-11e9-80bb-165094b1a89b.png)

**Comment by sanpil** [comment]
Are you creating an Estimator object? Then can you put the script and the dependent files in a subdirectory and specify that directory as the source_directory? I assume that currently, you local directory which is more than 300MB is used as the source_directory by default.

**Comment by bootsinthecity** [comment]
Hi Sanpil, 
I am trying to follow the instructions listed here: 
https://docs.microsoft.com/en-us/learn/modules/intro-to-azure-machine-learning-service/6-train-model

If I need to change the source_directory, I'm happy to do that, but is there documentation with details on how to? I'm still learning azure ml service.

**Comment by sanpil** [comment]
What is the directory from which you are launching Jupyter notebook? Before starting Jupyter Notebook (step 6), create a new sub directory and the cd to that newly created directory. Then do step 6.

**Comment by bootsinthecity** [comment]
Ahh. Ok. I can do that - I have a ton of other stuff in this directory. Who should I reach out to as a suggestion that they include this detail in the instructions for the online learning module?

**Comment by bootsinthecity** [comment]
I created a new folder and ran it in an empty folder and it worked like a charm. Thanks so much for your help. I really appreciate it! 😃

**Comment by sanpil** [comment]
@j-martens

**Comment by j-martens** [comment]
Thanks to all who have posted here. I've added a defect to  our documentation backlog to provide the following guidance if the 300MB error is encountered for snapshots:
1. Where to specify `snapshot_directory=None` and include an example.

2. Explain that users should put their scripts and the dependency files in a subdirectory and specify that directory as the `source_directory`. If there are bigger data files, then should be in the data store.

   + If you are using Jupyter notebooks, move your notebook into a new, empty, subdirectory and try again. 

   + If you are using pipelines, you can use a different sub-directory for each step.

3. Fix the aka.ms link to point to better content about large files. 

If you are satified, #please-close.

**Comment by nibaccam** [comment]
The above referenced PR addresses this issue and the  link  http://aka.ms/aml-largefiles has been updated
@pospanet 
If satisfied #pleas-close

**Comment by spacewaterbear** [comment]
> Having the same problem as well. Came across this: [MicrosoftDocs/azure-docs#26076](https://github.com/MicrosoftDocs/azure-docs/issues/26076). But not sure where to add `snapshot_directory=None`.

run = exp.start_logging(snapshot_directory=None)

**Comment by babakbiglari-py** [comment]
Hi Everyone
I am helping a partner with this error( total snapshot size exceeds the limit of 9.5367431640625 MB.) and appreciate your guidance. 

I have read above explanation and it is not solving the problem. Here is the partner setup :

Main Project Folder( PytorchTransferLearning) - Includes the following:
- PytorchTrain.py ( This has the script to load the dataset from datastore and setup the transfer learning using Alexnet + Save the model)
- PytorchProject.py ( sets up the workspace, scriptconfig) 
- XrayImages(data)
- config.json
- conda_dependencies.YAML

** already has the following code :
import azureml._restclient.snapshots_client
azureml._restclient.snapshots_client. SNAPSHOT_MAX_SIZE_BYTES = 10000000

** 
ws = Workspace.from_config()
compute_target = ws.compute_targets['TrainTorch']

src = ScriptRunConfig(source_directory='.',
                      script='PytorchTrain.py',
                      compute_target=compute_target,
                      environment=env)
                      
run = Experiment(workspace=ws, name='PytorchTrain').submit(src)
run.wait_for_completion(show_output=True)


Where do we need to add (snapshot_directory=None) to ?
Are there changes we need to make to the setup and arrangement of our codes?

Appreciate it if you could provide guidance.
