### ISSUE TITLE
Only AmlCopmute supported for mounting Data Storage

### ISSUE THREAD

**Issue by pospanet** [Azure/MachineLearningNotebooks#293]
For [mount](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.data_reference.datareference?view=azure-ml-py#as-mount--) only AmlCompute is supported. Better mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0867a8d-ffa4-768e-dcec-f527f006081b
* Version Independent ID: 1922d150-bd49-c09b-d3e0-8882bd8f36d9
* Content: [azureml.data.data_reference.DataReference class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.data_reference.datareference?view=azure-ml-py#as-mount--)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.data.data_reference.DataReference.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.data.data_reference.DataReference.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thanks for reporting. I've logged a bug for engineering.
