### ISSUE TITLE
error in description of "use_docker".

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#294]
This should not have also the description of custom_docker_image (str) parameter in the use_docker field.
use_docker
bool
A bool value indicating if the environment to run the experiment should be docker-based. custom_docker_image (str): The name of the docker image from which the image to use for training will be built. If not set, a default CPU based image will be used as the base image. Use this setting only for images available in public docker repositories. To use an image from a private docker repository, use environment_definition parameter instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e72d96a-0d5a-db01-8164-884a67c9282b
* Version Independent ID: 60110085-2bc0-7acd-7c5f-faa0cde01db5
* Content: [azureml.train.estimator.FrameworkBaseEstimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.frameworkbaseestimator?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.FrameworkBaseEstimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.FrameworkBaseEstimator.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@omartin2010 Thanks for reporting this doc issue. We have it in our backlog to address.
