### ISSUE TITLE
Broken link in https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/machine-learning-pipelines#azure-machine-learning-pipeline

### ISSUE THREAD

**Issue by pospanet** [Azure/MachineLearningNotebooks#296]
There is a list of notebooks and [link no. 10](https://aka.ms/pl-automl) is broken.

**Comment by danielsc** [comment]
I don't see the issue in the notebook anymore. Please reopen with a bit more detail if you still see the issue.
