### ISSUE TITLE
Broken link to https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig.automlconfig

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#297]
I searched "AutoMLConfig documentation" and the first [link ](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig.automlconfig)is broken.

**Comment by j-martens** [comment]
Hi! Thanks for your post. Where did you find this broken link?

**Comment by ktebbe** [comment]
I googled "AutoMLConfig documentation"

**Comment by j-martens** [comment]
Yeah, i see what you mean. Does this doc help? https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig?view=azure-ml-py

**Comment by ktebbe** [comment]
That's it! Thank you.
