### ISSUE TITLE
PipelineData's data_type parameter

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#300]
I don't know what the possible values for `data_type` are. The source code makes me think that possible values are 'str', `int`, `float`, or `bool` but I'm not sure how that would help.

What do I provide if I want it to represent json? Should I provide datatype "str"? and not even save it to file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c2ec02-ffc7-6653-e8bc-b085d951a8ed
* Version Independent ID: c15d23ad-249a-39cc-8135-1073678d5491
* Content: [azureml.pipeline.core.PipelineData class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinedata?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineData.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineData.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by sanpil** [comment]
data_type is a user defined string. You can specify the datatype of outputs which then limits which modules can use that output as input. Pipelines don't enforce that the output actually is that data type and also, providing data_type is optional.

**Comment by swanderz** [comment]
@sanpil thanks for the info. Perhaps this information should be in the documentation with `.ipynb` examples in the repo?

I haven't come across examples in this repo where any of the parameters are used, not to mention an example where a `PipelineData` object is used to indicate a single file.

See a paraphrase of my comment from #269 below.

@akshay-0 yeah I'm seeing the same thing now.

Thanks for you help through all of this. It seems my takeaway is that:
- PipelineData objects are intended by default to save single objects, and 
- the SDK will do exactly that if i come across a param like the `metrics_output` in the future.

What's the best way to make this clear to future users? Perhaps adding your output steps above to the Azure Machine Learning Pipeline with HyperDriveStep notebook?

Perhaps if i was a better dev, I could have figured this out more quickly, but I was lead astray by the following:
- every [pipeline ipynb's in this repo](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/machine-learning-pipelines) only uses `PipelineData` objects as directories to save files into,
- the error message when I tried to pass a filename (`metrics_output.json`) to the `name` parameter of `PipelineData`: "your cannot use `.`'s in the name parameter."
 `metrics_ouput = PipelineData("hd_metrics", datastore=def_blob_store)`, and
- reading the documentation's description (see below) to mean:
    "please tell us the folder where you would like the JSON to be saved"

> [`metrics_output`](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.hyper_drive_step.hyperdrivestep?view=azure-ml-py#parameters) :
> `PipelineData` or `azureml.data.data_reference.DataReference` or `azureml.pipeline.core.graph.OutputPortBinding`
> Optional value specifying the location to store HyperDrive run metrics as a JSON file

_Originally posted by @swanderz in https://github.com/Azure/MachineLearningNotebooks/issues/269#issuecomment-480405618_
