### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by gaziqbal** [Azure/MachineLearningNotebooks#308]
The AzureML SDK PyPI entry (https://pypi.org/project/azureml-sdk/#description) does not have any release notes and points to this page as the project reference. 
It was eventually able to track them down elsewhere (link below). It would very useful to add a section/link here as well.
https://docs.microsoft.com/en-us/azure/machine-learning/service/azure-machine-learning-release-notes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0be5f00-b267-a544-5e1c-36fa254f7801
* Version Independent ID: b8b3eec3-8cf4-dc39-a4e3-f2ed5fa3590d
* Content: [Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/intro?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-conceptual/intro.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-conceptual/intro.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by j-martens** [comment]
@vizhur - this makes sense. can we add a link from pypi to the release note doc?

**Comment by vizhur** [comment]
it will be updated with the next release on 07/22

**Comment by j-martens** [comment]
Thanks! I'll close the issue now. Please reopen if it continues to be an issue after 7/22.
