### ISSUE TITLE
AutoML - Information on data security

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#309]
Hello - I'm looking for any information/documentation on how AutoML, when used with the Python SDK, treats user's data (e.g. data privacy). I'm having a hard time finding it - can somebody point me to where that might be?

EDIT: I see a bit of information [here](https://azure.microsoft.com/en-us/blog/announcing-automated-ml-capability-in-azure-machine-learning/), but I'd love to have as much information as possible to ensure other stakeholders are comfortable with our adoption of AutoML.

**Comment by deepamu** [comment]
Hello Kira, thanks for the question. Can you please clarify what you'd like to see and to what level of details? We have designed AutoML with the goal of offering data privacy and not use customer data. Happy to add more documentation to clarify and provide confidence to customers. Thanks!

**Comment by Aniththa** [comment]
@ktebbe Just want to follow-up on @deepamu questions above. Feel free to reach out to us at AskAutomatedML@microsoft.com.
