### ISSUE TITLE
Stale file handle: '/databricks/python/lib/python3.5/site-packages/scipy/sparse'

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/MachineLearningNotebooks#310]
Trying to run AutoML on databricks.  Cluster config:

Mode: standard
Runtime : 5.3
Python : 3

Error when importing automl packages:

<command-3881929027467702> in <module>()
     12 from azureml.core.experiment import Experiment
     13 from azureml.core.workspace import Workspace
---> 14 from azureml.train.automl import AutoMLConfig
     15 from azureml.train.automl.run import AutoMLRun

/databricks/python/lib/python3.5/site-packages/azureml/train/automl/__init__.py in <module>()
     18 sys.path.append(vendor_folder)
     19 
---> 20 from automl.client.core.common.utilities import extract_user_data, get_sdk_dependencies
     21 
     22 from .automl import fit_pipeline

/databricks/python/lib/python3.5/site-packages/azureml/train/automl/_vendor/automl/client/core/common/utilities.py in <module>()
     21 from automl.client.core.common.constants import NumericalDtype, DatetimeDtype
     22 from automl.client.core.common.exceptions import DataException
---> 23 from sklearn import model_selection
     24 
     25 

/databricks/python/lib/python3.5/site-packages/sklearn/__init__.py in <module>()
    132 else:
    133     from . import __check_build
--> 134     from .base import clone
    135     __check_build  # avoid flakes unused variable error
    136 

/databricks/python/lib/python3.5/site-packages/sklearn/base.py in <module>()
     11 from scipy import sparse
     12 from .externals import six
---> 13 from .utils.fixes import signature
     14 from . import __version__
     15 

/databricks/python/lib/python3.5/site-packages/sklearn/utils/__init__.py in <module>()
      9 
     10 from .murmurhash import murmurhash3_32
---> 11 from .validation import (as_float_array,
     12                          assert_all_finite,
     13                          check_random_state, column_or_1d,[0m check_array,

/databricks/python/lib/python3.5/site-packages/sklearn/utils/validation.py in <module>()
     16 
     17 from ..externals import six
---> 18 from ..utils.fixes import signature
     19 from .. import get_config as _get_config
     20 from ..exceptions import NonBLASDotWarning

/databricks/python/lib/python3.5/site-packages/sklearn/utils/fixes.py in <module>()
    142     from ._scipy_sparse_lsqr_backport import lsqr as sparse_lsqr
    143 else:
--> 144     from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
    145 
    146 

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap.py in _find_spec(name, path, target)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap_external.py in find_spec(cls, fullname, path, target)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap_external.py in _get_spec(cls, fullname, path, target)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap_external.py in find_spec(self, fullname, target)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-22ce4116-d2fb-4de4-9b81-da38700c7954/lib/python3.5/importlib/_bootstrap_external.py in _fill_cache(self)

OSError: [Errno 116] Stale file handle: '/databricks/python/lib/python3.5/site-packages/scipy/sparse'

**Comment by savitamittal1** [comment]
Hello jakeatmsft,

Can you please let me know the version of SDK you have installed?

Thanks,
Savita

**Comment by jakeatmsft** [comment]
Restarting the cluster has solved this problem.  Regards.
