### ISSUE TITLE
Can't whitelist XGBoostClassifier

### ISSUE THREAD

**Issue by cywei23** [Azure/MachineLearningNotebooks#313]
When trying to whitelist XGBoostClassifier, I got the error as below. Can you please help? I have tried to put blacklist_models=None but still get this message. Same thing also happens to TensorFlowDNN and TensorFlowLinearClassifier. Are these 3 algorithms currently being turned of?
ValueError: Can not find models to train, all whitelisted models are also in blacklist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deee583c-0e11-b1da-bfe0-defb5a6f4b29
* Version Independent ID: b58f7491-6e71-29ab-f6a4-609a7d75cfed
* Content: [azureml.train.automl.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@nacharya1

**Comment by j-martens** [comment]
@deepamu

**Comment by hank1258** [comment]
Meet the same problem!!

**Comment by nagau** [comment]
@cywei23 , @hank1258 
For using XGBoost, Tensforflow pipelines, you would need to make sure that those packages are installed separately in the conda environment where you are starting the AutoML training. These packages are not part of default SDK installation.

**For local training:**
run the following in your conda env:
conda install py-xgboost<=0.80

**For remote training:**
You can follow following example to add py-xgboost to conda dependency: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/remote-amlcompute/auto-ml-remote-amlcompute.ipynb
You can find following code in the above mentioned sample notebook:
cd = CondaDependencies.create(pip_packages=['azureml-sdk[automl]'], conda_packages=['numpy','py-xgboost<=0.80'])\n",
conda_run_config.environment.python.conda_dependencies = cd

**Comment by cywei23** [comment]
Thank you! I haven't tried the remote training yet but the local run works. Have we thought about adding xgboost in the default dependency since it's a widely used model or noted somewhere in the documentation to remind people adding that?

**Comment by nagau** [comment]
@cywei23 pip package for xgboost is unstable for windows.
ref: https://pypi.org/project/xgboost/
Excerpts from above link: 
========
 Windows users: pip installation may not work on some Windows environments, and it may cause unexpected errors.
Installation from pip on Windows is therefore currently disabled for further investigation
========
Hence currently xgboost  is not included as dependency for our sdk.
But as there is a stable conda package, hence if you were to setup environment using steps at https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning#localconda you would get xgboost in your conda environment.

**Comment by cywei23** [comment]
ok got it and thanks!

**Comment by sstickney** [comment]
@nagau

Experiencing the same issue listed here. For remote compute using automl even using the example workbook you cannot pass XGBoostClassifier as a whitelisted model. Everytime I start an instance the settings pass "blacklist_algos" with ['XGBoostClassifer','XGBoostClassifier']. If I define other blacklist models, it will add them to the list, but XGBoostClassifier is always blacklisted. I've done the dependencies and checked the logs to determine it was installing xgboost, but the blacklist remains. Would appreciate any help in making the autoML classifier process also use XGBoost as a model.

**Comment by sstickney** [comment]
@nagau 

Disregard the above - for anyone running into this issue for remote compute - for some reason the check for xgboost occurs on the local environment to determine if it should be blacklisted or not. Likely a future improvement should perform this check after the docker image is built on the remote compute target, not on the local machine. Importing the xgboost library onto the machine that is initiating the runconfig and autoMLConfig will allow you to submit the experiment with XGBoostClassifier as a whitelisted algo.
