### ISSUE TITLE
ImportError: libSM.so.6: cannot open shared object file: No such file or directory on AML compute

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#317]
Hi,

I am trying to train my model on AML compute using tensorflow estimator APIs. However I have got an issue related to the envionment on compute target. please find below the error logs :

File "/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "training.py", line 151, in <module>
    train(args.dataset)
  File "training.py", line 50, in train
    import imgaug
  File "/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/imgaug/__init__.py", line 2, in <module>
    from imgaug.imgaug import *
  File "/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/imgaug/imgaug.py", line 13, in <module>
    import cv2
  File "/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

Error:
{
    "error": {
        "code": "UserError",
        "message": "libSM.so.6: cannot open shared object file: No such file or directory",
        "details": [],
        "debugInfo": {
            "type": "ImportError",
            "message": "libSM.so.6: cannot open shared object file: No such file or directory",
            "stackTrace": "  File \"azureml-setup/context_manager_injector.py\", line 90, in execute_with_context\n    runpy.run_path(sys.argv[0], globals(), run_name=\"__main__\")\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"training.py\", line 151, in <module>\n    train(args.dataset)\n  File \"training.py\", line 50, in train\n    import imgaug\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/imgaug/__init__.py\", line 2, in <module>\n    from imgaug.imgaug import *\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/imgaug/imgaug.py\", line 13, in <module>\n    import cv2\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/cv2/__init__.py\", line 3, in <module>\n    from .cv2 import *\n"
        }
    }
}
---------------------------------------------------------------------------
ActivityFailedException                   Traceback (most recent call last)
<ipython-input-7-3e699adca91c> in <module>
     24 RunDetails(run).show()
     25 
---> 26 run.wait_for_completion(show_output=True)

~/anaconda3/envs/azureml/lib/python3.6/site-packages/azureml/core/script_run.py in wait_for_completion(self, show_output, wait_post_processing, raise_on_error)
     77                     file_handle=sys.stdout,
     78                     wait_post_processing=wait_post_processing,
---> 79                     raise_on_error=raise_on_error)
     80                 return self.get_details()
     81             except KeyboardInterrupt:

~/anaconda3/envs/azureml/lib/python3.6/site-packages/azureml/core/script_run.py in _stream_run_output(self, file_handle, wait_post_processing, raise_on_error)
    321             file_handle.write("\n")
    322         if error and raise_on_error:
--> 323             raise ActivityFailedException(error_details=json.dumps(error, indent=4))
    324 
    325         file_handle.write("\n")

**ActivityFailedException: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "libSM.so.6: cannot open shared object file: No such file or directory",
        "details": [],
        "debugInfo": {
            "type": "ImportError",
            "message": "libSM.so.6: cannot open shared object file: No such file or directory",**
            "stackTrace": "  File \"azureml-setup/context_manager_injector.py\", line 90, in execute_with_context\n    runpy.run_path(sys.argv[0], globals(), run_name=\"__main__\")\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"training.py\", line 151, in <module>\n    train(args.dataset)\n  File \"training.py\", line 50, in train\n    import imgaug\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/imgaug/__init__.py\", line 2, in <module>\n    from imgaug.imgaug import *\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/imgaug/imgaug.py\", line 13, in <module>\n    import cv2\n  File \"/azureml-envs/azureml_dc24f14b45b5ae65c5316b30c5fead79/lib/python3.6/site-packages/cv2/__init__.py\", line 3, in <module>\n    from .cv2 import *\n"
        }
    }
}

it seems some shared libs are not installed correctly on compute target. How i can fix the environment on compute target since i dont have handle of it. I have also tried with enabling and disabling the use_docker option if it was happening inside docker image.

Can someone suggest something ?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed. Our apologies. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
