### ISSUE TITLE
Setting python interpreter does not work using HDI compute

### ISSUE THREAD

**Issue by richardleeaus** [Azure/MachineLearningNotebooks#319]
Hi,

Running a remote job on HDInsight does not seem to take into account the python environment i would like to use and continues to default to the 'default' python3 environment which is incorrect.

An example code snippet is below:

```
hdi_run_config = RunConfiguration()

hdi_run_config.target = hdi_compute.name


hdi_run_config.framework = "PySpark"
hdi_run_config.environment.python.interpreter_path = '/usr/bin/anaconda/envs/py35/bin/python3'
hdi_run_config.environment.python.user_managed_dependencies = True

sparkconf = SparkConfiguration()
sparkconf.configuration = {
        "spark.yarn.appMasterEnv.PYSPARK_PYTHON": "/usr/bin/anaconda/envs/py35/bin/python3",
        "spark.executorEnv.PYSPARK_PYTHON": "/usr/bin/anaconda/envs/py35/bin/python3",
        "spark.yarn.appMasterEnv.PYSPARK3_PYTHON": "/usr/bin/anaconda/envs/py35/bin/python3"
}
hdi_run_config.spark = sparkconf

src = ScriptRunConfig(
    source_directory="./code",
    script="transform/hive_data.py",
    run_config=hdi_run_config,
)

run = exp.submit(src)

```

Using a print statement in the script i'm trying to use, it signifies that it is not using the environment i have specified. e.g. i used code

```
print("Current exec:\t" + sys.executable)
```

and it printed out this

```
Current exec:	/usr/bin/python3
```

Why is it not using the environment i have specified?

Thanks

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Have you posted on the forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureMachineLearningService?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us. We see our answer was delayed. Our apologies. We did not receive a response to our post, so will close this issue for now. Should you need further assistance, please submit a post on this forum and we will respond promptly.
