### ISSUE TITLE
root_mean_squared_error causing 'parentRun configuration is invalid.' ?

### ISSUE THREAD

**Issue by rquintino** [Azure/MachineLearningNotebooks#32]
while trying to use root_mean_squared_error  on regression task got this error
(doesnt happen with different metrics?)

<class 'azureml.train.automl.exceptions.ServiceException'>: Unknown error raised. An unknown error has occurred.
<traceback object at 0x7fb9b64a4388>

~/anaconda3_501/lib/python3.6/site-packages/azureml/_restclient/operations/jasmine_operations.py in create_parent_run(self, subscription_id, resource_group_name, workspace_name, project_name, experiment_name, create_parent_run_dto, custom_headers, raw, **operation_config)
    368         if response.status_code not in [200]:
--> 369             raise HttpOperationError(self._deserialize, response)
    370 

HttpOperationError: Operation returned an invalid status code 'parentRun configuration is invalid.'

**Comment by rquintino** [comment]
same with 'root_mean_squared_log_error', normalized versions seem to work fine

**Comment by rquintino** [comment]
saw here (https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/machine-learning/service/how-to-configure-auto-train.md) that metrics RMSE are not listed (only normalized versions), although they were returned in the error message as possible options when trying to see which ones were available.
thx!

**Comment by SKrupa** [comment]
Hi Rui, thanks for reporting this issue. I've created a bug report on our side to address the error message. We have friendlier client side messages for unsupported metrics, but it looks like some aren't getting caught correctly. You should see this resolved in the November 1st release.
