### ISSUE TITLE
AutoML

### ISSUE THREAD

**Issue by shadabshaikh61** [Azure/MachineLearningNotebooks#320]
How to train AutoML on batches of data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cffb3794-72dc-cb10-be09-c8a8a8931fbe
* Version Independent ID: c762b160-c8ef-a063-431d-099bc21c37da
* Content: [azureml.train.automl package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@nacharya1 is this scenario supported? Do we have any guidance or [notebooks](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning) for this?

**Comment by nacharya1** [comment]
@shadabshaikh61 - sounds like Azure Machine Learning (AML) Pipelines can help you. AML Pipelines enables you to customize your own steps to prepare data, build/train models and deploy/predict. 
More information is available on links below 
Article - https://docs.microsoft.com/en-us/azure/machine-learning/service/concept-ml-pipelines
How to Guide - https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-your-first-pipeline
Notebook examples - https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines

**Comment by shadabshaikh61** [comment]
@nacharya1 - I don't think creating pipeline will help.
at the end AutoMLConfig accept data in single variable and that is throwing me memory error

**Comment by nacharya1** [comment]
My assumption is you want to train batches of data with automated ML. You can use pipeplines to create multiple pipes that prepare, build/train and deploy your batches of data in the way you want. Is this not you are looking to do?
Can you provide details about the memory error you are seeing, specifically the error message. Where you are training and how much is the data?
