### ISSUE TITLE
Databricks connecting to existing cluster fails without error

### ISSUE THREAD

**Issue by piizei** [Azure/MachineLearningNotebooks#323]
When creating a DatabricksStep with existing_cluster_id (with valid cluster-id), pipeline fails without any error. Cluster logs do not indicate anything. Same step without a cluster-id works (creating a new job cluster).

**Comment by skasturi** [comment]
@savitamittal1 , @jeff-shepherd

**Comment by savitamittal1** [comment]
@sonnypark , @yuezengms, can you please look into it?

**Comment by fahdkmsft** [comment]
@piizei can you please share your run id and if possible your code snippet where you create the DatabricksStep?

**Comment by j-martens** [comment]
Since we haven't heard back from you, we assume you've moved past this issue. Closing this one. Please reopen if you still need help.

**Comment by piizei** [comment]
Thanks for closing, I did not manage to replicate this on any other cluster so I assume the problem was with this particular cluster. Still would be nice to have some sort of error message.
