### ISSUE TITLE
.child_run not implemented for PipelineRun class

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#324]
My SDK version is 1.0.10. Perhaps the method is available in a newer version of the SDK?

My workaround was to use the method, `.find_step_run()` to get what I want.

```
from azureml.pipeline.core import PipelineRun
run_pipe = PipelineRun(experiment = Experiment(ws, 'attrition_steve'), run_id = "1934d2a4-2c83-4f44-beeb-52b40651cb90")
run_metrics = run_pipe.child_run( "get best run")
```

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-18-ab2d9f6e3f2e> in <module>
      1 from azureml.pipeline.core import PipelineRun
      2 run_pipe = PipelineRun(experiment = Experiment(ws, 'attrition_steve'), run_id = "1934d2a4-2c83-4f44-beeb-52b40651cb90")
----> 3 run_metrics = run_pipe.child_run( "get best run")

~\AppData\Roaming\Python\Python36\site-packages\azureml\pipeline\core\run.py in child_run(self, name, run_id, outputs)
    101         :rtype: azureml.core.run.Run
    102         """
--> 103         raise NotImplementedError("Child run is unsupported for Pipeline run.")
    104 
    105     #######################################

NotImplementedError: Child run is unsupported for Pipeline run.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1f08c12-3482-3ca6-d593-6237fdc60ff1
* Version Independent ID: d4cbab76-400b-8c64-1583-40a74de14e87
* Content: [azureml.pipeline.core.PipelineRun class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinerun?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by danielsc** [comment]
Could you explain what you are trying to do? `run.child_run` would create a child of the current run, which is not supported by `PipelineRun`s, since you children are created by defining the different steps of the pipeline.

If you want to list the child runs, then you would use `run.get_children()`. Is that what you wanted to achieve?

**Comment by danielsc** [comment]
@sanpil please make sure this is reflected in the API docs.

**Comment by sanpil** [comment]
We have a bug filed to improve documentation. However, in this case you can use .get_children() instead of .child_run()

**Comment by swanderz** [comment]
Hey @danielsc trying to remember my pain point from almost three months ago...
here's some background on some use cases.

## PipelineRun fingerprinting
we want to pull metrics (but only for certain steps) for all `PipelineRun`'s in an `Experiment`. If we use `PipelineRun.get_metrics(recursive=True)`, I get all the child runs of the hyperdrive step which i'm not interested in. with this result we could do fingerprinting on PipelineRuns and compare PipelineRuns side by side w/ something like Git diffs.

## unit test monitoring dashboard
- we have a pipeline that has a unit test step, in which a `test_results.json` is created as an output.
- we want to monitor in PowerBI the test results everytime a `PipelineRun` is submitted in an experiment.
- i thought the best way to do this would be to loop through every `PipelineRun` in an experiment and:
    - get the `StepRun` called "unit test"
    - get that `StepRun`'s output

The challenge (I think) is that `.get_children()` will return a list of runs that match a name, but I want to return exactly one step.

**Comment by vmagelo** [comment]
> @sanpil please make sure the fact that .child_run() is not implemented for PipelineRun class is reflected in the API docs.

Added. Will go live with next release of SDK reference.

**Comment by j-martens** [comment]
Thanks, Anders and Marc.
