### ISSUE TITLE
Variable is dropped causing train-within-notebook to fail (easy fix)

### ISSUE THREAD

**Issue by Fraser-Paine** [Azure/MachineLearningNotebooks#325]
When running 'train_within_notebook.ipynb' end-to-end the 13th code cell fails due to the '%%time' line at the top of the 12th code cell. 
This writes out the time but also throws away the variables created when the cell completes. 
This causes the rest of the notebook to fail when referring to 'service' which no longer exists.

This is obviously super easy to fix, but the cause of the issue might not be obvious to new users who are trying to learn from these notebooks

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue?

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us. We see our answer was delayed. Our apologies. We   did not receive a response to our post, so will close this issue for now.   Should you need further assistance, please submit a post on this forum and we   will respond promptly.
