### ISSUE TITLE
i couldnt import AutoMLConfig in my script

### ISSUE THREAD

**Issue by omnekkanti** [Azure/MachineLearningNotebooks#327]
Traceback (most recent call last):
  File "c:/Users/Om/Documents/ArcGIS 10.6.1/Automated ML/automl.py", line 9, in <module>
    from azureml.train.automl import AutoMLConfig
  File "C:\Users\Om\Anaconda3\envs\myenv\lib\site-packages\azureml\train\automl\__init__.py", line 20, in <module>
    from automl.client.core.common.utilities import extract_user_data, get_sdk_dependencies
  File "c:\Users\Om\Documents\ArcGIS 10.6.1\Automated ML\automl.py", line 9, in <module>
    from azureml.train.automl import AutoMLConfig
ImportError: cannot import name 'AutoMLConfig'

I created an environment using python 3.6.5. I read azure documentation on setting up dev environment (https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment#local). It says following

any specific python subversions can be chosen. SDK compatibility may not be guaranteed with certain major versions (3.5+ is recommended), and it's recommended to try a different version/subversion in your Anaconda environment if you run into errors. It will take several minutes to create the environment while components and packages are downloaded.

**Comment by deeptim123** [comment]
How did you create the environment and install the packages? 
We have scripts that you can use for setting up the environment on windows, linux and mac.
(automl_setup.cmd, automl_setup_linux.sh and automl_setup_mac.sh)

https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning

**Comment by omnekkanti** [comment]
should i just run it in /Users/omprakashnekkanti/anaconda3 folder. My understanding is it doesnt matter where i run it.

I tried importing in azurenotebooks as it comes pre-installed and it failed in notebooks as well. 
from azureml.train.automl import AutoMLConfig

**Comment by skasturi** [comment]
@wchill

**Comment by wchill** [comment]
@omnekkanti can you try `from azureml.train.automl.automlconfig import AutoMLConfig`? I suspect we have some wonky circular imports going on here for some reason.

**Comment by wchill** [comment]
Actually, I just noticed you named your script automl.py. Can you try naming it something else? This is probably causing the circular import.

**Comment by vladiliescu** [comment]
I had the same issue as OP, renaming my oh-so-aptly-named `automl.py` to something else fixed the issue. Thanks @wchill !

**Comment by kenkadota** [comment]
Closed per wchill
