### ISSUE TITLE
How to pass PipelineParameter to DataReference to change the input of a pipeline?

### ISSUE THREAD

**Issue by whataride** [Azure/MachineLearningNotebooks#328]
Use scenario: A user builds a pipeline to handle an input and hope to run the same pipeline whenever the input changes. The input is in blob storage.

I tried the following and it doesn't work:

```
input_para = PipelineParameter(name="input_arg", default_value='data')

blob_input_folder = DataReference(
    datastore=def_blob_store,
    data_reference_name="test_data",
    path_on_datastore=input_para
)
```
I checked the properties of a PipelineParameter object, but I don't find anything useful (name and default_value are there but not useful in this case)

The same question goes to: pass PipelineParameter to PipelineData.

**Comment by elihop22** [comment]
Please see this [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb) for an example of how to use DataPath with a PipelineParameter.
