### ISSUE TITLE
No module named 'azureml.train.estimator'

### ISSUE THREAD

**Issue by arielcedola** [Azure/MachineLearningNotebooks#329]
I'm running locally the notebook "img-classification-part1-training", in a Python 6 environment with the azureml.core version 1.0.23. When I try to create the estimator, I get the messagge:

ModuleNotFoundError: No module named 'azureml.train.estimator'

The same code runs ok on Azure Notebooks, which instead uses version 1.0.17 of azureml.core. Is there some issue with the version of the sdk? Did the estimator module change location?

Thanks!

**Comment by arielcedola** [comment]
Solved

**Comment by nemonameless** [comment]
@arielcedola  how did you solve it? please in detail
