### ISSUE TITLE
automl: are categorical columns supported?

### ISSUE THREAD

**Issue by rquintino** [Azure/MachineLearningNotebooks#33]
Hi, just testing a dataframe with mostly cat cols on pandas, is this supported already? Thanks!
# With preprocess=True
                Automl_config = AutoMLConfig(
    task='regression',
    preprocess = True,
    max_time_sec=600,
    iterations=100,
    primary_metric='normalized_root_mean_squared_log_error',
    X=X, 
    y=y,
    n_cross_validations=5)

~/anaconda3_501/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   3079             if name in self._info_axis:
   3080                 return self[name]
-> 3081             return object.__getattribute__(self, name)
   3082 
   3083     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'isna'

# Without preprocess

                Automl_config = AutoMLConfig(
    task='regression',
    preprocess = False,
    max_time_sec=600,
    iterations=100,
    primary_metric='normalized_root_mean_squared_log_error',
    X=X, 
    y=y,
    n_cross_validations=5)

Parent Run ID: AutoML_d448e304-8e28-4a3d-a9da-76af13b0f46c
***********************************************************************************************
ITERATION: The iteration being evaluated.
PIPELINE: A summary description of the pipeline being evaluated.
DURATION: Time taken for the current iteration.
METRIC: The result of computing score on the fitted pipeline.
BEST: The best observed score thus far.
***********************************************************************************************

ITERATION     PIPELINE                               DURATION                METRIC      BEST
         0                                            0:00:09.530248      179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000
ERROR: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by nagau** [comment]
@rquintino categorical (or text) data is supported with preprocess=True. You would need to update pandas to version >0.21.1 for isna() dependency. (See https://pandas.pydata.org/pandas-docs/version/0.21/whatsnew.html#na-naming-changes)
We will be fixing issue shortly, so that this dependency is explicitly pulled during install.

**Comment by rquintino** [comment]
Hi @nagau , was testing with Azure Notebooks, think it has pandas 0.20.3, will update & test again, 
thanks!

**Comment by rquintino** [comment]
seems to be running now,  updated to latest pandas, 0.23.4

conda info on update (az notebooks):

    numpy-1.14.2               |   py36hdbf6ddf_0         4.0 MB
    pandas-0.23.4              |   py36h04863e7_0        10.1 MB
    readline-7.0               |       ha6073c6_4         1.1 MB
    sqlite-3.24.0              |       h84994c4_0         1.8 MB
    wheel-0.31.1               |           py36_0          62 KB
    setuptools-40.2.0          |           py36_0         556 KB
    ------------------------------------------------------------
                                           Total:        20.0 MB

The following NEW packages will be INSTALLED:

    readline:        7.0-ha6073c6_4                        

The following packages will be UPDATED:

    certifi:         2017.7.27.1-py36h8b7b77e_0             --> 2018.8.24-py36_1     
    numpy:           1.12.1-py36he24570b_1                  --> 1.14.2-py36hdbf6ddf_0
    pandas:          0.20.3-py36h842e28d_2                  --> 0.23.4-py36h04863e7_0
    pip:             9.0.1-py36h8ec8b28_3                   --> 10.0.1-py36_0        
    python-dateutil: 2.6.1-py36h88d3b88_1                   --> 2.7.3-py36_0         
    pytz:            2017.2-py36hc2ccc2a_1                  --> 2018.5-py36_0        
    setuptools:      36.5.0-py36he42e2e1_0                  --> 40.2.0-py36_0        
    six:             1.11.0-py36h372c433_1                  --> 1.11.0-py36_1        
    wheel:           0.29.0-py36he7f4e38_1                  --> 0.31.1-py36_0        

The following packages will be DOWNGRADED:

    sqlite:          3.25.1-hb1c47c0_0          conda-forge --> 3.24.0-h84994c4_0

**Comment by skasturi** [comment]
@rastala, can you please close this issue?
