### ISSUE TITLE
Webservices: FailedACI service creation operation 

### ISSUE THREAD

**Issue by visvan** [Azure/MachineLearningNotebooks#335]
This operation fails after trying several times. May be due to score.py? 
%%writefile score.py and def init():​%%writefile score.py

**Error Step:**
%%time
from azureml.core.webservice import Webservice

# Create the webservice using all of the precreated configurations and our best model
service = Webservice.deploy_from_model(name='my-aci-svc',
                                       deployment_config=aciconfig,
                                       models=[model],
                                       image_config=image_config,
                                       workspace=ws)

# Wait for the service deployment to complete while displaying log output
service.wait_for_deployment(show_output=True)

**Error description:**

Creating image
Image creation operation finished for image my-aci-svc:6, operation "Succeeded"
Creating service
Running...........................................
FailedACI service creation operation finished, operation "Failed"
Service creation polling reached terminal state, current service state: Failed
{
  "code": "AciDeploymentFailed",
  "message": "Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance my-aci-svc.\nYou can also try to run image mlservice4565728713.azurecr.io/my-aci-svc:6 locally. Please refer to http://aka.ms/debugimage for more information.",
  "details": [
    {
      "code": "CrashLoopBackOff",
      "message": "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance my-aci-svc.\nYou can also try to run image mlservice4565728713.azurecr.io/my-aci-svc:6 locally. Please refer to http://aka.ms/debugimage for more information."
    }
  ]
}
CPU times: user 6.6 s, sys: 3.2 s, total: 9.8 s
Wall time: 8min 50s

**Comment by davidefiocco** [comment]
Try out the instructions at ttp://aka.ms/debugimage, especially debugging locally can be helpful.
A good answer to this on StackOverflow is this: https://stackoverflow.com/a/55288200/4240413

**Comment by j-martens** [comment]
We will now proceed to close this issue. Please reopen if you still need help,
