### ISSUE TITLE
Since I updated AML SDK to version 1.0.30, every call to Pipeline.publish() fails

### ISSUE THREAD

**Issue by Amalah** [Azure/MachineLearningNotebooks#339]
Prio to updating to SDK version 1.0.30 (previous version was 1.0.23),
calls to Pipeline.publish(...) did succeed.
Since I updatede to SDK 1.0.30, all calls to Pipeline.publish(...) fail with following error (stacktrace from python notebook):
----
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
&lt;ipython-input-9-5f9c2cc9b0ab&gt; in &lt;module&gt;
      1 published_pipeline1 = pipeline1.publish(name="pipeline-102-published", description="pipeline 101 published"
----&gt; 2                                         , continue_on_step_failure=True)
      3 published_pipeline1

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\pipeline.py in publish(self, name, description, version, continue_on_step_failure)
    188         """
    189         return self.graph._save(name=name, description=description, version=version,
--&gt; 190                                 continue_on_step_failure=continue_on_step_failure)

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\graph.py in _save(self, name, description, version, regenerate_outputs, continue_on_step_failure)
   2802         :rtype: azureml.pipeline.core.PublishedPipeline
   2803         """
-&gt; 2804         self._validate_and_finalize(pipeline_parameters=None, regenerate_outputs=regenerate_outputs)
   2805 
   2806         return self._context.workflow_provider.published_pipeline_provider.create_from_graph(

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\graph.py in _validate_and_finalize(self, pipeline_parameters, regenerate_outputs)
   2820 
   2821         if not self._finalized:
-&gt; 2822             self.finalize(dry_run=False, regenerate_outputs=regenerate_outputs)
   2823 
   2824     def _generate_node_id(self):

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\graph.py in finalize(self, dry_run, regenerate_outputs)
   2683 
   2684                 if new_module:
-&gt; 2685                     module_id = module_builder.build()
   2686                     print("Created step %s [%s][%s], (This step will run and generate new outputs)"
   2687                           % (node.name, node.node_id, module_id, ))

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\_module_builder.py in build(self)
     98         fingerprint = self.get_fingerprint()
     99         module_id = self._module_provider.create_module(
--&gt; 100             module_def=self._module_def, content_path=self._content_path, fingerprint=fingerprint)
    101         return module_id
    102 

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\_aeva_provider.py in create_module(self, module_def, content_path, fingerprint)
    238         if content_path is not None:
    239             is_interface_only = False
--&gt; 240             storage_id = self._module_uploader.upload(directory=content_path)
    241 
    242         properties = global_tracking_info_registry.gather_all(content_path or '.')

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\pipeline\core\_aeva_provider.py in upload(self, directory)
     64         snapshots_client = SnapshotsClient(service_context)
     65 
---&gt; 66         storage_id = snapshots_client.create_snapshot(directory)
     67 
     68         return storage_id

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\_restclient\snapshots_client.py in create_snapshot(self, file_or_folder_path, retry_on_failure, raise_on_validation_failure)
    103 
    104         # Git metadata
--&gt; 105         snapshot_properties = global_tracking_info_registry.gather_all(file_or_folder_path)
    106 
    107         with create_session_with_retry() as session:

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\_base_sdk_common\tracking\tracking_info_registry.py in gather_all(self, base_directory)
     30 
     31             for provider in self.providers:
---&gt; 32                 info.update(provider.gather())
     33 
     34             return info

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\_base_sdk_common\tracking\git_tracking_info_provider.py in gather(self)
     56 
     57         # Ask git itself to fill in any blanks.
---&gt; 58         repository_uri = repository_uri or GitTrackingInfoProvider._run_git_cmd(['ls-remote', '--get-url'])
     59         branch = branch or GitTrackingInfoProvider._run_git_cmd(['symbolic-ref', '--short', 'HEAD'])
     60         commit = commit or GitTrackingInfoProvider._run_git_cmd(['rev-parse', 'HEAD'])

C:\cont\miniconda3\envs\amls\lib\site-packages\azureml\_base_sdk_common\tracking\git_tracking_info_provider.py in _run_git_cmd(args)
     88         try:
     89             with open(os.devnull, 'wb') as devnull:
---&gt; 90                 return subprocess.check_output(['git'] + list(args), stderr=devnull).decode()
     91         except subprocess.CalledProcessError:
     92             return None

C:\cont\miniconda3\envs\amls\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--&gt; 336                **kwargs).stdout
    337 
    338 

C:\cont\miniconda3\envs\amls\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    401         kwargs['stdin'] = PIPE
    402 
--&gt; 403     with Popen(*popenargs, **kwargs) as process:
    404         try:
    405             stdout, stderr = process.communicate(input, timeout=timeout)

C:\cont\miniconda3\envs\amls\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--&gt; 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

C:\cont\miniconda3\envs\amls\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--&gt; 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: aaa79995-4d87-1c2b-c92b-3cdab7252e0c
* Version Independent ID: 7a14532f-9da3-8577-930e-4609ac2a11d6
* Content: [azureml.pipeline.core.pipeline.Pipeline class - Azure Machine Learning Python](https://docs.microsoft.com/fr-fr/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline.pipeline?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
Our team is also having issues with the pipelines module since the release of aml 1.0.30

I raised an issue on the "What's new in this release" page last week, but they still haven't gotten updated..
https://github.com/MicrosoftDocs/azure-docs/issues/29958

@heatherbshapiro @sanpil @RohitMungiMSFT @j-martens

**Comment by j-martens** [comment]
Ugh! The product manager recommended trying version 1.0.33. Hope that helps.

**Comment by Amalah** [comment]
I updated to version 1.0.33 which in fact solves the issue, thanks.
Please note that just looking at official AML service doc online, I had no clue to know that such a version 1.0.33 did exist!
