### ISSUE TITLE
Aka.ms links might need to be updated

### ISSUE THREAD

**Issue by angellmethod** [Azure/MachineLearningNotebooks#347]
https://aka.ms/azureml/concepts/datasets   -- This redirects me to the main microsoft.com page.

https://aka.ms/azureml/howto/createsnapshots  -- This one is redirecting me to the github article; I am not sure if it is intended to redirect to the docs.microsoft.com page instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ec1312-b3a5-a5fc-293b-b1f43e1035cc
* Version Independent ID: d05044b1-f65c-a4e5-4612-f4735f274cc8
* Content: [azureml.core.Dataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset%28class%29?view=azure-ml-py#head-count-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Dataset(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Dataset(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@MayMSFT

**Comment by j-martens** [comment]
@angellmethod content updating in a few days. Thanks for your report.
