### ISSUE TITLE
Is azureml-pipeline included in the azureml-defaults package?

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#352]
From the page:
> When submitting runs, the SDK by default installs the azureml-defaults package to the environment where the run is executed. It contains a small set of packages required for tasks such as logging metrics, uploading artifacts, and accessing data stores from within the run.

What packages exactly are installed? e.g. is azureml-pipelines installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30b9035-3671-a51d-5054-01313f9967ca
* Version Independent ID: 47fb4557-f0fa-6a43-e648-fd4b48921397
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by trevorbye** [comment]
@swanderz there is no such thing as azureml-pipeline(**s**), but I assume you mean azureml-pipeline. So, azureml-pipeline is not installed via azureml-defaults, but it is installed via azureml-sdk.

The setup.py file for azureml-defaults has the following dependencies list:
```python
DEPENDENCIES = [
    '{}=={}.*'.format("azureml-core", VERSION),
    # We use track_dependency that got added in 0.11.7
    "applicationinsights>=0.11.7"
]
```

**Comment by trevorbye** [comment]
@j-martens you should be able to close this one.

**Comment by swanderz** [comment]
@trevorbye thanks for the info.

Can I request that the following edit to the page?
>`azureml-defaults` contains the `azureml-core` and `applicationinsights` packages

 instead of saying
> `azureml-defaults` contains a small set of packages

If the documentation repo was open-sourced, I would have just opened a PR. Instead, my only recourse is to open an issue and ask for someone to do it for me.

**Comment by j-martens** [comment]
Thanks @swanderz - just checked in a fix.
