### ISSUE TITLE
Having problems installing OpenCV and Dlib

### ISSUE THREAD

**Issue by kishan19** [Azure/MachineLearningNotebooks#354]
Conda dependencies are not adding pip packages opencv-python and dlib, when am trying to build the run configuration for an Ubuntu DSVM. They are causing an error like the below.

   from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb6e18dd-c5d9-02dd-41ee-f12dc8152a24
* Version Independent ID: 8db0f517-4578-e32c-3162-cd95635a0dc3
* Content: [azureml.core.conda_dependencies.CondaDependencies class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies?view=azure-ml-py#add-channel-channel-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by michalmar** [comment]
This can be probaly solved by installing opencv-headless via PIP:

preview of YAML:
```
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - opencv-python-headless
```
