### ISSUE TITLE
Can we pass arguments to the docker when the server start the custom docker container?

### ISSUE THREAD

**Issue by xfdywy** [Azure/MachineLearningNotebooks#355]
When we start a job with custom docker images,  is there any methods to pass some arguments to the docker ? For example, can we achieve something like  -v -e -p   when the server run the docker container?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
