### ISSUE TITLE
StepRun should inherit Run's .download_files() method

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#357]
I have a `PipelineRun` for which I'd like to loop though all the StepRuns to download all the artifacts saved to the "outputs" dir. There are many outputs, I'd rather not specify each file for each StepRun...

```python
run_step = PipelineRun(exp, '9b13e0de-fa27-454a-84e1-204aa0037ea0')
```
this works
```python
run_step.download_file(name = "outputs/data.pkl", output_file_path = 'c:\\temp\\test-artifacts')
```
but this doesn't
```python
run_step.download_files(output_file_paths = 'c:\\temp\\test-artifacts')
```
```python
Traceback (most recent call last):
  File "download_files.py", line 33, in <module>
    run_step.download_files(output_file_path = 'c:\\temp\\test-artifacts')
AttributeError: 'PipelineRun' object has no attribute 'download_files'
```

@sanpil @akshay-0 maybe I'm off target because I can use `StepRun.get_outputs()` (see below), but it strikes me as not ideal because:
1. It makes a mess of directories I have to navigate to pull out the files, and I don't want every file, just a subset.
1. To view and download these files through the portal I'd have to also save these files to `"./outputs"`
```python
for output in run_step.get_outputs():
    (run_step
    .get_output(output)
    .get_port_data_reference()
    .download('c:\\temp\\test-artifacts', overwrite = True, show_progress = True)
    )
````
All the bugs aside, I'm most looking forward to work with you to figure best practice for persistent data storage and access for Pipeline data.

**Comment by sanpil** [comment]
Looking.

**Comment by sonnypark** [comment]
you can try: 
`run.download_files(prefix='', output_directory = 'c:\\temp\\test-artifacts')`
Note that you can specify filepath **prefix** for any subset of atifacts. But prefix='' is needed atm to download all artifacts.
For more details on [download_files](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#download-files-prefix-none--output-directory-none--output-paths-none--batch-size-100-).

**Comment by swanderz** [comment]
@sonnypark did you catch that the run object is a `StepRun` class, not a `Run` class? The method works no problem for me with the `Run` class. My issue is with the `StepRun` class

**Comment by sonnypark** [comment]
that was pipeline run since I found it from your error log:
_'**PipelineRun**' object has no attribute 'download_files'_
But it should work for both PipelineRun and StepRun. If you still see any errors with correct parameter names (**_prefix_** and **_output_dictectory_**), error details would be helpful to investigate.

**Comment by swanderz** [comment]
Also worth noting that we're on version `1.0.10` of the SDK right now.
```
AttributeError                            Traceback (most recent call last)
~\Documents\attrition\download_files.py in <module>
     85 #         )
     86 for run in [run_join, run_batch_score]:
---> 87     run.download_files(prefix='', output_directory=output_path, overwrite = True, show_progress = True)

AttributeError: 'StepRun' object has no attribute 'download_files'
```

**Comment by sonnypark** [comment]
I found **download_files** has been added around Mar. I do not think 1.0.10 has **download_files**.

**Comment by danielsc** [comment]
Please upgrade to a more recent version of the azureML Python SDK.

**Comment by swanderz** [comment]
@danielsc @j-martens if this is in the Python SDK, shouldn't it also be listed as a method in the docs?
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.steprun?view=azure-ml-py#methods

**Comment by sonnypark** [comment]
StepRun is a Run. You will see the method in the Run doc: 
![image](https://user-images.githubusercontent.com/10220522/60909142-5b93fb00-a232-11e9-8f38-b689a6574a2d.png)

**Comment by 12DReflections** [comment]
This link here was [sensational](https://www.programmersought.com/article/76424757228/) for downloading files. 

Before you can download files on the step you are required to wait for completion of the Step, which is different to waiting for completion of the run. 

```
    step_run = pipeline_run.find_step_run("train")[0]
    step_finished = run_object.wait_for_completion()['status']
    file_names = step_run.get_file_names() 
    print(step_run.get_file_names())
    file_names = step_run.get_file_names()
    for file in file_names:
        run.download_files(prefix='', output_directory='./outputs/')
```
Did the trick for me.
