### ISSUE TITLE
Failure Exception: DataException: No y values were provided.

### ISSUE THREAD

**Issue by prbans** [Azure/MachineLearningNotebooks#361]
File in question

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-energy-demand/auto-ml-forecasting-energy-demand.ipynb

## SYMPTOM

When using `fitted_model.forecast(x, y)` on y that does not immediately follow training data, forecast will fail with following error:

System.Private.CoreLib: Result: Failure
Exception: DataException: No y values were provided.

## FIX

If you supply

`fitted_model.forecast(x, y, ignore_data_errors=True)`

it will work

## SUGGESTION

It might be good to document this in the above notebook since production scenarios will unlikely have test data immediately following train data (gaps are bound to happen in production)

**Comment by Aniththa** [comment]
@prbans Thank you for sharing your feedback. We will make the update to our notebook.

**Comment by prbans** [comment]
@kenkadota - should the issue be closed before its resolved in the notebook?

**Comment by kenkadota** [comment]
@prbans We got the ok to close from the team lead. They will be updating the notebook.
