### ISSUE TITLE
difference between batch scoring using pipeline and model deployment as webservice

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#362]
Hi All,

Was curious to understand the difference between batch scoring using pipelines and deploying the model as web service ?  From my point of view when model is deployed somewhere , and we try to use it for inferencing/scoring using Rest API its as good as same thing than batch scoring pipeline. Could someone highlight the conceptual differences and in which case to use which one ?

Thanks,
Amardeep

**Comment by tracychms** [comment]
Hi Amardeep,

The major difference between batch scoring (aka, batch inference) and deploying the model as web service (aka, real-time inference) is the response latency. When you want to get inference/score right away, you should use real-time inference. When you don't need to get inferences right away, or when you have a large data set to get inferences for, you should use batch inference.

One more difference is when you use real-time inference through REST API, you need to pass the input data in http request and get the inference/score through API response (sync mode). When you create batch inference pipeline, you've already configured the data references, including both input and output. You can publish the batch inference pipeline and rerun it by using the REST endpoint, and it just triggers another pipeline run. You can check the inferences later after pipeline run finished (async mode).

Thanks,
Tracy
