### ISSUE TITLE
ACR Image Tags

### ISSUE THREAD

**Issue by zackdrescher** [Azure/MachineLearningNotebooks#366]
It looks like the create function pushes the image to the ACR with an incremented version tag. Is it possible to add another tag such as 'latest' in the ACR.

It looks like you can add tags to the image configuration but theyre only in AML not in ACR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cce8e1b-c570-b82c-2fe3-99ee0875ab37
* Version Independent ID: aba08684-7daa-2ad3-9268-0f4201a2bd14
* Content: [azureml.core.image.Image class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.image(class)?view=azure-ml-py#create-workspace--name--models--image-config-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.image.Image(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.image.Image(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by yanrez** [comment]
@jpe316

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close the issue. Should you need   assistance with another issue, please let us know and we will respond to your   post promptly.
