### ISSUE TITLE
start_time matches the week_days and time_of_day (or hour and minute)

### ISSUE THREAD

**Issue by bjcmit** [Azure/MachineLearningNotebooks#367]
When the start_time matches the week_days and time_of_day (or hour and minute) set in the ScheduleRecurrence class, there is no initial workload run the day it was schedule. I expected that the initial workload would be run at the specified start_time and the workload would be then run according to the specified parameters. If it is intended that no initial workload will be run if start_time matches the week_days and time_of_day (or hour and minute), then please change the documentation describing start_time and provide a message to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21366d06-362a-40fd-ae2d-81a6e96c4484
* Version Independent ID: 780eeaab-3b92-d6eb-3d40-f5e5011d05d7
* Content: [azureml.pipeline.core.schedule.ScheduleRecurrence class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.schedule.schedulerecurrence?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.schedule.ScheduleRecurrence.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.schedule.ScheduleRecurrence.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Added to start_time parameter to capture the message above. Will appear in next SDK release in approx 2 weeks.
