### ISSUE TITLE
Workspace.write_config() writes to a hidden folder

### ISSUE THREAD

**Issue by tarockey** [Azure/MachineLearningNotebooks#370]
It would be good to note that by default the .azureml folder that is created by write_config is hidden.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11bca2c-939e-2125-7dae-aee7d37c8844
* Version Independent ID: f362dc68-c243-df06-976d-9cc1eb5d427c
* Content: [azureml.core.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace(class)?view=azure-ml-py#write-config-path-none--file-name-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@tarockey - thanks for your report. We have created an issue internally requesting this addition to the docs. Thanks! https://msdata.visualstudio.com/Vienna/_workitems/edit/455337
