### ISSUE TITLE
Examples of mounting a datastore for AutoML

### ISSUE THREAD

**Issue by tarockey** [Azure/MachineLearningNotebooks#371]
Are there any examples of using a mounted datastore (rather than download) for training in AutoML? It appears that the path created for a mounted datastore is different than a downloaded one.

This would be set up by modifying the `auto-ml-remote-execution-with-datastore.ipynb` notebook with the following:

```python
from azureml.core.runconfig import DataReferenceConfiguration
dr = DataReferenceConfiguration(datastore_name=ds.name, 
                   path_on_datastore='data', 
                   path_on_compute='/tmp/azureml_runs',
                   mode='mount', # Mount the datastore on the compute target
                   overwrite=False)
```

**Comment by Aniththa** [comment]
Thank you for your feedback. We currently do not have an example using a mounted datastore. However, we will take this feedback.

**Comment by kenkadota** [comment]
Closed Per Ani

**Comment by kubasiak** [comment]
I have same issue. This shouldn't have been closed because there is still no solution. Does the method 'mount' use different path than 'download'?

**Comment by Aniththa** [comment]
@kubasiak You can read an environment variable in the get_data function to find the data file using a line like:
DATA_FOLDER = os.environ['AZUREML_DATAREFERENCE_<datastorename>']
where <datastorename> is the data store name

**Comment by kubasiak** [comment]
hi @Aniththa 
How do I pass the 'AZUREML_DATAREFERENCE_' to get_data()?
