### ISSUE TITLE
Reading parquet files

### ISSUE THREAD

**Issue by Menziess** [Azure/MachineLearningNotebooks#373]
I have a folder on blob storage that contains part parquet files, that together form a dataframe.

I'm receiving an UnexpectedError: 
    {'errorCode': 'Microsoft.DataPrep.ErrorCodes.Unknown', 'message': 'expected 878313 bytes in source stream but could read only 674363', 'errorData': {}}

when I try to create a Dataset from parquet files like this:

    events_data_ref = ds.path('events/parquet/*.parquet')
    dataset = Dataset.from_parquet_files(events_data_ref)

When I use the path 'events/parquet/', the following error is shown: UnexpectedError: 
    {'errorCode': 'Microsoft.DataPrep.ErrorCodes.Unknown', 'message': 'not a Parquet file (size too small)', 'errorData': {}}

Am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4a4a23-d2b0-1123-bba5-7556ed560add
* Version Independent ID: 6e350d69-726d-576f-404d-1f2ebe0b4528
* Content: [azureml.core.dataset.Dataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by tot0** [comment]
Hi Menziess,
This issue should be fixed as of `azureml-core` version `1.0.41`.
Would you mind trying again to see if this issue persists?
Cheers

**Comment by Menziess** [comment]
Thank you, a Microsoft employee has visited our company and would look into the issue personally. I can leave this Issue open to post our progress.

**Comment by Menziess** [comment]
I did some tests, and was able to read a parquet file in the folder `test/part-*`. But when I replicated our partitioned parquet file by moving the part-* files to `test/year=2019/month=4/day=14/part-*`, the following problems occured:

For each of the methods:

```python
def read_parquet_file(method, ref):
    return {
        1: dprep.auto_read_file,
        2: Dataset.auto_read_files,
        3: Dataset.from_parquet_files,
    }[method](ref)
```

I got the following errors:
ExecutionError: Failed to read files and get data source properties suggestions
ExecutionError: Failed to read files and get data source properties suggestions
ExecutionError: The provided path is not valid or the files could not be accessed.

**Comment by j-martens** [comment]
Hello. Are you still experiencing this issue?

**Comment by Menziess** [comment]
Hi, I've just tried to load the parquet file again, but I'm currently getting 
```python
HTTPError: HTTP Error 404: The specified blob does not exist.

During handling of the above exception, another exception occurred:

ValueError: Unsupported Linux distribution ubuntu 19.04
```

I can see that the blob exists using `datastore.blob_service.list_blobs(container, path)`.

**Comment by j-martens** [comment]
@nibaccam - can you see with may on the this one please?

**Comment by MayMSFT** [comment]
Hi Looks like you are using Linux ubuntu 19.04
Only 16.04 or 18.04 are supported

**Comment by nibaccam** [comment]
Hi @Menziess, did the above suggestion solve the issue? If so #please-close.

**Comment by PeterCLu** [comment]
@Menziess , since we haven't heard back from you. We will proceed to close the issue. If you feel that your issue has not resolved. Please re-open the issue with additional information
