### ISSUE TITLE
Tensorflow estimator: Unexpected keyword argument 'distributed_training'

### ISSUE THREAD

**Issue by hwuu** [Azure/MachineLearningNotebooks#375]
In https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/distributed-tensorflow-with-parameter-server/distributed-tensorflow-with-parameter-server.ipynb

When I ran the cell of creating the estimator, I encountered an error:

> TypeError: __init__() got an unexpected keyword argument 'distributed_training'

I was using Azure ML SDK Version 1.0.21.

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close the issue. Should you need  assistance with another issue, please let us know and we will respond to your post promptly.
