### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by yangsiyu007** [Azure/MachineLearningNotebooks#377]
Please add details to what the input parameters `runs` is (a list of Run objects), and what `local_root` is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1ee0e5-5dbf-99a8-8baf-517ecc53206e
* Version Independent ID: 1d321b94-2982-db21-fce7-9a81c8fbfaec
* Content: [azureml.tensorboard.Tensorboard class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-tensorboard/azureml.tensorboard.tensorboard?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-tensorboard/azureml.tensorboard.tensorboard.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-tensorboard/azureml.tensorboard.tensorboard.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thank you for this feedback. I'll open a bug internally to track this.

**Comment by j-martens** [comment]
@nibaccam / @vmagelo do we have this documented now?

**Comment by vmagelo** [comment]
@j-martens  Yes, will take up to a week to show in live docs, but we have addressed it.

**Comment by j-martens** [comment]
Thank you! We will now proceed to close this tread. Please reopen if you feel it has not be addressed.
