### ISSUE TITLE
Multiple scoring endpoints

### ISSUE THREAD

**Issue by alexHeu** [Azure/MachineLearningNotebooks#378]
Hi,

according the documentation, the scoring file needs a run(input_data) function that uses the model to generate a prediction.
This function is then exposed via the socring uri.
My question is, whether it is possible to expose multiple functions via one deployment to be able to support multiple model usage scenarios (e.g. returning a binary classification vs returning class probabilities)?

In the documentation and examples I found no way to so.
As a workaround I thought of explicitely passing the desired function name in the input_data json and then dynamically decide within the run function on which value to return.

Thanks in advance

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close the issue. Should you need assistance with another issue, please let us know and we will respond to your post promptly.
