### ISSUE TITLE
Pipeline Portal UX: log StepRun's metrics to parent PipelineRun

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#386]
### Background
Now that we have a stable pipeline infrastructure, we're enabled to do A/B testing, i.e. change one parameter to see its effect on model accuracy.
To do so, I submit two `PipelineRun`'s back to back with only one factor changed between them.

We've got a step called `get_best_run` which:
1. fetches the the best run from the previous hyperdrive step, and
2. logs the geometric_mean to the run.

I want to be able to compare,at a glance, `get_best_run`'s `geometric_mean` between two `PipelineRun`s

### Ask
It would be a HUGE win, if I could push a logged metric from a given step to the parent `PipelineRun`. This way, I could simply click on an experiment and see the resulting accuracy/lift of a model inline, without having to do a lot of extra clicking.

The difference is 3 clicks vs 11 clicks.

### Desired UX
1. Go to portal.azure.com
2. Click on ML service workspace
3. Click on Experiments in sidebar
4. Click on desired experiment
![image](https://user-images.githubusercontent.com/8158673/58140411-ffc6d180-7bf3-11e9-9392-8a5fae4efbce.png)
### Current UX
1. Click on a `PipelineRun`'s `run_id`
2. Click on the `get_best_run`'s `run_id`, then find geometric_mean (and write it down somewhere so you don't forget :stuck_out_tongue:)
4. Click "Back to Parent"
5. Click "Back to Experiment"
6. Repeat steps 1-5 for other experimental PipelineRuns
![image](https://user-images.githubusercontent.com/8158673/58140669-f853f800-7bf4-11e9-93df-20f0e7a69342.png)

![image](https://user-images.githubusercontent.com/8158673/58140702-20dbf200-7bf5-11e9-9bae-ec78b3293d9f.png)

**Comment by swanderz** [comment]
cc: @sanpil @jpe316 @heatherbshapiro

**Comment by sanpil** [comment]
I have captured this request in our backlog. Thank you!

**Comment by swanderz** [comment]
To confirm, does the SDK not allow logging metrics to a parent PipelineRun from within a StepRun? The portal UX isn't as interesting to me as the ability to do so w/ the SDK

**Comment by danielsc** [comment]
Yes, you are able to log to a parent of the current run. So in your pipeline step just execute:
```
from azureml.core import Run
Run.get_context().parent.log("foo", 100)
```
And you should get the below output:
![image](https://user-images.githubusercontent.com/8079390/60987352-44b6dc80-a2f6-11e9-90bf-efb3d1f70494.png)
