### ISSUE TITLE
ws.get_default_datastore() returns the workspaceblobstore instead of the workspacefilestore

### ISSUE THREAD

**Issue by ATGardner** [Azure/MachineLearningNotebooks#388]
This effects the pipeline tutorials, at least. for example, in how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-getting-started.ipynb, but also in the next notebook named aml-pipelines-with-data-dependency-steps.ipynb

It might also happen in other notebooks as well.

I don't know if this is a change in the azureml SDK, or with the AML service default store definitions, but the fact is that the examples expect the call to
```
# Default datastore (Azure file storage)
def_file_store = ws.get_default_datastore()
```
to return a filestore, and it returns a blobstore.
I locally changed the calls to
```
def_file_store = Datastore(ws, "workspacefilestore")
```
just to continue along with the sample

**Comment by j-martens** [comment]
@sanpil @yanrez looks like the notebooks need updated. Can you investigate and respond please?

@ATGardner thanks for your report!

**Comment by sanpil** [comment]
There were two Notebooks that showed this. The one mentioned above and aml-pipelines-publish-and-run-using-rest-endpoint.ipynb. I have a PR out to update them.

**Comment by j-martens** [comment]
@sanpil thank you so much. We'll proceed to close the issue now. Please reopen if it isn't showing the fix next week. thanks for your report @ATGardner
