### ISSUE TITLE
Invalid provisioning configuration, max nodes count is mandatory

### ISSUE THREAD

**Issue by nathansegers** [Azure/MachineLearningNotebooks#389]
When trying to use the default value for `max_nodes = None`, I receive the ComputeTargetException: invalid provisioning configuration, max nodes count is mandatory.

Shouldn't the default value be set to 1 then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135e6941-63a3-bfef-298d-d97c633c5fae
* Version Independent ID: 2c23acd7-e9e7-e626-9299-546cab8d8f06
* Content: [azureml.core.compute.AmlCompute class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.amlcompute(class)?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.compute.AmlCompute(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.compute.AmlCompute(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@nishankgu - is this correct? Do we need to change the docs?
@nathansegers thanks for your report and question. Investigating...

**Comment by nishankgu** [comment]
No we want the cusotmer to specifically make a decision on which VM family and how many nodes they want the c;luster to scale to. Those are the only two fields that we want from the customer to make a conscious decision while setting up the cluster - all the other fields have defaults!
