### ISSUE TITLE
Service Principal Authentication in Sample notebooks is outdated

### ISSUE THREAD

**Issue by syedsadiqalinaqvi** [Azure/MachineLearningNotebooks#391]
There are notebooks present at 

https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml

which talk about different ways of authentication. One of them is Service Principal Authentication, along with screenshots, for automated workflows. 

Microsoft has recently updated the Azure Active Directory feature and it's UI has changed significantly (options have shifted from one section to another and names have changed). This link talks about these changes:

https://docs.microsoft.com/en-us/azure/active-directory/develop/app-registrations-training-guide
 
Please update the notebooks and the screenshots in them for better guidance of customers.

Thanks.

**Comment by j-martens** [comment]
@aashishb can you comment for the notebook please? 

cc: @Blackmist - FYI for doc impacts

**Comment by rastala** [comment]
It should be up-to-date now.
