### ISSUE TITLE
Executing a local python file on Databricks doesn't get the input/output parameters

### ISSUE THREAD

**Issue by ATGardner** [Azure/MachineLearningNotebooks#392]
I am trying to follow the examples on `aml-pipelines-use-databricks-as-compute-target`, with the option of executing a local file on the Databricks cluster.
The example as it is works fine, but the py file doesn't do anything with the input or output parameters. I tried changing it to
```
print('In train-db-local.py')

dbutils.widgets.get('blob_input_data')
print('after')
```
And it crashes while telling me it can't find the `blob_input_data` input param.

My DataReference and Step definitions are:
```
blob_input_data = DataReference(
    datastore = datastore,
    data_reference_name = "blob_input_data",
    path_on_datastore = ".")
runLmStep = DatabricksStep(
    name = "RunLM",
    inputs = [blob_input_data],
    num_workers = 1,
    python_script_name = "train-db-local.py",
    source_directory = source_directory,
    run_name = 'Run LM',
    compute_target = databricks_compute,
    allow_reuse = True,
)
```
I tried playing around with or without the `python_script_params` field, and couldn't get it to work. The example notebook does not show how to do this with a local file, and also with a remote file on dbfs it's not clear.

**Comment by ATGardner** [comment]
I think I figured out how to do this - when using a standard py script, I should just use the standard libraries to parse arguments. I changed my py file to use argparse, added all the default parameters, and the input/output parameters (mathcing the name I give in the DataReference). Now it seems to work.

**Comment by jcalcant** [comment]
Hi! I am having the same issue. Can you provide a code example of your now working databricksstep, DataReference creation, and the part of your script where you get the input/output parameters. Thanks!!

**Comment by anirbansaha96** [comment]
@ATGardner can you please provide a sample of what worked for you. I am facing a similar issue.

**Comment by anirbansaha96** [comment]
@lostmygithubaccount Can you please look into this
