### ISSUE TITLE
Spark MPI Estimator Run continues running even after Experiment failed appears in log

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#398]
I submitted a run, that show that it failed after 5 minutes and yet the status of the run never went to "Failed" it just staying at "Running" for two hours until I manually cancelled it in the portal.

The error I was able to fix, but I'm flagging that the run never stopped, when I believe that I should have. Am I missing something? Do Spark / MPI jobs have retries built in?

`run_id`: `attrition-compute_test_1559078053_34ffd427`
[Here's a link ](https://gist.github.com/swanderz/4fd2f7cf20dedaf533d506d09ffbc0e7) to the:
- Estimator definition, 
- script I ran,
- `azureml-log\80_driver_log_rank_0.txt`, and
-`logs\azureml\azureml.log`

**Comment by swanderz** [comment]
Here's another example `run_id=attrition-compute_test_1559145929_1528c023`

**Comment by swanderz** [comment]
I spent all day making a reproducible example.
Here is the [Jupyter notebook](https://github.com/swanderz/MachineLearningNotebooks/blob/spark_fail_repro/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-how-to-use-estimatorstep.ipynb) committed with it in this fork are also necessary files to run it yourself.

![image](https://user-images.githubusercontent.com/8158673/59390108-2aa0d300-8d25-11e9-9282-dab1145639fa.png)

**Comment by swanderz** [comment]
#408 is the same

**Comment by ninghu** [comment]
@swanderz , could you provide the batchai logs which can be found in the blob store of your workspace: azureml-blobstore-{some guid}/batchai_logs

**Comment by swanderz** [comment]
@ninghu [here's a link to a zipped folder with all the logs](https://www.dropbox.com/s/kar98latzr3475b/logs.zip?dl=0) shown below:
![image](https://user-images.githubusercontent.com/8158673/59473376-1af1bf00-8df7-11e9-87bb-c84dfab50e36.png)

The Run failed 5 min after switching from "Queued" to "Running", but after two hours the Run was still going so I manually cancelled it.

**Comment by ninghu** [comment]
@swanderz, Thank you so much! 

@sogansky and I looked at the logs that you provided. Basically, there are two problems here:
1. It appears the user process actually doesn't exit as there is no "Script process exited with code.." found in the execution log. It might be caused by some thread that spawned by the main thread is still running or some other reason like atexists get stuck. You will need to check what's actually holding the process from exiting.

2. "Experiment failed..." is printed as soon as the main thread exited instead of user process.  This is all the confusion comes from. It is a known issue at our side and will be addressed soon!

**Comment by swanderz** [comment]
Wow thanks looking into this. To be clear, for repro this bug, intentionally introduced an error by having Spark try to execute SQL with a typo for a column name. In my head, the experiment failed is printed at the right time because that's when my script hits the error. I'm still confused why the user process hangs... it fails exactly like it should when I don't pass an MpiConfig and run the step on a single node

**Comment by ninghu** [comment]
The problem might be related to MPI then. I also see tons of "mpirun: Forwarding signal 10 to job" messages in log "56_batchai.stderr.txt". Not MPI expert so don't too much idea about this message. I guess the job actually exits but maybe mpirun process get stuck somehow.  

Curious if job hangs after fixing the user error?

**Comment by swanderz** [comment]
Nope the job completes when the column name is spelled correctly. The reason we're flagging this is that the "failure to fail" kept our VMs spinning for days which cost us a lot of $$$. I agree that it seems to be an issue w/ MPI, but as noob as they come w.r.t. MPI

**Comment by ninghu** [comment]
Agreed. We need to implement some mechanism to detect job hangs to stop the bleeding. Just let you know that this feature is already in our plan.

Also, in case you are not aware of, there is one parameter on Estimator called "max_run_duration_seconds". If the run takes longer than the value specified. the system will cancel run. It helps in some cases.

**Comment by swanderz** [comment]
@ninghu  @sogansky thanks for the help here identifying the specific bugs. the  `max_run_duration_seconds` is definitely helpful, thanks for the heads up. I'd close this ticket on GitHub, but I think it is probably better to leave it open until the bug you mentioned gets resolved.

**Comment by v-strudm-msft** [comment]
Confirmed this bug was resolved and issue is now closed.
