### ISSUE TITLE
Azure configuration notebook link is broken

### ISSUE THREAD

**Issue by sfilipi** [Azure/MachineLearningNotebooks#405]
The link to the configuration notebook in the [train-within-notebook.ipynb](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/train-within-notebook/train-within-notebook.ipynb) is 404. 

Link:
https://render.githubusercontent.com/configuration.ipynb

**Comment by j-martens** [comment]
Thanks for your report @sfilipi 
I couldn't reproduce. I'm closing this issue for now. Please reopen if you are still experiencing this issue.
