### ISSUE TITLE
"Machine Learning Studio Workspace" versus "Machine Learning service workspaces"

### ISSUE THREAD

**Issue by sfilipi** [Azure/MachineLearningNotebooks#406]
The notebooks, specifically [train-within-notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/train-within-notebook/train-within-notebook.ipynb) suggest creating a "AzureML Workspace". 

Should this be a "Machine Learning Studio Workspace" or a"Machine Learning service workspaces"?
Those are the only two relevant options that appear in the Azure portal.

**Comment by swinner95** [comment]
Refers to a Machine Learning service workspace.

**Comment by vishmonne** [comment]
what is the difference between machine learning studio workspace vs machine learning service workspace?
