### ISSUE TITLE
PipelineRuns and StepRuns can't be cancelled from the portal

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#407]
## Request
As initially brought up in #400, `StepRun`'s and `PipelineRun`'s can't be cancelled from the portal.
![portal](https://user-images.githubusercontent.com/8158673/58739572-da8a4e00-83bf-11e9-82de-23bbd4c1d51c.png)

**Comment by DebFro** [comment]
bug has been addressed, if you are still experiencing this issue please re-open.
