### ISSUE TITLE
Cannot create a new Azure resource group and a new workspace.

### ISSUE THREAD

**Issue by kritdikoon** [Azure/MachineLearningNotebooks#41]
This seems to be a simple question, it takes me long time.
Could anyone help me?

I try to create a new Azure resource group and a new workspace as below manual.
https://docs.microsoft.com/en-us/azure/machine-learning/service/quickstart-create-workspace-with-python

Python code
```
ws = Workspace.create(name='myaml',
                      subscription_id='xxxxxx-xxxx-xxxx-8ea0-991809afd024'
                      resource_group='Test',
                      create_resource_group=True,
                      location='Japan East' # or other supported Azure region
                     )
```

There is an error below:

  **File "<ipython-input-45-5d691351b38c>", line 3
    resource_group='Test',
                 ^
SyntaxError: invalid syntax**

What is wrong with above code?

**Comment by rquintino** [comment]
Hi would say missing comma after subscription_id='xxxxxx-xxxx-xxxx-8ea0-991809afd024'

**Comment by kritdikoon** [comment]
> Hi would say missing comma after subscription_id='xxxxxx-xxxx-xxxx-8ea0-991809afd024'

Many thanks rquintino
comma solves the issue.

**Comment by rastala** [comment]
This issue has been fixed.
