### ISSUE TITLE
How to delete a pipline from the ML Service

### ISSUE THREAD

**Issue by ashoksamal6363** [Azure/MachineLearningNotebooks#410]
How to delete a pipline from the ML Service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa79995-4d87-1c2b-c92b-3cdab7252e0c
* Version Independent ID: 7a14532f-9da3-8577-930e-4609ac2a11d6
* Content: [azureml.pipeline.core.pipeline.Pipeline class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline.pipeline?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@yanrez - where is delete covered? thanks!

**Comment by yanrez** [comment]
You should disable pipeline, it will hide it from ui and block triggers

p = PublishedPipeline.get(ws, id="068f4885-7088-424b-8ce2-eeb9ba5381a6")
p.disable()

you can recover it later using p.enable()

**Comment by ficocesari** [comment]
Could you please add disable pipeline functionality in the UI?

**Comment by CloudBreadPaPa** [comment]
+1 
@yanrez @j-martens any plan of "delete()" method for published pipeline?
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.publishedpipeline?view=azure-ml-py

**Comment by majidaldo** [comment]
yya that's not deleting! disabling is not deleting! it's still there!

**Comment by yanrez** [comment]
@balapv

**Comment by lostmygithubaccount** [comment]
I assume this should be reopened? Let me know if not.

**Comment by majidaldo** [comment]
It's not a doc issue. It's a AML issue.

**Comment by shbijlan** [comment]
Currently, the best way to clean up pipelines is to disable them from appearing in the UI. We have the feedback for a feature to delete pipelines documented and in our backlog. It will be reviewed in our planning cycle for future implementation.
