### ISSUE TITLE
Need default AMLCompute to run this sample notebook ?

### ISSUE THREAD

**Issue by konabuta** [Azure/MachineLearningNotebooks#413]
Running [this notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-keras/train-hyperparameter-tune-deploy-with-keras.ipynb) failed with error. This message show that I don't have default AmlCompute, while I create several AmlComputes in Azure Portal. 

It is confusiing. I think this notebook is assuming Azure ML workspace has default AmlCompute. But many users create Azure ML workspace in Azure Portal that doesn't create default AmlCompute. Hope the notebook will be fixed.

![image](https://user-images.githubusercontent.com/3815677/59031572-01a0be00-889f-11e9-86c2-e66b71935096.png)

![image](https://user-images.githubusercontent.com/3815677/59031719-770c8e80-889f-11e9-991b-5778caf7f195.png)

**Comment by rastala** [comment]
The notebooks have been updated to create compute if one is not available.
