### ISSUE TITLE
Using AzureMLTokenAuthentication fails because it doesn't implement _get_all_subscription_ids

### ISSUE THREAD

**Issue by ATGardner** [Azure/MachineLearningNotebooks#414]
I want to get a reference to my Workspace from inside a DatabricksStep, and it keeps failing because of that.

Also - what should the "host" parameter contain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d3c511e-176a-3f49-eceb-24b6b43f5706
* Version Independent ID: 5520641b-d61b-19ad-19db-7d3f22d90849
* Content: [azureml.core.authentication.AzureMLTokenAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.azuremltokenauthentication?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.authentication.AzureMlTokenAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.authentication.AzureMlTokenAuthentication.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.

**Comment by brunocous** [comment]
Too bad, this issue is already closed, because I facing the same issue.
