### ISSUE TITLE
Setting AZUREML_OUTPUT_UPLOAD_TIMEOUT_SEC results in error

### ISSUE THREAD

**Issue by arconederveen** [Azure/MachineLearningNotebooks#422]
Hi,

I was asked in the forum 

https://social.msdn.microsoft.com/Forums/azure/en-US/a002144b-669b-46dc-b8f8-47737148d37b/setting-azuremloutputuploadtimeoutsec-results-in-error?forum=AzureMachineLearningService

to submit a bug.

I wanted to increase the time out after I got this error on a former run with about 500MB in the outputs folder.

`ERROR:: OutputUpload failed. Output files can be accessed in the project working directory directly.. Exception Details:Traceback (most recent call last): File "/mnt/batch/tasks/shared/LS_root/jobs/argusml/azureml/train_yolo_full_1559718832_e006a7ea/mounts/azureml_project_share/azureml/train_yolo_full_1559718832_e006a7ea/azureml-setup/context_managers.py", line 74, in __exit__ self.history_context.__exit__(*args) File "/usr/local/lib/python3.5/dist-packages/azureml/_history/utils/context_managers.py", line 54, in __exit__ return self._exit_stack.__exit__(*args) File "/usr/lib/python3.5/contextlib.py", line 357, in __exit__ raise exc_details[1] File "/usr/lib/python3.5/contextlib.py", line 342, in __exit__ if cb(*exc_details): File "/usr/lib/python3.5/contextlib.py", line 258, in _exit_wrapper return cm_exit(cm, *exc_details) File "/usr/local/lib/python3.5/dist-packages/azureml/_history/utils/context_managers.py", line 208, in __exit__ self.file_watcher.join() File "/usr/lib/python3.5/threading.py", line 1054, in join self._wait_for_tstate_lock() File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock elif lock.acquire(block, timeout): File "/mnt/batch/tasks/shared/LS_root/jobs/argusml/azureml/train_yolo_full_1559718832_e006a7ea/mounts/azureml_project_share/azureml/train_yolo_full_1559718832_e006a7ea/azureml-setup/utility_context_managers.py", line 205, in _raise_timeout_error action_message)) SystemExit: Operation OutputUpload timed out after 600 sec. The timeout can be adjusted using AZUREML_OUTPUT_UPLOAD_TIMEOUT_SEC environment variable`

If I try to increase the AZUREML_OUTPUT_UPLOAD_TIMEOUT_SEC like so

`run_config.environment.environment_variables = {'AZUREML_OUTPUT_UPLOAD_TIMEOUT_SEC' : 1800}`

this results in the following error:

`ERROR:: OutputUpload failed. Output files can be accessed in the project working directory directly.. Exception Details:Traceback (most recent call last): File "/mnt/batch/tasks/shared/LS_root/jobs/******/azureml/train_yolo_full_1559821882_896b49cb/mounts/azureml_project_share/azureml/train_yolo_full_1559821882_896b49cb/azureml-setup/context_managers.py", line 72, in __exit__ timeout_envvar=self.timeout_envvar) if not azureml_globals.is_hdi else dummy(): File "/mnt/batch/tasks/shared/LS_root/jobs/******/azureml/train_yolo_full_1559821882_896b49cb/mounts/azureml_project_share/azureml/train_yolo_full_1559821882_896b49cb/azureml-setup/utility_context_managers.py", line 210, in __enter__ signal.alarm(self.timeout_sec) TypeError: an integer is required (got type str) `

How can increase the timeout or make sure the upload finishes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a52b4ac-50be-de5e-f374-0942b5c79091
* Version Independent ID: e37013e0-7618-9c14-a0af-9c9c305776df
* Content: [azureml.core.environment.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by kenkadota** [comment]
Closed per D. Schneider

**Comment by arconederveen** [comment]
What does "Closed per D. Schneider"  mean?
