### ISSUE TITLE
Way's to install pip packages

### ISSUE THREAD

**Issue by lucas95123** [Azure/MachineLearningNotebooks#430]
Is there any way to install some package from a particular --index-url while others from the default source?

**Comment by rastala** [comment]
You should be able to do this for example for script run. The conda dependency specification contains  https://pypi.python.org/simple as extra index by default.
```
from azureml.core import ScriptRunConfig
from azureml.core.conda_dependencies import CondaDependencies

cd = CondaDependencies.create(pip_indexurl="custom-index")

src = ScriptRunConfig(".","example.py")
src.run_config.conda_dependencies = cd
```

**Comment by kenkadota** [comment]
Closed per rastala
