### ISSUE TITLE
"Tenant Null Not Found" - Connect to Azure Auth  

### ISSUE THREAD

**Issue by SG-Gank** [Azure/MachineLearningNotebooks#432]
Hi AZML Notebook Team: 

While I am trying to connect to Azure in my notebook, I am encountering the following issue: 

"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator."

I am the owner of the notebook. 

Here's some more details:

Request Id: 8ad904b2-0fc7-4a7d-b697-26acceb40e00
Correlation Id: b55370f1-224a-4413-82e8-a31502fff332
Timestamp: 2019-06-13T22:45:07Z
Message: AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Advanced diagnostics: Enable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**Comment by SG-Gank** [comment]
"https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1346"

This issue was seen in this thread too.

**Comment by pjevans** [comment]
Same issue.  My team wants to now use AzureMachineLearning studio and they need a data workbench to work with the files...  They want to use Azure Blob Storage, which is great, but this annoying authentication issue has now completely road-blocked us.

**Comment by blossomplaza** [comment]
I ran into the same issue here. Looking forward to this getting resolved quickly

**Comment by DebFro** [comment]
Per "AzureAD/azure-activedirectory-library-for-dotnet#1346" this is Resolved by reverting the assembly "Microsoft.IdentityModel.Clients.ActiveDirectory" to Version=3.13.9.1126.
Using latest version of this assembly raised this issue. Version = 4.4.0.0
