### ISSUE TITLE
This page says that FPGA images are preview; they aren't. They are GA

### ISSUE THREAD

**Issue by davidly** [Azure/MachineLearningNotebooks#440]
FPGA images are GA, not preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037e6d0f-3167-d87a-f25f-326ca1c89ee1
* Version Independent ID: 71fe62be-fbc1-8289-c971-5b19a2b7d9d4
* Content: [azureml.core.Image class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image(class)?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Image(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Image(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thanks for your report!! We'll fix in the next SDK doc push. 
#please-close

**Comment by davidly** [comment]
Awesome, thanks!
