### ISSUE TITLE
Problem with get_steps()

### ISSUE THREAD

**Issue by ashoksamal6363** [Azure/MachineLearningNotebooks#442]
pipeline_run.find_step_run(name) works fine but why pipeline_run.get_steps() not returning a list?
O/P: &lt;generator object Run._rehydrate_runs at 0x7f4dc6ab9990&gt;

Can some one help me to understand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1f08c12-3482-3ca6-d593-6237fdc60ff1
* Version Independent ID: d4cbab76-400b-8c64-1583-40a74de14e87
* Content: [azureml.pipeline.core.PipelineRun class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinerun?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by danielsc** [comment]
The API returns a generator since the creation of each individual object could potentially be expensive.
If you need a list, you can just type:
```
list(pipeline_run.get_steps())
```
