### ISSUE TITLE
Model deployed as webservice on AKS is not stable

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#450]
I have deployed a deep learning tensorflow model on AKS compute. Model has been deployed successfully but service is unstable. Its frequently returning 502 or 503 and client have to keep retrying for successful execution of service.

Service response is :

WebserviceException: Received bad response from service:
Response Code: 502
Headers: {'server': 'Cowboy', 'date': 'Tue, 25 Jun 2019 09:40:13 GMT', 'content-length': '41', 'cache-control': 'max-age=0, private, must-revalidate', 'x-ms-request-id': 'ae21c07c-26b7-401e-858b-1d63c59605af'}
Content: b'Replica closed connection before replying'

**Comment by jpe316** [comment]
@vaidya-s

**Comment by DebFro** [comment]
As no further detail regarding this issue has been provided to assist with troubleshooting, I am closing this issue at this time.
