### ISSUE TITLE
Fail to convert the TensorFlow graph to ONNX with AttributeError: 'SwigPyObject' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by wtam** [Azure/MachineLearningNotebooks#451]
execute below code:
convert_request = AccelOnnxConverter.convert_tf_model(ws, registered_model, input_tensor, output_tensor)

return AttributeError: 'SwigPyObject' object has no attribute '__dict__'  and detail log below

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-cebb1e8bf4bd> in <module>
      2 from azureml.accel import AccelOnnxConverter
      3 
----> 4 convert_request = AccelOnnxConverter.convert_tf_model(ws, registered_model, input_tensor, output_tensor)
      5 # If it fails, you can run wait_for_completion again with show_output=True.
      6 # above code generte AttributeError: 'SwigPyObject' object has no attribute '__dict__'

~/anaconda3_501/lib/python3.6/site-packages/azureml/accel/_accel_onnx_converter.py in convert_tf_model(workspace, source_model, input_node, outputs_nodes, require_fpga_conversion)
     56         # create model convert client and start model conversion
     57         client = ModelConvertClient(workspace)
---> 58         operation_id = client.convert_model(request)
     59 
     60         # create and return ModelConvert operation

~/anaconda3_501/lib/python3.6/site-packages/azureml/_model_converters/_model_convert_client.py in convert_model(self, request)
     48             raise Exception('Model id is missing in the request {}.'.format(request))
     49 
---> 50         json_payload = json.loads(request.toJSON())
     51 
     52         try:

~/anaconda3_501/lib/python3.6/site-packages/azureml/_model_converters/_model_convert_request.py in toJSON(self)
     81 
     82     def toJSON(self):
---> 83         return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)

~/anaconda3_501/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

~/anaconda3_501/lib/python3.6/json/encoder.py in encode(self, o)
    199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
--> 201             chunks = list(chunks)
    202         return ''.join(chunks)
    203 

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    436                 markers[markerid] = o
    437             o = _default(o)
--> 438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:
    440                 del markers[markerid]

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    428             yield from _iterencode_list(o, _current_indent_level)
    429         elif isinstance(o, dict):
--> 430             yield from _iterencode_dict(o, _current_indent_level)
    431         else:
    432             if markers is not None:

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    436                 markers[markerid] = o
    437             o = _default(o)
--> 438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:
    440                 del markers[markerid]

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    428             yield from _iterencode_list(o, _current_indent_level)
    429         elif isinstance(o, dict):
--> 430             yield from _iterencode_dict(o, _current_indent_level)
    431         else:
    432             if markers is not None:

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    436                 markers[markerid] = o
    437             o = _default(o)
--> 438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:
    440                 del markers[markerid]

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    428             yield from _iterencode_list(o, _current_indent_level)
    429         elif isinstance(o, dict):
--> 430             yield from _iterencode_dict(o, _current_indent_level)
    431         else:
    432             if markers is not None:

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3_501/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    435                     raise ValueError("Circular reference detected")
    436                 markers[markerid] = o
--> 437             o = _default(o)
    438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:

~/anaconda3_501/lib/python3.6/site-packages/azureml/_model_converters/_model_convert_request.py in <lambda>(o)
     81 
     82     def toJSON(self):
---> 83         return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)

AttributeError: 'SwigPyObject' object has no attribute '__dict__'

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
