### ISSUE TITLE
 Databrick automl AssertionError: 

### ISSUE THREAD

**Issue by kritdikoon** [Azure/MachineLearningNotebooks#453]
Environment: 
Azure Databricks
5.3 (includes Apache Spark 2.4.0, Scala 2.11)
Python Version 3

Refer to below notebook, I cannot import  automl
automl-databricks-local-01.ipynb
Could you advise how to fix this issue.
===========================
azureml-sdk with automated ml
Source: Upload Python Egg or PyPi
PyPi Name: azureml-sdk[automl_databricks]
Select Install Library

===========================

import azureml.core
print("SDK Version:", azureml.core.VERSION)
------------------------------
SDK Version: 1.0.45

=========================

from azureml.train.automl import AutoMLConfig
from azureml.train.automl.run import AutoMLRun

----------------------
Error:

/databricks/python/lib/python3.5/site-packages/azureml/train/automl/automl.py in <module>()
      8 import pandas as pd
      9 import scipy
---> 10 from automl.client.core.common.datasets import ClientDatasets
     11 from automl.client.core.common import logging_utilities
     12 from azureml.automl.core import data_transformation, fit_pipeline as fit_pipeline_helper

/databricks/python/lib/python3.5/site-packages/azureml/automl/core/_vendor/automl/client/core/common/datasets.py in <module>()
     16 from sklearn import model_selection
     17 
---> 18 from automl.client.core.common import constants, problem_info, utilities
     19 from automl.client.core.common._cv_splits import FeaturizedCVSplit, _CVSplits, _CVType
     20 from automl.client.core.common.cache_store import MemoryCacheStore

/databricks/python/lib/python3.5/site-packages/azureml/automl/core/_vendor/automl/client/core/common/problem_info.py in <module>()
     11 import json
     12 
---> 13 from automl.client.core.common import constants, resource_limits
     14 from automl.client.core.common.constants import \
     15     TimeConstraintEnforcement as time_constraint

/databricks/python/lib/python3.5/site-packages/azureml/automl/core/_vendor/automl/client/core/common/resource_limits.py in <module>()
     46 
     47 # use this for module functions
---> 48 class SafeEnforceLimits:
     49     """Class to allow for early termination of an execution."""
     50 

/databricks/python/lib/python3.5/site-packages/azureml/automl/core/_vendor/automl/client/core/common/resource_limits.py in SafeEnforceLimits()
     57     except ImportError as e:
     58         # this is the error we're expecting
---> 59         assert str(e) == "No module named 'resource'"
     60         ok = False
     61 

AssertionError:

**Comment by Aniththa** [comment]
@kritdikoon are you still facing this issue? I tried recreating a new cluster today and was not able to reproduce your error. Can you please delete the SDK package and try attaching azureml-sdk[automl_databricks] to the same cluster? Feel free to reach out to AskAutomatedML@microsoft.com if you have additional questions.

**Comment by kenkadota** [comment]
Closed per Aniththa
