### ISSUE TITLE
Is it possible to acess datastores from a Webservice?

### ISSUE THREAD

**Issue by Wellington-Noberto** [Azure/MachineLearningNotebooks#454]
According to the documentation is possible to acess datastores during training, but I couldn't find nothing about using data from datastores inside the Webservice, wich is something extremely necessary for my model.

The only external file that I could use in a Webservice is the 'model.pkl' that I created previously

https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-access-data#access-datastores-during-training

**Comment by rastala** [comment]
Could you describe more why you'd need to access datastore from web service?

**Comment by Wellington-Noberto** [comment]
There are some important datasets with features that were created based on historical data which improves significantly the results of my model. For example, imagine that I'm trying to forecast if a client is going to pay a bill in the correct time, a good strategy is to extract information of the previous payments.
There are already some techniques using that kind of strategy, such as Target/Mean Encoding.

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see there wasn't a response to your last post, some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
