### ISSUE TITLE
PythonScriptStep environment variable values cut off at equals char ('=')

### ISSUE THREAD

**Issue by akbo** [Azure/MachineLearningNotebooks#458]
When trying to use environment variables containing an equals char ('=') in their value, everything from the equals char is cut off. 

Example:

```
from azureml.core.workspace import Workspace
from azureml.core.compute import AmlCompute
from azureml.core.runconfig import RunConfiguration
from azureml.pipeline.steps import PythonScriptStep
from azureml.pipeline.core import Pipeline


ws = Workspace.from_config()

aml_compute = AmlCompute(ws, "aml-compute")

run_config = RunConfiguration()
run_config.environment.environment_variables = {"TEST": "test=123=hel=lo"}
my_step = PythonScriptStep(
    name="My test step",
    script_name="test_env_vars.py",
    compute_target=aml_compute,
    source_directory=".",
    runconfig=run_config,
    allow_reuse=False,
)
pipeline = Pipeline(workspace=ws, steps=[my_step])
pipeline.submit("My-Experiment")
```

where **test_env_vars.py** contains

```
import os

print(os.environ["TEST"])
```

results in printing `test`. Expectation: `test=123=hel=lo` should be printed.

I am not sure what the scope of this is. Potentially, this is not restricted to the PythonScriptStep.

**Comment by cicorias** [comment]
Define as
```
test=“foo=bar”
```

**Comment by danielsc** [comment]
Looks like a bug to me -- @wbaumann-microsoft what are your thoughts?

**Comment by wbaumann-microsoft** [comment]
Definitely looks like a bug but I just tried to reproduce it with a simple script run against AmlCompute and couldn't. It printed the full ```test=123=hel=lo``` as expected. Appears like the issue is scoped to pipelines.

**Comment by yanrez** [comment]
+ @alexkalita

**Comment by alexkalita** [comment]
Thanks for the report!  I am working on a fix.

**Comment by jmwoloso** [comment]
Any luck with this @alexkalita ?

**Comment by alexkalita** [comment]
Yes, we deployed a fix for this issue last week.  It was on the pipeline service side so there is no client updated needed.  Can you let me know if you still see this issue?

**Comment by akbo** [comment]
Hi there, sorry for the late reply. I tested this and can confirm that the bug is fixed. Thanks!
