### ISSUE TITLE
Load model on each api call issue

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#462]
Hi,

I have deployed a deep learning tensorflow based model as web service on AKS instances using Azure machine learning services. IN the current scoring script, i am loading the model in run() method of scoring script. hence it gets loaded on each api call and increasing the inferencing time of the script.

Can someone suggest how can i avoid loading the model on each API call ?

Thanks,
Amardeep

**Comment by davidefiocco** [comment]
Usually, the model would be initialized in the `init()` method in the scoring script, thus solving the problem you are experiencing: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-deploy-and-where#prepare-to-deploy
Moving model loading to `init()` is the simplest way I see to solve your problem.
