### ISSUE TITLE
remote compute with ONNX compatible config on give ValueError: "ONNX models is not enabled on remote compute target"

### ISSUE THREAD

**Issue by wtam** [Azure/MachineLearningNotebooks#464]
How to reproduce:
- use this sample link: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing/auto-ml-classification-bank-marketing.ipynb
import json
- add "enable_onnx_compatible_models": True  in the automl_settings
-  when run to this step (remote_run = experiment.submit(automl_config, show_output = True)), error occur.

**Comment by ayuwhu** [comment]
Currently AutoML only supports generating ONNX compatible model on local compute. See example here: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-with-onnx/auto-ml-classification-with-onnx.ipynb

We will soon have an update to support ONNX on remote compute target. Will update this thread once it's ready.

**Comment by ayuwhu** [comment]
@wtam ONNX on remote compute target is now supported in Azure ML SDK v1.0.53 just released today. You can upgrade to the new SDK version, and run the same configuration as you tried before, it should work now.

**Comment by j-martens** [comment]
Thanks for your report. Since the new version should address your issue, we shall proceed to close this issue, #please-close. If you feel that your issue has not been resolved please reopen the issue and provide additional context.
