### ISSUE TITLE
Registering Datastore with Azure ML Service gives Max Retry Error

### ISSUE THREAD

**Issue by rrmistry** [Azure/MachineLearningNotebooks#465]
I am having issues with registering data stores in my Azure ML Service.

The error fails after a few seconds with python `MaxRetryError`.
![MaxRetryError](https://user-images.githubusercontent.com/25514145/60692969-64897300-9ea6-11e9-9330-1e4df16aaf61.png)

As seen above, I'm seeing the same issue with Azure ML CLI.

Upon further investigation with Postman and the REST API, I noticed that there is something fundamental going wrong on the service:

![PostManError](https://user-images.githubusercontent.com/25514145/60693001-8c78d680-9ea6-11e9-9945-bc34ba685f43.png)

The error message says `Credential service failed` but this is strange since I was basically able to `GET` all my existing datastores with the same REST API endpoint.

I checked *Azure Service Health* and did not see any service outage notices. So I'm not sure what I'm doing wrong.

I've already created an Azure support ticket in case this is simply a service outage, but any help would be greatly appreciated. Thank you!

----
|Environment Details|Value|
|-|-|
|Azure ML Service location|`canadacentral`|
|Azure ML SDK version|`1.0.45`|
|Python version|3.6.5|
|Conda version|4.7.5|

**Comment by rrmistry** [comment]
Just wanted to update that I also tried to register my datasource from the dedicated [notebook VMs](https://azure.microsoft.com/en-ca/blog/three-things-to-know-about-azure-machine-learning-notebook-vm/) under the same Azure Machine Learning service.

![notebook-vms](https://acomblogimages.blob.core.windows.net/media/Default/GIF/NotebookVM-demo-build2019-hq.gif)

I saw the same issues there.

**Comment by andscho-msft** [comment]
Hi,

It looks like the managed identity for the ML workspace no longer has permissions to set secrets on the Key Vault attached to the workspace. You can manually re-assign the permissions, or you can try the SDK "sync_keys" function which does so automatically:

```
from azureml.core import Workspace
ws = Workspace.from_config()
ws._sync_keys()
```

**Comment by rrmistry** [comment]
Hello @andscho-msft , thank you! Your comment helps pin down the root cause. My steps to resolution were as follows:

1. Update the access policies in the _Azure Key Vault_ associated with the _Azure ML Workspace_ and grant permissions for key, secret, and certificate management
2. Executing the `Workspace._sync_keys()` method
3. Register storage account again

----

I was able to infer the correct service principal based on the date created, but it does not follow an intuitive naming convention. For my AAD, the service principal had the form `aml-d1ad1ce8-XXXX-XXXX-XXXX-80ea85991a76`. I'm curious if this managed service identity can follow a more intuitive naming convention (e.g. like Azure Data Factory V2 where MSI Name ~= ADF Name).

Also to note, I could not find documentation on minimal permissions required when performing specific workspace operations. Would be easy to infer by trial and error but would be nice to get better understanding of dependency on Azure KV.

----

I'm still happy with the overall ML service though. Thank you for all your hard work. I genuinely appreciate it 👍

**Comment by andscho-msft** [comment]
Great, glad you could get everything working.

Thanks for the feedback about the service principal name, that seems like an easy fix.

For KeyVault permissions, azureml uses the 'get, set, delete' on the 'secret' type.

Glad you're enjoying azureml!
