### ISSUE TITLE
DataReferenceConfiguration stops working when mode=mount is used

### ISSUE THREAD

**Issue by kubasiak** [Azure/MachineLearningNotebooks#468]
I have been using DataReferenceConfiguration with 'download' mode to run my AutoML codes. Now I need to mount the data and I have been testing the mode 'mount'. Once I changed 'download' to 'mount' the run faild. The error says that the files don't exist. 

Does the path behave differently with 'mount' and 'download'? 
Anna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414eb483-502b-a964-5f81-25073d4914ec
* Version Independent ID: e1c7b21f-2fc2-4f57-66f9-33426b38ae76
* Content: [azureml.core.runconfig.DataReferenceConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfig.datareferenceconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.runconfig.DataReferenceConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.runconfig.DataReferenceConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by yanrez** [comment]
I think both should be working same way. Can you please share a code snippets where you face the issue? Can you also confirm that switching back from download to mount mitigated the issue (just to verify it's not due to data being actually deleted from storage).

**Comment by kubasiak** [comment]
Switching back to 'download' works fine. 
I issued a tickiet and it seems there is a problem with the 'mount' method. At least so far I did not get any information how to solve it. 

I am using 


`ds = ws.get_default_datastore()
dr = DataReferenceConfiguration(
                    datastore_name=ds.name, 
                    path_on_datastore='data_comic', 
                    path_on_compute='/tmp/azureml_runs',# not working
                    mode='download', # download files from datastore to compute target
                    overwrite=True)


from azureml.core.runconfig import RunConfiguration
from azureml.core.conda_dependencies import CondaDependencies

# create a new RunConfig object
conda_run_config = RunConfiguration(framework="python")

# set the data reference of the run coonfiguration
conda_run_config.data_references = {ds.name: dr}
`

**Comment by rongduan-zhu** [comment]
Unfortunately, the mount path is nondeterministic right now, unlike download which we have control over where we download the data. The documentation on accessing data can be found [here](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-access-data#access-datastores-during-training).

![image](https://user-images.githubusercontent.com/5406634/61071675-84e59000-a3c6-11e9-8406-64217ea8329e.png)

**Comment by singliar** [comment]
Rongduan - 

I understand you to say is that Anna should use a path_on_compute argument that is constructed from the $AZUREML_DATAREFERENCE variable.

Is that correct?

Tomas

**Comment by rongduan-zhu** [comment]
Hi Tomas,

Anna can just refer to the `$AZUREML_DATAREFERENCE_{ds.name}` in her get_data.py script to get the mounted path.

Thanks,
Rongduan

**Comment by ayuwhu** [comment]
Anna, did what Rongduan suggested above resolve the issue for you?

**Comment by kubasiak** [comment]
It works!
Thanks a lot!  One thing I found out is that I needed to change
additionally the path format I.e. get rid of initial "/".
Otherwise, it is exactly what I was looking for.

Regards
Anna
