### ISSUE TITLE
Specifying conda environment using PyTorch object

### ISSUE THREAD

**Issue by Darshan2701** [Azure/MachineLearningNotebooks#470]
Hello folks,

I am trying to follow the steps mentioned in "**https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb"**
I want to run my script on a specific conda environment created in the compute. Could you please guide me how to use it?

**Comment by j-martens** [comment]
does anything in here help? https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-train-pytorch

**Comment by Darshan2701** [comment]
@j-martens Thanks for the reply.
I  checked the link but unfortunately, there is no information about what I want.

My guess is that there must be some sort of flag inside **estimator = Pytorch(...)** to indicate the conda environment that I want to use on the compute.
By default, this code creates a docker image and apparently does all the job inside that docker, which I do not intend to do.

**Comment by j-martens** [comment]
@Darshan2701 - Did you check here? https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.pytorch?view=azure-ml-py

**Comment by Darshan2701** [comment]
@j-martens Yeah , i am checking the same class. it's quite confusing there. I am trying to use **environment_definition**, but no success. Do you possibly know more information regarding it's usage?

**Comment by Darshan2701** [comment]
I figured this out! Thanks for the help @j-martens
