### ISSUE TITLE
Script error "Run failed: No module named 'pandas'"

### ISSUE THREAD

**Issue by damucka** [Azure/MachineLearningNotebooks#471]
Hello,

I am trying to fit the example to my needs. I copied the tf_mnist.py to my tf_nn.py and try to read the data from the previously stored ds and create the X_train, X_test, y_train and y_test.
For that I wanted to use pandas, but I get the following error from Azure:
"Run failed: No module named 'pandas'.
How would I overcome this?

Also, forgive my ignorance but I am new to Azure ML:
- is it possible to debug the tf_mnist.py / tf_nn.py? Or is the execution flow directed to the compute resource and one would not have access to it? (debug)

Kind Regards,
Kamil

**Comment by TNieuwdorp** [comment]
`dbutils.library.installPyPI('pandas')
dbutils.library.restartPython()`
Seems like you're missing pandas, try running the code above first to install it. Does that fix it for you?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was posted some time ago so will close it.  We hope the community response helped. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
