### ISSUE TITLE
Reference PyPI URL in ADO Artifacts

### ISSUE THREAD

**Issue by zackdrescher** [Azure/MachineLearningNotebooks#473]
We host custom dependencies on Azure Artifacts. How might one configure AML to leverage a PyPI URL in ADO? 

From what I understand we need to add credentials to the pip.conf on the remote server. Is there a way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb6e18dd-c5d9-02dd-41ee-f12dc8152a24
* Version Independent ID: 8db0f517-4578-e32c-3162-cd95635a0dc3
* Content: [azureml.core.conda_dependencies.CondaDependencies class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies?view=azure-ml-py#set-pip-index-url-index-url-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was posted some time ago   so will close it.  We hope the   community response helped. Should you still need assistance with this or   another issue, please re-post and we will respond promptly.
