### ISSUE TITLE
Building a Pytorch project

### ISSUE THREAD

**Issue by Darshan2701** [Azure/MachineLearningNotebooks#477]
Hello folks,

I am using DSVM as my compute and using Azure machine learning services. 
I have a Pytorch based deep learning project for which I am trying to use hyperdrive to fine tune, my model, further.
So, when I execute **experiment.submit(estimator)**, the entire project gets uploaded to the remote VM. Now in order for the entry script to work, the project has to be built first.
Is there a way to do that or I need to initialize two estimator objects?

I am following this **https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb**

Any thoughts on how to solve this?

**Comment by swatig007** [comment]
Hi Darshan, HyperDrive supports only AML Compute as a compute target. can you please upload a sample of the estimator you are using with HyperDRive?
Thanks,

**Comment by v-strudm-msft** [comment]
Thank you for your post. We see our answer was delayed. Our apologies. We did not receive a response, so will close this issue for now.   Should you need further assistance, please post on this forum and we  will respond promptly.
