### ISSUE TITLE
Your job is submitted in Azure cloud....

### ISSUE THREAD

**Issue by Darshan2701** [Azure/MachineLearningNotebooks#478]
Hello Folks,

I am following this post **https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb**.
I am using DSVM as my compute.
After submitting the run, the following is seen and seems to be stuck forever.
Any idea why?

[
![azure_error](https://user-images.githubusercontent.com/18184336/61034461-98442b80-a3c5-11e9-8530-4428a824cf8f.PNG)
](url)

**Comment by davidefiocco** [comment]
I am not fully sure, but issues here _may_ arise if you don't use recent version of the azureml-sdk.
Try out 
```
import azureml.core
print("SDK version:", azureml.core.VERSION)
```
If your DSVM is not close to 1.0.48 you should consider running 
`pip install --upgrade azureml-sdk`
and trying executing your cell again and see if that solves.

**Comment by Darshan2701** [comment]
@davidefiocco Thanks for the information. I found out that I have deleted the storage blobs associated with this run I guess!
Because of this, it is not able to find a docker image and download the same in the compute, _iguess_.

Do you think it's possible?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was posted some time ago so will close it.  We hope the community response helped. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
