### ISSUE TITLE
Pass parameter to score file

### ISSUE THREAD

**Issue by ayoubelasryRoot** [Azure/MachineLearningNotebooks#484]
Hi,
I would like to pass the name of the model to my scoring file as an argument.  
But image_configuration doesn't have an argument parameter.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf6fb77-160e-92d8-987c-92f544f4fb31
* Version Independent ID: 3d19e0ce-c3c1-870e-1978-8bf0e12e9082
* Content: [azureml.core.image.ContainerImage class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.containerimage?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.image.ContainerImage.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.image.ContainerImage.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ayoubelasryRoot** [comment]
Thank you very much :)

**Comment by jpe316** [comment]
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where#prepare-to-deploy

# Example when the model is a file
model_path = os.path.join(os.getenv('AZUREML_MODEL_DIR'), '\model.pkl')
