### ISSUE TITLE
Documentation does not say input and output can only be a file

### ISSUE THREAD

**Issue by neonrights** [Azure/MachineLearningNotebooks#485]
Apparently Azure Batch does not support uploading or downloading of directories and their contents.  This is confusing since steps using AmlCompute do.  Could you update the documentation to clarify this restriction since it is not obvious at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d1b65c-55ee-0e0a-9f28-637543f8d2c9
* Version Independent ID: 9fb58543-342f-544d-a34f-78fbeed5884a
* Content: [azureml.pipeline.steps.azurebatch_step.AzureBatchStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.azurebatch_step.azurebatchstep?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.azurebatch_step.AzureBatchStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.azurebatch_step.AzureBatchStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@neonrights Thanks for the details report. I just put the fix request into the queue. I'm going to close this for now as we are tracking internally now. Thanks!
