### ISSUE TITLE
AMLSettingsJsonString required and missing from doc

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#489]
```
run = AutoMLRun(experiment, run_id)
run.get_output()
```
returns:
`KeyError: 'AMLSettingsJsonString'`

Is there some other item that should be included here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff6cc4e7-0396-d435-ed3e-1541c240cf97
* Version Independent ID: 0a2246dc-79a0-d24f-7994-3e9db0cf2f2d
* Content: [azureml.train.automl.run.AutoMLRun class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.run.automlrun?view=azure-ml-py#register-model-description-none--tags-none--iteration-none--metric-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.run.AutoMLRun.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.run.AutoMLRun.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by BillmanH** [comment]
I actually found out after some troubleshoot that you can only run this function on a model that had already been run within the kernel. If you are loading a `run_id `from an earlier run then there is no `SMLSettingsJsonString ` to pull. This makes sense but might be a good thing to document.

**Comment by ayuwhu** [comment]
I was not able to reproduce this error using AutoMLRun class to load a previous run. Here is a sample notebook showing you how to explore previous runs: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/exploring-previous-runs/auto-ml-exploring-previous-runs.ipynb

When you ran into the error, were you trying to retrieve an run_id that previously trained in the workspace?

**Comment by pbartos** [comment]
You can receive this error when you use run_id of AutoML sub-run, not AutoML run itself.
