### ISSUE TITLE
Possible double serialization on results returned from web service

### ISSUE THREAD

**Issue by screamyao** [Azure/MachineLearningNotebooks#49]
Noticed strange behavior on results returned from web service after constructing `score.py` following the SDK documentation. See the below comparison. 

Attempt 1. `run()` function using `json.dumps` on `return`:
```python
def run(input_json):
    '''
    Input: JSON "{\"skill\": \"legal\"}"
    '''

    try:
        input_df = json.loads(input_json)["skill"].lower()
        assert len(input_df)>0
    except:
        print("Input data is not in JSON format")

    res = predict(input_df)
    res_dict = {"skills" : res}

    return json.dumps(res_dict)
```
Output (notice the excessive backslashes):
```python
"{\"skills\": [\"finance\", \"corporate_finance\"]}"
```

Attempt 2. `run()` function simply returning Python dictionary:
```python
def run(input_json):
    '''
    SAME CODE
    '''
    return res_dict
```
Output:
```python
{"skills": ["finance", "corporate_finance"]}
```

The first output is consistent with applying `json.dumps` twice. 
```python
print(json.dumps(json.dumps({"skills":["finance","corporate_finance"]})))
```
Result: 
```python
"{\"skills\": [\"finance\", \"corporate_finance\"]}"
```

Makes me wonder if the API service is doing its own `json.dumps` on returned object already? Hence there should be no need of adding `json.dumps` in the `run()` function.

**Comment by prasanthpul** [comment]
@rastala is this documented somewhere? consider also updating the notebooks which show always using json.dumps, even on data that wouldn't need it.

**Comment by ezwiefel** [comment]
I agree with with @prasanthpul - this should be documented somewhere and the notebooks should be updated...

@hning86 - Could we update these notebooks to take out `json.dumps()` from the score.py examples. This causes malformed JSON to be returned from the webservice.

Additionally, we should have documentation that the return value from the `run` method in scoring scripts should be a _JSON serializable_ object and __not__ a JSON string

**Comment by hning86** [comment]
Yeah I will fix this. Thx for spotting it!

**Comment by hning86** [comment]
this is fixed. i am closing the issue.
