### ISSUE TITLE
Unable to tag pipeline runs with model version

### ISSUE THREAD

**Issue by alieus** [Azure/MachineLearningNotebooks#490]
We tried tagging our pipeline runs with the current model version but it appears that the Model class, specifically the Model.list() method doesn't work remotely with this. It works fine locally but once we try running it remotely, it fails.

**Comment by elihop22** [comment]
Could you provide the code you are using?

**Comment by alieus** [comment]
Just the classic:

            interactive_auth = InteractiveLoginAuthentication(
                 tenant_id="*************************")
             ws = Workspace.from_config(auth=interactive_auth)

    # get the details of the current model version being used
    model_details = str(Model.list(ws, name=args.model_name,
                                   tags=None, properties=None, run_id=None,
                                   latest=True))
# some string manipulation to retrieve the version number 
version = ...

# logging
run.log('version', version)

**Comment by elihop22** [comment]
So this is in the script of one of the steps in your pipeline? Can you include the logs for the step run?

**Comment by v-strudm-msft** [comment]
Thank you for your post and participation. We see your last response was some time ago so we will close this thread. Should you need further assistance, please post on this forum and we will respond promptly.
