### ISSUE TITLE
Any plans to make use of azure.identity revamp in azureml?

### ISSUE THREAD

**Issue by jmwoloso** [Azure/MachineLearningNotebooks#492]
Hi!

Are there any plans to have the `azureml-sdk` support the [revamps](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity) to the `azure.identity` library so that we can use `azure.identity.DefaultAzureCredential` instead of the `ServicePrincipalAuthentication` contained within the ML sdk?

**Comment by jmwoloso** [comment]
How would I propose a feature request for this?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
