### ISSUE TITLE
Memory Overflow Issues

### ISSUE THREAD

**Issue by BSofo** [Azure/MachineLearningNotebooks#493]
I am running this test script mem_overflow.py remotely and it immediately failed stating this error message:
 `msrest.exceptions.HttpOperationError: Operation returned an invalid status code 'Metric Document is too large, 3394b is larger than the max metric size 3000b.'`

This is the content of the script: 
`import pandas as pd
import argparse
import os
from pprint import pprint`
`parser = argparse.ArgumentParser(description="Starts the data transformation")
parser.add_argument('--input_dir', dest="input_dir", default="C:\\temp")
args = parser.parse_args()`
`print("all agrs:")`
`pprint(vars(args))`
`glacier = pd.read_csv(os.path.join(args.input_dir, 'glacier.csv'))`
`glacier_al = pd.get_dummies(glacier, columns=['Glacier ID', 'Political Unit', 'Continent', 'Basin Code',
                                              'Location Code', 'Glacier Code', 'Glacier Name', 'Latitude',
                                              'Longitude', 'Primary Class', 'Glacier Source', 'Basin Count',
                                              'Glacier Form', 'Glacier Activity', 'Activity Start', 'Activity End',
                                              'Minimum Elevation', 'Minimum Elevation Exposed', 'Mean Elevation',
                                              'Mean Elevation Accumulation', 'Mean Elevation Ablation',
                                              'Maximum Elevation', 'Snow Line Elevation', 'Snow Line Accuracy',
                                              'Glacier Area', 'Area Accuracy', 'Area Exposed', 'Mean Width',
                                              'Mean Length', 'Maximum Length', 'Maximum Length Exposed',
                                              'Maximum Length Ablation', 'Mean Depth', 'Depth Accuracy',
                                              'Accumulation Orientation', 'Ablation Orientation',
                                              'Topographic Map Year', 'Topographic Map Scale', 'Photograph Year'])`

`print(glacier_al.info())`

And the file is attached below in a txt format but I need to read it in a csv. 
[glacier.txt](https://github.com/Azure/MachineLearningNotebooks/files/3423383/glacier.txt)

**Comment by eedeleon** [comment]
Hello @BSofo ,

It looks like our error message is not clear. When a run.log(_list, _image, *) calls is made we make a web request to save your logged metric. This error message signifies that the metric is too large.

Assuming run.log_list or run.log_table were called, a possible workaround is to log a subset of the rows at a time. General rule of them is 50-100 values at a time for now while we work on increasing the number of values we support per log call.

example:

batch_size = 50
for batch in range(len(my_list)/ 50):
     current = batch * batch_size
     run.log_list("metric_name", my_list[current: current + batch_size])

# assuming my_list is a list of supported scalars or strings

**Comment by BSofo** [comment]
That makes sense, I have used run.log_list in a previous example and realized this. But in this case I am not logging anything, just running the script. 

I ran the script through the pipeline again and actually got a `MemoryError` message. Is there a more specific message I can get other than that?

**Comment by v-strudm-msft** [comment]
Thank   you for your post and participation. We see your last response was some time   ago so we will close this thread. Should you need further assistance, please post on this forum and we will respond promptly.
