### ISSUE TITLE
The doc for remove_pip_option says it “adds a pip option” it should be remove pip option

### ISSUE THREAD

**Issue by thomasendale** [Azure/MachineLearningNotebooks#494]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb6e18dd-c5d9-02dd-41ee-f12dc8152a24
* Version Independent ID: 8db0f517-4578-e32c-3162-cd95635a0dc3
* Content: [azureml.core.conda_dependencies.CondaDependencies class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
This was addressed and method description was corrected.
