### ISSUE TITLE
configurations link doesn't open in a new tab 

### ISSUE THREAD

**Issue by thomasendale** [Azure/MachineLearningNotebooks#495]
try opening it in a new tab and it failed to render but works with in the same window.

**Comment by j-martens** [comment]
which link are you referring to please? PLease provide a complete description so we can try to replicate. Thanks.

**Comment by v-strudm-msft** [comment]
Thank you for your post and participation. We see your last response was some time ago so we will close this thread. Should you need further assistance, please post on this forum and we  will respond promptly.
