### ISSUE TITLE
Incorrect mention of workspacefileblobstore

### ISSUE THREAD

**Issue by thgibbs** [Azure/MachineLearningNotebooks#496]
On https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-your-first-pipeline

under the "Set up a datastore" heading.

It says:
# Default datastore (Azure blob storage)
def_data_store = ws.get_default_datastore()

# The above call is equivalent to this
def_data_store = Datastore(ws, "workspaceblobstore")

# Get file storage associated with the workspace
def_file_store = Datastore(ws, "workspacefileblobstore")

However, the last line (workspacefileblobstore) doesn't work and other documentation states that the file store is the default.

**Comment by j-martens** [comment]
@nibaccam

**Comment by nibaccam** [comment]
@thgibbs 
Try:
def_filestore = Datastore(ws, "workspacefilestore") 

If this works for you, I will update the documentation accordingly.

**Comment by thgibbs** [comment]
Yes, this works.

**Comment by nibaccam** [comment]
@thgibbs the above referenced PR includes the updates to the associated documentation for this issue. If satisfied, #please-close.

**Comment by thgibbs** [comment]
Sorry, I don't see a PR...which one?

**Comment by nibaccam** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/83781

**Comment by thgibbs** [comment]
That gives me a 404.

**Comment by nibaccam** [comment]
@thgibbs the [documentation](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-your-first-pipeline) has been updated. #please-close
