### ISSUE TITLE
Should Workspace.create be able to accept mix of existing and non-existing service names?

### ISSUE THREAD

**Issue by jmwoloso** [Azure/MachineLearningNotebooks#497]
Should the `Workspace.create` method be able to accept a mixture of existing and non-existing service names? It currently doesn't seem to support that:

```
import os

from azureml.core.authentication import ServicePrincipalAuthentication
from azureml.core import Workspace

spa_auth = ServicePrincipalAuthentication(...)


ws = Workspace.create(
    name="test_ml_services",
    auth=spa_auth,
    subscription_id=os.environ["AZURE_SUBSCRIPTION_ID"],
    resource_group=os.environ["AZURE_RESOURCE_GROUP"],
    create_resource_group=False,
    location="westus2",
    friendly_name="Test ML Services",
    storage_account=<existing_storage_account_name>,
    key_vault=<existing_key_vault_name>,
    app_insights=<new_app_insights>,
    container_registry=<new_container_registry>,
    exist_ok=False,
    show_output=True
)
```

the above code returns errors indicating it can't find the specified `app_insights` and `container_registry`, which it shouldn't because they don't exist. If I run the code and fill in non-existing names for each of `storage_account`, `key_vault`, `app_insights` and `container_registry` keyword args, then the workspace is created with service names derived from the keywords (as expected).

**Comment by jmwoloso** [comment]
How would I create a feature request proposal based off of this?

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close it. Should you still need   assistance with this or another issue, please re-post and we will respond   promptly.
