### ISSUE TITLE
run_config parameter isn't described above

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#507]
It's described in the attributes, but a description of what it is, a link to RunConfiguration class would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c29f2f46-657d-4ae3-38f9-7888f935cdbd
* Version Independent ID: 32ef1c0f-0cf4-bb80-2d94-b2aae7d90972
* Content: [azureml.train.hyperdrive.HyperDriveConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.hyperdrive.hyperdriveconfig?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.HyperDriveConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.HyperDriveConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swatig007** [comment]
@omartin2010 thanks for the feedback. We'll add information about the run_config to the doc strings in the next release

**Comment by j-martens** [comment]
@vmagelo - FYI

**Comment by vmagelo** [comment]
Yes, parameter is will be included in next release.
