### ISSUE TITLE
No module named train.dnn

### ISSUE THREAD

**Issue by rfairhurst** [Azure/MachineLearningNotebooks#510]
I ran: 
python -m pip install azureml-train
But when I try to run:
from azureml.train.dnn import PyTorch
I get the message:
No module named train.dnn
How do I install azureml.train.dnn?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b9ea6e-f047-7395-6102-d044437ecf41
* Version Independent ID: 6191bb04-ce18-5615-8702-0f3862c2db0a
* Content: [azureml.train.dnn package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vizhur** [comment]
most likely something is wrong with your environment or installation

azureml-train is a metapackage that should bring azureml-train-core into your environment that has dnn package. 

Please startover from a clean environment
