### ISSUE TITLE
Error when following your information

### ISSUE THREAD

**Issue by LHTech-Analytics** [Azure/MachineLearningNotebooks#511]
When I try to run this code:

# get_default_datastore() gets the default Azure Blob Store associated with your workspace.
# Here we are reusing the def_blob_store object we obtained earlier
def_blob_store.upload_files(["./20news.pkl"], target_path="20newsgroups", overwrite=True)
print("Upload call completed")

I get the following error:

Exception: './20news.pkl' does not point to a file. Please upload the file to cloud first if running in a cloud notebook.

The comment says # Here we are reusing the def_blob_store object we obtained earlier. This is not something "We" did. I certainly didn't do it as I've been directed straight to this article via your documentation and this is my first touch ppoint in learning about this. Can you explain where and why this has gone wrong as I am completely unclear on where exactly we should have obtained the def_blob_store object that apparently should already be in my storage account :(

**Comment by purnesh42H** [comment]
Is this file "./20news.pkl" in your current directory where you are running your notebook?

**Comment by v-strudm-msft** [comment]
Thank you for your post and participation. We see your our response was some time ago and we've not heard from you so we will close this thread. Should you need further assistance, please post on this forum and we will respond promptly.
