### ISSUE TITLE
How can you access steps that the definition used?

### ISSUE THREAD

**Issue by IvoMerchiers** [Azure/MachineLearningNotebooks#512]
When I have a definition in my environment, it would be nice to see which transformation steps it uses, similar to the the default visualisation of a Dataflow object.

For example consider you loaded in a dataset:

```
ds_def=dataset.get_definition()
ds_def=ds_def.keep_columns(['name', 'device'])
```

This returns a Dataflow object which shows all the steps.

```
dataset2=dataset.update_definition(ds_def, 'Selected only specific columns')
dataset2.get_definition()
```

Returns a definition that no longer shows the steps (although they are stored in the object).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e75e44c-3103-b796-6869-1c02ca0a501d
* Version Independent ID: 22d507db-076f-643e-641f-b53540674675
* Content: [azureml.data.dataset_definition.DatasetDefinition class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_definition.datasetdefinition?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.data.dataset_definition.DatasetDefinition.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.data.dataset_definition.DatasetDefinition.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by jrcalzada** [comment]
We're aware of the issue. The current string representation of the definition object doesn't show much of the useful information that's contained within it.

We're in the process of making some changes to the Datasets API that should address this concern. We'll follow up here once those are released.

**Comment by j-martens** [comment]
@MayMSFT  has this been addressed?  cc: @nibaccam

**Comment by MayMSFT** [comment]
@j-martens the method has been deprecated. pls close it.
