### ISSUE TITLE
No name 'opendatasets' in module 'azureml' Error

### ISSUE THREAD

**Issue by yuchaozh** [Azure/MachineLearningNotebooks#518]
Hi,
I was trying to follow this documentation: https://azure.microsoft.com/en-us/services/open-datasets/catalog/noaa-integrated-surface-data/ (Go to "Data access" tab)to use opendatasets module to access historical weather data. But it gives me the error message `No name 'opendatasets' in module 'azureml'`. 
I tried `pip install azureml-sdk[opendatasets]` as well, it shows `WARNING: azureml-sdk 1.0.55 does not provide the extra 'opendatasets'`.
Do you know how to use the opendatasets module in azureml?

Thanks!

**Comment by yuchaozh** [comment]
Find the solution, maybe because `opendatasets` is a preview module, so it is not included in azureml sdk yet. You can download through pip `pip install azureml-opendatasets` in your env.

**Comment by chethanchandran** [comment]
> pip install azureml-opendatasets

Thanks, was looking for the solution, this worked !! However, I had another error " [WinError 5] Access is denied:" This was solved by adding --user at the end of your command.
