### ISSUE TITLE
DynamicLocalExplanation does not have any documentation

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#522]
Add some documentation or some kind of link to the object so that users can understand how to use it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef54051-4cc0-d0f4-0e64-51eb26267530
* Version Independent ID: 60435e0f-cf97-6d88-dc47-fa030e877217
* Content: [azureml.explain.model.shap.KernelExplainer class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-explain-model/azureml.explain.model.shap.kernelexplainer?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-explain-model/azureml.explain.model.shap.KernelExplainer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-explain-model/azureml.explain.model.shap.KernelExplainer.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thanks for your report. @vmagelo
