### ISSUE TITLE
Accessing Notebook VM from VS Code Remote SSH

### ISSUE THREAD

**Issue by michalmar** [Azure/MachineLearningNotebooks#524]
I have created a Notebook VM under AML service workspace - when I access the Notebook VM and try to do `conda env list` I see error: there is no conda installed. This happens when I am using Remote SSH access from VS Code plugin. When I log there from different client thrugh SSH it works.

Provide the following if applicable:
+ Your Python & SDK version : Python 3.6.5, SDK 1.0.44+ (currently1.0.55)

**Comment by danielsc** [comment]
Thanks for flagging this. I am not sure why it is working in ssh, but it seems that the VSCode terminal is truly bash. We will fix it -- in the meantime, on your notebook VM, please open the file `/home/azureuser/.bashrc` in an editor and add this line to the end of it:
```
export PATH=$PATH:/anaconda/bin
```
