### ISSUE TITLE
Examples of using PipelineData in pipeline steps

### ISSUE THREAD

**Issue by AndyLem** [Azure/MachineLearningNotebooks#525]
Hi,

Is it possible to provide some examples of how to use PipelineData objects in PythonScriptStep scripts to get data from previous steps or send it to the next ones?

Thanks

**Comment by j-martens** [comment]
Hi, 
Data is written out to a datastore between every step. The PipelineData object has the mount or download path to the files in question as an attribute. When passing the PipelineData object to the “inputs” argument of a Python Script step, it signals the following for the StepRun: 
1. Fetch the path attribute from the object
1. Create an environment variable with the name of the PipelineData object and path as the value, and
1. Assign that env variable to the corresponding arg parse script parameter. 


cc: @swanderz  @sanpil  @yanrez

**Comment by swanderz** [comment]
@AndyLem this notebook does a decent job of explaining, but I'd REALLY make sure you understand script arguments first. Then also be very careful to pass the PipelineData to both the `inputs` and  `arguments` examples
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb

**Comment by AndyLem** [comment]
Hello,
Thanks for your answers. @swanderz I saw the notebook and while it is great on how to set up the pipeline, it doesn't answer the question - how to use it in training scripts. Also, usage of tuples like data_parameter1 is not documented in SDK (or at least I wasn't able to find it) and confuses a bit.
Anyways, I've found out the reason for my issue. I have AML Compute with SSH access and when I tried to connect and see what's in the path of a mounted PipelineData, the path was incorrect. The reason is that I have been connecting AFTER the execution of the step. Then I've tried to connect DURING the step run, and the path was ok and the data was there. 
So basically what I am doing to make it work (thank you @j-martens):
1. creating PipelineData object, which points to a datastore
2. passing the object as an argument to PythonScriptStep step. As I understand, PipelineData.__str__ method substitutes output to be a path to a mounted folder on a target machine. 
3. passing the same object as input or output to the step constructor. It makes the pipeline know which step creates the data (the one which has it as an output) and how steps depend on each other. 
4. in the training script (or any other which uses PipelineData) I am extracting the value of the corresponding argument (using argparse of course), which is basically the "local" path and store my data in this folder (for output), or read from it (for input). 

I can't attach code examples as I use highly customized Ansible role for pipeline creation but feel free to ask any questions.

**Comment by swanderz** [comment]
@AndyLem Great. I 100% agree that the docs are very lacking where PipelineData objects are concerned. The `.str` method is never explained as its been abstracted from the user, i.e. if you reference the PipelineData script arg, in a function like `os.path.join()` it will automatically return the `.str` attribute you are talking about. Which is fine and dandy when it is working, but takes a lot time to reverse engineer when you're debugging something. Again it really needs to be explained better.

Check out the  [how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/scripts](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/scripts) There are actual (not dummy) examples of using the PipelineData objects in python scripts.

Two questions:
1) I don't know where `data parameter 1` comes from? 
1) was your PipelineData object "mounted" or "downloaded"?
I'd love to see how you're integrating Ansible. If you have some time to fork one of the notebooks in this repo and show how you'd use it, I'd be eternally grateful.

**Comment by AndyLem** [comment]
@swanderz, thanks for this example, it is much better! I wish I found it two weeks ago.
1. You can find data_parameter1 in this notebook https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb
it is being created right before compareStep:
`data_parameter1 = (datapath_param, DataPathComputeBinding(mode='mount'))`
So this is a tuple and I'm not quite sure how this thing works when it is passed as an input.
2. Well, this is a good question. I made some changes here and there so I can't tell what mode was in use when I tried to see the folder via ssh. Chances are I haven't specified the mode at all so it must have been 'mount' by default, right?
As for Ansible integration, I have a custom role which allows me to specify steps right in the yml file. By the way, I found that the Pipeline class has load_yaml method and I'm going to give it a try. But my implementation does something very similar, also allowing to include python bootstraps to create complex parameters.

**Comment by swanderz** [comment]
@AndyLem just looked at `data_parameter1` I have no idea what it is or what it does either. It certainly doesn't 

> give me a good sense of why the script argument names used below are important

@sanpil @j-martens @yanrez , passing this back to you guys for that...

**Comment by purnesh42H** [comment]
data_parameter1 is a PipelineIO object(another type of input) supported for PipelineSteps. It is a kind of PipelineParameter for datapaths, which allows you to specify parameterized input paths so that you can override during submission. It is only supported for inputs currently.

datapath = DataPath(datastore=def_blob_store, path_on_datastore='20newsgroups/20news.pkl')
datapath_param = PipelineParameter(name="compare_data", default_value=datapath)
data_parameter1 = (datapath_param, DataPathComputeBinding(mode='mount'))

**Comment by jadhosn** [comment]
> In the context of a notebook, a PipelineData object is a placeholder reference to some data that doesn't exist yet. It has a name but does not have a location assigned yet. The PipelineData objects are used to set up input/output connections in your pipeline (i.e. by passing them in as input/output/arguments to the step objects).
> 
> At step execution time, the PipelineData references are mapped to actual locations in a datastore, which are then mounted as local file paths for the step to interact with (either writing output data or reading input data). The step script usually receives those local file paths via environment variables in the arguments list.
> 
> After the step has completed, the output data is persisted to a datastore. You can access the output data at this point by calling StepRun.get_output_data() and similar methods. See https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb under 'See Outputs' and 'Download Outputs'.
> 
> If you want to use the output data from one pipeline in another pipeline, you can generate a data reference with StepRun.get_output_data('outputName').data_reference, and pass that as input to steps in the new pipeline. A DataReference here is a reference to a specific path on a datastore.
> 
> Datasets are a separate feature to store data with some extra metadata (name, format, versioning, etc.). Dataset support is still being implemented for pipelines. See here for more info: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-register-datasets
> 
> Does that help clear things up?

Thank you @alexkalita! That was really helpful. 

1. Going by the same application, how to write a dataframe saved in memory to the datastore, without going through writing it as a csv and then datastore.upload() to a path on the datastore? 
I'm struggling with saving my intermediate data directly to a specified blob location. 

2. I am also trying to access a directory on the datastore, and access all the files in that directory. I tried using DataPath (knowing in the documentation it mentions that it supports globbing), but I was not able to access a list dir for example for any path on the datastore.

**Comment by swanderz** [comment]
> 1. Going by the same application, how to write a dataframe saved in memory to the datastore, without going through writing it as a csv and then datastore.upload() to a path on the datastore?
>    I'm struggling with saving my intermediate data directly to a specified blob location.

@jadhosn, I can share how our team does this. we started before the `dprep` package got plugged into all the Pipeline examples and TBH I still don't completely understand it.

```python
import os
import argparse
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument('--input_data', dest= "input_data")
parser.add_argument('--output_data', dest= "output_data")
args = parser.parse_args()

df_raw = pd.read_csv(os.path.join(args.input_data, "data_raw.csv"))

df_gold = some_function(df_raw)
#write output
os.makedirs(args.output_dir, exist_ok=True)
df_gold.to_csv(os.path.join(args.output_dir, 'data_gold_DFS.csv'), index=False)
```

if you want more info, here is [a gist](https://gist.github.com/swanderz/cff0c170076669540f53cb29fa27d6e9) that has a `munge.py` script and how we call it from a `PipelineScriptStep`

**Comment by jadhosn** [comment]
> > 1. Going by the same application, how to write a dataframe saved in memory to the datastore, without going through writing it as a csv and then datastore.upload() to a path on the datastore?
> >    I'm struggling with saving my intermediate data directly to a specified blob location.
> 
> @jadhosn, I can share how our team does this. we started before the `dprep` package got plugged into all the Pipeline examples and TBH I still don't completely understand it.
> 
> ```python
> import os
> import argparse
> import pandas as pd
> 
> parser = argparse.ArgumentParser()
> parser.add_argument('--input_data', dest= "input_data")
> parser.add_argument('--output_data', dest= "output_data")
> args = parser.parse_args()
> 
> df_raw = pd.read_csv(os.path.join(args.input_data, "data_raw.csv"))
> 
> df_gold = some_function(df_raw)
> #write output
> os.makedirs(args.output_dir, exist_ok=True)
> df_gold.to_csv(os.path.join(args.output_dir, 'data_gold_DFS.csv'), index=False)
> ```
> 
> if you want more info, here is [a gist](https://gist.github.com/swanderz/cff0c170076669540f53cb29fa27d6e9) that has a `munge.py` script and how we call it from a `PipelineScriptStep`

@swanderz Thank you for sharing that example! 

But that means I have to go through a pipeline step to write something **directly** to the datastore (I'm assuming that we are depending on the args.input_data which is usually an environment variable that will point somewhere on the datastore). 

Instead, I am struggling just writing a simple dataframe as a csv to a path on the datastore from inside a cell inside my development environment. 

````
# Running this code outside a pipeline step
import pandas as pd
df  = pd.read_csv('path/to/file.csv')

df_processed = some_processing_func(df)

# Let's write this resulting dataframe to a path on the datastore 
df_processed.to_csv(os.path.join(??datastore_path??, 'df_processed.csv'), index=False)
````

In order to access `datastore_path`, I tried using DataPath which fails. I guess my question is how can I reference a datastore_path from inside my development environment?

**Comment by swanderz** [comment]
> I am struggling just writing a simple dataframe as a csv to a path on the datastore from inside a cell inside my development environment.

@jadhosn, so you're right I think the `dataprep` SDK will serve you here instead of the `pipeline` package. I know very little about `dataprep`, but one hunch would be to ask if the blob to which you want to write has:
1. been registered with ML Service, and
2. a corresponding datastore object created e.g. `dest_datastore = Datastore(workspace, 'dataprep_blob_key')`
Does [this notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/dataprep/how-to-guides/datastore.ipynb) help

**Comment by trevorbye** [comment]
@swanderz @jadhosn I feel your pain with this, I've expressed to the product team that it's ridiculous that you can't directly upload data if you already have it in memory, and that you have to first write it to a file, then load it, and then finally upload it to the datastore. 

Also, **dataprep is being deprecated and should not be used**, stick to pandas. It was replaced with "Datasets", which never worked with pipelines and is ALSO being deprecated, to be replaced by some new classes to allow transfer of data to/from the datastore. These will supposedly work with pipelines by end of this month but don't get your hopes up. See [this](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets/dataset-api-change-notice.md) for more info on the new classes. And yes we do know that this is eternally confusing.

I think the issue of not being able to do these operations from in-mem data will still be there, but I am being quite vocal about how nonsensical that is for users. If it were me, I would continue developing and using the custom behavior that you need.
