### ISSUE TITLE
[help wanted] function "model.predict_proba" doesn't give order of classes 

### ISSUE THREAD

**Issue by SleepyRoy** [Azure/MachineLearningNotebooks#527]
This applies to the latest automl (1.0.55).

For a typical classification problem, once an automl experiment is run and a desired model is chosen, we would be able to pass test X data into function **model.predict_proba(self, X)** to obtain the computed probabilities of each class, just like what is said in help(model):

 |  predict_proba(self, X)
 |      Apply transforms, and predict_proba of the final estimator
 |      
 |      Parameters
 |      ----------
 |      X : iterable
 |          Data to predict on. Must fulfill input requirements of first step
 |          of the pipeline.
 |      
 |      Returns
 |      -------
 |      y_proba : array-like, shape = [n_samples, n_classes]

However, **the order of classes is not given in returns**. For example, assume there's a four-class problem and the computed probabilities for a case are 0.2, 0.25, 0.4, 0.15. The problem is, 0.2/0.25/0.4/0.15 is the probability of which class?

I notice that there's an attribute self.classes_. I guess it's what I want (Unfortunately there's no introduction of it in help()). But then I find that it's simply a useless numpy array - For an m-class classification problem, it's always [0, 1, 2, ..., m-1] rather than names of classes.

**Really eager to find the solution cause I'm working on a project in company. Thanks!!!**

**Comment by SleepyRoy** [comment]
@ayuwhu
Thanks for your reply! It's night here and I'll try it tomorrow.
I used to observe some experiments and it seems that the names of classes are always placed in ascending order. For example, if there's a four-class problem (class names: ab, bc, cd, da) and predict_proba returns [0.1, 0.2, 0.3, 0.4], then it seems that 0.1-ab, 0.2-bc, 0.3-cd, 0.4-da.
In my current code I just made this assumption. Is it correct? If yes, I won't have to change my code. : )

**Comment by skasturi** [comment]
The label encoder used for transforming non-numeric y into numerics is provided as fitted_model.y_transformer. 

You can use inverse_transform() method of this transformer to obtain the actual label. 

Example with finding "max": 

![image](https://user-images.githubusercontent.com/482709/64367123-6f5aa400-cfcc-11e9-8a8c-e827f2a95698.png)

```python
for probabilities in fitted_model.predict_proba(X_test):
    # Get maximum probability for this row
    max_prob = max(probabilities)
    # Get the index of the class with highest probability
    class_with_best_prob, = np.where(probabilities == max_prob)
    print(fitted_model.y_transformer.inverse_transform(class_with_best_prob)[0], max_prob)
```

**Comment by v-strudm-msft** [comment]
Thank you for your post. We’re glad to see this issue was resolved and will close this thread. Should you have additional questions, please continue to post here and we will gladly continue the discussion.

**Comment by datashinobi** [comment]
This should work better

```
import pandas as pd

output_df = pd.DataFrame(classifer.predict_proba(input_sample), 
             columns=classifer.y_transformer.inverse_transform(classifer.classes_))
output_df.T
```
