### ISSUE TITLE
There is no description of run_after() function?

### ISSUE THREAD

**Issue by hangzh-msft** [Azure/MachineLearningNotebooks#528]
I got some internal help to use step3.run_after(step1) if I need to run step3 after step1 is completed. But I could not find the documentation here on the parameters of run_after(). 
My situation is that step3 needs to run only after both step1 and step2 is completed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2836b6f1-7d38-6091-e67a-1a4305fc8f4d
* Version Independent ID: 4153252b-fa22-0ccd-b9bd-a460f422339f
* Content: [azureml.pipeline.steps.python_script_step.PythonScriptStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.pythonscriptstep?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.PythonScriptStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.PythonScriptStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by sanpil** [comment]
If you want to run a particular step (step3) run after step1 and step2 are completed, please use:
`step3.run_after(step1)
step3.run_after(step2)
`

**Comment by vmagelo** [comment]
Additional information has been added to the SDK reference and the changes be published in the next two weeks.
