### ISSUE TITLE
Azureml Automl "Error: Null" Vague Error

### ISSUE THREAD

**Issue by nemasobhani** [Azure/MachineLearningNotebooks#534]
I'm not exactly sure on how to interpret this and what to refine. The error I'm getting is in the azureml.PipelineStep automl step. Here is the [link](https://mlworkspace.azure.ai/portal/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/RG-ITSMLTeam-Dev/providers/Microsoft.MachineLearningServices/workspaces/avadevitsmlsvc/experiments/deal-deal-nema/runs/7abe9617-ac79-413b-8843-7fd3878313f0).

When my dataset has more than ~1200 features, I consistently get this error, but when there are fewer features it works fine. Is there some limitation here?

**Comment by nemasobhani** [comment]
It seems to have been a one-off random occurrence. Considering solved.

**Comment by sonnypark** [comment]
Somehow I lost track on this. You can let me know if you have any further issues.
