### ISSUE TITLE
Add parameters to constructor of ContainerRegistry class

### ISSUE THREAD

**Issue by Lawiss** [Azure/MachineLearningNotebooks#535]
The ContainerRegistry class of python SDK does not accept parameters for its constructor, thus we must set each instance attributes (address, username and password) manually after object instanciation. Please add those attributes as parameters in the constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192d6efe-3bf4-adc1-e097-646df4b5e09c
* Version Independent ID: 618ded3a-585a-df39-0df5-9e229f9f5c35
* Content: [azureml.core.container_registry.ContainerRegistry class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.container_registry.containerregistry?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.container_registry.ContainerRegistry.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.container_registry.ContainerRegistry.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
For now, changed the SDK documentation to correctly represent address, username and password as instance attributes rather than parameters of the constructor.
