### ISSUE TITLE
[Notebook] Please do not publish code that has not been tested in a generic subscription

### ISSUE THREAD

**Issue by paulopsgility** [Azure/MachineLearningNotebooks#544]
### DESCRIPTION: Describe clearly + concisely
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-automated-machine-learning-step.ipynb does not work in a default azure subscription. At a miniumum, the azure-ml sdk is not the correct version but even after updating it there are still lots of issues.

.
### REPRODUCIBLE: Steps
In a generic subscription, not one that was provided to you by MS, create a notebook vm, run the notebook above, fail (because the default version of the azure ml sdk on a notebook vm is 1.0.55). Update to 1.0.57 of the azure ml sdk and you will get past the initial errors only to fail later.

.
### EXPECTATION: Clear description 
Published example notebooks should be verified on the current default versions of whatever services they require. For example, these notebooks should run without anything other than config changes on a Notebook VM.

.
### CONFIG/ENVIRONMENT: 
```Provide where applicable

## Your Python & SDK version:

## Environment definition:

## Notebook name or Python scripts:

## Run and Workspace Id:

## Pipeline definition:

## Example data:

## Any log files:





```

**Comment by v-strudm-msft** [comment]
Thank you for your post and participation. We see our response was some time ago. We've not heard from you so we will close this thread. Should you need further assistance, please post on this forum and we will respond promptly.
