### ISSUE TITLE
Circular link in the description of the 'preprocess' parameter

### ISSUE THREAD

**Issue by wooters** [Azure/MachineLearningNotebooks#546]
At the end of the description of the `preprocess` parameter, it has:
```
More details can be found here: https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig?view=azure-ml-py
```
This link points back to this same page, so there is no way to get any more information about this parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deee583c-0e11-b1da-bfe0-defb5a6f4b29
* Version Independent ID: b58f7491-6e71-29ab-f6a4-609a7d75cfed
* Content: [azureml.train.automl.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlconfig?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlconfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Fix is live.
