### ISSUE TITLE
Experimentation script in custom docker image works fine outside AzureML

### ISSUE THREAD

**Issue by georgeAccnt-GH** [Azure/MachineLearningNotebooks#549]
**Describe the bug**
experiment script in custom docker image works fine outside AzureML but fails inside AzureML Estimator, using either local or remote compute target.

Azure ML SDK Version:  1.0.57 

**To Reproduce**
I am trying to run an estimator with a custom docker image (cell under “Create an Azure ML SDK estimator with custom docker image, [here](https://github.com/microsoft/vb_sw_fwi/blob/bf0c980bef3f22f1ed072f4d45766c7fc41b1d67/code/020_CreateExperimentationAzureMLEstimator_GeophysicsTutorial_FWI_1_Forward_Modeling.ipynb)). I test the experiment script in custom docker image before that (in cell under “test script outside azurml”) outside AzureML, and it clearly shows (both via cli and within the experiment .py script) the default conda env fwi01_conda_env does have azureml. 1.0.55. However, Azure ML estimator fails both when:
-	using compute_target=gpu_cluster, apparently because AzureML unexpectedly decides to switch the default conda env to  “base”?
-	Using compute_target='local', with an unhelpful message in 60_control_log.txt log file “python: can't open file 'azureml-setup/run_script.py': [Errno 2] No such file or directory” ???

**Expected behavior**
Parity between running a script outside AzureML and within AzureML If the experiment script runs fine inside my custom docker image outside AzureML, it should run just as well inside AzureML, using both local and remote compute targets.

**Additional context**

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close it. Should you still need   assistance with this or another issue, please re-post and we will respond   promptly.
