### ISSUE TITLE
must_exist

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#550]
that param (must_exist) should be described at the top of the page in the constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a90fec-0f19-3637-d73f-621384c1f269
* Version Independent ID: 4d10d8f6-191e-393a-24a3-31c6e1baeb16
* Content: [azureml.core.webservice.local.LocalWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.local.localwebservice?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.local.LocalWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.local.LocalWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
This was addressed and is live in docs.
