### ISSUE TITLE
uniformity in constructor and register for parameters

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#551]
register(workspace, model_path, model_name, tags=None, properties=None, description=None, datasets=None, model_framework=None, model_framework_version=None, child_paths=None)

`name` for model registration is `model_name`, and on the constructor, it's `name`. I would suggest having the same nomenclature on both (and maybe more params, this is the one I've seen quickly).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d33267-fb2b-bc8a-1b61-50122b944dd1
* Version Independent ID: 17c92047-89c8-0881-6d9f-235f50a2d5af
* Content: [azureml.core.model.Model class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py#register-workspace--model-path--model-name--tags-none--properties-none--description-none--datasets-none--model-framework-none--model-framework-version-none--child-paths-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close it. Should you still need   assistance with this or another issue, please re-post and we will respond   promptly.
