### ISSUE TITLE
[Notebook issue]

### ISSUE THREAD

**Issue by sarahmass** [Azure/MachineLearningNotebooks#553]
**Describe the bug**
I am using the PyTorch class and am trying to use framework_version = 1.2 which is said to be supported, but when I run my code I get this:
TrainingException: TrainingException:
	Message: PyTorch 1.2 is not currently supported by the PyTorch estimator. Check https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn?view=azure-ml-py for all supported versions. To use PyTorch 1.2, switch to the generic Estimator class for your experiment.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "PyTorch 1.2 is not currently supported by the PyTorch estimator. Check https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn?view=azure-ml-py for all supported versions. To use PyTorch 1.2, switch to the generic Estimator class for your experiment."

Provide the following if applicable:
+ Your Python & SDK version: tried on version 1.0.55 and on 1.0.57

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
