### ISSUE TITLE
Incomplete statement at the remarks session

### ISSUE THREAD

**Issue by nansravn** [Azure/MachineLearningNotebooks#554]
At the remarks session we have the following statement:
"For example users can submit a simple training script on the local machine using this code."

Where is the example code? It would be great to have a sample code explaining the usage of this class together with ScriptRunConfig().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1053292b-f07e-a923-c880-11438dbe892f
* Version Independent ID: 886c442e-b1ee-af68-9810-7bca8571638a
* Content: [azureml.core.RunConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.RunConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.RunConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Added missing sample. Change in SDK should appear in next release in 2 weeks. Thanks for the report.

**Comment by j-martens** [comment]
Thanks for your report. We hope this answers your question. We will now proceed to close this issue.
