### ISSUE TITLE
RunConfiguration example

### ISSUE THREAD

**Issue by nansravn** [Azure/MachineLearningNotebooks#555]
We have the following statement on the Ramarks section:
"see the python code example in the documentation for RunConfiguration for an example of a ScriptRunConfig object in action."

I've searched on the RunConfiguration doc, but couldn't find any example of a ScriptRunConfig object in action.

Could you add an example about how to use ScriptRunConfig?

I'm reviewing some MLOps samples, I have an Azure DevOps hosted environment that's already configured with all the requirements for running successfully my experiment. I want to submit a training code from this DevOps hosted env, to be execute locally on the same environment. I don't want to specify additional conda_env packages or nothing like that.

Do I only need to use RunConfiguration(), with default parameters, on my ScriptRunConfig()?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c66c6bf-7238-9cbd-0561-45848e550bc3
* Version Independent ID: f82f82a9-38d2-5347-2f3a-fec5af849911
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
We added a sample. Look for it in the next release of the SDK in 2 weeks. Thanks!

**Comment by vmagelo** [comment]
Here's something that should get you going:

from azureml.core import ScriptRunConfig, RunConfiguration, Experiment

\# create or load an experiment
experiment = Experiment(workspace, "MyExperiment")
\# run a trial from the train.py code in your current directory
config = ScriptRunConfig(source_directory='.', script='train.py',
    run_config=RunConfiguration())
script_run = experiment.submit(config)

Also take a look at:
* the article https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-use-environments#using-environments-for-training
* these training notebooks https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/training

**Comment by j-martens** [comment]
Thanks for your report. We hope this answers your question. We will now proceed to close this issue.
