### ISSUE TITLE
Too many of : Error: Unable to upload project files to working directory in AzureFile because the storage is overloaded

### ISSUE THREAD

**Issue by pablomarin** [Azure/MachineLearningNotebooks#557]
SDK Version : 1.0.55

I’m having 10 AML clusters of 5 parallel hyperdrive runs each (50 runs at the same time) , and max runs of 150 for each, (1500 child runs total)
 
I am experiencing in average 30-40% of the child runs with FAILED status with this error:

***Unable to upload project files to working directory in AzureFile because the storage is overloaded.***
 
This is a huge % of failed runs related to an azure issue, non-user problem.
 
What can be done here to not use AzureFiles and use blob instead?

# Code:

```python 
#Start Experiment

exp = Experiment(workspace=ws, name=experiment_name)

print("Submitting HyperDrive Runs for Experiment:",experiment_name)
print(strftime("%Y-%m-%d %H:%M:%S", gmtime()))

#Get the list of AML clusters

clust = {}
clist = AmlCompute.list(ws)
for c in clist:
    if ('train' in c.name):
        clust[c.name] = c
        
MAX_CONCURRENT_RUNS = list(clust.values())[0].get_status().scale_settings.maximum_node_count        
NUM_HRUNS = len(list(clust.values()))       

MAX_TOTAL_RUNS_PER_CLUSTER = 150
METRIC = 'mymetric'


# Assign the HyperDrive Runs to each cluster        

htrDic = {}

for i, ct in clust.items():

    estimator = Estimator(source_directory=script_folder,
                compute_target=ct,
                inputs=[ds],
                script_params=script_params,
                entry_script=entry_script,
                conda_packages=conda_packages,
                pip_packages=pip_packages,
                custom_docker_image=dockerhub_image,
                use_gpu=True)
    
    
    htc = HyperDriveConfig(estimator=estimator,
                hyperparameter_sampling=param_sampling,
                primary_metric_name=METRIC,
                primary_metric_goal=PrimaryMetricGoal.MAXIMIZE,
                max_total_runs=MAX_TOTAL_RUNS_PER_CLUSTER,
                max_concurrent_runs=MAX_CONCURRENT_RUNS
               )
    
    
    htrDic[ct.name] = exp.submit(config=htc)
    
    print("Submited on cluster: {0}, RunID: {1}".format(ct.name,htrDic[ct.name].id))

    
print("Finished submitting experiments::")
print(strftime("%Y-%m-%d %H:%M:%S", gmtime()))

```

```python
# Monitor runs

for key,value in htrDic.items():
    hd_details = htrDic[key].get_details()
    print(hd_details['runId'] +' in cluster ' + hd_details['target'] + ' is ' + hd_details['status'])
    
    run_children = list(htrDic[key].get_children())
    print(pd.Series(map(lambda x: x.status, run_children)).value_counts().rename('Count').to_frame().transpose(), "\n")

```

# Results

Algo11_1567417449527 in cluster train-L4-78Hx is Running
       Completed  Failed  Running
Count         46      43        4 

Algo11_1567417450806 in cluster train-L4-09Hb is Running
       Completed  Failed  Running
Count         47      31        4 

Algo11_1567417454218 in cluster train-L4-65bi is Running
       Completed  Failed  Running
Count         36      18        4 

Algo11_1567417455859 in cluster train-L4-41Yn is Running
       Completed  Failed  Running
Count         42      20        4 

Algo11_1567417457865 in cluster train-L4-90HW is Running
       Failed  Completed  Running
Count      53         48        4 

Algo11_1567417458649 in cluster train-L4-07xz is Running
       Completed  Failed  Running
Count         48      33        4 

Algo11_1567417460119 in cluster train-L4-75aO is Running
       Completed  Failed  Running
Count         32      21        4 

Algo11_1567417460869 in cluster train-L4-27qh is Running
       Completed  Failed  Running  Finalizing
Count         42      22        3           1 

Algo11_1567417461685 in cluster train-L4-75il is Running
       Completed  Failed  Running  Starting
Count         45      28        2         1

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was not addressed and was   posted some time ago. Our apologies. We will close it. Should you still need   assistance with this or another issue, please re-post and we will respond   promptly.
