### ISSUE TITLE
Estimator custom_docker_image not working as expected with mmlspark

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#559]
See bug report here.
https://github.com/Azure/mmlspark/issues/655

@imatiach-msft says ML Service doesn't _really_ use `mmlspark`? @jpe316 @yanrez  any ideas?

**Comment by imatiach-msft** [comment]
nope, it does not, this is just a docker image - not related to the mmlspark codebase

**Comment by swanderz** [comment]
thanks @imatiach-msft -- totally get it now. My question now is who maintains the mmlspark docker image on docker hub?

**Comment by mhamilton723** [comment]
@swanderz What issue are you running into? I remade the docker image for 0.18 release of MMLSpark and can easily patch it if you need a hotfix

**Comment by swanderz** [comment]
@mhamilton723  I'm so glad @heatherbshapiro tracked you down for me!

if you submit the script, `spark_test.py` below to AML compute via the Azure ML SDK Estimator class, it works when you use docker image tagged `0.16` but not with `latest`. Any idea why `findspark` can't locate the spark installation anymore?


### `spark_test.py`
```python
import findspark as fs
import pyspark

print("find spark")
fs.find()
print("init spark")
fs.init()
print("Connect to Spark")
# Start Spark session
spark = pyspark.sql.SparkSession.builder.appName('test').getOrCreate()
print("spark con", spark)
```

### Estimator definition
```python
from azureml.train.estimator import Estimator
test_estimator = Estimator(
    source_directory=project_folder,
    entry_script="spark_test.py",
    script_params={},
    compute_target=cpu_cluster,
    conda_packages=['pyspark', 'pandas', 'numpy'],
    pip_packages=['pip', 'findspark'],
#     custom_docker_image='microsoft/mmlspark:0.16' # works
    custom_docker_image='microsoft/mmlspark:latest'  # doesn't work
)

run = experiment.submit(config=test_estimator)
run
```

### traceback

```
Traceback (most recent call last):
  File "spark_test.py", line 5, in <module>
    fs.find()
  File "/azureml-envs/azureml_64315925d0fe516da74ccb98be05e953/lib/python3.6/site-packages/findspark.py", line 33, in find
    raise ValueError("Couldn't find Spark, make sure SPARK_HOME env is set"
ValueError: Couldn't find Spark, make sure SPARK_HOME env is set or Spark is in an expected location (e.g. from homebrew installation).
```

### reprex

I took an existing notebook from this repo to reproduce the error. Check out the latest commit I made on my fork and [the notebook ](https://github.com/swanderz/MachineLearningNotebooks/blob/bug_mmlspark/how-to-use-azureml/training/train-on-amlcompute/train-on-amlcompute.ipynb) if need be

**Comment by mhamilton723** [comment]
Replicating this message on GH:

@swanderz, in the new docker image (for v0.18.1) we have transitioned to a system that doesen't need findspark so you can just import pyspark directly. When you use the docker image for notebooks we automatically load up spark with mmlspark for your information this script runs one notebook startup so you can just use the spark variable like you can in databricks. I would try changing your code to look like (MMLSpark lines optional):

```
from pyspark.sql import SparkSession

spark = SparkSession.builder \
.master("local[*]") \
.appName("MMLSpark Docker App") \
.config("spark.jars.packages", "com.microsoft.ml.spark:mmlspark_2.11:" + os.environ["MMLSPARK_VERSION"]) \
.config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
.getOrCreate()

print("spark con", spark)
```

If this doesn't work or you run into other issues with the new docker setup please let me know and ill help ya out. Also if you are using mmlspark models, some imports have changed in the latest version and the API docs https://mmlspark.blob.core.windows.net/docs/0.18.1/pyspark/mmlspark.html show all the new namespaces.  Thanks for your patience in working with us through our large quality upgrade!

**Comment by v-strudm-msft** [comment]
Thank you for your post. We’re glad to see this issue was resolved and will close this thread. Should you have additional questions, please continue to post here and we will gladly continue the discussion.
