### ISSUE TITLE
Missing module - No module named 'automl.client'

### ISSUE THREAD

**Issue by burstingninja** [Azure/MachineLearningNotebooks#56]
@rastala 
There is an error in the following notebook 03b.auto-ml-remote-batchai 

when running the cell under" Retrieve the Best Model"

best_run, fitted_model = remote_run.get_output()

print(best_run)

print(fitted_model)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-0c1d59c9eaaa> in <module>()
----> 1 best_run, fitted_model = remote_run.get_output()
      2 print(best_run)
      3 print(fitted_model)

~/anaconda3_501/lib/python3.6/site-packages/azureml/train/automl/run.py in get_output(self, iteration, metric)
    329         curr_run.download_file(name=model_name, output_file_path=model_local)
    330         with open(model_local, "rb") as model_file:
--> 331             fitted_model = pickle.load(model_file)
    332         return curr_run, fitted_model
    333 

ModuleNotFoundError: No module named 'automl.client'

**Comment by wchill** [comment]
Hi @burstingninja it seems you're running an older SDK version. We added a fix for this issue that should be present in SDK version 0.1.68. Can you try upgrading the package version with `pip install --upgrade azureml-train-automl`?

**Comment by burstingninja** [comment]
@wchill  Hello wchill, I tried your suggestion, but it didn't work. I am runny the notebook using azure notebooks.
it said I needed to run the command as SUDO; but I don't know microsoft's default password for the terminal in azure notebooks.
Besides pip installation of the library, Am I not missing to add an import statement?

**Comment by wchill** [comment]
You shouldn't be, the issue is an SDK one in SDK versions before 0.1.68.

Running pip with the `--user` parameter should get you around the sudo issue. Please try that and let me know if that works for you.

**Comment by burstingninja** [comment]
After running the command pip install --upgrade azureml-train-automl --user 
it does install successfully, but when I run again pip freeze to review my installed packages it returns the following error.
nbuser@nbserver:~$ pip freeze
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name 'main'

And when I run the runbook, the error persists.
how should the automl.client import look like? I already try with
import automl but it throws the same error
<img width="499" alt="capture" src="https://user-images.githubusercontent.com/7752099/47463326-8412bc80-d7ab-11e8-8bbc-04adba19548b.PNG">
The image was taken from this practice 08.auto-ml-remote-execution-with-text-file-on-DSVM.ipynb
which presents the same error.

Thank you in advance

**Comment by burstingninja** [comment]
Hello @jeff-shepherd  any updates?

**Comment by jeff-shepherd** [comment]
I was able to reproduce this issue and fixed it by upgrading the azureml-train-automl.
I ran the following command from a new cell in the notebook:
**!pip install --upgrade azureml-train-automl**

After this command completed I restarted the kernel using the menu option Kernel | Restart.
I then executed all of the cells of the notebook again.

The issue was that the remote run uses the latest published azureml-train-automl, which is version 1.68 but the notebook was running with version 1.65.   The get_output from version 1.65 was not able to load the model created by version 1.68. 

Please try the upgrade from a notebook cell, restart the kernel and let me know if you still see an issue.

**Comment by burstingninja** [comment]
It worked as a charm @jeff-shepherd . Thank you very much!
