### ISSUE TITLE
description for version

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#561]
should be "Optional version tag to denote a change in functionality for the module" to align with others, unless there's another reason for the parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b41845-1e17-a675-a00d-4c315ab57acd
* Version Independent ID: e968964b-e80a-3ff7-7dd6-c46042cb0de2
* Content: [azureml.pipeline.steps.hyper_drive_step.HyperDriveStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.hyper_drive_step.hyperdrivestep?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.hyper_drive_step.HyperDriveStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.hyper_drive_step.HyperDriveStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks for your report. We updated the SDK reference and the change will be published in the next two weeks.
