### ISSUE TITLE
version parameter

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#562]
should be "Optional version tag to denote a change in functionality for the module" to align with others, unless there's another reason for the parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3fba894-55e1-ad35-d940-b8dec82c1375
* Version Independent ID: 5e0b8c9e-c85b-19ad-0979-c562fcb527ff
* Content: [azureml.pipeline.steps.estimator_step.EstimatorStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.estimator_step.estimatorstep?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.estimator_step.EstimatorStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.estimator_step.EstimatorStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks for your report. Additional information has been added to the SDK reference and will be published in the next two weeks.
