### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by daiyoshi** [Azure/MachineLearningNotebooks#565]
A timeout occurs in 30 seconds. 
Please describe the parameters so that you can change the timeout settings.
I want CommandTimeout setting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6fab1c8-11bd-be26-cc24-507b1d2ce30c
* Version Independent ID: fbc57753-a5d8-fa9b-66e2-24f7575e551f
* Content: [azureml.dataprep.MSSQLDataSource class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-dataprep/azureml.dataprep.mssqldatasource?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-dataprep/azureml.dataprep.MSSQLDataSource.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-dataprep/azureml.dataprep.MSSQLDataSource.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
