### ISSUE TITLE
gpu_support warning issue for azureml version 1.0.60

### ISSUE THREAD

**Issue by AbhishekTanksali** [Azure/MachineLearningNotebooks#569]
**Describe the bug**

I have upgraded the azureml-sdk[notebooks] version from 1.0.43 to 1.0.60 i.e to latest in YAML files under compute/aml_config.

I am suddenly getting below warning:

_**"WARNING - 'gpu_support' is no longer necessary; AzureML now automatically detects and uses nvidia docker extension when it is available. It will be removed in a future release."**_

I am using aml_compute.runconfig & it has a field "gpu_support = false" under docker section.
I tried removing this field as well as trying to change "false" to "" / None / empty space, but still the gpu_support warning is coming.

Kindly let me know is there a way to get rid of this warning.

Provide the following if applicable:
+ Your Python & SDK version: 1.0.60
+ Python Scripts or the full notebook name

# Below is the snippet of code in pipeline.py for imporing ML workspace, experiment & run configuration.
`
if remote_run is True:
    try:
        auth = ServicePrincipalAuthentication(
            tenant_id=os.getenv('TENANT_ID', "TENANT_ID was not found"),
            service_principal_id=os.getenv('APP_ID', "APP_ID was not found"),  # 1.0.33 change to service_principal_id
            service_principal_password=os.getenv('CLIENT_SECRET', "CLIENT_SECRET was not found"),  # 1.0.33 change to service_principal_password
        )
    except KeyError:
        print("Getting Service Principal Authentication from Azure Devops")
        auth = None
        pass
else:
    auth = InteractiveLoginAuthentication(tenant_id="cf36141c-ddd7-45a7-b073-111f66d0b30c")

ws = Workspace.from_config(auth=auth, path=get_aml_config())
print("Found workspace {} at location {}".format(ws.name, ws.location))
project_name = make_resource_name(prefix, repo_name, max_len=36)
exp = Experiment(workspace=ws, name=project_name)
print("Experiment: {}".format(exp.name))
aml_compute = RunConfiguration().load(path='./compute/', name='aml_compute')`

# Attaching the aml_compute.runconfig in zip file format. This file is present under path compute\aml_config in my azure repo
[aml_compute.zip](https://github.com/Azure/MachineLearningNotebooks/files/3599769/aml_compute.zip)

+ Run and Workspace Id: 
workspace ID: avadevitsmlsvc
experiment name: ret-attestdeprecationwarnings
Run: 45, 34

**To Reproduce**
1. Change azureml-sdk[notebooks] version to 1.0.60 in YAML and run the pipeline

**Expected behavior**
Expected logs should not contain any warning related to gpu_support.

Kindly provide your inputs to get rid of this warning. 
Thanks.

**Comment by heatherbshapiro** [comment]
If you're using estimators, they implicitly set/access the gpu_support flag. We have plans to remove that in the future. In the meantime, you can ignore the warnings as they're deprecation warnings and shouldn't be impacting the run.

**Comment by v-strudm-msft** [comment]
Thank you for your post. It looks as though this issue was resolved so we closed this thread. Should you have additional questions, please continue to post here and and we will gladly continue the discussion.
