### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#571]
Using the new workspace in public preview, I saw I can generate a dataset profile. I tried to do that, but the generated run failed.

here's the [65_job_prep-tvmps_cb62dce547f1c239a889d4b7e44f5557607b10d2070db0f160ce7e42081f1df2_d.txt](https://gist.github.com/swanderz/d390a2347eab5d38cf031f65c0df0ff4).
Here's a snippet (for SEO)
```
Starting job preparation. Current time:2019-09-11T22:21:40.949160
Extracting the control code.
Creating directory: azureml-logs/
Retrieving project from snapshot: 78c852c0-af9c-4d22-8c1e-9bbf176b3bb9
Starting the daemon thread to refresh tokens in background for process with pid = 321
Unable to retrieve SaS Urls for project download
Failed to set run error
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
```
**Run  Id** : `dataset_1beea69c-8247-4067-b9ad-488390b145a5`
**workspace**: avadevitsmlsvc

**Comment by jenren** [comment]
Thanks for reporting this, Anders. We'll look into this now and hopefully get back to you shortly.

**Comment by swanderz** [comment]
[Here's a Dropbox link w/ the log files](https://www.dropbox.com/s/xck8dw2w3690ivo/dataset_1beea69c-8247-4067-b9ad-488390b145a5.zip?dl=0)

**Comment by v-strudm-msft** [comment]
Thank you for your post. It looks as though this issue was resolved so we closed this thread. Should you have additional questions, please continue to post here and and we will gladly continue the discussion.
