### ISSUE TITLE
Updates on project files not available in snapshot

### ISSUE THREAD

**Issue by gison93** [Azure/MachineLearningNotebooks#575]
When creating experiments if some files are modified sometimes those changes are not present in the snapshot used in the Experiment.
This leads eventually to a failure.

**Comment by purnesh42H** [comment]
Is it about pipeline experiments?

**Comment by gison93** [comment]
Thank you for your quick answer! Yes, it is a pipeline experiment. I am experiencing the issue when a json file used in the source script of one of the step is modified. All the files used by the pipeline main file and its step are in the same folder.

**Comment by purnesh42H** [comment]
which version of sdk are you using? Is it the latest?

**Comment by gison93** [comment]
I am using version 1.0.8.
In the meanwhile I have figured out that if I make changes in a python script used in a PythonScriptStep (also a trivial one like adding a comment) the changes that I make in the json file are uploaded in the snapshot, otherwise the previous state is present in the snapshot.

If it can be helpful I will provide a repro.

 Anyway I will try with the latest version and see if I get the same problem.

**Comment by purnesh42H** [comment]
yes, that's a correct behavior for the version(very old) you are using. Versions before 1.0.43 only check scripts(.py) files for the changes. if you want to continue using the old version, then you can specify the paths you want to hash in `hash_paths` parameter of your step. However, I would recommend you to upgrade to latest version. In that, everything under source_directory is hashed by default.

**Comment by gison93** [comment]
Thank you for your help!

**Comment by v-strudm-msft** [comment]
Thank   you for your post. It looks as though this issue was resolved so we closed   this thread. Should you have additional questions, please continue to post   here and and we will gladly continue the discussion.
