### ISSUE TITLE
Logging metrics to parent run

### ISSUE THREAD

**Issue by alieus** [Azure/MachineLearningNotebooks#576]
I would love to be able to log metrics to the parent run. Is run.parent.log() a thing? I have tried this but it doesn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b5836ca-7af4-3070-3e68-3bf8a9728aae
* Version Independent ID: 4f8b1886-9f38-ff00-1e30-02476c707972
* Content: [azureml.core.run.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.run.Run.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.run.Run.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by alieus** [comment]
Figured out that run.parent.log() works on versions later than 1.0.43. I updated my SDK to 1.0.62 and it now works. 

I have not seen anything on run.parent.log() / run.parent.tag() on the docs, it would be great if these can be added to the docs

**Comment by vmagelo** [comment]
Added a note to the docs as suggested above. Will appear in next release in approx 2 weeks.
