### ISSUE TITLE
ComputeTarget.create fails with uninformative message if clustername is NoneType

### ISSUE THREAD

**Issue by georgeAccnt-GH** [Azure/MachineLearningNotebooks#581]
**Describe the bug**
gpu_cluster_name = os.getenv('non_existent')
gpu_cluster_name
type(gpu_cluster_name)
 --> NoneType

compute_config = AmlCompute.provisioning_configuration(vm_size="Standard_NC6",
                                                       min_nodes=0,
                                                       max_nodes=1)
gpu_cluster = ComputeTarget.create(ws, gpu_cluster_name, compute_config)
gpu_cluster.wait_for_completion(show_output=True)

Output:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-535b2ada146b> in <module>
      6 
      7 # Wait for the cluster to complete, show the output log
----> 8 gpu_cluster.wait_for_completion(show_output=True)

/opt/conda/envs/aml-sdk-conda-env/lib/python3.6/site-packages/azureml/core/compute/amlcompute.py in wait_for_completion(self, show_output, min_node_count, timeout_in_minutes)
    257         """
    258         min_nodes_reached, timeout_reached, terminal_state_reached, status_errors_present = \
--> 259             self._wait_for_nodes(min_node_count, timeout_in_minutes, show_output)
    260         if show_output:
    261             print('AmlCompute wait for completion finished')

/opt/conda/envs/aml-sdk-conda-env/lib/python3.6/site-packages/azureml/core/compute/amlcompute.py in _wait_for_nodes(self, min_node_count, timeout_in_minutes, show_output)
    301         :rtype:
    302         """
--> 303         self.refresh_state()
    304         start_time = time.time()
    305 

/opt/conda/envs/aml-sdk-conda-env/lib/python3.6/site-packages/azureml/core/compute/amlcompute.py in refresh_state(self)
    417         Primarily useful for manual polling of compute state.
    418         """
--> 419         cluster = AmlCompute(self.workspace, self.name)
    420         self.modified_on = cluster.modified_on
    421         self.provisioning_state = cluster.provisioning_state

AttributeError: 'AmlCompute' object has no attribute 'workspace'

Provide the following if applicable:
Azure ML SDK Version:  1.0.60
'Linux-4.15.0-1057-azure-x86_64-with-debian-10.0' 

**To Reproduce**
1. 

**Expected behavior**

**Additional context**

**Comment by v-strudm-msft** [comment]
Thank   you for reaching out to us.  We see this issue was not addressed and was  posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
