### ISSUE TITLE
Example for `Run.register_model()` misleading

### ISSUE THREAD

**Issue by nihil0** [Azure/MachineLearningNotebooks#583]
The remark for this method says `model = best_run.register_model(model_name = 'best_model', model_path = 'outputs/model.pkl')`. But the documentation says that `model_path` is relative to the `outputs/` directory.  I would be better to clarify this in the remark. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b5836ca-7af4-3070-3e68-3bf8a9728aae
* Version Independent ID: 4f8b1886-9f38-ff00-1e30-02476c707972
* Content: [azureml.core.run.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#register-model-model-name--model-path-none--tags-none--properties-none--model-framework-none--model-framework-version-none--description-none--datasets-none----kwargs-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.run.Run.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.run.Run.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
We clarified the description for model_path parameter. It's not relative to the outputs/ directory, which is a commonly used in examples, but rather relative to root of the run's file structure. When in doubt, use run.get_files() to see the files (with paths) created by the run.
