### ISSUE TITLE
Technical details for the explain_model() function?

### ISSUE THREAD

**Issue by wooters** [Azure/MachineLearningNotebooks#584]
I'm using the `explain_model()` function for a classification model. The documentation above uses the words "feature importance" to describe the return values from this function. I'd like to get more information about what _exactly_ this means. Are there any academic papers or documentation that describe what this function is computing for a classification problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c9ed64-01c3-d7d5-bbdb-8ede3f69d02e
* Version Independent ID: 01df3a5d-c87d-b629-4cfe-2ddee7f2eb06
* Content: [azureml.train.automl.automlexplainer module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlexplainer?view=azure-ml-py#explain-model-fitted-model--x-train--x-test--best-run-none--features-none--y-train-none----kwargs-)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlexplainer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlexplainer.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by wamartin-aml** [comment]
Thanks @swanderz for alerting us to this one! Yes @wooters, there are a few different meanings for the term "feature importance" - when we refer to it, we are primarily using it in the same sense as SHAP does (see [the SHAP Github](https://github.com/slundberg/shap) for some high level information and links to the various papers with precise definitions). In addition, you may find useful information in [the paper for LIME](https://arxiv.org/abs/1602.04938) and a very different take on "feature importance" in [the paper](http://people.dbmi.columbia.edu/noemie/papers/15kdd.pdf) behind [Microsoft's state-of-the-art interpret repo](https://github.com/Microsoft/interpret).

**Comment by wamartin-aml** [comment]
@mesameki is it possible for us to make it easier for users to find this information about feature importance in our documentation?

**Comment by wooters** [comment]
Thanks @wamartin-aml, that is exactly the info I was looking for!

**Comment by vmagelo** [comment]
Added text similar to wamartin-aml comment above to intro to automlexplainer module.
