### ISSUE TITLE
[Notebook] QuantizedSsdVgg example

### ISSUE THREAD

**Issue by pzn666** [Azure/MachineLearningNotebooks#585]
Recently I followed the FPGA deployment example and successfully deployed a QuantizedResnet50 model to AKS.
Is there any example by using QuantizedSsdVgg?
I'm not familiar with SSD but seems QuantizedSsdVgg returns tensors from each ssd block which are tensors before output layer(or aggregation layer) rather then returns simple location and classify tensors
Any documents or examples are available?

**Comment by gvashishtha** [comment]
If QuantizedSsdVgg wasn't in the accel-models samples, then unfortunately we don't have one.
