### ISSUE TITLE
No Logs/Error messages on failed compute provisioning

### ISSUE THREAD

**Issue by djpugh** [Azure/MachineLearningNotebooks#590]
On attempt to provision a new AML Compute cluster, the provisioning fails with:
"An internal server error occurred. Please try again. If the problem persists, contact support"

There is no additional information provided here, nor in the resource group/ML Service workspace activity log

To Reproduce
1.

Expected behavior
A clear log of the failure inside the activity log

Additional context
We have fairly prescriptive Azure policies that limit certain things and actions, which seem likely to be causing this, but there is no error messages/notifications in the logs to help debug this

**Comment by djpugh** [comment]
To Reproduce:
1. Open ML Workspace
2. Select Compute, Add Compute
3. Select ML Compute (North Europe Region)
4. Enter a name and select a VM (tried multiple D types)
5. Select max nodes (tried 1, 2, 3)
6. Hit Create

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
