### ISSUE TITLE
end-to-end-samples directory is empty

### ISSUE THREAD

**Issue by wamartin-aml** [Azure/MachineLearningNotebooks#591]
**Describe the bug**
This directory should probably be used or removed.

**Comment by vizhur** [comment]
Thank you for reporting the issue @wamartin-aml! We appreciate your input. The folder will be deleted with a next release

**Comment by v-strudm-msft** [comment]
Thank you for your post. It looks as though this issue was resolved so we closed this thread. Should you have additional questions, please continue to post here.
