### ISSUE TITLE
Energy AutoML forecasting model example notebook error

### ISSUE THREAD

**Issue by annaymj** [Azure/MachineLearningNotebooks#593]
### DESCRIPTION: 
One line of code returns error in 
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-energy-demand/auto-ml-forecasting-energy-demand.ipynb

the .get_output works for local_run but not for local_run_lags

.
### REPRODUCIBLE: Steps
local_run_lags.get_output()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-cb2283b9237f> in <module>()
----> 1 local_run_lags.get_output()

AttributeError: 'Run' object has no attribute 'get_output'
.
### EXPECTATION: Clear description 

Appreciate your help looking into this.

**Comment by gaugup** [comment]
Thanks for reporting the issue. How are you running the notebook? From the notebook it doesn't look like this is possible.

**Comment by jialiu103** [comment]
Can you make sure you've installed conda env using setup scripts provided in the notebook folder?

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was posted some time ago so will close it.  We hope the community response helped. Should you still need assistance with this or another issue, please re-post and we will respond promptly.

**Comment by mrobertsonavidxchange** [comment]
I am having this same problem, and I see no solution was posted
