### ISSUE TITLE
validate() not documented

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#595]
`help(pipeline.validate())` shows that it's just a basic `class list(object)`. There should be some explanation of what checks are run.  **_Unconnected inputs_** are mentioned, is that the only check that it does?  My pipeline can still crash and yet this returns a basic `[]`. Is it possible that this method just inherits the basic list object as a placeholder, but the actual tests were never built?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d00f11-af17-c632-31bc-51ceb9021dda
* Version Independent ID: 0c6cf0f2-4854-ef65-290e-c98d8d03ad27
* Content: [azureml.pipeline.core.Pipeline class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline%28class%29?view=azure-ml-py#validate--)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.Pipeline(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.Pipeline(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
@trevor-MSFT @lobrien the `validate()` function def helps us fail faster. It would certainly help to have this documented (not to mentioned fleshed out with more potential validation scenarios)

**Comment by j-martens** [comment]
@vmagelo

**Comment by vmagelo** [comment]
We added to the validate() method docs. Examples of validation errors include:

- missing or unexpected pipeline datasources or step types
- missing parameters or output definitions for a pipeline datasource or step
- unconnected inputs
- pipeline steps that form a loop or cycle

If validation passes (returns an empty list) and your pipeline doesn't work, then see the [Debug and troubleshoot machine learning pipelines](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-debug-pipelines).

**Comment by j-martens** [comment]
We will now proceed to close this issue.
