### ISSUE TITLE
improve syntax example for attach_configuration

### ISSUE THREAD

**Issue by gjswalling** [Azure/MachineLearningNotebooks#597]
Please improve syntax example for attach_configuration from:
attach_configuration(username, address, ssh_port='22', password='', private_key_file='', private_key_passphrase='')

this would be better:
attach_configuration(address='<clustername>-ssh.azureinsight.net', ssh_port=22, username='', password='', private_key_file='', private_key_passphrase='')

especially since ssh_port is an int, not a string.
I borrowed from the example here: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-set-up-training-targets#hdinsight

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4daaafc9-a27d-cba0-64a1-70863e261603
* Version Independent ID: 20df6ca4-5301-d754-4222-83e540fd5c7a
* Content: [azureml.core.compute.hdinsight.HDInsightCompute class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.hdinsight.hdinsightcompute?view=azure-ml-py#attach-configuration-username--address--ssh-port--22---password-----private-key-file-----private-key-passphrase----)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.compute.hdinsight.HDInsightCompute.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.compute.hdinsight.HDInsightCompute.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by gjswalling** [comment]
correction: 
attach_configuration(address='-ssh.azurehdinsight.net', ssh_port=22, username='', password='', private_key_file='', private_key_passphrase='')

**Comment by j-martens** [comment]
improve syntax example for attach_configuration. User is asking for change in method parameters.

#assign:@rastala

**Comment by nishankgu** [comment]
#assign @sauryadas

**Comment by nishankgu** [comment]
I see this alread fixed here @j-martens : https://docs.microsoft.com/en-us/azure/machine-learning/how-to-set-up-training-targets#hdinsight

What am I missing?

**Comment by j-martens** [comment]
Great! This has been fixed. #please-close
