### ISSUE TITLE
RunConfiguration got an unexpected keyword argument 'node_count'

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#601]
Using SDK version `1.0.62`. Perhaps the majority of parameters here are deprecated now in favor of setting them after object initialization? If so, the docs should be updates to reflect that.
## works
```python
spark_run_config = RunConfiguration(
    framework="pyspark"
)
spark_run_config.node_count = 2
```
## doesn't work
```python
spark_run_config = RunConfiguration(
    framework="pyspark",
    node_count=2
)
```
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in 
     18 spark_run_config = RunConfiguration(
     19     framework="pyspark",
---> 20     node_count=2,
     21     # environment=spark_env,
     22 )

TypeError: __init__() got an unexpected keyword argument 'node_count'
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1053292b-f07e-a923-c880-11438dbe892f
* Version Independent ID: 886c442e-b1ee-af68-9810-7bca8571638a
* Content: [azureml.core.RunConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.RunConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.RunConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
The docs for RunConfiguration changed recently to reflect what you said above. There were many "parameters" that are actually class attributes that can be set after init.  In the HTML docs, these class attributes are summarized int the section called "Variables" (not the greatest naming unfortunately), which includes attributes like node_count.  

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfiguration?view=azure-ml-py#variables
