### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas.core.internals.managers'; 'pandas.core.internals' is not a package

### ISSUE THREAD

**Issue by DipeshJParmar** [Azure/MachineLearningNotebooks#602]
Hi,
I seem to having an issue using Azure AutoML to create a classification model. My apologies if this is not the correct area to post this issue.

**Issue**
I am using the Azure ML Python SDK (version 1.0.65) to automatically train a classification model.  I can submit my experiment to the machine learning service with no issues and the experiment runs with no issues but when I try to get the best fitted model running the following code i get "ModuleNotFoundError: No module named 'pandas.core.internals.managers'; 'pandas.core.internals' is not a package"

![VSCodeError](https://user-images.githubusercontent.com/43376366/66213984-b82f7680-e6b8-11e9-9010-24aef82c1e2f.png)

best_run, fitted_model = remote_run.get_output()

**Configuration step up**

Windows 10 (10.0.17763)
Anaconda 3
Visual Studio Code – 1.38.1
Python 3.6.5
azureml-sdk 1.0.65
Pandas - 0.23.4

The environment has been configured as per the advice on the following URL
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment#local

I have tried this same process with different versions of python (3.7.3, 3.7.2) and different versions of the pandas library (0.22,0 and 0.23.4) and a previous version of the azureml-sdk (1.0.62) but still getting the same error.

**Steps to reproduce**
Followed the notebook below but used my own data. 

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb

I have tried the same process within the Notebooks VM and get the same error.

![image](https://user-images.githubusercontent.com/43376366/66214858-64259180-e6ba-11e9-8006-4d309d282fde.png)

Any help on this issue is most appreciated.

**Comment by imatiach-msft** [comment]
@DipeshJParmar does upgrading pandas fix this issue for you?

pip install --upgrade pandas

relevant stackoverflow:

https://stackoverflow.com/questions/54665527/importerror-no-module-named-pandas-core-internals-managers-pandas-core-inte

**Comment by wchill** [comment]
@DipeshJParmar I have not been able to reproduce this issue. Would you be willing to share the output of `pip freeze` so I have an idea of what other packages you have installed locally? It's possible that there is some other package that is overwriting the needed version of pandas when the remote compute is set up.
