### ISSUE TITLE
This compute target type doesn't support non-Docker runs; overriding run configuration enable Docker.

### ISSUE THREAD

**Issue by dtoupo** [Azure/MachineLearningNotebooks#603]
I am getting this error when running the img-classification-part1-training.ipynb notebook.
How do I select the right compute target to avoid this error?

`from azureml.train.sklearn import SKLearn

script_params = {
    # to mount files referenced by mnist dataset
    '--data-folder': dataset.as_named_input('mnist').as_mount(),
    '--regularization': 0.5
}

est = SKLearn(source_directory=script_folder,
              script_params=script_params,
              compute_target=compute_target,
              environment_definition=env,
              entry_script='train.py')`

WARNING - If environment_definition or conda_dependencies_file_path is specified, Azure ML will not install any framework related packages on behalf of the user.
WARNING - This compute target type doesn't support non-Docker runs; overriding run configuration enable Docker.
WARNING - You have specified to install packages in your run. Note that you have overridden Azure ML's installation of the following packages: ['scikit-learn']. We cannot guarantee image build will succeed.

**Comment by vizhur** [comment]
@dtoupo these are warning and should not break the execution. 
**Create or Attach existing compute resource** section in the notebook explains a bit compute target question
