### ISSUE TITLE
Error: Workspace not found

### ISSUE THREAD

**Issue by jageshmaharjan** [Azure/MachineLearningNotebooks#604]
I am trying to get the Workspace Object from the kubeflow and as well as from my local machine.

However, with the provided credentials, I am receiving this error message.
```
{ProjectSystemException}ProjectSystemException:
 	Message: Workspace not found.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Workspace not found."
    }
}
```
The way I am calling the object:

```
Workspace(subscription_id='xxxx.xxxx.xxxxxx', resource_group='myRG', workspace_name='myworkspace', auth=ServicePrincipalAuthentication(tenant_id='xxx-xxxxx-xxxx', service_principal_id='xxxxx-xxxxxxxx-xxxxx',service_principal_password='xxxx?:dsdxxxx'))
```
I got tenant_id and service_principal_id from `App Registration` and i have added the role assignment in `IAM` of this particular resource group

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.

**Comment by amiradinari** [comment]
hello
 I am facing the same issue

**Comment by rastala** [comment]
Please double-check from Azure Portal that the workspace exists in the same tenant and subscription that you use in Workspace(...) command.

**Comment by irishun** [comment]
Hi I am facing the same issue.

Context: in the azure machine learning compute instance Jupyter, I am running the command 
`az ml workspace sync-keys -g <my RG> -w <my workspace name>`

I have double checked the RG name and workspace name, they are exactly the same as the printed names from 
`ws = Workspace.from_config()
print('Workspace name: ' + ws.name, 
      'Resource group: ' + ws.resource_group, sep='\n')`

But I still got the error:

> ProjectSystemException:
        Message: Workspace not found.
        InnerException None
        ErrorResponse
{
    "error": {
        "message": "Workspace not found."
    }
}

**Comment by XingxinHE** [comment]
Same thing here. Is there any solution addressed this yet?
