### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kumpera** [Azure/MachineLearningNotebooks#605]
metirics_data -&gt; metrics_data 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c9dcc31-649d-8dfb-a038-1c797133523e
* Version Independent ID: bb21b918-f0ff-ad2d-80a2-f1aa9e0174aa
* Content: [azureml.pipeline.core.TrainingOutput class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.trainingoutput?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.TrainingOutput.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.TrainingOutput.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks. Addressing this and changes should go live in a 1-2 weeks.
