### ISSUE TITLE
base_dockerfile parameters is unclear

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#607]
I realized that this param is in fact the string that is your docker file :
myenv.docker.base_dockerfile = 'FROM ubuntu:latest\nRUN ...\n...'
That works, but obviously not 
myenv.docker.base_dockerfile = './Dockerfile'
Which I think is more helpful/intuitive. But please make it clearer in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c28b4b3d-905f-cf45-2539-1dde68267062
* Version Independent ID: 05f90513-4605-c70b-27aa-809733105f4d
* Content: [azureml.core.environment.DockerSection class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.dockersection?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.environment.DockerSection.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.environment.DockerSection.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by omartin2010** [comment]
and also, since it requires ubuntu and conda to be installed, why not give an example that has ubuntu and conda, like our mcr.microsoft.com/azureml/base:latest image for example. That would make things simpler.

**Comment by vizhur** [comment]
Sorry about confusion. This feature is planned for upcoming releases, documentation will be updated accordingly
