### ISSUE TITLE
usage of `sample_weight` appears to have changed from documentation

### ISSUE THREAD

**Issue by Fraser-Paine** [Azure/MachineLearningNotebooks#608]
I'm training on a highly imbalanced dataset and thought I'd try sample weighting in AutoML using the method described [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/sample-weight/auto-ml-sample-weight.ipynb)

Unfortunately this results in the following error even when there are the same number of sample weights as instances.
`automl.client.core.common.exceptions.DataException: sample_weight length should match length of X`

I tracked this issue down to the `rule_based_validation()` function in `automl_base_settings.py`
This function is skipped if a `valid_X` and `valid_y` are defined, otherwise it creates them from the data provided, but it does not apply the same split to the `sample_weight` array.

The fix of adding my own `valid_X` and `valid_y` data and a `sample_weight_valid` array is easy enough, however this was not at all obvious from the original error message.

A pretty simple fix to this would be a modification of the error message. Ideally there would be a split on `sample_weight` to generate a `sample_weight_valid` array when `rule_based_validation()` is called to make this work as described in the example notebook linked above.

Hope this is helpful.
(I can send the whole error traceback if needed but it contains some client info so I would have to clean it first and didn't consider it critical.)

**Comment by rtanase** [comment]
Thanks for the pretty detailed report! An engineer is going to have a look at this issue.

**Comment by rtanase** [comment]
The issue was fixed, but it will probably be available on PyPi in about 2 weeks.

**Comment by v-strudm-msft** [comment]
Thank   you for your post. It looks as though this issue was resolved so we closed   this thread. Should you have additional questions, please continue to post   here and and we will gladly continue the discussion.
