### ISSUE TITLE
When will be the 2.0 version Tensorflow available?

### ISSUE THREAD

**Issue by JoelCantero** [Azure/MachineLearningNotebooks#609]
Tensorflow 1.13 is deprecated and our company is working with Tensorflow 2.0. When will you update it?

Thanks
Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 467fb465-3db5-bdec-c15a-4b42ba598324
* Version Independent ID: 08f6b327-dc9e-911d-adc8-535499c58ba3
* Content: [azureml.train.dnn.TensorFlow class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.tensorflow?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.TensorFlow.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.TensorFlow.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by maxluk** [comment]
Pre-built framework_version 2.0 for TensorFlow will be available next week 9/14. You will see update in release notes: https://docs.microsoft.com/en-us/azure/machine-learning/service/azure-machine-learning-release-notes.

You can always install any framework version using custom package specification in Estimator object, by using pip_packages or conda_packages parameter.
