### ISSUE TITLE
Difficulty executing automl_setup.cmd

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#61]
I'm trying to use this but am having difficulty getting off the ground. I made a new folder, copied the "automl_setup.cmd" file, located the folder in Command Prompt, and ran "automl_setup," as instructed. I got the error `The syntax of the command is incorect.` I tried opening the file directly, which opens & closes a window very quickly. I then tried to simply copy & run the 00.configuration.ipynb file and open it with Jupyter but it gave me a different error:
`C:\[path]\00.configuration.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")`

Any help would be greatly appreciated. I tried following the instructions in the readme as closely as I could but can't see what I'm doing wrong.

**Comment by ktebbe** [comment]
I overlooked the instruction that said to download the entire folder as a zip. I would be helpful if that was made more clear, as someone who is not terribly familiar with github.

**Comment by ktebbe** [comment]
At the end of the `automl_setup` execution, I got this error. 

![automl_setup error](https://user-images.githubusercontent.com/12629836/47574046-bab41880-d90c-11e8-9130-db053ae045d3.PNG)

**Comment by bartdesmet** [comment]
Thanks for trying AutoML! I've tried to repro locally but have been unable to get the same error. Let's check a few things about the environment to help narrow down the issue:

1. Was Conda for Python 3.7 or above installed property? [See here](https://github.com/Azure/MachineLearningNotebooks/blob/master/automl/README.md#1-install-mini-conda-from-here-choose-python-37-or-higher)
2. Can you run the `automl_setup` script from the Anaconda prompt? On my machine, it shows up in the Start menu under `Anaconda3 (64-bit)` as `Anaconda prompt`.
3. To confirm the environment is set up correctly, can you try running the commands below and check whether the version numbers match?

```
(base) C:\Projects\MLNB\automl>conda -V
conda 4.5.11

(base) C:\Projects\MLNB\automl>python -V
Python 3.7.0

(base) C:\Projects\MLNB\automl>pip -V
pip 10.0.1 from C:\Users\bartde\AppData\Local\Continuum\miniconda3\lib\site-packages\pip (python 3.7)
```

**Comment by ktebbe** [comment]
Thanks for your help!

1. Yes, it installed correctly. If there's an easy way to verify that, let me know.
2. I did not realize Anaconda Prompt was different than Command Prompt! Thanks for pointing that out. It set up successfully. 

I then was able to open and run through the configuration notebook file. I'll open another issue if I run into any other problems. Thank you!
