### ISSUE TITLE
Conda and pip dependency files

### ISSUE THREAD

**Issue by vapaunic** [Azure/MachineLearningNotebooks#610]
Parameters contain two copies of conda and pip dependency file paths. Is this a mistake?
conda_dependencies_file_path and conda_dependencies_file
pip_requirements_file_path and pip_requirements_file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f52dfdc-ba99-18da-ada5-8e58ed22f243
* Version Independent ID: 3c31cb06-b8af-8426-371e-e7e2610019a0
* Content: [azureml.train.dnn.PyTorch class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.pytorch?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
No. Parameters ending with "_path" are deprecated and you should use corresponding parameters without that ending. We are changing the documentation to reflect this. Thanks for letting us know. The changes will go live in 2-3 weeks.
