### ISSUE TITLE
BUG: ComputeTarget.create() returns 200 status error: Operation results in exceeding quota limits of Microsoft.Batchlusters

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#613]
## Error Message:
```JSON
{
    "code": "OK",
    "statusCode": 200,
    "message": "failed with status \"Failed\". Additional Info:\"Operation results in exceeding quota limits of Microsoft.Batchlusters\""
}
```
## Details
1) What this really means is that we've hit the limit of computes within the workspace.
1) This should be a 400 response
2) `Microsoft.Batchlusters` is misspelled.
3) `Azure Batch Clusters quota` is dead end of a Google search. (I think they mean Batch Pools?)
4) What I could find about [batch account quota management](https://docs.microsoft.com/en-us/azure/batch/batch-quota-limit) is unhelpful as ML Service's Batch account is not made available to the user.
## Remediation
Better error handling perhaps also add in a case for #581?

## example code

```python
def get_or_create_compute(workspace, compute_target_name, **kwargs):
    compute_target = ComputeTarget.create(
        workspace,
        compute_target_name,
        AmlCompute.provisioning_configuration(**kwargs))

    compute_target.wait_for_completion(show_output=True)
    return compute_target

compute_target = f.get_or_create_compute(workspace=ws,
                                         compute_target_name='test compute',
                                         vm_size='STANDARD_D12_V2',
                                         max_nodes=4
                                         )
```

## full "error" message
```
Provisioning errors: [{'code': 'OK', 'message': 'OK', 'error': {'code': 'OK', 'statusCode': 200, 'message': 
failed with status 'Failed'. Additional Info:'Operation results in exceeding quota limits of Microsoft.Batchlusters''\n"}]}}]
```
@alexsuttonms @j-martens @alieus

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
