### ISSUE TITLE
AttributeError: 'ServicePrincipalCredentials' object has no attribute '_get_service_client'

### ISSUE THREAD

**Issue by bbennett36** [Azure/MachineLearningNotebooks#616]
I've been trying to follow this tutorial to setup authorization for a app that I'm trying to create - https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb
  
My code -  
  
```
from azureml.core import Datastore
from azureml.core import Workspace
import azureml.data
from azureml.data.azure_storage_datastore import AzureFileDatastore, AzureBlobDatastore
from azure.common.credentials import ServicePrincipalCredentials

credentials = ServicePrincipalCredentials(
    client_id = CLIENT,
    secret = KEY,
    tenant = TENANT_ID
)


ws = Workspace(subscription_id=SUB_ID,  resource_group=RG workspace_name=WORKSPACE,  auth=credentials)
```

The code above is returning this error - 

```
try:
--> 337         workspaces = auth._get_service_client(AzureMachineLearningWorkspaces, subscription_id).workspaces
    338         return WorkspacesOperations.get(
    339             workspaces,

AttributeError: 'ServicePrincipalCredentials' object has no attribute '_get_service_client'
```    
  
I'm not sure how the ServicePrincipalCredentials class doesn't contain the method that the Workspace class needs for authentication.   
  
Any ideas on what the issue is here?

Thanks!

**Comment by jadhosn** [comment]
Try using the azure ml service principal authentication instead (keep in mind that you will need a service principal id and password) 

```python
from azureml.core import Workspace, Experiment, Run
from azureml.core.authentication import ServicePrincipalAuthentication

# Define an authentication string needed to define a workspace
svc_pr = ServicePrincipalAuthentication(
    tenant_id = tenant_id,
    service_principal_id = service_principal_id,
    service_principal_password = service_principal_password)

# Setup workspace
ws = Workspace(
    subscription_id = subscription_id,
    resource_group = resource_group,
    workspace_name = workspace_name,
    auth = svc_pr)
```

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was posted some time ago so will close it.  We hope the community response helped. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
