### ISSUE TITLE
Run failed: Failed to flush task queue within 300 seconds

### ISSUE THREAD

**Issue by gauss345** [Azure/MachineLearningNotebooks#623]
Hi, when submitting a run on a local target, after completing the run, and during the 'finalization' phase I get this error repeatedly, 

https://gist.github.com/gauss345/e9a34a1355d2b01b47ef16f73650ae6d

I've tested running the same training script in cloud, and it takes about 4 minutes, to complete.

please help #

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
