### ISSUE TITLE
deploy to AKS with tensorflow 2.0 failed

### ISSUE THREAD

**Issue by lisongshan** [Azure/MachineLearningNotebooks#624]
Any idea to help resolve this issue is appreciated.

the init() method in score file only have two lines:

import tensorflow as tf

print(tf.__version__)

The tensorflow in docker image is tensorflow-gpu=2.0,

I have tried to update azure machine learning service components on my aks by detach/attach. no impact at all. Run the pod interactive, the score file's init() is executed without any problem.  so the problem is due to score's init() is called through driver_module.init().

here is the log from AKS pod:

  File "/var/azureml-server/aml_blueprint.py", line 162, in register

    main.init()

  File "/var/azureml-app/main.py", line 88, in init

    driver_module.init()

  File "intent_score.py", line 3, in init

    import tensorflow as tf

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>

    from tensorflow_core import *

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 45, in <module>

    from . _api.v2 import compat

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/__init__.py", line 23, in <module>

    from . import v1

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py", line 49, in <module>

    from . import lite

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/v1/lite/__init__.py", line 11, in <module>

    from . import experimental

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/v1/lite/experimental/__init__.py", line 10, in <module>

    from . import nn

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/v1/lite/experimental/nn/__init__.py", line 10, in <module>

    from tensorflow.lite.python.lite import TFLiteLSTMCell

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 31, in <module>

    from tensorflow.lite.experimental.microfrontend.python.ops import audio_microfrontend_op  # pylint: disable=unused-import

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/lite/experimental/microfrontend/python/ops/audio_microfrontend_op.py", line 30, in <module>

    resource_loader.get_path_to_datafile("_audio_microfrontend_op.so"))

  File "/opt/miniconda/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 78, in load_op_library

    exec(wrappers, module.__dict__)

  File "<string>", line 32

    def audio_microfrontend(audio, sample_rate=16000, window_size=25, window_step=10, num_channels=32, upper_band_limit=, lower_band_limit=, smoothing_bits=10, even_smoothing=, odd_smoothing=, min_signal_remaining=, enable_pcan=False, pcan_strength=, pcan_offset=, gain_bits=21, enable_log=True, scale_shift=6, left_context=0, right_context=0, frame_stride=1, zero_padding=False, out_scale=1, out_type=_dtypes.uint16, name=None):

                                                                                                                        ^

SyntaxError: invalid syntax

**Comment by ram-msft** [comment]
@lisongshan Can you please share the notebook/code that you are trying.

**Comment by lisongshan** [comment]
The deployment.py ,

from azureml.core.webservice import Webservice
from azureml.core.image import ContainerImage
dependencies = []
image_config = ContainerImage.image_configuration(
    dependencies=dependencies,
    execution_script="score.py",
    runtime="python",
    conda_file="conda_env_gpu.yml",
    enable_gpu=True,#todo
    cuda_version="9.0"
)

# ws: workspace to be provided
image = ContainerImage.create(name = "asksamgpuclassifier-tf2.0-sm",
                              # this is the model object
                              models = [],
                              image_config = image_config,
                              workspace = ws)

image.wait_for_creation(show_output = True)

from azureml.core.webservice import AksWebservice
deployment_config = AksWebservice.deploy_configuration(autoscale_enabled=False,
                                                    num_replicas=1,
                                                    cpu_cores=1,
                                                    gpu_cores=1,
                                                    memory_gb=4)

aks_name = "myakscluster"
aks_target = ComputeTarget(workspace=ws, name=aks_name)

aks_service_name = 'aksclassifierservicegpu-tf2-1'

try:
    aks_service = Webservice.deploy_from_image(workspace = ws,
                                                name = aks_service_name,
                                                image = image,
                                                deployment_config = deployment_config,
                                                deployment_target = aks_target)

    aks_service.wait_for_deployment(show_output=True)
    print(aks_service.get_logs())
except Exception:
    print(aks_service.get_logs())
    print(aks_service.state)


score.py:
def init():
   # import tensorflow as tf
   # print(tf.__version__)
   pass

def run(rawdata):
    return "run(rawdata)"


conda_env_gpu.yml:
name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.9
- pip:
    - azureml-defaults
    - tensorflow-gpu
    - tensorflow_hub
    - azureml-monitoring
    - numpy
    - azureml-contrib-services

azureml sdk version: 1.0.69

let me know if you need more information. thanks a lot.

**Comment by lisongshan** [comment]
@ram-msft please let me know if you need more details. Thanks a lot.

**Comment by ram-msft** [comment]
@lisongshan Thanks for the details. Currently AML doesn’t support Tensorflow 2.0 just yet, azureml-sdk ==1.0.69 requires tensorflow==1.12.0. doesn't support tensorflow==2.0.0. Feel free to raise a user voice request [here](https://feedback.azure.com/forums/257792-machine-learning) so the community can vote and provide their feedback, the product team then checks this feedback and implements the feature in future releases.

**Comment by j-martens** [comment]
@lisongshan - I think TF 2.0 is supported in 1.0.69. Product team to confirm.

**Comment by lisongshan** [comment]
@j-martens - I was able to train with TF 2.0 through azureml sdk. But deploying the model is failed for TF2.0

**Comment by j-martens** [comment]
@lisongshan - It should work. The error say it's a syntax error, perhaps from your script.
 

SyntaxError: invalid syntax
 


def audio_microfrontend(audio, sample_rate=16000, window_size=25, window_step=10, num_channels=32, upper_band_limit=, lower_band_limit=, smoothing_bits=10, **even_smoothing=, odd_smoothing=, min_signal_remaining=**, enable_pcan=False, pcan_strength=, pcan_offset=, gain_bits=21, enable_log=True, scale_shift=6, left_context=0, right_context=0, frame_stride=1, zero_padding=False, out_scale=1, out_type=_dtypes.uint16, name=None):

**Comment by mpprasanna** [comment]
I am getting exactly same error. Any solution please let me know

**Comment by lisongshan** [comment]
@mpprasanna  I am using docker container or AKS directly.  I used ContainerImage.create to create a base image to have tf2.0, gpu support etc, then build a custom image for my serving code.

**Comment by gabe-l-hart** [comment]
In case anyone is still chasing this issue, I was seeing the exact same error in the signature of `def audio_microfrontend`, but in an entirely different environment. My setup was a custom python-extension module build in `c++` while importing `tensorflow 1.15.0`. Both my extension module and `tf` imported fine on their own, but when importing `tf` *after* my module, I saw this error. If I imported `tf` *before* my module, the import went cleanly, but my module segfaulted when run.

The solution ended up being pretty simple: I was building my module using `gcc 8.3.1` with the `-static-libstdc++` flag. It seems that the statically linked `libstdc++` and the dynamic linking in `_audio_microfrontend_op.so` were conflicting. Rebuilding my module without `-static-libstdc++` solved the problem!

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was posted some time ago so will close it.  We hope the community response helped. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
