### ISSUE TITLE
Model packaging

### ISSUE THREAD

**Issue by olgapoppe** [Azure/MachineLearningNotebooks#625]
Hi,

I have a Webservice up and running. However, when i package the model, pull the image and run it locally, the URI does not work. There is no error message. The init() method in my entry script is empty. The run() method prints "hello". Dependencies are minimal (azureml-defaults).

I also tried pulling the image of the working Webservice. But it does not run locally. I am able to run other docker images however. So, there is no issue with my local setup.

Any ideas? Thanks a lot!
Olga

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
