### ISSUE TITLE
Dataset.register() params out of date

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#630]
These params are old. It should be `create_new_version` instead of `exist_ok` or `update_if_exist`.
```
exist_ok
bool or optional
If True, the method returns the Dataset if it already exists in the given workspace, else error.

update_if_exist
bool or optional
If exist_ok is True and update_if_exist is True, this method will update the definition and return the updated Dataset.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4a4a23-d2b0-1123-bba5-7556ed560add
* Version Independent ID: 6e350d69-726d-576f-404d-1f2ebe0b4528
* Content: [azureml.core.dataset.Dataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py#register-workspace--name--description-none--tags-none--visible-true--exist-ok-false--update-if-exist-false-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by nibaccam** [comment]
@MayMSFT can you work with Eng for this one please?

**Comment by MayMSFT** [comment]
yep. the method will have deprecation message with the next release

**Comment by MayMSFT** [comment]
Hi Anders. Here is the base class for dataset: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py
we have added the deprecation message for the old dataset class: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py
Will add redirection link on the old dataset class to guide users to abstract dataset class

**Comment by swanderz** [comment]
Great thanks!
