### ISSUE TITLE
How to add additional .py files as dependencies when deploying a model?

### ISSUE THREAD

**Issue by nansravn** [Azure/MachineLearningNotebooks#631]
I've seen that the [ContainerImageConfig class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.container.containerimageconfig?view=azure-ml-py) has a Parameter named **dependencies**.

**``
dependencies
``** *<xref:azureml.core.image.container.list[str]>*
List of paths to additional files/folders that the image needs to run

If my **execution_script** (my *score.py* code) has a dependency of several *utils.py* codes, can I use this **depedencies** parameter to files or a folder when I'm creating the Docker Image? Can you share any sample code with **dependencies** being used?

**Comment by v-strudm-msft** [comment]
Thank you for your post. It looks as though this issue was resolved so we closed this thread. Should you have additional questions, please continue to post here and and we will gladly continue the discussion.
