### ISSUE TITLE
input params seems to be not properly defined

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#632]
It looks like the from_files() accepts _tuples_ (datastore, path) and not necessarily simply datastores. Can we make that clearer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037b6bff-9f7e-e872-c653-ddd8b15ee7ff
* Version Independent ID: 4c79302f-9617-d4c6-7128-f7ee7cb74d22
* Content: [azureml.data.dataset_factory.FileDatasetFactory class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_factory.filedatasetfactory?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.data.dataset_factory.FileDatasetFactory.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.data.dataset_factory.FileDatasetFactory.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
@omartin2010 I agree @MayMSFT we talked about this when you came to visit. I agree that yes, a list of tuples is convenient but can't you also pass a list of `DataReference`'s?

**Comment by MayMSFT** [comment]
yes. you can. we will add documentation into our API reference

**Comment by vmagelo** [comment]
This has been addressed. Appears in builds.
