### ISSUE TITLE
Workspace.from_config() - cannot complete authentication

### ISSUE THREAD

**Issue by tylercmsft** [Azure/MachineLearningNotebooks#633]
I am trying to run Workspace.from_config() to load my workspace config file (working in a custom local Python environment - running in Anaconda 3.7).  When I run the cell, a new browser window opens up - I am able to authenticate, but (back in the notebook browser), the cell itself never completes.  Any ideas of how to work around?  The message says something about using az login - but this

**Comment by jadhosn** [comment]
If the cell doesn't provide you with a login URL and a login code (usually [microsoft.com/devicelogin](microsoft.com/devicelogin) and some alphanumeric code that you would need to paste), then you can use your azure terminal to login using azure cli: 

1. Open a new terminal in your notebook vm or an Azure Command Shell from your azure portal
2. Install azure cli: `az extension add -n azure-cli-ml`
3. Run `az login` in your terminal, then when prompted go to [microsoft.com/devicelogin](microsoft.com/devicelogin) and paste the code shown for authentication

**Comment by vizhur** [comment]
@tylercmsft  please check this sample for auth https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb

**Comment by tylercmsft** [comment]
Hello, this error is back - but slightly different.  Whether in a Jupyter notebook, or in the Azure Command Shell, I am able to paste in a code (at the devicelogin page) - but then (on the next window) I am prompted to Sign In via my AAD email address ("You will be signed into Microsoft Azure Cross-platform....).  I click next, and then get a "Can't connect securely to this page  This might be because the site uses outdated or unsafe TLS security settings...." error.

**Comment by v-strudm-msft** [comment]
Thank you for posting this issue.  We see it was not addressed by us and was posted some time ago. Our apologies. We hope the community response helped. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.
