### ISSUE TITLE
Saving run.logs() in memory in a _OfflineRun

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#634]
While trying to run step scripts **locally** `run = Run.get_context(allow_offline=True)`, we can invoke some methods to log run metrics (e.g. log, log_table, log_raw etc.), we use these to compare models from child runs after the fact (in a future step). However, when executing locally, everything just gets pushed to standard out. In _OfflineRun executions, could the logs be added to the object and accessed via the same methods (`get_details` & `get_metrics`) as the class does not have definitions yet for those method signatures?

@sanpil @swanderz @j-martens

**Comment by rastala** [comment]
The offline mode is intended for cases where you want to work without internet connectivity, but it has the disadvantage that the runs are not tracked by run history service.

Under normal circumstances you should be able to run local runs without allow_offline=True. That way your metrics will appear in run history logs.

**Comment by jadhosn** [comment]
@rastala the reason I switched to using `allow_offline=True` is to have my step fail faster **locally**, before submitting a run to the portal. 

So in the scenario where I have a step A, that generates some output metric that is usually logged to the portal, and another step B (the step I wish to test locally), I won't be able to test step B **locally** unless I provide a valid step run id for step A (that contains the outputs and metrics that step B is looking for). 

So there's no way to run steps A & B both locally if step A is logging some metrics.

**Comment by rastala** [comment]
You should be able to use following approach to run locally with logging enabled:

```
runA = experiment.start_logging()
# put machine learning code here
runA.complete()
```

Then, in the second run you can consume metrics using ```runA.get_metrics(...)```

**Comment by v-strudm-msft** [comment]
Thank you for your post. It looks as though this issue was resolved so we closed this thread. Should you have additional questions, please continue to post here and and we will gladly continue the discussion.
