### ISSUE TITLE
`collect_model_data` is missing from the parameters defintion

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#635]
`collect_model_data` is only included in the class definition

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eb312fb-5317-8d04-0a2b-806d5bb34b42
* Version Independent ID: b5d87b71-994b-6d88-c161-f4852a3ce05a
* Content: [azureml.core.webservice.aci.AciServiceDeploymentConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aci.aciservicedeploymentconfiguration?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciServiceDeploymentConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciServiceDeploymentConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
We updated the docs to address the issue. Changes will appear in the next SDK release in approx two weeks.
