### ISSUE TITLE
Model retraining or scheduling model training

### ISSUE THREAD

**Issue by shmisra** [Azure/MachineLearningNotebooks#636]
If a model is created using AutoML or visual Interface, is there a way to trigger model retraining, or scheduling a model retrain on specific intervals?

**Comment by purnesh42H** [comment]
you can probably create a published pipeline to train with AutoMLStep and schedule it. Here is a sample notebook https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-setup-schedule-for-a-published-pipeline.ipynb

**Comment by luzhang06** [comment]
Visual interface (now upgraded to AML designer) supports publishing a pipeline as well. So you can trigger retraining/scheduling on the published pipeline (pipeline endpoint) now.
