### ISSUE TITLE
azureml.contrib.interpret - ModuleNotFoundError - build 1.0.72

### ISSUE THREAD

**Issue by jimwill3** [Azure/MachineLearningNotebooks#639]
I've installed and updated the sdk yet when attempting to import the module for the ExplainationDashboard i keep getting the error that the interpret module does not exist.
i am running build 1.0.72 and following the sample in 'how to use"/explain-model/tabular-data/explain-regression-local.ipynb 
the failing line in the sample notebook is:
**from azureml.contrib.interpret.visualize import ExplanationDashboard**
**"ModuleNotFoundError: No module named 'azureml.contrib.interpret' "**
this is the update command i ran:
pip install --upgrade azureml-sdk[explain,automl,contrib] 
(the install ran fine - no errors)
jim

**Comment by vizhur** [comment]
azureml-contrib-interpret is not a part of azureml-sdk contrib extras. Please install it separately
