### ISSUE TITLE
get_status() Values

### ISSUE THREAD

**Issue by cwarne** [Azure/MachineLearningNotebooks#645]
Can you please provide possible values returned from the get_status() function? Or provide an enum?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2068736-5778-55dc-0552-e2901af8196f
* Version Independent ID: d6daede6-01a2-c0f0-c2a5-a6c438c3addc
* Content: [azureml.core.ComputeTarget class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.computetarget?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.ComputeTarget.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.ComputeTarget.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by purnesh42H** [comment]
Here, https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#get-status--

**Comment by cwarne** [comment]
Hi, these look like a pipeline run status rather than the status of the compute. Is there values for the ComputeTarget.get_status() function?

**Comment by vmagelo** [comment]
We updated the docs to address the issue. Changes will appear in the next SDK release in approx two weeks. Values returned are listed in the Azure REST API Reference for [ProvisioningState](https://docs.microsoft.com/en-us/rest/api/azureml/workspacesandcomputes/machinelearningcompute/get#provisioningstate).
