### ISSUE TITLE
Too many requests for service XXXX (overloaded) when a model is deployed in AKS and ONLY one request was sent for testing from end

### ISSUE THREAD

**Issue by chengyu-liu-cs** [Azure/MachineLearningNotebooks#647]
As stated in title, I quite often get "**_Too many requests for service XXXX (overloaded)_**" when I re-ran the same pipeline/script. In this pipeline, there is ONLY ONE request sent to endpoint. The script contains following steps: model training, testing, registering, deploying (AKS) and monitoring (Application insights). If I use ACI as a deployment target, there was such an error (At least I do not recall there was once). So I concluded that it should be related model deployment in AKS.

In this AKS cluster there are a couple of the same model with different names deployed (see pods below).  
![image](https://user-images.githubusercontent.com/11485399/68277129-36e05080-0077-11ea-805e-fa4684a0d8e7.png)

Each model has its own endpoints generated from webservices for example (IP is modified)

- http://11.111.1.111:80/api/v1/service/amlcompute-docker-aks/score
- http://11.111.1.111:80/api/v1/service/local-docker-aks/score
- http://11.111.1.111:80/api/v1/service/local-nodocker-aks/score

Here is relevant log

Creating image
Running...............................................
Succeeded
Image creation operation finished for image amlcompute-docker-aksCreating a webservice    
Service is already deployed in AKS. Now updating
Service deployed in AKS is updated
Service stage is Healthy
http:///11.111.1.111:80/api/v1/service/amlcompute-docker-aks/score
consuming webservice url: http://11.111.1.111:80/api/v1/service/amlcompute-docker-aks/score
Too many requests for service amlcompute-docker-aks (overloaded)

Used azureml sdk version: 1.0.62

**Comment by Joon-L** [comment]
Hi @chengyu-liu-cs, thank you for raising this issue on Github. The 503 responses are normally seen when backends are not configured correctly to serve the requests. This can either mean that your backend may not have enough resource allocation to serve the request, or is not in a good state to serve the request (despite being created successfully).
Could you please double-check if your service has the right resource allocation and check our [troubleshooting guides](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-troubleshoot-deployment#http-status-code-503) to see if any of these apply?

If you need further assistance, please feel free to [open a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to us as well.
