### ISSUE TITLE
Deadlink

### ISSUE THREAD

**Issue by joshkyh** [Azure/MachineLearningNotebooks#648]
Full sample is available from https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification/auto-ml-classification.ipynb is a dead link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9ee5b5-b8b7-0e7e-a665-a9c602b835c0
* Version Independent ID: 6b238373-7218-71fc-a3aa-89a7687086d4
* Content: [azureml.widgets.RunDetails class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-widgets/azureml.widgets.rundetails?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-widgets/azureml.widgets.RunDetails.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-widgets/azureml.widgets.RunDetails.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by johndoe0920** [comment]
@jeff-shepherd @vizhur Did the classification directory that contained this notebook get deleted?

**Comment by jeff-shepherd** [comment]
@johndoe0920 
Yes, this sample notebook has been replaced with: [https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb)
which includes the sample for launching the widget.

**Comment by vmagelo** [comment]
We updated the docs to address the issue. Changes will appear in the next SDK release in approx two weeks.
