### ISSUE TITLE
How to use PyTorch distributed training

### ISSUE THREAD

**Issue by yuzhms** [Azure/MachineLearningNotebooks#649]
Can I use PDD instead of Horovod? How to modify my code and submit job using python SDK?

**Comment by mx-iao** [comment]
Assuming you mean DDP, yes - here is a tutorial: https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/ml-frameworks/pytorch/training/distributed-pytorch-with-nccl-gloo
