### ISSUE TITLE
What's the difference between Mpi and MpiConfiguration?

### ISSUE THREAD

**Issue by yuzhms** [Azure/MachineLearningNotebooks#650]
When using horovod for pytorch distributed learning, I found some of sample code use Mpi and some use MpiConfiguration. What's the difference? Which one is recommended? 

There is another question, can I use NCCL backend for horovod?

**Comment by lostmygithubaccount** [comment]
@mx-xiao

**Comment by mx-iao** [comment]
Both are effectively the same and will work, please use `MpiConfiguration` though as we are planning to deprecate `Mpi` to dedupe the two. NCCL is already enabled for Horovod in our base images that we use: https://github.com/Azure/AzureML-Containers/tree/master/base/gpu
