### ISSUE TITLE
Local notebook to interprect model does not work

### ISSUE THREAD

**Issue by bcafferky** [Azure/MachineLearningNotebooks#651]
The library says it cannot find the module . Code and error below. I tried this by importing the notebook into an Azure Notebook. 

code:

# 2. Mimic Explainer
from interpret.ext.blackbox import MimicExplainer
# You can use one of the following four interpretable models as a global surrogate to the black box model
from interpret.ext.glassbox import LGBMExplainableModel
from interpret.ext.glassbox import LinearExplainableModel
from interpret.ext.glassbox import SGDExplainableModel
from interpret.ext.glassbox import DecisionTreeExplainableModel

# OR

# 3. PFI Explainer
from interpret.ext.blackbox import PFIExplainer 

Gives the error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c1bce9677f6d> in <module>
      4 # Explainers:
      5 # 1. SHAP Tabular Explainer
----> 6 from interpret.ext.blackbox import TabularExplainer
      7 
      8 # OR

ModuleNotFoundError: No module named 'interpret'

**Comment by lostmygithubaccount** [comment]
@bcafferky is this still an issue? can you provide more details on the notebook that is failing?

**Comment by minthigpen** [comment]
@bcafferky could you please update this thread with more details on the notebook that is failing?

**Comment by bcafferky** [comment]
Hi,

I left Microsoft back in December.  Please remove me from this.

Thanks,

Bryan
