### ISSUE TITLE
nyc-taxi-data-regression-model-building needs to be updated

### ISSUE THREAD

**Issue by oussamachelly** [Azure/MachineLearningNotebooks#652]
I am running the Jupyter notebook on an Azure VM. It fails with the error:
`ImportError: cannot import name 'BlockBlobService'`

**Comment by lostmygithubaccount** [comment]
@oussamachelly is this still an issue?

**Comment by shbijlan** [comment]
@oussamachelly Thank you for your feedback. I am not seeing the import statement for BlockBlobStorage in the named sample notebook. Can you please confirm you are using the current sample notebook referenced below? 

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/nyc-taxi-data-regression-model-building.ipynb

**Comment by lostmygithubaccount** [comment]
closing - feel free to reopen
