### ISSUE TITLE
train-hyperparameter-tune-deploy-with-tensorflow needs to be updated

### ISSUE THREAD

**Issue by oussamachelly** [Azure/MachineLearningNotebooks#653]
I am running the Jupyter notebook on an Azure VM. It fails with the error:
`Error occurred: User program failed with AttributeError: module 'tensorflow' has no attribute 'placeholder'`

It seems to be caused by the new TensorFlow version (2.0).

**Comment by martinezgjuan** [comment]
We will look into this as soon as possible. Thanks!

**Comment by lostmygithubaccount** [comment]
@martinezgjuan @oussamachelly has this been fixed? @swatig007 fyi

**Comment by CESARDELATORRE** [comment]
@swatig007 Can you or a dev from the HyperDrive team look into this HyperDrive issue?

**Comment by swatig007** [comment]
@nagau can you pls take a look to see if this is still an issue?

**Comment by swatig007** [comment]
this is already fixed since notebooks now use TF 2
