### ISSUE TITLE
Predict test data in img-classification-part2-deploy.ipynb

### ISSUE THREAD

**Issue by raybellwaves** [Azure/MachineLearningNotebooks#656]
At the section "Predict test data
Feed the test dataset to the model to get predictions." in https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/img-classification-part2-deploy.ipynb

When running
```
import pickle
from sklearn.externals import joblib

clf = joblib.load( os.path.join(os.getcwd(), 'sklearn_mnist_model.pkl'))
y_hat = clf.predict(X_test)
```

I get the error
```
KeyError                                  Traceback (most recent call last)
<ipython-input-15-70889f27ad68> in <module>
      3 #import joblib
      4 
----> 5 clf = joblib.load( os.path.join(os.getcwd(), 'sklearn_mnist_model.pkl'))
      6 y_hat = clf.predict(X_test)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py in load(filename, mmap_mode)
    596                     return load_compatibility(fobj)
    597 
--> 598                 obj = _unpickle(fobj, filename, mmap_mode)
    599 
    600     return obj

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    524     obj = None
    525     try:
--> 526         obj = unpickler.load()
    527         if unpickler.compat_mode:
    528             warnings.warn("The file '%s' has been generated with a "

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

KeyError: 0
```

May have to relationship to this?
https://stackoverflow.com/questions/48948209/keyerror-when-loading-pickled-scikit-learn-model-using-joblib

**Comment by raybellwaves** [comment]
This fixed it
```
import pickle
#from sklearn.externals import joblib
import joblib

clf = joblib.load( os.path.join(os.getcwd(), 'sklearn_mnist_model.pkl'))
y_hat = clf.predict(X_test)
print(y_hat)
```
but gave the warning
[7 2 1 ... 4 5 6]
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/sklearn/base.py:253: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.21.3 when using version 0.20.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

**Comment by noelbundick** [comment]
This is also failing for me on a new workspace + tutorial run through, with azureml 1.0.76. Tried both the notebook and the `joblib` workaround - no luck

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-21-ae86a2f4407a> in <module>
      3 import joblib
      4 
----> 5 clf = joblib.load( os.path.join(os.getcwd(), 'sklearn_mnist_model.pkl'))
      6 y_hat = clf.predict(X_test)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/joblib/numpy_pickle.py in load(filename, mmap_mode)
    603                     return load_compatibility(fobj)
    604 
--> 605                 obj = _unpickle(fobj, filename, mmap_mode)
    606 
    607     return obj

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    527     obj = None
    528     try:
--> 529         obj = unpickler.load()
    530         if unpickler.compat_mode:
    531             warnings.warn("The file '%s' has been generated with a "

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in load_global(self)
   1336         module = self.readline()[:-1].decode("utf-8")
   1337         name = self.readline()[:-1].decode("utf-8")
-> 1338         klass = self.find_class(module, name)
   1339         self.append(klass)
   1340     dispatch[GLOBAL[0]] = load_global

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in find_class(self, module, name)
   1386             elif module in _compat_pickle.IMPORT_MAPPING:
   1387                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1388         __import__(module, level=0)
   1389         if self.proto >= 4:
   1390             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'sklearn.linear_model._logistic'
```

The version of sklearn on my notebook VM is still 0.20.3. Guessing my cpu-cluster pulled down latest (0.22, released 3 days ago) and was affected by this change: https://github.com/scikit-learn/scikit-learn/commit/0a7adef0058ef28c7a146734f38161f7c7c581af#diff-92df390a5979a1919078f0f9b92ca51a

**Comment by trangevi** [comment]
The issue does appear to be due to a disconnect in versions of scikit-learn. I'm working on updating the notebooks and provided model to use the latest version which fixes the issue.

**Comment by BUCTestUser** [comment]
Still got this issue on latest version of the notebook. Is there a quick and easy workaround for this issue?

**Comment by mukopikmin** [comment]
As a workaround for now, I manually updated `scikit-learn` from the Git terminal in JupyterLab.
In my case, `scikit-learn==0.22.1` worked fine.

**Comment by BUCTestUser** [comment]
I updated scikit-learn as shown below, however I still get the same error as shown above, not sure why though
!pip3 install --upgrade scikit-learn
Requirement already up-to-date: scikit-learn in /anaconda/envs/azureml_py36/lib/python3.6/site-packages (0.22.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /anaconda/envs/azureml_py36/lib/python3.6/site-packages (from scikit-learn) (0.14.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in /anaconda/envs/azureml_py36/lib/python3.6/site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied, skipping upgrade: scipy>=0.17.0 in /anaconda/envs/azureml_py36/lib/python3.6/site-packages (from scikit-learn) (1.4.1)

**Comment by BUCTestUser** [comment]
sudo apt-get upgrade updates it successfully

**Comment by cram-rod** [comment]
Encountered same issue with Azure ML SDK 1.0.83.  As mentioned before, the sklearn version in the azure VM is older (0.20.x).  So, open the tutorial with JupyterLab, click on Git, select Git Command in Terminal and enter: pip install -U scikit-learn. That installed 0.22.2 in my case.  Rerun the first tutorial so the model can be regenerated. Play safe and also change the import joblib in the second tutorial (#from sklearn.externals import joblib --> import joblib) so it is consistent with the joblib used in the first tutorial. Rerun the second tutorial and it should be all good now.

**Comment by derdanh** [comment]
> Encountered same issue with Azure ML SDK 1.0.83. As mentioned before, the sklearn version in the azure VM is older (0.20.x). So, open the tutorial with JupyterLab, click on Git, select Git Command in Terminal and enter: pip install -U scikit-learn. That installed 0.22.2 in my case. Rerun the first tutorial so the model can be regenerated. Play safe and also change the import joblib in the second tutorial (#from sklearn.externals import joblib --> import joblib) so it is consistent with the joblib used in the first tutorial. Rerun the second tutorial and it should be all good now.

I've got the same issue as @noelbundick (ModuleNotFoundError) with Azure ML SDK 1.0.83. I have never worked with Jupyterlab, opening it gives me a blank page only with navigation bars on top and to the left. How do I go about fixing this? BG

**Comment by dejokz** [comment]
i tried `!pip install --upgrade scikit-learn`
what followed was 

```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-a7c478feb870> in <module>
      2 import joblib
      3 
----> 4 clf = joblib.load(os.path.join(os.getcwd(), 'sklearn_mnist_model.pkl'))
      5 y_hat = clf.predict(X_test)
      6 print(y_hat)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/joblib/numpy_pickle.py in load(filename, mmap_mode)
    603                     return load_compatibility(fobj)
    604 
--> 605                 obj = _unpickle(fobj, filename, mmap_mode)
    606 
    607     return obj

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    527     obj = None
    528     try:
--> 529         obj = unpickler.load()
    530         if unpickler.compat_mode:
    531             warnings.warn("The file '%s' has been generated with a "

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in load_global(self)
   1336         module = self.readline()[:-1].decode("utf-8")
   1337         name = self.readline()[:-1].decode("utf-8")
-> 1338         klass = self.find_class(module, name)
   1339         self.append(klass)
   1340     dispatch[GLOBAL[0]] = load_global

/anaconda/envs/azureml_py36/lib/python3.6/pickle.py in find_class(self, module, name)
   1386             elif module in _compat_pickle.IMPORT_MAPPING:
   1387                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1388         __import__(module, level=0)
   1389         if self.proto >= 4:
   1390             return _getattribute(sys.modules[module], name)[0]

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py in <module>
     19 from joblib import Parallel, delayed, effective_n_jobs
     20 
---> 21 from ._base import LinearClassifierMixin, SparseCoefMixin, BaseEstimator
     22 from ._sag import sag_solver
     23 from ..preprocessing import LabelEncoder, LabelBinarizer

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/sklearn/linear_model/_base.py in <module>
     25 from joblib import Parallel, delayed
     26 
---> 27 from ..base import (BaseEstimator, ClassifierMixin, RegressorMixin,
     28                     MultiOutputMixin)
     29 from ..utils import check_array, check_X_y

ImportError: cannot import name 'MultiOutputMixin```

**Comment by carneya** [comment]
I get the same as @dejokz, any suggestions

**Comment by dejokz** [comment]
i ran the code the following date, it worked without any hitch

**Comment by adieldar** [comment]
To fix it

1. set scikit-learn 0.20.3 in the training notebook:

cd = CondaDependencies.create(pip_packages=['azureml-sdk','scikit-learn==0.20.3','azureml-dataprep[pandas,fuse]>=1.1.14'])

2. In the deploy notebook import joblib from sklearn:

#import joblib
from sklearn.externals import joblib

**Comment by jhagege** [comment]
Any chance you could update the existing notebooks with this solution ?
