### ISSUE TITLE
regression-automated-ml.ipynb: updated AutoMLConfig inputs

### ISSUE THREAD

**Issue by raybellwaves** [Azure/MachineLearningNotebooks#659]
In https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/regression-automated-ml.ipynb

When I run
```
from azureml.train.automl import AutoMLConfig

automl_config = AutoMLConfig(task='regression',
                             debug_log='automated_ml_errors.log',
                             X=x_train.values,
                             y=y_train.values.flatten(),
                             **automl_settings)
```

I get
```
WARNING - The AutoMLConfig inputs you have specified will soon be deprecated. Please use the AutoMLConfig shown in our documentation: https://aka.ms/AutoMLConfig
```

Couldn't see what parameters it is referring to in
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-auto-train#configure-your-experiment-settings

**Comment by ahyerman** [comment]
@raybellwaves sorry for the confusion and thank you for the feedback! We are updating the error message to explicitly list the parameters which are being deprecated.

We are moving aware from `X`, `y` and recommend using `training_data`, `label_column_name`. 
You'll find some samples of this in the latest released notebooks, for instance, [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/regression/auto-ml-regression.ipynb)
