### ISSUE TITLE
The constructor is not documented. 

### ISSUE THREAD

**Issue by nihil0** [Azure/MachineLearningNotebooks#66]
It would be useful to understand what the parameters in the constructor are. Could you add some documentation for them?

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: d11bca2c-939e-2125-7dae-aee7d37c8844
* Version Independent ID: f362dc68-c243-df06-976d-9cc1eb5d427c
* Content: [azureml.core.Workspace class](https://docs.microsoft.com/fi-fi/python/api/azureml-core/azureml.core.workspace(class)?view=azure-ml-py#write-config)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by akshaya-a** [comment]
Certainly @nihil0 - we'll add more examples and detailed descriptions of each parameter!

**Comment by j-martens** [comment]
@kenkadota why closed? Was it documented?

**Comment by kenkadota** [comment]
Sounds good Josee, thank you for the clarification.

**Comment by j-martens** [comment]
Thanks for your report. I believe the docs are complete now. Let us know if you feel differently.
