### ISSUE TITLE
Datastore.register_azure_blob_container() does not contain the argument grant_workspace_access

### ISSUE THREAD

**Issue by Ayoung-Ag** [Azure/MachineLearningNotebooks#661]
I'm trying to register a datastore that is in a vnet to my ML workspace. From the documentation, it looks like grant_workspace_access should be set to True, however, it is not actually an available argument of the function. Is this a deprecated or unnecessary step?

**Comment by anliakho2** [comment]
@Ayoung-Ag  check your `azureml-sdk` version. This flag was introduced in version 1.0.53
I suggest upgrading to the latest version of SDK and trying again.

**Comment by Ayoung-Ag** [comment]
Thank you, this is my issue. I now realize that I'm using an older version.
