### ISSUE TITLE
Pass an argument to the scoring script for a registered image

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#662]
I am trying to pass an argument to the `score.py` script that will be packaged in an image and deployed as a service: 
```python
from azureml.core.model import Model

def init():
    global model

    model_path = Model.get_model_path('MY-MODEL-NAME-AS-INPUT-PARAM')
    model = joblib.load(model_path)
```
Since the `score.py` is being packaged and registered with the `environment.yml` as a container, I am looking for a way to give the scoring script access to the model name other than hardcoding the name. 

I am familiar with passing a dependencies folder and packaging it but that means I am still hardcoding the name of the model in a config file that is also packaged in the container. 

Are there any solutions for dynamically giving access to the scoring script in the registered container to arguments that can be fed in? (in this case, the model name which in my scenario changes between a branch and another) 

@sanpil @swanderz

**Comment by jadhosn** [comment]
#484 seems to have already asked for something similar. @jpe316  I'm wondering if passing an argument was added?

**Comment by jpe316** [comment]
You can use the environment variable for this now. Our docs have been updated!

model_path = os.path.join(os.getenv('AZUREML_MODEL_DIR'), 'model.pkl')
