### ISSUE TITLE
img-classification-part1-training broken due to new version of azure-storage-blob (12.0.0)

### ISSUE THREAD

**Issue by ericct** [Azure/MachineLearningNotebooks#664]
Hello,

This notebook seems to be broken when loading MNIST data from line
`from azureml.opendatasets import MNIST`

I get this error : ``Import path `azure.storage.blob`; cannot import name 'BlockBlobService'``

pip freeze shows that current installed version for azure-storage-blob is 12.0.0. Reverting to previous version (2.1.0) fixes this (but an update from azureml.opendatasets would be welcome).

**Comment by vizhur** [comment]
latest azureml-opendatasets addressed the issue by pinning the upperbound of the dependency to <12.0.0 with 1.0.72.1 patch and following releases.
If you stay with the older version of SDK you'd need to mitigate the issue by downgrading azure-storage-blob
