### ISSUE TITLE
Error displaying widget  No renderer could be found for output. It has the following MIME types: application/aml.mini.widget.v1

### ISSUE THREAD

**Issue by konabuta** [Azure/MachineLearningNotebooks#666]
Hi experts,

I'm running error related to widget on JupyterLab of Notebook VM. Using latest sdk version 1.0.74 and default kernel "Python 3.6 - AzureML".

```python
from azureml.widgets import RunDetails
RunDetails(run).show()
```
_Error displaying widget
No renderer could be found for output. It has the following MIME types: application/aml.mini.widget.v1_

Any workaround on this ?

Regards,
Keita

**Comment by YutongTie-MSFT** [comment]
@konabuta 
Thanks for the feedback! I have assigned the issue to the product owner to investigate further and update the document as appropriate.

@maxluk 
Hi Maxim, this is a issue about Jupyter Notebook, could you please help to check? Thanks.

**Comment by swinner95** [comment]
Which notebook are you trying to run? @konabuta  @YutongTie-MSFT

**Comment by konabuta** [comment]
Thanks @swinner95 .

I tried the following notebook.

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/scikit-learn/training/train-hyperparameter-tune-deploy-with-sklearn/train-hyperparameter-tune-deploy-with-sklearn.ipynb

**Comment by swinner95** [comment]
The mini-widget does not yet work in Jupyter Lab.

**Comment by swinner95** [comment]
@JulianChu1207  can you provide an ETA on when this will become available?

**Comment by ovokpus** [comment]
It works on vscode, but not on the browser in the Jupyter Notebook

**Comment by IntegerMan** [comment]
Doesn't appear to work for me on VS Code Jupyter Notebooks at the moment, but perhaps an update fixes it.

**Comment by mrobertsonavidxchange** [comment]
Doesn't work on VS code for me as well

**Comment by thedamian** [comment]
I don't know if it helps. but now I've run the suggested lines below and now it does complain still about the mime types but the output from the workspaces remain on the screen.

Lines I ran as suggested:
```
python -m jupyter nbextension uninstall --py --user azureml.widgets
python -m jupyter nbextension uninstall --py --user azureml.train.widgets


python -m jupyter nbextension install --py --user azureml.widgets
python -m jupyter nbextension enable azureml.widgets --user --py

python -m jupyter nbextension install --py --user azureml.train.widgets
python -m jupyter nbextension enable azureml.train.widgets --user --py

```

**Comment by d-kleine** [comment]
Same issue with the newest *pip* package of `azureml.widgets` in VS Code for Python 3.10. I have had this issue when displaying the detail widget for an Azure Hyperdrive run in a Jupyter Notebook:

```python
# Submit your hyperdrive run to the experiment and show run details with the widget
hyperdrive_run = exp.submit(config=hyperdrive_config) 

# show run details with the widget
RunDetails(hyperdrive_run).show()
```
