### ISSUE TITLE
PipelineParameter with default_value empty string

### ISSUE THREAD

**Issue by gison93** [Azure/MachineLearningNotebooks#668]
Assigning to a pipeline parameter the default_value="" produces the following error:
Assignment for parameter <parameter_name> is not specified.
To solve the issue I used a placeholder "None" that then is handled in the script.
Is there a better way to handle the case in which the default value has to be an empyt string?

sdk version 1.0.62

**Comment by YutongTie-MSFT** [comment]
@gison93 
Thanks for the feedback! We are currently investigating and will update you shortly.

@sanpil Hi, could you please help us check this issue? Thanks a lot!

**Comment by purnesh42H** [comment]
@gison93 when do you get this error? During PipelineParameter initialization or pipeline creation? I think latest version of azureml-sdk does allow you to initialize it with empty string.

**Comment by purnesh42H** [comment]
@gison93 Just verified. PipelineParameter doesn't allow empty string or None as default value.

**Comment by sanpil** [comment]
We have identified the bug. Thanks for reporting.

**Comment by YutongTie-MSFT** [comment]
@sanpil Do we have something in backlog so that we are good to close this? Thanks.

**Comment by sanpil** [comment]
Yes, I have opened a bug. We are good to close this.

**Comment by YutongTie-MSFT** [comment]
@gison93 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
