### ISSUE TITLE
Deploying Faster R-CNN tensorflow model

### ISSUE THREAD

**Issue by pugillum** [Azure/MachineLearningNotebooks#67]
This is not an issue as such.  I've been trying to deploy a frozen inference graph I generated using the Tensorflow model zoo faster rcnn inception v2 model.  So far I've encounted issues with a dependency on Open CV which I fixed by shifting to use of Pillow but I'm still not able to get the initialization of my score.py working.  I wondered if there was any advice on what I'm attempting, particularly if what I'm trying to do is, in fact, not yet supported.  I'd be most willing to share my experience and any insights I've gained if that helps in any way.

**Comment by mx-iao** [comment]
Hi @pugillum , have you taken a look at this [tutorial](https://github.com/Azure/MachineLearningNotebooks/blob/master/training/03.train-hyperparameter-tune-deploy-with-tensorflow/03.train-hyperparameter-tune-deploy-with-tensorflow.ipynb) yet? It covers an example of writing a score.py file and deploying a TensorFlow model

**Comment by pugillum** [comment]
Thanks, I'll take a look. At the moment I'm having success using a Tensorflow serving docker container and deploying using ACI or AKS.
