### ISSUE TITLE
The azureml.core.Webservice isn't setting the Accept header to application/json and with ONNX deployments

### ISSUE THREAD

**Issue by joshheitzman-redcley-v-joheit-msft** [Azure/MachineLearningNotebooks#671]
If the response code is 200 the azureml.core.Webservice will always try to deserialize the content as JSON. But it isn't setting the Accept header to application/json in the request to ensure the server (e.g. the ONNX runtime server) actually provides JSON in the response.

This necessitates not using azureml.core.Webservice in the how-to-use-azureml/deployment/onnx/onnx-model-register-and-deploy.ipynb notebook as well as any other client of a deployment for a model that was registered with model_framework=azureml.core.model.Model.Framework.ONNX

**Comment by YutongTie-MSFT** [comment]
@joshheitzman-redcley-v-joheit-msft 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by Bozhong68** [comment]
Hey @joshheitzman-redcley-v-joheit-msft , Thanks for feedback, we are working on a fix to address the issue.
