### ISSUE TITLE
datastore parameter

### ISSUE THREAD

**Issue by rsethur** [Azure/MachineLearningNotebooks#672]
The description of the datastores states it should be of type AbstractAzureStorageDatastore or AzureDataLakeDatastore.
Does this support only AzureDataLakeDatastore (i.e. gen 1) or is it AbstractADLSDatastore ? i.e. it suports Gen 2 as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c2ec02-ffc7-6653-e8bc-b085d951a8ed
* Version Independent ID: c15d23ad-249a-39cc-8135-1073678d5491
* Content: [azureml.pipeline.core.PipelineData class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinedata?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineData.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineData.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@rsethur 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
