### ISSUE TITLE
to_dataset() is incorrect name?

### ISSUE THREAD

**Issue by rsethur** [Azure/MachineLearningNotebooks#673]
The page mentions api to_dataset() - is this actually as_dataset?
If this is an issue, needs fix in these pages as well:
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core?view=azure-ml-py
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_output_dataset?view=azure-ml-py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2acf24e-94d1-789e-f0f1-d90db42c57a7
* Version Independent ID: eb04f1f6-704d-1479-4571-d57a443973ac
* Content: [azureml.pipeline.core.pipeline_output_dataset module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_output_dataset?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline_output_dataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline_output_dataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@rsethur 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
This was fixed recently.  https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline_output_dataset?view=azure-ml-py.  Thanks.
