### ISSUE TITLE
How do I add a new index

### ISSUE THREAD

**Issue by wagenrace** [Azure/MachineLearningNotebooks#675]
We have our own artifacts feed and want to install package from there. How do I add this url?

On local machines I would do one of the following:
- add extra-index-url to pip.conf
- add -i after pip install command in requirments.txt
- add --extra-index-url at the top of requirments.txt

none of them I can get working. The requirments.txt is read without errors using from_pip_requirements but my package can not be loaded during a run

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a52b4ac-50be-de5e-f374-0942b5c79091
* Version Independent ID: e37013e0-7618-9c14-a0af-9c9c305776df
* Content: [azureml.core.environment.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py#from-pip-requirements-name--file-path-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@wagenrace 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by vizhur** [comment]
@wagenrace  
Environment.from_pip_requirements() uses CondaDependencies.create() method that has a limitation of allowing only 1 extra index url and also pins SDK to a client version. 
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies?view=azure-ml-py#create-pip-indexurl-none--pip-packages-none--conda-packages-none--python-version--3-6-2---pin-sdk-version-true-

In most of the case that should be sufficient. In a case you need more than 1 extra index url you can load env from yaml

env = Environment(name=name)
env.python.conda_dependencies = CondaDependencies(path_to_yaml_file)

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies?view=azure-ml-py

**Comment by YutongTie-MSFT** [comment]
@wagenrace 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
