### ISSUE TITLE
AutoMLConfig unknown location

### ISSUE THREAD

**Issue by fatosismali** [Azure/MachineLearningNotebooks#678]
I am running: ~/anaconda3/bin/pip install --upgrade azureml-sdk[explain,automl]

and getting the following result when I try to load AutoMLConfig:

```
ImportError                               Traceback (most recent call last)
<ipython-input-44-9416efdf608b> in <module>
----> 1 from azureml.train.automl import AutoMLConfig
      2 #from azureml.train.automl.automlconfig import AutoMLConfig
      3 from azureml.train.automl.run import AutoMLRun
      4 import logging
      5 

ImportError: cannot import name 'AutoMLConfig' from 'azureml.train.automl' (unknown location)
```
Here is the list of pip packages installed in my pc that are relevant to azureml:

```
 ~/anaconda3/bin/pip list | grep azureml
azureml-automl-core                            1.0.76       
azureml-automl-runtime                         1.0.76.1     
azureml-core                                   1.0.76       
azureml-dataprep                               1.1.31       
azureml-dataprep-native                        13.1.0       
azureml-defaults                               1.0.76       
azureml-explain-model                          1.0.76       
azureml-interpret                              1.0.76       
azureml-model-management-sdk                   1.0.1b6.post1
azureml-pipeline                               1.0.76       
azureml-pipeline-core                          1.0.76       
azureml-pipeline-steps                         1.0.76       
azureml-sdk                                    1.0.76       
azureml-telemetry                              1.0.76       
azureml-train                                  1.0.76       
azureml-train-automl                           1.0.76       
azureml-train-automl-client                    1.0.76       
azureml-train-automl-runtime                   1.0.76.1     
azureml-train-core                             1.0.76       
azureml-train-restclients-hyperdrive           1.0.76       
azureml-widgets                                1.0.69.1 

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30b9035-3671-a51d-5054-01313f9967ca
* Version Independent ID: 47fb4557-f0fa-6a43-e648-fd4b48921397
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by fatosismali** [comment]
I tried it on a fresh Data Science VM on Azure and this problem does not seem to occur. Which means that some of the python libraries are not compatible in my environment.

**Comment by YutongTie-MSFT** [comment]
@fatosismali 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
