### ISSUE TITLE
Published pipeline doesnt run its steps

### ISSUE THREAD

**Issue by gargiulman** [Azure/MachineLearningNotebooks#680]
I have added ML Pipeline execution activity in ADF and have provided the published pipeline name and its id. However when the ADF completes its run, i see the activity also completed. 
However on Azure ML workspace when i find the pipeline now has got completed in < 1 min whereas normally when i submit it, it runs for atleast 30 mins. 

Am i missing anything, or is that allow_reuse = false should be set if we plan to publish the azure ml pipeline.

**Comment by YutongTie-MSFT** [comment]
@gargiulman 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by elihop22** [comment]
Any steps in your PublishedPipeline will reuse previous results if there have not been any changes to the parameters of the step and allow_reuse is set to true. If you want the steps to generate a new run every time you submit the PublishedPipeline, allow_reuse should be set to false when you publish the Pipeline. More info [here](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-your-first-pipeline#caching--reuse)

**Comment by YutongTie-MSFT** [comment]
@gargiulman Close this thread since it's not active now.
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
