### ISSUE TITLE
Sample with Webservice(ws, service_name) does not work

### ISSUE THREAD

**Issue by algattik** [Azure/MachineLearningNotebooks#681]
Sample with `Webservice(ws, service_name)` does not work:

```
    service = Webservice(ws, service_name)
  File "lib/python3.7/site-packages/azureml/core/webservice/webservice.py", line 192, in __new__
    return super(Webservice, cls).__new__(cls)
TypeError: Can't instantiate abstract class Webservice with abstract methods _deploy, get_token, run, update
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 045c9469-5ed5-3435-49f6-6374202fbe01
* Version Independent ID: 9b483196-0666-e292-dc6a-c4f5d6454942
* Content: [azureml.core.Webservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice(class)?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Webservice(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Webservice(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@algattik 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
I just ran both notebooks referenced in [Webservice](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice%28class%29?view=azure-ml-py#remarks) class remarks class and they worked. The samples in the remarks are extracts from the notebooks and run only with the context provided in the notebook.

**Comment by PeterCLu** [comment]
@algattik Thanks for your report. Since we haven't heard back from you in awhile, I will proceed to close this issue. If you feel that your issue has not been resolved, please reopen the issue and provide additional context.
