### ISSUE TITLE
AutoMLConfig class signature is not readable..

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#682]
This signature above is not readable, at least it should show one parameter per line?...:

AutoMLConfig(task: str, path: typing.Union[str, NoneType] = None, iterations: typing.Union[int, NoneType] = None, data_script: typing.Union[str, NoneType] = None, primary_metric: typing.Union[str, NoneType] = None, compute_target: typing.Union[typing.Any, NoneType] = None, spark_context: typing.Union[typing.Any, NoneType] = None, X: typing.Union[typing.Any, NoneType] = None, y: typing.Union[typing.Any, NoneType] = None, sample_weight: typing.Union[typing.Any, NoneType] = None, X_valid: typing.Union[typing.Any, NoneType] = None, y_valid: typing.Union[typing.Any, NoneType] = None, sample_weight_valid: typing.Union[typing.Any, NoneType] = None, cv_splits_indices: typing.Union[typing.Any, NoneType] = None, validation_size: typing.Union[float, NoneType] = None, n_cross_validations: typing.Union[int, NoneType] = None, y_min: typing.Union[float, NoneType] = None, y_max: typing.Union[float, NoneType] = None, num_classes: typing.Union[int, NoneType] = None, featurization: typing.Union[str, azureml.automl.core.featurization.featurizationconfig.FeaturizationConfig] = 'off', lag_length: int = 0, max_cores_per_iteration: int = 1, max_concurrent_iterations: int = 1, iteration_timeout_minutes: typing.Union[int, NoneType] = None, mem_in_mb: typing.Union[int, NoneType] = None, enforce_time_on_windows: bool = True, experiment_timeout_minutes: typing.Union[int, NoneType] = None, experiment_exit_score: typing.Union[float, NoneType] = None, enable_early_stopping: bool = False, blacklist_models: typing.Union[typing.List[str], NoneType] = None, exclude_nan_labels: bool = True, verbosity: int = 20, enable_tf: bool = False, enable_cache: bool = True, cost_mode: int = 0, whitelist_models: typing.Union[typing.List[str], NoneType] = None, enable_onnx_compatible_models: bool = False, enable_voting_ensemble: bool = True, enable_stack_ensemble: bool = True, debug_log: str = 'automl.log', training_data: typing.Union[typing.Any, NoneType] = None, validation_data: typing.Union[typing.Any, NoneType] = None, label_column_name: typing.Union[str, NoneType] = None, weight_column_name: typing.Union[str, NoneType] = None, **kwargs: typing.Any) -&gt; None

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e822a65-17a8-2a1b-a62a-c143405481ff
* Version Independent ID: e632817d-3e64-d8e6-d1bb-5ee0165856f2
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@CESARDELATORRE 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by j-martens** [comment]
#re-assign:@cartacioS

**Comment by j-martens** [comment]
@CESARDELATORRE  is this fixed now?

**Comment by CESARDELATORRE** [comment]
I think it's appearing the same way:
![image](https://user-images.githubusercontent.com/1712635/84931143-3c7b2b80-b087-11ea-8f3f-68089e19ab23.png)

My proposal is to have one parameter per line. It'll be longer, but at least it'll be more readable.
Or any other structure where it's easier to identify the parameters in the signature.

However, I'm not sure if this is easy to do or not because it might be coming automatically from code? not sure...

**Comment by j-martens** [comment]
it is generated straight from the code. the engineer would have to fix formatting in the doc strings in VSO. If you know who can fix them, please assign them so they are aware.

**Comment by CESARDELATORRE** [comment]
Adding @rtanase

**Comment by rtanase** [comment]
@harneetvirk , is this something that can be controlled when docs get generated?

**Comment by CESARDELATORRE** [comment]
#please-close this issue as it's stale and not actionable since signatures are created the same way for all APIs.
