### ISSUE TITLE
Enable "Search in all of SDK documention" instead of "All Azure"

### ISSUE THREAD

**Issue by ezwiefel** [Azure/MachineLearningNotebooks#683]
The Search functionality in the [Azure Databricks documentation](https://docs.microsoft.com/en-us/azure/azure-databricks/) allows users to only search in the Azure Databricks documentation. That should be enabled for the AML documention (both the SDKs and the product docs.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0be5f00-b267-a544-5e1c-36fa254f7801
* Version Independent ID: b8b3eec3-8cf4-dc39-a4e3-f2ed5fa3590d
* Content: [Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/intro?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-conceptual/intro.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-conceptual/intro.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by YutongTie-MSFT** [comment]
@trevorbye 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by lostmygithubaccount** [comment]
@trevorbye is this enabled?

**Comment by paulshealy1** [comment]
This is the behavior I get now when I search in the docs.
