### ISSUE TITLE
pipeline cannot register dataset  in auto-ml-continuous-retraining.ipynb

### ISSUE THREAD

**Issue by shoresh57** [Azure/MachineLearningNotebooks#684]

**Comment by shoresh57** [comment]
The problem is with dataset (NOAA) , I changed week from 1 to 9 in upload_weather_data.py and it worked ,dataset is not uppdated during the last 2 weeks

**Comment by YutongTie-MSFT** [comment]
@vizhur Hi, could you please help us to check this issue? Thanks.

**Comment by shbijlan** [comment]
#please-close
