### ISSUE TITLE
model_explainability is missing

### ISSUE THREAD

**Issue by konabuta** [Azure/MachineLearningNotebooks#685]
model_explainability is missing in this documents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e822a65-17a8-2a1b-a62a-c143405481ff
* Version Independent ID: e632817d-3e64-d8e6-d1bb-5ee0165856f2
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@konabuta 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by j-martens** [comment]
cc: @vmagelo

**Comment by gaugup** [comment]
Sorry that you faced this issue. We have added a fix for this missing parameter in AutoMLConfig and this should be available in the upcoming AzureML python SDK releases.

**Comment by PeterCLu** [comment]
@konabuta Thanks for your report. Since we don't yet support that functionality, the documentation will remain as is. I will proceed to close this issue.
