### ISSUE TITLE
DatabricksStep requires compute_target even when passed RunConfiguration

### ISSUE THREAD

**Issue by OliStiel** [Azure/MachineLearningNotebooks#686]
With a normal PythonScriptStep, we can pass the compute target in a RunConfiguration with the following:

`fit_and_predict = PythonScriptStep(
    ...
    runconfig=fit_predict_RC)`

and with our compute passed into that config via...

`compute = ComputeTarget(workspace=workspace, name=COMPUTE_TARGET)
fit_predict_RC.target = compute`

But with a DatabricksScriptStep, when passing compute with...

`databricks_compute = DatabricksCompute(workspace=workspace, name=DB_COMPUTE_TARGET)`
```
dbricks_config = DatabricksCluster(existing_cluster_id='[CLUSTER_ID]')

dbricks_RC = RunConfiguration()
dbricks_RC.environment.databricks.cluster = dbricks_config
dbricks_RC.target = databricks_compute
```
We run into the following:
```
  File "...\envs\azure_ml\lib\site-packages\azureml\pipeline\core\_databricks_step_base.py", line 304, in __init__
    raise ValueError('compute_target is required')
ValueError: compute_target is required
```

This looks to be because in _DatabricksStepBase, the runconfig's target is never used, whereas in _PythonScriptStepBase, compute_target is pulled from the runconfig when present.

Is this intentional, and am I getting something horribly wrong? It seems unintuitive that for the PythonScriptStep that we can pass compute 'cleanly' in that run config, but can't for the databricks equivalent (where that .target property is ignored).

This is running on azure-sdk version 1.0.76

**Comment by YutongTie-MSFT** [comment]
@OliStiel 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by fahdkmsft** [comment]
Agree this is not consistent but it is what we have right now. Customer needs to pass compute_target separately.

**Comment by YutongTie-MSFT** [comment]
@OliStiel 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
