### ISSUE TITLE
NoaaIsdWeather dataset for data drift has wrong shape

### ISSUE THREAD

**Issue by benedikt-mayer** [Azure/MachineLearningNotebooks#691]
The data drift example notebook yields and error when run as-is.

https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/monitor-models/data-drift

## To reproduce

Run the data drift notebook as is.

## Error

`Invalid input array: an array with 2 dimensions is expected; input has 1 [shape (0,)]`

## Workaround

change the cell below `Run recent weather data through the webservice`

to an older date:

```
from datetime import datetime, timedelta
from azureml.opendatasets import NoaaIsdWeather

start = datetime.today() - timedelta(days=30) # instead of datetime.today() - timedelta(days=2)
end = datetime.today() - timedelta(days=28) # datetime.today()

isd = NoaaIsdWeather(start, end)

df = isd.to_pandas_dataframe().fillna(0)
df = df[df['stationName'].str.contains('FLORIDA', regex=True, na=False)]

X_features = ['latitude', 'longitude', 'temperature', 'windAngle', 'windSpeed']
y_features = ['elevation']

X = df[X_features]
y = df[y_features]
```
## Why is this broken?

I'm guessing the format for `NoaaIsdWeather` must've changed for December.

**Comment by YutongTie-MSFT** [comment]
@benedikt-mayer 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by lostmygithubaccount** [comment]
This is a known issue that was fixed in yesterday's release (Python SDK version 1.0.79 and associated example notebooks) - can you try updating your SDK/new notebook?

**Comment by lostmygithubaccount** [comment]
Apologies - the new notebook was not released yesterday. This notebook will be updated soon.

**Comment by WeiLengUSC** [comment]
@benedikt-mayer @lostmygithubaccount  please reference changes in this draft PR: https://github.com/Azure/MachineLearningNotebooks/pull/694/files which will not remove the dependency on opendataset.

**Comment by YutongTie-MSFT** [comment]
@benedikt-mayer 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
