### ISSUE TITLE
better error handling Dataset.to_pandas_dataframe()

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#692]
I heard a rumor that there was error handling coming to `dataprep`/`Datasets`.... For me this is a requirement as I'd like to be explicit about what happens. We're experiencing random errors when upgrading dataset versions due to invisible `to_pandas_dataframe()` error handling.

**Comment by YutongTie-MSFT** [comment]
@swanderz 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by MayMSFT** [comment]
Thanks Anders. We have checked in the option for users to specify whether they want to_pandas_dataframe() to fail if type conversion fails. the chance will be released on Jan 6. thanks

**Comment by YutongTie-MSFT** [comment]
@swanderz 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
