### ISSUE TITLE
how to search for public blob containers?

### ISSUE THREAD

**Issue by ballcap231** [Azure/MachineLearningNotebooks#693]
Under tutorials there is a notebook "tutorial-pipeline-batch-scoring-classification" that goes over setting up azure compute cluster and I've been trying to figure out how to do it for a few days already now. 

There's a section that says "Get the ImageNet evaluation public data sample from the public blob container sampledata on the account pipelinedata", but **where is the public blob container "sampledata" / where is the account "pipelinedata"?**  **(i.e. how do i search for public blob containers?)**

This would be good to know as I try to understand how the folder structures are setup. I don't understand the folder structure of how to setup input/output data directories.

I followed the notebook as best as I could but I get "directory not found" when i do os.chdir(whatever_file_path_name_it_is) to the DataReference object i input to my run. The path on path_on_datastore points to an existing folder in my blob container as far as I know.

![image](https://user-images.githubusercontent.com/40708323/70579203-7e299780-1b75-11ea-83b4-f08d54ad2fe2.png)

**Comment by jonringer** [comment]
>where is the public blob container "sampledata" / where is the account "pipelinedata"? 

They are in an Azure ML subscription.

> (i.e. how do i search for public blob containers?)

Blob containers cannot be searched or indexed by anonymous users. Only read access from direct URIs.

I think your question is: how can I make a blob container + path into a datareference, this is done in two parts: registering a blob container as a datastore, then using a path on that datastore to become a datareference.

You would need to do something such as:
```
my_datastore = Datastore.register_azure_blob_container(ws, 
                      datastore_name="new_datastore", 
                      container_name="mytestcontainer", 
                      account_name="storage_account_name", 
                      overwrite=True)
```

now that you have a datastore which is referring to the blob container, you can select a file or folder path with datareference:
```
input_images = DataReference(datastore=my_datastore, 
                             data_reference_name="what_i_want_to_name_it",
                             path_on_datastore="163ss_full_Des145_Meas18",
                             mode="download"
                            )
```

**Comment by YutongTie-MSFT** [comment]
@ballcap231 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
