### ISSUE TITLE
script folder not being created in train-with-datasets.ipynb

### ISSUE THREAD

**Issue by marcscho** [Azure/MachineLearningNotebooks#695]
As I'm working through train-with-datasets.ipynb, I realized that the script folder to later save the training file to is specified but not created.

script_folder = os.path.join(os.getcwd(), 'train-dataset')

### missing line
os.mkdir(script_folder)

**Comment by YLXiong1125** [comment]
This `train-dateset` is a preexisting folder for this sample notebook, which host the training dataset and will be uploaded to the default datastore of the workspace. If you run through the notebook, you will first see the cells, e.g. one cell is to upload the training dataset from this folder, and the other cell is to create a dataset referring to this training dataset in the default datastore. Then you will see the script creation cell. Hope it helps.

**Comment by YutongTie-MSFT** [comment]
@marcscho 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
