### ISSUE TITLE
aml-pipelines-with-data-dependency-steps.ipynb freezes on pipeline submit

### ISSUE THREAD

**Issue by julcik** [Azure/MachineLearningNotebooks#696]
I'm going through the tutorials running notebooks from local environment, but submitting to compute for execution.
For me aml-pipelines-with-data-dependency-steps.ipynb freezes on line
`pipeline_run1 = Experiment(ws, 'Data_dependency').submit(pipeline1)`
The experiment shows up on Experiments page in Azure ML Studio, but with 'No runs to display'.

I run notebook without any changes. 
SDK version: 1.0.79

I wanted use this example as a starting point for my project, but unfortunately it doesn't work.
Can you help me to figure out what can be the case of such behavior?

**Comment by purnesh42H** [comment]
@julcik did you try to run the RunDetails widget?

**Comment by julcik** [comment]
@purnesh42H today the same notebook on the same environment works. 
When I was writing this issue, I had no successful message: notebook cell used to freeze on submitting, control was not returned.

Can you, please, help me to understand how can I possibly debug such issues: how can I understand what goes wrong.

**Comment by YutongTie-MSFT** [comment]
@julcik Could you please share the tutorials you are referring to? Thanks.

**Comment by julcik** [comment]
> @julcik Could you please share the tutorials you are referring to? Thanks.

This one https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb
