### ISSUE TITLE
Feature: Button in UX to "download support files"

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#697]
This would be great to have in the UX that would bundle to log files to share w/ support team!
https://techcommunity.microsoft.com/t5/Azure-Data-Factory/Download-Azure-Data-Factory-support-files/ba-p/1042848
![image](https://gxcuf89792.i.lithium.com/t5/image/serverpage/image-id/159649i0F2301E6DFA000E7/image-size/large?v=1.0&px=999)

**Comment by YutongTie-MSFT** [comment]
@swanderz Hi, are you sharing the feedback for https://ml.azure.com/ ? Thanks.

**Comment by swanderz** [comment]
Yep, by using an example of functionality that already exists for adf.azure.com

**Comment by YutongTie-MSFT** [comment]
@swanderz Hi Anders, thanks for your feedback. I will forward your feedback to product team ^^

**Comment by swinner95** [comment]
Hi @swanderz , the experimentation UI team will be exposing the functionality in the UI to allow users to download all their logs. #please-close

**Comment by swanderz** [comment]
@swinner95 -- awesome! any specific timeline? weeks, months, quarters years?

**Comment by swinner95** [comment]
@swanderz  This semester (ETA: ~ Oct time frame)
