### ISSUE TITLE
Fail to Explaine the Automl model?

### ISSUE THREAD

**Issue by alla15747** [Azure/MachineLearningNotebooks#698]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-98-e33987ac5d10> in <module>
      4 client = ExplanationClient.from_run(remote_run)
      5 global_explanation = client.download_model_explanation()
----> 6 local_importance_values = global_explanation.local_importance_values
      7 expected_values = global_explanation.expected_values

AttributeError: 'NoneType' object has no attribute 'local_importance_values'

**Comment by YutongTie-MSFT** [comment]
@alla15747 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by gaugup** [comment]
Hi @alla15747 

Are you still experiencing this issue? Which AutoML user notebook are you using?

**Comment by YutongTie-MSFT** [comment]
@alla15747 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
