### ISSUE TITLE
Failed to kill job

### ISSUE THREAD

**Issue by yuzhms** [Azure/MachineLearningNotebooks#700]
I am using AML. There are some jobs I can't kill. The error messages are

InternalServerError RequestId: null, SessionId: null.

{
  "error": {
    "code": "ServiceError",
    "message": "InternalServerError",
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": {
      "type": "Newtonsoft.Json.JsonSerializationException",
      "message": "Error converting value \"BatchAI\" to type 'System.Nullable`1[Microsoft.MachineLearning.Execution.Services.ComputeTargetType]'. Path 'InitialRunState.ComputeTargetType'.",
      "stackTrace": "   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\n   at Microsoft.MachineLearning.Common.DocumentDb.DocumentExtensions.DeserializeToDocument[T](JObject jobject) in /home/vsts/work/1/s/src/azureml-api/src/Common/DocumentDb/Serialization/DocumentExtensions.cs:line 114\n   at Microsoft.MachineLearning.Common.DocumentDb.DocumentDbStore`2.GetDocumentAsync(String partitionKey, String documentId, Boolean includeDeleted) in /home/vsts/work/1/s/src/azureml-api/src/Common/DocumentDb/DocumentDbStore.cs:line 119\n   at Microsoft.MachineLearning.Execution.EntryPoints.Api.Controllers.ExecutionController.GetStateFromRunDocument(Guid subscriptionId, String resourceGroupName, String workspaceName, String experimentName, String runId) in /home/vsts/work/1/s/src/azureml-api/src/Execution/EntryPoints/Api/Controllers/ExecutionController.cs:line 647\n   at Microsoft.MachineLearning.Execution.EntryPoints.Api.Controllers.ExecutionController.CancelRun(Guid subscriptionId, String resourceGroupName, String workspaceName, String experimentName, RunDetails runDetails, RunStatus finalStatus) in /home/vsts/work/1/s/src/azureml-api/src/Execution/EntryPoints/Api/Controllers/ExecutionController.cs:line 471\n   at lambda_method(Closure , Object )\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()",
      "innerException": {
        "type": "System.ArgumentException",
        "message": "Requested value 'BatchAI' was not found.",
        "stackTrace": "   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)\n   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)",
        "innerException": null,
        "data": {},
        "errorResponse": null
      },
      "data": {},
      "errorResponse": null
    }
  },
  "correlation": {
    "operation": "13e0cdcffef389438ef76d1ffca1cb26",
    "request": "2Uoo8hQnXUI="
  },
  "environment": "canadacentral",
  "location": "canadacentral",
  "time": "2019-12-14T09:00:29.2331764+00:00"
}

I tried multiple times and the error is the same. Do someone know how to solve this problem?

Also, Is there a channel to get support for AML issue?

**Comment by YutongTie-MSFT** [comment]
@yuzhms Hi, could you please share which Azure Machine Learning product you are using? Thanks.

**Comment by yuzhms** [comment]
> @yuzhms Hi, could you please share which Azure Machine Learning product you are using? Thanks.

I'm not sure what's the product name I'm using, maybe Machine Learning under AI + MACHINE LEARNING ?
The aml workspace name is canadav100ws.
 Actually my Microsoft alias is v-yuzu, can you contact me directly on Teams? Thanks.

**Comment by yuzhms** [comment]
Anyone can help to solve this bug? The job is still running and wasting nodes.

**Comment by DebFro** [comment]
@yuzhms @YutongTie-MSFT This issue has been escalated to our engineering team for further investigation.

**Comment by jwang98052** [comment]
This was an old bug. It has has already been fixed and deployed to all prod regions.

**Comment by YutongTie-MSFT** [comment]
@yuzhms 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.

**Comment by m-r-tanha** [comment]
I need help when I want to open python in "Microsoft Azure Machine Learning Studio (classic)", the below error appears:
{"Error":{"Code":"ServiceError","Message":"InternalServerError","Target":null,"Details":[],"InnerError":null,"DebugInfo":null}}

**Comment by YutongTie-MSFT** [comment]
@m-r-tanha Hi, could you please open a new issue for this? This thread is outdated. Thanks.
