### ISSUE TITLE
S3 should be removed

### ISSUE THREAD

**Issue by algattik** [Azure/MachineLearningNotebooks#701]
In the doc for python_script_path: `The path to the python script in the DBFS or S3.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca726023-be45-d53f-b6b6-d8743c25e3b2
* Version Independent ID: bf659a77-735f-15ad-4dcd-a8dff635a4b5
* Content: [azureml.pipeline.steps.databricks_step.DatabricksStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.databricksstep?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.DatabricksStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.DatabricksStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@algattik 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by vmagelo** [comment]
We updated the docs. Changes will appear in next SDK release in approx two weeks.
