### ISSUE TITLE
Multi-tenant situations

### ISSUE THREAD

**Issue by mattc-eostar** [Azure/MachineLearningNotebooks#702]
What is the recommended plan of attack when it comes to solving a specific problem for multiple customers, which results in multiple versions of the same model that is specific for each customer?

Would I just create a separate training and scoring experiment for each customer? Where is this managed?

We would also like to be able to do the retraining and model updates within ADF. Would this have to be done in a custom activity where I loop through my customers and update the corresponding models?

Thank you!

**Comment by YutongTie-MSFT** [comment]
@mattc-eostar Hi Mathew, thanks for reaching out to us here. Could you please share more details about which product you are targeting for your question? Thanks a lot!

**Comment by mattc-eostar** [comment]
This is a question that would pertain to Azure Data Factory or Azure Machine Learning service.

What is the proper approach to handle multiple tenants within these environments? When creating an AzML pipeline, is there a best practice to keep our customers' specific models separated? We may want to set up a pipeline that takes different customers' data specific to them, and then create and track a different model for each customer. Is this possible with a single agnostic pipeline, or would I need to create a new pipeline for each customer?

We deal with customers in the same industry, but it would not make sense to create one general model for all customers since they all operate in different niches within that industry.

**Comment by dkmiller** [comment]
In these scenarios, it's recommended to use a single pipeline and scoring script, which is run in parallel against tenant data to produce many per-tenant models. We have an accelerator repo for this very use case:

https://github.com/microsoft/solution-accelerator-many-models/

**Comment by mattc-eostar** [comment]
I will take a look. Thank you!
