### ISSUE TITLE
Virtual Networks

### ISSUE THREAD

**Issue by tigerhive** [Azure/MachineLearningNotebooks#706]
Hi.
Is it possible to deploy a container with a model to a VNet?
Thanks
Mike

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135107d5-83c1-5358-ac71-12456ff76a15
* Version Independent ID: 11398512-1226-8fa9-4be2-5c379d8aca62
* Content: [azureml.core.webservice.AciWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-core/azureml.core.webservice.aciwebservice?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.AciWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.webservice.AciWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@tigerhive 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by aashishb** [comment]
Please check this https://docs.microsoft.com/en-us/azure/machine-learning/how-to-enable-virtual-network#use-azure-container-instances-aci
