### ISSUE TITLE
Docker Image Layer optimization

### ISSUE THREAD

**Issue by derdaele** [Azure/MachineLearningNotebooks#71]
Hello,

When I'm using the SDK to create a docker image. The model is copied before installing the conda environment. this means that when only the model is changing, the storage for the environment will be duplicated in the docker registry. 
```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
70c7ed31b44c        5 minutes ago       /bin/sh -c #(nop)  CMD ["supervisord" "-c" "…   0B
<missing>           5 minutes ago       /bin/sh -c pip --no-cache-dir install -r /va…   1.28MB
<missing>           5 minutes ago       /bin/sh -c conda env update --name=root -f /…   759MB               Environment installation
<missing>           8 minutes ago       /bin/sh -c #(nop) COPY dir:1fce004162580bc9b…   1.01MB              Model copy
<missing>           4 weeks ago         |1 PYTHON_VERSION=3.5.* /bin/sh -c chmod 755…   59B
```

I'm wasting 759MB (213MB when compressed) for each model whereas it could be shared if the environment installation layer is done before copying the model. 

Thanks a lot!

**Comment by rastala** [comment]
Thanks for your feedback, this is very good observation! I passed it to our engineering team.

**Comment by rastala** [comment]
We've added support for custom docker images, which should help mitigate this issue.
