### ISSUE TITLE
dataset.to_path() unsupported linux distribution

### ISSUE THREAD

**Issue by jmwoloso** [Azure/MachineLearningNotebooks#713]
Running `dataset.to_path()` on my local machine throws:

`NotImplementedError: Unsupported Linux distribution linuxmint 19.1`

**Comment by MayMSFT** [comment]
Hi Jason

Sorry for this. As per the error message suggests, dataset class is not supported by your Linux distribution. For Linux users, Dataset class is only supported on the following distributions: Red Hat Enterprise Linux, Ubuntu, Fedora, and CentOS.

**Comment by YutongTie-MSFT** [comment]
@jmwoloso 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.

**Comment by jmwoloso** [comment]
@YutongTie-MSFT @MayMSFT  Hi, Is there a fix planned for this? My distro is built on top of Ubuntu, so not sure why it shouldn't also work on my distro?

**Comment by MayMSFT** [comment]
we only support the following version of the distros:
Ubuntu: 14, 16, 18
Debian: 8, 9
RHEL: 7
Fedora: 27, 28
CentOS: 7

NO plan to add more support in the near future.

**Comment by jmwoloso** [comment]
But Mint is based on Ubuntu 18.04...

**Comment by epa095** [comment]
@jmwoloso I run ubuntu 19.10, which is also not supported. But I can trick it to work by just lying to the dotnetcore2 code about what distro I am running. I add the following at the top of my code, *before* any azure imports. 

```python
from dotnetcore2 import runtime
runtime.version = ("18", "10", "0")
```

**Comment by anliakho2** [comment]
you can also add support to any new linux distribution manually by ensuring that dotnetcore runtime could be ran.
Please refer to https://docs.microsoft.com/en-us/dotnet/core/install/linux for the guide for your distro
And then make sure that you install **dotnet-runtime-2.1** 
This should unblock you.
