### ISSUE TITLE
version argument / download method

### ISSUE THREAD

**Issue by cbertolasio** [Azure/MachineLearningNotebooks#719]
Maybe this document should include what version of the model is downloaded when multiple versions exists?  I think I figured out through trial and error that if I omit the version in the ctor, then the latest version is what is downloaded - but why not talk about the default behavior in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d33267-fb2b-bc8a-1b61-50122b944dd1
* Version Independent ID: 17c92047-89c8-0881-6d9f-235f50a2d5af
* Content: [azureml.core.model.Model class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@cbertolasio 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
We updated the docs to clarify. Changes will appear in next SDK release in approx two weeks.
