### ISSUE TITLE
How to convert an automl model to onnx and deploy on IoT Edge?

### ISSUE THREAD

**Issue by elepherai** [Azure/MachineLearningNotebooks#720]

**Comment by ram-msft** [comment]
As long as you include " 
,
                             enable_onnx_compatible_models=True
"

in your autoML config it should emit an ONNX model you can use.
Please follow the below notebook for onnx conversion.
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb

**Comment by elepherai** [comment]
It works. Thank you very much.
