### ISSUE TITLE
Environment.from_existing_conda_environment doesnt seem to work as expected

### ISSUE THREAD

**Issue by cbertolasio** [Azure/MachineLearningNotebooks#721]
While running conda and jupyter notebook locally, when I try to create an environment from an existing conda environment, I get the error listed below.
#### code that I am running:
`myenv = Environment.from_existing_conda_environment(name="myenv", conda_environment_name="azureenv")`

conda env list returns base and azureenv.  azureenv is the environment that I created using the previous guidance found in ["Setup dev environment"](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-environment) .  azureenv is a valid conda environment on my local windows 10 pc with python 3.6.5, azureml-sdk 1.0.81, sklearn 0.20.3, and spaCy.  Nothing special.

Maybe I am using the method incorrectly?
#### Error:

> ---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-58-7f420d272e85> in <module>
----> 1 myenv = Environment.from_existing_conda_environment("myenv", "azureenv")

C:\ProgramData\Anaconda3\envs\azureenv\lib\site-packages\azureml\core\environment.py in from_existing_conda_environment(name, conda_environment_name)
    630         """  # noqa: E501
    631         env = None
--> 632         if Environment._check_conda_installation() and Environment._check_conda_env_existance(conda_environment_name):
    633             try:
    634                 print("Exporting conda specifications for " +

C:\ProgramData\Anaconda3\envs\azureenv\lib\site-packages\azureml\core\environment.py in _check_conda_installation()
    885         try:
    886             conda_version_cmd = ["conda", "--version"]
--> 887             conda_version = subprocess.check_output(conda_version_cmd).decode("UTF-8").replace("conda", "").strip()
    888 
    889             from distutils.version import LooseVersion

C:\ProgramData\Anaconda3\envs\azureenv\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 
    338 

C:\ProgramData\Anaconda3\envs\azureenv\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    401         kwargs['stdin'] = PIPE
    402 
--> 403     with Popen(*popenargs, **kwargs) as process:
    404         try:
    405             stdout, stderr = process.communicate(input, timeout=timeout)

C:\ProgramData\Anaconda3\envs\azureenv\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

C:\ProgramData\Anaconda3\envs\azureenv\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df539276-e09d-1506-6011-3cec6af37404
* Version Independent ID: 65d38884-9aa1-6b01-f44f-15ec1d7591a8
* Content: [azureml.core.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment%28class%29?view=azure-ml-py#from-existing-conda-environment-name--conda-environment-name-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Environment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@cbertolasio Hi customer, sorry for the delay. Are you still suffering this issue now?

**Comment by vizhur** [comment]
@cbertolasio  what is the client version installed in your environment? The bug fix was shipped with 1.0.79 
https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes#2019-12-09
