### ISSUE TITLE
random_split needs better explanations

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#722]
random_split() should explain:
- Does the 'percentage' parameter (number between 0.0 and 1.0) apply to the first or the second returned Dataset?
If I specify 0.2, will that 20% dataset be split for the first or the second returned Dataset?
If I specify 0.9, will that 90% dataset be split for the first or the second returned Dataset?

After investigating by converting to a ScikitLearn DataFrame, it looks like the specified percentage will be applied to the first returned Dataset. This should be explained in the doc/reference. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d7a9417-1b43-e707-b546-8eaa37a31e6d
* Version Independent ID: 1d9554bd-9be0-a026-f6ce-5477d51e3e9e
* Content: [azureml.data.TabularDataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.tabulardataset?view=azure-ml-py#random-split-percentage--seed-none-)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.data.TabularDataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.data.TabularDataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@CESARDELATORRE 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
We updated the docs. Changes will appear in next SDK release in approx two weeks.

**Comment by j-martens** [comment]
#please-close
