### ISSUE TITLE
package starting with "python*" will fail to be loaded. 

### ISSUE THREAD

**Issue by Masutani** [Azure/MachineLearningNotebooks#726]
The line
 conda_dep.add_conda_package("pythonnet")

cause following error because the code recognize the package name includes python version.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\Users\masut\source\repos\DragonBall\Experiment\PreMainPy\amlrun2.py in 
      5 conda_dep = CondaDependencies()
      6 conda_dep.add_channel("conda-forge")
----&gt; 7 conda_dep.add_conda_package("pythonnet")

~\Anaconda3\envs\myenv\lib\site-packages\azureml\core\conda_dependencies.py in add_conda_package(self, conda_package)
    461                 if conda_package.startswith(PYTHON_PREFIX):
    462                     python_version = self._get_version(conda_package)
--&gt; 463                     self.set_python_version(python_version)
    464                 else:
    465                     self._conda_dependencies[PACKAGES].append(conda_package)

~\Anaconda3\envs\myenv\lib\site-packages\azureml\core\conda_dependencies.py in set_python_version(self, version)
    418                 if self._python_version != version:
    419                     # Doing an inplace update to preserve the comment above this field in the file.
--&gt; 420                     self._conda_dependencies[PACKAGES][index] = PYTHON_PREFIX + '=' + version
    421             else:
    422                 self._conda_dependencies[PACKAGES].append(PYTHON_PREFIX + '=' + version)

TypeError: can only concatenate str (not "NoneType") to str

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bb6e18dd-c5d9-02dd-41ee-f12dc8152a24
* Version Independent ID: 8db0f517-4578-e32c-3162-cd95635a0dc3
* Content: [azureml.core.conda_dependencies.CondaDependencies class - Azure Machine Learning Python](https://docs.microsoft.com/ja-jp/python/api/azureml-core/azureml.core.conda_dependencies.condadependencies#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.conda_dependencies.CondaDependencies.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@Masutani 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vizhur** [comment]
Thanks for reporting the issue. The workaround until the fix is out could be to instantiate CondaDependencies from a yaml file

**Comment by j-martens** [comment]
@vmagelo

**Comment by Masutani** [comment]
Thank you for your response, 
I discussed in stackoverflow and got similar workarounds :
https://stackoverflow.com/questions/59767816/azure-machine-learning-add-conda-package-will-fail-when-the-package-has-name-sta/59823050#59823050
