### ISSUE TITLE
Model_explainability is not working

### ISSUE THREAD

**Issue by ktebbe** [Azure/MachineLearningNotebooks#727]
I turned `model_explainability=True` in `AutoMLConfig` (for a regression) and got all of these error messages:
![image](https://user-images.githubusercontent.com/12629836/71933228-a0600680-316f-11ea-81bf-3c0c13f7852d.png)

**Comment by gaugup** [comment]
What is the version of azureml-train-automl in your python environment?

**Comment by imatiach-msft** [comment]
this is just an info message, I've subsequently suppressed it and changed it to a debug message:

https://github.com/interpretml/interpret-community/pull/148

**Comment by ram-msft** [comment]
@ktebbe We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
