### ISSUE TITLE
azureml.core.datastore class thread safety

### ISSUE THREAD

**Issue by lucas95123** [Azure/MachineLearningNotebooks#728]
I wonder if it is safe to use the same datastore object across different threads. so I have different threads that will access the same datastore object to register and unregister datastores of a workspace, do I need to add lock before accessing the shared datastore?

**Comment by lostmygithubaccount** [comment]
Hi Lucas,

Why do you need to register and unregister datastores on different threads? This does not fit our expected usage of datastores.

**Comment by DebFro** [comment]
Thank you for reaching out to us.  We did not receive a response to our last message, so will close this issue for now. Should you need further assistance please re-open.
