### ISSUE TITLE
Notebook for HyperDrive tuning is outdated. Uses HyperDriveRunConfig, should use HyperDriveConfig

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#729]
The Notebook for HyperDrive tuning is outdated. Uses HyperDriveRunConfig, should use HyperDriveConfig:

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/scikit-learn/training/train-hyperparameter-tune-deploy-with-sklearn/train-hyperparameter-tune-deploy-with-sklearn.ipynb

**Comment by YutongTie-MSFT** [comment]
@CESARDELATORRE 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
