### ISSUE TITLE
Mssing parameter definition for preprocess

### ISSUE THREAD

**Issue by davecatt** [Azure/MachineLearningNotebooks#732]
The parameter is used in the Python example but not described in the reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e822a65-17a8-2a1b-a62a-c143405481ff
* Version Independent ID: e632817d-3e64-d8e6-d1bb-5ee0165856f2
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@davecatt 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by PeterCLu** [comment]
#assign:@vmagelo

**Comment by PeterCLu** [comment]
#assign:@vmagelo

**Comment by vmagelo** [comment]
The sample was updated and the change will go live with next sdk release in a few weeks. Thanks for pointing this out.
