### ISSUE TITLE
Data Labelling Projects .BMP and .PNG files do not load

### ISSUE THREAD

**Issue by iannovic** [Azure/MachineLearningNotebooks#733]
.BMP and .PNG files do not load in either safari or google chrome when trying to start a labelling task within a label project (bounding box)

**Comment by ranvijaykumar** [comment]
@iannovic Thanks for reporting this issue. We are currently investigating and will update you shortly.

**Comment by lostmygithubaccount** [comment]
this has been fixed, please reopen if seen again
