### ISSUE TITLE
BUG: source_directory in InferenceConfig ignores .amlignore

### ISSUE THREAD

**Issue by maknotavailable** [Azure/MachineLearningNotebooks#743]
When deploying an inference script, before the Model.Deploy() step, the following snippet ignores the .amlignore file:
```
InferenceConfig(entry_script='code/infer.py',
                                   source_directory='.',
                                   environment=environment)
```
It takes all files in the root directory ('.' = root of the repository), even the files that are added to the .gitignore or .amlignore. In my case the problem is a folder that is +2GB in size. This reduces the speed of the deployment drastically and causes timeout errors.

**Comment by YutongTie-MSFT** [comment]
@maknotavailable 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by maknotavailable** [comment]
It seems that .git/ folder is not ignored unless explicitly added to the `.amlignore` file. Any chance this can be re-visited? The current .git folder I am working with is >300MB, and was causing the issues stated above.

**Comment by FlorianPydde** [comment]
Any update on this issue ? I am facing the same problem. I am using an .amlignore when deploying my  scripts to an ACI but it seems like the the service doesn't take into account the amlignore when creating the instance

**Comment by maknotavailable** [comment]
It seems that for training deployments, the .amlignore or .gitignore is taken into account. But not for deploying a service...This is filling up the container registry and resulting in very slow deployments. Any update on this issue?

**Comment by nonstoptimm** [comment]
Hi, I just found this ticket as I am experiencing the same issue. Have you been able to find a solution for this, @YutongTie-MSFT ? Already checked back with @maknotavailable 
Thanks!

**Comment by salilbapat** [comment]
Hi, this issue still exists. A tracking backlog item has been created, but not yet been scheduled. I will update the thread when this gets scheduled
