### ISSUE TITLE
Alternatives to include local source files/modules/packages

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#744]
I'm trying to find a better way to include local source files, and make them available to the step in a remote execution other than copying the source folder inside the step folder before running the step. 

The current hack does the following: 
1. Locate `./src` folder that contains all the custom modules that are project related
2. Copy the `./src` folder inside the step folder
3. Submit the step as a PythonStepScript

I'm trying to move away from this hacky solution. The aim of this exercise would be to abstract away all the project related modules outside the script, but we're not at a stage where we have enough modules to publish a package (or DevOps artifacts), nor maintain one.  

Any suggestions on that end?

**Comment by vizhur** [comment]
you can build a wheel and register it with your workspace. Then you can reference to it as a package. Please see
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py#add-private-pip-wheel-workspace--file-path--exist-ok-false-
Maybe not the best solution if you iterate on the ./src too much, but can be automated even in the script you are running on client to submit the job

**Comment by YutongTie-MSFT** [comment]
@jadhosn 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
