### ISSUE TITLE
SDK installation on databricks

### ISSUE THREAD

**Issue by yueguoguo** [Azure/MachineLearningNotebooks#75]
> NOTE: Some packages like psutil upgrade libs that can cause a conflict, please install such packages by freezing lib version. Eg. "pstuil cryptography==1.5 pyopenssl==16.0.0 ipython=2.2.0" to avoid install error. This issue is related to Databricks and not related to AML SDK.

I tried installing `psutil` (there is a typo. See my PR #74) with the package dependencies as well as their versions, on my Databricks cluster, but "attaching" process just hangs there forever. I am wondering if I am doing the correct thing. 

Appreciate any advice.

**Comment by rastala** [comment]
Try installing using ```pip install azureml-sdk[databricks]```. That should pin the dependent package versions.

**Comment by yueguoguo** [comment]
@rastala I did try installing `azureml-sdk[databricks]` and that gave me the error as follows

Error: java.lang.RuntimeException: Installation failed with message: Traceback (most recent call last): File "/databricks/python/bin/pip", line 7, in <module> from pip._internal import main File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/__init__.py", line 42, in <module> from pip._internal import cmdoptions File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/cmdoptions.py", line 16, in <module> from pip._internal.index import ( File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/index.py", line 15, in <module> from pip._vendor import html5lib, requests, six File "/databricks/python3/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 86, in <module> from pip._vendor.urllib3.contrib import pyopenssl File "/databricks/python3/lib/python3.5/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module> import OpenSSL.SSL File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module> from OpenSSL import rand, crypto, SSL File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/SSL.py", line 124, in <module> SSL_ST_INIT = _lib.SSL_ST_INIT AttributeError: module 'lib' has no attribute 'SSL_ST_INIT' Traceback (most recent call last): File "/databricks/python/bin/pip", line 7, in <module> from pip._internal import main File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/__init__.py", line 42, in <module> from pip._internal import cmdoptions File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/cmdoptions.py", line 16, in <module> from pip._internal.index import ( File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/index.py", line 15, in <module> from pip._vendor import html5lib, requests, six File "/databricks/python3/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 86, in <module> from pip._vendor.urllib3.contrib import pyopenssl File "/databricks/python3/lib/python3.5/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module> import OpenSSL.SSL File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module> from OpenSSL import rand, crypto, SSL File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/SSL.py", line 124, in <module> SSL_ST_INIT = _lib.SSL_ST_INIT AttributeError: module 'lib' has no attribute 'SSL_ST_INIT' Traceback (most recent call last): File "/databricks/python/bin/pip", line 7, in <module> from pip._internal import main File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/__init__.py", line 42, in <module> from pip._internal import cmdoptions File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/cmdoptions.py", line 16, in <module> from pip._internal.index import ( File "/databricks/python3/lib/python3.5/site-packages/pip/_internal/index.py", line 15, in <module> from pip._vendor import html5lib, requests, six File "/databricks/python3/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 86, in <module> from pip._vendor.urllib3.contrib import pyopenssl File "/databricks/python3/lib/python3.5/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module> import OpenSSL.SSL File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module> from OpenSSL import rand, crypto, SSL File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module> from OpenSSL._util import ( File "/databricks/python3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module> from cryptography.hazmat.bindings.openssl.binding import Binding File "/databricks/python3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 157, in <module> Binding.init_static_locks() File "/databricks/python3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 138, in init_static_locks cls._ensure_ffi_initialized() File "/databricks/python3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 125, in _ensure_ffi_initialized cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES) File "/databricks/python3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 85, in build_conditional_library if not getattr(lib, condition): AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCRYPT'

**Comment by adyada** [comment]
I think the steps to resolve this are:

1) Remove all the attached libraries from the cluster
2) Restart the cluster, which will reset the cluster to its default packages. 
3) Attach azureml-sdk[databricks] again.

**Comment by adyada** [comment]
What cluster version are you using? Please try to use cluster version 4.3

**Comment by emthomas** [comment]
>           What cluster version are you using? Please try to use cluster version 4.3

Thanks! That worked! now on to deploying a spark ml model!

**Comment by michalmar** [comment]
I have Databricks non-premium cluster and I dont see ML engine below 5.0 - how can I used 4.x on non-premium?

**Comment by adyada** [comment]
databricks 5.0 runtimes should also work, just choose the non-preview ones.

**Comment by kumaranpravin** [comment]
Thanks that worked for me as well. 
But if i try to use the dataprep package, i get no module found error. But i could able to import azureml.core.

![image](https://user-images.githubusercontent.com/29369204/49787543-f0e51480-fd61-11e8-87f2-a701c8b0cc98.png)

**Comment by Simon-Bru** [comment]
I'm having the exact same stacktrace when I try to install azureml-sdk on my databricks cluster. 
Here's my configuration: 
- Standard mode cluster
- Databricks 5.3
- Python 3
- Worker_type: Standard_DS3_V2
- Driver type: Standard_DS3_V2

Thank you for your help

**Comment by rodneyjoyce** [comment]
> Thanks that worked for me as well.
> But if i try to use the dataprep package, i get no module found error. But i could able to import azureml.core.
> 
> ![image](https://user-images.githubusercontent.com/29369204/49787543-f0e51480-fd61-11e8-87f2-a701c8b0cc98.png)

Did you get this working in the end? I was curious as to using the DataPrep SDK on Databricks - it's another API to learn...
