### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by wmpauli** [Azure/MachineLearningNotebooks#750]
The readme file in the following folder contains a dead link:
https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/azure-databricks

dead link:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/azure-databricks/Databricks_AMLSDK_1-4_6.dbc

The dbc archive is missing.

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by dem108** [comment]
@YutongTie-MSFT This dead link is still not fixed. Can anyone fix this? If we're no longer providing .dbc, the reference to it should be eliminated.

**Comment by GiftA-MSFT** [comment]
@DebFro can you please update **DBC link** under **Single File** in this [document](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/azure-databricks)? Thanks.

**Comment by jpe316** [comment]
notebooks have been removed
