### ISSUE TITLE
AttributeError: '_OfflineRun' object has no attribute 'experiment'

### ISSUE THREAD

**Issue by alla15747** [Azure/MachineLearningNotebooks#751]
run = Run.get_context()

print(experiment.name)
print(run.experiment.name)
print(run.experiment.workspace.name)
print(run.id)
run.complete()

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by GiftA-MSFT** [comment]
Closing this thread since its outdated. Please comment below if you need further assistance. Thanks.

**Comment by CristinaOviedo** [comment]
I have the same problem too

**Comment by kabyabasu** [comment]
Facing the same issue

**Comment by nikhil-shaw** [comment]
Facing same issue

**Comment by Ioannis-Mykelos** [comment]
I have the same error:

`AttributeError: '_OfflineRun' object has no attribute 'experiment'`

`- azureml-core==1.44.0`
I want to get my secret from my keyvault  and I am using the following code in my pipeline:
`from azureml.core import Run`
`run = Run.get_context()`
`ws = run.experiment.workspace`
