### ISSUE TITLE
2 directories should be moved for more clarity

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#753]
This directory : MachineLearningNotebooks/how-to-use-azureml/training-with-deep-learning/how-to-use-estimator/
I think should be relocated in training because it has nothing to do with deep learning... or at least available in both locations (trainig and training-with-deep-learning). Like there is using-environments in `/training`, there could/should be `using-estimators`.
In fact, I would also merge `training-with-deep-learning` to `ml-frameworks`, so that everything ML frameworks can essentially be found in a single place.

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by lostmygithubaccount** [comment]
@omartin2010 we're working on restructuring the examples - please reach out if you'd like to learn more
