### ISSUE TITLE
DBFS Datastore has no return type

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/MachineLearningNotebooks#754]
DBFS Datastore has no linked return type -&gt; cannot easily find the methods on it 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72d4eb-b5c9-c98d-3305-be3c00e937a2
* Version Independent ID: 5576d10f-9dad-b5cd-7032-07ce54f17b68
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#register-dbfs-workspace--datastore-name-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by lostmygithubaccount** [comment]
wrong link - https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#register-dbfs-workspace--datastore-name-

**Comment by yikei** [comment]
Thanks for raising this, the documentation is being fixed and will be refreshed with the next update.

**Comment by j-martens** [comment]
Thanks so much. We will now proceed to close this issue. You should see this doc live in 10 days. Thanks!
