### ISSUE TITLE
Document Origin of DataPath

### ISSUE THREAD

**Issue by tkawchak** [Azure/MachineLearningNotebooks#756]
The DataPath object used in the example is not imported or created in this example.  This documentation should show where this Object comes from.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 091afd7e-72ca-a384-01db-4da4d40a6734
* Version Independent ID: 0f3783bf-ab1f-f0d6-08f3-90becae914e8
* Content: [azureml.data.dataset_factory.FileDatasetFactory class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_factory.filedatasetfactory?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.dataset_factory.FileDatasetFactory.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.dataset_factory.FileDatasetFactory.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by tkawchak** [comment]
Actually, it looks like this DataPath should just be omitted.

**Comment by swanderz** [comment]
@MayMSFT remember when we asked for more guidance on this? Or just never mention it at all?

**Comment by MayMSFT** [comment]
DataPath is not required. The following is sufficient. Will update the documentation. Sorry for the confusion. 
`from azureml.core import Dataset, Datastore

   # create file dataset from files in datastore
   datastore = Datastore.get(workspace, 'workspaceblobstore')
   datastore_path = [
       (datastore, 'animals/dog/1.jpg'),
       (datastore, 'animals/dog/2.jpg'),
       (datastore, 'animals/dog/*.jpg')
   ]
   file_dataset = Dataset.File.from_files(path=datastore_path)
`

**Comment by vmagelo** [comment]
DataPath removed change appearing in live docs.

**Comment by j-martens** [comment]
Thanks so much. We will now proceed to close this issue.
