### ISSUE TITLE
Use Model.deploy(overwrite=True)

### ISSUE THREAD

**Issue by algattik** [Azure/MachineLearningNotebooks#757]
Instead of 

```
   # Remove any existing service under the same name.
   try:
       Webservice(ws, service_name).delete()
```

it's probably better to use Model.deploy(overwrite=True)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66024d40-0984-d107-cc99-a9175af6bf32
* Version Independent ID: bde95ec3-65f9-6aae-53ee-77ab01198951
* Content: [azureml.core.webservice.aci.AciWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-core/azureml.core.webservice.aci.aciwebservice?view=azure-ml-py#deploy-configuration-cpu-cores-none--memory-gb-none--tags-none--properties-none--description-none--location-none--auth-enabled-none--ssl-enabled-none--enable-app-insights-none--ssl-cert-pem-file-none--ssl-key-pem-file-none--ssl-cname-none--dns-name-label-none--)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.
