### ISSUE TITLE
If Dataset.register() is deprecated? Where can i find info on the `visible` param?

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#762]
It's not in `azureml.data.abstract_dataset.AbstractDataset.register` but `azureml.core.dataset.register` is deprecated? When I call `Dataset.register()` what class am I using anyway?? @MayMSFT 

`help(Dataset.register)`
```
Help on function register in module azureml.core.dataset:

register(self, workspace, name, description=None, tags=None, visible=True, exist_ok=False, update_if_exist=False)
    Register the Dataset in the workspace, making it available to other users of the workspace.
    
    .. note::
    
        This method is deprecated. Use :meth:`azureml.data.abstract_dataset.AbstractDataset.register` instead.
        For more information, see https://aka.ms/dataset-deprecation.
    
    :param workspace: The AzureML workspace in which the Dataset is to be registered.
    :type workspace: azureml.core.Workspace
    :param name: The name of the Dataset in the workspace.
    :type name: str
    :param description: A description of the Dataset.
    :type description: str, optional
    :param tags: Tags to associate with the Dataset.
    :type tags: dict[str,str], optional
    :param visible: Indicates whether the Dataset is visible in the UI.
        If False, then the Dataset is hidden in the UI and available via SDK.
    :type visible: bool, optional
    :param exist_ok: If True, the method returns the Dataset if it already exists in the given workspace,
        else error.
    :type exist_ok: bool, optional
    :param update_if_exist: If ``exist_ok`` is True and ``update_if_exist`` is True, this method will update
        the definition and return the updated Dataset.
    :type update_if_exist: bool, optional
    :return: A registered Dataset object in the workspace.
    :rtype: azureml.core.dataset.Dataset
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06be0567-a5f7-21d0-6dac-8edeefe68980
* Version Independent ID: 4c06aaf8-fce2-6df2-0386-51a7472957fb
* Content: [azureml.data.abstract_dataset.AbstractDataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py#register-workspace--name--description-none--tags-none--create-new-version-false-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.abstract_dataset.AbstractDataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.abstract_dataset.AbstractDataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
in the methods table of [contents of this page](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py#register-workspace--name--description-none--tags-none--visible-true--exist-ok-false--update-if-exist-false-), it says the method is deprecated
![image](https://user-images.githubusercontent.com/8158673/73899035-3440f300-4840-11ea-9e87-30fbfa62412a.png)
However it is linked directly from [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets#register-datasets)
![image](https://user-images.githubusercontent.com/8158673/73899069-4e7ad100-4840-11ea-821a-3e7e38b29f05.png)

**Comment by MayMSFT** [comment]
created a PR to fix the redirection on doc article (may take a day to live). It should redirect to https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py#register-workspace--name--description-none--tags-none--create-new-version-false-

Dataset.register is the deprecated method.

**Comment by nibaccam** [comment]
The documentation has been updated. We will now proceed to close this thread. 
#please-close

**Comment by swanderz** [comment]
@MayMSFT shouldn't the updated documentation include the `is_visible` parameter? I don't see it in the link you included

**Comment by MayMSFT** [comment]
visible parameter is not enabled for the FileDataset, TabularDataset register method. Do you need this capability?

**Comment by PeterCLu** [comment]
Since it's been awhile since we last heard from you, I will proceed to close this issue. If you feel that your doc issue hasn't been resolved, please reopen an issue with additional details.
