### ISSUE TITLE
Logger (level info/debug) not showing in streamed driver log

### ISSUE THREAD

**Issue by maknotavailable** [Azure/MachineLearningNotebooks#764]
In my training script I initiate the logger as follows:
```
import logging
logger = logging.getLogger(__name__)
logging.basicConfig(format = '%(asctime)s - %(levelname)s - %(name)s -   %(message)s',
                    datefmt = '%m/%d/%Y %H:%M:%S',
                    level = logging.INFO)
```
However, when I use the logger, I am unable to see anything level INFO and below. Only WARNING level will show up.

Is there any way to allow for levels below WARNING to show up?

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by GiftA-MSFT** [comment]
Hello, please refer to this [document ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-debug-pipelines#logging-options-and-behavior) and [resource](https://docs.python.org/2/library/logging.html). Thanks.
