### ISSUE TITLE
estimator_entry_script_arguments not described in the parameters

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#768]
self explanatory...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d50b00a6-7dc4-a34e-3032-f7f7ad8d191a
* Version Independent ID: b10edb8b-1fe4-424b-3e1b-c8452a1f05f3
* Content: [azureml.pipeline.steps.EstimatorStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.estimatorstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.EstimatorStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.EstimatorStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks for reporting this. There was formatting issues in the docstring preventing parameters from rendering in HTML. The fix is in and will appear in next release in a few weeks.
