### ISSUE TITLE
Incomplete documentation for sending binary data

### ISSUE THREAD

**Issue by jmwoloso** [Azure/MachineLearningNotebooks#769]
Hi,

According to the docs [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where) in the "Binary data" section, it is unclear how we would use the `AMLRequest` class to send the binary data in the first place. Could you provide a snippet that covers that? It doesn't appear there is a class signature implemented for the `AMLRequest` class.

Here is the snippet I'm referencing:

```python
from azureml.contrib.services.aml_request import AMLRequest, rawhttp
from azureml.contrib.services.aml_response import AMLResponse


def init():
    print("This is init()")


@rawhttp
def run(request):
    print("This is run()")
    print("Request: [{0}]".format(request))
    if request.method == 'GET':
        # For this example, just return the URL for GETs.
        respBody = str.encode(request.full_path)
        return AMLResponse(respBody, 200)
    elif request.method == 'POST':
        reqBody = request.get_data(False)
        # For a real-world solution, you would load the data from reqBody
        # and send it to the model. Then return the response.

        # For demonstration purposes, this example just returns the posted data as the response.
        return AMLResponse(reqBody, 200)
    else:
        return AMLResponse("bad request", 500)
```

**Comment by GiftA-MSFT** [comment]
@j-martens and @Blackmist please can you look into this feedback? Thanks.

**Comment by Blackmist** [comment]
@jmwoloso thanks for the feedback on this.

The AMLRequest class isn't used to send data. It's a wrapper around the a Flask request object. It's there so the score.py can access the raw incoming request.

From the client side, there's no special class provided by the SDK for sending binary data. There's no standard format; you might use base64 encoded, BSON, or some other format. It might be a multi-part message or a single file. Even a zip file that needs to be unpacked before processing. That's up to you to decide and implement.

The AMLRequest in the SDK is just there to let you get the raw data sent to the service, and then (knowing what format it is sent in from the client,) do whatever processing on it before submitting it to the model.

Similarly, the AMLResponse is there to help create a response that is a bit more custom. It also is a wrapper around the Flask response object. You can inspect the code for both of them by looking at the Conda environment on your local machine. For example, on my machine the files for these two classes live at C:\Users\mylogin\AppData\Local\Continuum\anaconda3\envs\myenv\Lib\site-packages\azureml\contrib\services

I'll create a work item to add some basic info on this to the docs.

**Comment by jmwoloso** [comment]
Thanks for the update @Blackmist . After playing around with it for a while I was able to get everything working.

**Comment by KutayAcar** [comment]
@jmwoloso Hi, can you share how did you manage to get it working?
