### ISSUE TITLE
PythonScriptStep allow_reuse param doesn't hash script arguments?

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#771]
@sanpil @purnesh42H @rastala @yanrez  @rastala  perhaps we discussed this before, but I thought that script arguments were "hashed" based on #298  In the case of [the reprex here](https://github.com/swanderz/MachineLearningNotebooks/blob/script_arg_hash/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb), if for the `trainStep` I:
- set `allow_reuse=True`, and
- change the `--test` script arg.

The run will be reused even though the test arg has changed... though perhaps this is a feature not a bug? For our team, this slows our team down a lot and causes big headaches.

P.S. the convention of this notebook consistently re-assigning values to `source_directory` was an extra hoop for me to jump through to make this reprex.

**Comment by sanpil** [comment]
Investigating.

**Comment by alexkalita** [comment]
@swanderz This is fixed in the 1.1.0rc0 pre-release version of the pipepline packages.  You can run 'pip install azureml-sdk --upgrade --pre' to update to this version.
