### ISSUE TITLE
models registered under older sdk versions not usable in azureml.85

### ISSUE THREAD

**Issue by BillmanH** [Azure/MachineLearningNotebooks#772]
Steps to repro:

using a model that was built using 1.0.55, download and load the model. 
```
favorite_model = Model(
        ws, id=params['model_name']+":" + str(params['version']))
favorite_model.download(
        target_dir=f'../models/{params["model_name"]}', exist_ok=True)
model = pickle.load(
        open(f'../models/{params["model_name"]}/model.pkl', "rb"))
```
The error you will get:
```
ModuleNotFoundError                       Traceback (most recent call last)
 in 
     13         target_dir=f'../models/{pass_info["model_name"]}', exist_ok=True)
     14 model = pickle.load(
---> 15         open(f'../models/{pass_info["model_name"]}/model.pkl', "rb"))

ModuleNotFoundError: No module named 'automl.client.core.common.problem_info'
```

However a model trained in .85 will work fine in the same script. This is likely that the module was moved without providing for backwards compatibility. This also means that all previous models are lost.

**Comment by skasturi** [comment]
@BillmanH Thank you for reporting the issue. I understand the concern here and apologies. While we try as much as possible to be backward compatible overall with the top level APIs, some modules might break when adding new functionality; like in this case. 

That said, we recommend using the same version of the SDK that you have built the model with for inference. In this case, can you please try loading the model with 1.0.55 version of the SDK itself and let us know in case you face any issues? 

@rtanase @SKrupa

**Comment by BillmanH** [comment]
The model will load with `1.0.55`.  We are able to retrain all of our older models, but this will take time.   I think that `open` is pretty "top level", is there anything more "top level" than that. 
A couple of ideas that might help with this:
* document that newer versions of the API are not intended to be backwards compatible.
* Is there somewhere in the model object that I can get the SDK version that it was built in? This will help future teams as they can query the MLS and know ahead of times which ones won't be compatible. 

Thanks for the quick response.

**Comment by BillmanH** [comment]
Closing this out as the solution is just to re-train models using the newer SDK or revert back to the older.
