### ISSUE TITLE
"Reuse" always reads "No" in UI, even when set to True. Hyperdrive cannot be reused.

### ISSUE THREAD

**Issue by nemasobhani** [Azure/MachineLearningNotebooks#773]
The `allow_reuse` parameter for script steps defaults to **True**, yet in the machine learning portal it shows **No** under reuse. Clearly these steps are being reused due to the speed at which they are completed in successive runs, but this makes troubleshooting changes unnecessarily complex.

This [branch](https://github.com/nemasobhani/MachineLearningNotebooks/blob/pipeline_reuse_bug/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb) demonstrates the issue using a tutorial notebook from Azure MachineLearningNotebooks repo.

Also as a follow-up, why is it that `HyperDriveSteps` can never be reused even though it supports the parameter? This adds a considerable amount of downtime to development.

Thank you.

**Comment by swanderz** [comment]
@sanpil @yanrez @luzhang06 @rastala

**Comment by swatig007** [comment]
@sonnypark, Akshay Vasudev, can you please take a look

**Comment by sonnypark** [comment]
https://github.com/Azure/MachineLearningNotebooks/issues/740
Fix has been checked in and will be available on the next release (which will be next week).

**Comment by GiftA-MSFT** [comment]
@nemasobhani please let us know if the fix resolved your issue. Thanks.

**Comment by swanderz** [comment]
@GiftA-MSFT we're waiting for this fix to be included in a stable release which we've been told will happen by the end of the week.

**Comment by GiftA-MSFT** [comment]
@swanderz thanks for your feedback. I noticed sonnypark's comment was 28 days ago, so I assumed the fix must've been deployed by now.

**Comment by nemasobhani** [comment]
Fixed in SDK 1.1.5. Thank you!

**Comment by sonnypark** [comment]
took so long for this stable release. Thanks for your patience!
