### ISSUE TITLE
Markup gone bad

### ISSUE THREAD

**Issue by danielsc** [Azure/MachineLearningNotebooks#781]
Looks like the markup for examples is a bit out of proportion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caff87c4-10a9-130e-2457-afdb41e4c90b
* Version Independent ID: b60d47ab-31cf-6609-d6e3-84cf77538c1f
* Content: [azureml-mlflow package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-mlflow/?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-mlflow/index.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-mlflow/index.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks. Addressed with a checkin last week. Will appear live in next release.

**Comment by j-martens** [comment]
Thank you so much for your report. We'll now proceed to close this thread.
