### ISSUE TITLE
ERROR: Setup iteration failed: Unidentified error, check logs in portal / compute

### ISSUE THREAD

**Issue by rajibstats** [Azure/MachineLearningNotebooks#784]
import logging
import os
import time
from azureml.train.automl import AutoMLConfig

automl_settings = {
                "name": "my_automl".format(time.time()),
                "iteration_timeout_minutes": 5,
                "iterations": 10,
                "n_cross_validations": 5,
                "primary_metric": "accuracy",
                "preprocess": True,
                "max_concurrent_iterations": 8,
                "verbosity": logging.INFO
            }
automl_config = AutoMLConfig(task="classification",
                                #debug_log='automl_errors.log',
                                compute_target=compute_target,
                                run_configuration=conda_run_config,
                                X=X,
                                y=y,
                                #data_script = project_folder + "\\get_data.py",
                                **automl_settings,
                                    )
print("AutoML config created.")
experiment=Experiment(ws, 'my_exp')
remote_run = experiment.submit(automl_config, show_output=True)

##Getting error when trying to run the autoML through training cluster. But its running successfully via local run

**Comment by cartacioS** [comment]
Hello,

Can you verify that you are using this notebook as a template to create the remote compute_target?
Specifically the Create or Attach Existing AML Compute section.

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb

Thanks,
Sabina

**Comment by ram-msft** [comment]
Please upgrade the following package azureml-train-automl-runtime.
