### ISSUE TITLE
Databricks import error with databricks runtime 6.3, automl and pandas.

### ISSUE THREAD

**Issue by ttelfer** [Azure/MachineLearningNotebooks#785]
When installing the automl package on databricks the package installs an older version of pandas which makes using koalas/pandas unusable. 

ImportError Traceback (most recent call last)
in
1 from pyspark.sql import SparkSession
2 from pyspark.sql.types import StructType, StructField, StringType, DoubleType, TimestampType
----> 3 import databricks.koalas as ks
4 import pyspark.sql.functions as F
5 import json

/databricks/python/lib/python3.7/site-packages/databricks/koalas/init.py in
47 os.environ["ARROW_PRE_0_15_IPC_FORMAT"] = "1"
48
---> 49 from databricks.koalas.frame import DataFrame
50 from databricks.koalas.indexes import Index, MultiIndex
51 from databricks.koalas.series import Series

/databricks/python/lib/python3.7/site-packages/databricks/koalas/frame.py in
30
31 import numpy as np
---> 32 import pandas as pd
33 from pandas.api.types import is_list_like, is_dict_like
34 if LooseVersion(pd.version) >= LooseVersion('0.24'):

/databricks/python/lib/python3.7/site-packages/pandas/init.py in
40 import pandas.core.config_init
41
---> 42 from pandas.core.api import *
43 from pandas.core.sparse.api import *
44 from pandas.tseries.api import *

/databricks/python/lib/python3.7/site-packages/pandas/core/api.py in
8 from pandas.core.dtypes.missing import isna, isnull, notna, notnull
9 from pandas.core.arrays import Categorical
---> 10 from pandas.core.groupby.groupby import Grouper
11 from pandas.io.formats.format import set_eng_float_format
12 from pandas.core.index import (Index, CategoricalIndex, Int64Index,

/databricks/python/lib/python3.7/site-packages/pandas/core/groupby/init.py in
1 # flake8: noqa
----> 2 from pandas.core.groupby.groupby import (
3 Grouper, GroupBy, SeriesGroupBy, DataFrameGroupBy
4 )

/databricks/python/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in
47 CategoricalIndex, _ensure_index)
48 from pandas.core.arrays import ExtensionArray, Categorical
---> 49 from pandas.core.frame import DataFrame
50 from pandas.core.generic import NDFrame, _shared_docs
51 from pandas.core.internals import BlockManager, make_block

/databricks/python/lib/python3.7/site-packages/pandas/core/frame.py in
64
65
---> 66 from pandas.core.generic import NDFrame, _shared_docs
67 from pandas.core.index import (Index, MultiIndex, _ensure_index,
68 _ensure_index_from_sequences)

/databricks/python/lib/python3.7/site-packages/pandas/core/generic.py in
41 from pandas.core.indexes.datetimes import DatetimeIndex
42 from pandas.core.indexes.period import PeriodIndex, Period
---> 43 from pandas.core.internals import BlockManager
44 import pandas.core.algorithms as algos
45 import pandas.core.common as com

/databricks/python/lib/python3.7/site-packages/pandas/core/internals/init.py in
1 # -- coding: utf-8 --
----> 2 from .blocks import ( # noqa:F401
3 _block2d_to_blocknd, _factor_indexer, _block_shape, # io.pytables
4 _safe_reshape, # io.packers
5 make_block, # io.pytables, io.packers

/databricks/python/lib/python3.7/site-packages/pandas/core/internals/blocks.py in
9
10 from pandas._libs import internals as libinternals, lib, tslib, tslibs
---> 11 from pandas._libs.tslibs import Timedelta, conversion, is_null_datetimelike
12 import pandas.compat as compat
13 from pandas.compat import range, zip

ImportError: cannot import name 'Timedelta' from 'pandas._libs.tslibs' (/databricks/python/lib/python3.7/site-packages/pandas/_libs/tslibs/init.py)

**Comment by cartacioS** [comment]
Hello,

So sorry you've encountered this issue. Can you please try installing pandas==0.24.0 prior to installing azureml-sdk[automl]? Essentially we're trying to pin a working version of pandas. This might be a suitable workaround for the time being.

Thanks,
Sabina

**Comment by GiftA-MSFT** [comment]
@ttelfer please let us know if the suggested solution resolved your issue. Thanks.
