### ISSUE TITLE
Import Error - from azureml.core import Dataset  - ImportError: cannot import name 'Dataset'

### ISSUE THREAD

**Issue by andrewkinsella** [Azure/MachineLearningNotebooks#787]
The following sample notebook fails 
### img-classification-part1-training.ipynb

when running:

### from azureml.core import Dataset

from azureml.core import Dataset
from azureml.opendatasets import MNIST

data_folder = os.path.join(os.getcwd(), 'data')
os.makedirs(data_folder, exist_ok=True)

mnist_file_dataset = MNIST.get_file_dataset()
mnist_file_dataset.download(data_folder, overwrite=True)

mnist_file_dataset = mnist_file_dataset.register(workspace=ws,
                                                 name='mnist_opendataset',
                                                 description='training and test dataset',
                                                 create_new_version=True)

**Here is the error**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-ac2e91b46eec> in <module>
----> 1 from azureml.core import Dataset
      2 from azureml.opendatasets import MNIST
      3 
      4 data_folder = os.path.join(os.getcwd(), 'data')
      5 os.makedirs(data_folder, exist_ok=True)

ImportError: cannot import name 'Dataset'

reference: yml file:
name: img-classification-part1-training
dependencies:
- pip:
  - azureml-sdk
  - azureml-widgets
  - matplotlib
  - sklearn
  - pandas
  - azureml-opendatasets

Azure ML SDK Version:  1.0.17
Python 3.6 - AzureML

@microsoft
Please kindly investigate.
Many thanks :)

**Comment by swanderz** [comment]
@andrewkinsella, version `1.0.17` is from [almost a year ago](https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes#2019-02-25). During that time, the `Datasets` class has evolved significantly (for the better). Can you try upgrading the SDK to the newest version and trying again? @MayMSFT

**Comment by andrewkinsella** [comment]
> @andrewkinsella, version `1.0.17` is from [almost a year ago](https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes#2019-02-25). During that time, the `Datasets` class has evolved significantly (for the better). Can you try upgrading the SDK to the newest version and trying again? @MayMSFT

**Comment by andrewkinsella** [comment]
Thank you very much @swanderz 
I will try your recommendation.
