### ISSUE TITLE
Getting "ErrorResponseException" while executing DataReference code

### ISSUE THREAD

**Issue by Shipika** [Azure/MachineLearningNotebooks#789]
I have executed the above code  and I am getting an error 
ErrorResponseException: (UserError) Could not find datastore: &lt;azureml.data.azure_storage_datastore.azureblobdatastore object at 0x7f51b72d5390&gt;.

Here "workspaceblobstore" is common among all the workspaces still it is could not find this datastore. I have even tried with the other datastores, still getting the same error.

Also, when I execute "def_blob_store", it has given "&lt;azureml.data.azure_storage_datastore.AzureBlobDatastore at 0x7f51b72d5390&gt;" this location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b57ef22-d9c6-3066-9489-a368b354357a
* Version Independent ID: cffee3ba-8d7a-ce13-4975-825d8195081b
* Content: [azureml.data.data_reference.DataReference class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.data_reference.datareference?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.data_reference.DataReference.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.data_reference.DataReference.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ManojBableshwar** [comment]
Have filed an incident to investigate this issue: https://icm.ad.msft.net/imp/v3/incidents/details/175120729/home

**Comment by swanderz** [comment]
1. what version of `azureml-sdk` and `azureml-dataprep` do you have?
2. could you please provide a snippet of code as well as the full error?
@MayMSFT

**Comment by Shipika** [comment]
I have resolved this issue. Actually instead of writing  
"input_data = DataReference(
    datastore=blob_store,
    data_reference_name="input_data",
    path_on_datastore="20newsgroups/20news.pkl")"

I have written 
"input_data = DataReference(
    datastore=Datastore(ws, blob_store),
    data_reference_name="test_data",
    path_on_datastore="20newsgroups/20news.pkl")"

This code I have taken from the below link:
https://docs.microsoft.com/en-us/azure/machine-learning/concept-ml-pipelines

You can close this issue and please update the above-mentioned link.
