### ISSUE TITLE
raising error when submitting experiment with invalid syntax identified

### ISSUE THREAD

**Issue by martinResearch** [Azure/MachineLearningNotebooks#791]
When I submit an experiment with an invalid syntax I see a warning in the command line "WARNING - Validation identified the following error(s):". I would like to be able to catch this warning as an error. Is it possible to get access to a flag is true if there is a syntax error ? or better would it be possible to add an option to the submit method so that it raises an error instead of just printing a warning?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22b45b16-b7ed-6dcf-02a6-0bb28cf07e15
* Version Independent ID: 5996774a-3d75-dcbf-4cf8-86f421d36694
* Content: [azureml.core.experiment.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment.experiment?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.experiment.Experiment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.experiment.Experiment.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vizhur** [comment]
@martinResearch there are many tools to validate the code you submit to run. Not sure how AzureML could help here

**Comment by martinResearch** [comment]
@vizhur  It seems that azureml is already automatically running some validation tool locally when submitting an experiment as it prints a warning when I have a syntax error.  My point is that I whish I could laverage that automatic tests  without having to set up my own validation test.

**Comment by vizhur** [comment]
@martinResearch it is simply impossible to do a validation like that on a client side. simple example, different python environment on a remote and user environment, i don't think you'd expect AzureML to spin out an env for the run locally to do a validation. Again, there are a lot of tools you can use locally to perform validation of your own code before submitting it for execution

**Comment by martinResearch** [comment]
I spend a bit of time to find the code in AzureML's client sdk I'm referring to in order to be more specific. A Pyflake (and it seems optionally pylint) syntax validation is already done in the AzureML submission code  (in the  method _validate in C:\Python36\Lib\site-packages\azureml\train\_script_validation.py called by _submit in C:\Python36\Lib\site-packages\azureml\train\estimator\_mml_base_estimator.py ). This is the validation I am talking about (which Indeed doesn't not run a virtual environment) which already happening and is thus not "impossible".
I would like to have the possibility to prevent the final submission to the AzureMLcloud if there are syntax detected detected at that stage. I could instead call pyflake myself as you suggest, but in that case what is that point of doing a syntax check in the AzureML code ? and why not reusing the result of that check already done instead of running the pyflake twice (once in my code before calling AzureML's experiment.submit method , and one inside theAzureMLl submission code) ?

**Comment by vizhur** [comment]
you can do it for estimators only and if pylint is installed in your current environment. After you instantiated an Estimator you can call 
_script_validation._validate() to get a lest of the warnings and raise if len() is not 0

**Comment by martinResearch** [comment]
thanks I'll do that, but that will still implies pyflake will be running twice on my code right ? (once from azureml , once when i call _script_validation._validate() ). Also I assume methods with underscore are internal method and thus suceptible to change and not meant to be called directly ? The goal of my initial comment is more about suggesting an improvement to the official azureml api (by allowing to raise an error when there are syntax validation error) rather than just finding a somewhat hacky way to raise errors by calling internal functions. Maybe that is not the right chanel to do that ?

**Comment by vizhur** [comment]
you can set _disable_validation to True if you do it yourself https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.estimator?view=azure-ml-py
and yes, underscore method means internal and not intended for a public use, but once you discovered it... anyway :). 
I understand the gist of your original comment. We put some effort into that earlier. Unfortunately, there is no reasonable and clean way to perform sufficient validation and avoid false alarms. Most of the time environment you submitting the code from is different from the one where the code is executed. Including platform, interpreter version and set of dependencies. Also everyone's requirement for the code quality is very different. Users are responsible for the code they submit so they can apply their own standards to the quality. There are many tools to do that on a user side and some of them can be integrated in IDE that would make experience a bit better

**Comment by martinResearch** [comment]
I see, thank you for the explanation! I'm still curious to know what the validation in script_validation._validate()  is used for then.
