### ISSUE TITLE
Parameter descriptions should say DsvmCompute

### ISSUE THREAD

**Issue by samurainate** [Azure/MachineLearningNotebooks#792]
Parameter description strings for the "workspace" and "name" parameters of the DsvmCompute(workspace,name) method describe themselves using HDInsightCompute, should replace with DsvmCompute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ea7d85-cea0-42a2-7687-f4cb88d81c97
* Version Independent ID: aea3a5e7-08fe-1e37-dfb1-93815fb649b2
* Content: [azureml.core.compute.DsvmCompute class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.dsvmcompute?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.compute.DsvmCompute.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.compute.DsvmCompute.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks for pointing this out. It has been fixed and should appear live in a few weeks.
