### ISSUE TITLE
AutoArima does not work in sample notebook - auto-ml-forecasting-orange-juice-sales

### ISSUE THREAD

**Issue by srinikris** [Azure/MachineLearningNotebooks#793]
Tried running the python notebook "auto-ml-forecasting-orange-juice-sales.ipynb".
AutoArima is throwing the following error 
############################################################

ValueError: Could not successfully fit ARIMA to input data. It is likely your data is non-stationary. Please induce stationarity or try a different range of model order params. If your data is seasonal, check the period (m) of the data.
############################################################

I ran AutoML ( with ARIMA) on the studio and it worked. Looks like there is a bug when you split the data into train/test ( which the studio does correctly) 

It seems to work with the other models like ElasticNet, Lassolars etc

**Comment by cartacioS** [comment]
Hello,

If you have access to the local environment, you can work-around this by activating the azureml conda env and running the following command.

`pip install --upgrade statsmodels==0.10.2`

Later releases will do this automatically and we're trying to patch the current table release to fix this.

Thanks,
Sabina

**Comment by srinikris** [comment]
Thanks !

**Comment by EricWrightAtWork** [comment]
@srinikris Please see the other issue we've opened for this bug. It contains a more general work-around: https://github.com/Azure/MachineLearningNotebooks/issues/807

**Comment by GiftA-MSFT** [comment]
@srinikris we will now proceed to close this thread. Thanks.

**Comment by DeeptiAgl** [comment]
> ls==0.10.2

Still not working
