### ISSUE TITLE
What are the parameters you can set in the Properties of ContainerImageConfig?

### ISSUE THREAD

**Issue by hangzh-msft** [Azure/MachineLearningNotebooks#794]
Can you provide a link with the parameters we can set? Specifically I am looking for disabling printing out the received data when the container is running. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa78123-03e7-de37-f735-933886a851c0
* Version Independent ID: 67c0a6e7-952b-761f-6b7e-1eb6ffed146c
* Content: [azureml.core.image.container.ContainerImageConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.container.containerimageconfig?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.image.container.ContainerImageConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.image.container.ContainerImageConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@hangzh-msft 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by jpe316** [comment]
ContainerImageConfig is deprecated and will not be receiving updates. Assigning this to Inference for triage with the new way of deploying

**Comment by jpe316** [comment]
Deprecated, won't fix https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-package-models
