### ISSUE TITLE
How to import additional py or library files from folder?

### ISSUE THREAD

**Issue by achieverprince** [Azure/MachineLearningNotebooks#796]
I am trying to deploy Mask RCNN model in Azure ML 

I need to import few functions from my local folder(cloned from Mask RCNN source)
Ex:
from mrcnn import utils
from mrcnn import visualize
from mrcnn.visualize import display_images
import mrcnn.model as modellib
from mrcnn.model import log

How can this be achieved when i deploy code using InferenceConfig
inference_config = InferenceConfig(entry_script="score.py", environment=myenv)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e0f3c7-6241-c84e-e655-03e5c3ed4780
* Version Independent ID: 6e6bb0d2-2ab8-651a-190d-90c198eca17c
* Content: [azureml.core.model.InferenceConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.inferenceconfig?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.model.InferenceConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.model.InferenceConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vizhur** [comment]
put them under source_directory you specified in your config
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.inferenceconfig?view=azure-ml-py

**Comment by achieverprince** [comment]
Thanks, will try that.
