### ISSUE TITLE
Data path in config file

### ISSUE THREAD

**Issue by Jhidzzo** [Azure/MachineLearningNotebooks#799]
Hey,

I am currently working on Implementing the Tensorflow OD Api in a ML pipeline.

I have my first step of the pipeline working so far, however I am struggling now and don't know how to deal with the problem.

So, I got my images and annotations registered as a dataset in the ML Studio. This is working so far and when running following data prep step I get my Tfrecord files on my blob uploaded. 

```
prep_data_step = PythonScriptStep(name="Prep Data",
                                 script_name="object_detection/dataset_tools/create_pet_tf_record.py",
                                 arguments=["--label_map_path",label_map,
                                             "--data_dir",dataset.as_named_input('pet_dataset').as_mount(),
                                             "--output_dir","./output"],
                                  inputs=[dataset.as_named_input('dataset').as_mount(),label_map],
                                  compute_target=cpu_cluster,
                                  outputs=[pet_data],
                                  source_directory=scripts_directory,
                                  runconfig=run_config)
```
My Tfrecord files are saved using following PipelineData object.
```
pet_data = PipelineData("pet_data",
                        datastore=blob_store4,
                        output_mode="upload",
                        output_path_on_compute="./output",
                        is_directory=True)
```
The next step would be to train the model. The model_main script does that for the TF OD Api and this script does not take an argument like data_dir, because it takes the path from the model config file. So my problem is how do I set the path in the config to the files from the blob, using the PipelineData object or do you guys have other ideas on how to solve such a problem? If the first and second step are executed on the same container, which is not the idea of my project, then I could just set the path to the output directory, but I want to have my pipeline steps as independent as possible, which would mean to retrieve the Tfrecord files from the blob. It could be, that I want to use a different compute cluster for the training than for the data prep step, which would not be possible using the dir on the container as data path.

Here is the config snippet, which defines the data path.
```
train_input_reader: {
  tf_record_input_reader {
    input_path: "PATH_TO_BE_CONFIGURED/pet_faces_train.record-?????-of-00010"
  }
  label_map_path: "PATH_TO_BE_CONFIGURED/pet_label_map.pbtxt"
}
```
I guess it would be possible to use a Data Reference, however I would like to mount the PipelineData object, to have it a clean and connecting pipeline.

Sorry for not so good english and unclear explanations, I am not a native speaker. I am doing this project in order to prepare myself for the AI-100 exam and to build up knowledge in the AI field.

Thanks in advance.

**Comment by swanderz** [comment]
@lostmygithubaccount

**Comment by MayMSFT** [comment]
You can parse the convert the PipelineData as dataset and pass it as the input for next training step. here is an example of using pipeline with dataset: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb

```
# define output of our data prep step
pet_data = PipelineData("pet_data",
                        datastore=blob_store4,
                        output_mode="upload",
                        output_path_on_compute="./output",
                        is_directory=True).as_dataset()

# set up training step with Tensorflow estimator
est = TensorFlow(entry_script='train.py',
                 source_directory=script_folder,                 
                 pip_packages = ['azureml-sdk','azureml-dataprep[fuse,pandas]', 'keras'],
                 compute_target=compute_target)

est_step = EstimatorStep(name='train step',
                         estimator=est,
                         estimator_entry_script_arguments=[],
                         inputs=[pet_data.as_mount()],
                         compute_target=compute_target)
```
then in ur training script:
```
# get mounted path of pet_data
from azureml.core import Run
run = Run.get_context()
path = run.input_datasets['pet_data']
```

**Comment by Jhidzzo** [comment]
Thanks for your reply!

I don't want to modify the train script, because I am pulling it from a public repo. So I could set the mount point to a hardcoded path, if I convert the PipelineData to a dataset? This Dataset would only appear as a Dataset in the studio if I specifically register it, right?
