### ISSUE TITLE
Errors in Tensorboard example notebooks

### ISSUE THREAD

**Issue by Fraser-Paine** [Azure/MachineLearningNotebooks#80]
There are a few errors in the current Tensorboard example notebooks in the training folder.
I was able to fix these following the [documentation pdf](https://docs.microsoft.com/en-us/azure/opbuildpdf/machine-learning/service/toc.pdf?branch=live)

Before any imports there should be a line: `!pip install azureml-contrib-tensorboard`
As this module is not installed by following the Installation and Configuration notebook. Also the link to the Installation and Configuration notebook is broken in [this example](https://github.com/Azure/MachineLearningNotebooks/blob/master/training/07.tensorboard/07.tensorboard.ipynb).

Also in code cell 7 `arguments_list = ["--log_dir", "./logs_dir"]` should be `arguments_list = ["--log_dir", "./logs"]`
Things seemed to work after I made these changes.

**Comment by mx-iao** [comment]
@Fraser-Paine Thanks for catching these! We will update the notebooks accordingly.

**Comment by mx-iao** [comment]
Updated

**Comment by j-martens** [comment]
@sdgilley
