### ISSUE TITLE
consequences of AutoMLStep's passthru_automl_config param

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#800]
SDK version: `v1.1.0rc0`

I adopted @purnesh42H 's approach of passing a `PipelineOutputFileDataset` to `AutoMLStep`. It works, but the consequence of  `passthru_automl_config=False` is that the environment must include AutoML as a dependency? I added `automl` as a dependency to the previous PythonScript step, then it worked...
 Perhaps this is because I'm using a pre-release version of the SDK? cc: @cartacioS 

```python
ImportError: cannot import name 'automl
```

```python
run_config = RunConfiguration()
ds = Dataset.File.from_files('https://dprepdata.blob.core.windows.net/demo/Titanic.csv')

dstore = Datastore(ws, 'workspaceblobstore')
output_dataset = PipelineData('output', datastore=dstore, output_mode="upload", 
                              output_path_on_compute='/tmp/data/').as_dataset()
prep_step = PythonScriptStep(
    script_name="train.py",
    arguments=[ds.as_named_input('train').as_mount('/tmp/{}'.format(uuid4()))],
    outputs=[output_dataset],
    source_directory='.',
    compute_target=compute_target,
    runconfig=run_config
)
automl_settings = {
    "iteration_timeout_minutes": 5,
    "iterations": 1,
    "n_cross_validations": 2,
    "primary_metric": 'AUC_weighted',
    "preprocess": True,
    "max_concurrent_iterations": 5,
    "verbosity": logging.INFO
}
tds = output_dataset.parse_delimited_files()
tds_x = tds.drop_columns('Survived')
tds_y = Dataset.Tabular.from_delimited_files('https://dprepdata.blob.core.windows.net/demo/Titanic.csv').keep_columns('Survived')
automl_config = AutoMLConfig(task='classification',
                             debug_log='automl_errors.log',
                             path='.',
                             X=tds_x, 
                             y=tds_y,
                             compute_target=compute_target,
                             **automl_settings)
automl_config._run_configuration = run_config
train_step = AutoMLStep('automl', automl_config, passthru_automl_config=False)
```

I'm confused because the [`20_image_build_log.txt`](https://gist.github.com/swanderz/adea0714c95a3b6bf7bd45ea609d9ae5) shows that `azureml-automl-core-1.1.0rc0` and `azureml-automl-runtime-1.1.0rc0` are installed...

Nothing special (that I can see) in the [`55_azureml-execution-tvmps-blah.txt`](https://gist.github.com/swanderz/4abdcb24d7f5889961b0c3e6283a9cb9). 

[`70_driver_log.txt`](https://gist.github.com/swanderz/2e9981d2286ca7a456cd7534c1c7baa8) has this error (among others):
```python
Traceback (most recent call last):
  File "setup_21de9b75-68cc-408a-b807-3ccfe189ece3.py", line 26, in <module>
    from azureml.train.automl import automl
ImportError: cannot import name 'automl'
```

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 775100c7-f34a-def7-77bc-de7261b7e6bf
* Version Independent ID: e1aa43cf-adde-001c-79a3-1468e665b2c7
* Content: [azureml.train.automl.runtime.AutoMLStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-runtime/azureml.train.automl.runtime.automlstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-runtime/azureml.train.automl.runtime.AutoMLStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-runtime/azureml.train.automl.runtime.AutoMLStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swaticolab** [comment]
I added this package to the conda dependencies, and it worked for me.

`azureml-sdk[notebooks,automl]`

**Comment by swanderz** [comment]
@swaticolab definitely worth noting that that was the fix. but @cartacioS @rastala why should the environment that is defined in a previous `PythonScriptStep` have anything to do with the environment needed for an `AutoMLStep`? It's mind-boggling

**Comment by swatig007** [comment]
@CESARDELATORRE can you pls review this issue

**Comment by CESARDELATORRE** [comment]
#please-close 
This issue is stale. We did some changes related to the “passthru_automl_config” and in the newer SDK versions it shouldn't behave like above.

Basically, the passthru_automl_config parameter has been deprecated from the SDK as of version 1.12.0. All runs using versions >=1.12.0 will automatically use pass through internally regardless of what the user passes in to AutoMLStep.

Please, open a new issue if any related problem related happens.

Adding @pieths if there's any additional question about “passthru_automl_config”
