### ISSUE TITLE
Spark section does not mention how to set framework

### ISSUE THREAD

**Issue by erwelch** [Azure/MachineLearningNotebooks#802]
From this line for the Spark Section: `The section configures Spark settings. It is only used when framework is set to PySpark.` 

There is no mention in this document what it means to set the framework to PySpark. There is no `framework` attribute on the Environment class so it's unclear what this is referencing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be571abf-9f4f-50f0-67df-140cadb5c916
* Version Independent ID: 4f9eb5f5-6844-b21d-6666-b5edac2f9981
* Content: [azureml.core.environment.Environment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.Environment.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
@erwelch, for us it was easy to use Spark in a PythonScriptStep if you create an environment that uses this param: `docker_base_image='microsoft/mmlspark:0.16'` because it has spark pre-installed. you can also adjust nodecount as you see fit. then in your script of the pythonscript, put this at the top.
```python
print("Connect to Spark")
# Start Spark session
spark = (SparkSession.builder
         .master("local[*]")
         .appName("MMLSpark Docker App")
         .getOrCreate()
         )
print("spark con", spark)
```

**Comment by erwelch** [comment]
@swanderz  thanks for the reply! I was installing pyspark passing this to the conda dependencies field: 
`CondaDependencies.create(conda_packages=['pyspark', 'openjdk==8.0.121'])`. The base docker image would have certainly been cleaner. The bug I logged was just for documentation - they don't make it clear how to set the framework. 


I've also been running into issues setting spark configurations since the memory related configs can't be set at runtime (e.g. `spark.executor.memory`). Was hoping they could provide a link to what they meant by `when framework is set to PySpark` to get more clarity on `PySpark` and its relation to the `Environment` class.

**Comment by j-martens** [comment]
@erwelch has your issue been resolved?
