### ISSUE TITLE
Static key for ACI deployment

### ISSUE THREAD

**Issue by Anaig** [Azure/MachineLearningNotebooks#805]
The primary_key and secondary_key seem to be part of the ACI deployment parameters of the Python SDK, however they are not part of the configurable parameters and they are ignored when given to the `az ml model deploy` CLI command. This works fine for AKS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc065b0b-4ab0-6355-e40d-c3125b0cc96e
* Version Independent ID: 0c91be5e-977c-2a35-a073-f6b1ff429904
* Content: [azureml.core.webservice.aci.AciServiceDeploymentConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aci.aciservicedeploymentconfiguration?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciServiceDeploymentConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.aci.AciServiceDeploymentConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@Anaig 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by PeterCLu** [comment]
@Anaig, thanks for your report. 

Primary Key and Secondary Key were added to the AciServiceDeploymentConfiguration class, but they were not added to the CLI. This is a product bug, and a ticket has been raised by the engineering team to resolve it.

Current workaround would be to use the SDK, or to create the service with the CLI and then use the regen-keys cli command to supply new keys.

**Comment by lostmygithubaccount** [comment]
@PeterCLu has this been fixed?

**Comment by vaidya-s** [comment]
We are tracking this as part of the product backlog and this capability will be available by end of December @Bozhong68 FYI

**Comment by Bozhong68** [comment]
CLI support is already available in the latest SDK.
