### ISSUE TITLE
leading slashes in subdir paths

### ISSUE THREAD

**Issue by algattik** [Azure/MachineLearningNotebooks#806]
"then the RunConfiguration is loaded from /.azureml/ or /aml_config/."

should be rewritten without leading slashes:

"then the RunConfiguration is loaded from .azureml/ or aml_config/."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 882f737f-4f00-3cc2-d9b8-410c09fdad9f
* Version Independent ID: ea049c24-1544-523b-c9ba-e3b805d60492
* Content: [azureml.core.RunConfiguration class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfiguration?view=azure-ml-py#load-path--name-none-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.RunConfiguration.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.RunConfiguration.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Thanks for pointing this out. The HTML was not rendering correctly so there was missing markup before the leading slash and after the trailing slash that would give the correct context. The correct markup is:

<path>/.azureml/<name> or <path>/aml_config/<name>

Rendering was addressed and will go live in next SDK release in a few weeks.

**Comment by j-martens** [comment]
thanks for your question.
