### ISSUE TITLE
Service deployment polling reached non-successful terminal state, current service state: Unhealthy

### ISSUE THREAD

**Issue by Rahulvks** [Azure/MachineLearningNotebooks#808]
Getting the below error while deploying Webservice, how to fix this ? 
```
WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
```
Operation ID: 795f8409-f390-4e84-bc3f-21def6bb28ac

```
from azureml.core.webservice import AciWebservice

aciconfig = AciWebservice.deploy_configuration(cpu_cores = 1, 
                                               memory_gb = 1, 
                                              auth_enabled = True) # auth_key

from azureml.core.webservice import Webservice

service_name = 'my-aci-service-5'
print(service_name)

image.wait_for_creation(show_output=True)

service = Webservice.deploy_from_image(deployment_config = aciconfig,
                                           image = image,
                                           name = service_name,
                                           workspace = ws)
service.wait_for_deployment(True)
print(service.state)
```
Error
`print(service.get_logs())
`
```
2020-02-19T07:57:36,079771880+00:00 - iot-server/run 
2020-02-19T07:57:36,089235800+00:00 - nginx/run 
2020-02-19T07:57:36,088401772+00:00 - gunicorn/run 
2020-02-19T07:57:36,094611482+00:00 - rsyslog/run 
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2020-02-19T07:57:36,266457089+00:00 - iot-server/finish 1 0
2020-02-19T07:57:36,274280453+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.9.0
Listening at: http://127.0.0.1:31311 (11)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 44
Exception in worker process
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/var/azureml-server/wsgi.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 3, in <module>
    from app import main
  File "/var/azureml-server/app.py", line 32, in <module>
    import main as user_main
  File "/var/azureml-app/main.py", line 12, in <module>
    driver_module_spec.loader.exec_module(driver_module)
  File "/var/azureml-app/score.py", line 36
    '''
      ^
IndentationError: unindent does not match any outer indentation level
Worker exiting (pid: 44)
Shutting down: Master
Reason: Worker failed to boot.
2020-02-19T07:57:38,608210692+00:00 - gunicorn/finish 3 0
2020-02-19T07:57:38,609583438+00:00 - Exit code 3 is not normal. Killing image
```

**Comment by prafulmbm** [comment]
Please check your score.py file. it has indentation errors.

**Comment by Rahulvks** [comment]
Hi score file are good I have attached the error and score file below

`ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 5dcd070b-469b-4c41-aeab-59fe04f47ee7
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 5dcd070b-469b-4c41-aeab-59fe04f47ee7
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
/opt/anaconda3/lib/python3.7/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    648                                           '{}'.format(self.state, self._operation_endpoint.split('/')[-1],
--> 649                                                       logs_response, error_response), logger=module_logger)
    650             print('{} service creation operation finished, operation "{}"'.format(self._webservice_type,

WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 5dcd070b-469b-4c41-aeab-59fe04f47ee7
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nOperation ID: 5dcd070b-469b-4c41-aeab-59fe04f47ee7\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}

During handling of the above exception, another exception occurred:

WebserviceException                       Traceback (most recent call last)
<ipython-input-19-ec27460236c5> in <module>
     10                                            name = service_name,
     11                                            workspace = ws)
---> 12 service.wait_for_deployment(True)
     13 print(service.state)

/opt/anaconda3/lib/python3.7/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    656                                           'Current state is {}'.format(self.state), logger=module_logger)
    657             else:
--> 658                 raise WebserviceException(e.message, logger=module_logger)
    659 
    660     def _wait_for_operation_to_complete(self, show_output):

WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 5dcd070b-469b-4c41-aeab-59fe04f47ee7
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nOperation ID: 5dcd070b-469b-4c41-aeab-59fe04f47ee7\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}`

Score file

`%%writefile score.py

# import library
import pickle, json
from azureml.core.model import Model

# Keras
from tensorflow.keras import backend
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding

# Other
import numpy as np
import pandas as pd
import re
import io


def init():
    global model,tokenizer
    model_path = Model.get_model_path(model_name = "model_600")
    tokenizer_path = Model.get_model_path(model_name = "tokenizer")
    model,tokenizer = pickle.load(open(model_path,"rb")), pickle.load(open(tokenizer_path,"rb"))
    

def run(raw_data):
    
    try:
        text = json.loads(raw_data)["data"]
        
        prob = 0.5
        minlen = 6
        maxlen = 55
        
       '''
       Preprocessing text before put into the model.
       '''  
        # clean text
        text = text.lower()     # Converting to lowercase
        text = re.sub(r'[?|!|\'|"|#|,|)|(|\|/$%\n\t.:;""‘’]',r'',text)
        
        # text to phrases
        word_list = text.split(' ')
        len_text = len(word_list)
        
        phrases = []   
        len_each_phrase = list(set([minlen,(maxlen + minlen)//2, maxlen]))    

        i = 0
        while i <= len_text:
            for nword in len_each_phrase:    
                if i+nword >= len_text:
                    phrase = ' '.join(word_list[i:])
                    phrases.append(phrase)
                    i = len_text
                    break

                else:
                    phrase = ' '.join(word_list[i:i+nword])
                    phrases.append(phrase)
            i += 1
            
        # tokenize phrases (text -> numerical value)
        sequences = tokenizer.texts_to_sequences(phrases) #phrases
        test_data = pad_sequences(sequences, maxlen = maxlen)
        
        # predict with model
        preds = model.predict(test_data)

        preds_df = pd.DataFrame(preds)
        count = preds_df[preds_df > prob].count()
        
        # return label based on probability
        if sum(count[1:] > 0) > 0:
            result = count.idxmax()
        else:
            result = 0

        return json.dumps({"category": result}) 
    
    except Exception as e:
        result = str(e)
        return json.dumps({"category": result})`

**Comment by prafulmbm** [comment]
You see the error on the triple quoted string. That's where you need to
check your code.

**Comment by SUDEEPIOTTECH** [comment]
Hi Team, 

I am also getting Similar  error. Could you let me know, how I will solve the issue or whom I have to contact or any link where I will post / support link ?

from azureml.core.webservice import Webservice

aci_service_name = 'tempsensor-iotedge-ml-2'
print(aci_service_name)
aci_service = Webservice.deploy_from_image(deployment_config = aciconfig,
                                           image = image,
                                           name = aci_service_name,
                                           workspace = ws)
aci_service.wait_for_deployment(True)
print(aci_service.state)
tempsensor-iotedge-ml-2
Running...................................................................................................................................................................................................................................................................................................................................................................
TimedOut
ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
~/anaconda3_501/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    530                                           'Error:\n'
--> 531                                           '{}'.format(self.state, logs_response, error_response), logger=module_logger)
    532             print('{} service creation operation finished, operation "{}"'.format(self._webservice_type,

WebserviceException: WebserviceException:
        Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
        InnerException None
        ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}

During handling of the above exception, another exception occurred:

WebserviceException                       Traceback (most recent call last)
<ipython-input-30-48487f6bebba> in <module>
      7                                            name = aci_service_name,
      8                                            workspace = ws)
----> 9 aci_service.wait_for_deployment(True)
     10 print(aci_service.state)

~/anaconda3_501/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    538                                           'Current state is {}'.format(self.state), logger=module_logger)
    539             else:
--> 540                 raise WebserviceException(e.message, logger=module_logger)
    541 
    542     def _wait_for_operation_to_complete(self, show_output):

WebserviceException: WebserviceException:
        Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}
        InnerException None
        ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"
    }
}


Thanks and Regards,
Sudeep Kumar Patel
