### ISSUE TITLE
YAML file examples

### ISSUE THREAD

**Issue by djpugh** [Azure/MachineLearningNotebooks#810]
Please note that according to https://docs.microsoft.com/en-us/azure/machine-learning/reference-pipeline-yaml#steps ModuleStep is not supported by yaml - can you at least make sure your docs releases are internally consistent........... (https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline(class)?view=azure-ml-py#load-yaml-workspace--filename---workflow-provider-none---service-endpoint-none-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac092952-4045-3862-e95f-8771d0b67649
* Version Independent ID: f33af841-db1e-91e1-790f-56cc7a97040b
* Content: [Machine Learning pipeline YAML - Azure Machine Learning](https://docs.microsoft.com/en-us/azure/machine-learning/reference-pipeline-yaml#steps)
* Content Source: [articles/machine-learning/reference-pipeline-yaml.md](https://github.com/Microsoft/azure-docs/blob/master/articles/machine-learning/reference-pipeline-yaml.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @sanpil
* Microsoft Alias: **sanpil**

**Comment by vmagelo** [comment]
ModuleStep is supported by yaml. The article referenced will be updated. Thanks for pointing this out.
