### ISSUE TITLE
Primary metric for hyperdrive

### ISSUE THREAD

**Issue by kubasiak** [Azure/MachineLearningNotebooks#812]
It seems that primary metric doesn't refer to anything logged by run.log(). How are the metrics calculated then? and where is the list of available ones? Is it possible to use custom metric?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7be45ce-baa1-ab0b-9c4a-8c64aab8131d
* Version Independent ID: 92eda8b3-b75c-69a3-11f0-ac1ec2fe4a87
* Content: [azureml.train.hyperdrive.HyperDriveConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.hyperdrive.hyperdriveconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.HyperDriveConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.hyperdrive.HyperDriveConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
you can use any metric you want. Check out [this notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb) in which `primary_metric_name='validation_acc'` is passed to `HyperDriveConfig`. If you look at the `entry_script`, `tf_mnist.py`, you can that `validation_acc` is in fact a custom logged metric.

```python
run.log('validation_acc', np.float(acc_val))
```

@j-martens @lobrien perhaps this could be made more clear in the description for `primary_metric_name` in `HyperDriveConfig`

**Comment by GiftA-MSFT** [comment]
@kubasiak and @swanderz thanks for your feedback. We will now proceed to close this thread.
