### ISSUE TITLE
`conda_dependencies_file_path` and `conda_dependencies_file` have same description

### ISSUE THREAD

**Issue by yangsiyu007** [Azure/MachineLearningNotebooks#813]
The description for the parameters `conda_dependencies_file_path` and `conda_dependencies_file` is exactly the same: "The relative path to the conda dependencies yaml file. If specified, Azure ML will not install any framework related packages." Same for the pip equivalents. This is unhelpful. 

Using `conda_dependencies_file` (instead of `conda_dependencies_file_path`) for giving the path to the environment.yml file gives the error that the Python interpreter version needs to be specified in the file, even though I have it specified as the first dependency. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb892243-d2f3-79a1-4061-b2d46235aff4
* Version Independent ID: a6e4c4ab-3665-c0d3-65ff-abc5cbb0b835
* Content: [azureml.train.dnn.PyTorch class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.pytorch?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by yangsiyu007** [comment]
Actually I retract the second point... The error message about having to specify the Python interpreter version actually meant that Python version needs to be specified exactly (python==3.6.2), and not by a range (python>=3.6).

If these two names are aliases, please make that clear.

**Comment by j-martens** [comment]
@mvagelo

**Comment by vmagelo** [comment]
The docs were updated and (are live) to reflect that conda_dependencies_file_path is deprecated (as well as pip_requirements_file_path) and you should use parameters without the _path.

**Comment by j-martens** [comment]
thanks for your report. this has been fixed through documentation. we shall now proceed to close this thread.
