### ISSUE TITLE
ParallelRunStep --output parameter

### ISSUE THREAD

**Issue by himat-shell** [Azure/MachineLearningNotebooks#814]
In the output parameter I have a PipelineData object set to output_mode "upload".  However when i compile the ParallelRunStep --output argument fails to read my object.  It appears blank.

`worker_main.py: error: argument --output: expected one argument`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad40bfd-b1f2-aa7e-828b-f3c6acf163df
* Version Independent ID: d1cfafdb-a8dd-17fc-d785-e1abf72bdaba
* Content: [azureml.contrib.pipeline.steps.parallel_run_step.ParallelRunStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.parallel_run_step.parallelrunstep?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.parallel_run_step.ParallelRunStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.parallel_run_step.ParallelRunStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by HSSD-shell** [comment]
output_dir = PipelineData(name="results",
                          datastore=blob_datastore,
                          output_path_on_compute="inference/",
                          output_mode="upload",
                          output_overwrite=True)

**Comment by shbijlan** [comment]
@himat-shell, are you still facing an issue with this? Could you share the parallel run config you created? We'll need some additional info to reproduce the issue.

**Comment by lostmygithubaccount** [comment]
closing given no response, feel free to reopen
