### ISSUE TITLE
Sample code has 'experiment_timeout_minutes' parameter but the parameter is 'experiment_timeout_hours' (float value)

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#815]
The sample code is wrong, probably due to older versions.
The current parameter is called "experiment_timeout_hours" (float value)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RachelKellam** [comment]
Thanks Cesar! We have created a work item to fix this

**Comment by vmagelo** [comment]
Thanks for pointing this out. We fixed the sample code. The change will go live with the next sdk release in a few weeks.
