### ISSUE TITLE
validation_size": 0.3 description should explicitly say that the % value should be provided as a decimal number (between 0 and 1)

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#816]
The current description of "validation_size" only says:
"What percent of the data to hold out for validation when user validation data is not specified."

That's misleading. a percent is specified with a number between 0 and 100 (i.e. 20 for a 20% validation set), but the expected number for this argument is a value between 0 and 1, such as 0.2. That should be explicit in the description.
Example:  
validation_size = 0.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by gaugup** [comment]
Thanks for pointing this out. We have put a fix to address this documentation in our SDK. It should be available in next few weeks.
