### ISSUE TITLE
<class 'ValueError'>: ZIP does not support timestamps before 1980 <traceback object at 0x7fa5604a9b08>

### ISSUE THREAD

**Issue by ansylenium** [Azure/MachineLearningNotebooks#817]
I am having this issue when running shutil.make_archive(mdl, 'zip', model_dbfs)

**Comment by YutongTie-MSFT** [comment]
@ansylenium 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by GiftA-MSFT** [comment]
Closing this thread since its outdated. Please comment below if you need further assistance. Thanks.
