### ISSUE TITLE
How to create the dataset using rest api Any documentation available?

### ISSUE THREAD

**Issue by imshreya** [Azure/MachineLearningNotebooks#819]

**Comment by imshreya** [comment]
we are Try to create the dataset in tabular format using REST API ...we didn't find any documentation related to dataset creation.

**Comment by skasturi** [comment]
Here is an example that is used in AutoML notebooks. 

```python
# ws representing the workspace object
datastore = ws.get_default_datastore()
datastore.upload_files(files = ['./train.csv'], target_path = 'beer-dataset/tabular/', overwrite = True,show_progress = True)
datastore.upload_files(files = ['./valid.csv'], target_path = 'beer-dataset/tabular/', overwrite = True,show_progress = True)
datastore.upload_files(files = ['./test.csv'], target_path = 'beer-dataset/tabular/', overwrite = True,show_progress = True)

from azureml.core import Dataset
train_dataset = Dataset.Tabular.from_delimited_files(path = [(datastore, 'beer-dataset/tabular/train.csv')])
valid_dataset = Dataset.Tabular.from_delimited_files(path = [(datastore, 'beer-dataset/tabular/valid.csv')])
test_dataset = Dataset.Tabular.from_delimited_files(path = [(datastore, 'beer-dataset/tabular/test.csv')])
```
 
Link to the actual notebook: [link](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb)

**Comment by imshreya** [comment]
@skasturi wants to find the rest API docs something like that so that it can be implemented in any given language.

**Comment by skasturi** [comment]
I do not know if we support API based create a data set natively. @deepak-muniappan ?  

That said, a workaround would be to use the pythonic way I mentioned above in a sub-process.
