### ISSUE TITLE
How to download individual files from a Datastore directory

### ISSUE THREAD

**Issue by nicolemhfarley** [Azure/MachineLearningNotebooks#820]
I would like to be able to download individual files from a directory .   I'm currently using the `Datastore.download()` method to access my files but that downloads all files within the directory.  This happens even if I specify a single file by name using the `target_path` argument. Is there a similar method that would allow me to be more selective?

**Comment by balapv** [comment]
If you are using a blob datastore you can download files using
ds.download(target_path='<path where you want to store the downloaded file>',
                   prefix='<path of file to download>',
                   show_progress=True)

**Comment by balapv** [comment]
You can download a speciofic file using the prefix paramater
ds.download(target_path='path to store the downloaded file',
                   prefix='path of file to download',
                   show_progress=True)

**Comment by GiftA-MSFT** [comment]
Thanks for your feedback. We will now proceed to close this thread.
