### ISSUE TITLE
Clone button not appearing

### ISSUE THREAD

**Issue by ErnstRoell** [Azure/MachineLearningNotebooks#822]
In the older version of Microsoft Edge the clone button in the Azure ML Studio does not appear next to the folders. It seems to work in Chrome though.
The version numbers:
Microsoft Edge 44.18362.449.0

![noButton](https://user-images.githubusercontent.com/41236056/75434848-7696b500-5952-11ea-9086-989f9ff91405.png)

**Comment by YutongTie-MSFT** [comment]
@ErnstRoell 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AbeOmor** [comment]
#pleaseclose This button is not supported in the old version of Edge. You will need to upgrade to newest Microsoft Edge based on Chromium
