### ISSUE TITLE
No reference to Run class

### ISSUE THREAD

**Issue by maxluk** [Azure/MachineLearningNotebooks#823]
Tensorboard class constructor takes list of Run objects as input. The documentation page should include link to the Run object class documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a27c9b-8c46-66ea-3232-45687d198ac0
* Version Independent ID: fc5fb2e8-9579-79a0-c914-d5f90a5e201e
* Content: [azureml.tensorboard.Tensorboard class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-tensorboard/azureml.tensorboard.tensorboard?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-tensorboard/azureml.tensorboard.Tensorboard.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-tensorboard/azureml.tensorboard.Tensorboard.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment]
Addressed. Thanks. Change will appear in next release of SDK.

**Comment by PeterCLu** [comment]
#please-close
