### ISSUE TITLE
Updating arguments in PythonScriptStep is not reflected in published pipeline  

### ISSUE THREAD

**Issue by ficocesari** [Azure/MachineLearningNotebooks#825]
Steps to reproduce

1. Create a PythonScriptStep with name "output" and arguments=["--format", "json"] 
2. Publish pipeline
3. Update PythonScriptStep with the same name "output" and arguments=["--format", **"geojson"**] 
4. Publish pipeline
5. Notice in the UI and at runtime that the --format argument still has the old value "json"

Had to resort to change the name of the step to avoid this issue.

Actual code:
PythonScriptStep(
                script_name="output.py",
                name="output"
                arguments=["--inputs", self.inputs,
                           "--format", "json",
                           "--pipeline_data", pipeline_data[0],
                           "--output", output],
                inputs=[pipeline_data[0]],
                outputs=[output],
                compute_target=self.compute_target,
                source_directory=self.project_folder,
                runconfig=self.run_config,
                allow_reuse=False
            ),

After change
PythonScriptStep(
                script_name="output.py",
                name="output"
                arguments=["--inputs", self.inputs,
                           "--format", "geojson",
                           "--pipeline_data", pipeline_data[0],
                           "--output", output],
                inputs=[pipeline_data[0]],
                outputs=[output],
                compute_target=self.compute_target,
                source_directory=self.project_folder,
                runconfig=self.run_config,
                allow_reuse=False
            ),

**Comment by swanderz** [comment]
@ficocesari you're awesome for making a repo. not fun. also happened to me (#771 ) @alexkalita let me know the fix is in a pre-release version of the SDK version `1.1.0rc0` as well as future versions

**Comment by ficocesari** [comment]
Thanks!
This is great, thanks for relaying the info.  Will try 1.1.0rc0

**Comment by GiftA-MSFT** [comment]
We will now proceed to close this thread. Thanks.
