### ISSUE TITLE
"Deploy a model to Azure Container Instances" link does not exist

### ISSUE THREAD

**Issue by damochiz** [Azure/MachineLearningNotebooks#827]
Clicking the link "Deploy a model to Azure Container Instances" accesses the following URL, but displays the page if it does not exist.

URL: https://docs.microsoft.com/en-us/python/api/azureml-core/%5Bhttps://docs.microsoft.com/azure/machine-learning/service/how-to-deploy-azure-container-instance%5D(https://docs.microsoft.com/azure/machine-learning/service/how-to-deploy-azure-container-instance)?view=azure-ml-py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ca682e-3d11-0c75-736a-19225ce818c3
* Version Independent ID: 7a55db78-b784-63c8-29d9-7f38dc40bfe5
* Content: [azureml.core.webservice.AciWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aciwebservice?view=azure-ml-py#deploy-configuration-cpu-cores-none--memory-gb-none--tags-none--properties-none--description-none--location-none--auth-enabled-none--ssl-enabled-none--enable-app-insights-none--ssl-cert-pem-file-none--ssl-key-pem-file-none--ssl-cname-none--dns-name-label-none-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AciWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AciWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@damochiz Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YutongTie-MSFT** [comment]
@j-martens Hi Josee, could you please help us fix this page? Thanks.

**Comment by vmagelo** [comment]
A fix is in the works. Thanks for pointing this out.

**Comment by vmagelo** [comment]
Fix will appear in next release in 1-2 weeks. Thanks.

**Comment by PeterCLu** [comment]
Fix has been applied, I'll proceed to close this issue.
