### ISSUE TITLE
How to deploy a secondary endpoint specific for features importance 

### ISSUE THREAD

**Issue by samoliveira** [Azure/MachineLearningNotebooks#828]
I'm trying to deploy a custom model inside azure ml not specifically trained inside the platform, and i didn't figure out a way to customize the endpoints, for instance i would like to create another one separated from scoring just to get models features importance.

**Comment by YutongTie-MSFT** [comment]
@samoliveira 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
