### ISSUE TITLE
Unusual blob/files synchronisation issues in SDK

### ISSUE THREAD

**Issue by kodonnell** [Azure/MachineLearningNotebooks#83]
NB: not a notebooks question, but I'm not sure where the SDK is located to raise an issue.

### Background

We're running tensorflow object detection (TOD). Since we don't want to rewrite the code, we did a nasty thing by outputting the events + checkpoints to the `./logs` directory. This means we can use the Azure ML Tensorboard plugin (which looks for `./logs`).

### Problem

The events get synced fine when we run tensorboard (the Azure ML contrib). However, TOD also writes checkpoints out to the same directory, so tensorboard syncs all of these too. The initial problem we have was that when we went to use the synced checkpoints ('cos why not), the file names were associated to the incorrect file. For example, we'd expect something like

```
X.index
X.meta
X.data
```

However, we found the content of `X.meta` was actually that of `X.index`, etc.

Digging a bit further, we found that the associated fileshare (`azureml/<experiment>/logs`) was 'correct', and didn't have this issue:

![image](https://user-images.githubusercontent.com/8204904/48524520-6ede0900-e8e5-11e8-9633-d8a9cd4167f9.png)

whereas the files in the associated blob account (`azureml/ExperimentRuns/<experiment>/logs`) were incorrect - note that the size of the `meta` and `index` files has switched. (Ignore the tempstate file which I think is related to partial downloads or something.)

![image](https://user-images.githubusercontent.com/8204904/48524549-9634d600-e8e5-11e8-8d76-727673972f53.png)

Since Tensorboard syncs using the RunWatcher etc. which uses the **blobs** not the file share (verified by printing the URI + filepath inside of RunWatcher), this is why our local files end up with incorrect names. We can't really provide a test case, but I'd start by looking for cases where you split off the extension (possibly while trying to get mimetype?). 

On a side note - only the last five `X` are kept by TOD, and it overwrites as it goes. The file store correctly shows this, but not the blob account - i.e. the blob account doesn't appear to be being synced correctly to remove files that are deleted (when run on the container).

**Comment by kodonnell** [comment]
Thanks to @Fraser-Paine for debugging this too.

**Comment by imatiach-msft** [comment]
hi @kodonnell and @Fraser-Paine , the issue should now be fixed in the latest release of SDK 1.0.6.  Thanks for reporting, closing this issue.
