### ISSUE TITLE
Run.complete() not uploading anything to Azure Studio

### ISSUE THREAD

**Issue by ballcap231** [Azure/MachineLearningNotebooks#830]
For a run object, what does it mean for it to upload "run artifacts"? it is said that during completion (i.e. run.complete()) the run loads "run artifacts" but I don't see anything uploaded to my outputs/log tab on Azure Studio.

In this example code:
experiment = Experiment(workspace, "My Experiment")
   run = experiment.start_logging(outputs=None, snapshot_directory=".")
   ...
   run.log_metric("Accuracy", accuracy)
   run.complete()

![image](https://user-images.githubusercontent.com/40708323/75711979-db247d80-5c8c-11ea-84be-0f50ad001a72.png)

![image](https://user-images.githubusercontent.com/40708323/75712477-9a793400-5c8d-11ea-92c5-6804cdd32f9e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
* Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
* Content: [azureml.core.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment%28class%29?view=azure-ml-py#start-logging--args----kwargs-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@ballcap231 Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by ram-msft** [comment]
@ballcap231 Please follow the below document to enable logging in azure machine learning.
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-enable-logging#training-models-and-compute-target-logging
![image](https://user-images.githubusercontent.com/49180516/75978030-a40bd180-5f03-11ea-9ecf-165ecc0e75f4.png)

**Comment by ram-msft** [comment]
@ballcap231 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
