### ISSUE TITLE
Broken link in PyTorch mnist notebook

### ISSUE THREAD

**Issue by gvashishtha** [Azure/MachineLearningNotebooks#834]
Configuration link under Prerequisites appears to be broken in [this notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/training/distributed-pytorch-with-horovod/distributed-pytorch-with-horovod.ipynb](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/training/distributed-pytorch-with-horovod/distributed-pytorch-with-horovod.ipynb)

**Comment by YutongTie-MSFT** [comment]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/training/distributed-pytorch-with-horovod/distributed-pytorch-with-horovod.ipynb

@gvashishtha Hi Gopal, this link works for me well. Could you please try again? Thanks!

**Comment by gvashishtha** [comment]
Yep, still broken. Try going to https://render.githubusercontent.com/configuration.ipynb , and it will not work.

[This line](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/training/distributed-pytorch-with-horovod/distributed-pytorch-with-horovod.ipynb?short_path=f711b27#L32) is the issue

**Comment by YutongTie-MSFT** [comment]
@vizhur Hi, could you please help fix this repo? Thanks.

**Comment by j-martens** [comment]
@YutongTie-MSFT  please assign to notebook author.  The impacted notebooks use a path like ../../../configuration.ipynb but the location of the notebook is too deep and the link doesn’t resolve. This happens in particular with ml-frameworks notebooks which are deeply nested like the notebook in the issue.

**Comment by vizhur** [comment]
sample is moved/renamed closing the isse
