### ISSUE TITLE
No config.json example

### ISSUE THREAD

**Issue by gvashishtha** [Azure/MachineLearningNotebooks#835]
This page should have an example of a config.json for using workspace.from_config()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90efe042-27ac-6e77-9292-10df77bb1c36
* Version Independent ID: 3b9f2576-7d3f-00f8-0afe-549960520f08
* Content: [azureml.core.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace(class)?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@gvashishtha 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

@j-martens 
Hi Josee, could you take a look of this issue? There is some information missing here. Thanks!

**Comment by vmagelo** [comment]
We added a link to an example/discussion of the config in an article. The article has more context around the fields in the config. Change will appear in next SDK release in a few weeks. Thanks.
