### ISSUE TITLE
SSL Setting - requests

### ISSUE THREAD

**Issue by lphomiej** [Azure/MachineLearningNotebooks#836]
I'm working through issues around being behind a corporate network/proxy and this package's issues with SSL. Using Windows 10. Issue occurs in command line and using VS Code/Jupyter notebook.

So far, the steps I've gone through to make this work are as follows:
1.) Azure ML SDK couldn't login using the InteractiveLoginAuthentication method due to SSL errors.

2.) Assuming this was using the same login as the Azure CLI, I tested that and it wans't working either - with `az login` (gave the same error). So, I followed this guide: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

3.) I updated Azure CLI certifi cert to include our proxy's cert at the bottom, and that fixed Azure CLI, but not AzureML SDK.

4.) I then updated the "certifi" module's certificate to include my proxy's cert, and that fixed the AzureML SDK InteractiveLogin issue.

5.) Then, going through creating a pipeline (ie: `pipeline = Pipeline( description="A test pipeline",workspace=ws,steps=[ingest_step,dataprep_step,train_step]`), I'm now seeing an error when I try to create a Pipeline:

MaxRetryError: HTTPSConnectionPool(host='westus2.aether.ms', port=443): Max retries exceeded with url: /api/v1.0/subscriptions/-----------------------/resourceGroups/AzureML/providers/Microsoft.MachineLearningServices/workspaces/---------/DataTypes (Caused by ResponseError('too many 503 error responses'))

6.) Some help threads suggested this was common behavior when the service was just down, so I went home (off the network), and tested the script, and it worked fine. Came back into work this morning, and it's still doing the same thing. 

7.) So, I tried some things listed in another thread, but none of this helped... https://github.com/Azure/azure-cli/issues/5099
-- Tried adding the certifi cert to the environment variable REQUESTS_CA_BUNDLE (in Windows cmd prompt and Windows powershell).
-- Tried moving the cert to the 'requests' module folder. 
-- Tried manually setting urllib3 to use certifi's cert that I edited: 
`import certifi
import urllib3
http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED',
    ca_certs=certifi.where())`

Any ideas...? =\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e29a33-0622-294e-4558-ca898e9ea5a3
* Version Independent ID: e3e3dfc0-3f51-a15e-309e-81113ef49bdb
* Content: [azureml.pipeline.core.pipeline.Pipeline class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipeline.pipeline?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.pipeline.Pipeline.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@lphomiej Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by ram-msft** [comment]
@lphomiej Can you please add more details about if you running Fiddler on your machine or anything capturing traffic, are they? If you are running behind a proxy you can set that as the HTTP_PROXY/HTTPS_PROXY environment variables to configure the requests library.

**Comment by ram-msft** [comment]
@aashishb Can you please help on this SSL error.

**Comment by lphomiej** [comment]
I haven't been in the office due to the COVID-19 thing, so I'm not able to test this further right now. I was hoping it'd be clear that the Pipeline class was using Request, overwriting some settings or something - since everything else worked (logging in). 

Our infrastructure team said they might have to whitelist certain traffic because it's being decrypted as it comes in (or something like that). So, if that's the case, then I may just have to continue working with them on this.

**Comment by aashishb** [comment]
Adding @sanpil  for pipelines

**Comment by sanpil** [comment]
Will wait for @lphomiej to get back to us with an update.

**Comment by shbijlan** [comment]
#please-close
