### ISSUE TITLE
Arguments passed to ModuleStep or PythonScriptStep showing up as empty from the scripts/module side

### ISSUE THREAD

**Issue by stemoor** [Azure/MachineLearningNotebooks#837]
Hello, 
I ran into this problem a couple times where the argument I am passing does not show up on the other side. Instead it shows as empty ''. This has happened to me both with a ModuleStep and a PythonScriptStep. Here is a bit of my code for the module step. This is basically the same as for the PythonScript step except for the step type, but things are done in the same way. 

```python

    input_case_data = DataReference(
        datastore=datastore,
        data_reference_name= "input_data",
        mode="download"
    )

    output_data = PipelineData(
        name = "output_data",
        datastore=datastore,
        is_directory=True
    )

    step_input_wiring = {"input_data":input_case_data }
    step_output_wiring = {"output_data":output_data}
    output_data_name = "something.json"

    middle_step = ModuleStep(
        module=module,
        inputs_map= step_input_wiring, 
        outputs_map= step_output_wiring,
        runconfig=run_config, compute_target=compute_target,
        arguments =[
            "--input_data", input_case_data , 
            "--output_dir", output_data,
            "--output_data", output_data_name]
    )

```

On the other side, this is how the parameter --input_data shows up as empty ''

Preparing to call script [ clean_data.py ] with arguments: ['--input_data', '', '--output_dir', '/mnt/batch/tasks/shared/LS_root/jobs/cyril-dev-aml-ws/azureml/81e48921-f1b0-41fa-8bfa-b7d3f646d518/mounts/training_datastore/azureml/81e48921-f1b0-41fa-8bfa-b7d3f646d518/output_data', '--output_data', 'clean_case_data.json']
After variable expansion, calling script [ clean_data.py ] with arguments: ['--input_data', '', '--output_dir', '/mnt/batch/tasks/shared/LS_root/jobs/cyril-dev-aml-ws/azureml/81e48921-f1b0-41fa-8bfa-b7d3f646d518/mounts/training_datastore/azureml/81e48921-f1b0-41fa-8bfa-b7d3f646d518/output_data', '--output_data', 'clean_case_data.json']

This same behavior happened with the PythonScript but with the output_dir argument instead. The way I "fixed it" was by commenting out the output_mode="upload" when declaring the output_data  variable. 

I have found a work around for this issue with the Module as well. By using Pipeline Parameter. 
Like this:

```python
    input_path = DataPath.create_from_data_reference(input_case_data)
    param = (PipelineParameter(name="initialNum", default_value=input_path), 
    DataPathComputeBinding(mode='download'))
    step_input_wiring = {"input_data":input_case_data}
```

Then pass this variable param to the module as an argument as well.

Here is how I created the module:

```python
    input_data = InputPortDef(
        name="input_data", 
        default_datastore_mode="mount", 
        default_data_reference_name=datastore.name, 
        label="Raw case data")

    output_data = OutputPortDef(name="output_data", default_datastore_name=datastore.name, default_datastore_mode="mount",
                                label="The cleaned data")
    
    module.publish_python_script(
        "clean_data.py", 
        "middle",
        inputs=[input_data], 
        outputs=[output_data], version="1.4", 
        is_default=True, 
        source_directory="./")

```

SDK Version: azureml-sdk==1.1.0rc0

**Comment by GiftA-MSFT** [comment]
@stemoor thanks for sharing this feedback. We will now proceed to close this thread.

**Comment by YutongTie-MSFT** [comment]
@stemoor 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by alexkalita** [comment]
This is because your DataReference is using the 'download' mode.  If you switch this to 'mount' (which is the default), it should do the path expansion for the arguments list.

    input_case_data = DataReference(
        datastore=datastore,
        data_reference_name= "input_data",
        mode=**"download"**
    )

The 'download' mode is intended to be use when the script expects a specific (e.g. hard-coded) path for the input data.  In this case, you would specify the path with the path_on_compute parameter when you declare the DataReference.  Then AML will download the data to that path before executing your script.  Since the path is not generated by AML in this case, we don't do the variable expansion for the arguments list.

With the 'mount' mode, AML creates a temporary directory with the mounted data and sets an environment variable with that path, which is expanded in the arguments list.

Our documentation is a little lacking on how the download/upload modes work, and we are working to improve that.

**Comment by vmagelo** [comment]
We added info to the doc capturing the info above. Will appear with next SDK releast.

**Comment by j-martens** [comment]
We will now proceed to close this thread. Thank you so much for your post. The updated docs should be released in the new 2-3 weeks.

**Comment by stemoor** [comment]
Thank this helps. I am running into a similar situation with the PipelineData type. If I use output_mode = "upload" with output_path_on_compute = "./output", then it seems like the variable expansion is not done automatically from the first script side. It shows up as "". In this case, how do my script knows where to save the output to so it gets picked up and uploaded to the next script? I could not find anywhere in the documentation explaining this.

**Comment by alexkalita** [comment]
For the upload/download mode, it is assumed that the script already knows the path to write to.  If it is not hard-coded in the script, you can pass in the path "./output" in the arguments list.
