### ISSUE TITLE
Support multiple countries

### ISSUE THREAD

**Issue by robert4os** [Azure/MachineLearningNotebooks#843]
Hi,

in Europe we have retailers that get customers from different countries in the same store, sometimes even three countries. It is typical that customers cross borders if they are close to obtain cheaper prices.

Therefor it would be great if multiple countries would be accepted by automl for holiday feature generation.

Thank you and best regards,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by cartacioS** [comment]
Hello @robert4os ,

Support for multiple regions/countries is already an item in our backlog. 

It'd be great sync offline on your use case for AutoML and forecasting. If you're interested in sharing your requirements and product feedback please reach out to us at AskAutomatedML@microsoft.com

Thanks,
Sabina

**Comment by YutongTie-MSFT** [comment]
@robert4os 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
