### ISSUE TITLE
arguments as list needs examples

### ISSUE THREAD

**Issue by gvashishtha** [Azure/MachineLearningNotebooks#847]
Usually, arguments are passed as a dictionary of key-value pairs. It's not clear from this page how to use a list to pass arguments to the ScriptRunConfig.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109d9284-e234-5086-5da6-4155291361c8
* Version Independent ID: 57cc0c7a-faa7-1a86-ee14-b9cf99fb540d
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@gvashishtha 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
To help you immediately, the list is of strings arguments are in pairs.  

arguments = ['--arg1', arg1_val, '--arg2', arg2_val]

([notebook example](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/track-and-monitor-experiments/tensorboard/tensorboard.ipynb)) arguments_list = ["--log_dir", logs_dir]

([notebook example](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/train-on-remote-vm/train-on-remote-vm.ipynb)) script_arguments = ['--data-folder', dataset.as_named_input('diabetes').as_mount('/tmp/{}'.format(uuid4()))]

**Comment by vmagelo** [comment]
We updated docs. Changes will go out with next SDK release in 1-2 weeks. Thanks.
