### ISSUE TITLE
Any chance to get this information soon?

### ISSUE THREAD

**Issue by samoliveira** [Azure/MachineLearningNotebooks#848]
Any chance to get this information soon?
No content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57603f8f-c5c0-b5c9-f7f6-50f3c76b6970
* Version Independent ID: 0f85cea1-a89f-46a3-38f1-57d5041bc253
* Content: [azureml.core.dataset.Dataset.Tabular class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset.tabular?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.Tabular.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.dataset.Dataset.Tabular.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@samoliveira 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
I believe this page isn't really a class; it's a spurious result output from the build system.  Everything you need to know about Tabular is in https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py.

**Comment by yikei** [comment]
In addition to the Dataset class linked by the previous reply, you can also refer to TabularDataset class here: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.tabulardataset?view=azure-ml-py

We will look into why the empty page exists and fix it.

Hope this resolves the issue, thanks!

**Comment by PeterCLu** [comment]
@vmagelo, the change was merged in, but I still don't see the message. Any updates on this?

**Comment by vmagelo** [comment]
Sorry for the delay. There was a mix up on where the change should go. It has been fixed and the change is live.

**Comment by j-martens** [comment]
Thank you for your report. I'll now proceed to close this issue.
