### ISSUE TITLE
Better document properties that are added to runs by default in get_properties

### ISSUE THREAD

**Issue by gvashishtha** [Azure/MachineLearningNotebooks#849]
This page should include a dictionary of properties that are automatically added to a run, so that people doing experiment.get_runs() know what properties are available to filter on. When I do run.get_properties(), I see the following, hopefully enough to get started.

{'_azureml.ComputeTargetType': 'amlcompute',
 'ContentSnapshotId': 'f459664c-f3ad-4c28-8e0c-e76861f42c0a',
 'azureml.git.repository_uri': 'git@github.com:gvashishtha/pytorch-object.git',
 'mlflow.source.git.repoURL': 'git@github.com:gvashishtha/pytorch-object.git',
 'azureml.git.branch': 'register-model',
 'mlflow.source.git.branch': 'register-model',
 'azureml.git.commit': '164fbede8c31e67bdc3b9e310a39e6d2765f3046',
 'mlflow.source.git.commit': '164fbede8c31e67bdc3b9e310a39e6d2765f3046',
 'azureml.git.dirty': 'False',
 'AzureML.DerivedImageName': 'azureml/azureml_9125fd9b495cfdec8f7bf56c6d28d91d',
 'ProcessInfoFile': 'azureml-logs/process_info.json',
 'ProcessStatusFile': 'azureml-logs/process_status.json'}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a70336d-fb4a-4c18-26d0-68784b5b3d72
* Version Independent ID: e28876d8-08a0-8546-4bd1-6e434c8c7826
* Content: [azureml.core.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py#get-properties--)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Run(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@vmagelo

**Comment by vmagelo** [comment]
What you see for properties depends on the context. A simple run started in local notebook shows just 'ContentSnapshotId' whereas a ScriptRun will many properties.  You can see this running this [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/track-and-monitor-experiments/manage-runs/manage-runs.ipynb) and looking at properties of each run: 

I suspect the properties that you listed above are specific to your environment and situation. 

In general, possible properties mirror the REST API properties with some additional additional properties added. See for example:
https://docs.microsoft.com/en-us/rest/api/azureml/runtracking/runs/getdetails
https://docs.microsoft.com/en-us/rest/api/azureml/runs/startlocalrun#runconfiguration

Will investigate how to make clearer.

**Comment by vmagelo** [comment]
We reviewed the run class and improved the docs around properties and what default properties will show. Changes will appear in next SDK release in a week or two.
