### ISSUE TITLE
Link does not work at the en of page...

### ISSUE THREAD

**Issue by initmahesh** [Azure/MachineLearningNotebooks#850]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/track-and-monitor-experiments/using-mlflow/train-local/train-local.ipynb

on the end of page there in Next Step section  -> Links are returning 404 error ...

Next steps
Try out these notebooks to learn more about MLflow-Azure Machine Learning integration:

**_

1. Train a model using remote compute on Azure Cloud
2. Deploy the model as a web service

_**

**Comment by YutongTie-MSFT** [comment]
@initmahesh 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by jpe316** [comment]
@akshaya-a

**Comment by lostmygithubaccount** [comment]
@shivp950

**Comment by salilbapat** [comment]
Those notebooks were old and not fully working. they have been removed
