### ISSUE TITLE
the image can not build.

### ISSUE THREAD

**Issue by oo2316oo** [Azure/MachineLearningNotebooks#851]
would you mind let us know who this work? we tried it, but can not see any image build in the portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 890c70c7-0502-35b1-5e4d-b0db738332bb
* Version Independent ID: f0636a71-27c7-30d7-e2a0-a4953227ce5d
* Content: [azureml.core.environment.ImageBuildDetails class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.imagebuilddetails?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.ImageBuildDetails.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.ImageBuildDetails.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@oo2316oo 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by j-martens** [comment]
@YutongTie-MSFT this is not a doc question but a product question. please assign to product team. thank you

**Comment by vizhur** [comment]
@oo2316oo hard to guess what is not working for you as you did not provide any example but let me try :).

After you instantiated environment you can register it and build it. You can build it locally by calling build_local() or run a cloud docker image build for your environment by calling registered_env.build(ws). I suspect you doing that.
so, build() returns ImageBuildDetails object and you can check the status, acr build log url, stream an output or get the log from docker image build. Portal does not track image build on your workspace, AzureML just queues a task to Azure Container Registry to start an image build for a docker file specified for your environment.

Hope this helps

**Comment by YutongTie-MSFT** [comment]
@oo2316oo 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
