### ISSUE TITLE
programmatically get list of available regions

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/MachineLearningNotebooks#853]
How do I programmatically get the list of regions? I don't want to get the strings wrong, and want to automate creating a workspace per region.

From the `create` documentation I can see the list of supported regions, but is there a way to get a list of the strings (e.g. 'southcentralus') from the Python SDK? How? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90efe042-27ac-6e77-9292-10df77bb1c36
* Version Independent ID: 3b9f2576-7d3f-00f8-0afe-549960520f08
* Content: [azureml.core.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace(class)?view=azure-ml-py#create-name--auth-none--subscription-id-none--resource-group-none--location-none--create-resource-group-true--sku--basic---friendly-name-none--storage-account-none--key-vault-none--app-insights-none--container-registry-none--cmk-keyvault-none--resource-cmk-uri-none--hbi-workspace-false--default-cpu-compute-target-none--default-gpu-compute-target-none--exist-ok-false--show-output-true-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@lostmygithubaccount Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by ram-msft** [comment]
@j-martens Can you please check on this.

**Comment by j-martens** [comment]
@ram-msft - Please reach out to product team for information on whether this is possible or not. Not a doc bug at this point.
