### ISSUE TITLE
what is the setup method? why can you set default clusters? 

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/MachineLearningNotebooks#854]
confused by the `setup` method/documentation, and a few of the others  - should these be exposed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90efe042-27ac-6e77-9292-10df77bb1c36
* Version Independent ID: 3b9f2576-7d3f-00f8-0afe-549960520f08
* Content: [azureml.core.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace(class)?view=azure-ml-py#create-name--auth-none--subscription-id-none--resource-group-none--location-none--create-resource-group-true--sku--basic---friendly-name-none--storage-account-none--key-vault-none--app-insights-none--container-registry-none--cmk-keyvault-none--resource-cmk-uri-none--hbi-workspace-false--default-cpu-compute-target-none--default-gpu-compute-target-none--exist-ok-false--show-output-true-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Workspace(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@lostmygithubaccount we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@lostmygithubaccount thanks for your feedback. setup() is now deprecated. Instead, use create() to create a new workspace, or get()/from_config() to retrieve an existing workspace.

@j-martens can we proceed to remove setup() method from documentation?

**Comment by j-martens** [comment]
@GiftA-MSFT -  the engineering team must remove it from the doc strings. Please assign to Akshaya Annavajhala

**Comment by GiftA-MSFT** [comment]
@j-martens there is warning note. Thanks for your feedback. Will proceed to close.
![image](https://user-images.githubusercontent.com/51332022/76670552-87a51000-6567-11ea-8eb5-c9e4927f6a4a.png)

**Comment by lostmygithubaccount** [comment]
should the warning also be in documentation? not seeing it there
