### ISSUE TITLE
Compute Instance behind VNET - restrict public access

### ISSUE THREAD

**Issue by michalmar** [Azure/MachineLearningNotebooks#857]
I want to provision Compute Instance behind VNET but also to access it **ONLY** through that VNET, so basically get rid of public IP and use predefined NSG - but couldn't find how. 

Also in this VNET setup, I am not able to access Jupyter server/notebooks under the Private IP of the Compute Instance.

**Comment by ram-msft** [comment]
@michalmar Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by ram-msft** [comment]
@michalmar Thanks. Enabling VNet for compute instance and private IP are orthogonal. 
You can put compute instance behind a VNet using the steps mentioned in [this ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-enable-virtual-network#compute-instance) doc.

We’re working on enabling private IP for compute instance in near future. Until we do that you still need to use NSGs as defined in the [doc](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-enable-virtual-network#compute-instance).

**Comment by ram-msft** [comment]
@michalmar We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by michalmar** [comment]
Can be closed. Thanks a lot!
