### ISSUE TITLE
Compute Instance LOGS access when creation FAILED

### ISSUE THREAD

**Issue by michalmar** [Azure/MachineLearningNotebooks#858]
I cannot get logs when Compute Instance provisioning fails. Where the logs are created?

![image](https://user-images.githubusercontent.com/16072588/76574299-2aa05000-64bc-11ea-895c-a6acc8088ac0.png)

**Comment by ram-msft** [comment]
@michalmar Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by ram-msft** [comment]
@michalmar Can you please add more details about the SDK version that you are using and min_nodes used for creating the compute instance.

**Comment by michalmar** [comment]
@ram-msft I am not using any specific SDK - running from latest Workspace (ml.azure.com) in Azure. As per min nodes: set to 0 (zero).

**Comment by ram-msft** [comment]
@maxluk Can you please check on the compute Instance - creation Logs.
