### ISSUE TITLE
`user_managed_dependencies` and `conda_dependencies_file`

### ISSUE THREAD

**Issue by usuyama** [Azure/MachineLearningNotebooks#859]
Is it possible to use `conda_dependencies_file` with `user_managed_dependencies`?

For example, when we use a custom Docker image with a custom Python environment (i.e. using interpreter_path), would be great if we can specify `conda_dependencies_file` for additional dependencies on top of the Docker image.

In other words, can we use conda_dependencies_file with a custom Docker image?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e4ad40e-a088-cc58-220a-4d022206d0a1
* Version Independent ID: 9650bc0c-2c1e-6968-559f-94684abadadf
* Content: [azureml.core.environment.PythonSection class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.pythonsection?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.PythonSection.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.PythonSection.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@usuyama Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by ram-msft** [comment]
@usuyama Can you please add more details about the custom docker image that you are trying. A custom image to be used as base image. If no base image is given then the base image will be used based off of given runtime parameter.

Use a custom environment
If you want more control over how your model is run, if it uses another framework, or if it has special runtime requirements, you can instead specify your own environment and scoring method. Custom environments can be used for any model you want to deploy.

Specify the model's runtime environment by creating an Environment object and providing the CondaDependencies needed by your model.

from azureml.core import Environment
from azureml.core.conda_dependencies import CondaDependencies


environment = Environment('my-sklearn-environment')
environment.python.conda_dependencies = CondaDependencies.create(pip_packages=[
    'azureml-defaults',
    'inference-schema[numpy-support]',
    'joblib',
    'numpy',
    'scikit-learn'
])
When using a custom environment, you must also provide Python code for initializing and running your model.

**Comment by usuyama** [comment]
@ram-msft We're using a custom docker image for NVIDIA/apex, which cannot be installed from requirements.txt file or conda.yml file (a known issue).

Other dependencies can be installed from pip/conda, so I was wondering if we can use `pip_packages` parameter to install additional libraries on top of our custom docker image. It's desirable because we don't need to build new docker images to add more pip/conda libraries.

**Comment by ram-msft** [comment]
@usuyama If `pip_packages` is not specified, `azureml-defaults` will be added as the default dependencies. User specified `pip_packages` dependencies will override the default values. If you want to  `pin_sdk_version` is set to true, pip dependencies of the packages distributed as a part of Azure Machine Learning Python SDK will be pinned to the SDK version installed in the current environment.

**Comment by j-martens** [comment]
@Rastala please confirm. Thank you!

**Comment by saachigopal** [comment]
By default, Azure ML will build a Conda environment with dependencies you specified, and will execute the run in that environment instead of using any Python libraries that you installed on the base image. So by keeping user_managed_dependencies = False, a custom Docker image can be used with conda dependencies but if the image has a python environment it will not be used.
