### ISSUE TITLE
tags from AutoML runs don't show on the new portal

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#861]
Trying to tag AutoML runs on the new portal doesn't show any of the tags being fed in vs the old experience that shows the tags being fed. (snapshots below) 
### Old portal
![old portal](https://user-images.githubusercontent.com/17963295/76658572-aab4cd00-6531-11ea-82f6-b20e9c131eec.png)
### New Portal
![new portal](https://user-images.githubusercontent.com/17963295/76658716-f49db300-6531-11ea-970c-e62f961ce220.png)

**Comment by skasturi** [comment]
@chnldw

**Comment by MohitGargMSFT** [comment]
@jadhosn Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by cartacioS** [comment]
Hello @jadhosn, you can view the tags for a run if you go to the experiments tab and click on your experiment. 
![image](https://user-images.githubusercontent.com/9436875/89448375-63abbc00-d70c-11ea-9117-46861ceb0f00.png)

If you still have a question, please let us know. If this resolves your question, please do close this issue :).

Thanks!
