### ISSUE TITLE
Page is not containing the proper information under attributes

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#863]
Attribute names are missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
* Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
* Content: [azureml.core.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py#methods)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@omartin2010 we will review your feedback and get back to you shortly. Thanks.

**Comment by vmagelo** [comment]
Thanks. Something is broken in the build so that Attribute names are not showing up. We are investigating.

**Comment by vmagelo** [comment]
Attributes are back in place. Sorry about that.

**Comment by j-martens** [comment]
Thanks for your report. It was helpful to identify quickly. We will now proceed to close this thread.
