### ISSUE TITLE
Attrubutes section looks like it's missing the name of the attributes

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#864]
We see this :
```
Attributes
DEPRECATED. Azure automatically detects and uses the NVIDIA Docker extension when it is available.
```
but this doesn't tell us which attribute is deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74ef100-d06b-b9c5-bbfb-78120ee794c5
* Version Independent ID: a0fdc0b6-3d00-2886-895f-7aa502aab668
* Content: [azureml.core.environment.DockerSection class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.dockersection?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.DockerSection.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.DockerSection.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@omartin2010 we will review your feedback and get back to you shortly. Thanks.

**Comment by vmagelo** [comment]
Thanks. Something is broken in the build so that names are not showing up. We are investigating.

**Comment by vmagelo** [comment]
Attribute names are back - in this case indicating what was deprecated. Thanks.

**Comment by j-martens** [comment]
Thanks for your report. It was helpful to identify quickly. We will now proceed to close this thread.
