### ISSUE TITLE
AutoML Beer Forecasting Notebook: Pyplot issues

### ISSUE THREAD

**Issue by adgustaf** [Azure/MachineLearningNotebooks#866]
Hi All,

I ran through the [beer forecasting notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb) and I found some strange code regarding how pyplot is used/called.  I'll enumerate them below.  My guess is that these issues pop up in other notebooks as well and the issue is not limited to just the beer forecasting notebook.

**Redundant pyplot commands**
We only need to import pyplot once, and the traditional way to do it is:

`import matplotlib.pyplot as plt`

Note that one can equivalently do

`from matplotlib import pyplot as plt`

though IMO this is somewhat less readable.  This is what is done in in the “Setup” portion of the notebook, and that’s OK.  However, somewhat strangely later in the “Data” section of the notebook the following appears twice within the same code box, which is a bit sloppy IMO:

`from matplotlib import pyplot`

There are then code calls using both plt and pyplot.  Again, seems a bit sloppy.  While they point to the same library, I’m not sure what the implications are of mixed use of plt and pyplot are.  Even if they are aliases for the same bit of code, it looks like this code has never been proofread so to speak, if I may say so respectfully.  So this could probably be cleaned up?

**Figure size meta info displayed in plots**
When running the notebook, the current code displays 

"Figure size 432x288 with 0 Axes"

When `plt.show()` is run.  This again seems sloppy, if I may say so respectfully. The solution is to run the line

`plt.figure(figsize=(20,10))`

before running `plt.tight_layout()`

I can make these minor fixes if you like and do a PR... would that be helpful?   Please let me know.  Thanks...

- Adam

**Comment by ram-msft** [comment]
@adgustaf Thanks for the feedback. We will update you shortly.

**Comment by adgustaf** [comment]
Hi @ram-msft ... unfortunately I'm having issues pushing my local branch to remote, for some reason.  Forgive me for this I'm somewhat of a github newbie.  Set up keys according to 

https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

yet when I run the following in git bash

`git push -u origin adgustaf/beer-notebook-pyplot-fix`

(that's the branch I called it locally) I get 

```
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
ERROR: Permission to Azure/MachineLearningNotebooks.git denied to adgustaf.
fatal: Could not read from remote repository.
```

Not sure why (I'm a statistician more so than a programmer!).  Anyway, there's just one cell in the notebook that needs to be changed, the first sell in the "Data" section.  Here's what it should be changed to if you would like to make a PR yourself....

```
import pandas as pd
from pandas import DataFrame
from pandas import Grouper
from pandas import concat
from pandas.plotting import register_matplotlib_converters

register_matplotlib_converters()
plt.figure(figsize=(20, 10))
plt.tight_layout()

plt.subplot(2, 1, 1)
plt.title('Beer Production By Year')
df = pd.read_csv("Beer_no_valid_split_train.csv", parse_dates=True, index_col= 'DATE').drop(columns='grain')
test_df = pd.read_csv("Beer_no_valid_split_test.csv", parse_dates=True, index_col= 'DATE').drop(columns='grain')
plt.plot(df)

plt.subplot(2, 1, 2)
plt.title('Beer Production By Month')
groups = df.groupby(df.index.month)
months = concat([DataFrame(x[1].values) for x in groups], axis=1)
months = DataFrame(months)
months.columns = range(1,13)
months.boxplot()
plt.show()
```

Note that the line `from matplotlib import pyplot as plt` had already been run in the first notebook cell.

**Comment by adgustaf** [comment]
Again, please do check other notebooks as they likely have similar issues.

**Comment by cartacioS** [comment]
Hi @adgustaf seems the notebook has been updated as I only see one reference to 'from matplotlib import pyplot as plt'. Can we please close this issue? Thanks!

**Comment by cartacioS** [comment]
Seems this has been addressed. Thanks! #please-close
