### ISSUE TITLE
AutoML Beer Forecasting Notebook: General Feedback

### ISSUE THREAD

**Issue by adgustaf** [Azure/MachineLearningNotebooks#867]
Hi All,

I'm just attempting to give some feedback on some issues that I encountered when running the [beer forecasting notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb).  I hope this feedback is helpful in designing notebooks that are a bit more user-friendly.

This feedback is less "issues" and more of "what I'd imagine a user would feel running this notebook for the first time" type of comment.  

My intent is to be as respectful as possible in providing such feedback, so I hope what I write below is seen as constructive.  

The overall theme is there doesn't seem to be much compassion for the user who is new to AML and/or AutoML and/or these notebooks.  Generally it assumes only one of many possible means by which the notebook could be executed, relies on helper code that is not documented/commented very well, and seems (perhaps?) to assume one has run examples before (perhaps in regression or classification) whereas assuredly the user may only be interested in forecasting.

Specific instances of this theme are enumerated below:

**Lack of Preqreqs**
It should clearly state at the very top of the notebook in its own dedicated section (i.e., bold letters) what one should have completed before running the notebook.  This should be in an itemized list (use markdown's lists).  

**Lack of Use Cases**
If this notebook is only to be run locally with remote compute, clearly state as much after the prereq section.  Specifically state what are the recommended (better yet) required methods for running these notebooks.   More on this point next....

**Local w/ Remote Compute vs. Compute Instance in Machine Learning Workspace**
My pathway to doing these before now has been to clone the repo locally and run with remote compute.  This requires running the configuration.ipynb notebook and making sure that’s all set up beforehand (following the general instructions).  The notebooks seems to assume this path.  But
assuredly Compute Instance + Jupyter Notebook is also an intended use case (I believe this would be quite common for those learning AutoML).  

So my number one suggestion is to make these notebooks aware of whether or not you’re using a notebook on a compute instance aka a notebook VM; also, be sure to prevent the user (via the previous section message) regarding any use cases not intended.  From what I see in that notebook, perhaps one needs to break up the initial part of the notebook into two chunks: 

(1)	If running on notebook VM aka compute instance and then launched a jupyter notebook/lab/etc., give instructions on how to copy all the relevant files to the right place (you can do this within Jupyter Notebook).  Alternatively SSH/SCP (presuming they’ve set it up?  I’ve yet to actually do this myself).  I think then the rest of the “AmlCompute Instance” session still applies, as it will make a training cluster called “cpu-cluster” ultimately within that compute instance.  
(2)	Else (if) running local + remote compute then warn user to run configurator.ipynb (and direct them to it).

There may be other steps to consider (see the Datastore sections below).

Incidentally, some colleagues of mine reported that JupyterLab from compute instance works fine for "cloning" the notebook VMs.  I couldn't get this to work w Jupyter Notebook ... I had just uploaded everything myself from w/in Jupyter Notebook once it was running.  

**Split Training Data?  What's this?**
This section needs a lot of explanation.  Firstly, at the very least there needs to be explanation about what the `helper.py` file provides.  Better is comments (in particular docstrings) for every single function in `helper.py`.  Note that only one function has a docstring, and it isn’t a very good docstring at that, in my opinion.   Additionally every use of `helper.py` in the notebook **needs** a markdown cell explaining what’s going on.  

It’s reasonable to assume that users who are running these notebooks in this manner understand training/test splits.  It is unreasonable to assume they are going to be happy parsing a python file that has little/no explanation of what it’s doing and why.  At a bare minimum this must be provided in my opinion, in comments/docstrings/markdown/etc. (actually in all of the above).

A general rule of thumb in my opinion is to *pretend that you’re seeing this for the very first time*, and be brutally honest about it.  I don’t think even users with a lot of background in data science would see this and feel it’s at all straightforward, and it certainly looks bad in my opinion to just call a bunch of helper code that has no explanation to it whatsoever.  

**Datastore?  What's this?  What about when running from Jupyter Notebook?**
Again, this section needs a lot of explanation.  Let's not assume users are comfortable with Azure concepts either (if so, prereqs statement at the top of each notebook!!!!!).  It’s easy enough for users to skim if they’re already familiar, but invaluable if they’re not too familiar.  

Some of this information may have been explained already in the configuration.ipynb file (which it’s not clear they’ll have to run if they’re using a compute instance + jupyter notebook, so it may need to be repeated here).

I believe what is happening here is that training and test splits are being created locally, and saved as .csv files in the same directory as where the notebook is running.  Then these are being uploaded to a datastore which the training cluster consumes.  This may seem obvious from the code, but there should be markdown explaining it.

As for making these notebooks local but then run remote vs. notebook VM aware, is there a way to avoid this step?  I.e., if I’m running on a notebook VM, I think I’ve already set up blob store when I made the machine learning workspace, no?  I’m confused here.  

**Train section: layout…**
I think this section should be broken down (in the typical markdown fashion by using sections, subsections, subsubsections, etc.) into subsections Configuration, Run, and Retrieve the Best Model… only the third section currently is there.

**Train section: configuration issues and blacklisting...**
The table is given without any explanation.  Literally, write “the following table summarizes the configuration settings of the automl experiment when AutoMlConfig is called” or something of that nature.  It was not clear to me at first glance that this table corresponded to the automl_config object created by AutoMLConfig.  While one can easily deduce that later on, I think it's best to make sure you are asking the least bit possible of the users.  Again, this may be the first notebook they've run after the configuration notebook (if that).

Additionally, the properties and the descriptions of those properties are a subset of those actually used in the AutoMLConfig call.  Even if they seem self-explanatory, provide the ones used in the call. Again, you should ask the least bit possible of the users in a tutorial.  Again, imagine you’re seeing this for the first time.

I think you should also give recommendations for models to blacklist (as they take a while to train).  We should be sure to update these recommendations as we make fixes to improve the speed of such methods.

Why are certain parameters passed in as a dictionary of kwargs (i.e., the automl_settings) to this function?  Is this necessary?  Note this is the only place in the notebook that automl_settings is used.  Would it be better to either use all kwargs for all settings (if possible) rather than 3 seemingly random settings?  Note that the docstring for AutoMLConfig puts some of the parameters into kwargs that are currently explicitly put into the call itself in the notebook (e.g, verbosity.  Not sure what the best practice is here just want it to be clear for the user what the “usual” approach is and to adhere to it.

Incidentally, the docstring to AutoMLConfig is fantastic.  It’d be nice to have something similar for the helper.py and infer.py files (the latter having a better set of docstrings than the former).

**Train section: run issues....**
What is this about 10 iterations of model search?   Did you not just say “max_concurrent_iterations=4”?  What does the 10 iterations refer to?  I honestly don’t know.

I think it'd help to explain why “show_output=False” is used in experiment.submit.  If I understand correctly, if you show the output, you'll not get the nice experiment and id table below with links to following the experiment runs, and you'll hang on that cell waiting for output.  Is that correct?

By the way, If these notebooks take more than a few minutes to run , there needs to be a major warning about it I think.  While some of us may know this already, again think about a user seeing this for the first time and expecting results relatively quickly.

**Evaluation:**
This seems mostly okay I think except for two issues.  

Firstly, there’s a lot of code that is used but isn’t explained.  Before each code cell, just provide a simple explanation of what it’s doing, even if it seems obvious to you.  Again, imagine seeing it for the first time.  Though the docstrings for `infer.py` are better, I still have the same feeling about it as I do for `helper.py`.  The user should be able to understand what this code is doing.

Secondly, the “run_inference” terminology is not ubiquitous among data scientists even if it’s used in AutoML.  I presume this just means scoring the models on the test data?  Let’s again imagine the scenario where a user comes across this notebook as their first experiment in AutoML (because they’re interested only in forecasting, and “beer” is first among the notebooks).  

I hope the above helps!  I'd imagine similar comments apply for the remaining notebooks (though I haven't recently run them).  

- Adam

**Comment by RohitMungi-MSFT** [comment]
@adgustaf Thanks for your honest feedback. We shall pass this feedback to our internal team for Machine Learning notebooks to look at the structure of the notebooks and recommend to add more details to the steps required while using the notebooks. 
Tagging @rastala @vizhur for visibility

**Comment by cartacioS** [comment]
FYI @jialiu103 @EricWrightAtWork @ahyerman

**Comment by jadhosn** [comment]
@cartacioS As a first hand user of AutoML and AutoML config, building AutoML experiments on daily basis lately, I echo most of what @adgustaf mentioned above. Some information even contradicts between docstring, docs and sample notebooks. 

For example, `max_concurrent_iterations` jumps between being the number of iterations <= number of cores (so a single machine with 4 cores should be <=4), then in the docstring, it switches to nodes (which a cluster with 4 nodes, and each node having cores, so that's max <= 16?) just as an example

**Comment by adamthorne** [comment]
I think this is an excellent summary. I would still love to know what is with splitting the training dataset into train and valid (my assumption is that its used somehow for model scoring but would love to be clear!!!!)

**Comment by cartacioS** [comment]
Hi @adamthorne thanks for the great summary. We'll keep these notes on hand as we develop future notebooks and keep in mind usability. Since this is more of guidelines and overall feedback, I'll close this issue :) 
#please-close
