### ISSUE TITLE
 data_script and "get_data.py" are mentioned but AFAIK they are not supported in the last version

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#868]
data_script and "get_data.py" are mentioned but AFAIK they are not supported in the last version of AutoMLConfig class.

Sentence above:
"The file path specified in the data_script configuration parameter must end with a file named "get_data.py".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8e0e0c5-990a-20c3-3f18-ac578dad684c
* Version Independent ID: 6d406c3e-d2f0-6f37-6d34-275303567e4f
* Content: [azureml.pipeline.steps.automl_step.AutoMLStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.automl_step.automlstep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.automl_step.AutoMLStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.automl_step.AutoMLStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by CESARDELATORRE** [comment]
Basically, data_script and "get_data.py" are deprecated so it should be removed from the docs.
Also, related, the AutoMLStep class reference doc should have richer information.

**Comment by j-martens** [comment]
@vmagelo

**Comment by vmagelo** [comment]
We made updates to the doc which will go appear in next SDK release in 1-2 weeks.
