### ISSUE TITLE
Unable to perform AutoML model training with Tensorflow. Reports "WARNING - tensorflow module is not installed"

### ISSUE THREAD

**Issue by lufthavn** [Azure/MachineLearningNotebooks#869]
I am interested in utilizing TF algorithms as part of automated training of a model using AutoML. AutoML by itself works fine in my notebook, but when I try to enable Tensorflow by passing `"enable_tf": True` to the AutoMLConfig class, I get the warning `WARNING - tensorflow module is not installed`. I have tried to alter a demo notebook to include Tensorflow algorithms in a regression task to illustrate my approach and problem:
![image](https://user-images.githubusercontent.com/7838029/76902664-ca832280-689c-11ea-8db1-34e01b5d1316.png)
 
I have followed several samples of how to setup my environment, including from the docs and in the [Automated ML Introduction](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning) document. I haven't been able to make this warning go away. I have tried installing Tensorflow manually in my environment with pip or conda but that didn't make a difference.

I am at a loss as to what to do to make this warning disappear, so that I can use Tensorflow algorithms in automated ML. 
It is very likely that I'm totally wrong in my approach here, I haven't worked a great deal with Python, and the Anaconda and Jupyter Notebooks are new tools to me.

**Comment by skasturi** [comment]
@omkarmore83 @naraymad1

**Comment by ram-msft** [comment]
@lufthavn Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by lufthavn** [comment]
Thank you. Let me know if you need any more info from me.

**Comment by naraymad** [comment]
What is the version of python in your environment? Tensorflow is supported only under python 3.6 and version 1.12.0. Please install tensorflow 1.12.0 under python 3.6 and set enable=True, whitelist_models = ['TensorFlowDNN', 'TensorFlowLinearRegressor] and featurization="off" in automl_config.

**Comment by lufthavn** [comment]
Thank you. With your help I was able to get solve my problem, but I encountered another one right afterwards. The same cell now fails with this error: 
```
---------------------------------------------------------------------------
ConfigException                           Traceback (most recent call last)
<ipython-input-33-ecba6634f7f4> in <module>
     14                              training_data = train_data,
     15                              label_column_name = label,
---> 16                              **automl_settings
     17                             )

~\Anaconda3\envs\tfenv\lib\site-packages\azureml\core\_experiment_method.py in wrapper(self, *args, **kwargs)
     91             """
     92             ExperimentSubmitRegistrar.register_submit_function(self.__class__, submit_function)
---> 93             return init_func(self, *args, **kwargs)
     94         return wrapper
     95     return real_decorator

~\Anaconda3\envs\tfenv\lib\site-packages\azureml\train\automl\automlconfig.py in __init__(self, task, path, iterations, primary_metric, compute_target, spark_context, X, y, sample_weight, X_valid, y_valid, sample_weight_valid, cv_splits_indices, validation_size, n_cross_validations, y_min, y_max, num_classes, featurization, lag_length, max_cores_per_iteration, max_concurrent_iterations, iteration_timeout_minutes, mem_in_mb, enforce_time_on_windows, experiment_timeout_hours, experiment_exit_score, enable_early_stopping, blacklist_models, exclude_nan_labels, verbosity, enable_tf, enable_cache, model_explainability, whitelist_models, enable_onnx_compatible_models, enable_voting_ensemble, enable_stack_ensemble, debug_log, training_data, validation_data, label_column_name, weight_column_name, **kwargs)
    848                 elif set(whitelist_models).issubset(set(blacklist)):
    849                         raise ConfigException.create_without_pii(
--> 850                             "Can not find models to train, all whitelisted models are also in blacklist")
    851 
    852         for key, value in kwargs.items():

ConfigException: ConfigException:
	Message: Can not find models to train, all whitelisted models are also in blacklist
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Can not find models to train, all whitelisted models are also in blacklist"
    }
}
```

The Python code in the cell looks like this:
```
automl_settings = {
    "n_cross_validations": 3,
    "primary_metric": 'r2_score',
    "enable_early_stopping": True, 
    "experiment_timeout_hours": 0.3, #for real scenarios we reccommend a timeout of at least one hour 
    "max_concurrent_iterations": 4,
    "max_cores_per_iteration": -1,
    "verbosity": logging.INFO,
    "whitelist_models": ['TensorFlowDNN', 'TensorFlowLinearRegressor'], 
    "enable_tf": True
}

automl_config = AutoMLConfig(task = 'regression',
                             training_data = train_data,
                             label_column_name = label,
                             **automl_settings
                            )
```

I have tried to "wipe" the blacklist by passing blacklist_models as None and empty list, but neither had an effect.

**Comment by naraymad** [comment]
You have to set featurization="off", only numeric data is supported for Tensorflow

automl_settings = {
    "n_cross_validations": 3,
    "primary_metric": 'r2_score',
    "enable_early_stopping": True, 
    "experiment_timeout_hours": 0.3, #for real scenarios we reccommend a timeout of at least one hour 
    "max_concurrent_iterations": 4,
    "max_cores_per_iteration": -1,
    "verbosity": logging.INFO,
    "whitelist_models": ['TensorFlowDNN', 'TensorFlowLinearRegressor'], 
    "enable_tf": True,
    "featurization": "off"
}
.

**Comment by lufthavn** [comment]
My mistake, I just realized that. How come automatic featurization is not supported?

**Comment by naraymad** [comment]
Featurization makes the dataset sparse and DNN needs dense dataset.
