### ISSUE TITLE
Mojibake in auto-ml-classification-credit-card-fraud.ipynb 

### ISSUE THREAD

**Issue by justinormont** [Azure/MachineLearningNotebooks#870]
[Mojibake ](https://en.wikipedia.org/wiki/Mojibake)in dataset reference:
![image](https://user-images.githubusercontent.com/4080826/76910383-14ebab80-686b-11ea-9ab6-b3efaa8fb243.png)

https://github.com/Azure/MachineLearningNotebooks/blob/e0ea99a6bb284ada8c4044f2fb8ce6481863519f/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb#L422-L432

See Mojibake (https://en.wikipedia.org/wiki/Mojibake)

**Comment by ram-msft** [comment]
@justinormont Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by swatig007** [comment]
@jialiu103 can you pls take a look at this notebook issue?

**Comment by jialiu103** [comment]
@justinormont @anupsms are following up on this issue.

**Comment by deepakmukunthu** [comment]
@justinormont @anupsms any updates?

**Comment by CESARDELATORRE** [comment]
@justinormont @anupsms any update on this issue?

Thanks,

**Comment by skasturi** [comment]
This should be fixed in the next release.

**Comment by skasturi** [comment]
Completed the PR. This should be fixed in the next release.

**Comment by justinormont** [comment]
Thanks @skasturi for the swift PR. I'll close the issue since your fix is in the release cycle.
