### ISSUE TITLE
Support for user-assigned managed identity missing

### ISSUE THREAD

**Issue by denniseik** [Azure/MachineLearningNotebooks#872]
When using user-assigned identities e.g. on App Service, a client or object id must be provided as an argument to the MSIAuthentication object. AML's authentication object doesn't allow for this, breaking the scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeee5fbb-56db-817e-f095-928ea13e478e
* Version Independent ID: 10f2c77a-1dd7-29bb-7e04-c57885c39813
* Content: [azureml.core.authentication.MsiAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.msiauthentication?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.MsiAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.MsiAuthentication.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@denniseik 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by atbagga** [comment]
@j-martens I am facing the same issue. Any updates on this?
@denniseik  Were you able to find some way around it?

**Comment by PeterCLu** [comment]
@atbagga, @denniseik 
Currently, only system identity is supported. We currently don't support user assigned msi in production. We will add a note in the reference page to clarify this issue.

**Comment by vmagelo** [comment]
We added the note. Change will appear with next SDK release in 1-2 weeks.
