### ISSUE TITLE
Making lack of Azure Data Lake Gen 2 support more explicit

### ISSUE THREAD

**Issue by masoncusack** [Azure/MachineLearningNotebooks#873]
Hi folks,

I work in Microsoft's Commercial Software Engineering org and we are working with a major Azure customer to implement AML pipelines to mature and automate their path from data science to production.

We've come across the fact that Azure Datalake Gen 2 is specifically not supported by the DataReference SDK class at this time. However, rather than catching this in the documentation, it was only when we attempted to use it that we found this.

I and I think other developers would appreciate a more explicit warning in the Datastore and DataReference docs, that in fact Gen 2 is not currently supported as a DataReference, and therefore as an input to, for example, PythonScriptSteps. 

It should be made clear that by supporting AzureDataLakeDatastore DataReferences, we mean Data Lake Gen 1, and not Gen 2. This clarity would have been really helpful.

Output to stderr resulting from this issue:

```	
Message: Activity Failed:
{
    "error": {
        "code": "ServiceError",
        "message": "DataLocation raw_programmes DataReference Type AzureDataLakeGen2 is not supported",
        "details": []
    },
    "time": "0001-01-01T00:00:00.000Z"
}
	InnerException None
	ErrorResponse
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"ServiceError\",\n        \"message\": \"DataLocation raw_programmes DataReference Type AzureDataLakeGen2 is not supported\",\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b57ef22-d9c6-3066-9489-a368b354357a
* Version Independent ID: cffee3ba-8d7a-ce13-4975-825d8195081b
* Content: [azureml.data.data_reference.DataReference class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.data_reference.datareference?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.data_reference.DataReference.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.data_reference.DataReference.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by SturgeonMi** [comment]
Hi Mason,

Currently ADLSGen2 datastore can be registered as AML datastore, and data can be registered as Dataset, and Dataset can be used as input of pipeline steps (like PythonScriptStep). 
AML Data4ML team actually recommend to use Dataset but not DataReference as input (or output) of pipeline steps.

Please check related doc here: 
Train with datasets in Azure Machine [Learning](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets) and **sample notebook** here: [Train with datasets using pipelines](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb)

I think we need to modify Pipeline related docs to recommend Dataset rather than Datareference.

**Comment by masoncusack** [comment]
Hi Xun, thanks for the insight.

That kind of forces adoption of the Dataset functionality, but I will look into how quickly we can use this as a workaround. We were quite enjoying the modularity of being able to version raw data in ADLS Gen 2, with new versions created by Azure Data Factory, then pulling this in for preprocessing directly.

So just FYI, In think the ability to pull in data directly via DataReference is really useful, in case the customer already has an existing external setup for dataset versioning.

I'll let you know how I get on creating and using Datasets.

**Comment by masoncusack** [comment]
Hi again, 

I'm noticing that when trying to inspect a dataset in a workspace we've authenticated with using a service principal, I'm prompted to sign into my own account via the browser, and retrieval therefore fails.

This is using Dataset.get_by_name():

```
    # Service principal auth necessary for local dev
    svc_pr = (
        ServicePrincipalAuthentication(
            tenant_id=os.getenv("TENANT_ID"),
            service_principal_id=os.getenv("SERVICE_PRINCIPAL_ID"),
            service_principal_password=args.servicePrincipalSecret,
        )
        if args.servicePrincipalAuth
        else None
    )

    # Retrieve AML Workspace
    ws = Workspace.get(
        name=os.getenv("AML_WORKSPACE_NAME"),
        subscription_id=os.getenv("SUBSCRIPTION_ID"),
        resource_group=os.getenv("RESOURCE_GROUP"),
        auth=svc_pr,
    )

    print("\nWorkspace retrieved: " + str(ws.name))

    # Set up datastore
    datastore = adl_datastore_setup(
        workspace=ws,
        datastore_name=os.getenv("RAW_DATASTORE_NAME"),
        container_name=os.getenv("RAW_CONTAINER_NAME"),
        storage_acct_name=os.getenv("ADL_STORAGE_ACCOUNT_NAME"),
        tenant_id=os.getenv("TENANT_ID"),
        svcpr_id=os.getenv("SERVICE_PRINCIPAL_ID"),
        svcpr_secret=args.servicePrincipalSecret
    )

    dataset = Dataset.get_by_name(ws, name='my_dataset_name') # Will get latest
    print(dataset.to_pandas_dataframe())


```

**Comment by masoncusack** [comment]
I'm also getting the following error in validation when registering the Dataset. There is absolutely valid data at the path I'm pointing to:

`azureml.data.dataset_error_handling.DatasetValidationError: Cannot load any data from the specified path. Make sure the path is accessible and contains data.`

**Comment by SturgeonMi** [comment]
Created ICM and bug to track:
Incident 179527278 : dataset interactive auth issue 
Impediment 670833: "Cannot load any data from the specified path" for Parquet file in DataReference

**Comment by masoncusack** [comment]
Good news! I found that the issue with retrieving data from the specified path was an access issue, rather than to do with the actual mechanics of retrieval. Assigning my service principal/app registration the role Storage Blob Data Owner in RBAC allowed access, so I can now create and register a dataset from the targeted data.

I'll keep you updated on using the workaround of a Dataset as opposed to DataReference (the original plan) to potentially close out this issue.

Thanks for the eyes on this.

**Comment by masoncusack** [comment]
In the interest of getting ahead, is there a standard way of passing a Dataset as an output of one pipeline step to the input of another, when the two occur sequentially?

**Comment by masoncusack** [comment]
Hi again,

I'm finding that datasets are allowed as inputs but disallowed when created from PipelineData objects as outputs. For the same reason as before (processed_store below is an ADL Gen 2 Datastore):

Error:

```
 "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"ServiceError\",\n        \"message\": \"DataLocation preprocessed_activities_dataset DataReference Type AzureDataLakeGen2 is not supported\",\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
```

Code:

```
    preprocessed_activities_dataset = PipelineData('preprocessed_activities_dataset', datastore=processed_store).as_dataset()
    preprocessed_activities_dataset = preprocessed_activities_dataset.register(name='preprocessed_activities_dataset', create_new_version=True)
    preprocessed_programmes_dataset = PipelineData('preprocessed_programmes_dataset', datastore=processed_store).as_dataset()
    preprocessed_programmes_dataset = preprocessed_programmes_dataset.register(name='preprocessed_programmes_dataset', create_new_version=True)

    # Define preprocessing PythonScriptStep
    preprocessing = PythonScriptStep(
        script_name=preprocessing_script_name,
        name="Preprocessing",
        inputs=[
            input_programmes,
            input_programme_records,
            input_activities,
            input_programme_activities,
        ],
        outputs=[
            preprocessed_activities_dataset,
            preprocessed_programmes_dataset
        ],
        compute_target=workspace.compute_targets[training_compute_target],
        source_directory=preprocessing_source_directory,
        runconfig=retraining_config,
        allow_reuse=True,
    )

```

Is there a way to output to ADL Gen 2?

**Comment by masoncusack** [comment]
I've also converted an output dataset to a PipelineOutputTabularDataset to see if this would help. There still seems to be a DataReference in use under the hood, as the error is the same.

Code:

`preprocessed_activities_dataset = PipelineData('preprocessed_activities_dataset', datastore=processed_store).as_dataset().parse_delimited_files() # Should be PipelineOutputTabularDataset`

**Comment by YutongTie-MSFT** [comment]
@masoncusack Thanks for the information and pleaase keep eyes on the ticket. I am going to close this and we will use the ICM ticket to track this issue. 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.

@SturgeonMi Hi Xun, please also refer to the additional information.
