### ISSUE TITLE
Documentation of base_dockefile property

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#875]
Can we have, in particular for the `base_dockerfile` property, a 'real' example that works?
```
environment.docker.base_dockerfile = 'FROM mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04\n' \
            'RUN apt update && apt install -y apt-transport-https curl\n' \
            'RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -\n' \
            'RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list &gt; /etc/apt/sources.list.d/mssql-release.list\n' \
            'RUN apt update\n' \
            'RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17'
```
would be a good example. Others more simple are welcome but an example of a real working case is helpful. Also specify that the images needs to have python and anaconda (I believe these are requirements, not sure if `FROM ubuntu:latest` would actually work. But keep me honest here... :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74ef100-d06b-b9c5-bbfb-78120ee794c5
* Version Independent ID: a0fdc0b6-3d00-2886-895f-7aa502aab668
* Content: [azureml.core.environment.DockerSection class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.dockersection?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.DockerSection.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.environment.DockerSection.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@omartin2010 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YutongTie-MSFT** [comment]
@j-martens Hi Josee, could you please take a look of this document insight? Thanks.

**Comment by j-martens** [comment]
@YutongTie-MSFT - please assign to the product team for this area.

**Comment by vmagelo** [comment]
We added to the documentation to show how to docker_file with some docker commands. Thanks for the suggestion. The changes will go live with next SDK release in 1-2 weeks.

**Comment by omartin2010** [comment]
by the way, I still don't see any changes in the doc. Can you point me to them? I'm having to point someone to it and right now... it doesn't work. This FROM ubuntu thing, I believe is broken b/c conda isn't there.

**Comment by swanderz** [comment]
@j-martens on SO, [this question](https://stackoverflow.com/questions/62886435/using-a-custom-docker-with-azure-ml/62888135#62888135) was just asked. So I searched here for more info on `base_dockerfile`. Do we have anything I can point OP to?

**Comment by omartin2010** [comment]
I've just asked for a few more precisions because the `base_dockerfile` should be used when written this way. I've gotten this to work multiple times..

**Comment by vizhur** [comment]
@omartin2010 https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.dockersection?view=azure-ml-py

**Comment by omartin2010** [comment]
You’re right, I’ve asked the person on SO more precisions, i should’ve been clearer.
