### ISSUE TITLE
Failed to send request to .../datasets/parse

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#876]
Trying to register a dataset from the UI returning a send request failure

![image](https://user-images.githubusercontent.com/17963295/77108738-0246b300-69e0-11ea-9212-a4ec37473f53.png)

@MayMSFT

**Comment by jadhosn** [comment]
I tried doing the same through the SDK, it seems that a dataset was already registered using the same source file 

![image](https://user-images.githubusercontent.com/17963295/77111063-dfb69900-69e3-11ea-8e02-c668468f861f.png)

**Comment by MayMSFT** [comment]
yes. we current don't support registering the same source file as a different dataset. We are working on removing that limitation. 
As for the UI error, we will treat it as a bug to make sure we surface actionable error message.

**Comment by HarshUpadhyay** [comment]
It seems like a internet connection error in the UI rather than a non actionable error message. I just tried registering a duplicate dataset.
![image](https://user-images.githubusercontent.com/6505154/77114485-d4666c00-69e9-11ea-8053-44643ff79842.png)
