### ISSUE TITLE
bind_mode description

### ISSUE THREAD

**Issue by omartin2010** [Azure/MachineLearningNotebooks#877]
We can see it can be `mount` but what other modes are accessible? That should be documented.
Also, can we give an explicit example of `parameter_name` ? It seems like it's probably the PipelineParameter name, but I think we should be explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce88661d-a489-14f1-717e-4332629f8130
* Version Independent ID: 4c01a20c-2346-16f0-edc0-5c3e664b8b66
* Content: [azureml.pipeline.core.graph.PipelineDataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.pipelinedataset?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.graph.PipelineDataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.graph.PipelineDataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@omartin2010 we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@omartin2010  the document describes [bind_mode](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.pipelinedataset?view=azure-ml-py#parameters) as "_How the dataset should be made available, either **mount** or **download**"_  and [parameter_name](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.pipelinedataset?view=azure-ml-py#parameter-name) as "_pipeline parameter name of this pipeline dataset_".

**Comment by GiftA-MSFT** [comment]
@j-martens please review customer's feedback for doc enhancement. Thanks.

**Comment by omartin2010** [comment]
Feel free to reach out directly, I’m internal. Cheers
