### ISSUE TITLE
Acccelrated model training notebook fail on train steps with " AttributeError: 'With' object has no attribute 'value'"

### ISSUE THREAD

**Issue by initmahesh** [Azure/MachineLearningNotebooks#879]
tried the transfer learning notebook and getting below error as well 
                MachineLearningNotebooks/how-to-use-azureml/deployment/accelerated-models/accelerated-models-training.ipynb

6. Execute steps
You can run through the Transfer Learning section, then skip to Create AccelContainerImage. By default, because the custom weights section takes much longer for training twice, it is not saved as executable cells. You can copy the code or change cell type to 'Code'.
6.a. Training using Transfer Learning
In [15]:

%%time
# Launch the training
tf.reset_default_graph()
sess = tf.Session(graph=tf.get_default_graph())

with sess.as_default():
    in_images, image_tensors, features, preds, featurizer = construct_model(quantized=True)
    train_model(preds, in_images, img_train, label_train, is_retrain=False, train_epoch=10, learning_rate=0.01)    
    accuracy = test_model(preds, in_images, img_test, label_test)  
    print("Accuracy:", accuracy)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-11cf029d1f3d> in <module>
----> 1 get_ipython().run_cell_magic('time', '', '# Launch the training\ntf.reset_default_graph()\nsess = tf.Session(graph=tf.get_default_graph())\n\nwith sess.as_default():\n    in_images, image_tensors, features, preds, featurizer = construct_model(quantized=True)\n    train_model(preds, in_images, img_train, label_train, is_retrain=False, train_epoch=10, learning_rate=0.01)    \n    accuracy = test_model(preds, in_images, img_test, label_test)  \n    print("Accuracy:", accuracy)\n')

/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2356             with self.builtin_trap:
   2357                 args = (magic_arg_s, cell)
-> 2358                 result = fn(*args, **kwargs)
   2359             return result
   2360 

</anaconda/envs/py36/lib/python3.6/site-packages/decorator.py:decorator-gen-61> in time(self, line, cell, local_ns)

/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/magics/execution.py in time(self, line, cell, local_ns)
   1284             if len(expr_ast.body) > 1 :
   1285                 expr_val=expr_ast.body[-1]
-> 1286                 code_val = self.shell.compile(ast.Expression(expr_val.value)
   1287                                                 , '<timed eval>'
   1288                                                 , 'eval')

AttributeError: 'With' object has no attribute 'value'

**Comment by initmahesh** [comment]
issue was %%time made progess by commenting for the time being
6. Execute steps
You can run through the Transfer Learning section, then skip to Create AccelContainerImage. By default, because the custom weights section takes much longer for training twice, it is not saved as executable cells. You can copy the code or change cell type to 'Code'.


6.a. Training using Transfer Learning
**#%%time**

**Comment by initmahesh** [comment]
issue was %%time 
workaround is to comment we will not get time but can atleast train ..

6. Execute steps
You can run through the Transfer Learning section, then skip to Create AccelContainerImage. By default, because the custom weights section takes much longer for training twice, it is not saved as executable cells. You can copy the code or change cell type to 'Code'.


6.a. Training using Transfer Learning

**#%%time**

**Comment by femsulu** [comment]
Thanks for your comment. We are actively investigating and will get back to you shortly. Thanks for your patience.
