### ISSUE TITLE
NewConnectionError/TimeOutError when locally submitting the experiment generated in the AutoML-Energy-Forecast Notebook

### ISSUE THREAD

**Issue by derdanh** [Azure/MachineLearningNotebooks#886]
Hello everyone,

I'm having a problems running the [Auto ML Forecasting Energy Demand Notebook](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning/forecasting-energy-demand) locally using the Python SDK.

When submitting the experiment using
```remote_run = experiment.submit(automl_config, show_output=True)```

I receive the error 
```WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000191A362D1C8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /history/v1.0/subscriptions/811f3be2-cca6-45ae-a489-b678c1ea35b4/resourceGroups/myResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/myFirstWorkspace/experiments/automl-forecasting-energydemand```

If anybody could help me, I'd gladly appreciate it. I can also provide further information, if needed.

**Comment by GiftA-MSFT** [comment]
@derdanh we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@derdanh thanks for reaching out. I didn't observe the error you described while running this sample notebook in my local environment. This appears to be a networking issue within your local environment, perhaps check your firewall settings and try reconnecting to your internet. If you continue to experience issues, please share your workspace location so I can test in that region as well. Thanks.

![image](https://user-images.githubusercontent.com/51332022/78040043-e37be100-733c-11ea-969d-70bea54f6377.png)

**Comment by ram-msft** [comment]
@derdanh It's intermittent issue as we are not seeing this issue. 
![image](https://user-images.githubusercontent.com/49180516/78110770-32974400-7419-11ea-8d18-34d569c16077.png)

Forecasting within automated machine learning now includes new capabilities that improve the accuracy and performance of our recommended models:
•	New predict forecast function
•	Rolling-origin cross validation
•	Configurable Lags
•	Rolling window aggregate features
•	Holiday detection and featurizer 
•	Model explainability
•	Added metric score for MAPE (medium absolute mean percentage error) metric score 

To learn more about these capabilities review our how to guide 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast#configure-and-run-experiment
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by adamthorne** [comment]
derdahn this is the same issue i have subequently reported here: https://github.com/Azure/MachineLearningNotebooks/issues/958 

I replicated my environment from windows on an i5 chip to ubuntu i7 and this error disappeared.
