### ISSUE TITLE
PyTorch Version 1.4 Supported but not Supported

### ISSUE THREAD

**Issue by calebheinzman** [Azure/MachineLearningNotebooks#887]
Get the following error when trying to use framework_version='1.4'

TrainingException: TrainingException:
	Message: PyTorch 1.4 is not currently supported by the PyTorch estimator. Check https://docs.microsoft.com/python/api/azureml-train-core/azureml.train.dnn?view=azure-ml-py for all supported versions. To use PyTorch 1.4, switch to the generic Estimator class for your experiment.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "PyTorch 1.4 is not currently supported by the PyTorch estimator. Check https://docs.microsoft.com/python/api/azureml-train-core/azureml.train.dnn?view=azure-ml-py for all supported versions. To use PyTorch 1.4, switch to the generic Estimator class for your experiment."
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c63a256e-13b8-4a6d-8db9-c5f63a32cf6e
* Version Independent ID: 350d20c5-dfba-592e-2ede-31fdff01f3a7
* Content: [azureml.train.dnn package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@calebheinzman we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@j-martens can you please confirm if this a doc bug or product bug?

**Comment by j-martens** [comment]
@GiftA-MSFT - product bug

**Comment by GiftA-MSFT** [comment]
@j-martens thanks for the info.
@calebheinzman I have informed the product team regarding this issue and will share updates as soon as I have more information.

**Comment by calebheinzman** [comment]
Great, I was having an issue with pillow versions working with torchvision, but my current workaround is to use an older version of pillow:

pip_packages=['pillow==6.2.1']

**Comment by GiftA-MSFT** [comment]
@calebheinzman I am able to confirm that PyTorch Version 1.4 is supported and works as expected. I tried using this [sample experiment](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/deployment/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb) and added _framework_version = '1.4'_ as parameter in the _Create a PyTorch estimator_ section. Furthermore, ensure that you are using the _latest SDK version_. Hope this helps. Will now proceed to close the thread. Thanks.

![image](https://user-images.githubusercontent.com/51332022/78044402-a31f6180-7342-11ea-9301-f8f40bffb062.png)


![image](https://user-images.githubusercontent.com/51332022/78044036-212f3880-7342-11ea-902b-97f658d39ed8.png)
