### ISSUE TITLE
Pytorch Framework Version 1.4 does not work.

### ISSUE THREAD

**Issue by calebheinzman** [Azure/MachineLearningNotebooks#888]
The framework_version='1.4' for the Pytorch estimator does not work. All the documentation says that it should work.

**Comment by GiftA-MSFT** [comment]
@calebheinzman we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@calebheinzman it seems framework_version='1.4' isn't supported at the moment, but I am trying to confirm this information.

**Comment by GiftA-MSFT** [comment]
@danielsc @maxluk can you please help to confirm?

**Comment by GiftA-MSFT** [comment]
duplicate of [[887](https://github.com/Azure/MachineLearningNotebooks/issues/887)].
