### ISSUE TITLE
Tutorial required for Deploying a web service to Azure Kubernetes Service (AKS) for Image data

### ISSUE THREAD

**Issue by shankarpandala** [Azure/MachineLearningNotebooks#889]
Tutorial required for Deploying a web service to Azure Kubernetes Service (AKS) for Image data where Input and output both are images (segmentation)

**Comment by RohitMungi-MSFT** [comment]
@shankarpandala Thanks for the feedback. This forum is primarily used for bugs related to existing documentation but we will request our content authors to take this up in their backlog. 

With respect to deployment using AKS we have a [quickstart ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-azure-kubernetes-service)that can help you get started. Also, you can use this [image classification model](https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-deploy-models-with-aml#deploy-as-a-web-service) experiment to be deployed on AKS by changing the configuration as mentioned in the comments.

**Comment by RohitMungi-MSFT** [comment]
@shankarpandala We will now proceed to close this thread. If there are further questions regarding this matter, please tag @RohitMungi-MSFT in your reply.
