### ISSUE TITLE
Notebook aml-pipelines-with-automated-machine-learning-step.ipynb throws errors and it's partially outdated 

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#890]
This notebook was updated to version 1.2.0 and when running it, its pipeline training works.
 
However, part of it right at the end of the notebook is throwing errors: 

![image](https://user-images.githubusercontent.com/1712635/77794395-0babcd00-7029-11ea-8fad-575ae070eb61.png)

Plus it needs to be updated so there are no warnings about APIs parameters being deprecated:
![image](https://user-images.githubusercontent.com/1712635/77795629-24b57d80-702b-11ea-9b70-c40bdde39814.png)

Also still talking about "" but should be "COMPUTE INSTANCE":

`...If you are using an Azure Machine Learning **Notebook VM**...`

I'll make sure this is fixed. I'll work on it.

**Comment by CESARDELATORRE** [comment]
This notebook is updated internally, we need to publish it in GitHub, here.

**Comment by YutongTie-MSFT** [comment]
@CESARDELATORRE Thank you Cesar, I have assigned this issue to the author. @sanpil Could you please check this issue? Thanks.
