### ISSUE TITLE
Too many request to AutoML. Request got thottled.

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#892]
>Bad Request error raised. Operation returned an invalid status code 'Too many request to AutoML. Request got thottled.'

I'm seeing this error whenever I submit AutoML runs. First n runs go through, then I hit this error. Most of the runs after the run that returns this error are failing (maybe all of them, not sure, waiting on them to finish running). 

There are no logs in this run to be accessed. Runs that followed this system error actually run the parent run, but then shows this error on the iterations (also with no logs on the iterations)
>Error: 
Child runs failed with no error messages. Please try again.

Is there a limit of automl runs (submitted through the SDK)? 

Key Details: 
1. max_concurrent_iterations = 70 < max nodes in cluster = 120
2. Total number of automl runs (not iterations, automl submits) <= 60

Example run id: 
AutoML_a2dc1efe-e6ff-4fea-bc9b-b2a9bd8837f9 (too many auto ml requests)
AutoML_6f5374d5-09f3-4a36-a52b-5a9eb08ef885 (child runs failed, try again)

@sanpil @MayMSFT @CESARDELATORRE 

CC: @swanderz

**Comment by ram-msft** [comment]
@jadhosn Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by cartacioS** [comment]
Hi @jadhosn, reaching out to see if you are still facing this issue?

**Comment by jadhosn** [comment]
@cartacioS I haven't faced this issue since opening this thread. We learned that there's an invisible limit on the number of concurrent jobs per workspace (roughly 100 runs). Once I baked that into my scenarios, I stopped facing this issue. I will close this thread.
