### ISSUE TITLE
ScriptRun sample from ref docs doesn't work

### ISSUE THREAD

**Issue by vassilyl** [Azure/MachineLearningNotebooks#893]
I'm trying to run minimal code with azureml-core 1.3:

from azureml.core import Workspace, Experiment, ScriptRunConfig, RunConfiguration
ws = Workspace.from_config("config.json")
ex = Experiment(ws, "Repro")
ex.submit(ScriptRunConfig(
    source_directory=".",
    script="subdir/script.py",
    run_config=RunConfiguration()))

The run fails with the following error:

UserError: 
Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109d9284-e234-5086-5da6-4155291361c8
* Version Independent ID: 57cc0c7a-faa7-1a86-ee14-b9cf99fb540d
* Content: [azureml.core.ScriptRunConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.ScriptRunConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@vassilyl Hi Vassily, are you using conda environment?

**Comment by vizhur** [comment]
@vassilyl looks like you have a pirate version of AzureML SDK. We did not ship 1.3 yet :)

I guess you are trying to make a local run so you need conda in the path. If you want to run the script in your current python environment you need to set to True userManagedDependencies 

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.pythonsection?view=azure-ml-py

and more samples referenced in Environment help page

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py

**Comment by vassilyl** [comment]
No. And if you dig deeper in documentation it's clear that the example tries to use local compute target. Neighter the page, nor the error message mentions this fact. Since this is not the main use case for AzureML SDK, I would change it to show setting a compute target.

Also, the "run_config=RunConfiguration()" argument seems to be redundant.

**Comment by vassilyl** [comment]
The version is 1.2, it's a typo, sorry.

**Comment by vassilyl** [comment]
@vizhur, thank you for the links. The issue is about the documentation page though. The sample in the context of the documentation page is incomplete and confusing.

**Comment by vizhur** [comment]
@vassilyl I have created a ticket for that. I agree the sample is a bit confusing

**Comment by YutongTie-MSFT** [comment]
@vizhur Could we close this or you want to keep it opening? Thanks.

**Comment by vizhur** [comment]
@YutongTie-MSFT it's not resolved yet, i'd keep it open unless @vassilyl is fine to close this as we have internal ticket filed

**Comment by lostmygithubaccount** [comment]
@vizhur has this been resolved

**Comment by vizhur** [comment]
docs were updated
