### ISSUE TITLE
No child runs could be found for this parent run [AutoML]

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#894]
>No child runs could be found for this parent run. Possible solutions: 
>1) Please check if your remote compute target is healthy. 
>2) Please check if your experiment was deleted / archived. 

No logs show up on this submit and no models. The following traceback popped up locally (submitted through Python-SDK):
>Traceback (most recent call last):
  File "C:/code/ml-CreditScore/main/AutoML/automl-loop-script.py", line 181, in <module>
    whitelist_models=whitelist_models, target_ls=target_columns_ls)
  File "C:/code/ml-CreditScore/main/AutoML/automl-loop-script.py", line 98, in call_automl_config
    automl_run.wait_for_completion(show_output=True, wait_post_processing=True)
  File "C:\miniconda3\envs\creditscore-1.1.5.1\lib\site-packages\azureml\train\automl\run.py", line 917, in wait_for_completion
    primary_metric)
  File "C:\miniconda3\envs\creditscore-1.1.5.1\lib\site-packages\azureml\train\automl\_remote_console_interface.py", line 312, in _show_output
    remote_printer.print_scores(current_run, primary_metric)
  File "C:\miniconda3\envs\creditscore-1.1.5.1\lib\site-packages\azureml\train\automl\_remote_console_interface.py", line 93, in print_scores
    if not self._init_console_interface(parent_run):
  File "C:\miniconda3\envs\creditscore-1.1.5.1\lib\site-packages\azureml\train\automl\_remote_console_interface.py", line 72, in _init_console_interface
    _constants_azureml.Properties.PROBLEM_INFO))
azureml.train.automl.exceptions.SystemException: SystemException:
	Message: Key "ProblemInfoJsonString" missing from setup run properties
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "System",
        "message": "Key \"ProblemInfoJsonString\" missing from setup run properties"
    }
}

![image](https://user-images.githubusercontent.com/17963295/78172073-49826a00-740a-11ea-8381-283c406f2b3d.png)

@sanpil @MayMSFT @CESARDELATORRE @swanderz

**Comment by CESARDELATORRE** [comment]
I'll create an issue to investigate that run from our side.
Questions:

- Is that issue reproducible by submitting the same experiment again? Or did that happened only for that particular parent run?

- Can you provide the following info **in text**?
   **- Parent Run ID
   - Azure datacenter region where you have the AML Workspace
   - Is it a "local run" or a "remote run (using AML cluster)"?**

Thanks,

**Comment by jadhosn** [comment]
> * Is that issue reproducible by submitting the same experiment again? Or did that happened only for that particular parent run?

The issue is not reproducible by submitting the same experiment

> * Can you provide the following info **in text**?
>   * Parent Run ID

AutoML_675fb8f9-e0b5-46d8-b036-45781d1758e8
>   * Azure datacenter region where you have the AML Workspace

usw2
>   * Is it a "local run" or a "remote run (using AML cluster)"?

remote run

**Comment by lostmygithubaccount** [comment]
@CESARDELATORRE any updates on this?

**Comment by CESARDELATORRE** [comment]
#please-close This issue is stale. We didn't have a further follow up from DriveTime (Jad). It was a single issue in time not reproducible and probably fixed in later versions.
