### ISSUE TITLE
Need to document value "-1" for max_cores_per_iteration. Not mentioned in the reference doc.

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#895]
In the REMARKS sample aboove and also in some notebooks we have it with max_cores_per_iteration = -1.
I think that means "use all the possible cores per iteration/child-run". 

However, the "-1" value is not documented in this reference doc page. We need to document it.

Right now the description of the parameter is just this (check above in this page):

max_cores_per_iteration
int
Maximum number of threads to use for a given training iteration. This should be less than or equal to the maximum number of cores on the compute target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by vmagelo** [comment]
Change was made and will go live with next SDK release. Thanks.

**Comment by j-martens** [comment]
Thanks for your report.
