### ISSUE TITLE
auto-ml-forecasting-bike-share.ipynb crashes in cell using shutil.copy2(): Change to shutil.copy() 

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#896]
**auto-ml-forecasting-bike-share.ipynb** crashes in cell using `shutil.copy2()` under some versions of Python in the local environment. 

Change to `shutil.copy()` so it works in most Python environments.

![image](https://user-images.githubusercontent.com/1712635/78201705-17dbc400-7447-11ea-8f27-4f3baedc610c.png)

Error that can happen:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-18-4abbbb8a291f> in <module>
      4 script_folder = os.path.join(os.getcwd(), 'forecast')
      5 os.makedirs(script_folder, exist_ok=True)
----> 6 shutil.copy2('forecasting_script.py', script_folder)
      7 shutil.copy2('forecasting_helper.py', script_folder)

/anaconda/envs/azureml_py36/lib/python3.6/shutil.py in copy2(src, dst, follow_symlinks)
    262         dst = os.path.join(dst, os.path.basename(src))
    263     copyfile(src, dst, follow_symlinks=follow_symlinks)
--> 264     copystat(src, dst, follow_symlinks=follow_symlinks)
    265     return dst
    266 

/anaconda/envs/azureml_py36/lib/python3.6/shutil.py in copystat(src, dst, follow_symlinks)
    227             else:
    228                 raise
--> 229     _copyxattr(src, dst, follow_symlinks=follow)
    230 
    231 def copy(src, dst, *, follow_symlinks=True):

/anaconda/envs/azureml_py36/lib/python3.6/shutil.py in _copyxattr(src, dst, follow_symlinks)
    155 
    156         try:
--> 157             names = os.listxattr(src, follow_symlinks=follow_symlinks)
    158         except OSError as e:
    159             if e.errno not in (errno.ENOTSUP, errno.ENODATA):

**OSError: [Errno 38] Function not implemented: 'forecasting_script.py'**

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the feedback. We will update you shortly.

**Comment by ram-msft** [comment]
Raised a PR #917  for the changes. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by CESARDELATORRE** [comment]
@ram-msft Hey ram, shouldn't the PRs go against the ADO Git instead directly to the GitHub repo?
Other than that updates from the ADO Git would revert the PR here in GitHub. Am I wrong?
Can you confirm?
