### ISSUE TITLE
NotebookRunnerStep inputs problem as DatasetConsumptionConfig 

### ISSUE THREAD

**Issue by aleixsd** [Azure/MachineLearningNotebooks#897]
Hello,

I am currently trying to use a NotebookRunnerStep to create a ML pipeline that reads a dataset as input. To do so I create a NotebookRunnerStep  and whereas in PythonScriptStep works perfectly, when I create the Pipeline with the NotebookRunnerStep I get an TypeError "input or output should be of one of these types: PipelineData, OutputPortBinding, InputPortBinding, Dataset, PipelineDataset, DataReference, PortDataReference". Is this correct? If so, What do I need to do to use a Dataset as an input in the NotebookRunnerStep ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9352b7e0-5654-a6b6-ab09-00466b33d1b0
* Version Independent ID: 5bfa4c56-dadc-a74d-34d1-f8b74b8628e7
* Content: [azureml.contrib.notebook.NotebookRunnerStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-contrib-notebook/azureml.contrib.notebook.notebookrunnerstep?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-notebook/azureml.contrib.notebook.NotebookRunnerStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-contrib-notebook/azureml.contrib.notebook.NotebookRunnerStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@aleixsd Here is an example of using a dataset from the datastore in this github [repo](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-notebook-runner-step.ipynb). Could you please check and let us know if this helps?

**Comment by aleixsd** [comment]
Hello,
I have tried to run the example but I keep on getting the same error in the step: "UnicodeDecodeError: 'ascii' codec can't decode byte X in position X: ordinal not in range(128)".
In addition, I can see you use a Datastore in the example but can not see where the Dataset is. For mi purpose I need to set as input a Dataset allready created previously.

**Comment by RohitMungi-MSFT** [comment]
@danielsc @mx-iao Could you please help  to provide more details about using a dataset with notebookrunner step? The example in the [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-notebook-runner-step.ipynb) uses a datastore but while using a dataset an error is seen.
`"UnicodeDecodeError: 'ascii' codec can't decode byte X in position X: ordinal not in range(128)".
`

**Comment by mx-iao** [comment]
Hi @RohitMungi-MSFT, assigning @sanpil and @MayMSFT as this is a pipelines + datasets issue.

**Comment by purnesh42H** [comment]
@aleixsd  the input dataset should be of type
**<class 'azureml.data.dataset_consumption_config.DatasetConsumptionConfig>**

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_consumption_config.datasetconsumptionconfig?view=azure-ml-py

here is an example for NotebookRunnerStep. Also, please make sure you have the latest azureml-sdk version

```python
from azureml.pipeline.core import PipelineParameter
from azureml.core import Dataset

output_from_notebook = PipelineData(name="notebook_processed_data",
                                    datastore=Datastore.get(ws, "workspaceblobstore"))

input_dataset = Dataset.File.from_files('https://dprepdata.blob.core.windows.net/demo/Titanic.csv')

my_pipeline_param = PipelineParameter(name="pipeline_param", default_value="my_param")

print('Source directory for the step is {}.'.format(os.path.realpath(source_directory)))
notebook_runner_step = NotebookRunnerStep(name="training_notebook_step",
                                          notebook_run_config=cfg,
                                          params={"my_pipeline_param": my_pipeline_param},
                                          inputs=[output_data, input_dataset.as_named_input('input_dataset').as_mount()],
                                          outputs=[output_from_notebook],
                                          allow_reuse=True,
                                          compute_target=compute_target,
                                          output_notebook_pipeline_data_name="notebook_result")

print("Notebook Runner Step is Created.")
```

**Comment by rongduan-zhu** [comment]
@aleixsd adding to what @purnesh42H said, you can then retrieve the mounted `input_dataset` by referring to the `input_dataset` variable inside your notebook. Essentially, the `name` you pass into `as_named_input` will become the variable we initialize in the notebook.

So following the example [here](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-notebook-runner-step.ipynb), in [`train_notebook.ipynb`](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/notebook_runner/training_notebook.ipynb), the cell `# declaring parameters to override`, will actually be replaced with variable initializations based on parameters and arguments you passed into the step and one of the variable that we initialize will be `input_dataset` which is set to the mounted path. We replace that cell because the cell's metadata section is tagged with parameter.
```json
      "metadata": {
        "tags": [
          "parameters"
        ]
      },
```

**Comment by lostmygithubaccount** [comment]
reopening per new policy
