### ISSUE TITLE
There is no links for Event, Metric

### ISSUE THREAD

**Issue by sfilipi** [Azure/MachineLearningNotebooks#898]
There is no links for Event, Metric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e4e284-9067-15ce-b56d-9abaae786d0f
* Version Independent ID: 8efbc1d4-b58a-d9c1-49b4-d48929852d4a
* Content: [azureml.telemetry.logger.ApplicationInsightsEventLogger class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-telemetry/azureml.telemetry.logger.applicationinsightseventlogger?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-telemetry/azureml.telemetry.logger.ApplicationInsightsEventLogger.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-telemetry/azureml.telemetry.logger.ApplicationInsightsEventLogger.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@sfilipi Thanks for the feedback. We will update you shortly.

**Comment by vmagelo** [comment]
We added the links. The changes will appear in next release of SDK in 1-2 weeks.

**Comment by j-martens** [comment]
Thank you for your report. I'll now proceed to close this issue.
