### ISSUE TITLE
Estimator does not accept databricks as compute target

### ISSUE THREAD

**Issue by FlorianPydde** [Azure/MachineLearningNotebooks#899]
Hi, The Estimator class does not accept databricks as a compute target. How are we supposed to train spark based models ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db16bca-3797-0285-3ef2-99de84e4a0be
* Version Independent ID: cba716ef-395b-c8f9-2cbc-967bbc338c87
* Content: [azureml.train.estimator.Estimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-train-core/azureml.train.estimator.estimator?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@FlorianPydde To use databricks are compute you can use the steps mentioned in this [notebook ](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-use-databricks-as-compute-target.ipynb)and setup the same.

**Comment by FlorianPydde** [comment]
Thanks for the quick reply. However, the approach mentioned in the notebook does not allow to use custom modules in the specified script. For instance, if I want to run a train.py in a databrickstep it's all fine. However, if import in my train.py something like import myCustomModule, the execution fails in databricks with the error "no module found: myCustomModule". I assume that this comes from the fact that only the train.py is sent to the remote databricks cluster but not the entire specified folder

**Comment by RohitMungi-MSFT** [comment]
@nishankgu Could you please help with the above query? Is it possible to import custom modules in the databrick step?

```
python_script_name = "train-db-local.py"
source_directory = "./databricks_train"

dbPythonInLocalMachineStep = DatabricksStep(
    name="DBPythonInLocalMachine",
    inputs=[step_1_input],
    num_workers=1,
    python_script_name=python_script_name,
    source_directory=source_directory,
    run_name='DB_Python_Local_demo',
    compute_target=databricks_compute,
    allow_reuse=True
)
```

**Comment by mikemowgli** [comment]
Also, a reason why a Databricks compute target is needed is that a HyperDrive parameter tuning relies on an estimator. So as long as the Estimator class does not support the Databricks compute target, nobody could ever run hyperparameter tuning on databricks... or am I seeing this wrongly?

**Comment by brunocous** [comment]
I'm experiencing the same issue. I would like to use a HypderDrive parameter tuning step with Databricks as compute target. I haven't been able to achieve this. Any suggestions are certainly welcome.

**Comment by jpe316** [comment]
Not supported - by design
