### ISSUE TITLE
Where can I find an exhaustive list of the run.submit()'s kwargs?

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#900]
Is there a place that lists the different kwargs that this [function](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py#submit-config--tags-none----kwargs-) accepts? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49038bc-1bad-a7ca-b107-760f156f4ee9
* Version Independent ID: e4244e08-b247-38aa-dc95-acdd004f86bd
* Content: [azureml.core.Experiment class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py#submit-config--tags-none----kwargs-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@jadhosn we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@jadhosn **kwargs allows you to specify additional arguments or information in the function for configurations. Hence, there is no list defined, but you can define those parameter yourself. Check out this tutorial on [how to use *args and **kwargs](https://www.digitalocean.com/community/tutorials/how-to-use-args-and-kwargs-in-python-3). Hope this helps. Thanks.

**Comment by vizhur** [comment]
hi @jadhosn, whatever is intended to be public is outside the kwargs scope. Anything in particular you are looking for?

**Comment by jadhosn** [comment]
@vizhur, for example, *wait_for_completion* to help with async calls whenever I submit runs

```
Experiment(workspace, name=experiment_name).submit(automl_config,wait_for_completion=True)
```
vs.
```
automl_run = Experiment(workspace, name=experiment_name).submit(automl_config)
automl_run.wait_for_completion(show_output=True, wait_post_processing=True)
```

PS:  A very kind MS escalation engineer shared with us this setting in a previous ticket

**Comment by vizhur** [comment]
:) #2 is intended usage and documented behavior

**Comment by GiftA-MSFT** [comment]
Thanks @vizhur for your input.
