### ISSUE TITLE
tutorial-pipeline-batch-scoring-classification

### ISSUE THREAD

**Issue by AliCharkhi** [Azure/MachineLearningNotebooks#902]
When I run tutorial-pipeline-batch-scoring-classification notebook, the pipeline creation gives the following error:

`from azureml.core import Experiment
from azureml.pipeline.core import Pipeline

pipeline = Pipeline(workspace=ws, steps=[batch_score_step])
pipeline_run = Experiment(ws, 'batch_scoring').submit(pipeline)
pipeline_run.wait_for_completion(show_output=True)`

TypeError                                 Traceback (most recent call last)
<ipython-input-34-c3f1db1260e9> in <module>
      2 from azureml.pipeline.core import Pipeline
      3 
----> 4 pipeline = Pipeline(workspace=ws, steps=[batch_score_step])
      5 pipeline_run = Experiment(ws, 'batch_scoring').submit(pipeline)
      6 pipeline_run.wait_for_completion(show_output=True)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/_experiment_method.py in wrapper(self, *args, **kwargs)
     91             """
     92             ExperimentSubmitRegistrar.register_submit_function(self.__class__, submit_function)
---> 93             return init_func(self, *args, **kwargs)
     94         return wrapper
     95     return real_decorator

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/pipeline.py in __init__(self, workspace, steps, description, default_datastore, default_source_directory, resolve_closure, _workflow_provider, _service_endpoint, **kwargs)
    175                 raise ValueError('parameter %s is not recognized for Pipeline ' % key)
    176         self._enable_email_notification = enable_email_notification
--> 177         self._graph = self._graph_builder.build(self._name, steps, finalize=False)
    178 
    179     def _set_experiment_name(self, name):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/builder.py in build(self, name, steps, finalize, regenerate_outputs)
   1381                 pass
   1382 
-> 1383         graph = self.construct(name, steps)
   1384         if finalize:
   1385             graph.finalize(regenerate_outputs=regenerate_outputs)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/builder.py in construct(self, name, steps)
   1403         self._graph = Graph(name, self._context)
   1404         self._nodeStack.append([])
-> 1405         self.process_collection(steps)
   1406         for builder in self._builderStack[::-1]:
   1407             builder.apply_rules()

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/builder.py in process_collection(self, collection)
   1439         self._nodeStack.append([])
   1440         self._builderStack.append(builder)
-> 1441         builder.process_collection(collection)
   1442         added_nodes = self._nodeStack.pop()
   1443         self._nodeStack[-1].extend(added_nodes)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/builder.py in process_collection(self, collection)
   1651         """
   1652         for item in collection:
-> 1653             self._base_builder.process_collection(item)
   1654 
   1655     def apply_rules(self):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/builder.py in process_collection(self, collection)
   1433         # just a step?
   1434         if isinstance(collection, PipelineStep):
-> 1435             return self.process_step(collection)
   1436 
   1437         # delegate to correct builder

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/builder.py in process_step(self, step)
   1477             return self._step2node[step]
   1478 
-> 1479         node = step.create_node(self._graph, self._default_datastore, self._context)
   1480         self.assert_node_valid(step, self._graph, node)
   1481 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/contrib/pipeline/steps/parallel_run_step.py in create_node(self, graph, default_datastore, context)
    436         :rtype: azureml.pipeline.core.graph.Node
    437         """
--> 438         node = super(ParallelRunStep, self).create_node(graph, default_datastore, context)
    439         node.get_param("BatchInferencingMetaData").set_value(self._generate_batch_inference_metadata())
    440         node.get_param("Script").set_value(DEFAULT_BATCH_SCORE_MAIN_FILE_NAME)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/steps/python_script_step.py in create_node(self, graph, default_datastore, context)
    240         """
    241         return super(PythonScriptStep, self).create_node(
--> 242             graph=graph, default_datastore=default_datastore, context=context)
    243 
    244     def _set_amlcompute_params(self, native_shared_directory=None):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/_python_script_step_base.py in create_node(self, graph, default_datastore, context)
    115                                             output_bindings=output_bindings, param_defs=list(param_defs),
    116                                             allow_reuse=self._allow_reuse, version=self._version,
--> 117                                             arguments=self._annotated_arguments)
    118 
    119         module_builder = _ModuleBuilder(

TypeError: create_module_def() got an unexpected keyword argument 'arguments'

Any idea about the solution? Thanks

**Comment by GiftA-MSFT** [comment]
@AliCharkhi we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@AliCharkhi I was able to successfully run the notebook in Azure ML Studio. I think this error is caused by your local environment. Can you please try to run the notebook in AML Studio located in Samples/Python/1.2.0/tutorials/machine-learning-pipelines-advanced'? Thanks.

**Comment by AliCharkhi** [comment]
![image](https://user-images.githubusercontent.com/32510881/78911974-57c62b00-7a87-11ea-9c1e-9e1764687923.png)

**Comment by GiftA-MSFT** [comment]
@yanrez are you aware of this issue in Western Europe region?

**Comment by GiftA-MSFT** [comment]
@AliCharkhi can you please share your run id from the run details so we can look into this issue further? I'm unable to repro this issue even in West Europe region.

**Comment by yanrez** [comment]
@sanpil

**Comment by sanpil** [comment]
Can you make sure the versions of azureml-contrib-pipeline-steps and azureml-pipeline-core are the same?

**Comment by AliCharkhi** [comment]
Thanks a lot for the hint. Upfrading the full SDK solved the issue. I was updating just the core SDK.
