### ISSUE TITLE
Can not access scikit modules when running img-classification-part2-deploy.ipynb

### ISSUE THREAD

**Issue by beauwilliams** [Azure/MachineLearningNotebooks#904]
When running this code

-----------------------------------------

import pickle
import joblib
clf = joblib.load( os.path.join(os.getcwd(), 'sklearn_mnist_model.pkl'))
y_hat = clf.predict(X_test)
print(y_hat)

---------------------------------------
We encounter the below error, which prevents any further execution of the notebook

`ModuleNotFoundError: No module named 'sklearn.linear_model._logistic'`

[Error](https://i.ibb.co/5MVtnL8/Screen-Shot-2020-04-07-at-7-55-47-pm.png)

This is resolved by ssh'ing into the AzureML Compute (e.g ssh azureuser@ipaddress -p 50000), and running 

`pip install -U scikit-learn`

You will get a dependency warning, but the notebooks afterwards will run just fine

See below for more information
[Warnings](https://i.ibb.co/SNS2b7N/Screen-Shot-2020-04-07-at-8-03-46-pm.png)

Since we have updated scikit-learn to 0.22.2.post1, we can see from the below screenshot that the above code will now run successfully.

[Success](https://i.ibb.co/7YW8Sxg/Screen-Shot-2020-04-07-at-7-57-08-pm.png)

**Comment by vizhur** [comment]
@beauwilliams For compatible serialization/deserialization you need to use the same version of the dependency. AzureML SDK pins it to a range that does not have 0.22.2.post1, pip is raising a legit warning.

what is the environment for creating sklearn_mnist_model.pkl, I would assume it has the version you tried to update on remote. Btw, why didn't you specify dependency version you need in the environment but manually installing it on compute where it will be reset with the next run?

**Comment by beauwilliams** [comment]
Yes, I agree with your sentiments on dependencies, I do not think this is a good solution but I am running on a deadline, and wish to at least get a working start to finish all from within AzureML Studio.

In the part 1 MNIST Training notebook, there is some code that might be causing the issue, external joblib 

`from sklearn.linear_model import LogisticRegression`
`from sklearn.externals import joblib`

Note that in the part 2 MNIST Deploy notebook we appear to be using local joblib

'import joblib'

Perhaps these are different versions?

The environment used to train the model in the Part 1 MNIST Training notebook is

`from azureml.core.environment import Environment`

Please note: I am running the code in the notebooks as is, all from within azureML with no modifications, this is important so that students can run through this exercise start to finish without needing to worry about environments or dependencies. 

The reason being is that for a Microsoft workshop in a weeks time, students will be expected to run through the tutorials using AzureML Studio. I wish for them also not to need to bother with GitHub for the initial tutorial, but simply clone the repository from within MLStudio using the GUI, as stated on the AzureML tutorial guides.

How could I explicitly specify this dependency version then? I can fork and update parts of the code for the students if that is necessary. The hope was that they can run through the tutorials on AzureML Studio without needing to worry about setting up local environments and dependencies or modifying the code in these notebooks. Again, it's their first introduction to ML.

If I have to fork and change some of the code then it will mean that students can not simply use this repo in AzureML by cloning it in the notebooks section, and that some might get stuck following the guides provided by Microsoft and it will be a bit of a mess.

**Comment by vizhur** [comment]
so you trained your model with Part 1 sample, and part 2 throws the error you mentioned?
Just to double check, the first cell in sample 2 should be ignored then

```
# If you did NOT complete the tutorial, you can instead run this cell 
# This will register a model and download the data needed for this tutorial
# These prerequisites are created in the training tutorial
# Feel free to skip this cell if you completed the training tutorial 
```

**Comment by beauwilliams** [comment]
Thanks for getting back to me.
Indeed I did not run the first code snippet in the Part2 MNIST Tutorial Book. I will give it another run today, just to make sure I did not run it mistake and feeding you the wrong information!

**Comment by beauwilliams** [comment]
I can confirm having just tested again that I am still running into this issue, making sure not to run the first code snippet in the MNIST tutorial 2 notebooks.

**Comment by sdgilley** [comment]
The issue is indeed a problem with different versions of scikit-learn between the training environment, your local environment, and the deployed environment.  

We're working to update the deployment notebook, to cut out local altogether and instead test on the deployed model using the same Python environment that was saved in the training notebook.  

In the training notebook, there is code that creates and registers an environment:
```
from azureml.core.environment import Environment
from azureml.core.conda_dependencies import CondaDependencies

# to install required packages
env = Environment('tutorial-env')
cd = CondaDependencies.create(pip_packages=['azureml-dataprep[pandas,fuse]>=1.1.14', 'azureml-defaults'], conda_packages = ['scikit-learn==0.22.1'])

env.python.conda_dependencies = cd

# Register environment to re-use later
env.register(workspace = ws)
```
You can then use this environment during deployment.  This is not in the deployment notebook yet but it will be, within the next week I hope.  In the meantime, use this code to deploy:
```
%%time
from azureml.core.webservice import Webservice
from azureml.core.model import InferenceConfig
from azureml.core.environment import Environment
from azureml.core import Workspace
from azureml.core.model import Model

ws = Workspace.from_config()
model = Model(ws, 'sklearn_mnist')

myenv = Environment.get(workspace=ws, name="tutorial-env", version="1")
inference_config = InferenceConfig(entry_script="score.py", environment=tutorial-env)

service = Model.deploy(workspace=ws, 
                       name='sklearn-mnist-svc3', 
                       models=[model], 
                       inference_config=inference_config, 
                       deployment_config=aciconfig)

service.wait_for_deployment(show_output=True)
```
Then you can test the model with the deployed version.  Download the test data as in the notebook but then use this code to get predictions:

```python
import json
test = json.dumps({"data": X_test.tolist()})
test = bytes(test, encoding='utf8')
y_hat = service.run(input_data=test)
```

**Comment by beauwilliams** [comment]
Thank you very much this is great, I will give this a run now.
