### ISSUE TITLE
AzureMLCompute cluster {NAME} does not exist

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#906]
Never seen this before... Any idea what is going on?

### `logs/azureml/stderrlogs.txt`

```
[2020-04-08 23:36:01Z] Job failed,job RunId is 
b9b3eac6-73ff-41b1-a91b-11dd5c547ed5.
Error: {"Error":{"Code":"UserError",
"Message":"AzureMLCompute cluster deal-uat does not exist",
"Target":null,"Details":[],"InnerError":null,"DebugInfo":null},
"Correlation":{"operation":null,"request":"0cd3a5ee3625937d"}}
```

![image](https://user-images.githubusercontent.com/8158673/78844042-6f36e280-79b9-11ea-96c7-7ea173a49c3d.png)

```
Provisioning error: BatchAI cluster
'/subscriptions/ff2e23ae-7d7c-4cbd-99b8-116bb94dca6e/resourceGroups/rg-itsmlteamdev/providers/Microsoft.BatchAI/workspaces/avadevitsmlsvc/clusters/deal-uat'
was not found.

Client Request ID : c9818a6c-e019-40f3-bd27-bb7557131fc3
Service Request ID : |52edafce60e6470ea914df4001cbcff0.93c57303822b4cb4.22d56217_
```

![image](https://user-images.githubusercontent.com/8158673/78844081-883f9380-79b9-11ea-83eb-257670b368e6.png)

**Comment by ram-msft** [comment]
@swanderz Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by swanderz** [comment]
deleting, then recreating this compute target resolved the problem. I'll re-open if I see this behavior again.
