### ISSUE TITLE
Changing scripts arguments won't trigger a rerun 

### ISSUE THREAD

**Issue by beekill95** [Azure/MachineLearningNotebooks#907]
Currently, I'm passing many arguments to `PythonScriptStep` as string or number, such as `arguments=['--shuffle-data', '--data', '/home/1.txt', '--data', '/home/2.txt']`. However, if I change the params from `/home/1.txt` to `/home/abc/1.txt`, it won't trigger a rerun. To overcome this, I use `PipelineParameter`, but I'm not sure if it is the correct way to do it.

Furthermore, if later on I don't want to shuffle data, I'll omit the flag `--shuffle-data`, but this too won't trigger a rerun.

Is there a way to trigger a rerun on they step when its arguments are changed?

Btw, I'm using SDK version 1.0.85

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1411eede-5d88-1a8e-0ddf-2dc0ceea4f0e
* Version Independent ID: 6b5a0467-67a8-674a-a569-a8865e6cb400
* Content: [azureml.pipeline.steps.python_script_step.PythonScriptStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.pythonscriptstep?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.PythonScriptStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.PythonScriptStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@beekill95 Thanks for the question. We will update you shortly.

**Comment by purnesh42H** [comment]
@beekill95 if you create the step again along with pipeline, after changing the argument, it will rerun. PipelineParameter is the correct way to achieve this for a published pipeline. 

Alternatively, if you want to always trigger a new run, you can set allow_reuse flag to false for that step.

**Comment by shbijlan** [comment]
#please-close
