### ISSUE TITLE
ResourceNotReady error when using DatabricksStep in pipeline

### ISSUE THREAD

**Issue by psterkens1** [Azure/MachineLearningNotebooks#908]
Hi, 

I was going through the [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-use-databricks-as-compute-target.ipynb) on DatabricksStep implementation in Azure ML pipelines and I keep on getting the same error while running the pipeline.

![image](https://user-images.githubusercontent.com/63408637/78902520-314dc300-7a7a-11ea-9e6e-6bff7dbcfb68.png)

I used the exact same steps as they did in the notebook so I am not sure what went wrong. Any help on what may cause this error and how to solve it would be really appreciated!

**Comment by GiftA-MSFT** [comment]
@psterkens1 we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@psterkens1 please ensure that your Databricks compute target is up and running. Thanks.
