### ISSUE TITLE
nltk stopword and punkt

### ISSUE THREAD

**Issue by lesh3000** [Azure/MachineLearningNotebooks#909]
I am deploying the model, and need to use nltk stopwords and tokenizer that uses nltk.punk
The model deployment fails because those files are not included in standard nltk. It requests to call nltk.download("stopwords") similar for punkt, but adding it into init() does not let to deploy model neither. It gives Unhealthy service message.
Is there anything I can do to be able to use corresponding nltk functions?

**Comment by GiftA-MSFT** [comment]
@lesh3000 thanks for reaching out. Please what notebook are you referring to?

**Comment by lesh3000** [comment]
I tried deploying a similar model: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-existing-model . Mine had  nltk tokenizer imported.  I get the error when deploying the package because for instance stopwords needs to be downloaded separetely. I can provide you with the script.  Furthermore, for me it worked to import keras model file as json and then to add model_weights:

json_file = open(model_path+'/model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    modelKeras = model_from_json(loaded_model_json)
# load weights into new model
    modelKeras.load_weights(model_path+"/model.h5")

**Comment by GiftA-MSFT** [comment]
@lesh3000 we don't have particular guidance on how you should install these functions. If your init function is failing (which is probably what is leading to the unhealthy response), then try to debug with local containers. You could use the docker file step to run python -c "import nltk; nltk.download('stopword')" at build time and then it would be present in the environment. Hope this helps. Thanks.
