### ISSUE TITLE
Please define container vs replica vs web service

### ISSUE THREAD

**Issue by robert4os** [Azure/MachineLearningNotebooks#911]
The terms container and replica are confusing without a clear definition.

Also they seem to be mixed up as well, for instance here
&gt;&gt;
autoscale_min_replicas
int
default value: None
The minimum number of containers to use when autoscaling this Webservice. Defaults to 1
&lt;&lt;

Thank you and best regards,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c5068c-bf75-51ea-a8b3-a3356ba81b5c
* Version Independent ID: 9036f1f0-f669-bb28-74e7-3ea8dae6d7e9
* Content: [azureml.core.webservice.AksWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.akswebservice?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AksWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AksWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@robert4os we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@j-martens are replicas and containers used interchangeably here? For example, the document has
- [num_replicas](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.akswebservice?view=azure-ml-py#variables) defined as -> The number of replicas for the Webservice.
- [num_replicas](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.akswebservice?view=azure-ml-py#deploy-configuration-autoscale-enabled-none--autoscale-min-replicas-none--autoscale-max-replicas-none--autoscale-refresh-seconds-none--autoscale-target-utilization-none--collect-model-data-none--auth-enabled-none--cpu-cores-none--memory-gb-none--enable-app-insights-none--scoring-timeout-ms-none--replica-max-concurrent-requests-none--max-request-wait-time-none--num-replicas-none--primary-key-none--secondary-key-none--tags-none--properties-none--description-none--gpu-cores-none--period-seconds-none--initial-delay-seconds-none--timeout-seconds-none--success-threshold-none--failure-threshold-none--namespace-none--token-auth-enabled-none--compute-target-name-none-) also defined as -> The number of containers to allocate for this Webservice.

**Comment by GiftA-MSFT** [comment]
@j-martens please review this feedback for doc enhancement.

**Comment by j-martens** [comment]
@blackmist - do you know who could clarify these definitions?

**Comment by jpe316** [comment]
@vaidya-s to clarify

Best doc we have is here:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-azure-kubernetes-service#deploy-to-aks

**Comment by PeterCLu** [comment]
I clarified with Vaidyaraman. I'll update the reference docs to standardize as "number of replicas for the webservice" since "container" is an implementation detail rather than the over-arching concept.

**Comment by j-martens** [comment]
@peterclu - where is this now please?

**Comment by lostmygithubaccount** [comment]
@PeterCLu @j-martens any updates?

**Comment by j-martens** [comment]
@lostmygithubaccount - the product team owns SDK now fully and should make these fixes. Thanks!

**Comment by vaidya-s** [comment]
@Bozhong68

**Comment by gvashishtha** [comment]
Fix was made to the documentation (should go out with next SDK release). This issue can be closed.
