### ISSUE TITLE
Input prediction data X_pred or input forecast_destination contains dates prior to the latest date in the training data. Please remove prediction rows with datetimes in the training date range or adjust the forecast_destination date."

### ISSUE THREAD

**Issue by rajibstats** [Azure/MachineLearningNotebooks#912]
Hi all,

My experiment is running successfully till training successfully. But when I am going to predict on test data with bellow code, Its throwing an exception.
y_predictions, X_trans = fitted_model.forecast(X_test)

Exception:

WrongShapeDataError: WrongShapeDataError:
	Message: Input prediction data X_pred or input forecast_destination contains dates prior to the latest date in the training data. Please remove prediction rows with datetimes in the training date range or adjust the forecast_destination date.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "InvalidData",
            "inner_error": {
                "code": "DataShape"
            }
        },
        "message": "Input prediction data X_pred or input forecast_destination contains dates prior to the latest date in the training data. Please remove prediction rows with datetimes in the training date range or adjust the forecast_destination date."
    }
}
@MS-Alexander @ms-aminianp @Rohit-MSFT @msft-adrianma

**Comment by rajibstats** [comment]
Hi all,

My experiment is running successfully till training successfully. But when I am going to predict on test data with bellow code, Its throwing an exception.
y_predictions, X_trans = fitted_model.forecast(X_test)

Exception:

WrongShapeDataError: WrongShapeDataError:
	Message: Input prediction data X_pred or input forecast_destination contains dates prior to the latest date in the training data. Please remove prediction rows with datetimes in the training date range or adjust the forecast_destination date.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "InvalidData",
            "inner_error": {
                "code": "DataShape"
            }
        },
        "message": "Input prediction data X_pred or input forecast_destination contains dates prior to the latest date in the training data. Please remove prediction rows with datetimes in the training date range or adjust the forecast_destination date."
    }
}

**Comment by RohitMungi-MSFT** [comment]
@rajibstats Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by rajibstats** [comment]
I have used bellow code:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-orange-juice-sales/auto-ml-forecasting-orange-juice-sales.ipynb

**Comment by RohitMungi-MSFT** [comment]
@rajibstats After running the notebook as is I was able to predict without any errors in any of the steps.
![image](https://user-images.githubusercontent.com/46958063/79232176-cc80d700-7e84-11ea-8fc1-e5ed22de951f.png)

**Comment by RohitMungi-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag @RohitMungi-MSFT in your reply.
