### ISSUE TITLE
Need to add description for each transformer in this page. 

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#913]
There's no a single explanation/description in this page. Each transformer should have a short description saying what it does. i.e. "What MaxAbsScaler does"

This other page has the same issue:
https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.constants.supportedtransformers?view=azure-ml-py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330c878e-f793-2e6a-1fbc-46900c25af3a
* Version Independent ID: fbce2079-09fc-b32c-c737-ee44efe6a23a
* Content: [azureml.automl.core.constants.SupportedTransformersFactoryNames.Generic class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.constants.supportedtransformersfactorynames.generic?view=azure-ml-py#maxabsscaler)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.constants.SupportedTransformersFactoryNames.Generic.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.constants.SupportedTransformersFactoryNames.Generic.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the feedback. We will update you shortly.

**Comment by ram-msft** [comment]
@Aniththa can you please check on this.

**Comment by vmagelo** [comment]
Worked with Aniththa and we improved the docs around transformers. Changes will appear in next SDK release in 1-2 weeks.
