### ISSUE TITLE
experiment_timeout_hours description should mention that it can be decimal (i.e. 0.25 for 15min)

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#915]
experiment_timeout_hours parameter's description should mention that it can be decimal (i.e. 0.25 for 15min).
Other than that it initially looks like the minimum value is 1h.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by CESARDELATORRE** [comment]
Also mention the dataset's limit in size (rows * cols cannot be greater than 10,000,000) in order to be able to specify less than 1.0 hours, or you'll get this error:

"Message: The ExperimentTimeout should be set more than 60 minutes with an input data of rows*cols(535690*58=31070020) more than 10,000,000."

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by jadhosn** [comment]
@CESARDELATORRE regarding the dataset limit, how does that limit look for larger time frames?

**Comment by CESARDELATORRE** [comment]
The dataset size limit in Azure AutoML is 100GB if using AML remote compute runs using certain trainers/algorithms that will stream the data while training from Azure ML **Datasets**.

Those trainers are based on NimbusML/ML.NET that support data-streaming and would be automatically selected due to the data size.

If not using those trainers supporting data-streaming (i.e. if using AutoML local runs), then the limit will be in the local compute / VM memory and what it can handle when using Pandas Dataframe.

Is that what you are asking?

**Comment by vmagelo** [comment]
Docs work is done. Changes will appear in next sdk release 1-2 weeks.

**Comment by CESARDELATORRE** [comment]
@vmagelo - If this is done, can you close/hide this issue?
It's still appearing in the doc page.
