### ISSUE TITLE
For max_concurrent_iterations and AMLCompute (Cluster) it should match number of nodes, not cores 

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#916]
max_concurrent_iterations
int
For max_concurrent_iterations and AMLCompute (Cluster) it should match number of nodes, not cores. 
The description says: 
"
Maximum number of iterations that would be executed in parallel on an AmlCompute cluster, on a DSVM, or on Databricks. This should be less than or equal to the number of cores on the AmlCompute/DSVM or worker nodes on Databricks."

Probably DSVM and AMLCompute (Training cluster) should be separated in different sentence since it's a very different case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by CESARDELATORRE** [comment]
Plus it should mention what's the by default value of max_concurrent_iterations if not specified.
Same issue for other parameters.

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the feedback. We will update you shortly.

**Comment by vmagelo** [comment]
@CESARDELATORRE - Changes for max_concurrent_iterations were made recently to separate AMLCompute, DSVM, and Databricks and other corrections. They haven't made it live yet.

For you second comment, are you suggesting that we put default values for all parameters? For methods, we get "free" default values printed out under parameters. For classes, we don't unfortunately and must do it manually. We rely on the class signature being the place to definitively show the defaults.  See image. 

Is this good enough, or do you think we need to put default for every parameter? Until now, for class parameter description we mention default value only when we are clarifying or talking about it.

![image](https://user-images.githubusercontent.com/51368918/79249989-57120800-7e7e-11ea-8918-eeb69df57b87.png)

**Comment by CESARDELATORRE** [comment]
Thanks @vmagelo,

I think users would prefer to have the by default param values in the description because the AutoMLConfig is "massive".. plus sometimes the default value needs an explanation on what exactly it means for that case.

I'd say we don't need that for all classes in AutoML, but this class in particular is the most important class for configuring AutoML runs, so we'd need to improve it. Most params need "more love" and further explanations. :)

This class is critical for AutoML.

**Comment by vmagelo** [comment]
Okay, working through tracking down some of those parameters and creating change request.

**Comment by vmagelo** [comment]
We updated parameters. Changes will appear in next release.

**Comment by CESARDELATORRE** [comment]
@vmagelo - If this is done, can you close/hide this issue?
It's still appearing in the doc page.
