### ISSUE TITLE
Tensorboard exmple notebook not working 

### ISSUE THREAD

**Issue by vineetgarhewal** [Azure/MachineLearningNotebooks#920]
1. Run this notebook - MachineLearningNotebooks/how-to-use-azureml/training-with-deep-learning/export-run-history-to-tensorboard/export-run-history-to-tensorboard.ipynb
2. Go to tensorboard url 
3. You'll hit "502 Bad Gateway" error

**Comment by ram-msft** [comment]
@vineetgarhewal Thanks for the feedback. We will update you shortly.

**Comment by lostmygithubaccount** [comment]
@ram-msft any update?

**Comment by rastala** [comment]
This notebook has been deprecated - please take a look at new documentation here:

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-tensorboard

**Comment by fionnmk** [comment]
> This notebook has been deprecated - please take a look at new documentation here:
> 
> https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-tensorboard

I have the exact same issue following this guide. Both options give a URL that leads to a 502 bad gateway error.

**Comment by NA-Dev** [comment]
I have the same issue months later. There doesn't seem to be much about this Azure ML system that isn't buggy.

**Comment by Rico2000** [comment]
any update?

**Comment by VELCpro** [comment]
We run into this issue today with my team. Any update?

**Comment by sweco-nlridc** [comment]
Also very interested in an update on this issue.
