### ISSUE TITLE
AMLConfig target_lags param ambiguity?

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#921]
Why does the description for `target_lags`, but only allow `int` ? I would love to pass multiple lags
> This is represented as a list or single integer

> When forecasting, this parameter represents the number of rows to lag the target values based on the frequency of the data. **This is represented as a list or single integer**. Lag should be used when the relationship between the independent variables and dependent variable do not match up or correlate by default. For example, when trying to forecast demand for a product, the demand in any month may depend on the price of specific commodities 3 months prior. In this example, you may want to lag the target (demand) negatively by 3 months so that the model is training on the correct relationship.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@Aniththa The documentation for `target_lags `indicates it is of type int but it looks like it should be list(int) according to the description of the field. Could you please review and correct the same?

**Comment by swanderz** [comment]
There's a few other forecasting params that should also be `list(int)` I believe. Plus the UI doesn't even let you enter a list and tells you it must be an integer. @nibaccam

**Comment by cartacioS** [comment]
You are both correct, we have work items opened now to update the documentation to say that target_lags accept a list as well as an integer. We already have a work item on our end to enable list input through the UI, so this is on our radar.

Could you point out the other forecasting params that should be list but aren't documented correctly?

**Comment by swanderz** [comment]
Well now I'm just not sure... maybe it is more about clarifying fixing some mislabeled things.

## `lag_length`?
in the function def at the top of AutoMLConfig, there's mention of `lag_length: int = 0,` but I assume that its been renamed to `target_lags`, right?

Can I add multiple lags to lag_length? In the [blog post ](https://azure.microsoft.com/en-us/blog/build-more-accurate-forecasts-with-new-capabilities-in-automated-machine-learning/), it mentions how passing  `lag_length=2` creates a 1-day lag and a 2-day lag? So is lag_length

> The table below illustrates how a lag length of two would be treated. Green columns are engineered features with lags of sales by one day and two day. The blue arrows indicate how each of the lags are generated by the training data. Not a number (Nan) are created when sample data does not exist for that lag period.
![](https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d5a15865-3df6-441a-84df-0136c9b0f68c.png)


## `target_rolling_window_size`

Can I create multiple lags? like I can with `target_lags`?

**Comment by vmagelo** [comment]
re: update of `target_lags` parameter in AutoMLConfig class: this is included in a PR in progress for updating docs.

**Comment by cartacioS** [comment]
Lag_length is an outdate parameter before target_lags we're introduced. We will be removing this parameter from our documentation. Though the blog (due to the nature of blogs) will remain as is. 

Targer_lags does accept a list of integers and those are the doc updated we have created work items for and will address.

**Comment by vmagelo** [comment]
Updated docs for target_lags.

**Comment by nibaccam** [comment]
Thank you for reporting this @swanderz . The docs update has been checked in. We will now proceed to close this thread. #please-close
