### ISSUE TITLE
example does not contain mpistep

### ISSUE THREAD

**Issue by miquelladeboer** [Azure/MachineLearningNotebooks#922]
For an example of using MpiStep, see the notebook https://aka.ms/pl-style-trans.
Example does not contain MpiStep

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45291b3-d33a-9e94-0335-d757bd53d7fb
* Version Independent ID: bcb6c980-141a-601f-9c18-d71c277edbbc
* Content: [azureml.pipeline.steps.MpiStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.mpistep?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.MpiStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.MpiStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@miquelladeboer Thanks for pointing this out. There is an existing issue for this item which i have referenced in this issue. 
Here is an [example ](https://github.com/Azure/MachineLearningNotebooks/blob/75610ec31cc83471e0eea10f13937a1e13a2b5ad/how-to-use-azureml/machine-learning-pipelines/pipeline-style-transfer/pipeline-style-transfer.ipynb)of MPI step from a previous commit of the notebook that you can refer.

**Comment by RohitMungi-MSFT** [comment]
@miquelladeboer We will now proceed to close this thread. If there are further questions regarding this matter, please tag @RohitMungi-MSFT in your reply.
