### ISSUE TITLE
AutoMLConfig max_cores_per_iteration=-1 ?

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#924]
What does setting  `max_cores_per_iteration=-1` accomplish? Its done' in [numerous AutoML notebooks](https://github.com/Azure/MachineLearningNotebooks/search?q=max_cores_per_iteration%3D-1&unscoped_q=max_cores_per_iteration%3D-1).

**Comment by CESARDELATORRE** [comment]
It means "use all the possible cores per iteration/child-run".

I created this issue on docs a couple of weeks ago. It'll be published in the upcoming docs release:
https://github.com/Azure/MachineLearningNotebooks/issues/895

Thanks for your feedback! 👍

**Comment by YutongTie-MSFT** [comment]
@swanderz 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
