### ISSUE TITLE
RunDetails(run).show() is not able to display and throwing error 

### ISSUE THREAD

**Issue by vineetgarhewal** [Azure/MachineLearningNotebooks#926]
1. Create a new notebook compute instance in workspace
2. Clone this notebook - MachineLearningNotebooks/how-to-use-azureml/work-with-data/datasets-tutorial/train-with-datasets/train-with-datasets.ipynb
3. Run cell by cell and submit a run
4. Try to show the run details by executing cell with - RunDetails(run).show() 
5. You'll hit error message - "Error displaying widget: model not found"

**Comment by ram-msft** [comment]
@vineetgarhewal Thanks for the question. We will update you shortly.

**Comment by vineetgarhewal** [comment]
Any update on this ?

**Comment by maswaffer** [comment]
Getting this in the "Getting Started with Azure Machine Learning" lab

**Comment by lostmygithubaccount** [comment]
should be fixed - please reopen if you experience this again
