### ISSUE TITLE
modules not found using databrickssteps in pipeline

### ISSUE THREAD

**Issue by psterkens1** [Azure/MachineLearningNotebooks#927]
Hi, 
Whenever I run an azureml pipeline in databricks with several databrickssteps (that access other databricks notebooks), I get an error while loading libraries (e.g. azure-storage-blob) during pipeline execution. When I run the command blocks manually in Databricks, I can import the libraries just fine but if the notebooks are accessed through databrickssteps, I suddenly get errors stating: 'no module named...'. 

![issue1](https://user-images.githubusercontent.com/63408637/79452793-036ffd80-7fe9-11ea-8475-925a8aae7c91.png)

I installed all the libraries on the databricks cluster that I use to run these notebooks. Furthermore, I tried passing the libraries using a runconfig argument in the Databrickssteps (without any luck). Any help would be really appreciated!

**Comment by TravisCragg-MSFT** [comment]
@psterkens1 can you post a link to the doc you are referring to?

**Comment by psterkens1** [comment]
I have used the following [notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/azure-databricks/databricks-as-remote-compute-target/aml-pipelines-use-databricks-as-compute-target.ipynb) as a basis for the set up of my workspace and construction of the pipeline. When accessing the model train notebook I constructed for my project during pipeline execution ([databricksstep](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.databricks_step.databricksstep?view=azure-ml-py)), the module errors occur.

**Comment by psterkens1** [comment]
It appears that the databrickssteps are running on a job cluster rather than the cluster I passed as compute target argument. That explains why the modules I installed are not present. Any idea why the passed compute is not used?

**Comment by shbijlan** [comment]
@psterkens1 Thank you for the feedback. I have opened a work item to investigate this. We should have some answers shortly.

**Comment by fahdkmsft** [comment]
@psterkens1 it seems that you want Pipelines to run your job on an interactive cluster but it runs it on a new job cluster, is that correct?

Could you please copy your code that you use to create DatabricksStep over here so I can check the parameters you are trying to use?
