### ISSUE TITLE
Documentation: Gloo or Nccl

### ISSUE THREAD

**Issue by pashminacameron** [Azure/MachineLearningNotebooks#931]
Is this a class for managing Gloo settings or Nccl settings? Documentation refers to Gloo, but the class name is Nccl. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45b7359-e799-3511-8da3-825fe92b469e
* Version Independent ID: 9f90199b-d892-e2a2-f075-6a29462c3969
* Content: [azureml.train.dnn.Nccl class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.nccl?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.Nccl.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.Nccl.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by TravisCragg-MSFT** [comment]
@pashminacameron Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by YutongTie-MSFT** [comment]
@pashminacameron I have updated document and fixed the typo. Thanks for the feedback. @j-martens please review the PR.

**Comment by vmagelo** [comment]
We addressed the bug in the docstring. Fix will appear in next release 1-2 weeks. Thanks.
