### ISSUE TITLE
Where is the entry point to getting started on Azure Notebooks?

### ISSUE THREAD

**Issue by MachineIntelligenceCN** [Azure/MachineLearningNotebooks#932]
https://github.com/Azure/MachineLearningNotebooks/blob/7970209069b38265fa74b6cc15fa2693a457ecb1/configuration.ipynb#L155

This line indicates the instructions in that link is feasible on [azure notebooks](notebooks.azure.com), which is not. I can't enter the code from https://microsoft.com/devicelogin.

![image](https://user-images.githubusercontent.com/45580364/79677965-f8a3ab80-8228-11ea-8990-2987e1aa45a8.png)

I guess it is due to the SUBSCRIPTION_ID. How to get that?

![image](https://user-images.githubusercontent.com/45580364/79677978-27218680-8229-11ea-9171-09b8e208072c.png)

**Comment by TravisCragg-MSFT** [comment]
@MachineIntelligenceCN Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by YutongTie-MSFT** [comment]
@MachineIntelligenceCN Thanks for reaching out to us, please follow the guidance for register your subscription of Azure and set up your Azure Machine Learning Workspace. https://github.com/Azure/MachineLearningNotebooks/blob/master/configuration.ipynb

We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.

Regards,
Yutong
