### ISSUE TITLE
Explain default behavior for 'Early Stopping' and 'Stopping Criteria'

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#934]
In the current reference page this is the only info about 'Early Stopping':
enable_early_stopping bool
Flag to enable early termination if the score is not improving in the short term.

Customers are demanding additional details about AutoML 'Stopping Criteria' and  'Early Stopping'. The following default behavior needs to be added to this page (probably at the 'enable_early_stopping' param section):

Default Behavior for Stopping Criteria: 
- If iteration and experiment timeout not specified -&gt; we turn early stopping on, experiment_timeout = 6 days, num_iterations = 1000 
- If experiment timeout specified: early_stopping = off, num_iterations = 1000 
 
Early Stopping Logic: 

- No early stopping for first 20 iterations (landmarks) 
- Early stopping window starts on 21st iteration and looks for early_stopping_n_iters iterations (currently set to 10) 
This means that the first iteration where stopping is probably the 31st. 
 
- AutoML still schedules 2 ensemble iterations AFTER early stopping, which might result in higher scores 
 
- Early stopping is triggered if the absolute value of best score calculated is same for past early_stopping_n_iters iterations. I.e., if there is no improvement in score for early_stopping_n_iters iterations. 

If this info is too large for a parameter's section, we might want to put it as a 'Default Behavior for Stopping Criteria' at the end of the page, within the REMARKS section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment]
@CESARDELATORRE Thanks for the feedback. We will update you shortly.

**Comment by j-martens** [comment]
@CESARDELATORRE - did you work with @vmagelo on this issue? After this month, reference content will be turned back over engineering completely.

**Comment by CESARDELATORRE** [comment]
I did not talk to @vmagelo any further. 
Basically, it'll be to add the information above as part of the AutoMLConfig class reference page:
https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py

Adding @Aniththa so she can coordinate and track this down. I don't have bandwidth to drive it.

**Comment by vmagelo** [comment]
Info added. Will appear in next SDK release.

**Comment by j-martens** [comment]
Thanks for your post. This has been addressed and we will now proceed to close the thread.
