### ISSUE TITLE
Remarks - register_azure_data_lake_gen2

### ISSUE THREAD

**Issue by masoncusack** [Azure/MachineLearningNotebooks#935]
Under the register_azure_data_lake_gen2 function, it would be great to have a remarks section that warns developers that the recommended way to read data from an AzureDataLakeGen2Datastore is via registration of a Dataset. We should warn that using DataReferences for reading, as well as generally writing to an AzureDataLakeGen2Datastore, are not supported capabilities.

Relevant links to documentation for Dataset and DataReference should probably also be included. 

This is a good place for the warning because developers will see it before attempting registration. I ran into prolonged problems with this when I attempted to use a registered Gen 2 Data Lake store like other stores which support the use of DataReferences, and writing data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72d4eb-b5c9-c98d-3305-be3c00e937a2
* Version Independent ID: 5576d10f-9dad-b5cd-7032-07ce54f17b68
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@masoncusack Thanks for the suggestions. @danielsc Can the above suggestions be incorporated in the doc updates for datastore class?

**Comment by MayMSFT** [comment]
thanks for the feedback. we will track this as a bug for API reference update

**Comment by j-martens** [comment]
@MayMSFT - do we have an update here?

**Comment by MayMSFT** [comment]
Yes. the PR has been completed on last sunday. changes will go live in the next sdk release.

**Comment by j-martens** [comment]
Thanks for your report. This issue has now been resolved. Thank you. #please-close
