### ISSUE TITLE
Add to note about data access

### ISSUE THREAD

**Issue by masoncusack** [Azure/MachineLearningNotebooks#936]
The notes at the top of this page on data access should probably also stress that the recommended method for reading data from this type of store is via registration of a Dataset, and that previously supported access methods such as DataReferences are no longer supported. 

We may also want to mention that writing back intermediate pipeline data to this Datastore type is not currently possible, and enclose all this in a purple "note" window so that it's more prominent. It's great that it's at the very top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67812833-0e6c-e5f8-a94a-0d9711ad8670
* Version Independent ID: e5f3de4a-2588-3db2-83d5-23b4fb846fd0
* Content: [azureml.data.azure_data_lake_datastore.AzureDataLakeGen2Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.azure_data_lake_datastore.azuredatalakegen2datastore?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.azure_data_lake_datastore.AzureDataLakeGen2Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.azure_data_lake_datastore.AzureDataLakeGen2Datastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by masoncusack** [comment]
There's also the fact that if using Service Principal Auth (which I believe is required for working with Data Lake), the SP or app registration needs to be assigned the specific RBAC role of "Storage Blob Data Owner", which is broadly poorly documented, and may help developers adopt the use of this datastore in their AML work.

I ran into initially confusing authentication issues using this Datastore type because of this, so it would also be helpful to add this to the notes.

**Comment by RohitMungi-MSFT** [comment]
@masoncusack Thanks for the feedback. @danielsc Can we incorporate this recommendation as a note in the SDK documentation?

**Comment by MayMSFT** [comment]
thanks for the feedback. we will work with documentation for the update

**Comment by vmagelo** [comment]
We updated the docs. Changes will appear in next SDK release in 1-2 weeks. Thanks!
