### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by wmpauli** [Azure/MachineLearningNotebooks#937]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/using-environments/using-environments.ipynb

Next steps, at bottom of notebook, top two are dead links.

Thanks

**Comment by Mike-Ubezzi-MSFT** [comment]
@wmpauli Thank you for bringing this to our attention. We will have this issue corrected.

**Comment by RohitMungi-MSFT** [comment]
@rastala It looks like github render content links are now dead.

https://render.githubusercontent.com/train-on-amlcompute
https://render.githubusercontent.com/train-on-remote-vm

Could you please update the same with the correct links?

**Comment by SamVanhoutte** [comment]
also in the main readme.md there are quite a few dead links
some here: 
- ./how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb
- ./how-to-use-azureml/training-with-deep-learning/distributed-pytorch-with-horovod/distributed-pytorch-with-horovod.ipynb
- ./how-to-use-azureml/training/logging-api/logging-api.ipynb
