### ISSUE TITLE
Add tensorflow2 E2E tutorials

### ISSUE THREAD

**Issue by DjangoPeng** [Azure/MachineLearningNotebooks#938]
TensorFlow 2 has been released for more than 1 year. 

And there are amounts of developers and users heading to TensorFlow 2, which is more friendly and easier to use. But we don't have any related tutorials or guides for that. 

As a TensorFlow contributor and MS Gold Partner, I'd like to submit some PRs to fill in the gap between TF 1.x and 2.x, since I just completed an E2E pipeline of MobileNet with TensorFlow 2.2.0rc2 released last month.

**Comment by ram-msft** [comment]
@DjangoPeng Thanks for the feedback. Please feel free to raise a PR for the same.

**Comment by DjangoPeng** [comment]
Sure, I'll raise a PR this day.  Where do you suggest to place the tutorial?

How about creating a new folder named use-tensorflow-2 under MachineLearningNotebooks/tutorials?

@ram-msft

**Comment by ram-msft** [comment]
@DjangoPeng Yes feel free to create under MachineLearningNotebooks/tutorials or you can use the following ml-frameworks/tensorflow folder. 
https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/ml-frameworks/tensorflow

**Comment by shbijlan** [comment]
@DjangoPeng @ram-msft can we close this issue?

**Comment by lostmygithubaccount** [comment]
@DjangoPeng going to proceed to close - if you're still interested in contributing tf2 examples, please raise a PR to https://github.com/azure/azureml-examples, thanks!
