### ISSUE TITLE
No module named 'azureml.datadrift'

### ISSUE THREAD

**Issue by madiepev** [Azure/MachineLearningNotebooks#939]
After updating the sdk (stable version) and importing the datadrift object, I get the error that there is no module named datadrift. When installing datadrift specifically during the sdk update, I see the WARNING: azureml-sdk 1.3.0 does not provide the extra 'datadrift'. Is the example code still correct or should the object be imported using a different name for datadrift (e.g. datadriftdetector)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971e236e-9b2d-45c6-0a25-af77b8fb361d
* Version Independent ID: 630ef5c4-863a-b8ca-f001-d5a147bc1bfe
* Content: [azureml.datadrift.datadriftdetector.DataDriftDetector class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-datadrift/azureml.datadrift.datadriftdetector.datadriftdetector?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-datadrift/azureml.datadrift.datadriftdetector.DataDriftDetector.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-datadrift/azureml.datadrift.datadriftdetector.DataDriftDetector.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@madiepev we will review your feedback and get back to you shortly. Thanks.

**Comment by madiepev** [comment]
It seems to work after I do a pip install of azureml-datadrift. It's not specified in the documentation however that this needs to be done (and I think this wasn't necessary before). Could you add this?

**Comment by GiftA-MSFT** [comment]
@madiepev you received the error because you needed to install azureml-datadrift. The following document specifies the [pre-requisites](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-data-drift#prerequisites). Thanks.

**Comment by madiepev** [comment]
Can this be added to the SDK documentation too? Just like other necessary installs are also listed in this documentation?

**Comment by GiftA-MSFT** [comment]
@madiepev install information is specified [here](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py) and not in the class documents.
@j-martens do you have any input here?

**Comment by madiepev** [comment]
Yes I've seen that. The install for data-drift is not mentioned on that page, could that be added?

**Comment by GiftA-MSFT** [comment]
Gotcha.

**Comment by GiftA-MSFT** [comment]
@madiepev thanks for your feedback, the content team has created a work item to add azureml-datadrift to the SDK document, I will now proceed to close this thread.
