### ISSUE TITLE
Adding custom files (own modules) in docker image

### ISSUE THREAD

**Issue by Axxeption** [Azure/MachineLearningNotebooks#94]
Hi,

I want to deploy my own trained model like stated in this notebook (https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/02.deploy-models.ipynb) 

When I want to make the docker file, it seems that it's only possible using the Environment .yml file. Though to score on my model I need more then some packages, but I need to use my own local and custom models. Basically, I want to upload some extra folders to my dockerImage so that I can import that code in score.py. 

Is there any way to add files in the docker of do I have to put them online so I can download them in the init() phase? Which would be a very inefficient workaround...

Regards

**Comment by rastala** [comment]
You can specify additional Docker build steps, see docker_file argument in ContainerImageConfig:

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.image.container.containerimageconfig?view=azure-ml-py

**Comment by Axxeption** [comment]
Wauw, great! That was exactly what I needed, thanks!

**Comment by sleebapaul** [comment]
@Axxeption @rastala   Would you mind helping me with an example of using `ContainerImageConfig`? I need to set up a `CUDA 9.1 + PyTorch 0.4` for my purpose. I tried using `Estimator` with `CustomDocker` option but the run was crashing providing little information. 

I've raised an issue at [here](https://github.com/Azure/MachineLearningNotebooks/issues/282) but didn't get any help.

**Comment by Axxeption** [comment]
@sleebapaul did you try to run this docker locally already?

**Comment by sleebapaul** [comment]
@Axxeption Unfortunately, I use a Mac and I can't try CUDA containers it seems.
