### ISSUE TITLE
Problems with the wait_for_completion() function once submited a pipeline

### ISSUE THREAD

**Issue by aleixsd** [Azure/MachineLearningNotebooks#941]
I had this problem during this week. I have a pipeline that runs a few RScriptSteps which used to work and I have not changed. The main issue is when I run the python script, that creates and submits the pipeline. Then, the next error appears:
{
    "error": {
        "code": "UserError",
        "message": "User program failed with TypeError: wait_for_completion() got an unexpected keyword argument 'timeout_seconds'",
        "detailsUri": "https://aka.ms/azureml-known-errors",
        "details": [],
        "debugInfo": {
            "type": "TypeError",
            "message": "wait_for_completion() got an unexpected keyword argument 'timeout_seconds'",
            "stackTrace": ......
        },
        "messageParameters": {}
    },
    "time": "0001-01-01T00:00:00.000Z"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with TypeError: wait_for_completion() got an unexpected keyword argument 'timeout_seconds'\",\n        \"detailsUri\": \"https://aka.ms/azureml-known-errors\",\n        \"details\": [],\n        \"debugInfo\": {\n            \"type\": \"TypeError\",\n            \"message\": \"wait_for_completion() got an unexpected keyword argument 'timeout_seconds'\",\n            \"stackTrace\": \"  File \\\"azureml-setup/context_manager_injector.py\\\", line 127, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/azureml-envs/azureml_....../lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/azureml-envs/azureml_...../lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/azureml-envs/azureml_....../lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"src/main/pipeline/ml-pipeline.py\\\", line 132, in &lt;module&gt;\\n    pipeline_run1.wait_for_completion()\\n  File \\\"/azureml-envs/azureml_.....1/lib/python3.6/site-packages/azureml/pipeline/core/run.py\\\", line 291, in wait_for_completion\\n    raise_on_error=raise_on_error)\\n\"\n        },\n        \"messageParameters\": {}\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
    }
}

When I call the wait_for_completition() function I do not specify any parameters but it seems like it does not accept the default ones.

Any idea why this error appears now? Last week it all worked perfectly

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a064d37-24e5-beb7-693f-f320540e0049
* Version Independent ID: cdec949d-d0ec-aa5e-5d78-faf85bb9e6b0
* Content: [azureml.pipeline.core.PipelineRun class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinerun?view=azure-ml-py#wait-for-completion-show-output-true--timeout-seconds-9223372036854775807--raise-on-error-true-)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@aleixsd  
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by shirolkar** [comment]
I see the same error "wait_for_completion() got an unexpected keyword argument 'timeout_seconds'" when running the build pipeline in MCW MLOps https://github.com/microsoft/MCW-ML-Ops. It fails on the call pipeline_run.wait_for_completion(show_output=True). Note that the pipeline steps complete successfully and the error happens right at the end.

**Comment by aleixsd** [comment]
@YutongTie-MSFT 

Do you have any news about the issue?

Thanks!

**Comment by luuk-codebeez** [comment]
I have the same error.

**Comment by martin-weber** [comment]
I had the same  issue and was able to solve it by running:
`pip install --upgrade azureml-sdk`

**Comment by aleixsd** [comment]
Hello @martin-weber,

In my case, I use Azure Pipelines to execute the ML pipeline. This means every time I run the ML pipeline I use the latest azureml-sdk but error still ocurrs. I also tried other versions of azureml-sdk but haven't found a solution yet.

@YutongTie-MSFT, it's been 17 days already. Have you got any news about this issue?

Thank you

**Comment by luuk-codebeez** [comment]
If so please close the issue :)

**Comment by shbijlan** [comment]
#please-close
