### ISSUE TITLE
train-on-local notebook fail with error "Your project exceeds the file limit of 2000."when run from kubeflow notebook server...

### ISSUE THREAD

**Issue by initmahesh** [Azure/MachineLearningNotebooks#943]
We are trying to run AML notebook “train -on-local”  on DSVM with the Kubeflow cluster on Azure VM with AKS luster on cloud, we wish to run the sample on Azure stack to leverage compute ….
https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/training/train-on-local
It fails with the error below know anyone who can help here as I think the issue is due to Kubeflow mount too long path, but not sure as to how we can get around this ….

On the same cluster, I can run my notebook and train model with Kubeflow but failing with the above sample only with error below …

Error:     
---------------------------------------------------------------------------
SnapshotException                         Traceback (most recent call last)
<ipython-input-9-2c2485b270ab> in <module>
----> 1 run = exp.submit(src)

~/.local/lib/python3.6/site-packages/azureml/core/experiment.py in submit(self, config, tags, **kwargs)
    200         submit_func = get_experiment_submit(config)
    201         with self._log_context("submit config {}".format(config.__class__.__name__)):
--> 202             run = submit_func(config, self.workspace, self.name, **kwargs)
    203         if tags is not None:
    204             run.set_tags(tags)

~/.local/lib/python3.6/site-packages/azureml/core/script_run_config.py in submit(script_run_config, workspace, experiment_name, run_id, _parent_run_id)
     55     run = _commands.start_run(project, run_config,
     56                               telemetry_values=script_run_config._telemetry_values,
---> 57                               run_id=run_id, parent_run_id=_parent_run_id)
     58     run.add_properties(global_tracking_info_registry.gather_all(script_run_config.source_directory))
     59 

~/.local/lib/python3.6/site-packages/azureml/_execution/_commands.py in start_run(project_object, run_config_object, run_id, injected_files, telemetry_values, parent_run_id, prepare_only, check)
    114             raise ExperimentExecutionException("Can not check preparation of local targets")
    115         return _start_internal_local_cloud(project_object, run_config_object,
--> 116                                            **shared_start_run_kwargs)
    117     else:
    118         return _start_internal(project_object, run_config_object, prepare_check=check,

~/.local/lib/python3.6/site-packages/azureml/_execution/_commands.py in _start_internal_local_cloud(project_object, run_config_object, prepare_only, custom_target_dict, run_id, injected_files, telemetry_values, parent_run_id)
    279                 raise ExperimentExecutionException(ex.output)
    280 
--> 281             snapshot_id = snapshot_async.get() if snapshot_async else None
    282             thread_pool.close()
    283 

/usr/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
   642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

/usr/lib/python3.6/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    117         job, i, func, args, kwds = task
    118         try:
--> 119             result = (True, func(*args, **kwds))
    120         except Exception as e:
    121             if wrap_exception and func is not _helper_reraises_exception:

~/.local/lib/python3.6/site-packages/azureml/_restclient/snapshots_client.py in create_snapshot(self, file_or_folder_path, retry_on_failure, raise_on_validation_failure)
     92                             "\n".format(file_or_folder_path, SNAPSHOT_MAX_FILES)
     93             if raise_on_validation_failure:
---> 94                 raise SnapshotException(error_message)
     95             else:
     96                 print(error_message)

SnapshotException: SnapshotException:
                Message: ====================================================================

While attempting to take snapshot of /home/jovyan
Your project exceeds the file limit of 2000.

====================================================================

                InnerException None
                ErrorResponse 
{
    "error": {
        "message": "====================================================================\n\nWhile attempting to take snapshot of /home/jovyan\nYour project exceeds the file limit of 2000.\n\n====================================================================\n\n"
    }
}

**Comment by ram-msft** [comment]
@initmahesh Thanks for the question. We will update you shortly.

**Comment by lostmygithubaccount** [comment]
@ram-msft any updates?
