### ISSUE TITLE
BUG: Versioning not enabled when pulling data from SQL DB/DW into Azure ML datasets

### ISSUE THREAD

**Issue by swaticolab** [Azure/MachineLearningNotebooks#944]
Whenever I pull the data from an azure SQL DB or DW, the version history is not maintained. Everytime I pull a new data, the first version is only refreshing.
I have created a reproducible example to explain my issue. 

https://github.com/swaticolab/MachineLearningNotebooks/blob/SQL_to_ML/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/Connect_SQL_to_ML_dataset.ipynb

**Comment by RohitMungi-MSFT** [comment]
@swaticolab Could you please check if all versions are available when you specify the version with [get_by_name()](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py#get-by-name-workspace--name--version--latest--)

Also, a note in azureml.core.dataset.dataset [documentation ](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py#to-pandas-dataframe--) mentions that [to_pandas_dataframe()](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.dataset.dataset?view=azure-ml-py#to-pandas-dataframe--) is deprecated and replaced by azureml.data.tabulardataset [to_pandas_dataframe()](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.tabulardataset?view=azure-ml-py#to-pandas-dataframe-on-error--null---out-of-range-datetime--null--). Could you please check with this implementation to check if all versions are shown?

**Comment by swaticolab** [comment]
@RohitMungi-MSFT Yes I did try using the get_by_name() approach. But it was still not working.

**Comment by swanderz** [comment]
@MayMSFT

**Comment by MayMSFT** [comment]
dataset is just a pointer to data in your storage. here is an article that explains how dataset versioning works:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-version-track-datasets
