### ISSUE TITLE
Adapt Beer forecasting for local run without DNN?

### ISSUE THREAD

**Issue by adamthorne** [Azure/MachineLearningNotebooks#945]
The Beer Forecasting sample for AzureML relies on remote_run as it uses the DNN algorithms which are not yet available for local compute. I am wondering if there is a script available that doesn't rely on DNN and only the other AutoML approaches?

**Comment by Mike-Ubezzi-MSFT** [comment]
@adamthorne Than you for your inquiry. Is there a specific document you are following for this tutorial? I found the following: https://gallery.azure.ai/Experiment/Forecasting-Beer-Consumption-2 but not sure if this is the same as what you are working from.

**Comment by adamthorne** [comment]
> Mike thanks I am working from this script here: (https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb) .

I am now progressing through the script and adapting it for use of the AutoML algorithms that are possible to run on local compute and will share them in a repo once available (will not be best practice but will work!). 

Thanks for sharing the example link you sent based on linear programming. I'd like to include some AutoML features beyond linear but may try to integrate this in the above! 


> 
> @adamthorne Than you for your inquiry. Is there a specific document you are following for this tutorial? I found the following: https://gallery.azure.ai/Experiment/Forecasting-Beer-Consumption-2 but not sure if this is the same as what you are working from.

**Comment by RohitMungi-MSFT** [comment]
@adamthorne Tagging the author @omkarmore83 for visibility.
