### ISSUE TITLE
pass specific files as parameter

### ISSUE THREAD

**Issue by shankarpandala** [Azure/MachineLearningNotebooks#946]
In this example 'sample_datapath1' refers to the path on the datastore which is a folder. If I have 4 files 1.jpg, 2.jpg, 3.jpg, 4.jpg in the 'sample_datapath1' folder  and I want only 1.jpg, 2.jpg only as the dataset, How can I choose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c885638-333a-17cf-7c37-2b9b55b7dd30
* Version Independent ID: bf4221f7-f110-008e-26f9-f81a996a9717
* Content: [azureml.data.datapath.DataPath class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.datapath.datapath?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.datapath.DataPath.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.datapath.DataPath.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@shankarpandala we will review your feedback and get back to you shortly, Thanks.

**Comment by MayMSFT** [comment]
Hi @shankarpandala 
You can 
1. create a dataset pointing to the folder 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets
2. mount the dataset to your compute target and load only the files you want in your script. you can pass in the name of the files as argument in your experiment
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets

**Comment by shankarpandala** [comment]
> Hi @shankarpandala
> You can
> 
> 1. create a dataset pointing to the folder
>    https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets
> 2. mount the dataset to your compute target and load only the files you want in your script. you can pass in the name of the files as argument in your experiment
>    https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets

Thanks! If this is the only way. You can close the issue.
