### ISSUE TITLE
RScriptStep missing

### ISSUE THREAD

**Issue by lucazav** [Azure/MachineLearningNotebooks#947]
In [this page](https://render.githubusercontent.com/view/ipynb?commit=7970209069b38265fa74b6cc15fa2693a457ecb1&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6c7563617a61762f4d616368696e654c6561726e696e674e6f7465626f6f6b732f373937303230393036396233383236356661373462366363313566613236393361343537656362312f686f772d746f2d7573652d617a7572656d6c2f6d616368696e652d6c6561726e696e672d706970656c696e65732f696e74726f2d746f2d706970656c696e65732f616d6c2d706970656c696e65732d67657474696e672d737461727465642e6970796e62&nwo=lucazav%2FMachineLearningNotebooks&path=how-to-use-azureml%2Fmachine-learning-pipelines%2Fintro-to-pipelines%2Faml-pipelines-getting-started.ipynb&repository_id=259281926&repository_type=Repository#Creating-a-Step-in-a-Pipeline) about pipeline steps the [RScriptStep](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.rscriptstep?view=azure-ml-py) is missing.

**Comment by GiftA-MSFT** [comment]
@lucazav we will review your feedback and get back to you shortly. Thanks.

**Comment by mx-iao** [comment]
As RScriptStep is in preview we are leaving it out of that notebook for now.
