### ISSUE TITLE
Azure DataStore name limits?

### ISSUE THREAD

**Issue by LordGordonQ** [Azure/MachineLearningNotebooks#951]
The Azure ML web interface dictates that "Datastore name should only consist of lowercase letters, digits, and underscore". This information is lacking in the documentation. And, in general, such limits are lacking in whole Azure ML SDK documentation.

Is is possible to better specify such limits to avoid annoying errors in production code?

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72d4eb-b5c9-c98d-3305-be3c00e937a2
* Version Independent ID: 5576d10f-9dad-b5cd-7032-07ce54f17b68
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by LordGordonQ** [comment]
Btw, there are also limits for the maximum length of the string?

**Comment by YutongTie-MSFT** [comment]
@LordGordonQ 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SturgeonMi** [comment]
Thanks for the feedback!
Opened a bug for this documentation improvement.

And currently we don't have hard limitation of length of the string for Datastore name. (As long as the length is within docdb limit.)

**Comment by YutongTie-MSFT** [comment]
@LordGordonQ 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
