### ISSUE TITLE
Sample code is wrong, the parameter 'experiment' in AutoMLRun() is an object/variable, not a string/name

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#953]
The parameter 'experiment' in AutoMLRun() is an object/variable, not a string/name

This example code is wrong and doesn't work:

from azureml.train.automl.run import AutoMLRun
remote_run = AutoMLRun(experiment = 'experiment name', run_id = 'replace with your run id')

The following code does work:

from azureml.train.automl.run import AutoMLRun
ws = Workspace.from_config()
experiment = ws.experiments['my-experiment-name']
automl_run = AutoMLRun(experiment, run_id = 'AutoML_9fe201fe-89fd-41cc-905f-2f41a5a98883')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f73dc3-6e33-e99d-de65-c8c3d86cdbf7
* Version Independent ID: 4df3e0e3-4d59-eae6-1646-09c873f8fcea
* Content: [azureml.train.automl.run.AutoMLRun class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.run.automlrun?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.run.AutoMLRun.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.run.AutoMLRun.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@CESARDELATORRE 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
We changed the example. Change will go live in 1-2 weeks with next release.

**Comment by j-martens** [comment]
Thank you very much for your report. We have made the fix and will now proceed to close this issue. #please-close
