### ISSUE TITLE
scoring_uri is said to be of bool type, but it's not

### ISSUE THREAD

**Issue by gabrielnespoli** [Azure/MachineLearningNotebooks#954]
The scoring endpoint for the Webservice "azureml.core.webserivce.AksWebservice.scoring_uri" is listed as type bool, but it's not. It's necessary to correct the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c5068c-bf75-51ea-a8b3-a3356ba81b5c
* Version Independent ID: 9036f1f0-f669-bb28-74e7-3ea8dae6d7e9
* Content: [azureml.core.webservice.AksWebservice class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.akswebservice?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AksWebservice.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.webservice.AksWebservice.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment]
@gabrielnespoli 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by vmagelo** [comment]
Thanks for the report. We addressed this in the docs and change will appear live in next SDK release in 1-2 weeks.

**Comment by PeterCLu** [comment]
#please-close
