### ISSUE TITLE
The transformer parameter in add_transformer_params() should specify a list of the possible transformers (i.e. 'Imputer', etc.)

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#955]
The transformer parameter in add_transformer_params() should specify a list of the possible transformers (i.e. 'Imputer', etc.)

With the current info a user won't know what are the possible transformers.
Also, add sample code or a pointer to a notebook using "custom featurization/transformers" such as this:

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-orange-juice-sales/auto-ml-forecasting-orange-juice-sales.ipynb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5904e4cc-a5e4-04f3-c430-46e6ceb77e3f
* Version Independent ID: 5087fbc2-9df6-cf25-6a2f-fbb731525f0b
* Content: [azureml.automl.core.featurization.featurizationconfig.FeaturizationConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.featurization.featurizationconfig.featurizationconfig?view=azure-ml-py#add-transformer-params-transformer--str--cols--typing-list-str---params--typing-dict-str--typing-any------none)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.featurization.featurizationconfig.FeaturizationConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.featurization.featurizationconfig.FeaturizationConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@CESARDELATORRE we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
re-assigning to @j-martens since this has to do with doc enhancement. Thanks.

**Comment by j-martens** [comment]
@CESARDELATORRE - do you know what the possible transformers are? Who is the point person on the team for this info?

**Comment by CESARDELATORRE** [comment]
@j-martens - Not sure, probably **Vinod Shanbhag**. If not, he'll be able to forward to the right folk.
I'll send an email to him copying you, ok? :)

**Comment by vmagelo** [comment]
We updated the docs for add_transformer_params with example and pointing to list of CUSTOMIZABLE_TRANSFORMERS attribute. We also improved the general class docs. Changes will go live in next release 1-2 weeks.

**Comment by j-martens** [comment]
Thank you very much for your report. We have made the fix and will now proceed to close this issue. #please-close
