### ISSUE TITLE
No such file or directory/ERROR conda.core.link:_execute(502): issue while building a pipeline

### ISSUE THREAD

**Issue by farh33n** [Azure/MachineLearningNotebooks#956]
Hi
I am building an ML pipeline following below link.
https://docs.microsoft.com/en-us/learn/modules/create-pipelines-in-aml/
**I am getting below error for the first step of pipeline.**
`Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... failed
[91m
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::astor-0.7.1-py_0'.
FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_27ab7248e2ed0650e4ce536266f776dc/bin/python3.6'")
Attempting to roll back.

[0mRolling back transaction: ...working... done
[91m
FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_27ab7248e2ed0650e4ce536266f776dc/bin/python3.6'")

[0mThe command '/bin/sh -c ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_27ab7248e2ed0650e4ce536266f776dc -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig' returned a non-zero code: 1
2020/05/05 10:54:28 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: cha failed after 2m35s. Error: failed during run, err: exit status 1

Error occurred: Image build failed. For more details, check log file azureml-logs/20_image_build_log.txt
'
**I have updated conda version to 4.8.3.
I have also included this code.**
`myenv.add_pip_package("azureml-defaults")
myenv.add_pip_package("keras")
myenv.add_pip_package("pynacl==1.2.1")
myenv.add_pip_package("astor==0.8.1")

with open("myenv.yml", "w") as f:
    f.write(myenv.serialize_to_string())

with open("myenv.yml", "r") as f:
    print(f.read())`

but the error remains. I will appreciate if someone can guide me towards the solution.
Thanks

**Comment by YutongTie-MSFT** [comment]
@farh33n 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by vizhur** [comment]
this is a user error. there is no package astor-0.7.1-py_0 on conda-forge channel caused by recent (kinda... it happened 2 months ago) conda channels reshuffle. 

please add anaconda channel to your environment. latest AzureML SDK versions automatically add it if user does not specify the channels
