### ISSUE TITLE
ParallelRunStep: Workers don't pick up any task!

### ISSUE THREAD

**Issue by MaheshSQL** [Azure/MachineLearningNotebooks#957]
Hello Team,

I am running distributed training on Azure ML Compute Cluster, 3 nodes.
I'm using file dataset and mini_batch parameter is set = 1 (So that files are distributed to all workers). There are 100 files read from Datastore.

After reviewing the Worker logs from Azure ML Studio (Workspace), I see all the print() statements in stdout.txt for my master node. However these stdout files are blank for all other 2 workers.
Nothing is picked up or worked on by workers. I see there are processes created on workers, but they are not picking up the code.

I remember seeing the task getting distributed across all workers for my past runs, but can't somehow reproduce it.

I confirm that there are no errors and experiment completes successfully, however not all files are used by workers.

I compared the process.task.csv files of master node and worker. I notices that the tasks are picked up by master node and run, however nothing happens on worker node after picking up task.

Please see below comparison.

**Master Node:**
Task Id,Dequeue Count,Start Time,Total,Succeeded,Failed,Elapsed Seconds,Process Seconds,Run Method Seconds,Status,Error
N/A,N/A,2020-05-06T05:50:48.682392,N/A,N/A,N/A,N/A,N/A,N/A,ENTRY_SCRIPT_INIT_START,
N/A,N/A,2020-05-06T05:50:48.695997,N/A,N/A,N/A,N/A,N/A,N/A,ENTRY_SCRIPT_INIT_DONE,
1,1,2020-05-06T05:50:48.727529,0,0,0,0,0,0,TASK_PICKED,
1,1,2020-05-06T05:50:48.727529,1,1,0,9.284419059753418,1.428939417,9.275160710999899,**TASK_PROCESSED**,
17,1,2020-05-06T05:50:58.066369,0,0,0,0,0,0,TASK_PICKED,
17,1,2020-05-06T05:50:58.066369,1,1,0,3.1083929538726807,1.749675871,3.0820019239999965,**TASK_PROCESSED**,
................................and so on, it works.

**Worker node:**
Task Id,Dequeue Count,Start Time,Total,Succeeded,Failed,Elapsed Seconds,Process Seconds,Run Method Seconds,Status,Error
N/A,N/A,2020-05-06T05:50:55.938494,N/A,N/A,N/A,N/A,N/A,N/A,ENTRY_SCRIPT_INIT_START,
N/A,N/A,2020-05-06T05:50:55.951807,N/A,N/A,N/A,N/A,N/A,N/A,ENTRY_SCRIPT_INIT_DONE,
7,1,2020-05-06T05:50:55.972707,0,0,0,0,0,0,**TASK_PICKED**,

As a result, only part of files are getting processed. From logs I also see that all mini-batches get created successfully. Also run() function is never called by any worker.

Please can you help.

#ParallelRunStep #azureml.contrib.pipeline

**Comment by GiftA-MSFT** [comment]
@MaheshSQL we will review your feedback and get back to you shortly. Thanks.

**Comment by MaheshSQL** [comment]
Thank you, we can see the worker stdout by going to AML Default BLOB Store for respective run.
Also the distributed training success can be confirmed from processed_task.csv under sys -> report where we can see tasks were processed by workers.

I believe the streaming of the worker stdout into Azure ML shall be fixed soon.
Closing the issue as it is no longer a blocker for me.

@psavdekar @GiftA-MSFT
