### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by adamthorne** [Azure/MachineLearningNotebooks#958]
WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001919ED04288>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /artifact/v2.0/subscriptions/fcb3eeed-e44c-484a-bb57-66793b629de4/resourceGroups/ML-CLOUD/providers/Microsoft.MachineLearningServices/workspaces/AZURE-ML/artifacts/batch/metadata/ExperimentRun/dcid.AutoML_7a1ebd6e-7a70-4d5b-91cf-debc33268459_27

In trying to run the sample experiments (beer forecast) I'm regularly running into connectivity issues such as the one above. I'm actually trying to run it as a local compute experiment. Some times this happens once and others it's repetitive. I wonder if I have a resource / subscription issue but not clear.

Sometimes the job finishes but others it just persists repeating this error voer and over. 

**Any views on how to debug or get after it?** 

Here is the train code: 
`    from azureml.core.runconfig import RunConfiguration
    # Edit a run configuration property on the fly.
    run_local = RunConfiguration()
    run_local.environment.python.user_managed_dependencies = False
    #run the job
    local_run = experiment.submit(automl_config, show_output=True)
    local_run`

**_I'm also getting it when just trying test run with a specified earlier (successful train run)_**
`run_id = 'AutoML_7a1ebd6e-7a70-4d5b-91cf-debc33268459_8'
test_run_id = 'MLForecast_test_1588753528_7f0d1070'
test_run = Run(test_experiment, test_run_id)`
test_run.wait_for_completion()`

**Comment by GiftA-MSFT** [comment]
@adamthorne we will review your feedback and get back to you shortly. Thanks.

**Comment by adamthorne** [comment]
Thanks for this. I added the run details code to watch what was happening in the test_run

`    RunDetails(test_run).show() 
    print(RunDetails(test_run))`

I think the timeout is happening because of Conda issue .When I look in the 60_control_log.txt is the below message printed many, many times. That "wait" is presumably driving the time out shown above. 
**_Waiting for other Conda operations to finish...
Delete C:\Users\Adam.Thorne/.azureml/locks/azureml_conda_lock to override._**

In the Azure ML Portal on the experiment I see this related error:

_**UserError: Failed to build the conda environment with exit code: 1. Please check azureml-logs/60_control_log.txt for more details.**_

**Comment by GiftA-MSFT** [comment]
@danielsc can you please help look into this issue? Thanks.

**Comment by adamthorne** [comment]
I can report back that this seems to be a local environment or local performance issue. The above issue i can replicate over and over on an i5 Gen 7 Windows 10 Enterprise computer. However I configured the exact same conda environment on an i7 Gen 8 Ubuntu machine and the script runs fine to completion with no time out I will close this issue.
