### ISSUE TITLE
AutoML extension installation fails on Ubuntu 20.04 (support Python 3.8)

### ISSUE THREAD

**Issue by lehmus** [Azure/MachineLearningNotebooks#959]
I am not able to install the AutoML extension on a local computer running Ubuntu 20.04. Tried to run this command from the documentation:

pip install --upgrade azureml-sdk[explain,automl]

but I run into the following error:

ERROR: Could not find a version that satisfies the requirement onnxruntime==1.0.0 (from azureml-train-automl-runtime~=1.4.0-&gt;azureml-train-automl~=1.4.0; extra == "automl"-&gt;azureml-sdk[automl]) (from versions: 1.2.0)
ERROR: No matching distribution found for onnxruntime==1.0.0 (from azureml-train-automl-runtime~=1.4.0-&gt;azureml-train-automl~=1.4.0; extra == "automl"-&gt;azureml-sdk[automl])

Python version is 3.8 (64bit) and Pip version is 20.1. I have also installed the ONNX library via Pip. ONNX version is 1.6.0, although I also tried downgrading it to 1.0.0 but received the same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Install the Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by ram-msft** [comment]
@lehmus Thanks for the question. We will update you shortly.

**Comment by vizhur** [comment]
@lehmus I believe that should work now. onnxruntime just released 3.8 version. If you see any issues please consider to user py37

**Comment by lehmus** [comment]
It seems that Python 3.8 is only supported for onnxruntime >= 1.2.0. This conflicts with requirement onnxruntime == 1.0.0 in 'azureml-train-automl' (latest version).

So the issue is not Ubuntu 20.04, but Python 3.8. I confirmed this by installing azureml-sdk[automl] with conda for both 3.7 and 3.8. Python 3.7 installation succeeds but 3.8 fails. So the current workaround is to use Python 3.7.

Thank you for your assistance.

**Comment by lehmus** [comment]
Note that the Windows Store currently ships Python 3.8, so AutoML installation will probably fail on Windows as well...

**Comment by vizhur** [comment]
resolving the issue as automl does not support python 3.8 at the moment until onboards with the latest onnx

**Comment by RileyMShea** [comment]
@vizhur Can this be-reopened now that azureml now officially supports python 3.8?

**Comment by vizhur** [comment]
@RileyMShea AutoML runtime still doesn't support 3.8

**Comment by savitamittal1** [comment]
Currently AutoML support python 3.6 and 3.7 version of python.
Version 3.8 is in roadmap and is planned to be added in the second semester of the year.

**Comment by kvijaykannan** [comment]
Closing the issue, as it is already responded
