### ISSUE TITLE
Experiment name length limit

### ISSUE THREAD

**Issue by RoozbehBandpey** [Azure/MachineLearningNotebooks#961]
- **Package Name**: azureml.core
- **Package Version**: 1.1.5
- **Operating System**: Windows 10 64-bit
- **Python Version**:  3.7.3 64-bit

While trying to fetch runs for experiments which have names longer that 36 character, the SDK returns this:
```powershell
azureml.exceptions._azureml_exception.UserErrorException: UserErrorException:
        Message: Experiment name must be between 1 and 36 characters long. Its first character has to be alphanumeric, and the rest may contain hyphens and underscores. No whitespace is allowed.
        InnerException None
        ErrorResponse
{
    "error": {
        "code": "UserError",
        "message": "Experiment name must be between 1 and 36 characters long. Its first character has to be alphanumeric, and the rest may contain hyphens and underscores. No whitespace is allowed."
    }
}
```
While still it is possible to submit experiments with names longer than 36 chars via AML pipeline
**How to handle metrics for those experiments?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb938463-51c2-43f3-d528-76a07a28bec8
* Version Independent ID: e15753c0-6fe1-100a-0efc-08c1f845dc83
* Content: [Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/index.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/index.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by GiftA-MSFT** [comment]
@RoozbehBandpey we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@maxluk can you please review the above feedback? Thanks.

**Comment by shbijlan** [comment]
@RoozbehBandpey Thank you for your feedback regarding the inconsistency on character limits across AML Pipelines. I am part of the Pipelines team and have opened a work item to track this issue which will be addressed in the planning and release cycle.

**Comment by shbijlan** [comment]
#please-close
