### ISSUE TITLE
Run setup.py before running main.py

### ISSUE THREAD

**Issue by zhipenghan** [Azure/MachineLearningNotebooks#964]
The backend is running the script within a docker container. As the users have customize environment to setup before running the main.py. It's not flexible as there is no way to customize the data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb938463-51c2-43f3-d528-76a07a28bec8
* Version Independent ID: e15753c0-6fe1-100a-0efc-08c1f845dc83
* Content: [Azure Machine Learning SDK for Python - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/docs-ref-conceptual/index.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/docs-ref-conceptual/index.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by GiftA-MSFT** [comment]
@zhipenghan we will review your feedback and get back to you shortly. Thanks.

**Comment by v-strudm-msft** [comment]
@zhipenghan Please provide additional detail illustrating the flexibility to customize the data you are looking for.

**Comment by CESARDELATORRE** [comment]
@zhipenghan - Note that for every PythonScriptStep in a pipeline or for any single Run, you can specify a custom environment with the RunConfiguration class later assigned to the step:

**RunConfiguration class:**
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfig.runconfiguration?view=azure-ml-py

What's the environment customization setup you'd need to do that cannot be performed with RunConfiguration before running the main.py

Also, for regular environments and easier environment setup, use curated environments in AML.
