### ISSUE TITLE
hbi_workspace setting

### ISSUE THREAD

**Issue by timoklimmer** [Azure/MachineLearningNotebooks#969]
The effect of setting hbi_workspace needs to be documented in more detail. What does "selectively" in "When set to True, downstream services will selectively disable logging." actually mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d94ed89-5c02-627d-be4b-7be85ffeb876
* Version Independent ID: 581b19dc-544c-6a91-fa47-3d582f23a34b
* Content: [azureml.core.workspace.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace.workspace?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@j-martens please can you help clarify? Thanks.

**Comment by vmagelo** [comment]
We added to the parameter description to link to more information and describe what this setting does a bit better. Changes will appear in next SDK release in 1-2 weeks.  Basically, some information is redacted for internally-collected telemetry but this has no impact on what users see. In addition, some additional encryption is performed as described here: https://docs.microsoft.com/azure/machine-learning/concept-enterprise-security#data-encryption.
