### ISSUE TITLE
Where does azureml (Model.register() ) really store the registered model in the storage?

### ISSUE THREAD

**Issue by ashoksamal6363** [Azure/MachineLearningNotebooks#970]
Where does azureml (Model.register() ) really store the registered model in the storage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1517f63f-2d2e-1539-060e-0a471c1c438a
* Version Independent ID: 9e466042-1059-b835-8c92-01e9d9858166
* Content: [azureml.core.model.Model class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@ashoksamal6363 we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment]
@ashoksamal6363 they are stored in your workspace.

![image](https://user-images.githubusercontent.com/51332022/81996334-bc425000-961a-11ea-8fe6-80aa111ef15b.png)
