### ISSUE TITLE
Strange exception when submitting ScriptRun locally

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/MachineLearningNotebooks#972]
Hello all, 

Just followed the very basic steps to try to execute a ScriptRun locally.  
I uploaded my repo notebook here: https://gist.github.com/SamVanhoutte/58433f6fc8646dd7c2aa4674ef4f28f0 - you should be able to run it against any AzureML workspace following the executions.

The code I executed is very straight forward:

```python
work_env =  Workspace.from_config()
exp = Experiment(workspace=work_env, name='Repo')

run_local = RunConfiguration()
run_local.environment.python.user_managed_dependencies = True

config = ScriptRunConfig(source_directory='.', script=script_file_name, run_config = run_local)
script_run = exp.submit(config)
script_run.wait_for_completion(show_output=True)
```

The error I'm getting is very strange and does not help me at all, as a user:

```
Entering context manager injector. Current time:2020-05-14T12:16:22.325243
Starting the daemon thread to refresh tokens in background for process with pid = 20466
Warning: Unable to import azureml.history. Output collection disabled.
Preparing to call script [ script_file.py ] with arguments: []
After variable expansion, calling script [ script_file.py ] with arguments: []



The experiment failed. Finalizing run...
Error occurred when setting run status to Finalizing: 'NoneType' object has no attribute 'get_process_name'
Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 278, in <module>
    execute_with_context(options.inject, options.invocation)
  File "azureml-setup/context_manager_injector.py", line 191, in execute_with_context
    print("Error occurred when setting run status to Finalizing: {}".format(ex))
  File "/private/var/folders/s_/lzy93vds1hz0stvfdr565bdm0000gn/T/azureml_runs/Repo_1589451377_ed72aae1/azureml-setup/utility_context_managers.py", line 152, in __exit__
    end_time = time.time()
AttributeError: 'NoneType' object has no attribute 'time'
```

In general it seems there's a lot of samples that are outdated and it's quite hard to get some very straightforward things working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d94ed89-5c02-627d-be4b-7be85ffeb876
* Version Independent ID: 581b19dc-544c-6a91-fa47-3d582f23a34b
* Content: [azureml.core.workspace.Workspace class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.workspace.workspace?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.workspace.Workspace.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by v-strudm-msft** [comment]
@SamVanhoutte Thanks for your feedback. We're routing this to the appropriate team to follow up.

**Comment by sumitkuml** [comment]
Hi,
Getting same error while trying to start training using custom docker. 
anyone spot a workaround for this?

**Comment by SamVanhoutte** [comment]
I didn't get any of this to work locally, no.  Really hoping for a solution here, @maxluk ?

**Comment by j-martens** [comment]
@sdgilley - who on the PM team would be good here?

**Comment by swanderz** [comment]
what version of the SDK is this on?

**Comment by SamVanhoutte** [comment]
I just retried (have everything wrapped in a custom library, that uses the above code) and it seems to be working without an issue for me now (and I still use the `show_output=True`)

**Comment by chengyu-liu-cs** [comment]
I am also having the same error. I have tried different versions including latest 1.12.0. But the problem remains.

I was running locally

**Comment by mx-iao** [comment]
Let me try to repro and route this to the product team.

**Comment by tailaiw** [comment]
Having the same issue too.

**Comment by swanderz** [comment]
@tailaiw can you share the SDK version you're on and the control plane code (not the training script but how you submit the run)?

**Comment by rdzotz** [comment]
While troubleshooting this error I found it also occurs when running the tutorial [register-model-deploy-local.ipynb](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-to-local/register-model-deploy-local.ipynb)

**Comment by dinaAbdelrahman** [comment]
I am getting same error. I run experiment but not able to get best run

<ipython-input-16-f3ee208d7746> in <module>
      7 #if best_run is None:
      8 #    raise Exception("No best run was found")
----> 9 print(best_run.get_details()['runDefinition']['arguments'])

AttributeError: 'NoneType' object has no attribute 'get_details'

**Comment by paulshealy1** [comment]
@dinaAbdelrahman are you doing local training? Can you share a code snippet to help repro?
