### ISSUE TITLE
Specify which metrics are supported to export to TensorBoard

### ISSUE THREAD

**Issue by zoekdestep** [Azure/MachineLearningNotebooks#973]
In this documentation, it is not specified which metrics are supported to export to TensorBoard. It seems that values (e.g. mse) are supported, but plots or images are not. Would be useful to specify.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db08b8e8-ce5e-1650-b6cb-2cc7fc7f7a23
* Version Independent ID: 29ad8d3f-1fb3-3711-2a5a-e41df8f80ba5
* Content: [azureml.tensorboard.export module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-tensorboard/azureml.tensorboard.export?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-tensorboard/azureml.tensorboard.export.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-tensorboard/azureml.tensorboard.export.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@j-martens please review above feedback for doc enhancement. Thanks.

**Comment by swinner95** [comment]
I created a work item to address this issue (https://msdata.visualstudio.com/Vienna/_workitems/edit/887606). We will update the document with more details.
