### ISSUE TITLE
Dataflow can not work for AML run.

### ISSUE THREAD

**Issue by oo2316oo** [Azure/MachineLearningNotebooks#974]
when we configure dataflow item for AUTOml RUN training data and validation data, it is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acefcd26-56c5-29eb-0399-a05c5aa2b5ff
* Version Independent ID: 3296fba4-71ac-585a-738e-d927eef8087d
* Content: [azureml.dataprep.Dataflow class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-dataprep/azureml.dataprep.dataflow?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-dataprep/azureml.dataprep.Dataflow.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-dataprep/azureml.dataprep.Dataflow.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@RohitMungi-MSFT Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by DebFro** [comment]
@oo2316oo sorry to hear you are having troubles.  Can you please provide additional context as to the steps you are taking and the error you are receiving.

**Comment by j-martens** [comment]
We have not heard back in the last month so we will proceed to close this issue. Please re-open if you still need help. #please-close
