### ISSUE TITLE
[docs] Change X_valid mention in the cv_splits_indices parameter section in SDK Reference and mention validation_data instead

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#975]
Since X,y approach is being deprecated in AutoMLConfig class, change X_valid mention in the cv_splits_indices parameter section and mention validation_data instead.

Current text is:
"
Do not specify cv_splits_indices if specifying split validation data with X_valid. Specify either cv_splits_indices or n_cross_validations, but not both. Similarly, specify either cv_splits_indices or validation_size, but not both.
"

Instead sayin "with X_valid" say "with validation_data".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@CESARDELATORRE Thanks for the feedback. I have assigned the issue to AutoML team to check and make this update.

**Comment by KrishnaG-MSFT** [comment]
@j-martens please review above feedback for doc enhancement. Thanks.

**Comment by j-martens** [comment]
@CESARDELATORRE - did you provide this feedback to marc when you reviewed the package docs? 

cc: @vmagelo

**Comment by CESARDELATORRE** [comment]
I don’t think I did provide this feedback until now. I think we missed that mention in the content.
 
This parameter is an advanced feature that until a recent fix only worked in local runs. In any case I think we missed it in that review weeks ago.

**Comment by j-martens** [comment]
Thank you!
