### ISSUE TITLE
Can not return the inferred horizon values from beer forecasting

### ISSUE THREAD

**Issue by adamthorne** [Azure/MachineLearningNotebooks#976]
In the beer forecasting tutorial it shows how to set up the experiment and then run and score the models but not how to actually produced the predicted values out to the max_horizon.

I tried to call infer directly to do this using the below code but it returns an error KeyError: test_data (even if dates unique and regardless of whether a grain exists)```

from infer import do_rolling_forecast
df_forecast = do_rolling_forecast(fitted_model, X_test, y_test, max_horizon)
```

**Is that an error or should users try a different mechanism to actually show the inferred values out to the horizon?**

**Comment by TravisCragg-MSFT** [comment]
@adamthorne can you post a link to the doc you are referring to?

**Comment by adamthorne** [comment]
> 
> 
> @adamthorne can you post a link to the doc you are referring to?

Travis thanks for response :) 

I'm essentially looking at the beer forecasting tutorial from here: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb

This tutorial returns the scores from the experiments to the summary_df but does not return the actually inferred values within the horizon period. Which is what I'm trying to do by adding on this code:

```
from infer import do_rolling_forecast
df_forecast = do_rolling_forecast(fitted_model, X_test, y_test, max_horizon)
```

Separately I also tried adding the below code for the beer forecasting script but it only returns a forecast up to the end of the test_data not to the horizon...

best_run, fitted_model = remote_run.get_output()
test = test_dataset.to_pandas_dataframe()
X_test = test
y_predictions, X_trans = fitted_model.forecast(X_test)

**Comment by adamthorne** [comment]
On further experimentation now I understand that applying the trained model to test_data is the forecast and it will work up to the dates provided in the time-series in the test_data data frame. 

Leaving this here for future reference of others.
