### ISSUE TITLE
can't run mnist tutorial on remote cluster

### ISSUE THREAD

**Issue by dgcaron** [Azure/MachineLearningNotebooks#981]
i was following the steps on this tutorial:

[https://github.com/Azure/MachineLearningNotebooks/tree/master/tutorials/image-classification-mnist-data](url)

i am unsure how to solve this issue effectively as it looks like the node image is misconfigured for joblib?

--- logs
bash: /azureml-envs/azureml_e43ff11e7e1d0c0598a1a23316061ca3/lib/libtinfo.so.5: no version information available (required by bash)
2020/05/22 09:09:21 Instrumentation Key Is Empty Skipping App Insight Logger
bash: /azureml-envs/azureml_e43ff11e7e1d0c0598a1a23316061ca3/lib/libtinfo.so.5: no version information available (required by bash)
Entering context manager injector. Current time:2020-05-22T09:09:23.265131
Initialize DatasetContextManager.
Starting the daemon thread to refresh tokens in background for process with pid = 101
Set Dataset mnist_opendataset's target path to /tmp/tmp9wru_xzz
Enter __enter__ of DatasetContextManager
Processing 'mnist_opendataset'
Processing dataset FileDataset
{
  "source": [
    "https://azureopendatastorage.blob.core.windows.net/mnist/**/*.gz"
  ],
  "definition": [
    "GetFiles"
  ],
  "registration": {
    "id": "51bff131-b63f-4074-987c-27d7315814e0",
    "name": "mnist_opendataset",
    "version": 1,
    "description": "training and test dataset",
    "workspace": "Workspace.create(name='..', subscription_id='..', resource_group='..')"
  }
}
Mounting mnist_opendataset to /tmp/tmp9wru_xzz
Mounted mnist_opendataset to /tmp/tmp9wru_xzz
Exit __enter__ of DatasetContextManager
Entering Run History Context Manager.
Preparing to call script [ train.py ] with arguments: ['--data-folder', '$mnist_opendataset', '--regularization', '0.5']
After variable expansion, calling script [ train.py ] with arguments: ['--data-folder', '/tmp/tmp9wru_xzz', '--regularization', '0.5']

Starting the daemon thread to refresh tokens in background for process with pid = 101

The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.000827789306640625 seconds
Enter __exit__ of DatasetContextManager
Unmounting /tmp/tmp9wru_xzz.
Finishing unmounting /tmp/tmp9wru_xzz.
Exit __exit__ of DatasetContextManager
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib'

2020/05/22 09:09:55 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2020/05/22 09:09:55 MPI publisher: intel ; version: 2018

**Comment by GiftA-MSFT** [comment]
@dgcaron we will review your feedback and get back to you shortly.

@maxluk can you please help looking into this issue

**Comment by vizhur** [comment]
@dgcaron scikit-learn deprecated vendored joblib starting 0.23. either downgrade scikit-learn by pinning upperbound to <0.23 or add joblib into environment and replace failing line with import joblib

**Comment by dgcaron** [comment]
ok, thanks for the feedback!
