### ISSUE TITLE
Failed to Build Deployment Environment - Possibly CUDA related

### ISSUE THREAD

**Issue by cmsimpson31** [Azure/MachineLearningNotebooks#983]
Hello, I'm getting an error that's beyond me. This occurs when running running Model.deploy. My .yml file is quite simple:
 
name: deploy
dependencies:
  - python=3.6.0
  - azureml-defaults
  - azureml-sdk
  - tensorflow=2.2

Error logs below......
2020/05/24 04:28:30 Downloading source code...
2020/05/24 04:28:31 Finished downloading source code
2020/05/24 04:28:32 Creating Docker network: acb_default_network, driver: 'bridge'
2020/05/24 04:28:32 Successfully set up Docker network: acb_default_network
2020/05/24 04:28:32 Setting up Docker configuration...
2020/05/24 04:28:33 Successfully set up Docker configuration
2020/05/24 04:28:33 Logging in to registry: iobotanymlwo0c1a5dcf.azurecr.io
2020/05/24 04:28:34 Successfully logged into iobotanymlwo0c1a5dcf.azurecr.io
2020/05/24 04:28:34 Executing step ID: acb_step_0. Timeout(sec): 5400, Working directory: '', Network: 'acb_default_network'
2020/05/24 04:28:34 Scanning for dependencies...
2020/05/24 04:28:35 Successfully scanned dependencies
2020/05/24 04:28:35 Launching container with name: acb_step_0
Sending build context to Docker daemon  60.93kB

Step 1/15 : FROM mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04@sha256:a1b514f3ba884b9a7695cbba5638933ddaf222e8ce3e8c81e8cdf861679abb05
sha256:a1b514f3ba884b9a7695cbba5638933ddaf222e8ce3e8c81e8cdf861679abb05: Pulling from azureml/base
Digest: sha256:a1b514f3ba884b9a7695cbba5638933ddaf222e8ce3e8c81e8cdf861679abb05
Status: Downloaded newer image for mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04@sha256:a1b514f3ba884b9a7695cbba5638933ddaf222e8ce3e8c81e8cdf861679abb05
 ---> 93a72e6bd1ce
Step 2/15 : USER root
 ---> Running in 4c364ae3d8e1
Removing intermediate container 4c364ae3d8e1
 ---> b782a4c10199
Step 3/15 : RUN mkdir -p $HOME/.cache
 ---> Running in 0abb1d7f2626
Removing intermediate container 0abb1d7f2626
 ---> 4ff6c38eaf44
Step 4/15 : WORKDIR /
 ---> Running in 7793e4d21759
Removing intermediate container 7793e4d21759
 ---> 9df8cf128de8
Step 5/15 : COPY azureml-environment-setup/99brokenproxy /etc/apt/apt.conf.d/
 ---> 83429e3f1301
Step 6/15 : RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.11; then conda install conda==4.4.11; fi
 ---> Running in 55a4018d01b7
Removing intermediate container 55a4018d01b7
 ---> 09c3f76a8086
Step 7/15 : COPY azureml-environment-setup/mutated_conda_dependencies.yml azureml-environment-setup/mutated_conda_dependencies.yml
 ---> d39feb1a00d6
Step 8/15 : RUN ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_8ae5b90a8bae2a252476369dd3bb1b16 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig
 ---> Running in 1141cbf275cf
Solving environment: ...working... failed
[91m
ResolvePackageNotFound: 
  - azureml-defaults
  - tensorflow=2.2
  - azureml-sdk

[0mThe command '/bin/sh -c ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_8ae5b90a8bae2a252476369dd3bb1b16 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig' returned a non-zero code: 1
2020/05/24 04:29:00 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: cf2 failed after 32s. Error: failed during run, err: exit status 1

**Comment by BharathNimmala-MSFT** [comment]
@cmsimpson31  Thank you for reaching out , can you please share the documentation link which you are referring, which would help our team to route you accordingly.

**Comment by cmsimpson31** [comment]
Thanks for looking into it! :)

This link should produce the same error message.

https://iobotanymlwork2011288214.blob.core.windows.net/azureml/ImageLogs/7318187b-cda2-40fe-9982-172bf51dbc8a/build.log?sv=2018-03-28&sr=b&sig=QZEqTrQdan5%2BRKnAG8rn6tk4swwJt63zxucthSqgLUQ%3D&st=2020-05-24T23%3A47%3A08Z&se=2020-05-25T07%3A52%3A08Z&sp=r

best,
Cory

**Comment by vizhur** [comment]
@cmsimpson31 from what I see from the logs, you have azureml dependencies in conda section. AzureML Python SDK is available on PyPI only. Please update your environment to

dependencies:
-python=3.6
-tensorflow=2.2
-pip:
 -azureml-defaults

please consider to avoid using azureml-sdk metapackage in your environments and reference packages you need. List of the packages and reference documentation is available here 
https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py

**Comment by Mike-Ubezzi-MSFT** [comment]
@cmsimpson31 
We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by cmsimpson31** [comment]
Thanks all!!!
