### ISSUE TITLE
Missing documentation on get_model_path method behaviour when _workspace=None

### ISSUE THREAD

**Issue by szonp** [Azure/MachineLearningNotebooks#985]
Example code

```
model = Model(ws, name='model_name')
model_path = model.get_model_path('model_name')
```

Obtaining model path using **get_model_path** method without giving it **_workspace** parameter limits the search for a model to local cache only. This behaviour is not documented and is a bit misleading, since model object has been created with reference to the workspace (**ws**).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1517f63f-2d2e-1539-060e-0a471c1c438a
* Version Independent ID: 9e466042-1059-b835-8c92-01e9d9858166
* Content: [azureml.core.model.Model class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by RohitMungi-MSFT** [comment]
@szonp Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by j-martens** [comment]
@vmagelo - did this get reviewed as part of core?

**Comment by vmagelo** [comment]
Yes, but that was missed. Thank @szonp for the feedback. We updated the docs. Change will appear in next release in a few days.
