### ISSUE TITLE
"enable_dnn" parameter is not listed in the reference for AutoMLConfig() function

### ISSUE THREAD

**Issue by BreakingBI** [Azure/MachineLearningNotebooks#986]
[Enter feedback here]

The "enable_dnn" parameter is specifically leveraged in a number of examples, but isn't present in the function documentation.  It's unclear how this should be leveraged or what exactly it does, if anything.  This makes it difficult to understand why DNN's don't appear in the AutoML run results.

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.ipynb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc2b21e-6b1a-cb94-2857-147177a29d7c
* Version Independent ID: d14620a6-a2f6-49f1-632e-73903d41de8c
* Content: [azureml.train.automl.automlconfig.AutoMLConfig class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.automlconfig.AutoMLConfig.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@BreakingBI we will review your feedback and get back to you shortly. Thanks.

@Aniththa can you please review the above feedback? Thanks.

**Comment by Aniththa** [comment]
@BreakingBI Thanks for the feedback. We will work on exposing it in API docs. As you correctly mention, currently user facing notebooks have this flag available but yes it should be part of the API docs soon.

**Comment by Aniththa** [comment]
@GiftA-MSFT this can be marked as resolved.

**Comment by GiftA-MSFT** [comment]
Thanks @Aniththa. Will proceed to close.
