### ISSUE TITLE
Depracated Tensorflow Models should be labeled as such

### ISSUE THREAD

**Issue by BreakingBI** [Azure/MachineLearningNotebooks#987]
[Enter feedback here]

In the Azure ML Python SDK Reference Guide, we list all of the supported AutoML models.  The Classification and Regression pages mention Tensorflow models.  These models appear to be implicitly black-listed, even though they do not appear in the list of Blacklisted models in Azure ML Studio.  If these are depracated, please update these documentation pages to reflect this.

https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.constants.supportedmodels.classification?view=azure-ml-py

https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.constants.supportedmodels.classification?view=azure-ml-py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9deb6087-5a6c-d2a3-0084-c4c6e5ce243e
* Version Independent ID: b71af4bf-9104-436c-06bb-6a52aa99df59
* Content: [azureml.train.automl.constants.SupportedModels.Classification class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.constants.supportedmodels.classification?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.constants.SupportedModels.Classification.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-automl-client/azureml.train.automl.constants.SupportedModels.Classification.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@CESARDELATORRE - would you be able to  confirm the expected state of these please? Or tell us who can? Thank you!!

**Comment by j-martens** [comment]
@BreakingBI - I see only one link here (copied twice). Did you mean to share 2 different links?

**Comment by BreakingBI** [comment]
My apologies.  The second link was supposed to be to the regression page.

https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.constants.supportedmodels.regression?view=azure-ml-py

**Comment by CESARDELATORRE** [comment]
@j-martens - The feedback provided is right. The TensorFlow models are currently not used unless whitelisted. In the upcoming releases those TF models will be removed, too.

Hence, those reference pages above should be updated plus this additional page where we're still listing the TF models (DNN based):

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-train#select-your-experiment-type

![image](https://user-images.githubusercontent.com/1712635/83173958-81d2bb80-a0ce-11ea-8c88-b22eaf75686e.png)

We should probably remove them from the docs, already.

Adding @rtanase to confirm.

**Comment by Karishma-Tiwari-MSFT** [comment]
Test

**Comment by j-martens** [comment]
@nibaccam

**Comment by nibaccam** [comment]
@BreakingBI Thank you for reporting this issue. The documents have been updated and the changes will be published in the next release cycle. @j-martens @PeterCLu please close this issue
