### ISSUE TITLE
OJ Forecasting Example Notebook uses Unsupported Parameter in AutoMLConfig

### ISSUE THREAD

**Issue by BreakingBI** [Azure/MachineLearningNotebooks#988]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-orange-juice-sales/auto-ml-forecasting-orange-juice-sales.ipynb

For the OJ Forecasting Example Notebook, we receive the following error when we submit the experiment.

WARNING - Received unrecognized parameter: experiment_timeout_hours 0.25

This parameter is explicitly listed in the AutoMLConfig documentation.

https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.automlconfig.automlconfig?view=azure-ml-py

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by GiftA-MSFT** [comment]
@BreakingBI I can confirm a successful submission. Can you try again, it could be an intermittent issue or issue with your set up? Refer to my response [here](https://github.com/Azure/MachineLearningNotebooks/issues/989) as well.
