### ISSUE TITLE
Fatal Error in AutoML OJ Forecast Example Notebook when Forecasting Test Data

### ISSUE THREAD

**Issue by BreakingBI** [Azure/MachineLearningNotebooks#989]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-orange-juice-sales/auto-ml-forecasting-orange-juice-sales.ipynb

For the OJ Forecasting Example Notebook, we receive the following error when we attempt to run the following code:

**CODE START**

y_predictions, X_trans = fitted_model.forecast(X_test)

**CODE END**
**OUTPUT START**

---------------------------------------------------------------------------
InvalidTsdfArgument                       Traceback (most recent call last)
<ipython-input-23-b2cbed066f3c> in <module>
      2 # This contains the assumptions that were made in the forecast
      3 # and helps align the forecast to the original data
----> 4 y_predictions, X_trans = fitted_model.forecast(X_test)

~/anaconda3_501/lib/python3.6/site-packages/azureml/automl/core/_vendor/automl/client/core/runtime/model_wrappers.py in forecast(self, X_pred, y_pred, forecast_destination, ignore_data_errors)
   2575         :rtype: tuple
   2576         """
-> 2577         self._check_data(X_pred, y_pred, forecast_destination)
   2578         # Make sure that we have a data frame in both cases: when user provided X_pred and y_pred
   2579         # or forecast_destination

~/anaconda3_501/lib/python3.6/site-packages/azureml/automl/core/_vendor/automl/client/core/runtime/model_wrappers.py in _check_data(self, X_pred, y_pred, forecast_destination)
   2316         if (X_pred is None) != (y_pred is None):
   2317             # If user provided only one of  X_pred or y_pred raise the error.
-> 2318             raise InvalidTsdfArgument(ForecastingPipelineWrapper.FATAL_X_Y_XOR)
   2319 
   2320     def _check_max_horizon_and_grain(self, grain_tuple: Tuple[Any],

InvalidTsdfArgument: InvalidTsdfArgument:
	Message: X_pred and y_pred should both be None or both not None.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "ValidationError",
        "inner_error": {
            "code": "BadArgument"
        },
        "message": "X_pred and y_pred should both be None or both not None."
    }
}

**OUTPUT END**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by GiftA-MSFT** [comment]
@BreakingBI I was able to run the notebook successfully. Please check result of prior steps.

![image](https://user-images.githubusercontent.com/51332022/83707071-267d5d80-a5e7-11ea-9a30-b0f6d21a3fa9.png)
![image](https://user-images.githubusercontent.com/51332022/83707125-3eed7800-a5e7-11ea-84dd-cf295fb5dadb.png)

**Comment by GiftA-MSFT** [comment]
Will proceed to close this thread but feel free to comment below if you have updates or would like the thread to be reopened. Thanks.
