### ISSUE TITLE
parameters appear malformed

### ISSUE THREAD

**Issue by gvashishtha** [Azure/MachineLearningNotebooks#990]
The parameters for this class appear malformed on the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff1a3c8d-b8f9-e935-d60d-af2ff641d238
* Version Independent ID: c019227e-b16c-b5b9-d737-b8b7cc5339d9
* Content: [azureml.core.compute.computeinstance.ComputeInstanceStatus class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.computeinstance.computeinstancestatus?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.compute.computeinstance.ComputeInstanceStatus.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.compute.computeinstance.ComputeInstanceStatus.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by MarileeTurscak-MSFT** [comment]
@j-martens 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by vmagelo** [comment]
This was addressed; changes will appear live in next release in a few days. Thanks!
