### ISSUE TITLE
Apex support

### ISSUE THREAD

**Issue by jonrbates** [Azure/MachineLearningNotebooks#991]
How can I add Apex (ie. FP16) to a pytorch estimator?  
https://github.com/NVIDIA/apex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb892243-d2f3-79a1-4061-b2d46235aff4
* Version Independent ID: a6e4c4ab-3665-c0d3-65ff-abc5cbb0b835
* Content: [azureml.train.dnn.PyTorch class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.pytorch?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by SaurabhSharma-MSFT** [comment]
@jonrbates Thanks for your feedback! We will investigate and update as appropriate.

**Comment by GiftA-MSFT** [comment]
@Aniththa can you please review above feedback. Do we currently support or have plans to support APEX?

**Comment by mx-iao** [comment]
@jonrbates If you want to use Apex for training, you will have to build a custom Docker image that includes Nvidia Apex, create an Azure ML Environment for the image (see [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-environments#use-a-custom-docker-image-or-dockerfile)), and pass that into the `environment_definition` parameter of the PyTorch estimator.
