### ISSUE TITLE
using pytorch 1.5 problem

### ISSUE THREAD

**Issue by leoxiaobin** [Azure/MachineLearningNotebooks#994]
[Enter feedback here]
When I set framework_version=1.5 in Pytorch Estimator. After submitting the job, it shows an error that "UserError: Unable to get image details : Specified base docker image pytorch:1.5-gpu not found". 

When I want to use pytorch 1.5, do I need to do any other configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb892243-d2f3-79a1-4061-b2d46235aff4
* Version Independent ID: a6e4c4ab-3665-c0d3-65ff-abc5cbb0b835
* Content: [azureml.train.dnn.PyTorch class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.pytorch?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-train-core/azureml.train.dnn.PyTorch.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **jmartens**

**Comment by MarileeTurscak-MSFT** [comment]
@leoxiaobin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by GiftA-MSFT** [comment]
@leoxiaobin I tried running this [sample](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/pytorch/deployment/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb) and specified "framework_version=1.5" without errors.
![image](https://user-images.githubusercontent.com/51332022/84065572-92b6e300-a992-11ea-9d10-caa8ce4fd9f6.png)

**Comment by leoxiaobin** [comment]
@GiftA-MSFT , I have tried again, however I still get the same error information. could you me any advice about how to debug it?

**Comment by GiftA-MSFT** [comment]
@leoxiaobin did you try the sample notebook I provided above? Can you describe your development environment and resource location? Please share your estimator configurations if possible. Ensure that you have created a **gpu enabled compute cluster** and specified `use_gpu=True` in your estimator. Here's another [documentation/sample](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-pytorch) that you can reference.

**Comment by GiftA-MSFT** [comment]
Will proceed to close this issue, but feel free to comment below if you are still experiencing issues and need it reopened. Thanks.
