### ISSUE TITLE
More than just Azure VM's can use Managed Identity for auth

### ISSUE THREAD

**Issue by a30001539** [Azure/MachineLearningNotebooks#999]
Update to say Managed Identity is supported on Azure Functions and Azure Data Factory too, or any Azure service that supports the AzureML Python SDK and Managed Identity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeee5fbb-56db-817e-f095-928ea13e478e
* Version Independent ID: 10f2c77a-1dd7-29bb-7e04-c57885c39813
* Content: [azureml.core.authentication.MsiAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.msiauthentication?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.MsiAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.core.authentication.MsiAuthentication.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **jmartens**

**Comment by GiftA-MSFT** [comment]
@j-martens @DebFro can you please review above feedback for doc enhancement? Thanks.

**Comment by j-martens** [comment]
@vmagelo for core

**Comment by j-martens** [comment]
@Blackmist & @aashishb thoughts?

**Comment by aashishb** [comment]
@rastala can you check?

**Comment by rastala** [comment]
It's correct, but the main use case is auth from client VM, such as DSVM, to Workspace.
